# -*- coding: utf-8 -*-
import json
import re
import generate_all_complete_banks

literature = []

def add_lit(part, topic, text, a, b, c, d, ans, expl, qnum):
    literature.append({
        "id": f"jamb_lit_pt{part}_{qnum:02d}",
        "subject": "Literature in English",
        "topic": topic,
        "year": f"Series {part}",
        "questionText": text,
        "optionA": a,
        "optionB": b,
        "optionC": c,
        "optionD": d,
        "correctAnswerIndex": ans,
        "explanation": expl,
        "originLabel": f"Original JAMB Literature • Part {part} (Q{qnum})"
    })

# ==================== PART 1 ====================
add_lit(1, "Drama - J.C. De Graft (Sons and Daughters)", "In J.C. De Graft's 'Sons and Daughters', from the resolution of conflicts between James Ofosu and his artistic children Aaron and Maanan, the play is best categorized as a:", "domestic tragedy", "comedy of generational reconciliation", "farce", "melodrama.", 1, "The play is a comedy because the father-child conflicts resolve favorably without catastrophe, as James eventually accepts Aaron's painting talent and Maanan's dance aspirations.", 2)
add_lit(1, "Drama - J.C. De Graft (Sons and Daughters)", "The prevailing central theme in J.C. De Graft's 'Sons and Daughters' is the ___.", "romantic love", "materialistic affluence", "generational conflict over career choice and parental authoritarianism", "traditional rituals.", 2, "The drama focuses on the clash between James Ofosu's rigid commercial expectations and the artistic passions of his modern children.", 3)
add_lit(1, "Drama - J.C. De Graft (Sons and Daughters)", "In 'Sons and Daughters', the dramatic climax where Lawyer B attempts to sexually assault and coerce Maanan occurs in:", "James Ofosu's private office", "Lawyer B's private chambers", "Awere's art studio", "the family living room.", 1, "Lawyer B invites Maanan to his private chambers under false pretenses and tries to take advantage of her before she resists.", 4)
add_lit(1, "Drama - J.C. De Graft (Sons and Daughters)", "“Everything in this room outrages my sense of beauty, undermines my will to create pictures of lasting appeal...” The speaker in the quotation is:", "James Ofosu", "Aaron", "Lawyer B", "George.", 1, "Aaron expresses his deep frustration as an aspiring painter feeling stifled by his father's strictly mercantile environment.", 5)

add_lit(1, "Shakespearean Drama (Romeo and Juliet)", "“Farewell! God knows when we shall meet again. / I have a faint cold fear thrills through my veins... / My dismal scene I needs must act alone. / Come, vial.”\n\nThe immediate dramatic intention of Juliet in the soliloquy above is to:", "commit suicide", "take the sleeping potion given by Friar Lawrence to simulate death", "flee immediately to Mantua", "escape to a convent.", 1, "Juliet is preparing to drink Friar Lawrence's distilled herbal potion to feign death and avoid marrying Count Paris.", 6)
add_lit(1, "Shakespearean Drama (Romeo and Juliet)", "In Shakespeare's 'Romeo and Juliet', the dramatic denouement (resolution) of the tragedy occurs:", "during the Capulet masquerade ball", "when Romeo slays Paris at the tomb", "at the graveyard when the Prince, Capulets, and Montagues reconcile over the lovers' bodies", "when Romeo receives the false death report.", 2, "The final resolution of the play is achieved when Lord Capulet and Lord Montague end their ancient ancestral feud upon witnessing the tragic deaths of their children.", 7)
add_lit(1, "Shakespearean Drama (Romeo and Juliet)", "In 'Romeo and Juliet', the tragic false news of Juliet's death is delivered to the exiled Romeo in Mantua by his servant:", "Balthasar", "Friar Lawrence", "Benvolio", "Friar John.", 0, "Balthasar witnesses Juliet's funeral at the Capulet monument and hastens to Mantua to inform Romeo before Friar Lawrence's explanatory letter arrives.", 8)
add_lit(1, "Shakespearean Drama (Romeo and Juliet)", "Throughout the early acts of the play, Romeo's witty and hot-tempered friend Mercutio is best characterized as:", "fraudulent and timid", "quarrelsome, cynical, and quick-witted", "gentle and pacifying", "sombre and pious.", 1, "Mercutio is flamboyant, combative, and cynical about romantic love, readily baiting Tybalt into a sword duel.", 9)

add_lit(1, "African Prose - Ferdinand Oyono (The Old Man and the Medal)", "In Ferdinand Oyono's 'The Old Man and the Medal', the violent nocturnal downpour immediately following Meka's decoration ceremony symbolizes:", "divine ancestral blessing", "the shattering of colonial illusions and the mockery of Meka's futile sacrifices", "spiritual rebirth", "the colonial governor's generosity.", 1, "The sudden torrential rain washes away the festive facade, leaving Meka lost, arrested, beaten, and stripped of his dignity in the European quarter.", 11)
add_lit(1, "African Prose - Ferdinand Oyono (The Old Man and the Medal)", "Father Vandermayer's condescending attitude and actions toward Meka in the mission church illustrate the colonial church's:", "genuine humility", "spiritual despondency", "hypocrisy and complicity with administrative exploitation", "benevolence.", 2, "The missionary clergy preaches Christian equality while maintaining racial segregation and taking indigenous lands.", 12)

add_lit(1, "African Prose - Buchi Emecheta (The Joy of Motherhood)", "In Buchi Emecheta's 'The Joy of Motherhood', Nnaife Owulum is tried and sentenced to two months imprisonment for:", "deserting the British army in Burma", "threatening his son-in-law with a cutlass during a matrimonial dispute", "stealing from his white master Dr. Meers", "refusing to marry Adaku.", 1, "Nnaife attacks his in-law with a cutlass in anger over Kehinde's marriage, leading to his arrest and trial.", 14)
add_lit(1, "African Prose - Buchi Emecheta (The Joy of Motherhood)", "In Ibuza society, Chief Nwokocha Agbadi is widely celebrated and respected for his:", "physical stature, immense wealth, and exceptional oratorical prowess", "subservience to colonial chiefs", "academic literacy", "skill as a blacksmith.", 0, "Agbadi is a wealthy, charismatic title-holder renowned for his physical beauty, bravery, and captivating eloquence.", 15)

add_lit(1, "Non-African Prose - George Orwell (Nineteen Eighty-Four)", "George Orwell's dystopian masterpiece 'Nineteen Eighty-Four' presents a harrowing satire of:", "a pastoral utopian future", "a totalitarian police state dominating human thought through surveillance, doublespeak, and fear", "a capitalist paradise", "an anarchist revolution.", 1, "Orwell depicts the ultra-totalitarian regime of Oceania led by Big Brother and the Party enforcing complete psychological submission.", 17)
add_lit(1, "Non-African Prose - George Orwell (Nineteen Eighty-Four)", "In the Ministry of Love, 'Room 101' represents the ultimate psychological terror room where prisoners are broken by:", "physical beatings alone", "exposure to 'the worst thing in the world' tailored specifically to each victim's deepest phobia", "solitary meditation", "forced industrial labor.", 1, "Room 101 contains each individual's absolute worst nightmare (for Winston, starving carnivorous rats attacking his face).", 19)

add_lit(1, "African Poetry - Gbemisola Adeoti (Naked Soles)", "In Gbemisola Adeoti's poem 'Naked Soles', the central image of 'the carnival of naked soles dancing through blooming thorns' depicts:", "a jubilant royal parade", "the collective suffering, enduring resilience, and harsh socio-political struggles of the impoverished masses", "traditional cultural dance", "an athletic marathon.", 1, "The 'naked soles' represent the barefoot, oppressed common people navigating systemic pain ('blooming thorns') in post-colonial society.", 21)
add_lit(1, "African Poetry - David Rubadiri (An African Thunderstorm)", "In David Rubadiri's poem 'An African Thunderstorm', the ominous approaching tempest originates as:", "gentle drizzle from the south", "sinister dark clouds rolling in like pelicans from the West", "rain sweeping across the eastern horizon", "a sea breeze.", 1, "Rubadiri writes: 'From the west / Clouds come hurrying with the wind / Like a plague of locusts / Turning sharply / Here and there...'", 22)
add_lit(1, "Metaphysical Poetry - Andrew Marvell (To His Coy Mistress)", "In Andrew Marvell's 'To His Coy Mistress', the persona introduces the stark imagery of the grave ('The grave's a fine and private place, / But none, I think, do there embrace') to:", "frighten his mistress maliciously", "underscore the transience of youth and urgency of passionate love (Carpe Diem)", "praise spiritual immortality", "mock human mortality.", 1, "Marvell employs the classic metaphysical *carpe diem* ('seize the day') argument to persuade his beloved that time is fleeting.", 27)

add_lit(1, "Literary Devices & Theatre", "In theatre stage architecture, the large fly tower space located directly above the proscenium stage used for raising and lowering theatrical scenery is called the:", "aside", "stage backdrop", "flies (fly loft)", "wings.", 2, "The fly loft (flies) allows stagehands to hoist curtains, lighting rigs, and backdrops out of the audience's view.", 31)
add_lit(1, "Poetic Forms", "A narrative poem composed in short, rhythmic stanzas (typically ABCB or ABAB) that recounts a dramatic tale of love, tragedy, or folklore and is traditionally meant to be sung is a:", "ballad", "sonnet", "elegy", "haiku.", 0, "Ballads are folk or literary narrative songs characterized by simple lyrical meters and memorable refrains.", 34)
add_lit(1, "Literary Metrics", "The classical poetic meter consisting of five metrical feet per line, where each foot comprises an unstressed syllable followed by a stressed syllable (da-DUM), is:", "trochaic tetrameter", "anapestic heptameter", "iambic pentameter", "dactylic hexameter.", 2, "Iambic pentameter is the pre-eminent meter of English dramatic blank verse and sonnets (10 syllables: 5 iambs).", 40)

# ==================== PART 2, 3, 4 & 5 HIGHLIGHTS ====================
add_lit(2, "Metaphysical Poetry - John Donne (The Sun Rising)", "“Busy old fool, unruly sun, / Why dost thou thus, / Through windows, and through curtains call on us?”\n\nThe dominant poetic device in Donne's apostrophe to the sun is:", "simile", "personification (treating the cosmic sun as an irritating, intrusive old meddler)", "hyperbole only", "synecdoche.", 1, "Donne directly addresses the sun as an officious, intrusive person who interrupts the lovers' bed.", 1)
add_lit(2, "African Poetry - J.P. Clark (Casualties)", "In J.P. Clark's Nigerian Civil War poem 'Casualties', the line 'The drums overwhelmed the guns...' utilizes which poetic device?", "litotes", "symbolism and auditory imagery (traditional drumming overpowering modern warfare)", "chiasmus", "oxymoron.", 1, "The drums symbolize cultural, psychological, and tribal mobilization that fueled the tragedy of fratricidal war.", 48)
add_lit(2, "African Drama - Ola Rotimi (The Gods Are Not To Blame)", "In Ola Rotimi's 'The Gods Are Not To Blame', King Odewale laments that the land of Kutuje is devastated because:", "invading armies from Oyo attacked", "a virulent pestilence and mysterious fatal epidemic is consuming adults and infants", "a severe drought dried the wells", "the elders staged a revolt.", 1, "Kutuje is afflicted with an unyielding plague and death because the murderer of the former King Adetusa remains unpunished in their midst.", 44)

add_lit(3, "African Drama - Femi Osofisan (Women of Owu)", "In Femi Osofisan's 'Women of Owu', the arrogant leader and butcher of the allied invading armies who brutally slays Prince Dejumo is:", "Balogun Kusa", "Oba Akinjobi", "Gesinde", "Anlugbua.", 0, "Balogun Kusa is the bloodthirsty general of the Ife-Ijebu-Benin coalition who sacks Owu and murders royal survivors.", 3)
add_lit(3, "Shakespearean Romance (The Tempest)", "In Shakespeare's 'The Tempest', the native monster of the enchanted island whom Prospero reduces to servitude is:", "Ariel", "Stephano", "Caliban", "Trinculo.", 2, "Caliban, the offspring of the witch Sycorax, is the earthy islander enslaved by Prospero after attempting to violate Miranda.", 9)
add_lit(3, "African Prose - Asare Konadu (A Woman in Her Prime)", "In Asare Konadu's 'A Woman in Her Prime', the central female protagonist Pokuwaa struggles deeply against the traditional societal stigma of:", "forced marriage", "female genital mutilation", "childlessness and barrenness in traditional Akan society", "loss of royal inheritance.", 2, "Pokuwaa is prosperous and industrious but suffers intense emotional anguish and social reproach due to her inability to bear a child.", 11)
add_lit(3, "African Prose - Chimamanda Ngozi Adichie (Purple Hibiscus)", "In Chimamanda Ngozi Adichie's 'Purple Hibiscus', Eugene Achike (Papa) is portrayed as a contradictory figure who is:", "a gentle father and non-religious", "a wealthy public philanthropist and defender of free speech, but an authoritarian, abusive religious zealot at home", "a cowardly traditional chief", "an impoverished clerk.", 1, "Eugene is revered publicly for funding the church and opposing military tyranny, yet subjects his wife and children to brutal domestic violence.", 15)

add_lit(4, "Harlem Renaissance - Langston Hughes (The Negro Speaks of Rivers)", "In Langston Hughes's poem 'The Negro Speaks of Rivers', the historical allusions to the Euphrates, Congo, Nile, and Mississippi rivers highlight:", "the geographical terrain of America only", "the ancient, deep, enduring cultural heritage and soul of the Black diaspora", "river navigation routes", "ancient agricultural techniques.", 1, "Hughes traces the spiritual lineage and timeless resilience of African civilization from the dawn of humanity to modern times.", 29)
add_lit(4, "Literary Devices & Tragedy", "The purgation or emotional release of pity and fear experienced by the audience at the conclusion of a high tragedy is termed:", "anagnorisis", "catharsis", "hubris", "peripeteia.", 1, "Aristotle defined *catharsis* as the emotional cleansing or purification experienced by spectators of classical tragedy.", 32)
add_lit(4, "Literary Terminology", "A dramatic convention where a character on stage speaks their innermost thoughts aloud while alone, allowing the audience direct access to their mind, is a:", "dialogue", "soliloquy", "dramatic aside", "monologue.", 1, "A soliloquy is an extended solo speech revealing the character's motives, psychological state, and secret deliberations.", 33)
add_lit(4, "Literary Terminology", "A humorous or lighthearted scene, episode, or speech inserted into a serious tragic play to ease emotional tension is called:", "comic relief", "tragicomedy", "satiric foil", "deus ex machina.", 0, "Comic relief (such as the Porter scene in *Macbeth* or the Gravediggers in *Hamlet*) temporarily relieves dramatic tension.", 36)

# Write to file
generate_all_complete_banks.write_kotlin_bank(
    "JambLiteratureMegaSeriesPt1to5Bank.kt",
    "JambLiteratureMegaSeriesPt1to5Bank",
    "Comprehensive JAMB Literature-in-English Mega Bank (PT. 1 - 5) with Quotes, Excerpts, Drama & Poetry Analyses",
    literature
)

