# -*- coding: utf-8 -*-
import os

def generate_geography():
    # 81 questions from PDF JAMB Geography 2015
    # Answers mapping from pages 44-59:
    # 1. D, 2. D, 3. C, 4. B, 5. D, 6. C, 7. A, 8. A, 9. B, 10. A
    # 11. B, 12. D, 13. A, 14. B, 15. C, 16. A, 17. A, 18. D, 19. B, 20. D
    # 21. D, 22. A, 23. C, 24. A, 25. C, 26. B, 27. D, 28. B, 29. D, 30. B
    # 31. B, 32. C, 33. D, 34. A, 35. A, 36. B, 37. B, 38. B, 39. B, 40. A
    # 41. A, 42. D, 43. C, 44. B, 45. A, 46. A, 47. B, 48. D, 49. D, 50. B
    # 51. A, 52. C, 53. D, 54. D, 55. D, 56. D, 57. B, 58. D, 59. B, 60. C
    # 61. D, 62. C, 63. C, 64. D, 65. B, 66. D, 67. A, 68. D, 69. C, 70. D
    # 71. B, 72. A, 73. A, 74. C, 75. B, 76. A, 77. C, 78. B, 79. D, 80. D, 81. B

    geo_raw = [
        (1, "The following are natural resources except", "rubber", "soil", "water", "cellophane", 3, "Cellophane is a synthetic man-made polymer packaging material, not a naturally occurring resource like soil, water, or rubber."),
        (2, "All these are examples of fold mountains except", "Himalayas", "Rockies", "Andes", "Vosges Mountain", 3, "Vosges Mountain in France is a block (horst) mountain formed by faulting, whereas Himalayas, Rockies, and Andes are fold mountains."),
        (3, "All the following are fertile plains except", "loess plains", "alluvial plains", "erosional plains", "flood plain", 2, "Erosional plains are formed by denudation which washes away fertile topsoil, exposing rock or infertile subsoil."),
        (4, "The current world population is estimated at about", "2.0 billion", "7.0 billion", "6.0 billion", "4.0 billion", 1, "The global human population exceeded 7.0 billion people (approaching ~7.3+ billion during this period)."),
        (5, "Soil factor in an ecosystem is referred to as", "topographic", "climatic", "biotic", "edaphic", 3, "Edaphic factors refer specifically to the physical and chemical properties of soil influencing organisms."),
        (6, "Alternating wet and dry seasons on rocks is associated with", "chemical weathering", "biological weathering", "physical weathering", "mass movement", 2, "Alternating wetting and drying causes expansion and contraction stresses in rocks, leading to physical/mechanical weathering."),
        (7, "The axis of the earth is inclined to the plane of the ecliptic at an angle of", "66.5°", "23.5°", "90.0°", "45.0°", 0, "The earth's axis of rotation is tilted at 66.5° to the plane of the ecliptic (or 23.5° from the perpendicular)."),
        (8, "West Africa is located between latitudes", "4° N and 20° N", "3° N and 15° N", "2° N and 10° N", "10° N and 15° N", 0, "West Africa spans geographically from approximately latitude 4° N to 20° N of the equator."),
        (9, "All the following crops are involved in plantation agriculture except", "rubber", "wheat", "cocoa", "oil palm", 1, "Wheat is an annual cereal crop grown in temperate grasslands/arable fields, unlike perennial cash crops in tropical plantations."),
        (10, "In a food chain, the position occupied by an organism is called", "the trophic level", "energy level", "the feeding level", "the habitat level", 0, "A trophic level denotes the sequential feeding position occupied by an organism in an ecological food chain."),
        (11, "Tropical rain forest can be conserved by the following practices except", "agroforestry", "deforestation", "shifting cultivation control", "crop rotation", 1, "Deforestation (indiscriminate tree felling) destroys forest ecosystems and accelerates biodiversity loss."),
        (12, "Population growth rate may be defined as the", "mortality rate per unit area over a period", "number of times an organism occurs within a given period", "number of particular species per unit area", "net rate of population change per unit area over a period", 3, "Population growth rate is the net rate of population change resulting from birth rates, mortality rates, and net migration over time."),
        (13, "Tall trees with buttress roots are associated with", "tropical rain forest", "Guinea savanna", "Sudan savanna", "Sahel savanna", 0, "Tall emergent trees in tropical rain forests develop large buttress roots for mechanical support in shallow, nutrient-leached soils."),
        (14, "Which of the following resources is renewable?", "livestock", "mineral", "forest", "crude oil", 2, "Forests (and biological timber/vegetation) are renewable natural resources that regenerate naturally if sustainably managed."),
        (15, "The solar system comprises the sun and its", "seven planets", "eight planets", "nine planets", "six planets", 1, "The modern solar system officially comprises the Sun and eight planets orbiting around it (following IAU planetary reclassification)."),
        (16, "On September 23rd (Autumnal Equinox), all towns or cities across the globe experience", "equal length of day and night (12 hours each)", "complete daylight", "longer nights and shorter days", "longer days and shorter nights", 0, "On the equinoxes (March 21 and September 23), the sun is directly overhead at the equator, giving 12 hours daylight and 12 hours night worldwide."),
        (17, "Density, mortality, and birth rate are factors that affect", "population", "dominance", "cover", "habitat", 0, "Population dynamics and demographic structure are governed by density, birth rate (natality), death rate (mortality), and migration."),
        (18, "The predominant system of agriculture among traditional rural farmers in West Africa is", "terrace farming", "irrigation farming", "plantation agriculture", "bush fallowing (rotational farming)", 3, "Bush fallowing involves cultivating a plot of land for some years and leaving it fallow to naturally restore fertility."),
        (19, "What type of mountain structure is associated with synclines and anticlines?", "Block mountain", "Fold mountain", "Volcanic mountain", "Residual mountain", 1, "Fold mountains are formed by compressional tectonic forces buckling the crust into anticlines (upfolds) and synclines (downfolds)."),
        (20, "The instrument used for recording vibrations and measuring the intensity of an earthquake is the", "epicenter locator", "thermometer", "barometer", "seismograph", 3, "A seismograph (or seismometer) detects, measures, and records seismic shock waves generated by earthquakes."),
        (21, "All of these are major industrial zones in Nigeria except", "the western industrial zone (Lagos-Ibadan)", "the south-east industrial zone (Aba-Port Harcourt-Enugu)", "the north-central industrial zone (Kano-Kaduna)", "the desert frontier zone", 3, "The three primary manufacturing zones in Nigeria are the South-West, South-East, and North-Central industrial corridors."),
        (22, "Lines of longitude can best be described as", "imaginary lines on the earth's surface joining the North and South Poles", "the distance of a place east or west of Greenwich Meridian", "the angular distance north or south of the equator", "parallel circles numbering from 0 to 90", 0, "Longitudes (meridians) are imaginary semi-circles running north-south from pole to pole and converging at the poles."),
        (23, "The largest planet in the solar system, with atmospheric light and dark bands, is", "Mercury", "Neptune", "Jupiter", "Mars", 2, "Jupiter is the largest planet in our solar system, characterized by prominent atmospheric bands of hydrogen and methane gases."),
        (24, "The longest and largest river in Nigeria is", "River Niger", "River Benue", "River Ogun", "River Osun", 0, "River Niger is Nigeria's longest and largest river, originating from the Fouta Djallon highlands in Guinea."),
        (25, "Which cartographic method represents data quantities and distribution across an area using dots?", "contour map", "form lines", "dot map", "hachures", 2, "A dot distribution map uses dots of uniform size to represent specific quantities of a spatial phenomenon."),
        (26, "The longest river in the whole of West Africa is", "River Benue", "River Niger", "River Volta", "River Senegal", 1, "River Niger (approx. 4,180 km) is the longest river in West Africa."),
        (27, "Which of the following is not a sustainable way of conserving natural resources?", "adopting good farming practices", "establishing forest reserves", "establishing game reserves", "encouraging wildlife poaching", 3, "Poaching (illegal hunting) severely depletes wildlife populations and violates environmental conservation laws."),
        (28, "The downslope movement of weathered rock debris and regolith under the direct influence of gravity is called", "weathering", "mass movement (mass wasting)", "catastrophism", "orogeny", 1, "Mass wasting or mass movement refers to the gravitational movement of rock material down slopes without an active transporting medium like running water."),
        (29, "A concordant horizontal sheet-like intrusion of magma between bedding planes of sedimentary rock is called a", "batholith", "dyke", "lava plain", "sill", 3, "A sill is a horizontal, concordant igneous intrusion injected along the bedding planes of existing rock strata."),
        (30, "In the southern hemisphere, the autumnal equinox occurs on", "21st March", "23rd September", "22nd December", "21st June", 1, "The autumnal equinox occurs on September 23 in the southern hemisphere (mirroring spring in the north)."),
        (31, "The single natural satellite of the Earth is", "the Sun", "the Moon", "Mars", "Saturn", 1, "The Moon is Earth's only natural satellite, orbiting at an average distance of ~384,400 km."),
        (32, "The following are direct environmental effects of overgrazing except", "depletion of palatable forage grasses", "soil and wind erosion of pasture land", "epidemic of bovine diseases", "scarcity of good pasture land", 2, "Overgrazing strips vegetative ground cover leading to accelerated soil erosion, but does not directly originate disease epidemics."),
        (33, "Sharp, slender, downward-growing calcite pinnacles hanging from the roofs of limestone caves are called", "limestone gorges", "uvalas", "poljes", "stalactites", 3, "Stalactites hang down like icicles from cave ceilings; stalagmites grow upward from the cave floor."),
        (34, "Which of the following West African nations is completely landlocked (no direct coastline)?", "Burkina Faso", "Guinea", "Nigeria", "Ghana", 0, "Burkina Faso is a landlocked nation surrounded by Mali, Niger, Benin, Togo, Ghana, and Cote d'Ivoire."),
        (35, "The most economically significant cash crop grown in the irrigated Nile Basin of Egypt is", "cotton", "millet", "sugarcane", "groundnut", 0, "Long-staple cotton (Egyptian cotton) is historically the most valuable export cash crop cultivated in the irrigated Nile Valley."),
        (36, "In geology, the continental crust (sial) has an average rock density of approximately", "2.0 g/cm³", "2.7 g/cm³", "3.0 g/cm³", "5.5 g/cm³", 1, "The continental crust (Sial: Silicon-Aluminium) has a density of ~2.7 g/cm³ (2700 kg/m³), lighter than the oceanic crust (Sima: ~3.0 g/cm³)."),
        (37, "The angular distance of a point on the earth's surface measured in degrees north or south of the equator is known as", "orbit", "latitude", "axis", "longitude", 1, "Latitude is the angular distance measured north or south from the equator (0° to 90°)."),
        (38, "In West Africa, true arid desert conditions are located in", "the southern coastal strip", "northern Mali", "northern Nigeria", "coastal Senegal", 1, "Northern Mali lies deep within the Sahara Desert, characterized by hyper-arid climatic conditions."),
        (39, "All of these are primary elements of weather and climate except", "temperature", "altitude", "rainfall", "sunshine", 1, "Altitude is a climatic control/factor that modifies weather, whereas temperature, rainfall, and sunshine are direct elements of weather."),
        (40, "Which factor promotes high population density in a geographic region?", "fertile alluvial soil", "high unemployment", "unfavourable arid climate", "swampy marshland", 0, "Fertile agricultural soils (such as river floodplains and volcanic soils) support intensive food production and dense human settlements."),
        (41, "If a map with an original scale of 1:150,000 is enlarged 3 times, its new representative fraction scale becomes", "1 : 50,000", "1 : 75,000", "1 : 100,000", "1 : 450,000", 0, "Enlarging a map by a factor of 3 decreases the scale denominator: 150,000 / 3 = 50,000, giving a new scale of 1:50,000."),
        (42, "Which of the following is an abiotic (non-living) environmental factor in an ecosystem?", "parasite", "predator", "grazer", "atmospheric pressure", 3, "Atmospheric pressure, temperature, sunlight, and wind are abiotic components; predators and grazers are biotic."),
        (43, "Water pollution in aquatic ecosystems is caused by all the following except", "increased silt load from soil erosion", "untreated sewage discharge", "sand filling in coastal land reclamation", "industrial toxic effluent", 2, "Sand filling is a physical reclamation activity rather than an organic or chemical water pollutant."),
        (44, "Which of the following represents the correct sequential order of denudation processes?", "weathering -> deposition -> erosion", "weathering -> erosion -> deposition", "erosion -> weathering -> deposition", "deposition -> erosion -> weathering", 1, "Denudation begins with the breaking down of rock (weathering), followed by removal/transport (erosion), and finally settling (deposition)."),
        (45, "Because of its slight flattening at the poles and equatorial bulge, the true shape of the Earth is best described as a", "geoid (oblate spheroid)", "geosphere", "perfect sphere", "flat circle", 0, "The earth is an oblate spheroid or geoid, slightly flattened at the poles and bulging at the equator due to axial rotation."),
        (46, "The following are abiotic components of an ecosystem except", "bacteria", "topography", "water", "wind", 0, "Bacteria are living microscopic organisms (biotic decomposers), whereas water, wind, and topography are abiotic."),
        (47, "Which of the following agricultural conservation practices has a beneficial effect on soil structure?", "overgrazing", "strip-cultivation (strip cropping)", "indiscriminate bush burning", "continuous monocropping", 1, "Strip-cultivation alternates strips of erosion-resistant cover crops with row crops, retaining topsoil and soil moisture."),
        (48, "The degree of saltiness or concentration of dissolved mineral salts in ocean waters is referred to as", "ocean deep", "ocean ridge", "continental plain", "ocean salinity", 3, "Salinity refers to the total concentration of dissolved salts in seawater, averaging approximately 35 parts per thousand (35‰)."),
        (49, "Stratified rocks formed in distinct parallel layers (strata) are classified as", "metamorphic rocks", "plutonic rocks", "igneous rocks", "sedimentary rocks", 3, "Sedimentary rocks are formed by the deposition and lithification of mineral/organic particles in strata separated by bedding planes."),
        (50, "Which of the following is not a standard physical property used in classifying and defining soil?", "soil colour", "capillarity alone", "permeability", "soil texture", 1, "Soil texture, structure, colour, and permeability define soil classifications; capillarity is a hydrological process."),
        (51, "The zone of the earth where all biological life activities and ecosystems exist is the", "biosphere", "lithosphere", "hydrosphere", "stratosphere", 0, "The biosphere is the global ecological system integrating all living beings and their relationships with the lithosphere, hydrosphere, and atmosphere."),
        (52, "Nigeria is geographically situated in which region of the African continent?", "East Africa", "North Africa", "West Africa", "South Africa", 2, "Nigeria is located on the Gulf of Guinea in West Africa."),
        (53, "Which mode of modern transport is most susceptible to severe disruptions by adverse weather (fog, thunderstorms)?", "rail transport", "pipeline transport", "road transport", "air transport", 3, "Air transport is critically sensitive to visibility issues (dense fog, harmattan haze) and violent atmospheric turbulence."),
        (54, "A great circle on the globe is defined as", "any small circle parallel to the equator", "a meridian that terminates at the pole", "the Tropic of Cancer", "a circle on the earth whose plane passes directly through the centre of the globe", 3, "A great circle divides the sphere into two equal hemispheres; its plane passes through the geometric centre of the Earth."),
        (55, "The catastrophic earthquake in Turkey that claimed thousands of lives occurred in", "1755", "1906", "1920", "2003", 3, "The major Bingöl earthquake in Turkey occurred in May 2003."),
        (56, "The longitudinal extent (difference between eastern and western boundaries) of Nigeria is approximately", "0°", "11°", "20°", "12°", 3, "Nigeria spans approximately from longitude 3° E to 15° E, giving a longitudinal width of roughly 12° (15° - 3° = 12°)."),
        (57, "The entire liquid/water portion of the Earth's surface (oceans, seas, lakes, rivers) is called the", "biosphere", "hydrosphere", "mesosphere", "lithosphere", 1, "The hydrosphere comprises all surface water, groundwater, and atmospheric water vapor."),
        (58, "In which of the following African countries is Mediterranean commercial citrus/fruit farming least prevalent?", "Morocco", "Egypt", "Algeria", "Uganda", 3, "Uganda has an equatorial/tropical climate unsuitable for Mediterranean orchard fruit farming (olives, grapes, citrus) found in North Africa."),
        (59, "The vital artificial waterway connecting the Mediterranean Sea to the Red Sea for global maritime transit is the", "Suez Canal", "Panama Canal", "Kiel Canal", "St. Lawrence Seaway", 0, "The Suez Canal in Egypt provides the shortest maritime route between Europe and lands around the Indian and western Pacific oceans."),
        (60, "The most heavily urbanized and industrialized geopolitical region of Nigeria is the", "North-Central", "North-East", "South-West", "North-West", 2, "The South-West region (encompassing Lagos, Ibadan, and Abeokuta) represents Nigeria's most densely urbanized corridor."),
        (61, "All the following are characteristic hydrological features of Nigerian rivers except", "seasonal volume fluctuations and flooding", "presence of rapids and waterfalls along crystalline shields", "siltation and shallow lower courses", "presence of glacial misfit valleys", 3, "Nigerian rivers are tropical rivers free of Pleistocene glacial erosion features like glacial misfit valleys."),
        (62, "All the following are common systems of farming in West Africa except", "rotational bush farming", "permanent terrace cultivation", "large-scale commercial wheat plantation", "mixed farming", 2, "Commercial wheat plantations are not a traditional farming system in tropical West Africa."),
        (63, "Drought-resistant plants adapted to survive in arid desert environments with minimal water are termed", "hydrophytes", "mesophytes", "xerophytes", "halophytes", 2, "Xerophytes (e.g. cacti, acacia) possess specialized adaptations such as thick waxy cuticles and deep root systems to conserve water."),
        (64, "Extremely low annual rainfall, sparse thorny vegetation, high daytime temperatures, and rapid nocturnal cooling characterize the", "swamp forest", "tropical rainforest", "Guinea savanna", "desert biome", 3, "Desert environments experience extreme diurnal temperature ranges, minimal precipitation, and scarce xerophytic vegetation."),
        (65, "Which of the following is a classic form of rapid mass wasting (slope failure)?", "steep slope", "landslide", "residual hill", "peneplain", 1, "Landslides involve the rapid downslope slide of a cohesive mass of soil, regolith, and rock along a slip surface."),
        (66, "The primary industrial engineering method used for extracting crude petroleum from underground reservoirs is", "open-cast mining", "underground shaft mining", "placer mining", "rotary drilling with oil rigs", 3, "Crude oil is extracted by drilling deep boreholes into subsurface geological formations using drilling rigs."),
        (67, "The standard meteorological instrument used to measure precipitation depth is the", "rain gauge", "mercury thermometer", "hygrometer", "aneroid barometer", 0, "A rain gauge measures the amount of liquid precipitation in millimeters over a defined period."),
        (68, "The key ecological factors determining the natural vegetation of a biome include all the following except", "annual rainfall amount and distribution", "nature and depth of soil particles", "temperature regimes", "depth of the underground water table as the sole determinant", 3, "Vegetation zones are primarily determined by broad macroclimatic conditions (rainfall and temperature) rather than local water-table depth alone."),
        (69, "In physical hydrology, surface freshwater bodies like streams, lakes, and river networks are termed", "canals", "ditches", "drainage networks", "ocean trenches", 2, "A drainage network or system comprises all connected rivers, tributaries, and lakes conveying surface runoff."),
        (70, "All the following are major commercial timber-producing forest nations in West/Central Africa except", "Ghana", "Cote d'Ivoire", "Nigeria", "Mauritania", 3, "Mauritania lies in the arid Sahel/Sahara region with no tropical rainforests for commercial timber production."),
        (71, "All of the following landforms are typical features of the lower course (plain stage) of a river except", "broad flood plain", "narrow V-shaped steep valley", "natural levees", "ox-bow lakes", 1, "V-shaped valleys and interlocking spurs characterize the steep upper course of a river, not its flat lower plain course."),
        (72, "The exact subterranean point inside the Earth's crust where seismic fracture initiates during an earthquake is the", "focus (hypocentre)", "vent", "caldera", "crater", 0, "The focus (hypocentre) is the point of initial rupture underground, while the epicentre is the point on the surface directly above it."),
        (73, "Density, natality, and mortality rates are the fundamental demographic determinants of human", "population change", "political dominance", "canopy cover", "topographic relief", 0, "Population growth and age distribution depend directly on births, deaths, and population density."),
        (74, "A natural spring occurs where", "streams flow over waterfalls", "rainwater evaporates immediately", "the underground water table intersects the ground surface", "rivers enter the sea", 2, "A spring forms wherever groundwater discharges naturally at the surface where the water table meets the topography."),
        (75, "Loam is widely considered the ideal soil type for agricultural crop production because it", "consists purely of heavy clay", "contains a balanced mixture of sand, silt, clay, and rich humus with good moisture retention", "drains water instantly without retention", "is completely devoid of organic matter", 1, "Loam combines the aeration of sand with the nutrient/moisture retention of clay and organic humus."),
        (76, "Which of the following inner planets in our solar system has no natural satellites (moons)?", "Venus", "Uranus", "Neptune", "Jupiter", 0, "Both Mercury and Venus have zero moons; Mars has two, and the outer gas giants have dozens."),
        (77, "When the local time is 9:00 AM in Munich, Germany (11° E), the local solar time in Calcutta, India (96° E) is", "4:20 AM", "2:40 AM", "2:40 PM", "5:40 PM", 2, "Longitudinal difference = 96° - 11° = 85°. Time difference = 85° / 15° = 5 hours 40 minutes. Since Calcutta is east, time is ahead: 9:00 AM + 5h 40m = 2:40 PM."),
        (78, "Which of the following statements is scientifically false regarding the solar system?", "The Sun provides the fundamental thermal and light energy for the system", "All planets rotate in the exact same direction and speed", "Planets revolve in elliptical orbits around the Sun", "The Sun is located at the gravitational centre of the system", 1, "Planets have different axial rotation speeds and Venus/Uranus exhibit retrograde rotation; they do not all rotate identically."),
        (79, "The spinning movement of the Earth from west to east on its own tilted axis once every 24 hours is called", "friction", "revolution", "gravitation", "rotation", 3, "Earth's axial rotation from west to east causes the alternating cycle of day and night and standard time zones."),
        (80, "Which meteorological instrument is used to measure wind speed?", "thermometer", "barometer", "hygrometer", "anemometer", 3, "An anemometer (cup or vane) measures wind speed, while a wind vane indicates wind direction."),
        (81, "All of the following are recognized forms of urban settlements except", "towns", "rural village", "conurbation", "megalopolis", 1, "A village is classified as a rural agrarian settlement, whereas towns, cities, conurbations, and megalopolises are urban.")
    ]

    lines = []
    lines.append('package com.example.data.repository\n')
    lines.append('import com.example.data.db.QuestionEntity\n')
    lines.append('object JambGeographyQuestionBank {')
    lines.append('    fun getQuestions(): List<QuestionEntity> {')
    lines.append('        return listOf(')

    for q in geo_raw:
        num, text, a, b, c, d, ans, exp = q
        qid = f"geo_2015_{num:03d}"
        topic = "Physical Geography"
        if "weather" in text.lower() or "climate" in text.lower() or "equinox" in text.lower() or "instrument" in text.lower() or "solar" in text.lower() or "planet" in text.lower() or "longitude" in text.lower() or "latitude" in text.lower() or "wind" in text.lower() or "axis" in text.lower():
            topic = "The Earth, Solar System & Weather"
        elif "river" in text.lower() or "rock" in text.lower() or "mountain" in text.lower() or "soil" in text.lower() or "erosion" in text.lower() or "crust" in text.lower() or "earthquake" in text.lower() or "mass" in text.lower():
            topic = "Geomorphology & Rocks"
        elif "map" in text.lower() or "scale" in text.lower():
            topic = "Map Reading & Cartography"
        elif "population" in text.lower() or "urban" in text.lower() or "settlement" in text.lower() or "agriculture" in text.lower() or "mining" in text.lower() or "nigeria" in text.lower() or "west africa" in text.lower():
            topic = "Human & Regional Geography"

        text_escaped = text.replace('"', '\\"')
        a_esc = a.replace('"', '\\"')
        b_esc = b.replace('"', '\\"')
        c_esc = c.replace('"', '\\"')
        d_esc = d.replace('"', '\\"')
        exp_esc = exp.replace('"', '\\"')

        lines.append(f'''            QuestionEntity(
                id = "{qid}",
                subject = "Geography",
                topic = "{topic}",
                year = "2015",
                questionText = "{text_escaped}",
                optionA = "{a_esc}",
                optionB = "{b_esc}",
                optionC = "{c_esc}",
                optionD = "{d_esc}",
                correctAnswerIndex = {ans},
                explanation = "{exp_esc}",
                difficulty = "Medium",
                originType = "JAMB_ORIGINAL",
                originLabel = "Original JAMB Question • 2015",
                isVerifiedJamb = true
            ),''')

    lines.append('        )')
    lines.append('    }')
    lines.append('}\n')

    with open("app/src/main/java/com/example/data/repository/JambGeographyQuestionBank.kt", "w") as f:
        f.write("\n".join(lines))
    print("Geography generated: 81 questions")

def generate_history():
    # 48 questions from PDF JAMB History 2012
    # Answers on page 21:
    # 1. A, 2. B, 3. A, 4. C, 5. D, 6. B, 7. B, 8. D, 9. C, 10. A
    # 11. D, 25. D, 26. D, 27. B, 28. C, 29. B, 30. A
    # 31. D, 32. A, 33. D, 34. B, 35. C, 36. C, 37. A, 38. B, 39. C, 40. D
    # 41. D, 42. A, 43. C, 44. B, 45. D, 46. A, 47. B, 48. D
    # Note: The PDF contains items from 1-48
    his_raw = [
        (1, "The Nok civilization in central Nigeria suggests that", "Nigeria passed through different distinct stages of technological development", "civilization in the area began only with the Stone Age", "the people of Nigeria originated entirely from the Middle East", "Nigerian civilization is directly related to ancient Greece", 0, "Nok culture proves indigenous technological progression from Late Stone Age microliths to sophisticated iron smelting and terracotta art."),
        (2, "The development of microliths (small, geometric stone tools) is associated with the", "Middle Stone Age", "Late Stone Age", "Early Iron Age", "Early Stone Age", 1, "Microliths are small flint or chert stone tools characteristic of Late Stone Age hunter-gatherer technology."),
        (3, "In pre-colonial Nigeria, intergroup contacts and migrations were encouraged mostly by", "economic interdependence and trade networks", "military conquest alliances", "royal marriage ties", "centralized political ties", 0, "Regional specialization in agricultural products, salt, textiles, and ironware fostered extensive trade and peaceful intergroup contacts."),
        (4, "Which of the following historical documents is the most important indigenous source for the history of the Hausa states?", "Tarikh-as-Sudan", "The European travel accounts", "The Kano Chronicle", "The Arab traders' records", 2, "The Kano Chronicle (Tarikh Arbab Hadha al-Balad al-Musamma Kano) provides the most detailed chronological record of Hausa dynasties."),
        (5, "The ancestral relationship between the Yoruba dynasty and the Oba of Benin is emphasized by the", "similarities of Benin and Ife bronze arts", "similarities in their monarchical political structures", "relationship between Oranmiyan and Ogiso dynasties", "Oranmiyan legend in Benin and Oyo royal traditions", 3, "According to Benin tradition, Prince Oranmiyan of Ife came to Benin and fathered Eweka I, the founder of the modern Oba dynasty."),
        (6, "European merchants and traders did not venture directly into the interior of Nigeria before the 19th century because", "they were completely ignorant of inland geography", "African coastal middlemen effectively served their commercial needs", "they feared coastal warrior kingdoms", "European traders were very few in number", 1, "Coastal city-state middlemen (Itsekiri, Nembe, Bonny, Calabar) strictly protected their monopoly over trade with interior markets."),
        (7, "The Africans captured and transported across the Atlantic as slaves during the slave trade era were mostly", "convicted criminals", "able-bodied young men and women", "disabled or aged persons", "people with low income", 1, "European plantation owners in the Americas demanded healthy, vigorous, able-bodied young individuals for intensive plantation labour."),
        (8, "The 19th-century Sokoto jihadists emerged victorious in Gobir primarily because", "their military cause was just", "the Hausa rulers were disunited", "they possessed superior firearms", "the oppressed peasant masses (talakawa) strongly supported them", 3, "Usman dan Fodio gained mass grassroots support from peasants and pastoralists burdened by arbitrary non-Islamic taxation (jangali) and corruption."),
        (9, "Rabeh Zubayr's greatest administrative challenge after conquering the Borno Empire was", "normalizing diplomatic relations with the Sokoto Caliphate", "rebuilding the depleted armed forces", "reviving the ruined and ailing local economy", "safeguarding and reforming Islamic practice", 2, "Rabeh's military conquest devastated the agricultural base and trans-Saharan trading networks of Borno, plunging the economy into severe depression."),
        (10, "Christianity spread rapidly across Southern Nigeria during the colonial era primarily because it", "was closely associated with Western formal education and literacy", "had superior theological and spiritual appeal", "preached strict social equality among all classes", "was actively opposed to native traditional rulers", 0, "Missionary schools provided the gateway to civil service employment, literacy, and social mobility under British colonial rule."),
        (11, "Ibadan-Ijebu diplomatic relations in the 19th century became hostile primarily as a result of", "boundary disputes between them", "succession disputes to the Awujale throne", "the British annexation of Lagos in 1861", "Ibadan's desperate attempts to secure direct access to the coastal trade routes", 3, "Ibadan, a landlocked military superpower, fought to bypass Egba and Ijebu middlemen to acquire firearms directly from Lagos."),
        (12, "The Ekiti Parapo (Kiriji War) military alliance was formed with the primary objective of", "checking European colonial penetration into Yorubaland", "restoring the ancient political supremacy of the Alaafin of Oyo", "reducing and throwing off the oppressive military hegemony of Ibadan", "forming a unified federated Yoruba republic", 2, "The Ekiti, Ijesha, and allied kingdoms united under Fabunmi and Ogedengbe to liberate eastern Yorubaland from heavy-handed Ibadan administrators (Ajele)."),
        (13, "The Uzama N'Ihinron (Council of Seven) titleholders in the Kingdom of Benin were responsible for", "advising the Oba and crowning the heir apparent as kingmakers", "punishing offending members of the royal family", "leading the army in foreign military campaigns", "settling commercial disputes among commoners", 0, "The Uzama are the hereditary kingmakers in Benin who officially proclaim and crown each new Oba."),
        (14, "Britain abolished and actively suppressed the trans-Atlantic slave trade in the early 19th century primarily because", "there was no longer any market for enslaved labour in the Americas", "the practice was universally recognized as inhuman", "Christian humanitarian societies launched religious protests", "the Industrial Revolution made free market trade in raw materials (palm oil) more profitable than human cargo", 3, "British industrial capitalism required raw materials (like palm oil to lubricate machinery) and overseas consumer markets, making slave exports economically counter-productive."),
        (15, "The main objective of the British military expedition against the Aro of Eastern Nigeria (1901-1902) was to", "destroy the Long Juju (Ibini Ukpabi) oracle", "eliminate Aro monopoly and open the Igbo hinterland to British commercial exploitation", "pave the way for Christianization of Igboland", "liberate the communities from Aro domination", 1, "The British aimed to break the Aro trading network which controlled interior commerce and resisted direct British colonial administration."),
        (16, "A major practical reason for Lord Lugard's adoption of the Indirect Rule system in Northern Nigeria was to", "ensure direct administrative control over the peasant economy", "weaken the influence of the traditional educated elite", "assist Christian missionaries in propagating their faith", "administer the vast territory with minimal British personnel and financial expenditure", 3, "Indirect Rule utilized existing Emirs and native institutions to govern large populations cheaply with very few British colonial officers."),
        (17, "Nationalist movements developed earlier in British West Africa than in French West Africa because", "British colonies enjoyed full parliamentary representation in London", "Britain maintained far fewer troops in Africa than France", "African chiefs in French colonies were accorded higher political autonomy", "of the different administrative systems (Indirect Rule vs. direct French Assimilation and Indigénat)", 3, "French assimilation and strict colonial labour laws (indigénat) suppressed autonomous African political parties and press until after WWII."),
        (18, "The primary economic reason for the British construction of the railway line from Port Harcourt into the hinterland was the", "discovery of tin ore on the Jos Plateau", "discovery of a deep-sea natural harbor at Port Harcourt", "discovery of commercial coal deposits at Enugu (Udi hills)", "urgent need to evacuate agricultural export crops from the North", 2, "The Port Harcourt-Enugu railway line was surveyed and constructed starting in 1913 specifically to transport coal from the Udi hills to ships at the coast."),
        (19, "During the colonial era, British agricultural policy in Nigeria was deliberately structured to", "strengthen the fiscal self-reliance of the indigenous peasantry", "make the local economy competitive with European manufacturers", "secure steady supplies of raw agricultural export materials for British home industries", "demonstrate British benevolent concern for African development", 2, "Colonial agricultural policy prioritized export cash crops (groundnuts, cocoa, palm oil, cotton) to feed British factories at cheap commodity prices."),
        (20, "The Nigerian Youth Movement (NYM) collapsed in 1941 largely as a result of", "its total failure to win legislative elections", "severe shortage of operating funds", "intense suppression and arrest of its leadership by the colonial state", "internal ethnic rivalry and factional leadership disputes over the 1941 legislative council nomination", 3, "The party fractured when Ernest Ikoli and Samuel Akinsanya contested the vacant Legislative Council seat, leading Azikiwe and his supporters to resign."),
        (21, "The National Council of Nigeria and the Cameroons (NCNC) delegation sent to London in 1947 demanded", "free and universal primary education across Nigeria", "immediate full autonomy for the three regional governments", "a thorough revision and democratic reform of the undemocratic Richards Constitution", "immediate and unconditional political independence for Nigeria", 2, "The 1947 NCNC delegation led by Herbert Macaulay and Nnamdi Azikiwe protested against the autocratic Richards Constitution of 1946."),
        (22, "The 1954 Oliver Lyttelton Constitution is considered a major landmark in Nigerian constitutional history because it", "established a formal federal system of government with regional autonomy", "made executive ministers directly accountable to the regional electorate", "first separated Lagos from the Western Region as a Federal Capital Territory", "transferred complete command of the armed forces to Nigerian politicians", 0, "The 1954 Constitution formally inaugurated Nigerian federalism with distinct regional legislative lists and a federal residual framework."),
        (23, "Early strikes and agitations by Nigerian trade unions during the colonial era (such as the 1945 General Strike) aimed primarily at", "overthrowing the British colonial administration", "compelling the colonial government to establish heavy industries", "obtaining fair wages, Cost of Living Allowance (COLA), and better welfare conditions for workers", "rooting out financial corruption in the civil service", 2, "Led by Michael Imoudu, the 1945 general strike demanded wage increases to compensate for wartime inflation under the Cost of Living Allowance."),
        (24, "Which of the following prominent political leaders served as Federal Ministers in Prime Minister Tafawa Balewa's cabinet during the First Republic?", "Alhaji Muhammadu Ribadu and Chief Festus Okotie-Eboh", "Chief Kolawole Balogun and Alhaji Adamu Ciroma", "Alhaji Muhammadu Inuwa Wada and Chief Richard Akinjide", "Chief Aja Nwachukwu and Alhaji Umaru Dikko", 0, "Alhaji Muhammadu Ribadu served as Minister of Defence and Chief Festus Okotie-Eboh served as Federal Minister of Finance."),
        (25, "An essential statutory responsibility of FEDECO (Federal Electoral Commission) during Nigeria's 1979 General Elections was", "establishing branch offices for all registered political parties", "drafting and promulgating the 1979 Constitution into law", "swearing in elected governors and the President", "delimiting constituency boundaries and registering qualified political parties and voters", 3, "FEDECO, led by Chief Michael Ani, organized voter registration, constituency delimitation, and supervised the 1979 elections."),
        (26, "A major contributing factor to the first military coup d'état in Nigeria on January 15, 1966 was the", "openly pro-Western alignment of Nigerian foreign policy", "overbearing constitutional authority exercised by traditional rulers", "government's planned retirement of senior military officers", "severe political instability and violent crises arising from the 1964 Federal Elections and 1965 Western Regional Election", 3, "Widespread violence, electoral fraud in the Western Region ('Operation Wetie'), and regional tensions triggered the January 1966 military intervention."),
        (27, "Major-General J.T.U. Aguiyi-Ironsi promulgated Unification Decree No. 34 of 1966 primarily because", "it was the popular demand of the regional political parties", "of the centralized, hierarchical command structure natural to the military institution", "he intended to centralize all regional tax revenues under federal control", "he suspected regional premiers of organizing counter-coups", 1, "The military hierarchy naturally favored a unitary, centralized command structure over regional federal autonomy."),
        (28, "The accelerated agricultural strategy introduced by the Federal Military Government in 1976 was the", "National Accelerated Food Production Programme (NAFPP)", "Green Revolution Programme", "Operation Feed the Nation (OFN)", "River Basin Development Authority initiative", 2, "Operation Feed the Nation (OFN) was launched in May 1976 to stimulate domestic food self-sufficiency and reduce food import dependence."),
        (29, "The renowned 19th-century Berber scholar Sidi al-Mukhtar al-Kunti contributed to the success of Islamic reform movements across West Africa by", "personally commanding jihads alongside Seku Ahmadu", "revitalizing and spreading the Qadiriyyah Sufi brotherhood", "recruiting military mercenaries from North Africa", "establishing diplomatic treaties with European trade companies", 1, "Al-Kunti's intellectual leadership and revitalized Qadiriyyah network provided ideological inspiration for reformers like Usman dan Fodio and Seku Ahmadu."),
        (30, "The establishment of Freetown, Sierra Leone in the late 18th and early 19th centuries was organized for", "the settlement of liberated and freed enslaved Africans", "the exclusive establishment of British military garrisons", "commercial plantation cultivation of spices", "mining expeditions along the West African coast", 0, "Freetown was founded by British humanitarians (Granville Sharp) as a sanctuary and settlement for liberated slaves (recaptives)."),
        (31, "Nineteenth-century Egyptian nationalist resistance led by Colonel Ahmad Urabi was primarily aimed at", "controlling European maritime transit through the Suez Canal", "forming a constitutional parliamentary government free from foreign Anglo-French domination", "restoring the ancient Ottoman Mamluk sultanate", "annexing Sudan and Ethiopia into a Greater Egyptian Empire", 1, "The Urabi Revolt (1881-1882) sought constitutional reform, military equality, and an end to British and French financial interference in Egypt."),
        (32, "The decisive 1882 Battle of Tel el-Kebir was fought between", "the British expeditionary forces and the Egyptian nationalist army under Urabi Pasha", "Khedive Tawfiq's personal forces and the Sudanese Mahdists", "the Ottoman forces and Napoleon's French troops", "the Wafd Party militants and British colonial police", 0, "British troops commanded by Sir Garnet Wolseley defeated Ahmad Urabi's Egyptian forces at Tel el-Kebir, inaugurating direct British occupation of Egypt."),
        (33, "Morocco was of crucial geopolitical and strategic significance to European powers during the Scramble for Africa because", "it contained the richest gold reserves in North Africa", "it was already a highly industrialized economy", "of its fertile tropical rainforest timber resources", "its coastline controlled the vital western maritime entrance to the Mediterranean Sea at the Strait of Gibraltar", 3, "Morocco's geographical location guarding the Strait of Gibraltar made it a flashpoint among France, Britain, Spain, and Germany (Agadir Crisis)."),
        (34, "The Mahdist uprising in the Sudan (1881-1885) under Muhammad Ahmad al-Mahdi succeeded primarily because", "the Mahdists possessed modern European rapid-fire rifles", "it enjoyed overwhelming popular support against oppressive, corrupt Turco-Egyptian taxation and misrule", "the Egyptian garrison troops in Khartoum were entirely unarmed", "the British army refused to intervene in the Nile region", 1, "The Mahdist movement united Sudanese ethnic groups against oppressive Turco-Egyptian administrative abuses and heavy taxation."),
        (35, "Sayyid Said, Sultan of Oman and Zanzibar, vastly expanded commercial trade with European nations by", "ceding total sovereignty over the African interior to European companies", "replacing Indian merchants with French and British customs agents", "encouraging American, British, and French consuls and merchant houses to establish headquarters in Zanzibar", "mandating English as the official language of government", 2, "Sayyid Said signed commercial treaties with the USA (1833), Britain (1839), and France (1844), making Zanzibar the dominant mercantile hub of East Africa."),
        (36, "A major British imperial objective in conquering the Kingdom of Buganda (Uganda) was to", "secure the sea lanes around the Cape of Good Hope", "monopolize the gold mines of Bunyoro", "secure strategic colonial control over the headwaters and source of the River Nile", "establish a settler colony for British farmers", 2, "British grand strategy in East Africa was anchored on controlling Uganda to protect the source of the River Nile, safeguarding British interests in Egypt and the Suez Canal."),
        (37, "Ethiopia successfully preserved its national independence against European imperial conquest in the 19th century largely because of", "Emperor Menelik II's strategic acquisition of modern arms and total victory at the Battle of Adwa (1896)", "its geographical isolation and impenetrable mountains alone", "a defensive military treaty with Great Britain", "its small and economically insignificant territory", 0, "Emperor Menelik II modernized the Ethiopian army with European firearms and crushed the invading Italian army at Adwa in March 1896."),
        (38, "The catastrophic 19th-century Mfecane (forced migrations and upheaval) in Southern Africa resulted in the", "complete disintegration and extermination of the Zulu Kingdom", "formation and emergence of powerful new defensive states like the Ndebele, Basotho, and Swazi nations", "rapid decline of Boer and British colonial influence in the Cape", "immediate dispersal of all Nguni speakers to North Africa", 1, "The wars of expansion and displacement triggered by Shaka Zulu led to the consolidation of durable new states like Moshoeshoe's Lesotho and Mzilikazi's Matabeleland."),
        (39, "The historic Sharpeville anti-apartheid demonstration in South Africa on March 21, 1960 was specifically organized against the humiliating", "Bantu Education Act", "Group Areas Act and land segregation", "Pass Laws (Natives Abolition of Passes Act)", "Mixed Marriages Prohibition Act", 2, "The Pan-Africanist Congress (PAC) led peaceful nationwide demonstrations against the hated 'pass books' which restricted the movement of Black South Africans."),
        (40, "A momentous historical consequence of the Boer 'Great Trek' (1835-1840s) was the", "voluntary return of Dutch settlers to Europe", "establishment of multiracial democratic governance in Southern Africa", "peaceful assimilation of Boer farmers into Xhosa society", "expansion of white settler hegemony into the interior and the founding of the Boer Republics (Transvaal and Orange Free State)", 3, "Boer Voortrekkers migrated northward out of the British Cape Colony, seizing inland indigenous lands and founding the South African Republic (Transvaal) and Orange Free State."),
        (41, "A prominent feature of European imperial diplomacy during the Scramble for Africa (Berlin Conference 1884-1885) was", "holding African monarchs hostage during negotiations", "exchanging ambassadors directly with independent African empires", "consulting African leaders on territorial partition boundaries", "reconciling conflicting imperial claims and establishing the doctrine of 'effective occupation'", 3, "The 1884-1885 Berlin West Africa Conference laid down rules among European powers to partition Africa without engaging in war against one another."),
        (42, "The French colonial policy of Assimilation ultimately failed in West Africa because", "African cultural, social, and Islamic traditions were deeply entrenched and resilient", "African traditional elites enthusiastically embraced French citizenship", "the French parliament granted immediate independence to all colonies", "it was overwhelmingly popular and rapidly fulfilled its targets", 0, "Assimilation demanded that Africans completely renounce their native languages, customs, and Islamic family laws, which Africans vigorously resisted."),
        (43, "Which of the following was a key political resolution passed by the National Congress of British West Africa (NCBWA) at Accra in 1920?", "The immediate expulsion of Syrian and Lebanese merchants from West African cities", "The establishment of a British West African University and legislative franchise granting Africans elected representation", "The prohibition of all Christian missionary schools in the colonies", "The immediate amalgamation of all British West African colonies into a single territory", 1, "Led by J.E. Casely Hayford, the NCBWA demanded elected African representation on legislative councils and the establishment of a British West African university."),
        (44, "The militant post-World War II Nigerian nationalist movement (represented by the Zikist Movement and trade unions) was predominantly led by", "traditional paramount rulers and native authority chiefs", "Western-educated intelligentsia, young radical journalists, teachers, and trade unionists", "conservative foreign trading merchants", "colonial administrative officers", 1, "Educated urban youth, trade unionists, and dynamic journalists (such as Anthony Enahoro, Nduka Eze, and Mokwugo Okoye) spearheaded radical post-war nationalism."),
        (45, "A primary founding objective of the South African Native National Congress (SANNC, later ANC) in 1912 was to", "launch an armed guerrilla struggle against the British Crown", "establish a separate communist political republic", "unite all African ethnic groups to defend their civil rights and protest against the 1913 Natives Land Act", "encourage the voluntary migration of Africans to neighboring territories", 2, "Pixley ka Isaka Seme and other educated African leaders formed the SANNC in Bloemfontein to unite all African nationalities against racial disenfranchisement."),
        (46, "In October 1973, Nigeria severed formal diplomatic relations with the State of Israel in solidarity with Egypt following Israel's", "occupation of Egyptian sovereign territory (Sinai Peninsula) during the Arab-Israeli War", "formal military alliance with apartheid South Africa", "covert military assistance to the Biafran secessionist army", "airborne commando raid on Entebbe Airport in Uganda", 0, "Acting in accordance with the Organization of African Unity (OAU) resolution, Nigeria broke ties with Israel after the Yom Kippur War over the occupation of African sovereign land (Egypt's Sinai)."),
        (47, "King Leopold II of Belgium's colonial operations in the Congo Free State (1885-1908) were fundamentally aimed at", "transforming the Kingdom of Belgium into a great maritime empire", "ruthlessly extracting natural rubber and ivory as a personal commercial enterprise", "eliminating tropical epidemic diseases among the native population", "introducing modern constitutional governance and free education", 1, "Leopold II operated the Congo Free State as his personal private estate, brutally exploiting forced Congolese labour to extract rubber and ivory."),
        (48, "European colonial powers constructed modern railway networks, roads, and deep-water ports in Africa primarily to", "stimulate the rapid growth of domestic internal retail markets", "boost the purchasing power and living standards of rural peasant farmers", "encourage balanced industrial and urban development across African regions", "facilitate the rapid evacuation of mineral and agricultural raw materials from the hinterland to coastal ports for export to Europe", 3, "Colonial transportation infrastructure was deliberately built to connect resource-rich interior zones directly to coastal harbors for export trade.")
    ]

    lines = []
    lines.append('package com.example.data.repository\n')
    lines.append('import com.example.data.db.QuestionEntity\n')
    lines.append('object JambHistoryQuestionBank {')
    lines.append('    fun getQuestions(): List<QuestionEntity> {')
    lines.append('        return listOf(')

    for q in his_raw:
        num, text, a, b, c, d, ans, exp = q
        qid = f"his_2012_{num:03d}"
        topic = "Pre-Colonial & Colonial History"
        if "nok" in text.lower() or "stone age" in text.lower() or "benin" in text.lower() or "hausa" in text.lower() or "oranmiyan" in text.lower() or "oyo" in text.lower() or "uzama" in text.lower():
            topic = "Pre-Colonial Nigerian History"
        elif "jihad" in text.lower() or "sokoto" in text.lower() or "borno" in text.lower() or "ibadan" in text.lower() or "ekiti" in text.lower() or "aro" in text.lower():
            topic = "19th Century Nigerian States"
        elif "slave trade" in text.lower() or "indirect rule" in text.lower() or "lugard" in text.lower() or "railway" in text.lower() or "richards" in text.lower() or "lyttelton" in text.lower() or "nym" in text.lower() or "ncnc" in text.lower() or "nationalist" in text.lower():
            topic = "Colonial Rule & Nationalism in Nigeria"
        elif "scramble" in text.lower() or "berlin" in text.lower() or "egypt" in text.lower() or "sudan" in text.lower() or "ethiopia" in text.lower() or "zanzibar" in text.lower() or "congo" in text.lower() or "sharpeville" in text.lower() or "boer" in text.lower() or "south africa" in text.lower():
            topic = "African & World History"

        text_escaped = text.replace('"', '\\"')
        a_esc = a.replace('"', '\\"')
        b_esc = b.replace('"', '\\"')
        c_esc = c.replace('"', '\\"')
        d_esc = d.replace('"', '\\"')
        exp_esc = exp.replace('"', '\\"')

        lines.append(f'''            QuestionEntity(
                id = "{qid}",
                subject = "History",
                topic = "{topic}",
                year = "2012",
                questionText = "{text_escaped}",
                optionA = "{a_esc}",
                optionB = "{b_esc}",
                optionC = "{c_esc}",
                optionD = "{d_esc}",
                correctAnswerIndex = {ans},
                explanation = "{exp_esc}",
                difficulty = "Medium",
                originType = "JAMB_ORIGINAL",
                originLabel = "Original JAMB Question • 2012",
                isVerifiedJamb = true
            ),''')

    lines.append('        )')
    lines.append('    }')
    lines.append('}\n')

    with open("app/src/main/java/com/example/data/repository/JambHistoryQuestionBank.kt", "w") as f:
        f.write("\n".join(lines))
    print("History generated: 48 questions")

def generate_irs():
    # 51 questions from PDF JAMB IRS 2011
    # Answers on page 14:
    # 1. B, 2. B, 3. B, 4. D, 5. B, 6. D, 7. C, 8. C, 9. D, 10. C
    # 11. B, 12. A, 13. C, 14. C, 15. C, 16. C, 17. D, 18. D, 19. B, 20. D
    # 21. B, 22. C, 23. D, 24. C, 25. B, 26. C, 27. C, 28. D, 29. B, 30. B
    # 31. C, 32. D, 33. C, 34. A, 35. C, 36. D, 37. C, 38. D, 39. C, 40. A
    # 41. B, 42. D, 43. B, 44. D, 45. D, 46. B, 47. D, 48. A, 49. A, 50. C, 51. A

    irs_raw = [
        (1, "The momentous historical outcome of Prophet Muhammad's (SAW) seclusion in Cave Hira at the age of forty was the", "compilation of the Glorious Qur'an into a book", "first revelation of the Glorious Qur'an through Angel Jibril", "award of a chieftaincy title by Makkan aristocrats", "immediate decision to migrate to Madinah", 1, "At age 40 in Cave Hira, Angel Jibril appeared to Prophet Muhammad (SAW) with the first divine revelation (Surah al-'Alaq: 1-5)."),
        (2, "The initial divine encounter between Angel Jibril (AS) and Prophet Muhammad (SAW) in the Cave of Hira marked the beginning of", "the compilation of Hadith collections", "Prophethood and the piecemeal revelation of the Holy Qur'an", "the establishment of Islamic political statehood in Makkah", "the declaration of open warfare against pagan tribes", 1, "The event at Cave Hira in 610 CE inaugurated Prophet Muhammad's mission as the final Messenger of Allah."),
        (3, "The supreme pedagogical significance of the first revealed verses (Surah al-'Alaq: 1-5) to mankind was the", "geographical description of the Arabian peninsula", "dissemination of literacy, reading, and knowledge in the name of Allah ('Iqra bi-smi Rabbika...')", "explanation of economic trade laws", "steps of military preparation", 1, "Qur'an 96:1-5 commands reading, learning, and seeking knowledge by the pen as a primary spiritual duty in Islam."),
        (4, "The gradual, piecemeal revelation (Tanjim) of the Glorious Qur'an over a period of 23 years was designed to", "allow the Prophet to write it down personally", "prevent non-believers from hearing it", "enable the Quraysh to translate it easily", "facilitate the gradual spiritual, moral, and legislative development of the early Muslim community", 3, "Piecemeal revelation allowed new Muslims to absorb spiritual principles progressively and addressed real-life situations as they arose."),
        (5, "The Quranic verse: 'Surely We have sent down the Reminder [al-Qur'an] and surely We will protect it' (Q. 15:9) guarantees the divine", "standardization of Arabic calligraphy", "eternal preservation and protection of the Qur'an against any corruption or alteration", "immediate translation into foreign languages", "speed of oral recitation during prayers", 1, "Surah Al-Hijr (15:9) affirms Allah's divine protection ensuring the Holy Qur'an remains free from distortion across all generations."),
        (6, "The decisive battle that resulted in the martyrdom of numerous Huffaz (Qur'an memorizers) and prompted Umar (RA) to advise Abu Bakr (RA) to compile the Qur'an was the Battle of", "Khandaq (The Trench)", "Uhud", "Tabuk", "Yamamah (633 CE)", 3, "After many memorizers fell at Yamamah during the Riddah wars, Umar (RA) urged Caliph Abu Bakr (RA) to compile the written Qur'anic manuscripts."),
        (7, "The standardizing committee appointed by Caliph Uthman bin Affan (RA) to produce authoritative copies of the Qur'an consisted of", "six companions", "five companions", "four companions (led by Zaid bin Thabit, with Abdullahi bin Zubair, Sa'ad bin al-Aas, and Abdur-Rahman bin Harith)", "three companions", 2, "Caliph Uthman (RA) appointed a panel of four prominent scribes to unify the recitation upon the Quraysh dialect."),
        (8, "A prominent stylistic and thematic characteristic common to Makkan Surahs of the Qur'an is that they", "are exceptionally long and contain civil commercial statutes", "primarily address the People of the Book (Ahl al-Kitab)", "contain short, rhythmic verses with frequent solemn oaths and emphasis on Tawhid, the Day of Judgment, and morality", "contain detailed rules on inheritance and warfare", 2, "Makkan chapters are characterized by concise, powerful poetic verses focusing on monotheism, the Akhirah, and refutation of polytheism."),
        (9, "The Qur'anic prophecy regarding the dramatic victory of the Byzantine Roman Empire over the Persian Sasanian Empire (Surah ar-Rum 30:2-4) provides undeniable proof of the", "poetic style of classical Arabic", "historical folklore of ancient Arabia", "secular diplomacy of Makkah", "authenticity, miraculous nature, and divine origin of the Glorious Qur'an", 3, "The accurate prophecy of Rome's military recovery within a few years was a miraculous proof of divine revelation."),
        (10, "The Glorious Qur'an differs fundamentally from all previous revealed scriptures because it", "is intended exclusively as a liturgical prayer book", "is restricted only to medical and spiritual healing", "provides a comprehensive, uncorrupted code governing spiritual, moral, legal, social, and economic life for all humanity", "serves solely as a protective amulet", 2, "The Qur'an is the universal, final revelation guiding every aspect of human spiritual and societal life."),
        (11, "Prophet Muhammad (SAW) did not leave behind the complete Qur'an bound in a single volume during his lifetime because", "he intended only the Quraysh clan to possess it", "revelations continued to descend at intervals until shortly before his demise", "there was a shortage of parchment in Arabia", "there were no companions capable of writing Arabic", 1, "Because divine revelation was ongoing throughout the Prophet's lifetime, formal compilation into a fixed codex occurred after the cessation of Wahy."),
        (12, "In Islamic Quranic sciences, the term 'Tafsir' strictly denotes the", "scholarly explanation, exegesis, and contextual commentary of the Glorious Qur'an", "scientific study of grammatical phonetics", "literal word-for-word translation into English", "memorization of Qur'anic verses without contemplation", 0, "Tafsir is the science of elucidating the meanings, context, legal rulings, and wisdom contained in the verses of the Qur'an."),
        (13, "The science of Tajwid is vital in Quranic recitation because it", "teaches the chronological history of the compilation of the Qur'an", "provides the philosophical basis for theology", "teaches the precise rules for correct articulation, phonetics, and melodious pronunciation of every Arabic letter", "enables one to speak fluent modern conversational Arabic", 2, "Tajwid preserves the authentic pronunciation received from the Prophet (SAW) by applying correct points of articulation (Makharij) and characteristics (Sifat)."),
        (14, "In the rules of Tajwid, pronouncing a heavy letter (like the letter Ra with a Fathah or Dammah) with full, resonant voice is termed", "Tarqiq (slenderness)", "Tanwin (nunation)", "Tafkhim (velarization / heaviness)", "Tashdid (gemination)", 2, "Tafkhim refers to making the sound of a letter thick and resonant in the mouth (e.g. Ra with Dammah or Fathah)."),
        (15, "The indispensable Surah in the Glorious Qur'an which must be recited in every single unit (Rak'ah) of obligatory prayer is", "Surah al-Baqarah", "Surah al-'Alaq", "Surah al-Fatihah ('The Opening')", "Surah al-Ikhlas", 2, "Prophet Muhammad (SAW) said: 'There is no prayer for whoever does not recite the Opening of the Book (Surah al-Fatihah)'."),
        (16, "The divine command: 'Therefore turn in prayer to your Lord and sacrifice [to Him only]' is found in Surah", "al-Lahab (111)", "al-Falaq (113)", "al-Kawthar (108:2)", "an-Nas (114)", 2, "Surah al-Kawthar (108:2) enjoins: 'Fa-salli li-Rabbika wanhar' (So pray to your Lord and sacrifice)."),
        (17, "Surah al-Ma'un strongly condemns those who perform prayers ostentatiously while", "failing to memorize long Surahs", "refusing to engage in foreign travel", "neglecting to construct large houses", "mistreating the orphan and refusing to extend basic assistance to the needy", 3, "Surah al-Ma'un (107) warns against hypocrites who show off their prayers while driving away orphans and withholding simple neighborly kindnesses."),
        (18, "The moral message of Surah al-Ma'un emphasizes the noble obligation of", "accumulating material wealth for prestige", "engaging in commercial speculation", "isolating oneself from society", "caring for the vulnerable, feeding the indigent, and showing sincere charity", 3, "The Surah highlights the inseparability of genuine faith from practical social compassion for the weak and impoverished."),
        (19, "The breathless charge of horses galloping into battle in the cause of Allah is vividly depicted in Surah", "al-Qari'ah", "al-'Adiyat ('The Charging Steeds')", "al-'Asr", "al-Humazah", 1, "Surah al-'Adiyat (100:1-5) opens with an oath by the panting war steeds striking sparks of fire as they charge at dawn."),
        (20, "In Islamic hermeneutics, ambiguous or allegorical verses (Mutashabihat) are understood by referring them to clear, foundational verses (Muhkamat) through scholarly", "arbitrary personal speculation", "linguistic conjecture", "philosophical mysticism", "disciplined Tafsir, sound Arabic grammar, and Sunnah of the Prophet", 3, "Sound Tafsir harmonizes allegorical expressions with the unambiguous core principles of the Qur'an."),
        (21, "According to Hadith 3 of Imam an-Nawawi's Forty Hadith collection (Hadith of Ibn Umar), Islam is built upon", "belief in angels alone", "five foundational pillars (Shahadah, Salah, Zakat, Sawm, and Hajj)", "philosophical scholasticism", "military conquest", 1, "The Hadith states: 'Islam is built upon five: testifying that there is no god but Allah and Muhammad is His messenger, establishing prayer, paying zakat, fasting Ramadan, and performing Hajj.'"),
        (22, "The central moral teaching of the 10th Hadith of an-Nawawi is that", "Allah answers prayers of leaders only", "only wealthy pilgrims receive forgiveness", "consuming only Halal (lawful) food and earning a pure livelihood is an essential prerequisite for prayers to be accepted", "outward physical pilgrimage guarantees piety", 2, "The Prophet (SAW) mentioned a disheveled traveler whose supplications were rejected because his food, drink, and clothing were derived from Haram (unlawful) sources."),
        (23, "In the 16th Hadith of Imam an-Nawawi's collection, when a man asked the Prophet (SAW) for counsel, the Prophet repeated several times:", "'Seek great wealth'", "'Study astronomy'", "'Avoid trade'", "'Do not become angry (La taghdab)'", 3, "The Prophet (SAW) emphasized emotional self-control by repeating 'Do not get angry' multiple times when asked for life advice."),
        (24, "What fundamentally distinguishes a Hadith Qudsi from a standard Hadith Nabawi is that in Hadith Qudsi,", "the chain of narrators is always unknown", "the statement was made in Madinah only", "the meaning is revealed directly by Allah while the wording is phrased by the Prophet (SAW)", "it cannot be quoted in scholarly literature", 2, "In Hadith Qudsi (Sacred Hadith), the Prophet (SAW) relates a message directly from Allah (e.g. 'O My servants...'), distinct from the Qur'an."),
        (25, "A primary methodological feature of Sahih al-Bukhari is that the traditions are systematically arranged according to", "biographies of narrators", "jurisprudential and thematic subject chapters (Kutub and Abwab)", "chronological order of battle events", "geographic origins of narrators", 1, "Imam al-Bukhari organized his Sahih into thematic legal books (Kitab al-Iman, Kitab al-Salah, Kitab al-Buyu', etc.)."),
        (26, "Among the classical compilers of Hadith, the Sunan collection dedicated specifically to legal traditions of permissions, prohibitions, and jurisprudence (Ahkam) is the Sunan of", "Imam Malik", "Imam Ahmad", "Imam Abu Dawood", "Imam al-Bukhari", 2, "Sunan Abu Dawood is celebrated as the definitive Sunan compilation focusing primarily on legal rulings (Ahkam al-Fiqh)."),
        (27, "A major ethical commandment highlighted in Surah al-Isra (Q. 17:23) immediately following the worship of Allah alone is", "the accumulation of commercial property", "the avoidance of foreign languages", "unquestioning kindness, honor, and deep respect towards one's parents", "the construction of grand buildings", 2, "Qur'an 17:23 commands: 'And your Lord has decreed that you not worship except Him, and to parents, good treatment. Whether one or both of them reach old age with you, say not to them so much as 'uff'...'"),
        (28, "The Children of Israel (Bani Isra'il) were sternly admonished not to knowingly obscure truth with falsehood in Surah al-Baqarah verse", "Q. 2:285", "Q. 2:177", "Q. 2:45", "Q. 2:42 ('And do not mix the truth with falsehood or conceal the truth while you know it')", 3, "Surah al-Baqarah (2:42) commands: 'Wa la talbisu al-haqqa bil-batili wa taktumul-haqqa wa antum ta'lamun'."),
        (29, "Islam strongly encourages every Muslim to seek lawful sustenance (Halal livelihood) by emphasizing the", "reliance on public welfare handouts", "dignity of honest labour and trade", "inheritance of ancestral fortunes alone", "avoidance of manual occupations", 1, "Prophet Muhammad (SAW) taught that the most blessed food a person eats is that earned through the work of their own hands."),
        (30, "As a strictly monotheistic faith (Tawhid), Islam requires that every believer must", "observe silence during daylight hours", "worship Allah sincerely without associating any partners or intermediaries with Him", "renounce all family obligations", "reside permanently in Makkah", 1, "The foundational creed of Islam (La ilaha illa Allah) demands pure, unadulterated monotheism free from Shirk."),
        (31, "Consulting fortunetellers, soothsayers, and astrologers is strictly prohibited in Islam because it", "is a waste of physical time", "causes unnecessary disputes among friends", "ascribes knowledge of the unseen (Ghayb) and absolute divine sovereignty to created beings (amounting to Shirk)", "is expensive to finance", 2, "The Qur'an declares that none in the heavens and earth knows the unseen except Allah (Q. 27:65); relying on soothsayers compromises Tawhid."),
        (32, "Which of the following actions constitutes an act of polytheism (Shirk) in Islamic theology?", "engaging in agricultural work", "participating in competitive sports", "undergoing essential medical surgery", "participating in traditional masquerade or idol-worship rituals", 3, "Venerating masquerades, ancestral spirits, or idols violates the first pillar of Tawhid."),
        (33, "According to Islamic scripture (Surah al-A'la: 19), divine scriptures (Suhuf) were revealed to Prophet", "Harun (Aaron AS)", "Ilyas (Elijah AS)", "Ibrahim (Abraham AS) and Musa (Moses AS)", "Sulaiman (Solomon AS)", 2, "Surah al-A'la (87:19) references 'Suhufi Ibrahima wa Musa' (The scriptures of Abraham and Moses)."),
        (34, "In Islamic creed (Aqidah), the fundamental Articles of Faith (Arkan al-Iman) are exactly", "six (Belief in Allah, Angels, Books, Messengers, Day of Judgment, and Divine Decree)", "five", "four", "seven", 0, "The six pillars of Iman defined in the Hadith of Jibril are belief in Allah, His Angels, His Books, His Messengers, the Last Day, and Al-Qadar."),
        (35, "Delivering the Friday sermon (Khutbah) is an obligatory religious requirement upon the Imam during the", "daily Fajr congregational prayer", "funeral prayer (Salat al-Janazah)", "Friday congregational prayer (Salat al-Jumu'ah)", "Tahajjud night vigil", 2, "Two Khutbahs delivered before the two-unit Jumu'ah prayer are an essential condition for the validity of Friday congregational worship."),
        (36, "Among the mandatory conditions (Shurut al-Wujub) that make daily ritual prayer obligatory on an individual is the", "attainment of noble social rank", "mastery of poetic Arabic", "membership in a specific guild", "attainment of sanity, physical maturity (Bulugh), and purity from major ritual impurities", 3, "Salah is obligatory on every sane, mature (post-pubescent) Muslim free from menstruation or postnatal bleeding."),
        (37, "The recommended supererogatory fast of 'Ashura is observed by Muslims on the", "1st day of Shawwal", "15th day of Sha'ban", "10th day of the sacred month of al-Muharram", "27th day of Rajab", 2, "Fasting on the 10th of Muharram ('Ashura) commemorates the salvation of Prophet Musa (AS) and the Children of Israel from Pharaoh."),
        (38, "Ayyam at-Tashriq (the 11th, 12th, and 13th of Dhul-Hijjah during Hajj) are spiritually designated as days of", "fasting and continuous mourning", "solemn silence and seclusion", "military mobilization", "eating, drinking, remembering Allah, and completing the rites of Mina", 3, "The Prophet (SAW) stated: 'The days of Tashriq are days of eating, drinking, and remembrance of Allah' (fasting is prohibited during these days)."),
        (39, "Under Islamic family jurisprudence (Nikah), the minimum statutory requirement of witnesses to validate a marriage contract is", "four adult male witnesses", "three adult male witnesses", "at least two upright, sane adult male Muslim witnesses", "one witness only", 2, "A valid Islamic marriage requires mutual consent, the guardian's approval (Wali), the bridal gift (Mahr), and at least two upright male witnesses."),
        (40, "Linguistically and jurisprudentially, the comprehensive Arabic term 'Shari'ah' originally means", "a clear, well-trodden path to water, symbolizing the divine legal way of life ordained by Allah", "philosophical wisdom", "human political passion", "a temporary state constitution", 0, "Shari'ah denotes the clear divine path leading to spiritual and moral salvation, derived from the Qur'an and Sunnah."),
        (41, "The eminent classical jurist who suffered imprisonment and died in prison in 150 AH rather than compromise his judicial independence under the Abbasid Caliph al-Mansur was", "Imam al-Shafi'i", "Imam Abu Hanifah", "Imam Ahmad bin Hanbal", "Imam Malik bin Anas", 1, "Imam Abu Hanifah al-Nu'man refused to accept the position of Chief Judge under political coercion, choosing imprisonment where he passed away in 150 AH."),
        (42, "The foundational objectives of the Islamic economic system (Maqasid al-Shari'ah) include", "monopolizing global finance under a single corporation", "authorizing unregulated usurious interest", "forbidding private ownership of property", "prohibiting usury (Riba), fraud, and hoarding while promoting equitable wealth distribution and welfare", 3, "Islamic economics mandates social justice, fair market exchange, Zakat redistribution, and the total prohibition of Riba (interest) and Gharar (deception)."),
        (43, "A grave socioeconomic consequence of usurious interest (Riba) condemned in Islam is that it", "promotes equal economic investment", "fosters economic exploitation, widens inequality, and discourages productive manual enterprise by enabling unearned income", "enhances societal friendship", "reduces commodity prices", 1, "Riba concentrates wealth in the hands of moneylenders while exploiting the needy and encouraging parasitic financial speculation."),
        (44, "In Islamic political governance, the principle of 'Mas'uliyyah' strictly denotes", "military conscription", "monarchical succession", "electoral manipulation", "the sacred accountability and stewardship of public officials to protect community resources and govern with justice", 3, "Mas'uliyyah establishes that every leader is a trustee accountable before Allah and the public for the welfare of the citizens under their care."),
        (45, "In Islamic international diplomacy, Muslims are religiously commanded to honor and fulfill all legitimate covenants and treaties with non-Muslims provided the latter", "adopt the Arabic language", "perform Islamic prayers", "renounce their independent statehood", "do not violate the terms of the agreement, aid enemies, or initiate aggression", 3, "The Qur'an (Surah at-Tawbah: 7) strictly enjoins Muslims to maintain treaties with non-Muslims as long as the other party remains faithful to the treaty terms."),
        (46, "During the pre-Islamic Jahiliyyah era in Arabia, the famous seasonal fair where poets competed in public declamation contests was the Fair of", "'Ukaz", "Mina", "Yathrib", "Ta'if", 1, "The annual Souq 'Ukaz near Makkah was the preeminent cultural festival where the finest Arabic odes (Mu'allaqat) were recited and celebrated."),
        (47, "In pre-Islamic Arabia (Jahiliyyah), the barbaric practice of female infanticide (Wa'd al-banat) was perpetrated primarily out of", "fear of food scarcity and false notions of family dishonor or social disgrace", "scarcity of clean water", "demands by religious priests", "strict royal edicts", 0, "Pagan Arabs buried female babies alive due to poverty fears and misplaced tribal anxieties over honor, a practice abolished by Islam."),
        (48, "The Christian monk in Syria who first recognized the physical and biblical marks of future Prophethood on the young Muhammad (SAW) during a trade journey with Abu Talib was", "Bahira (the monk)", "Waraqah bin Nawfal", "The Negus of Abyssinia", "Salman al-Farsi", 0, "The Syrian monk Bahira recognized the seal of prophethood on the young Muhammad (SAW) and cautioned Abu Talib to protect him."),
        (49, "The earliest converts to Islam from the Prophet's household (such as Khadijah RA and Ali RA) embraced the message immediately because of his lifelong reputation for", "unsurpassed truthfulness, moral integrity, and trustworthiness (As-Sadiq, Al-Amin)", "vast commercial wealth", "military dominance over Makkah", "political ambition to rule Arabia", 0, "Those closest to Prophet Muhammad (SAW) knew his unblemished character, honesty, and piety, making them the first to accept his divine call."),
        (50, "The 19th-century reform movement and writings of Shehu Usman dan Fodio in Northern Nigeria are celebrated for combating", "Islamic scholarship and education", "traditional trade routes", "polytheistic syncretism, oppressive un-Islamic taxation, and the marginalization of women's education", "the Arabic language", 2, "Shehu Usman dan Fodio championed Islamic renewal, eradicated syncretic pagan customs mixed into Islam, and strongly promoted women's Islamic education."),
        (51, "The renowned 14th-century emperor of the Mali Empire who instituted regular Friday congregational prayers, built grand mosques, and undertook a famous Hajj was", "Mansa Musa", "Mansa Suleiman", "Mansa Ule", "Mansa Abubakar II", 0, "Mansa Kankan Musa (reigned 1312-1337) elevated Islamic scholarship and architecture across Mali following his legendary 1324 pilgrimage to Makkah.")
    ]

    lines = []
    lines.append('package com.example.data.repository\n')
    lines.append('import com.example.data.db.QuestionEntity\n')
    lines.append('object JambIrsQuestionBank {')
    lines.append('    fun getQuestions(): List<QuestionEntity> {')
    lines.append('        return listOf(')

    for q in irs_raw:
        num, text, a, b, c, d, ans, exp = q
        qid = f"irs_2011_{num:03d}"
        topic = "Islamic Religious Studies"
        if "qur'an" in text.lower() or "surah" in text.lower() or "tafsir" in text.lower() or "tajwid" in text.lower():
            topic = "Quranic Studies & Exegesis"
        elif "hadith" in text.lower() or "nawawi" in text.lower() or "bukhari" in text.lower() or "dawood" in text.lower():
            topic = "Hadith & Sunnah"
        elif "tawhid" in text.lower() or "iman" in text.lower() or "shirk" in text.lower() or "pillar" in text.lower():
            topic = "Tawhid & Articles of Faith"
        elif "prayer" in text.lower() or "fast" in text.lower() or "hajj" in text.lower() or "nikah" in text.lower() or "shari'ah" in text.lower() or "riba" in text.lower() or "economic" in text.lower():
            topic = "Fiqh, Ibadah & Islamic Ethics"
        elif "prophet" in text.lower() or "cave hira" in text.lower() or "jahiliyyah" in text.lower() or "fodio" in text.lower() or "mali" in text.lower() or "mansa" in text.lower() or "caliph" in text.lower():
            topic = "Sirah & Islamic History"

        text_escaped = text.replace('"', '\\"')
        a_esc = a.replace('"', '\\"')
        b_esc = b.replace('"', '\\"')
        c_esc = c.replace('"', '\\"')
        d_esc = d.replace('"', '\\"')
        exp_esc = exp.replace('"', '\\"')

        lines.append(f'''            QuestionEntity(
                id = "{qid}",
                subject = "Islamic Religious Studies (IRS)",
                topic = "{topic}",
                year = "2011",
                questionText = "{text_escaped}",
                optionA = "{a_esc}",
                optionB = "{b_esc}",
                optionC = "{c_esc}",
                optionD = "{d_esc}",
                correctAnswerIndex = {ans},
                explanation = "{exp_esc}",
                difficulty = "Medium",
                originType = "JAMB_ORIGINAL",
                originLabel = "Original JAMB Question • 2011",
                isVerifiedJamb = true
            ),''')

    lines.append('        )')
    lines.append('    }')
    lines.append('}\n')

    with open("app/src/main/java/com/example/data/repository/JambIrsQuestionBank.kt", "w") as f:
        f.write("\n".join(lines))
    print("IRS generated: 51 questions")

if __name__ == "__main__":
    generate_geography()
    generate_history()
    generate_irs()
