import re
import os

raw_commerce_text = """
Commerce	1994	1	Commerce is defined as the study of how	A. man utilizes the resources in his physical environmentB. man produces, distributes and consumes his goods and servicesC. man buys, sells and distributes goods and servicesD. raw materials are changed into finished goods.	C. man buys, sells and distributes goods and services	Commerce is the branch of production that deals with the exchange of goods and services, as well as all activities that facilitate this exchange (aids to trade).
Commerce	1994	2	The type of activity which turns processed raw materials into consumer and industrial goods is described as	A. extractiveB. manufacturingC. constructiveD. processing	B. manufacturing	Manufacturing industries convert processed raw materials into finished consumer or industrial goods (e.g., turning flour into bread).
Commerce	1994	3	The production process that combines two or more raw materials into one end product is	A. conditioningB. blendingC. mergingD. synthesis.	D. synthesis.	Synthetic production combines two or more separate chemical or physical materials to form a completely new product (e.g., making cement or plastics).
Commerce	1994	4	A demonstration of social responsibility by a business is the payment of	A. taxes to governmentB. dividends to shareholdersC. interest on loansD. premium for insurance.	A. taxes to government	Fulfilling legal obligations, such as paying corporate taxes to the government, is a fundamental dimension of a business's social and civic responsibility.
Commerce	1994	5	A distinguishing characteristic of a limited liability company is that it	A. is a collection of many sole proprietorsB. is a multiple partnershipC. can sue and be suedD. has limited resources.	C. can sue and be sued	An incorporated company is a legal entity distinct from its owners; it possesses corporate personality, meaning it can sue and be sued in its own name.
Commerce	1994	6	Which of the following takes place when firms producing at different stages in the same industry combine?	A. ConglomerationB. Vertical integrationC. Horizontal integrationD. Cartel.	B. Vertical integration	Vertical integration occurs when firms at different, sequential stages of production or distribution in the same industry merge (e.g., a tannery merging with a shoe factory).
Commerce	1994	7	Which of the following groups is paid first when a firm liquidates?	A. Preference shareholders.B. Debenture holdersC. Ordinary shareholders.D. Cumulative preference shareholders.	B. Debenture holders	Debenture holders are external creditors of a company. Upon liquidation, all creditors must be paid in full before any class of shareholders receives residual funds.
Commerce	1994	8	Compulsory dissolution of a business can arise from	A. an agreement by the ownersB. a declaration by a court of lawC. the termination of its lifeD. an unfavourable economic climate.	B. a declaration by a court of law	A business can be compulsorily wound up or dissolved by an order or declaration issued by a court of competent jurisdiction, often due to insolvency or illegal acts.
Commerce	1994	9	Based on the balance sheet of MBV Enterprises, what is the circulating capital of the sole proprietor?	A. N27,380B. N34,980C. N36,180D. N51,680	D. N51,680	Circulating capital is another term for current assets. According to the balance sheet, current assets sum up to N51,680.
Commerce	1994	10	Based on the balance sheet of MBV Enterprises, what is the working capital as at December 31, 1992?	A. N65,250B. N60,000C. N48,650D. N41,950	D. N41,950	Working Capital is calculated as Current Assets minus Current Liabilities: N51,680 (Current Assets) - N9,730 (Creditors / Current Liabilities) = N41,950.
Commerce	1994	11	A company earned a total revenue of N108 million with a total cost of N91 million in 1991. If it paid 45% tax on its gross profit for that year, determine its net profit.	A. N24.65 million.B. N17.00 million.C. N9.35 million.D. N7.65 million.	C. N9.35 million.	Gross Profit = N108m - N91m = N17m. Tax is 45% of N17m = N7.65m. Net Profit = N17m - N7.65m = N9.35 million.
Commerce	1994	12	What are fixtures and fittings in a balance sheet?	A. Liquid capitalB. Current assetsC. Fixed assetsD. Working capital	C. Fixed assets	Fixtures and fittings are long-term, tangible physical properties owned by a business for ongoing operations and are classified under fixed assets.
Commerce	1994	13	Governments impose import duties for the following reasons EXCEPT	A. to raise revenue for other servicesB. to act as a retaliatory measure against other governmentsC. to discourage the redistribution of income at homeD. to protect home industries from external competition.	C. to discourage the redistribution of income at home	Import duties protect infant industries, raise state revenue, and retaliate against trade policies, but they are not used to discourage domestic income redistribution.
Commerce	1994	14	A sole enterprise may flourish best in	A. a mining businessB. a retailing businessC. an oil exploration businessD. a car assembly business	B. a retailing business	Sole proprietorships excel in retailing due to low initial capital requirements, flexibility of operations, and the need for close personal contact with consumers.
Commerce	1994	15	The use of coin-operated machines to sell goods is a form of	A. personal sellingB. retailingC. wholesalingD. mail-order selling.	B. retailing	Vending machines are automated retailing mechanisms that sell goods in small quantities directly to final consumers.
Commerce	1994	16	What is a major function of the wholesaler?	A. Buying from small-scale producers and selling to exporters.B. Distributing to consumers directly.C. Organizing cooperative retail stores.D. Providing information to manufacturers on market situation.	D. Providing information to manufacturers on market situation.	Wholesalers act as vital feedback links between retailers and manufacturers, providing valuable market research on consumers' preferences and demand trends.
Commerce	1994	17	The rate at which a country’s exports exchange for its imports is called	A. balance of paymentsB. balance of tradeC. terms of paymentD. terms of trade.	D. terms of trade.	Terms of trade measure the ratio of a country's export price index to its import price index, reflecting the rate of commodity exchange.
Commerce	1994	18	The difference between the total payments for imports and the receipts from exports within a given period is referred to as	A. balance of paymentsB. balance of tradeC. comparative cost advantageD. comparative advantage	B. balance of trade	The Balance of Trade is the net difference between the monetary value of a nation's exports and imports of physical, tangible merchandise.
Commerce	1994	19	A pro forma invoice is NOT required when	A. quoting for the supply of goodsB. goods are sent on approvalC. dealing regularly with a customerD. final prices are uncertain.	C. dealing regularly with a customer	A pro forma invoice acts as a preliminary quotation or for goods on approval; regular customers are billed using standard commercial invoices.
Commerce	1994	20	Which of the following statements is TRUE about sea transport?	A. All ships have specific routes to ply.B. All ships must be insured at every journeyC. All ships are insured separately from the crewD. All ships normally arrive at their destination with goods.	C. All ships are insured separately from the crew	Under marine insurance law, ship hulls, cargo, and crews are covered under completely separate insurance policies.
Commerce	1994	21	The postal organization which preceded the Nigerian Postal Service was	A. Post and TelecommunicationsB. Post and TelephoneC. Post and TeleprinterD. Post and Telegraph.	A. Post and Telecommunications	Before NIPOST was established, postal and telecommunication services in Nigeria were run by the government department known as Post and Telecommunications (P&T).
Commerce	1994	22	Goods discharged from ships on which import duties have not been paid are kept in the	A. ordinary warehouseB. public warehouseC. private warehouseD. bonded warehouse.	D. bonded warehouse.	A bonded warehouse is a secure, customs-controlled storage facility where dutiable goods are kept until import duties are fully paid.
Commerce	1994	23	A sole proprietor insured his goods worth N200,000 for half the value. There was a fire incident in which goods valued at N80,000 were destroyed. The value of compensation expected from the insurer is	A. N40,000B. N80,000C. N100,000D. N200,000	A. N40,000	Under the Average Clause rule of insurance, compensation = (Sum Insured / Actual Value) * Actual Loss = (100,000 / 200,000) * 80,000 = N40,000.
Commerce	1994	24	One of the effects of the devaluation of the Naira is that the	A. goods that can be imported with the Naira have become cheaperB. value of other currencies relative to the Naira have become cheaperC. goods that can be exported from Nigeria have become costlierD. imports that can be bought with the Naira have become costlier.	D. imports that can be bought with the Naira have become costlier.	Devaluation reduces the external value of a national currency, making foreign-produced import commodities far more expensive in domestic terms.
Commerce	1994	25	Drawing two parallel lines across a cheque means that it has to be paid into the account of the	A. payeeB. drawerC. draweeD. payer.	A. payee	Crossing a cheque with two parallel lines serves as an instruction to paying banks that the cheque cannot be cashed over the counter; it must be paid directly into the payee's bank account.
Commerce	1994	26	The specialized bank established by the Federal Government to facilitate international trade is the	A. Central Bank of NigeriaB. Federal Savings BankC. Nigerian Industrial Development BankD. Nigerian Export-Import Bank.	D. Nigerian Export-Import Bank.	The Nigerian Export-Import Bank (NEXIM) provides credit guarantees, export credit insurance, and trade information to support international trade.
Commerce	1994	27	Which of the following is both a direct and indirect credit enterprise?	A. Co-operative and thrift society.B. Retail co-operative society.C. Consumer co-operative society.D. Wholesaler co-operative society.	A. Co-operative and thrift society.	A cooperative thrift and credit society pools members' savings to directly advance cash loans and indirectly provide credit resources on favorable terms.
Commerce	1994	28	The business in the stock exchange is characterized essentially by	A. dealing.B. brokerageC. speculationD. transactions.	C. speculation	The activities of brokers, bulls, bears, and stags on the stock exchange are highly speculatively oriented around expected future price changes of securities.
Commerce	1994	29	The Second-Tier Securities Market is	A. an appendage to the Nigerian Stock ExchangeB. a member of the Nigeria Stock ExchangeC. meant for the shares of the quoted private companiesD. a regulating arm of the Nigeria Stock Exchange	A. an appendage to the Nigerian Stock Exchange	The Second-Tier Securities Market (SSM) was established as an arm or appendage of the NSE to allow small and medium-scale indigenous firms to raise public capital.
Commerce	1994	30	The elements of the marketing mix are	A. product, promotion, place and price.B. personal selling, advertising and research.C. promotion, production, place and price.D. procurement, price, product and place.	A. product, promotion, place and price.	The standard marketing mix (the 4 Ps) comprises: Product, Price, Place (distribution), and Promotion.
Commerce	1994	31	Which of the following items has the shortest effect on the consumer?	A. Fashion.B. Innovation.C. FadD. Attribute.	C. Fad	A fad is an intense, short-lived consumer enthusiasm or fashion trend that emerges rapidly and declines just as quickly.
Commerce	1994	32	Which of the following is a form of sales promotion?	A. Advertising on radio.B. Offering free samples.C. Distributing printed materials.D. Advertising on Television.	B. Offering free samples.	Sales promotions are short-term incentive schemes (e.g., free samples, discounts, coupons) designed to stimulate immediate consumer purchases.
Commerce	1994	33	One advantage of personal selling over all other elements of promotion is that	A. it can provide instant feedbackB. it is very cheap in terms of cost per contractC. it does not need to use mass mediaD. sales people are well trained.	A. it can provide instant feedback	Personal selling involves direct, face-to-face interaction, allowing the sales representative to receive and adapt to instant verbal and non-verbal feedback from the buyer.
Commerce	1994	34	Which of the following must be present in an agency by agreement?	A. Intentions.B. Will.C. Consent.D. Authority.	C. Consent.	An agency relationship created by agreement requires the mutual consent and meeting of minds of both the principal and the agent.
Commerce	1994	35	An agreement to sell is distinguishable from a sale because in the former, the transfer of goods is	A. not anticipated.B. not discussed.C. deferred.D. immediate.	C. deferred.	In a sale, the transfer of ownership of the goods is immediate. In an agreement to sell, the transfer of title is deferred to a future date or subject to some conditions.
Commerce	1994	36	Mr. Amusa says to Mr Bello 'I will sell you this hat for N30'. And Mr Bello replied 'I will pay N29'. The contract is	A. an offer and acceptanceB. an implied contract.C. a complete simple contract.D. an offer but no acceptance.	D. an offer but no acceptance.	Mr. Bello's response is a counter-offer, which legally rejects and terminates the original offer. Therefore, there is an offer but no valid acceptance has occurred.
Commerce	1994	37	Nationalization of an industry means that its ownership becomes that of	A. government.B. shareholders.C. consumers.D. communities.	A. government.	Nationalization is a state policy that compulsorily transfers ownership, control, and assets of private industries to the federal government.
Commerce	1994	38	The pre-shipment inspection scheme was set up by the federal government in order to	A. reverse Nigeria’s unfavourable balance.B. promote fair trade between Nigeria and other countries.C. counteract all fraudulent business deals of Nigerians with other nationals.D. ensure that imports into Nigeria are of the correct quality, value and quantity.	D. ensure that imports into Nigeria are of the correct quality, value and quantity.	Pre-shipment inspection protects the economy by physically verifying the quality, technical specifications, value, and volume of foreign imports before shipment.
Commerce	1994	39	Which of the following has powers to order withdrawal of a particular food item from circulation?	A. Standards Organisation of Nigeria.B. Federal High Courts in Nigeria.C. Food and Drugs Department of the Federal Ministry of Health.D. Local government health inspectors.	C. Food and Drugs Department of the Federal Ministry of Health.	The Food and Drugs Department (or regulatory successors like NAFDAC) has the legal authority to order public recalls of adulterated, unsafe, or contaminated consumables.
Commerce	1994	40	Which of the following maxims negates the principle of collective bargaining?	A. Individual employees have weak bargaining base.B. Individual employees attain strength when they come together in a union.C. Only members of the union can benefit from agreements negotiated by the union.D. Collective bargaining covers the vast majority of employees, whether union members or not.	C. Only members of the union can benefit from agreements negotiated by the union.	Collective bargaining is designed to establish general working frameworks that cover and benefit all employees across the firm, regardless of union membership.
Commerce	1994	41	NACCIMA stands for	A. Nigerian-American Centre for Culture Industries, Mines and ArtsB. Nigerian Association for Culture, Civics, Industries, Minerals and ArtsC. National Agency for Culture, Civilization, Investments, Manufacturing and AgricultureD. Nigerian Association of Chambers of Commerce, Industries, Mines and Agriculture.	D. Nigerian Association of Chambers of Commerce, Industries, Mines and Agriculture.	NACCIMA stands for the Nigerian Association of Chambers of Commerce, Industry, Mines and Agriculture, representing the private sector business voice.
Commerce	1994	42	For the establishment of a powerful consumers’ association in Nigeria to exist, there must be	A. financial and moral support from the public.B. honest and committed leadership.C. allocation of goods from the producers.D. freedom from external influence.	B. honest and committed leadership.	Developing structured, powerful consumer defense associations requires dedicated, highly principled, and honest leadership to mobilize citizens.
Commerce	1994	43	Which of the following is the most important business resource?	A. Money.B. ManagementC. MaterialsD. Manpower.	D. Manpower.	Manpower (human capital) is the most critical resource because humans coordinate, manage, and operate all other inanimate resources (money, machinery, materials).
Commerce	1994	44	The harmonization of all individual and unit efforts in an organization is ensured through	A. co-ordinationB. motivationC. planning.D. leadership.	A. co-ordination	Coordination is the managerial process of unifying and synchronizing diverse organizational activities and objectives to achieve a common goal.
Commerce	1994	45	The principle of span of control stipulates that	A. an employee should report to only one superiorB. managers must demand accountability from their subordinatesC. resources have to be economized within the various divisionsD. the number of employees reporting to one superior should be kept to a workable maximum.	D. the number of employees reporting to one superior should be kept to a workable maximum.	Span of control defines the maximum number of direct subordinates a manager can supervise efficiently and effectively.
Commerce	1994	46	Which of the following makes other functions of business its appendages?	A. Production.B. Marketing.C. Finance.D. Personnel.	B. Marketing.	Under modern marketing philosophy, the business exists to satisfy consumer needs; thus, production, finance, and personnel are aligned around marketing outcomes.
Commerce	1994	47	The use of computers in modern banking industry is a reflection of	A. competitive developmentB. scientific developmentC. economic developmentD. technological development	D. technological development	Adopting information systems, database servers, and computing machines in banking is a direct outcome of global technological development.
Commerce	1994	48	When an oil exploring and mining company builds a health centre in one of the communities where it operates, such a company is	A. currying favour from local peopleB. finding a way to spend excess profitsC. fulfilling part of its social responsibilityD. investing its idle funds.	C. fulfilling part of its social responsibility	Corporate Social Responsibility (CSR) requires corporate entities to contribute positively to the development and social welfare of host communities.
Commerce	1994	49	The West African Clearing House became legally operational on	A. 1st July, 1976B. 25th June, 1975C. 14th March, 1975D. 3rd May, 1974	A. 1st July, 1976	The West African Clearing House (WACH) was established in Freetown to handle multilateral settlements, becoming operational on July 1, 1976.
Commerce	1994	50	The Lake Chad Basin Commission was founded to enable member states to	A. expand the volume of water in the Lake for fishing activityB. increase navigational activities on the lakeC. dam the lake for electricity and agricultural purposes.D. co-ordinate their efforts in managing the use of the lake’s resources.	D. co-ordinate their efforts in managing the use of the lake’s resources.	The LCBC was founded in 1964 by countries bordering Lake Chad to regulate and manage the scarce ecological, water, and fishery resources of the basin.
"""

# Let's save a parser for generating all 9 parts.
print("Parsing 1994 questions...")
