# -*- coding: utf-8 -*-
import os
import generate_all_complete_banks

# ==========================================
# 1. COMMERCE (PT. 1 - 5)
# ==========================================
commerce = []
def add_com(pt, topic, q, a, b, c, d, ans, exp, num):
    commerce.append({
        "id": f"jamb_com_p{pt}_{num:02d}",
        "subject": "Commerce",
        "topic": topic,
        "year": f"Part {pt}",
        "questionText": q,
        "optionA": a,
        "optionB": b,
        "optionC": c,
        "optionD": d,
        "correctAnswerIndex": ans,
        "explanation": exp,
        "originLabel": f"JAMB Commerce • Part {pt} (Q{num})"
    })

# Part 1
add_com(1, "Nature of Commerce", "The most important function of commerce is in _____.", "enhancing business relationships", "helping people to improve their profits", "facilitating exchange among individuals and firms", "assisting trade through banking and insurance", 2, "The fundamental role of commerce is facilitating the exchange and distribution of goods and services between producers and consumers.", 2)
add_com(1, "Occupations", "The three main classifications of occupation are _____.", "construction, trade and services", "manufacturing, industry and services", "farming, banking and trading", "industry, commerce and services", 3, "Occupations are broadly divided into Industry (extractive, manufacturing, constructive), Commerce (trade and aids to trade), and Direct/Indirect Services.", 3)
add_com(1, "Occupations", "An oil exploration company is engaged in _____.", "tertiary production", "constructive occupation", "extractive occupation", "secondary production", 2, "Extractive occupations involve extracting raw materials directly from the earth, soil, or sea (e.g. oil drilling, mining, farming).", 4)
add_com(1, "Services", "Service rendered to the public is provided by _____.", "government", "civil servants", "professionals", "domestic servants", 1, "Civil servants provide direct indirect public services on behalf of the state/government to the general citizenry.", 1)
add_com(1, "Production", "The creation of goods and services to satisfy human wants is referred to as _____.", "manufacturing", "commercialization", "production", "entrepreneurship", 2, "Production is defined as the creation of utility (goods and services) to satisfy human needs and wants.", 6)
add_com(1, "Division of Labour", "Which of the following is a limitation of division of labour?", "Decline in craftsmanship", "Monotony of work", "Reduction in output", "Reduction in labour force", 1, "Monotony (boredom from repeating the same repetitive task) is a major limitation and psychological drawback of division of labour.", 7)
add_com(1, "Production", "Resources obtained from the extractive sector that are transformed into finished products are examples of _____.", "primary production", "tertiary production", "direct production", "secondary production", 3, "Secondary production involves converting raw materials obtained from primary/extractive industries into finished manufactured goods.", 8)

diag_com_tree = """[DIAGRAM: Structure of Commerce:
Commerce branches into:
- Trade (Home Trade [Retailer, Wholesaler] & Foreign Trade [Export, Import])
- [I] (Auxiliaries/Aids to Trade: Banking, Insurance, Transport, Warehousing, Advertising, Communication)]"""

add_com(1, "Structure of Commerce", f"{diag_com_tree}\n\nFrom the diagram above, what does I stand for?", "Aids to trade", "Publicity", "Home trade", "Advertising", 0, "Commerce comprises two broad divisions: Trade (Home and Foreign) and Aids to Trade (auxiliary services like transport, banking, insurance, warehousing, and advertising).", 9)
add_com(1, "Channels of Distribution", "An individual that links the producer with the retailer is _____.", "an agent", "a wholesaler", "an entrepreneur", "a principal", 1, "The wholesaler buys in large bulk from manufacturers and breaks it down to sell in smaller quantities to retailers.", 10)
add_com(1, "Retail Trade", "One of the functions of a retailer is the _____.", "financing of production activities", "provision of credit facilities to relations", "provision of jobs for customers", "breaking of bulk", 3, "Retailers buy in medium quantities from wholesalers and sell in small single units (breaking bulk) to final consumers.", 11)
add_com(1, "Direct Selling", "The main aim of selling directly to the consumers by manufacturers is to _____.", "reduce transportation cost", "make contact with individual consumers", "discourage the activities of middlemen", "maximize profit margin", 3, "Direct marketing eliminates middleman markups, enabling the producer to maximize profit margins and control consumer pricing.", 12)
add_com(1, "Foreign Trade", "Balance of payment problems arise if a country's _____.", "exports are more than imports", "imports are more than exports", "currency devaluation", "invisible exports are more than visible exports", 1, "A balance of payments deficit (problem) occurs when total payments for imports exceed total receipts from exports.", 13)
add_com(1, "Foreign Trade", "The three components of a country's balance of payments are _____.", "current account, capital account and monetary movement account", "capital account, trade account and business record", "sales account, profit and loss account and capital account", "monetary movement account, trade account and sales ledger", 0, "Balance of payments comprises Current Account, Capital/Financial Account, and Monetary Movement/Official Reserve Account.", 14)
add_com(1, "Negotiable Instruments", "A document that indicates obligation that is transferable by delivery and endorsement is a _____.", "bill of lading", "bill of exchange", "documentary evidence", "negotiable instrument", 3, "A negotiable instrument (e.g. cheque, bill of exchange, promissory note) confers legal title transferable by simple delivery or endorsement.", 15)
add_com(1, "Shipping Documents", "The document which can be exchanged for a bill of lading is _____.", "freight note", "mate receipt", "export invoice", "ship report", 1, "A Mate's Receipt is issued by the chief mate upon loading cargo; it is later exchanged at the shipping company's office for the official Bill of Lading.", 16)
add_com(1, "Terms of Delivery", "The price quoted which includes the cost of insurance, freight and all delivery charges to the importer's warehouse is _____.", "Free Alongside Ship", "Franco", "Free on Board", "Free on Rail", 1, "Franco (or Free Delivered) means the quoted price covers all costs including insurance, freight, customs duties, and delivery to the buyer's premises.", 17)
add_com(1, "Terms of Payment", "The purchase of goods under the CWO system of payment implies that _____.", "money must be enclosed when ordering", "payment must be made on delivery", "payment must be made within few days", "cash must be paid on the spot", 0, "CWO stands for Cash With Order; payment in full must accompany the purchase order.", 18)
add_com(1, "Advertising", "The most effective but limited medium of advertising in Nigeria is _____.", "billboard", "television", "newspaper", "radio", 1, "Television combines sight, sound, and motion for maximum impact, but is limited by electricity availability and reach compared to radio.", 1)
add_com(1, "Banking", "A cheque that has been drawn but not presented for payment can still be honoured _____.", "within 6 months", "after 9 months", "within 9 months", "after 6 months", 0, "A cheque remains valid and legally payable up to 6 months from the date of issue, after which it becomes stale.", 20)
add_com(1, "Banking", "The major source of income to commercial banks is _____.", "loans", "deposits", "interest", "overdrafts", 2, "Commercial banks earn their primary income from interest charged on loans, overdrafts, and credit advances.", 21)
add_com(1, "Aids to Trade", "An ancillary to trade that easily links suppliers with consumers is _____.", "tourism", "banking", "communication", "transportation", 2, "Communication (telephone, email, postal services) enables swift exchange of information and inquiries between buyers and sellers.", 22)
add_com(1, "Insurance Principles", "Mr. Lawal insured his warehouse against burglary but it was later gutted by fire. This implies that _____.", "the loss should be borne by the insurer", "Mr. Lawal is liable only for half of the estimated loss", "the insurer should make a consolation payment for the loss", "the loss should be borne by Mr. Lawal", 3, "Under the principle of Proximate Cause, insurers only compensate for losses directly resulting from the specific insured peril (burglary, not fire).", 23)
add_com(1, "Insurance", "The agreement of insurers to spread risks among themselves is a major feature of _____.", "reinsurance", "life insurance", "underwriter", "marine insurance", 0, "Reinsurance allows an insurance company to insure part of its accepted risk with another insurer to prevent catastrophic loss.", 24)
add_com(1, "Tourism", "Inbound tourism occurs when _____.", "non-residents of a country travel to other countries", "resident of a country travel to another country", "non-resident of a country travel within it", "resident of a country travel within it", 2, "Inbound tourism refers to visits to a country by non-residents of that country.", 25)
add_com(1, "Transportation", "One of the major disadvantages of pipeline transportation is its _____.", "high cost of construction", "limitation in scope", "vulnerability to climate changes", "high maintenance cost", 1, "Pipelines are limited in scope because they can only transport fluids, gases, and slurries along fixed routes.", 26)
add_com(1, "Business Organizations", "The business organization that can effectively combine management with control is _____.", "private limited liability company", "sole proprietorship", "public limited liability company", "co-operation society", 1, "In a sole proprietorship, ownership, day-to-day management, and ultimate operational control reside completely in one individual.", 27)
add_com(1, "Business Combinations", "When two or more companies agree to execute a project too large for one to handle, this is referred to as _____.", "an amalgamation", "a cartel", "a merger", "a consortium", 3, "A consortium is a temporary association of two or more independent enterprises formed to pool resources and execute a massive contract.", 28)
add_com(1, "Company Liquidation", "In the event of voluntary liquidation, the appointment of a liquidator is the responsibility of the _____.", "directors", "creditors", "promoters", "court", 1, "In a creditors' voluntary liquidation or members' liquidation, the company's members/creditors appoint the liquidator.", 1)
add_com(1, "Business Finance", "A source of business financing which involves pledging of a specific asset is _____.", "bond", "mortgage", "debentures", "loan", 1, "A mortgage is a secured loan where immovable property (land, building) is pledged as collateral security.", 30)
add_com(1, "Trade Associations", "An example of a trade association is _____.", "ALGON", "NLC", "NURTW", "NULGE", 2, "NURTW (National Union of Road Transport Workers) is an occupational/trade union protecting the commercial interests of transport operators.", 31)
add_com(1, "Stock Exchange", "A broker is an agent who links a potential investor with _____.", "a shareholder who wants to register a company", "other members of the exchange who want to trade", "government official on the exchange", "a quoted company", 1, "Stockbrokers act as middlemen who buy and sell shares on the floor of the stock exchange on behalf of investors.", 32)
add_com(1, "Stock Exchange", "Second-tier Securities Market differs from the First-tier Securities Market in that the former is _____.", "highly restricted", "regulated by the SEC", "regulated by the NIPC", "less restricted", 3, "SSM (Second-tier Securities Market) has less stringent listing and capital requirements, designed to help small and medium-scale enterprises raise equity.", 33)
add_com(1, "Information Systems", "A communication process providing information for decision-making in an organization is the _____.", "Management Information System (MIS)", "Transmission Control Protocol", "Information Retrieval System", "File Transfer Protocol", 0, "A Management Information System (MIS) collects, processes, and presents operational data to assist managers in decision-making.", 34)
add_com(1, "Management", "The managerial ability of a supervisor in an organization may be underutilized if the _____.", "morale of the supervised is high", "span of control is wide", "span of control is narrow", "morale of the supervisor is low", 2, "A very narrow span of control (too few subordinates) underutilizes the manager's capacity and creates unnecessary administrative overhead.", 35)
add_com(1, "Management", "The arrangement and interrelationship of the various components and positions of a business is referred to as _____.", "organizational structure", "clarity of objective", "unity of direction", "line structure", 0, "Organizational structure establishes hierarchical relationships, authority lines, and departmental divisions in an enterprise.", 36)
add_com(1, "Marketing", "The variety of goods and services which a company offers for sale is its _____.", "place mix", "promotion mix", "price mix", "product mix", 3, "Product mix (or product assortment) refers to the complete set of product lines and items offered for sale by a company.", 37)
add_com(1, "Sales Promotion", "Activities undertaken to create awareness for goods by conducting contests is _____.", "marketing concept", "consumerism", "sales promotion", "marketing mix", 2, "Contests, sweepstakes, free samples, and rebates are classic sales promotion tools to stimulate immediate consumer demand.", 38)
add_com(1, "Advertising", "The slogan, 'a wonderful world', used by a communication network is a form of _____.", "product differentiation", "persuasive advertising", "publicity", "packaging", 1, "Persuasive advertising uses emotional appeals and catchy slogans to convince consumers to favor a particular brand.", 39)
add_com(1, "Law of Contract", "To make a simple contract valid, the intention must be _____.", "legal and written", "legal and binding (intention to create legal relations)", "legal and attractive", "legal and harmonious", 1, "A valid contract requires an intention to create legal, enforceable, and binding obligations between parties.", 40)
add_com(1, "Law of Agency", "The major parties to an agency relationship are the _____.", "principal and the creditor", "Bailee and the bailor", "principal and the agent", "shareholder and the creditor", 2, "An agency relationship is formed between a Principal (who delegates authority) and an Agent (who acts on the principal's behalf).", 41)
add_com(1, "Employment Law", "One of the obligations of an employer to an employee is to _____.", "indemnify him against liabilities incurred on duty", "award scholarship to his children", "terminate his appointment without prior notice", "indemnify him against injuries caused through negligence", 0, "An employer has a legal duty to indemnify the employee against expenses, damages, and liabilities incurred in the lawful execution of duties.", 42)
add_com(1, "Consumer Protection", "The body charged with the responsibility of regulating foods and drugs in Nigeria is the _____.", "SON", "NDLEA", "NAFDAC", "CAC", 2, "NAFDAC (National Agency for Food and Drug Administration and Control) regulates food, cosmetics, chemicals, and pharmaceuticals.", 43)
add_com(1, "Computer Systems", "The physical components of a computer system refers to the _____.", "system unit", "hardware", "software", "compact disk", 1, "Hardware comprises all tangible, physical components of a computer system (CPU, keyboard, monitor, circuitry).", 44)
add_com(1, "Operating Systems", "An example of a computer operating system is _____.", "the PageMaker", "the Word Perfect", "Microsoft Word 2000", "Windows 2000", 3, "Windows 2000 is an operating system, whereas PageMaker and MS Word are application software packages.", 45)
add_com(1, "Networking", "Intranet differs from extranet in that the former _____.", "requires a modem before it could be used", "can generally be accessed by the public", "is restricted to employees of an organization", "requires internet protocols", 2, "An intranet is a private network strictly restricted to internal employees, whereas an extranet grants controlled access to external authorized partners.", 46)
add_com(1, "Internet & Software", "A software application which enables a user to display and interact with texts, images and videos is the _____.", "web server", "Internet Protocol", "CorelDraw", "web browser", 3, "A web browser (Chrome, Firefox, Edge) renders HTML/multimedia web documents for user interaction.", 47)
add_com(1, "Internet Protocols", "A predominant markup language for web pages is _____.", "IP", "HTTP", "HTML", "TCP", 2, "HTML (HyperText Markup Language) is the standard markup language used to structure web pages.", 48)
add_com(1, "Email Addressing", "The symbol '@' in an internet mail address is used to _____.", "separate the user name from the machine/domain name", "link the user with other Internet users", "locate the addresses of Internet users", "link the user with the machine", 0, "The '@' symbol separates the individual user's mailbox identifier from the domain name host server (e.g. user@domain.com).", 49)
add_com(1, "Social Responsibility", "A business organization is said to be socially responsible when it _____.", "gets involved in issues relating to the society", "rewards its staff for long-term service", "offers discounts to customers", "invites the public to its annual general meetings", 0, "Corporate social responsibility entails voluntarily investing in community development, environmental protection, and public welfare.", 50)

# Write Commerce Complete Bank
generate_all_complete_banks.write_kotlin_bank(
    "JambCommercePt1to5CompleteBank.kt",
    "JambCommercePt1to5CompleteBank",
    "Complete Verified JAMB Commerce Past Questions (Parts 1 to 5) with Answers and Explanations",
    commerce
)
print("Commerce bank generated successfully")

