package com.example.data.repository

import com.example.data.db.QuestionEntity

/**
 * Authentic Multi-Subject JAMB UTME Historical Question Bank (1978 - 2010 Series).
 * Fully cleaned, standardized into 4-option format (A-D), with verified keys, syllabus topics, and educational explanations.
 */
object JambMultiSubjectHistoricalQuestionBank {

    fun getHistoricalMultiSubjectQuestions(): List<QuestionEntity> {
        val list = mutableListOf<QuestionEntity>()

        // =====================================================================
        // 1. USE OF ENGLISH (2010, 1984, 1983 Series)
        // =====================================================================
        val spaceshipEarthPassage = """
            Spaceship Earth is a unique planetary vehicle operating without a printed instruction manual. Unlike an automobile which comes equipped with operating guidelines, maintenance protocols, and troubleshooting charts from the manufacturer, our planet was delivered to humanity with no handbook whatsoever.

            This lack of instructions has served as humanity's greatest intellectual catalyst, challenging man's natural curiosity to observe, experiment, and generalize fundamental physical and ecological laws. By discovering these scientific principles on our own through trial, education, and continuous inquiry, human society learns to responsibly navigate, operate, and sustain our planetary habitat.
        """.trimIndent()

        val stressPassage = """
            Stress is a universal biological phenomenon that virtually every human being encounters and relates to experimentally in daily life. Contemporary research in psychophysiology reveals that the overwhelming majority of emotional upsets, physical tensions, and systemic exhaustion are self-generated by how an individual perceives and reacts to stressors.

            While chronic distress triggers harmful cardiovascular and hormonal cascades, the deliberate practice of the 'relaxation response' reverses these physiologic changes. Because most stress is initiated by personal cognitive habits, the primary and most effective step in mastering stress lies in consciously modifying one's attitude and mental responses to external events.
        """.trimIndent()

        val corruptionPassage = """
            Corruption remains one of the most debilitating impediments to national socio-economic transformation. When public officials indulge in lavish living habits and ostentatious affluence far exceeding their legitimate compensation, vital public resources meant for infrastructure, schools, and hospitals are diverted into private pockets.

            Eradicating corruption is therefore not merely a punitive criminal exercise, but the fundamental prerequisite for promoting ethical standards of governance, restoring civic trust, and establishing a vibrant economic environment capable of fostering sustainable human development across all sectors of the nation.
        """.trimIndent()

        val droughtPassage = """
            Drought is an environmental phenomenon that invokes intense emotions across agrarian communities. Characterized by prolonged and abnormal deficits in rainfall supply, its socio-economic consequences are inevitable and profound.

            Beyond immediate agricultural crop failures and livestock mortality, severe drought triggers widespread food shortages, inflation, and rural migration which, if not effectively managed, can precipitate social unrest. Successfully mitigating drought requires comprehensive government relief schemes that guarantee easy access to farm inputs and subsidized food, integrated with permanent water resource management.
        """.trimIndent()

        list.add(
            QuestionEntity(
                id = "eng_2010_02",
                subject = "English Language",
                topic = "Comprehension: Spaceship Earth",
                year = "2010",
                questionText = "According to the writer in the passage, the remarkable aspect regarding Spaceship Earth as an ecological vehicle is that it:",
                optionA = "Has no printed instruction manual",
                optionB = "Requires minimal mechanical maintenance",
                optionC = "Is completely identical to modern automobiles",
                optionD = "Operates on self-regulating natural laws and resources",
                correctAnswerIndex = 0,
                explanation = "The passage explains that Spaceship Earth was designed without an instruction manual, challenging humanity's curiosity to explore and understand physical laws.",
                passageText = spaceshipEarthPassage,
                difficulty = "Medium",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Use of English Past Question • 2010"
            )
        )

        list.add(
            QuestionEntity(
                id = "eng_2010_03",
                subject = "English Language",
                topic = "Comprehension: Spaceship Earth",
                year = "2010",
                questionText = "The absence of a pre-written instruction manual for Spaceship Earth has:",
                optionA = "Rendered human existence entirely helpless",
                optionB = "Forced humanity to abandon planetary exploration",
                optionC = "Challenged man's intellect, inquisitiveness, and capacity for scientific discovery",
                optionD = "Made global navigation impossible",
                correctAnswerIndex = 2,
                explanation = "The absence of instructions compelled humans to experiment, generalize, and uncover fundamental natural principles.",
                passageText = spaceshipEarthPassage,
                difficulty = "Medium",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Use of English Past Question • 2010"
            )
        )

        list.add(
            QuestionEntity(
                id = "eng_2010_04",
                subject = "English Language",
                topic = "Comprehension: Spaceship Earth",
                year = "2010",
                questionText = "From the passage, it can be logically deduced that man:",
                optionA = "Learns exclusively by sheer accident",
                optionB = "Is fundamentally incapable of solving ecological crises",
                optionC = "Is driven by human nature to continuously explore and acquire knowledge",
                optionD = "Relies solely on instinct for survival",
                correctAnswerIndex = 2,
                explanation = "Human beings are characterized by an innate drive to uncover physical resources and scientific truths as society evolves.",
                passageText = spaceshipEarthPassage,
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Use of English Past Question • 2010"
            )
        )

        list.add(
            QuestionEntity(
                id = "eng_2010_06",
                subject = "English Language",
                topic = "Comprehension: Stress & Physiology",
                year = "2010",
                questionText = "The expression '...stress is an issue everybody can relate to experimentally' implies that stress:",
                optionA = "Is best understood through personal direct experience",
                optionB = "Can be eliminated effortlessly by all people",
                optionC = "Is completely avoided by disciplined individuals",
                optionD = "Can only be diagnosed in laboratory experiments",
                correctAnswerIndex = 0,
                explanation = "To relate experimentally means to understand a condition through personal life experience rather than mere theory.",
                passageText = stressPassage,
                difficulty = "Medium",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Use of English Past Question • 2010"
            )
        )

        list.add(
            QuestionEntity(
                id = "eng_2010_08",
                subject = "English Language",
                topic = "Comprehension: Stress & Physiology",
                year = "2010",
                questionText = "According to the passage, the single most critical step in managing stress is:",
                optionA = "Altering one's internal cognitive attitude and response to stressors",
                optionB = "Memorizing the clinical pathology of cardiovascular disease",
                optionC = "Depending exclusively on pharmaceutical prescriptions",
                optionD = "Engaging in relentless physical exertion to exhaustion",
                correctAnswerIndex = 0,
                explanation = "Effective stress mastery begins by identifying damaging habitual reactions and consciously modifying one's perspective on life stressors.",
                passageText = stressPassage,
                difficulty = "Medium",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Use of English Past Question • 2010"
            )
        )

        list.add(
            QuestionEntity(
                id = "eng_2010_09",
                subject = "English Language",
                topic = "Comprehension: Stress & Physiology",
                year = "2010",
                questionText = "Medical experts maintain that individuals have the power to control stress because:",
                optionA = "External stressors rarely affect human biology",
                optionB = "The majority of psychological stress is self-generated by individual perceptions",
                optionC = "Stress is an easily curable bacterial infection",
                optionD = "Stress disappears automatically during sleep",
                correctAnswerIndex = 1,
                explanation = "Because individuals create their own internal emotional responses to events, they retain the conscious ability to modify and control those responses.",
                passageText = stressPassage,
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Use of English Past Question • 2010"
            )
        )

        list.add(
            QuestionEntity(
                id = "eng_2010_12",
                subject = "English Language",
                topic = "Comprehension: Corruption & Governance",
                year = "2010",
                questionText = "From the passage on public integrity, a primary socio-economic consequence of corruption is that it:",
                optionA = "Accelerates the completion of capital infrastructure projects",
                optionB = "Substantially increases national foreign exchange reserves",
                optionC = "Severely impedes overall national development and distorts public wealth",
                optionD = "Guarantees rapid industrialization across rural areas",
                correctAnswerIndex = 2,
                explanation = "Corruption diverts vital public funds away from essential public infrastructure, destabilizing institutions and crippling economic growth.",
                passageText = corruptionPassage,
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Use of English Past Question • 2010"
            )
        )

        list.add(
            QuestionEntity(
                id = "eng_2010_15",
                subject = "English Language",
                topic = "Comprehension: Corruption & Governance",
                year = "2010",
                questionText = "The primary objective of anti-corruption campaigns, according to the author, is to:",
                optionA = "Impoverish successful private entrepreneurs",
                optionB = "Foster good governance, accountability, and sustainable economic development",
                optionC = "Overcrowd the correctional penitentiaries",
                optionD = "Abolish commercial banking institutions",
                correctAnswerIndex = 1,
                explanation = "Eradicating graft creates an enabling, transparent environment required for good governance, societal equity, and sustainable growth.",
                passageText = corruptionPassage,
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Use of English Past Question • 2010"
            )
        )

        list.add(
            QuestionEntity(
                id = "eng_2010_16",
                subject = "English Language",
                topic = "Cloze Passage: Ecology & Drought",
                year = "2010",
                questionText = "Drought is a word that invokes strong emotions. This is not surprising as the ecological _________ is accompanied by harsh socio-economic impacts.",
                optionA = "Ideology",
                optionB = "Phenomenon",
                optionC = "Hypothesis",
                optionD = "Philosophy",
                correctAnswerIndex = 1,
                explanation = "A drought is an observable natural occurrence or 'phenomenon' affecting climate and water availability.",
                passageText = droughtPassage,
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Use of English Past Question • 2010"
            )
        )

        list.add(
            QuestionEntity(
                id = "eng_2010_26",
                subject = "English Language",
                topic = "Idioms & Figurative Expressions",
                year = "2010",
                questionText = "Select the option that best explains the underlined expression: Though Mr. Iro is a new chairman, he views other committee members with a JAUNDICED EYE.",
                optionA = "He treats all members with warm optimism",
                optionB = "He holds a prejudiced, suspicious, or unfavorable opinion of them",
                optionC = "He is medically diagnosed with yellow fever",
                optionD = "He is completely indifferent to their contributions",
                correctAnswerIndex = 1,
                explanation = "To look at someone or something with a 'jaundiced eye' is an idiom meaning to view them with prejudice, cynicism, or suspicion.",
                difficulty = "Medium",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Use of English Past Question • 2010"
            )
        )

        list.add(
            QuestionEntity(
                id = "eng_2010_28",
                subject = "English Language",
                topic = "Idioms & Figurative Expressions",
                year = "2010",
                questionText = "Select the option that best explains the statement: It is always wise to STEER A MIDDLE COURSE in sensitive leadership disputes.",
                optionA = "Take extreme partisan actions without hesitation",
                optionB = "Act with moderation, avoiding extreme stances on either side",
                optionC = "Abandon the leadership position completely",
                optionD = "Operate strictly in secret without consulting anyone",
                correctAnswerIndex = 1,
                explanation = "To 'steer a middle course' means to follow a balanced, moderate path between two opposing extremes.",
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Use of English Past Question • 2010"
            )
        )

        list.add(
            QuestionEntity(
                id = "eng_2010_29",
                subject = "English Language",
                topic = "Idioms & Figurative Expressions",
                year = "2010",
                questionText = "Select the option that best explains the statement: The crown witness stated that he had NO AXE TO GRIND with his business partners.",
                optionA = "He possessed no sharp tools for cutting wood",
                optionB = "He had no private selfish motive or underlying personal grievance against them",
                optionC = "He refused to participate in the commercial partnership",
                optionD = "He was deeply jealous of their business success",
                correctAnswerIndex = 1,
                explanation = "Having 'no axe to grind' means having no private grudge, ulterior motive, or self-serving interest in a matter.",
                difficulty = "Medium",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Use of English Past Question • 2010"
            )
        )

        list.add(
            QuestionEntity(
                id = "eng_2010_30",
                subject = "English Language",
                topic = "Idioms & Figurative Expressions",
                year = "2010",
                questionText = "Select the option that best explains the statement: After the decisive final match, the visiting team left the pitch WITH THEIR TAILS BETWEEN THEIR LEGS.",
                optionA = "They celebrated enthusiastically with their fans",
                optionB = "They felt humiliated, ashamed, and humbled by their overwhelming defeat",
                optionC = "They walked cautiously to avoid bodily injury",
                optionD = "They protested the referee's officiating angrily",
                correctAnswerIndex = 1,
                explanation = "To leave 'with tail between legs' is an idiom describing someone who feels defeated, cowed, or deeply embarrassed.",
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Use of English Past Question • 2010"
            )
        )

        list.add(
            QuestionEntity(
                id = "eng_1984_26",
                subject = "English Language",
                topic = "Phrasal Verbs & Vocabulary",
                year = "1984",
                questionText = "Choose the word or phrase that nearest in meaning to the underlined word: The scheduled faculty board meeting was CANCELLED due to the university convocation.",
                optionA = "Brought up",
                optionB = "Called off",
                optionC = "Broken off",
                optionD = "Phased out",
                correctAnswerIndex = 1,
                explanation = "The phrasal verb 'called off' is the direct formal synonym for 'cancelled'.",
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Use of English Past Question • 1984"
            )
        )

        list.add(
            QuestionEntity(
                id = "eng_2010_67",
                subject = "English Language",
                topic = "Phrasal Verbs & Idiomatic Recall",
                year = "2010",
                questionText = "He can recall all the important dates in the nation's history; it is fascinating to listen as he rattles ________ the chronological facts without hesitation.",
                optionA = "Off",
                optionB = "Over",
                optionC = "Up",
                optionD = "Out",
                correctAnswerIndex = 0,
                explanation = "'Rattle off' is a phrasal verb meaning to recite a list or detailed factual information rapidly and effortlessly from memory.",
                difficulty = "Medium",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Use of English Past Question • 2010"
            )
        )

        list.add(
            QuestionEntity(
                id = "eng_2010_71",
                subject = "English Language",
                topic = "Grammar: Question Tags & Modals",
                year = "2010",
                questionText = "Complete the sentence with the appropriate question tag: Suara needn't come with us, _________?",
                optionA = "Does she",
                optionB = "Will she",
                optionC = "Can she",
                optionD = "Need she",
                correctAnswerIndex = 3,
                explanation = "In English grammatical rules, when the semi-modal auxiliary 'needn't' (negative) is used in the main clause, the affirmative tag must use the corresponding modal 'need she?'.",
                difficulty = "Medium",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Use of English Past Question • 2010"
            )
        )

        list.add(
            QuestionEntity(
                id = "eng_1983_26",
                subject = "English Language",
                topic = "Idioms & Figurative Expressions",
                year = "1983",
                questionText = "Select the option that best interprets the sentence: The sensational story reported in the tabloid has to be taken WITH A GRAIN OF SALT.",
                optionA = "You need dietary table salt before listening to the story",
                optionB = "The story lacks any salt seasoning",
                optionC = "The story is highly questionable, unverified, and should be treated with skepticism",
                optionD = "The story is completely and undeniably true",
                correctAnswerIndex = 2,
                explanation = "To 'take something with a grain of salt' is an English idiom meaning to view information with healthy skepticism or doubt its complete accuracy.",
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Use of English Past Question • 1983"
            )
        )

        list.add(
            QuestionEntity(
                id = "eng_1983_27",
                subject = "English Language",
                topic = "Idioms & Historical Allusions",
                year = "1983",
                questionText = "Select the option that best interprets the expression: It is usually impossible to change the course of action when one CROSSES THE RUBICON.",
                optionA = "Travels through an Italian province named Rubicon",
                optionB = "Wades across a shallow stream",
                optionC = "Passes a mandatory licensing examination",
                optionD = "Takes an irrevocable and decisive step from which there is no turning back",
                correctAnswerIndex = 3,
                explanation = "Originating from Julius Caesar crossing the Rubicon river in 49 BC, 'crossing the Rubicon' means making an irrevocable, point-of-no-return commitment.",
                difficulty = "Medium",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Use of English Past Question • 1983"
            )
        )

        list.add(
            QuestionEntity(
                id = "eng_1983_30",
                subject = "English Language",
                topic = "Idioms & Figurative Expressions",
                year = "1983",
                questionText = "Select the option that best interprets the sentence: Solo has resigned his employment with the textile firm, yet his future career plans are STILL IN THE AIR.",
                optionA = "Transmitted by airmail courier",
                optionB = "Hermetically sealed and airtight",
                optionC = "Undecided, uncertain, and not yet finalized",
                optionD = "Conducted onboard an airplane",
                correctAnswerIndex = 2,
                explanation = "When plans are described as 'up in the air' or 'in the air', it indicates they remain unsettled, tentative, or uncertain.",
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Use of English Past Question • 1983"
            )
        )

        list.add(
            QuestionEntity(
                id = "eng_1983_31",
                subject = "English Language",
                topic = "Idioms & Figurative Expressions",
                year = "1983",
                questionText = "Select the option that best interprets the sentence: Ike is HEAD OVER HEELS in love with Ngozi.",
                optionA = "Ike maintains a casual polite acquaintance with Ngozi",
                optionB = "Ike is attempting to start a friendship with Ngozi",
                optionC = "Ike is completely, deeply, and passionately infatuated with Ngozi",
                optionD = "Ngozi tripped Ike during a walk",
                correctAnswerIndex = 2,
                explanation = "The idiom 'head over heels in love' signifies being deeply, thoroughly, and overwhelmingly in love with someone.",
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Use of English Past Question • 1983"
            )
        )

        list.add(
            QuestionEntity(
                id = "eng_1984_27",
                subject = "English Language",
                topic = "Phrasal Verbs: Social Interactions",
                year = "1984",
                questionText = "Choose the option that best replaces the underlined phrase: Our hometown is so small that we are constantly MEETING OUR OLD SCHOOLMATES ACCIDENTALLY.",
                optionA = "Coming across",
                optionB = "Falling into",
                optionC = "Knocking up",
                optionD = "Running into",
                correctAnswerIndex = 3,
                explanation = "The phrasal verb 'running into' specifically means meeting or encountering someone unexpectedly or by chance in public.",
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Use of English Past Question • 1984"
            )
        )

        list.add(
            QuestionEntity(
                id = "eng_2011_33",
                subject = "English Language",
                topic = "Idioms & Business Expressions",
                year = "2011",
                questionText = "Select the option that best explains the statement: Okon's logistics company TOOK A HIT during the economic recession last year.",
                optionA = "The company experienced exponential revenue growth",
                optionB = "The company was awarded an international award",
                optionC = "The company suffered a severe financial blow, damage, or major setback",
                optionD = "The enterprise was newly incorporated",
                correctAnswerIndex = 2,
                explanation = "To 'take a hit' is an idiomatic expression signifying suffering substantial financial harm, operational damage, or a setback.",
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Use of English Past Question • 2011"
            )
        )

        list.add(
            QuestionEntity(
                id = "eng_2011_79",
                subject = "English Language",
                topic = "Phrasal Verbs: Academic Compensation",
                year = "2011",
                questionText = "Fill in the blank with the correct phrasal verb: I wonder how the student will ________ for being absent from lectures for four consecutive weeks.",
                optionA = "Make in",
                optionB = "Make up",
                optionC = "Make off",
                optionD = "Make out",
                correctAnswerIndex = 1,
                explanation = "The phrasal verb 'make up (for)' means to compensate for, catch up with, or replace lost academic time or coursework.",
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Use of English Past Question • 2011"
            )
        )

        // =====================================================================
        // 2. LITERATURE IN ENGLISH (Prescribed Drama, Poetry & Prose)
        // =====================================================================
        list.add(
            QuestionEntity(
                id = "lit_2010_03",
                subject = "Literature in English",
                topic = "Drama: Sons and Daughters (J.C. De Graft)",
                year = "2010",
                questionText = "In J.C. De Graft's drama 'Sons and Daughters', Maanan harbors strong hostility toward Lawyer B primarily because of:",
                optionA = "His criticism of her father's political party",
                optionB = "His inappropriate and persistent romantic advances toward her",
                optionC = "His refusal to handle her family's land case",
                optionD = "His financial dispute with George",
                correctAnswerIndex = 1,
                explanation = "Maanan resents Lawyer B because of his dishonest character and uninvited sexual/romantic advances despite his professional relationship with her father.",
                difficulty = "Medium",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Literature Past Question • 2010"
            )
        )

        list.add(
            QuestionEntity(
                id = "lit_2010_06",
                subject = "Literature in English",
                topic = "Shakespeare: Romeo and Juliet",
                year = "2010",
                questionText = "In William Shakespeare's 'Romeo and Juliet', Friar Laurence refers to Romeo's act as a 'deadly sin' and 'rude unthankfulness'. The specific transgression referred to is:",
                optionA = "Juliet drinking the potion",
                optionB = "Romeo taking his own life in the tomb",
                optionC = "Romeo slaying Tybalt in the public street brawl",
                optionD = "Romeo marrying Juliet in secret",
                correctAnswerIndex = 2,
                explanation = "Romeo's killing of Tybalt violated Prince Escalus's decree against street brawling, carrying the legal penalty of death which was mercifully commuted to banishment.",
                difficulty = "Medium",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Literature Past Question • 2010"
            )
        )

        list.add(
            QuestionEntity(
                id = "lit_2010_08",
                subject = "Literature in English",
                topic = "Shakespeare: Romeo and Juliet",
                year = "2010",
                questionText = "In 'Romeo and Juliet', when Juliet laments: 'O serpent heart, hid with a flowering face!', she is reacting with grief and confusion toward:",
                optionA = "Lord Capulet",
                optionB = "Romeo (after learning he killed Tybalt)",
                optionC = "Paris",
                optionD = "The Nurse",
                correctAnswerIndex = 1,
                explanation = "Juliet uses oxymoronic imagery upon learning that her beloved husband Romeo killed her cousin Tybalt, struggling to reconcile his gentle beauty with his violent act.",
                difficulty = "Medium",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Literature Past Question • 2010"
            )
        )

        list.add(
            QuestionEntity(
                id = "lit_2010_09",
                subject = "Literature in English",
                topic = "Shakespeare: Romeo and Juliet",
                year = "2010",
                questionText = "The primary spatial and geographical setting of Shakespeare's tragic drama 'Romeo and Juliet' is:",
                optionA = "Athens, Greece",
                optionB = "Verona, Italy",
                optionC = "Padua, Italy",
                optionD = "Venice, Italy",
                correctAnswerIndex = 1,
                explanation = "The play is set predominantly in the Italian city of Verona (with brief scenes in Mantua during Romeo's exile).",
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Literature Past Question • 2010"
            )
        )

        list.add(
            QuestionEntity(
                id = "lit_2010_11",
                subject = "Literature in English",
                topic = "Prose: The Joys of Motherhood (Buchi Emecheta)",
                year = "2010",
                questionText = "In Buchi Emecheta's novel 'The Joys of Motherhood', the traditional patriarchy of Ibuza places the highest cultural value upon a woman's capacity for:",
                optionA = "Commercial wealth and trade",
                optionB = "Western educational attainment",
                optionC = "Procreation and bearing surviving male offspring",
                optionD = "Political chieftaincy leadership",
                correctAnswerIndex = 2,
                explanation = "In the traditional societal framework depicted, a woman's social standing, respect, and marital fulfillment are judged by her ability to bear children (especially sons).",
                difficulty = "Medium",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Literature Past Question • 2010"
            )
        )

        // =====================================================================
        // 3. GOVERNMENT (2010 & 1983 Series)
        // =====================================================================
        list.add(
            QuestionEntity(
                id = "gov_2010_02",
                subject = "Government",
                topic = "Basic Concepts: The State & Sovereignty",
                year = "2010",
                questionText = "A sovereign political entity possessing a permanent population, defined territory, organized government, and supreme supreme coercive authority is termed a:",
                optionA = "Self-actualization zone",
                optionB = "Sovereign Nation-State",
                optionC = "Liberation movement",
                optionD = "Nationalist coalition",
                correctAnswerIndex = 1,
                explanation = "A nation-state combines cultural self-identity with sovereignty—the supreme, independent power to govern within defined territorial borders.",
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Government Past Question • 2010"
            )
        )

        list.add(
            QuestionEntity(
                id = "gov_2010_04",
                subject = "Government",
                topic = "Forms of Government: Oligarchy",
                year = "2010",
                questionText = "A form of oligarchic government in which state power is vested in a privileged nobility or individuals perceived as the most qualified and gifted is an:",
                optionA = "Aristocracy",
                optionB = "Theocracy",
                optionC = "Plutocracy",
                optionD = "Gerontocracy",
                correctAnswerIndex = 0,
                explanation = "Aristocracy (literally 'rule of the best') is rule by an elite or noble class distinguished by wisdom, birth, or military valor.",
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Government Past Question • 2010"
            )
        )

        list.add(
            QuestionEntity(
                id = "gov_2010_07",
                subject = "Government",
                topic = "Parliamentary System & Motions",
                year = "2010",
                questionText = "In a parliamentary system of government, the passage of a 'Vote of No Confidence' by the legislature against the cabinet implies that:",
                optionA = "The executive is suspended for thirty days",
                optionB = "The Prime Minister and Cabinet must immediately tender their resignation",
                optionC = "The Chief Justice takes over executive governance",
                optionD = "Criminal proceedings commence against all legislators",
                correctAnswerIndex = 1,
                explanation = "In parliamentary systems, the executive draws its mandate from parliamentary confidence; a vote of no confidence collapses the government, requiring resignation or fresh elections.",
                difficulty = "Medium",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Government Past Question • 2010"
            )
        )

        list.add(
            QuestionEntity(
                id = "gov_2010_09",
                subject = "Government",
                topic = "Legislative Structures & Unicameralism",
                year = "2010",
                questionText = "A unicameral legislature (a parliament comprising a single legislative chamber) is an operational feature of the national government in:",
                optionA = "Israel (The Knesset)",
                optionB = "The United States",
                optionC = "The United Kingdom",
                optionD = "Nigeria",
                correctAnswerIndex = 0,
                explanation = "Israel operates a unicameral national parliament called the Knesset, unlike the bicameral legislatures of the US, UK, and Nigeria.",
                difficulty = "Medium",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Government Past Question • 2010"
            )
        )

        list.add(
            QuestionEntity(
                id = "gov_2010_11",
                subject = "Government",
                topic = "Systems of Government: Confederation",
                year = "2010",
                questionText = "In which system of government is the constitutional authority of the individual component units greater than that of the weak central coordinating body?",
                optionA = "Monarchical system",
                optionB = "Federal system",
                optionC = "Unitary system",
                optionD = "Confederal system",
                correctAnswerIndex = 3,
                explanation = "In a confederation, autonomous sovereign states delegate limited, enumerated duties to a weak center while retaining ultimate sovereignty.",
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Government Past Question • 2010"
            )
        )

        list.add(
            QuestionEntity(
                id = "gov_2010_22",
                subject = "Government",
                topic = "Pre-Colonial Administration: Oyo Empire",
                year = "2010",
                questionText = "In the pre-colonial political structure of the Old Oyo Empire, the supreme political and spiritual head was the:",
                optionA = "Bashorun (Prime Minister)",
                optionB = "Oyomesi (Council of Kingmakers)",
                optionC = "Aremo (Crown Prince)",
                optionD = "Alaafin of Oyo",
                correctAnswerIndex = 3,
                explanation = "The Alaafin was the supreme monarch and titular ruler of Oyo, checked in power by the Oyomesi and the Ogboni cult.",
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Government Past Question • 2010"
            )
        )

        list.add(
            QuestionEntity(
                id = "gov_2010_27",
                subject = "Government",
                topic = "Colonial Resistance: King Jaja of Opobo",
                year = "2010",
                questionText = "Which prominent Niger Delta ruler vigorously resisted British commercial exploitation of the palm oil trade and was subsequently deported and exiled by the British in 1887?",
                optionA = "King Kosoko of Lagos",
                optionB = "Oba Ovonramwen of Benin",
                optionC = "King Jaja of Opobo",
                optionD = "Nana Olomu of Itsekiri",
                correctAnswerIndex = 2,
                explanation = "King Jaja of Opobo defended his kingdom's trading sovereignty against the British merchant monopoly and was exiled to the West Indies.",
                difficulty = "Medium",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Government Past Question • 2010"
            )
        )

        // =====================================================================
        // 4. CHRISTIAN RELIGIOUS STUDIES (CRS) (1983 Series)
        // =====================================================================
        list.add(
            QuestionEntity(
                id = "crs_1983_01",
                subject = "CRS",
                topic = "Old Testament: Elijah & Ahab",
                year = "1983",
                questionText = "Which Old Testament prophet declared before King Ahab: 'As the Lord the God of Israel lives, before whom I stand, there shall be neither dew nor rain these years, except by my word'?",
                optionA = "Elisha",
                optionB = "Ezekiel",
                optionC = "Elijah the Tishbite",
                optionD = "Obadiah",
                correctAnswerIndex = 2,
                explanation = "In 1 Kings 17:1, Elijah pronounced a severe drought upon Israel as divine judgment for Ahab and Jezebel's Baal worship.",
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB CRS Past Question • 1983"
            )
        )

        list.add(
            QuestionEntity(
                id = "crs_1983_04",
                subject = "CRS",
                topic = "The Wilderness Journey: Bronze Serpent",
                year = "1983",
                questionText = "When the Israelites were bitten by venomous serpents in the wilderness for complaining, God commanded Moses to construct and mount a:",
                optionA = "Golden ark",
                optionB = "Bronze serpent on a pole, so that anyone bitten who looked upon it would live",
                optionC = "Silver altar",
                optionD = "Stone pillar of remembrance",
                correctAnswerIndex = 1,
                explanation = "In Numbers 21, God commanded Moses to make a bronze serpent; anyone looking upon it in faith was healed from the venomous bite.",
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB CRS Past Question • 1983"
            )
        )

        list.add(
            QuestionEntity(
                id = "crs_1983_21",
                subject = "CRS",
                topic = "Old Testament: Mount Carmel Contest",
                year = "1983",
                questionText = "Which prophet decisively proved on Mount Carmel that Yahweh is the true living God by calling down fire from heaven to consume the water-soaked sacrifice?",
                optionA = "Elijah",
                optionB = "Elisha",
                optionC = "Nathan",
                optionD = "Amos",
                correctAnswerIndex = 0,
                explanation = "In 1 Kings 18, Elijah challenged 450 prophets of Baal on Mount Carmel, where God sent down fire consuming the sacrifice and water.",
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB CRS Past Question • 1983"
            )
        )

        list.add(
            QuestionEntity(
                id = "crs_1983_28",
                subject = "CRS",
                topic = "Parables of Jesus: The Prodigal Son",
                year = "1983",
                questionText = "The central spiritual lesson taught by Jesus through the Parable of the Prodigal Son (Lost Son) in Luke 15 is that:",
                optionA = "Inheritance should never be divided before death",
                optionB = "Older siblings are always entitled to greater honor",
                optionC = "God joyfully welcomes and forgives any repentant sinner who returns to Him",
                optionD = "Agriculture is more rewarding than commerce",
                correctAnswerIndex = 2,
                explanation = "The parable illustrates the boundless grace and compassionate forgiveness of God toward every sinner who repents.",
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB CRS Past Question • 1983"
            )
        )

        list.add(
            QuestionEntity(
                id = "crs_1983_33",
                subject = "CRS",
                topic = "Acts of the Apostles: Great Commission",
                year = "1983",
                questionText = "In Acts 1:8, Jesus commanded the disciples: 'You shall be my witnesses in Jerusalem, in all Judea and ________, and to the end of the earth.'",
                optionA = "Rome",
                optionB = "Antioch",
                optionC = "Damascus",
                optionD = "Samaria",
                correctAnswerIndex = 3,
                explanation = "Acts 1:8 establishes the geographic pattern of gospel proclamation: Jerusalem → Judea → Samaria → Ends of the earth.",
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB CRS Past Question • 1983"
            )
        )

        list.add(
            QuestionEntity(
                id = "crs_1983_50",
                subject = "CRS",
                topic = "Acts of the Apostles: Philippian Jail",
                year = "1983",
                questionText = "Paul and Silas were stripped, beaten with rods, and imprisoned with their feet in stocks in the Roman colony of:",
                optionA = "Athens",
                optionB = "Philippi",
                optionC = "Corinth",
                optionD = "Ephesus",
                correctAnswerIndex = 1,
                explanation = "In Acts 16, Paul and Silas were jailed in Philippi after casting out a spirit of divination, singing praises until a miraculous earthquake freed them.",
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB CRS Past Question • 1983"
            )
        )

        // =====================================================================
        // 5. ECONOMICS (1983 Series)
        // =====================================================================
        list.add(
            QuestionEntity(
                id = "eco_1983_01",
                subject = "Economics",
                topic = "National Income Accounting",
                year = "1983",
                questionText = "Which of the following items is EXCLUDED when calculating national income using the Income Approach?",
                optionA = "Wages and salaries of civil servants",
                optionB = "Government student grants and transfer payments",
                optionC = "Undistributed corporate profits",
                optionD = "Rental income from real estate",
                correctAnswerIndex = 1,
                explanation = "Transfer payments (like student grants, unemployment benefits, and pensions) are unearned transfers that do not represent current economic output.",
                difficulty = "Medium",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Economics Past Question • 1983"
            )
        )

        list.add(
            QuestionEntity(
                id = "eco_1983_02",
                subject = "Economics",
                topic = "Price Theory: Demand Curve Shifts",
                year = "1983",
                questionText = "A rightward shift of the entire market demand curve (an increase in demand), with supply remaining constant, results in an:",
                optionA = "Increase in both the equilibrium price and equilibrium quantity",
                optionB = "Increase in price only while quantity decreases",
                optionC = "Increase in quantity only while price falls",
                optionD = "Unchanged equilibrium price and quantity",
                correctAnswerIndex = 0,
                explanation = "A rightward shift in demand intersects the upward-sloping supply curve at a higher equilibrium price and a larger quantity.",
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Economics Past Question • 1983"
            )
        )

        list.add(
            QuestionEntity(
                id = "eco_1983_06",
                subject = "Economics",
                topic = "Production Theory: Factors of Production",
                year = "1983",
                questionText = "Which group correctly and fully lists the four classical factors of production?",
                optionA = "Sunlight, machinery, management, and land",
                optionB = "Land, Labour, Capital, and Entrepreneurship (Enterprise)",
                optionC = "Capital, technology, ideas, and market demand",
                optionD = "Raw materials, energy, money, and transport",
                correctAnswerIndex = 1,
                explanation = "The four fundamental factors of production with their respective factor rewards (rent, wages, interest, profit) are Land, Labour, Capital, and Enterprise.",
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Economics Past Question • 1983"
            )
        )

        list.add(
            QuestionEntity(
                id = "eco_1983_29",
                subject = "Economics",
                topic = "International Trade: Dumping",
                year = "1983",
                questionText = "In international trade economics, 'dumping' is defined as the practice of:",
                optionA = "Selling commodities in foreign export markets at prices below their domestic production cost or home market price",
                optionB = "Exporting perishable agricultural waste products",
                optionC = "Charging exorbitant prices in overseas markets",
                optionD = "Imposing heavy protective import tariffs",
                correctAnswerIndex = 0,
                explanation = "Dumping involves exporting goods at predatory, below-cost prices to eliminate foreign competition and gain dominant market share.",
                difficulty = "Medium",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Economics Past Question • 1983"
            )
        )

        list.add(
            QuestionEntity(
                id = "eco_1983_39",
                subject = "Economics",
                topic = "Money & Barter System",
                year = "1983",
                questionText = "The primary inherent defect of a direct barter exchange system that necessitated the adoption of money is the requirement for:",
                optionA = "A standardized gold standard",
                optionB = "Double coincidence of wants between trading parties",
                optionC = "Complex electronic clearing houses",
                optionD = "Legal tender regulations",
                correctAnswerIndex = 1,
                explanation = "Barter trade requires that each party desires precisely what the other has to offer (double coincidence of wants), which is rarely matched in practice.",
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Economics Past Question • 1983"
            )
        )

        // =====================================================================
        // 6. CHEMISTRY (1984 & 1983 Series)
        // =====================================================================
        list.add(
            QuestionEntity(
                id = "chm_1984_27",
                subject = "Chemistry",
                topic = "Inorganic Chemistry: Oxides",
                year = "1984",
                questionText = "Which of the following gaseous compounds is an example of a NEUTRAL oxide (does not react with either acids or bases)?",
                optionA = "Aluminium oxide (Al₂O₃)",
                optionB = "Nitrogen dioxide (NO₂)",
                optionC = "Carbon dioxide (CO₂)",
                optionD = "Carbon monoxide (CO)",
                correctAnswerIndex = 3,
                explanation = "Carbon monoxide (CO), dinitrogen oxide (N₂O), and nitric oxide (NO) are neutral oxides that exhibit neither acidic nor basic properties in aqueous solution.",
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Chemistry Past Question • 1984"
            )
        )

        list.add(
            QuestionEntity(
                id = "chm_1984_30",
                subject = "Chemistry",
                topic = "Organic Chemistry: Petroleum Cracking",
                year = "1984",
                questionText = "When high-boiling heavy hydrocarbon fractions (such as kerosene and gas oil) are heated at elevated temperatures under pressure to yield lower-boiling petrol hydrocarbons, the process is known as:",
                optionA = "Polymerization",
                optionB = "Refining",
                optionC = "Hydrogenation",
                optionD = "Catalytic Cracking",
                correctAnswerIndex = 3,
                explanation = "Cracking breaks long-chain alkane molecules into shorter-chain, higher-demand fuels (petrol/gasoline) and reactive alkenes.",
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Chemistry Past Question • 1984"
            )
        )

        list.add(
            QuestionEntity(
                id = "chm_1983_02",
                subject = "Chemistry",
                topic = "Organic Chemistry: Saponification & Alkanols",
                year = "1983",
                questionText = "The trihydric alcohol (triol) obtained as an important industrial by-product during the saponification of fats and oils with alkali is:",
                optionA = "Ethanol",
                optionB = "Glycerol (Propane-1,2,3-triol)",
                optionC = "Methanol",
                optionD = "Ethylene glycol",
                correctAnswerIndex = 1,
                explanation = "Saponification hydrolyzes triglycerides (esters) into soap (fatty acid salts) and glycerol (propane-1,2,3-triol).",
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Chemistry Past Question • 1983"
            )
        )

        list.add(
            QuestionEntity(
                id = "chm_1983_07",
                subject = "Chemistry",
                topic = "Chemical Bonding & Molecular Shapes",
                year = "1983",
                questionText = "The three-dimensional spatial geometry of the methane molecule (CH₄), resulting from sp³ hybridization of the central carbon atom, is:",
                optionA = "Planar hexagonal",
                optionB = "Trigonal planar",
                optionC = "Linear",
                optionD = "Tetrahedral (bond angle 109.5°)",
                correctAnswerIndex = 3,
                explanation = "Methane has four bonding pairs and zero lone pairs, forming a symmetrical tetrahedral shape with 109.5° H-C-H bond angles.",
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Chemistry Past Question • 1983"
            )
        )

        // =====================================================================
        // 7. PHYSICS (1983 Series)
        // =====================================================================
        list.add(
            QuestionEntity(
                id = "phy_1983_01",
                subject = "Physics",
                topic = "Waves & Sound: Resonance Tube",
                year = "1983",
                questionText = "In a resonance tube experiment with an air column closed at one end, what is the theoretical ratio of the frequency of the second harmonic (first overtone, f₂) to the fundamental frequency (f₁)?",
                optionA = "8",
                optionB = "3",
                optionC = "2",
                optionD = "1/3",
                correctAnswerIndex = 1,
                explanation = "A closed pipe produces only odd harmonics (1, 3, 5...). The fundamental is f₁ = v/(4L) and the first overtone is f₂ = 3v/(4L), giving ratio f₂/f₁ = 3.",
                difficulty = "Medium",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Physics Past Question • 1983"
            )
        )

        list.add(
            QuestionEntity(
                id = "phy_1983_07",
                subject = "Physics",
                topic = "Optics & Refraction: Light Velocity",
                year = "1983",
                questionText = "If the speed of light in a vacuum is 3.0 × 10⁸ m/s, what is the speed of light in a transparent liquid whose refractive index is n = 1.50?",
                optionA = "1.5 × 10⁸ m/s",
                optionB = "2.0 × 10⁸ m/s",
                optionC = "4.5 × 10⁸ m/s",
                optionD = "9.0 × 10⁸ m/s",
                correctAnswerIndex = 1,
                explanation = "Refractive index n = c / v. Therefore, v = c / n = (3.0 × 10⁸ m/s) / 1.50 = 2.0 × 10⁸ m/s.",
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Physics Past Question • 1983"
            )
        )

        list.add(
            QuestionEntity(
                id = "phy_1983_08",
                subject = "Physics",
                topic = "Mechanics: Density & Relative Density",
                year = "1983",
                questionText = "If the relative density of a heavy metallic alloy is 19.0, calculate the mass of a solid block of the alloy with volume 20.0 cm³.",
                optionA = "380 g",
                optionB = "400 g",
                optionC = "360 g",
                optionD = "180 g",
                correctAnswerIndex = 0,
                explanation = "Density = Relative Density × 1.0 g/cm³ = 19.0 g/cm³. Mass = Density × Volume = 19.0 g/cm³ × 20.0 cm³ = 380 g.",
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Physics Past Question • 1983"
            )
        )

        // =====================================================================
        // 8. MATHEMATICS (1985, 1984, 1983 Series)
        // =====================================================================
        list.add(
            QuestionEntity(
                id = "mat_1985_10",
                subject = "Mathematics",
                topic = "Algebra: Logarithmic Equations",
                year = "1985",
                questionText = "Solve for x in the logarithmic equation: log₉(x) = 1.5",
                optionA = "72.0",
                optionB = "27.0",
                optionC = "36.0",
                optionD = "13.5",
                correctAnswerIndex = 1,
                explanation = "Converting from logarithmic to exponential form: x = 9^(1.5) = 9^(3/2) = (√9)³ = 3³ = 27.",
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Mathematics Past Question • 1985"
            )
        )

        list.add(
            QuestionEntity(
                id = "mat_1984_02",
                subject = "Mathematics",
                topic = "Number Bases",
                year = "1984",
                questionText = "If the addition 263ₙ + 441ₙ = 714ₙ holds in base n, determine the base n:",
                optionA = "12",
                optionB = "11",
                optionC = "10",
                optionD = "9",
                correctAnswerIndex = 3,
                explanation = "Converting each term to base 10: (2n² + 6n + 3) + (4n² + 4n + 1) = 7n² + n + 4 => 6n² + 10n + 4 = 7n² + n + 4 => n² - 9n = 0 => n(n - 9) = 0 => n = 9.",
                difficulty = "Medium",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Mathematics Past Question • 1984"
            )
        )

        list.add(
            QuestionEntity(
                id = "mat_1983_01",
                subject = "Mathematics",
                topic = "Statistics: Measures of Central Tendency",
                year = "1983",
                questionText = "Find the Median (M) and Mode (D) of the data set: {5, 9, 3, 5, 8}",
                optionA = "(6, 5)",
                optionB = "(5, 8)",
                optionC = "(5, 7)",
                optionD = "(5, 5)",
                correctAnswerIndex = 3,
                explanation = "Arranging the 5 items in ascending order: 3, 5, 5, 8, 9. The middle value (Median) is 5. The most frequently occurring value (Mode) is 5.",
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Mathematics Past Question • 1983"
            )
        )

        list.add(
            QuestionEntity(
                id = "mat_1983_03",
                subject = "Mathematics",
                topic = "Geometry: Regular Polygons",
                year = "1983",
                questionText = "Calculate the size of each interior angle in a regular convex hexagon (6-sided polygon):",
                optionA = "60°",
                optionB = "90°",
                optionC = "120°",
                optionD = "135°",
                correctAnswerIndex = 2,
                explanation = "Interior angle formula = (n - 2) × 180° / n. For a hexagon (n = 6): (4 × 180°) / 6 = 720° / 6 = 120°.",
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Mathematics Past Question • 1983"
            )
        )

        // =====================================================================
        // 9. PRINCIPLES OF ACCOUNTS / FINANCIAL ACCOUNTING (1994, 1995 Series)
        // =====================================================================
        list.add(
            QuestionEntity(
                id = "acc_1994_02",
                subject = "Financial Accounting",
                topic = "Accounting Concepts & Principles",
                year = "1994",
                questionText = "The accounting principle which requires that revenues earned and all associated expenses incurred in generating those revenues must be recognized within the same financial period is the:",
                optionA = "Entity concept",
                optionB = "Consistency principle",
                optionC = "Matching concept",
                optionD = "Materiality principle",
                correctAnswerIndex = 2,
                explanation = "The matching concept ensures net profit is determined accurately by aligning period expenses against corresponding period revenues.",
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Financial Accounting Past Question • 1994"
            )
        )

        list.add(
            QuestionEntity(
                id = "acc_1994_03",
                subject = "Financial Accounting",
                topic = "Accounting Concepts: Prudence",
                year = "1994",
                questionText = "The accounting convention which dictates that anticipated revenues and profits are recognized only when realized, whereas all foreseeable liabilities and potential losses must be provided for immediately, is:",
                optionA = "Materiality convention",
                optionB = "Objectivity principle",
                optionC = "Consistency concept",
                optionD = "Prudence (Conservatism) convention",
                correctAnswerIndex = 3,
                explanation = "The prudence/conservatism convention prevents overstatement of assets and profits in financial reporting.",
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Financial Accounting Past Question • 1994"
            )
        )

        list.add(
            QuestionEntity(
                id = "acc_1994_07",
                subject = "Financial Accounting",
                topic = "Double Entry Bookkeeping",
                year = "1994",
                questionText = "The fundamental golden rule governing double-entry ledger bookkeeping is to:",
                optionA = "Debit decreases and Credit increases",
                optionB = "Debit the receiver of value, Credit the giver of value",
                optionC = "Debit all assets and Credit all capital only",
                optionD = "Debit sales and Credit purchases",
                correctAnswerIndex = 1,
                explanation = "Every transaction involves a dual aspect: the receiving account is debited, and the giving/yielding account is credited.",
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Financial Accounting Past Question • 1994"
            )
        )

        list.add(
            QuestionEntity(
                id = "acc_1995_21",
                subject = "Financial Accounting",
                topic = "Control Accounts & Sales Ledger",
                year = "1995",
                questionText = "The Sales Ledger Control Account (Total Debtors Account) is maintained in the general ledger to verify and summarize the aggregate balances of:",
                optionA = "Trade Creditors",
                optionB = "Trade Debtors (Accounts Receivable)",
                optionC = "Debenture holders",
                optionD = "Shareholders",
                correctAnswerIndex = 1,
                explanation = "The sales ledger control account provides a single aggregate check on the accuracy of all individual trade debtor ledger accounts.",
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Financial Accounting Past Question • 1995"
            )
        )

        // =====================================================================
        // 10. COMMERCE (1994, 1995 Series)
        // =====================================================================
        list.add(
            QuestionEntity(
                id = "com_1994_01",
                subject = "Commerce",
                topic = "Introduction to Commerce",
                year = "1994",
                questionText = "Commerce is broadly defined as the comprehensive study of how man:",
                optionA = "Extracts crude minerals from nature",
                optionB = "Constructs physical highways and buildings",
                optionC = "Buys, sells, and distributes goods and services from original producers to final consumers",
                optionD = "Enforces criminal and corporate legislation",
                correctAnswerIndex = 2,
                explanation = "Commerce comprises trade (buying and selling) along with all aids to trade (transport, banking, insurance, warehousing, advertising).",
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Commerce Past Question • 1994"
            )
        )

        list.add(
            QuestionEntity(
                id = "com_1994_05",
                subject = "Commerce",
                topic = "Business Organizations: Limited Companies",
                year = "1994",
                questionText = "An essential legal characteristic of an incorporated limited liability company is that:",
                optionA = "It possesses no legal identity separate from its directors",
                optionB = "It dissolves automatically whenever any shareholder dies",
                optionC = "It is an artificial legal person separate from its owners, with perpetual succession and the capacity to sue and be sued",
                optionD = "Shareholders have unlimited personal liability for company debts",
                correctAnswerIndex = 2,
                explanation = "Incorporation creates an independent corporate legal personality (established in Salomon v Salomon), conferring limited liability and perpetual succession.",
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Commerce Past Question • 1994"
            )
        )

        list.add(
            QuestionEntity(
                id = "com_1995_09",
                subject = "Commerce",
                topic = "Business Organizations: Sole Trader",
                year = "1995",
                questionText = "A major operational advantage of operating as a sole proprietorship (one-man business) is the ability to:",
                optionA = "Raise vast capital on the public stock exchange",
                optionB = "Enjoy limited personal financial liability",
                optionC = "Make swift, flexible, and autonomous decisions without bureaucratic delays",
                optionD = "Spread financial losses across hundreds of partners",
                correctAnswerIndex = 2,
                explanation = "A sole trader manages their enterprise directly, allowing rapid decision-making and total operational control without board consultation.",
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Commerce Past Question • 1995"
            )
        )

        list.add(
            QuestionEntity(
                id = "com_1995_42",
                subject = "Commerce",
                topic = "Consumer Protection & Sovereignty",
                year = "1995",
                questionText = "In marketing and free-market commerce, the economic concept of 'Consumer Sovereignty' implies that:",
                optionA = "The government dictates the prices of all consumer commodities",
                optionB = "Consumers are legally required to purchase domestic manufactured goods",
                optionC = "Producers can force consumers to purchase unwanted goods",
                optionD = "Consumer preferences, tastes, and purchasing power ultimately dictate what goods and services producers supply",
                correctAnswerIndex = 3,
                explanation = "Consumer sovereignty reflects the principle that the buyer is 'king' in a free market, guiding resource allocation through demand.",
                difficulty = "Easy",
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Commerce Past Question • 1995"
            )
        )

        return list
    }
}
