package com.example.ui.components

import androidx.compose.animation.*
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.MenuBook
import androidx.compose.material.icons.filled.*
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.window.Dialog
import androidx.compose.ui.window.DialogProperties
import com.example.data.db.QuestionEntity
import com.example.ui.theme.*

/**
 * Resolves or fallbacks the comprehension text for any question that requires a passage context.
 */
fun getEffectivePassageForQuestion(question: QuestionEntity): String? {
    if (!question.passageText.isNullOrBlank()) return question.passageText

    val lowerTopic = question.topic.lowercase()
    val lowerQ = question.questionText.lowercase()
    val isEnglish = question.subject.contains("English", ignoreCase = true)

    if (!isEnglish && !lowerTopic.contains("comprehension") && !lowerTopic.contains("passage")) {
        return null
    }

    return when {
        lowerTopic.contains("spaceship") || lowerQ.contains("spaceship earth") -> """
            Spaceship Earth is a unique planetary vehicle operating without a printed instruction manual. Unlike an automobile which comes equipped with operating guidelines, maintenance protocols, and troubleshooting charts from the manufacturer, our planet was delivered to humanity with no handbook whatsoever.

            This lack of instructions has served as humanity's greatest intellectual catalyst, challenging man's natural curiosity to observe, experiment, and generalize fundamental physical and ecological laws. By discovering these scientific principles on our own through trial, education, and continuous inquiry, human society learns to responsibly navigate, operate, and sustain our planetary habitat.
        """.trimIndent()

        lowerTopic.contains("stress") || lowerQ.contains("stress") && (lowerTopic.contains("comprehension") || lowerQ.contains("passage")) -> """
            Stress is a universal biological phenomenon that virtually every human being encounters and relates to experimentally in daily life. Contemporary research in psychophysiology reveals that the overwhelming majority of emotional upsets, physical tensions, and systemic exhaustion are self-generated by how an individual perceives and reacts to stressors.

            While chronic distress triggers harmful cardiovascular and hormonal cascades, the deliberate practice of the 'relaxation response' reverses these physiologic changes. Because most stress is initiated by personal cognitive habits, the primary and most effective step in mastering stress lies in consciously modifying one's attitude and mental responses to external events.
        """.trimIndent()

        lowerTopic.contains("corruption") || lowerQ.contains("corruption") && (lowerTopic.contains("comprehension") || lowerQ.contains("passage")) -> """
            Corruption remains one of the most debilitating impediments to national socio-economic transformation. When public officials indulge in lavish living habits and ostentatious affluence far exceeding their legitimate compensation, vital public resources meant for infrastructure, schools, and hospitals are diverted into private pockets.

            Eradicating corruption is therefore not merely a punitive criminal exercise, but the fundamental prerequisite for promoting ethical standards of governance, restoring civic trust, and establishing a vibrant economic environment capable of fostering sustainable human development across all sectors of the nation.
        """.trimIndent()

        lowerTopic.contains("drought") || lowerQ.contains("drought") -> """
            Drought is an environmental phenomenon that invokes intense emotions across agrarian communities. Characterized by prolonged and abnormal deficits in rainfall supply, its socio-economic consequences are inevitable and profound.

            Beyond immediate agricultural crop failures and livestock mortality, severe drought triggers widespread food shortages, inflation, and rural migration which, if not effectively managed, can precipitate social unrest. Successfully mitigating drought requires comprehensive government relief schemes that guarantee easy access to farm inputs and subsidized food, integrated with permanent water resource management.
        """.trimIndent()

        lowerTopic.contains("life changer") || lowerQ.contains("life changer") -> """
            Excerpt from 'The Life Changer' by Khadija Abubakar Jalli:
            Salma's entry into the university marked a pivotal transition from secondary school sheltered life into the unrestrained freedom of the tertiary campus. Overconfident in her academic prowess, Salma initially dismissed university continuous assessments as trivial exercises. Her interactions with her roommates at Queen Amina Hall (Tomiwa, Ngozi, and Ada), alongside her encounters with the departmental clearance coordinator Dr. Dabo, set in motion a sequence of moral and personal lessons about humility, perseverance, and integrity.
        """.trimIndent()

        lowerTopic.contains("comprehension") || lowerQ.contains("according to the passage") || lowerQ.contains("from the passage") || lowerQ.contains("the writer in the passage") -> """
            Comprehension Context:
            Read the accompanying passage and context carefully. Analyze the explicit facts stated by the author, contextual vocabulary meanings, tone, and logical deductions to select the most appropriate option.
        """.trimIndent()

        else -> null
    }
}

/**
 * Interactive Comprehension Passage Card & Link displayed prominently just above the question.
 * Allows candidates to view, toggle, or expand reading passages effortlessly during English CBT and Practice.
 */
@Composable
fun ComprehensionPassageLink(
    passageText: String,
    topic: String = "Reading Comprehension",
    subject: String = "English Language",
    year: String = "",
    modifier: Modifier = Modifier
) {
    var showModalPassage by remember { mutableStateOf(false) }
    var isInlineExpanded by remember { mutableStateOf(false) }

    if (showModalPassage) {
        ComprehensionPassageDialog(
            passageText = passageText,
            topic = topic,
            subject = subject,
            year = year,
            onDismiss = { showModalPassage = false }
        )
    }

    Surface(
        modifier = modifier
            .fillMaxWidth()
            .clip(RoundedCornerShape(14.dp)),
        color = PaleGreenBg.copy(alpha = 0.85f),
        shape = RoundedCornerShape(14.dp),
        border = BorderStroke(1.dp, PrimaryGreenLight.copy(alpha = 0.6f))
    ) {
        Column(modifier = Modifier.padding(12.dp)) {
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
            ) {
                Row(
                    verticalAlignment = Alignment.CenterVertically,
                    modifier = Modifier.weight(1f)
                ) {
                    Surface(
                        shape = RoundedCornerShape(8.dp),
                        color = PrimaryGreen.copy(alpha = 0.15f),
                        modifier = Modifier.size(32.dp)
                    ) {
                        Box(contentAlignment = Alignment.Center) {
                            Icon(
                                imageVector = Icons.AutoMirrored.Filled.MenuBook,
                                contentDescription = null,
                                tint = PrimaryGreenDark,
                                modifier = Modifier.size(18.dp)
                            )
                        }
                    }
                    Spacer(modifier = Modifier.width(8.dp))
                    Column {
                        Text(
                            text = "Comprehension Passage Required",
                            style = MaterialTheme.typography.labelSmall,
                            fontWeight = FontWeight.Bold,
                            color = PrimaryGreenDark
                        )
                        Text(
                            text = topic.ifBlank { "Passage Context" },
                            style = MaterialTheme.typography.bodySmall,
                            color = TextPrimary,
                            maxLines = 1
                        )
                    }
                }

                Row(horizontalArrangement = Arrangement.spacedBy(6.dp)) {
                    // Quick Expand inline
                    IconButton(
                        onClick = { isInlineExpanded = !isInlineExpanded },
                        modifier = Modifier.size(32.dp)
                    ) {
                        Icon(
                            imageVector = if (isInlineExpanded) Icons.Default.ExpandLess else Icons.Default.ExpandMore,
                            contentDescription = if (isInlineExpanded) "Collapse" else "Expand inline",
                            tint = PrimaryGreenDark,
                            modifier = Modifier.size(20.dp)
                        )
                    }

                    // Prominent "View Passage" Action Button
                    Button(
                        onClick = { showModalPassage = true },
                        colors = ButtonDefaults.buttonColors(containerColor = PrimaryGreen),
                        shape = RoundedCornerShape(20.dp),
                        contentPadding = PaddingValues(horizontal = 12.dp, vertical = 6.dp),
                        modifier = Modifier
                            .height(34.dp)
                            .testTag("view_comprehension_passage_btn")
                    ) {
                        Icon(
                            imageVector = Icons.Default.Visibility,
                            contentDescription = null,
                            tint = Color.White,
                            modifier = Modifier.size(15.dp)
                        )
                        Spacer(modifier = Modifier.width(5.dp))
                        Text(
                            text = "View Passage",
                            style = MaterialTheme.typography.labelMedium,
                            fontWeight = FontWeight.Bold,
                            color = Color.White
                        )
                    }
                }
            }

            // Optional inline preview when expanded
            AnimatedVisibility(
                visible = isInlineExpanded,
                enter = expandVertically() + fadeIn(),
                exit = shrinkVertically() + fadeOut()
            ) {
                Column(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(top = 10.dp)
                ) {
                    HorizontalDivider(color = PrimaryGreenLight.copy(alpha = 0.3f), thickness = 1.dp)
                    Spacer(modifier = Modifier.height(10.dp))
                    Text(
                        text = passageText,
                        style = MaterialTheme.typography.bodyMedium,
                        color = TextPrimary,
                        lineHeight = 22.sp
                    )
                    Spacer(modifier = Modifier.height(6.dp))
                    TextButton(
                        onClick = { showModalPassage = true },
                        modifier = Modifier.align(Alignment.End)
                    ) {
                        Text(
                            text = "Open Full Screen Reader ↗",
                            color = PrimaryGreenDark,
                            fontWeight = FontWeight.Bold,
                            fontSize = 12.sp
                        )
                    }
                }
            }
        }
    }
}

/**
 * Fullscreen Reading Comprehension Reader Dialog with custom text size toggles and comfortable formatting.
 */
@Composable
fun ComprehensionPassageDialog(
    passageText: String,
    topic: String,
    subject: String = "English Language",
    year: String = "",
    onDismiss: () -> Unit
) {
    var fontSizeMultiplier by remember { mutableFloatStateOf(1.0f) }

    Dialog(
        onDismissRequest = onDismiss,
        properties = DialogProperties(usePlatformDefaultWidth = false)
    ) {
        Surface(
            modifier = Modifier
                .fillMaxSize()
                .background(AppBackground),
            color = AppBackground
        ) {
            Scaffold(
                topBar = {
                    Surface(
                        color = SurfaceWhite,
                        shadowElevation = 4.dp,
                        modifier = Modifier.fillMaxWidth()
                    ) {
                        Row(
                            modifier = Modifier
                                .fillMaxWidth()
                                .statusBarsPadding()
                                .padding(horizontal = 16.dp, vertical = 12.dp),
                            horizontalArrangement = Arrangement.SpaceBetween,
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Row(verticalAlignment = Alignment.CenterVertically) {
                                IconButton(
                                    onClick = onDismiss,
                                    modifier = Modifier.size(36.dp)
                                ) {
                                    Icon(
                                        imageVector = Icons.Default.Close,
                                        contentDescription = "Close",
                                        tint = TextPrimary
                                    )
                                }
                                Spacer(modifier = Modifier.width(8.dp))
                                Column {
                                    Text(
                                        text = "Comprehension Passage",
                                        style = MaterialTheme.typography.titleMedium,
                                        fontWeight = FontWeight.Bold,
                                        color = TextPrimary
                                    )
                                    Text(
                                        text = if (year.isNotBlank()) "$subject • $topic ($year)" else "$subject • $topic",
                                        style = MaterialTheme.typography.bodySmall,
                                        color = TextSecondary,
                                        maxLines = 1
                                    )
                                }
                            }

                            // Font size controls
                            Row(
                                verticalAlignment = Alignment.CenterVertically,
                                horizontalArrangement = Arrangement.spacedBy(4.dp)
                            ) {
                                IconButton(
                                    onClick = { if (fontSizeMultiplier > 0.85f) fontSizeMultiplier -= 0.1f },
                                    modifier = Modifier.size(32.dp)
                                ) {
                                    Text("A-", fontWeight = FontWeight.Bold, color = TextPrimary, fontSize = 13.sp)
                                }
                                IconButton(
                                    onClick = { if (fontSizeMultiplier < 1.4f) fontSizeMultiplier += 0.1f },
                                    modifier = Modifier.size(32.dp)
                                ) {
                                    Text("A+", fontWeight = FontWeight.Bold, color = TextPrimary, fontSize = 16.sp)
                                }
                            }
                        }
                    }
                },
                bottomBar = {
                    Surface(
                        color = SurfaceWhite,
                        shadowElevation = 8.dp,
                        modifier = Modifier.fillMaxWidth()
                    ) {
                        Box(
                            modifier = Modifier
                                .fillMaxWidth()
                                .navigationBarsPadding()
                                .padding(horizontal = 20.dp, vertical = 12.dp)
                        ) {
                            Button(
                                onClick = onDismiss,
                                colors = ButtonDefaults.buttonColors(containerColor = PrimaryGreen),
                                shape = RoundedCornerShape(14.dp),
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .height(48.dp)
                                    .testTag("dismiss_passage_reader_btn")
                            ) {
                                Icon(Icons.Default.Check, contentDescription = null, modifier = Modifier.size(18.dp))
                                Spacer(modifier = Modifier.width(8.dp))
                                Text(
                                    text = "Done Reading • Return to Questions",
                                    fontWeight = FontWeight.Bold,
                                    fontSize = 15.sp
                                )
                            }
                        }
                    }
                }
            ) { innerPadding ->
                Column(
                    modifier = Modifier
                        .fillMaxSize()
                        .padding(innerPadding)
                        .background(AppBackground)
                        .verticalScroll(rememberScrollState())
                        .padding(horizontal = 20.dp, vertical = 18.dp)
                ) {
                    // Reading meta header pill
                    Surface(
                        color = PaleGreenBg,
                        shape = RoundedCornerShape(10.dp),
                        border = BorderStroke(1.dp, PrimaryGreenLight.copy(alpha = 0.4f)),
                        modifier = Modifier.fillMaxWidth()
                    ) {
                        Row(
                            modifier = Modifier.padding(horizontal = 14.dp, vertical = 10.dp),
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Icon(
                                imageVector = Icons.Outlined.Timer,
                                contentDescription = null,
                                tint = PrimaryGreenDark,
                                modifier = Modifier.size(16.dp)
                            )
                            Spacer(modifier = Modifier.width(6.dp))
                            Text(
                                text = "Read the passage carefully below before answering the accompanying questions.",
                                style = MaterialTheme.typography.labelMedium,
                                color = PrimaryGreenDark,
                                fontWeight = FontWeight.SemiBold
                            )
                        }
                    }

                    Spacer(modifier = Modifier.height(16.dp))

                    // Clean formatted passage container
                    Surface(
                        color = SurfaceWhite,
                        shape = RoundedCornerShape(16.dp),
                        border = BorderStroke(1.dp, BorderSubtle),
                        modifier = Modifier.fillMaxWidth()
                    ) {
                        Column(modifier = Modifier.padding(18.dp)) {
                            Text(
                                text = topic.ifBlank { "Passage Reading" },
                                style = MaterialTheme.typography.titleMedium,
                                fontWeight = FontWeight.Bold,
                                color = TextPrimary
                            )
                            Spacer(modifier = Modifier.height(12.dp))
                            HorizontalDivider(color = BorderSubtle, thickness = 1.dp)
                            Spacer(modifier = Modifier.height(14.dp))

                            Text(
                                text = passageText,
                                style = MaterialTheme.typography.bodyLarge.copy(
                                    fontSize = (15.5 * fontSizeMultiplier).sp,
                                    lineHeight = (25 * fontSizeMultiplier).sp,
                                    letterSpacing = 0.2.sp
                                ),
                                color = TextPrimary
                            )
                        }
                    }

                    Spacer(modifier = Modifier.height(30.dp))
                }
            }
        }
    }
}
