# Part 4: Questions 151 - 200 (1990 - 1993 Series)
part4_questions = [
    {
        "id": "chem_mr_151",
        "topic": "Organic Chemistry (Hybridization in Carbon)",
        "year": "1990",
        "question": "Carbon is tetravalent in methane and other saturated organic molecules because:",
        "a": "Electrons in 2s and 2p have identical spin",
        "b": "The one 2s and three 2p atomic orbitals hybridize to form four equivalent sp³ hybrid orbitals",
        "c": "Carbon forms ionic bonds with hydrogen",
        "d": "Carbon has six valence electrons",
        "ans": 1,
        "explanation": "During chemical bonding, one 2s electron is promoted to the vacant 2p_z orbital, followed by hybridization of the single 2s and three 2p orbitals to form four degenerate sp³ hybrid orbitals directed tetrahedrally."
    },
    {
        "id": "chem_mr_152",
        "topic": "Organic Qualitative Analysis (Terminal Alkynes)",
        "year": "1990",
        "question": "Which of the following hydrocarbons will give a reddish-brown precipitate when bubbled through ammoniacal copper(I) chloride solution?",
        "a": "But-2-yne (CH₃-C≡C-CH₃)",
        "b": "But-1-yne (CH₃-CH₂-C≡CH)",
        "c": "But-2-ene (CH₃-CH=CH-CH₃)",
        "d": "Butane (CH₃-CH₂-CH₂-CH₃)",
        "ans": 1,
        "explanation": "Terminal alkynes possess weakly acidic acetylenic protons (≡C-H) that react with ammoniacal Cu₂Cl₂ to precipitate reddish-brown copper(I) acetylides (dicopper dicarbide derivatives)."
    },
    {
        "id": "chem_mr_153",
        "topic": "Applied Organic Chemistry (Petroleum & Octane Number)",
        "year": "1990",
        "question": "The knocking tendency of petrol in internal combustion engines is reduced and its fuel efficiency is increased by having a higher percentage of:",
        "a": "Straight-chain alkanes (such as n-heptane)",
        "b": "Highly branched-chain alkanes and aromatic hydrocarbons",
        "c": "Unsaturated cycloalkanes",
        "d": "Halogenated alkanes",
        "ans": 1,
        "explanation": "Branched alkanes (e.g. 2,2,4-trimethylpentane / isooctane) burn smoothly without premature detonation ('knocking'), raising the octane rating and efficiency of engine fuel."
    },
    {
        "id": "chem_mr_154",
        "topic": "Organic Qualitative Analysis (Iodoform Test)",
        "year": "1990",
        "question": "When ethanol is warmed with iodine in the presence of aqueous sodium hydroxide, a pale yellow crystalline precipitate with a characteristic antiseptic smell is formed. This precipitate is:",
        "a": "Trichloromethane", "b": "Triiodomethane (iodoform, CHI₃)", "c": "Iodoethane", "d": "Ethanal",
        "ans": 1,
        "explanation": "Compounds containing the CH₃-CH(OH)- or CH₃-C=O group undergo the haloform reaction. Ethanol is oxidized to ethanal, then iodinated and cleaved to form yellow crystals of triiodomethane (CHI₃, iodoform)."
    },
    {
        "id": "chem_mr_155",
        "topic": "Fractional Distillation of Petroleum",
        "year": "1990",
        "question": "The most volatile fraction obtained from the fractional distillation of crude petroleum consists mainly of:",
        "a": "Kerosene and diesel",
        "b": "Lubricating oils and bitumen",
        "c": "Refinery petroleum gases (methane, ethane, propane, and butane)",
        "d": "Naphtha and gas oil",
        "ans": 2,
        "explanation": "Petroleum refinery gases have the shortest carbon chains (C₁ to C₄) and the lowest boiling points (< 40°C), discharging at the top of the fractionating column as the most volatile fraction."
    },
    {
        "id": "chem_mr_156",
        "topic": "Applied Chemistry & Soap Making",
        "year": "1990",
        "question": "In traditional local black soap preparation, palm oil is boiled with an aqueous extract of plant ash. The function of the plant ash extract is to provide:",
        "a": "A strong mineral acid",
        "b": "An ester of an alkanoic acid",
        "c": "Soluble alkaline potassium carbonate (potash / alkali)",
        "d": "Glycerol",
        "ans": 2,
        "explanation": "Wood ash contains high concentrations of potassium carbonate (potash, K₂CO₃) which hydrolyzes in water to give a strongly alkaline caustic solution needed to saponify the fatty acids in palm oil."
    },
    {
        "id": "chem_mr_157",
        "topic": "Polymers & Synthetic Rubber",
        "year": "1990",
        "question": "Neoprene (polychloroprene), a synthetic oil-resistant rubber, is produced by the polymerization of:",
        "a": "2-chlorobuta-1,3-diene (chloroprene)",
        "b": "2-methylbuta-1,3-diene (isoprene)",
        "c": "Ethene",
        "d": "Phenylethene (styrene)",
        "ans": 0,
        "explanation": "Neoprene is a synthetic elastomer produced by the addition polymerization of 2-chlorobuta-1,3-diene (chloroprene: CH₂=CCl-CH=CH₂)."
    },
    {
        "id": "chem_mr_158",
        "topic": "Organic Synthesis & Acetylene",
        "year": "1990",
        "question": "When water is added dropwise to solid calcium carbide (CaC₂), the gas evolved burns in a specialized welding torch to produce an:",
        "a": "Oxy-methane flame", "b": "Oxy-hydrogen flame", "c": "Oxy-acetylene flame", "d": "Air-butane flame",
        "ans": 2,
        "explanation": "CaC₂ + 2H₂O → Ca(OH)₂ + C₂H₂↑. The ethyne (acetylene) gas generated burns with pure oxygen in an oxy-acetylene torch to produce temperatures above 3000°C for metal welding."
    },
    {
        "id": "chem_mr_159",
        "topic": "Chemical Formula & Valency",
        "year": "1990",
        "question": "The chemical formula of the compound formed between a trivalent metal M (valency +3) and a tetravalent non-metal X (valency -4) is:",
        "a": "MX", "b": "M₃X₄", "c": "M₄X₃", "d": "M₂X₃",
        "ans": 2,
        "explanation": "By the criss-cross valency rule, combining M³⁺ with X⁴⁻ produces the neutral compound M₄X₃."
    },
    {
        "id": "chem_mr_160",
        "topic": "Laws of Chemical Combination",
        "year": "1990",
        "question": "2.25 g of one oxide of copper gave 2.00 g of copper on reduction. 2.50 g of another oxide of copper gave 2.00 g of copper on reduction. These experimental data illustrate the:",
        "a": "Law of Definite Proportions",
        "b": "Law of Conservation of Mass",
        "c": "Law of Multiple Proportions",
        "d": "Law of Reciprocal Proportions",
        "ans": 2,
        "explanation": "For a fixed mass of copper (2.00 g), the masses of combined oxygen are 0.25 g and 0.50 g respectively. The ratio of oxygen masses combining with a fixed mass of copper is 0.25 : 0.50 = 1 : 2 (a simple whole-number ratio), demonstrating the Law of Multiple Proportions."
    },
    {
        "id": "chem_mr_161",
        "topic": "Stoichiometry & Gas Volumes",
        "year": "1990",
        "question": "1.0 mole of propane (C₃H₈) is mixed with 5.0 moles of oxygen (O₂) and ignited. At STP after the reaction, what is the volume of residual gaseous products? [Molar volume of gas at STP = 22.4 dm³]",
        "a": "112.0 dm³", "b": "67.2 dm³", "c": "56.0 dm³", "d": "44.8 dm³",
        "ans": 1,
        "explanation": "C₃H₈(g) + 5O₂(g) → 3CO₂(g) + 4H₂O(l). At STP (0°C, 1 atm), the water condenses to liquid. The only gaseous product remaining is 3.0 moles of CO₂: Volume = 3 × 22.4 dm³ = 67.2 dm³."
    },
    {
        "id": "chem_mr_162",
        "topic": "Intermolecular Forces",
        "year": "1990",
        "question": "The weak attractive forces holding non-polar molecular crystals of naphthalene together in the solid state are:",
        "a": "Electrovalent (ionic) bonds",
        "b": "Covalent bonds",
        "c": "Van der Waals (London dispersion) forces",
        "d": "Hydrogen bonds",
        "ans": 2,
        "explanation": "Naphthalene (C₁₀H₈) is a non-polar covalent molecule. Its molecular crystal lattice is held together purely by weak van der Waals dispersion forces, accounting for its low melting point (81°C) and ease of sublimation."
    },
    {
        "id": "chem_mr_163",
        "topic": "Atomic Structure & Ions",
        "year": "1990",
        "question": "A metallic ion X²⁺ with an inert noble gas electron configuration contains 18 electrons. How many protons are present in the nucleus of this ion?",
        "a": "20", "b": "18", "c": "16", "d": "22",
        "ans": 0,
        "explanation": "Neutral atom X lost 2 electrons to form X²⁺. Therefore, the neutral atom has 18 + 2 = 20 electrons and 20 protons (Calcium, Z = 20)."
    },
    {
        "id": "chem_mr_164",
        "topic": "Periodic Properties & Trends",
        "year": "1990",
        "question": "Which of the following physical properties decreases progressively from left to right across a period of the periodic table?",
        "a": "Ionization energy", "b": "Electron affinity", "c": "Electronegativity", "d": "Atomic radius",
        "ans": 3,
        "explanation": "Across a period from left to right, effective nuclear charge increases while electrons are added to the same principal energy shell. The increased nuclear pull draws outer electrons closer, decreasing atomic radius."
    },
    {
        "id": "chem_mr_165",
        "topic": "Atomic Structure & Periodic Configuration",
        "year": "1990",
        "question": "What are the common oxidation numbers exhibited by chlorine (atomic number 17, electronic configuration 2, 8, 7)?",
        "a": "-1, +1, +3, +5, +7", "b": "-2, +2, +4", "c": "-3, +3, +5", "d": "+2, +4, +6",
        "ans": 0,
        "explanation": "Chlorine gains one electron to achieve an octet (-1 oxidation state in chlorides) or shares its 7 valence electrons with more electronegative oxygen to form oxoacids/oxoanions in +1, +3, +5, and +7 states."
    },
    {
        "id": "chem_mr_166",
        "topic": "Periodic Properties (Electron Affinity)",
        "year": "1990",
        "question": "The energy change accompanying the addition of an electron to an isolated gaseous atom to form a uninegative gaseous ion is known as:",
        "a": "First ionization energy",
        "b": "Electronegativity",
        "c": "First electron affinity",
        "d": "Lattice energy",
        "ans": 2,
        "explanation": "First electron affinity is defined as the enthalpy change when one mole of electrons is acquired by one mole of gaseous atoms to form one mole of uninegative ions: X(g) + e⁻ → X⁻(g)."
    },
    {
        "id": "chem_mr_167",
        "topic": "Solutions & Gas Solubility",
        "year": "1990",
        "question": "The molar ratio of oxygen to nitrogen dissolved in air-saturated water is approximately 1:2 (or ~33% O₂), whereas it is 1:4 (21% O₂) in atmospheric air. This difference occurs because:",
        "a": "Oxygen is significantly more soluble in water than nitrogen",
        "b": "Nitrogen has a higher partial pressure",
        "c": "Oxygen reacts chemically with water",
        "d": "Nitrogen decomposes in water",
        "ans": 0,
        "explanation": "Oxygen is more soluble in water than nitrogen due to higher polarizability. Therefore, dissolved air is enriched in oxygen compared to atmospheric air."
    },
    {
        "id": "chem_mr_168",
        "topic": "Environmental Pollution & Poisonous Gases",
        "year": "1990",
        "question": "An environmental spill released a high concentration of poisonous, foul-smelling hydrogen sulphide (H₂S) gas. The contaminated air can be neutralized by spraying with:",
        "a": "Moist sulphur(IV) oxide (SO₂) gas/water",
        "b": "Concentrated hydrochloric acid",
        "c": "Pure nitrogen gas",
        "d": "Anhydrous carbon dioxide",
        "ans": 0,
        "explanation": "Moist SO₂ reacts with H₂S in a redox reaction to deposit harmless solid elemental sulfur and water: 2H₂S(g) + SO₂(g) → 3S(s) + 2H₂O(l)."
    },
    {
        "id": "chem_mr_169",
        "topic": "Stoichiometry & Hydrated Salts",
        "year": "1990",
        "question": "1.34 g of hydrated sodium tetraoxosulphate(VI) (Na₂SO₄·xH₂O) was heated to constant weight, leaving 0.71 g of anhydrous salt. The value of x is: [Na=23, S=32, O=16, H=1]",
        "a": "1", "b": "2", "c": "7", "d": "10",
        "ans": 2,
        "explanation": "Mass of anhydrous Na₂SO₄ = 0.71 g (0.71 / 142 = 0.0050 mol). Mass of water lost = 1.34 - 0.71 = 0.63 g (0.63 / 18 = 0.035 mol). x = 0.035 / 0.0050 = 7 (Na₂SO₄·7H₂O)."
    },
    {
        "id": "chem_mr_170",
        "topic": "Water Hardness & Soap",
        "year": "1990",
        "question": "A water sample that lathers immediately and easily with soap can be assumed to have a negligible concentration of:",
        "a": "Na⁺ and K⁺ ions", "b": "Ca²⁺ and Mg²⁺ ions", "c": "Cl⁻ and NO₃⁻ ions", "d": "SO₄²⁻ ions",
        "ans": 1,
        "explanation": "Hardness in water is caused by dissolved calcium (Ca²⁺) and magnesium (Mg²⁺) ions, which precipitate insoluble scum with stearate soap molecules. Soft water contains negligible Ca²⁺/Mg²⁺."
    },
    {
        "id": "chem_mr_171",
        "topic": "Acids, Bases & pH Calculations",
        "year": "1990",
        "question": "Which of the following 0.10 M aqueous solutions has the lowest pH value?",
        "a": "Sodium trioxocarbonate(IV) (Na₂CO₃)",
        "b": "Ethanoic acid (CH₃COOH)",
        "c": "Hydrochloric acid (HCl)",
        "d": "Distilled water",
        "ans": 2,
        "explanation": "Hydrochloric acid (HCl) is a strong mineral acid that completely dissociates in aqueous solution (0.10 M HCl yields [H⁺] = 0.10 M, pH = -log(0.10) = 1.0), giving the lowest pH."
    },
    {
        "id": "chem_mr_172",
        "topic": "Acids, Bases & Salts (Hydrolysis)",
        "year": "1990",
        "question": "Which of the following salts dissolves in water to form a strictly neutral solution with pH = 7.0 that does not affect litmus?",
        "a": "NH₄Cl", "b": "Na₂CO₃", "c": "FeCl₃", "d": "NaCl",
        "ans": 3,
        "explanation": "Sodium chloride (NaCl) is the salt of a strong acid (HCl) and a strong base (NaOH). Neither Na⁺ nor Cl⁻ undergoes hydrolysis in water, maintaining [H⁺] = [OH⁻] = 10⁻⁷ M (pH = 7.0)."
    },
    {
        "id": "chem_mr_173",
        "topic": "Volumetric Neutralization Calculations",
        "year": "1990",
        "question": "What volume of 0.10 M H₃PO₄ will be required to neutralize 45.0 cm³ of 0.20 M NaOH? [H₃PO₄ + 3NaOH → Na₃PO₄ + 3H₂O]",
        "a": "10.0 cm³", "b": "20.0 cm³", "c": "27.0 cm³", "d": "30.0 cm³",
        "ans": 3,
        "explanation": "Using (C_A · V_A) / (C_B · V_B) = n_A / n_B => (0.10 × V_A) / (0.20 × 45.0) = 1 / 3 => 0.10 · V_A = 9.0 / 3 = 3.0 => V_A = 3.0 / 0.10 = 30.0 cm³."
    },
    {
        "id": "chem_mr_174",
        "topic": "Classification of Salts",
        "year": "1990",
        "question": "Which of the following chemical species is classified as a basic salt?",
        "a": "Na₂CO₃", "b": "Mg(OH)Cl", "c": "NaHCO₃", "d": "KAl(SO₄)₂·12H₂O",
        "ans": 1,
        "explanation": "Mg(OH)Cl (magnesium hydroxychloride) contains replaceable hydroxide ions (OH⁻) resulting from incomplete neutralization of a polyhydroxy base, defining it as a basic salt."
    },
    {
        "id": "chem_mr_175",
        "topic": "Redox & Dual Oxidizing/Reducing Behaviour",
        "year": "1990",
        "question": "Which of the following substances can act as both an oxidizing agent and a reducing agent depending on reaction conditions?",
        "a": "Hydrogen (H₂)", "b": "Sulphur(IV) oxide (SO₂)", "c": "Carbon (C)", "d": "Methane (CH₄)",
        "ans": 1,
        "explanation": "In SO₂, sulfur is in an intermediate oxidation state (+4). It can be oxidized to +6 (acting as a reducing agent towards Cl₂ or KMnO₄) or reduced to 0 (acting as an oxidizing agent towards H₂S)."
    },
    {
        "id": "chem_mr_176",
        "topic": "Electrolysis of Copper Chloride",
        "year": "1990",
        "question": "During the electrolysis of aqueous copper(II) chloride (CuCl₂) using carbon electrodes, the cathode half-cell reaction is:",
        "a": "Cu²⁺(aq) + 2e⁻ → Cu(s)",
        "b": "2Cl⁻(aq) → Cl₂(g) + 2e⁻",
        "c": "4OH⁻(aq) → 2H₂O(l) + O₂(g) + 4e⁻",
        "d": "2H⁺(aq) + 2e⁻ → H₂(g)",
        "ans": 0,
        "explanation": "At the cathode (negative electrode), Cu²⁺ ions are preferentially discharged over H⁺ ions due to copper's lower position (more positive reduction potential) in the electrochemical series: Cu²⁺ + 2e⁻ → Cu(s)."
    },
    {
        "id": "chem_mr_177",
        "topic": "Reaction Kinetics & Rate Increase",
        "year": "1990",
        "question": "For the reaction: Na₂S₂O₃(aq) + 2HCl(aq) → 2NaCl(aq) + H₂O(l) + SO₂(g) + S(s), which of the following changes will produce the greatest increase in the reaction rate?",
        "a": "Decreasing temperature and increasing reactant concentration",
        "b": "Increasing temperature and decreasing reactant concentration",
        "c": "Increasing both the temperature and the concentration of the reactants",
        "d": "Decreasing both temperature and reactant concentration",
        "ans": 2,
        "explanation": "Reaction rate increases exponentially with temperature (higher kinetic energy, greater fraction of molecules exceeding E_a) and directly with concentration (higher collision frequency). Increasing both yields the maximum rate increase."
    },
    {
        "id": "chem_mr_178",
        "topic": "Reaction Kinetics & Catalysts",
        "year": "1990",
        "question": "Which of the following thermodynamic and kinetic properties is modified by the introduction of a catalyst in a reversible reaction?",
        "a": "Enthalpy change (ΔH)",
        "b": "Activation energy (E_a)",
        "c": "Free energy change (ΔG)",
        "d": "Equilibrium constant (K_eq)",
        "ans": 1,
        "explanation": "A catalyst lowers the activation energy barrier for both forward and reverse paths. It does NOT alter state functions (ΔH, ΔS, ΔG) or the equilibrium constant."
    },
    {
        "id": "chem_mr_179",
        "topic": "Non-Metals & Fire Extinguishers",
        "year": "1990",
        "question": "Which of the following gases is widely used in fire extinguishers because it is denser than air and does not support combustion?",
        "a": "Carbon(II) oxide (CO)",
        "b": "Carbon(IV) oxide (CO₂)",
        "c": "Ammonia (NH₃)",
        "d": "Sulphur(IV) oxide (SO₂)",
        "ans": 1,
        "explanation": "Carbon(IV) oxide (CO₂) is non-flammable, approximately 1.5 times denser than air, and smothers flames by blanketing the combustion zone and cutting off oxygen supply."
    },
    {
        "id": "chem_mr_180",
        "topic": "Redox Reactions (Iron & H₂S)",
        "year": "1990",
        "question": "When H₂S gas is bubbled into a yellow aqueous solution of iron(III) chloride (FeCl₃), the solution turns pale green with a yellow turbidity. This is because:",
        "a": "Fe³⁺ ions are oxidized to Fe⁴⁺",
        "b": "Fe³⁺ ions are reduced to pale green Fe²⁺ ions while H₂S is oxidized to sulfur",
        "c": "FeCl₃ precipitates as an insoluble sulfide",
        "d": "Chlorine gas is evolved",
        "ans": 1,
        "explanation": "2FeCl₃(aq) + H₂S(g) → 2FeCl₂(aq) + 2HCl(aq) + S(s)↓. Yellow Fe³⁺ is reduced to pale green Fe²⁺, and H₂S is oxidized to a yellow precipitate of elemental sulfur."
    },
    {
        "id": "chem_mr_181",
        "topic": "Organic Dehydration & Carbohydrates",
        "year": "1990",
        "question": "In the reaction: C₁₂H₂₂O₁₁(s) → 12C(s) + 11H₂O(l), concentrated tetraoxosulphate(VI) acid acts as a powerful:",
        "a": "Reducing agent", "b": "Oxidizing agent", "c": "Dehydrating agent", "d": "Hydrolytic catalyst",
        "ans": 2,
        "explanation": "Concentrated H₂SO₄ has an intense chemical affinity for water, extracting the elements of water (H and O in a 2:1 ratio) from carbohydrates (sucrose, cellulose) to leave a black spongy mass of carbon ('charring')."
    },
    {
        "id": "chem_mr_182",
        "topic": "Non-Metals (Nitrogen Preparation)",
        "year": "1990",
        "question": "Suitable laboratory reagents for preparing pure nitrogen gas by gentle warming are aqueous solutions of:",
        "a": "Sodium dioxonitrate(III) (NaNO₂) and ammonium chloride (NH₄Cl)",
        "b": "Sodium trioxonitrate(V) (NaNO₃) and ammonium chloride (NH₄Cl)",
        "c": "Sodium chloride and concentrated nitric acid",
        "d": "Ammonium sulfate and dilute hydrochloric acid",
        "ans": 0,
        "explanation": "NaNO₂(aq) + NH₄Cl(aq) → NaCl(aq) + NH₄NO₂(aq). Upon gentle warming, unstable ammonium dioxonitrate(III) decomposes smoothly into nitrogen and steam: NH₄NO₂ → N₂↑ + 2H₂O."
    },
    {
        "id": "chem_mr_183",
        "topic": "Thermal Decomposition of Nitrates",
        "year": "1990",
        "question": "Thermal decomposition of crystalline copper(II) trioxonitrate(V) [Cu(NO₃)₂] produces solid copper(II) oxide and:",
        "a": "Nitrogen(II) oxide and steam",
        "b": "Nitrogen(IV) oxide (NO₂) gas and oxygen (O₂) gas",
        "c": "Dinitrogen monoxide and oxygen",
        "d": "Nitrogen gas and water",
        "ans": 1,
        "explanation": "2Cu(NO₃)₂(s) → 2CuO(s) + 4NO₂(g) + O₂(g). Heavy metal nitrates decompose upon heating into the metal oxide, reddish-brown fumes of NO₂, and oxygen gas."
    },
    {
        "id": "chem_mr_184",
        "topic": "Industrial Chemistry (Chlor-Alkali Process)",
        "year": "1990",
        "question": "Chlorine gas is manufactured commercially on a massive scale by:",
        "a": "Heating potassium trioxochlorate(V)",
        "b": "Electrolysis of concentrated sodium chloride solution (brine)",
        "c": "Reaction of manganese(IV) oxide with dilute HCl",
        "d": "Displacement of bromide by fluorine",
        "ans": 1,
        "explanation": "The chlor-alkali industry electrolyzes saturated brine (concentrated NaCl solution) in diaphragm or membrane cells to produce Cl₂ gas at the anode, H₂ gas at the cathode, and NaOH in solution."
    },
    {
        "id": "chem_mr_185",
        "topic": "Industrial Chemistry (Glass Manufacture)",
        "year": "1990",
        "question": "Which of the following compounds is an essential flux raw material used with silica (SiO₂) and limestone (CaCO₃) in the manufacture of ordinary soda-lime glass?",
        "a": "Sodium chloride", "b": "Sodium trioxocarbonate(IV) (soda ash, Na₂CO₃)", "c": "Sodium tetraoxosulphate(VI)", "d": "Sodium trioxonitrate(V)",
        "ans": 1,
        "explanation": "Soda-lime glass is manufactured by fusing silica sand (SiO₂), soda ash (Na₂CO₃), and limestone (CaCO₃) in a high-temperature furnace: Na₂CO₃ + SiO₂ → Na₂SiO₃ + CO₂."
    },
    {
        "id": "chem_mr_186",
        "topic": "Metallurgy of Aluminium (Hall-Héroult Process)",
        "year": "1990",
        "question": "Aluminium is extracted commercially from pure alumina (Al₂O₃) by:",
        "a": "Reduction with coke in a blast furnace",
        "b": "Electrolysis of fused alumina dissolved in molten cryolite (Na₃AlF₆)",
        "c": "Reduction with hydrogen gas",
        "d": "Thermal decomposition of its carbonate",
        "ans": 1,
        "explanation": "Pure Al₂O₃ has a very high melting point (~2050°C). Dissolving it in molten cryolite (Na₃AlF₆) at ~950°C lowers the melting temperature and enhances electrical conductivity for electrolytic reduction."
    },
    {
        "id": "chem_mr_187",
        "topic": "Purification of Metals (Electrorefining)",
        "year": "1990",
        "question": "In the industrial electrorefining of impure blister copper, the electrolytic cell setup requires that:",
        "a": "Platinum electrodes are used as anode and cathode",
        "b": "The impure copper is made the anode, and a pure copper strip is the cathode in a CuSO₄/H₂SO₄ electrolyte",
        "c": "The impure copper is made the cathode",
        "d": "Carbon electrodes are used throughout",
        "ans": 1,
        "explanation": "Impure copper dissolves at the anode (Cu → Cu²⁺ + 2e⁻) and pure copper deposits onto the cathode (Cu²⁺ + 2e⁻ → Cu), while impurities like silver and gold settle below as valuable anode slime."
    },
    {
        "id": "chem_mr_188",
        "topic": "Organic Functional Groups (Esters)",
        "year": "1990",
        "question": "Alkanoate esters are prepared by the condensation reaction between an alkanoic acid and an:",
        "a": "Alkyl halide", "b": "Alkanol (alcohol)", "c": "Ether", "d": "Alkanone",
        "ans": 1,
        "explanation": "Esterification involves the acid-catalyzed reaction between a carboxylic acid (RCOOH) and an alcohol (R'OH) to yield an ester (RCOOR') and water: RCOOH + R'OH ⇌ RCOOR' + H₂O."
    },
    {
        "id": "chem_mr_189",
        "topic": "Organic Chemistry (Hydrocarbon Classification)",
        "year": "1990",
        "question": "The four fundamental classes of hydrocarbons are:",
        "a": "Alkanes, alkenes, alkynes, and aromatic hydrocarbons",
        "b": "Methane, ethane, propane, and butane",
        "c": "Alcohols, esters, carboxylic acids, and amines",
        "d": "Carbohydrates, lipids, proteins, and nucleic acids",
        "ans": 0,
        "explanation": "Hydrocarbons are categorized into aliphatic saturated (alkanes), aliphatic unsaturated with double bonds (alkenes), aliphatic unsaturated with triple bonds (alkynes), and aromatic systems (arenes)."
    },
    {
        "id": "chem_mr_190",
        "topic": "Petroleum Refining (Catalytic Reforming)",
        "year": "1990",
        "question": "The high-temperature catalytic conversion of straight-chain alkanes into branched-chain alkanes, cycloalkanes, and aromatics with hydrogen evolution is known as:",
        "a": "Photolysis", "b": "Polymerization", "c": "Catalytic reforming (isomerization/aromatization)", "d": "Saponification",
        "ans": 2,
        "explanation": "Catalytic reforming restructures low-octane straight-chain naphtha hydrocarbons over platinum catalysts into high-octane branched isomers and aromatics for premium petrol blending."
    },
    {
        "id": "chem_mr_191",
        "topic": "Biochemistry (Enzymatic Hydrolysis)",
        "year": "1990",
        "question": "In the enzymatic breakdown of starch: 2(C₆H₁₀O₅)ₙ + nH₂O → nC₁₂H₂₂O₁₁, the enzyme diastase functions as a:",
        "a": "Dehydrating agent", "b": "Biological catalyst (enzyme)", "c": "Reducing agent", "d": "Denaturing agent",
        "ans": 1,
        "explanation": "Diastase (amylase) is a biological catalyst that accelerates the hydrolysis of complex polysaccharide starch macromolecules into the disaccharide maltose without being consumed."
    },
    {
        "id": "chem_mr_192",
        "topic": "Organic Chemistry (Boiling Points & Hydrogen Bonding)",
        "year": "1990",
        "question": "Which of the following four-carbon isomeric compounds has the highest boiling point?",
        "a": "Butan-1-ol (CH₃CH₂CH₂CH₂OH)",
        "b": "Butanal (CH₃CH₂CH₂CHO)",
        "c": "Butane (CH₃CH₂CH₂CH₃)",
        "d": "Ethoxyethane (CH₃CH₂OCH₂CH₃)",
        "ans": 0,
        "explanation": "Butan-1-ol contains a polar hydroxyl (-OH) group capable of forming strong intermolecular hydrogen bonds, requiring significantly more thermal energy to boil (b.p. ~117°C) than aldehydes, ethers, or alkanes."
    },
    {
        "id": "chem_mr_193",
        "topic": "Applied Chemistry (Synthetic Detergents)",
        "year": "1990",
        "question": "Synthetic detergents (soapless detergents) are superior to ordinary soaps in hard-water districts because:",
        "a": "Their calcium and magnesium salts are water-soluble and do not form insoluble scum",
        "b": "They are cheaper to manufacture",
        "c": "They are less soluble in water",
        "d": "They contain natural animal fats",
        "ans": 0,
        "explanation": "Unlike sodium carboxylate soaps (which precipitate insoluble calcium stearate scum in hard water), alkyl sulfonates and alkyl benzene sulfonates (R-SO₃⁻Na⁺) form soluble calcium and magnesium salts."
    },
    {
        "id": "chem_mr_194",
        "topic": "Fossil Fuels (Destructive Distillation of Coal)",
        "year": "1990",
        "question": "The destructive distillation of bituminous coal in the absence of air produces:",
        "a": "Coal gas, coal tar, ammoniacal liquor, and solid coke",
        "b": "Carbon(IV) oxide and steam only",
        "c": "Producer gas and water gas",
        "d": "Petroleum ether and asphalt",
        "ans": 0,
        "explanation": "Pyrolysis (destructive distillation) of coal yields non-condensable coal gas (H₂, CH₄, CO), coal tar (aromatics, phenols), ammoniacal liquor (fertilizer feed), and porous carbon residue (coke)."
    },
    {
        "id": "chem_mr_195",
        "topic": "Gas Laws (Dalton's Law of Partial Pressures)",
        "year": "1990",
        "question": "What is the partial pressure of hydrogen gas collected over water at standard atmospheric pressure (760 mmHg) and 25°C, if the saturated vapour pressure of water at 25°C is 23 mmHg?",
        "a": "737 mmHg", "b": "760 mmHg", "c": "783 mmHg", "d": "740 mmHg",
        "ans": 0,
        "explanation": "By Dalton's law of partial pressures: P_total = P_dry gas + P_water vapour => P_H₂ = P_total - P_H₂O = 760 - 23 = 737 mmHg."
    },
    {
        "id": "chem_mr_196",
        "topic": "Chemical Bonding (Formula from Electronic Configuration)",
        "year": "1990",
        "question": "Element X has configuration 1s² 2s² 2p⁴ and element Y has configuration 1s² 2s² 2p⁶ 3s² 3p¹. When they combine chemically, the formula of the compound is:",
        "a": "YX", "b": "Y₂X", "c": "Y₂X₃", "d": "X₂Y₃",
        "ans": 2,
        "explanation": "Element X (Oxygen, Z=8) has 6 valence electrons and requires 2 electrons (valency 2). Element Y (Aluminium, Z=13) has 3 valence electrons (valency 3). Combining Y³⁺ and X²⁻ yields Y₂X₃ (Al₂O₃)."
    },
    {
        "id": "chem_mr_197",
        "topic": "Nuclear Composition",
        "year": "1990",
        "question": "The atomic number of caesium is 55 and its mass number is 133. The nucleus of a caesium atom contains:",
        "a": "55 protons and 55 electrons",
        "b": "55 protons and 78 neutrons",
        "c": "78 protons and 55 neutrons",
        "d": "133 protons and 55 neutrons",
        "ans": 1,
        "explanation": "The nucleus consists of Z protons = 55 and N neutrons = A - Z = 133 - 55 = 78 neutrons. (Electrons orbit outside the nucleus)."
    },
    {
        "id": "chem_mr_198",
        "topic": "Periodic Table (Noble Gases)",
        "year": "1990",
        "question": "Four elements P, Q, R, and S have atomic numbers 4, 10, 12, and 14 respectively. Which of these elements is a chemically unreactive noble gas?",
        "a": "P (Z = 4)", "b": "Q (Z = 10)", "c": "R (Z = 12)", "d": "S (Z = 14)",
        "ans": 1,
        "explanation": "Element Q (Z = 10, Neon) has a stable closed-shell octet electron configuration (2, 8), making it an inert noble gas belonging to Group 0 (Group 18)."
    },
    {
        "id": "chem_mr_199",
        "topic": "Atomic Structure & Valence Electrons",
        "year": "1990",
        "question": "How many valence electrons are contained in an atom of phosphorus (³¹₁₅P)?",
        "a": "3", "b": "5", "c": "15", "d": "31",
        "ans": 1,
        "explanation": "Phosphorus (atomic number 15) has electron configuration 2, 8, 5 (or 1s² 2s² 2p⁶ 3s² 3p³). Its outermost principal quantum shell (n=3) contains 2 + 3 = 5 valence electrons."
    },
    {
        "id": "chem_mr_200",
        "topic": "Environmental Pollution (Smelting)",
        "year": "1990",
        "question": "The gaseous pollutant sulphur(IV) oxide (SO₂) is most likely to be detected in substantial quantities in the atmosphere surrounding a:",
        "a": "Bauxite-to-aluminium reduction plant",
        "b": "Sulphide ore copper-smelting plant",
        "c": "Margarine manufacturing plant",
        "d": "Chlor-alkali electrolysis plant",
        "ans": 1,
        "explanation": "Copper extraction from copper pyrites (CuFeS₂) involves roasting sulphide ores in air: 2CuFeS₂ + 4O₂ → Cu₂S + 2FeO + 3SO₂↑, releasing huge amounts of SO₂ gas."
    }
]

print("Part 4 dataset ready")
