# Part 6: Questions 251 - 300 (1998 - 2002 Series)
part6_questions = [
    {
        "id": "chem_mr_251",
        "topic": "Chemical Storage & Handling",
        "year": "1998",
        "question": "Solid sodium hydroxide (caustic soda) pellets must be stored in tightly stoppered, airtight plastic containers because they:",
        "a": "Decompose on exposure to light",
        "b": "Are highly deliquescent and absorb both atmospheric moisture and carbon(IV) oxide",
        "c": "Sublime rapidly at room temperature",
        "d": "Release toxic chlorine gas",
        "ans": 1,
        "explanation": "Solid NaOH is strongly deliquescent (absorbs water from air until it dissolves) and reacts with acidic CO₂ to form sodium carbonate crust, degrading the reagent."
    },
    {
        "id": "chem_mr_252",
        "topic": "Industrial Chemistry (Coloured Glass)",
        "year": "1998",
        "question": "To produce deep blue or greenish-blue coloured glass, which metal oxide is added to the fused silicate batch mixture?",
        "a": "Iron(III) oxide", "b": "Copper(II) oxide or Cobalt(II) oxide", "c": "Sodium oxide", "d": "Calcium oxide",
        "ans": 1,
        "explanation": "Transition metal ions with partially filled d-orbitals produce characteristic colours in glass by forming coloured silicates: Cobalt gives deep royal blue, and Copper(II) gives turquoise/greenish-blue."
    },
    {
        "id": "chem_mr_253",
        "topic": "Qualitative Analysis & Amphoteric Lead",
        "year": "1998",
        "question": "Which of the following white compounds decomposes on heating to leave a residue that is reddish-brown when hot and yellow when cold (PbO), and forms a precipitate with aqueous NaOH that dissolves in excess alkali?",
        "a": "ZnCO₃", "b": "PbCO₃", "c": "Al₂(SO₄)₃", "d": "(NH₄)₂CO₃",
        "ans": 1,
        "explanation": "PbCO₃ decomposes to yellow PbO and CO₂. With NaOH, Pb²⁺ forms white amphoteric Pb(OH)₂, which dissolves in excess NaOH to form soluble sodium plumbite(II), [Pb(OH)₄]²⁻."
    },
    {
        "id": "chem_mr_254",
        "topic": "Organic Chemistry (Cycloalkane Isomerism)",
        "year": "1998",
        "question": "How many structural (constitutional) cycloalkane isomers have the molecular formula C₅H₁₀?",
        "a": "2", "b": "3", "c": "5", "d": "7",
        "ans": 2,
        "explanation": "The 5 cycloalkane isomers of C₅H₁₀ are: cyclopentane, methylcyclobutane, 1,1-dimethylcyclopropane, 1,2-dimethylcyclopropane, and ethylcyclopropane."
    },
    {
        "id": "chem_mr_255",
        "topic": "Organic Qualitative Analysis (Alkanols vs Ethers)",
        "year": "1998",
        "question": "A colourless neutral organic liquid reacts briskly with clean sodium metal to liberate bubbles of hydrogen gas. The liquid must be an:",
        "a": "Alkanoate ester", "b": "Alkene", "c": "Alkanol (alcohol)", "d": "Alkane",
        "ans": 2,
        "explanation": "Alkanols contain a polar hydroxyl proton that is displaced by active alkali metals (Na/K) to form sodium alkoxides and effervescence of hydrogen gas: 2ROH + 2Na → 2RONa + H₂↑."
    },
    {
        "id": "chem_mr_256",
        "topic": "Acids, Bases & Neutralization",
        "year": "1998",
        "question": "HOOC-COOH + 2NaOH → NaOOC-COONa + 2H₂O. The chemical reaction above is an example of:",
        "a": "An addition reaction", "b": "A neutralization reaction", "c": "An elimination reaction", "d": "A substitution reaction",
        "ans": 1,
        "explanation": "The reaction between ethanedioic (oxalic) acid and sodium hydroxide (a strong base) to yield a carboxylate salt and water is a classic neutralization reaction."
    },
    {
        "id": "chem_mr_257",
        "topic": "Physical Properties & Intermolecular Forces",
        "year": "1998",
        "question": "Alkanoic acids have significantly lower volatility (higher boiling points) than corresponding alkanols of similar molecular mass because alkanoic acids:",
        "a": "Are non-polar",
        "b": "Form stronger cyclic dimeric hydrogen bonds involving two hydrogen bonds per pair of molecules",
        "c": "Have higher density",
        "d": "Cannot form hydrogen bonds",
        "ans": 1,
        "explanation": "Carboxylic acids form stable cyclic dimers via pairs of intermolecular hydrogen bonds (>C=O···H-O-), creating effectively doubled molecular units with much higher boiling points than alcohols."
    },
    {
        "id": "chem_mr_258",
        "topic": "Petroleum & Octane Rating",
        "year": "1998",
        "question": "A fuel sample whose antiknock performance matches a mixture of 55% 2,2,4-trimethylpentane (isooctane) and 45% n-heptane by volume has an octane number of:",
        "a": "45", "b": "55", "c": "80", "d": "100",
        "ans": 1,
        "explanation": "By definition, the octane number of a fuel is the percentage by volume of isooctane (octane rating 100) in a reference blend with n-heptane (octane rating 0) that matches the knock characteristics. Hence, the octane number is 55."
    },
    {
        "id": "chem_mr_259",
        "topic": "Separation of Liquid Mixtures",
        "year": "1998",
        "question": "Which of the following mixtures can be separated into its pure components by fractional distillation?",
        "a": "Nitrogen and oxygen from liquefied air",
        "b": "Sodium chloride from sea water",
        "c": "Sand and water",
        "d": "Iodine from sand",
        "ans": 0,
        "explanation": "Liquid air contains liquid nitrogen (b.p. -196°C) and liquid oxygen (b.p. -183°C). Fractional distillation exploits their difference in boiling points to separate nitrogen (top) from oxygen (bottom)."
    },
    {
        "id": "chem_mr_260",
        "topic": "Stoichiometry & Thermal Decomposition",
        "year": "1998",
        "question": "Calculate the volume of CO₂ gas measured at S.T.P produced by the complete thermal decomposition of 1.00 kg of potassium hydrogen trioxocarbonate(IV) (KHCO₃). 2KHCO₃ → K₂CO₃ + H₂O + CO₂. [K=39, C=12, O=16, H=1, Molar volume at STP = 22.4 dm³]",
        "a": "28 dm³", "b": "56 dm³", "c": "112 dm³", "d": "224 dm³",
        "ans": 2,
        "explanation": "Molar mass of KHCO₃ = 39 + 1 + 12 + 48 = 100 g/mol. Moles KHCO₃ in 1000 g = 1000 / 100 = 10.0 mol. 2 moles KHCO₃ yield 1 mole CO₂ => Moles CO₂ = 10.0 / 2 = 5.0 mol. Volume at STP = 5.0 × 22.4 dm³ = 112 dm³."
    },
    {
        "id": "chem_mr_261",
        "topic": "Ideal Gas Equation (PV = nRT)",
        "year": "1998",
        "question": "A sample of an ideal gas exerts a pressure of 8.20 atm when confined in a 2.93 dm³ container at 20°C (293 K). What is the number of moles of gas present? [R = 0.0820 dm³ atm K⁻¹ mol⁻¹]",
        "a": "1.00 mol", "b": "2.00 mol", "c": "3.00 mol", "d": "4.00 mol",
        "ans": 0,
        "explanation": "PV = nRT => n = (PV) / (RT) = (8.20 × 2.93) / (0.0820 × 293) = 24.026 / 24.026 = 1.00 mol."
    },
    {
        "id": "chem_mr_262",
        "topic": "Chemical Bonding (Valence Electrons)",
        "year": "1998",
        "question": "Atoms of element X (with 2 valence electrons) combine with atoms of element Y (with 7 valence electrons). Which of the following statements is FALSE?",
        "a": "The resulting compound has the empirical formula XY",
        "b": "The bonding is predominantly electrovalent (ionic)",
        "c": "The compound contains X²⁺ cations",
        "d": "The compound contains Y⁻ anions",
        "ans": 0,
        "explanation": "Element X donates its 2 valence electrons to become X²⁺, while each Y atom requires 1 electron to become Y⁻. Two Y atoms combine with one X atom to give XY₂, so formula XY is FALSE."
    },
    {
        "id": "chem_mr_263",
        "topic": "Atomic Structure & Isoelectronic Species",
        "year": "1998",
        "question": "The ions X⁻ and Y⁺ are isoelectronic, each containing a total of 10 electrons. How many protons are present in the nuclei of neutral atoms X and Y respectively?",
        "a": "10 and 10", "b": "9 and 11", "c": "11 and 9", "d": "8 and 12",
        "ans": 1,
        "explanation": "X⁻ has 10 electrons after gaining 1 electron => neutral X has 10 - 1 = 9 protons (Fluorine). Y⁺ has 10 electrons after losing 1 electron => neutral Y has 10 + 1 = 11 protons (Sodium)."
    },
    {
        "id": "chem_mr_264",
        "topic": "Electronic Configuration & Hund's Rule",
        "year": "1998",
        "question": "An element has the ground state electronic configuration 1s² 2s² 2p⁶ 3s² 3p³. According to Hund's rule, how many unpaired electrons does this atom have in its 3p subshell?",
        "a": "1", "b": "2", "c": "3", "d": "5",
        "ans": 2,
        "explanation": "Hund's rule of maximum multiplicity states that electrons occupy degenerate orbitals singly with parallel spins before pairing up. The three 3p orbitals (3p_x, 3p_y, 3p_z) each contain 1 unpaired electron (total = 3 unpaired electrons)."
    },
    {
        "id": "chem_mr_265",
        "topic": "Chemical Bonding in Ammonium Chloride",
        "year": "1998",
        "question": "Which of the following types of chemical bonds are present in crystalline solid ammonium chloride (NH₄Cl)?",
        "a": "Ionic bonds only",
        "b": "Covalent bonds only",
        "c": "Electrovalent (ionic), polar covalent, and coordinate covalent (dative) bonds",
        "d": "Metallic and hydrogen bonds",
        "ans": 2,
        "explanation": "In NH₄Cl, the four N-H bonds inside the NH₄⁺ cation comprise 3 polar covalent bonds and 1 coordinate covalent (dative) bond (from the N lone pair to H⁺). Electrostatic attraction between NH₄⁺ and Cl⁻ constitutes an ionic (electrovalent) bond."
    },
    {
        "id": "chem_mr_266",
        "topic": "Periodic Table & Electronegativity Ordering",
        "year": "1998",
        "question": "Which of the following sequences correctly arranges the Period 3 elements in order of INCREASING electronegativity?",
        "a": "Cl < P < Al < Mg < Na",
        "b": "Na < Mg < Al < P < Cl",
        "c": "Na < Al < Mg < Cl < P",
        "d": "P < Na < Mg < Al < Cl",
        "ans": 1,
        "explanation": "Electronegativity increases steadily across a period from left to right as nuclear charge increases and atomic radius decreases: Na (0.93) < Mg (1.31) < Al (1.61) < P (2.19) < Cl (3.16)."
    },
    {
        "id": "chem_mr_267",
        "topic": "Gas Analysis & Alkaline Pyrogallol",
        "year": "1998",
        "question": "A sample of air was passed through a weighed tube containing alkaline pyrogallol. An increase in the weight of the tube is due to the absorption of:",
        "a": "Nitrogen", "b": "Carbon(II) oxide", "c": "Oxygen (O₂)", "d": "Argon",
        "ans": 2,
        "explanation": "Alkaline potassium pyrogallate (pyrogallol dissolved in KOH solution) is an active reagent that quantitatively and selectively absorbs oxygen gas from air mixtures."
    },
    {
        "id": "chem_mr_268",
        "topic": "Environmental Pollution & Toxic Heavy Metals",
        "year": "1998",
        "question": "Which of the following heavy metal ions is extremely toxic and hazardous in drinking water even in minute trace concentrations?",
        "a": "Ca²⁺", "b": "Mg²⁺", "c": "Hg²⁺ (Mercury) and Pb²⁺ (Lead)", "d": "Na⁺",
        "ans": 2,
        "explanation": "Mercury (Hg²⁺) and lead (Pb²⁺) are non-essential cumulative heavy metal poisons that bioaccumulate in tissues, causing severe neurological damage, renal failure, and Minamata disease."
    },
    {
        "id": "chem_mr_269",
        "topic": "Preparation of Temporary Hard Water",
        "year": "1998",
        "question": "A sample of temporary hard water can be synthesized in the laboratory by:",
        "a": "Dissolving calcium chloride in distilled water",
        "b": "Bubbling carbon(IV) oxide gas continuously into clear lime water until the precipitate redissolves",
        "c": "Dissolving sodium hydrogentrioxocarbonate(IV) in water",
        "d": "Adding sodium sulphate to distilled water",
        "ans": 1,
        "explanation": "Passing excess CO₂ into lime water converts insoluble CaCO₃ into soluble calcium hydrogen trioxocarbonate(IV): CaCO₃(s) + H₂O(l) + CO₂(g) → Ca(HCO₃)₂(aq), which is temporary hard water."
    },
    {
        "id": "chem_mr_270",
        "topic": "Colloids & Tyndall Effect",
        "year": "1998",
        "question": "A characteristic optical property that distinguishes a colloidal dispersion from a true solution is:",
        "a": "The Tyndall effect (light scattering)",
        "b": "True homogeneity",
        "c": "High osmotic pressure",
        "d": "Electrical neutrality",
        "ans": 0,
        "explanation": "Colloidal particles (1 to 100 nm) are sufficiently large to scatter a beam of visible light passing through them, rendering the light path visible (Tyndall effect). True solute particles (< 1 nm) do not scatter light."
    },
    {
        "id": "chem_mr_271",
        "topic": "Stoichiometry & Gas Volumes (Carbonates)",
        "year": "1998",
        "question": "What volume of CO₂ gas measured at S.T.P is liberated by reacting 10.0 cm³ of 0.10 M Na₂CO₃ solution with excess hydrochloric acid? [Molar volume of gas at STP = 22,400 cm³]",
        "a": "2.24 cm³", "b": "22.4 cm³", "c": "224.0 cm³", "d": "2240 cm³",
        "ans": 1,
        "explanation": "Na₂CO₃ + 2HCl → 2NaCl + H₂O + CO₂. Moles Na₂CO₃ = 0.010 dm³ × 0.10 M = 0.0010 mol = moles CO₂. Volume at STP = 0.0010 × 22,400 cm³ = 22.4 cm³."
    },
    {
        "id": "chem_mr_272",
        "topic": "Faraday's Laws & Oxidation States",
        "year": "1998",
        "question": "When a steady current of 1.50 A is passed for 4.0 hours through a molten tin salt, 13.3 g of metallic tin is deposited at the cathode. What is the oxidation state (valency) of tin in the salt? [Sn = 118.7, 1 F = 96,500 C]",
        "a": "+1", "b": "+2", "c": "+3", "d": "+4",
        "ans": 1,
        "explanation": "Q = I · t = 1.50 × (4 × 3600) = 21,600 C. Moles e⁻ = 21600 / 96500 = 0.2238 mol e⁻. Moles Sn deposited = 13.3 / 118.7 = 0.1120 mol Sn. Valency n = Moles e⁻ / Moles Sn = 0.2238 / 0.1120 ≈ 2. Thus, tin is in the +2 oxidation state (Sn²⁺)."
    },
    {
        "id": "chem_mr_273",
        "topic": "Salt Hydrolysis & pH",
        "year": "1998",
        "question": "Which of the following 0.10 M aqueous solutions will have a pH greater than 7.0 (alkaline)?",
        "a": "FeCl₃ and NH₄Cl",
        "b": "Na₂SO₄ and NaCl",
        "c": "Na₂CO₃ and CH₃COONa",
        "d": "AlCl₃ and (NH₄)₂SO₄",
        "ans": 2,
        "explanation": "Na₂CO₃ and CH₃COONa are salts formed from strong bases (NaOH) and weak acids (H₂CO₃ and CH₃COOH). Their conjugate base anions (CO₃²⁻ and CH₃COO⁻) undergo basic hydrolysis in water to produce excess OH⁻ ions (pH > 7)."
    },
    {
        "id": "chem_mr_274",
        "topic": "Redox Reactions (Balancing Half-Equations)",
        "year": "1998",
        "question": "In the reduction half-equation: MnO₄⁻ + 8H⁺ + ne⁻ → Mn²⁺ + 4H₂O, the value of n is:",
        "a": "2", "b": "3", "c": "4", "d": "5",
        "ans": 3,
        "explanation": "Balancing charge: Reactant side has (-1) + 8(+1) + n(-1) = +7 - n. Product side has +2. Setting +7 - n = +2 gives n = 5 electrons (Mn changes from +7 in MnO₄⁻ to +2 in Mn²⁺)."
    },
    {
        "id": "chem_mr_275",
        "topic": "Redox Reactions (Hydrogen Sulphide & SO₂)",
        "year": "1998",
        "question": "In the reaction: 2H₂S(g) + SO₂(g) → 3S(s) + 2H₂O(l), which species acts as the reducing agent?",
        "a": "SO₂", "b": "H₂S", "c": "Elemental S", "d": "H₂O",
        "ans": 1,
        "explanation": "In H₂S, sulfur is in the -2 oxidation state and increases to 0 in elemental sulfur (oxidation, loss of electrons). Therefore, H₂S is the reducing agent, reducing SO₂ (+4 to 0)."
    },
    {
        "id": "chem_mr_276",
        "topic": "Chemical Equilibrium & Le Chatelier's Principle",
        "year": "1998",
        "question": "For the gaseous reaction: 2NO(g) + O₂(g) ⇌ 2NO₂(g); ΔH = -114 kJ mol⁻¹, which combination of conditions will maximize the equilibrium yield of NO₂?",
        "a": "Low temperature and high pressure",
        "b": "High temperature and low pressure",
        "c": "High temperature and high pressure",
        "d": "Low temperature and low pressure",
        "ans": 0,
        "explanation": "The reaction is exothermic (ΔH < 0), so low temperature shifts equilibrium forward. There are 3 moles of gas on the left and 2 moles on the right (decrease in volume), so high pressure shifts equilibrium forward."
    },
    {
        "id": "chem_mr_277",
        "topic": "Chemical Equilibrium & Pressure Independence",
        "year": "1998",
        "question": "Which of the following gaseous equilibrium reactions will have its position of equilibrium UNAFFECTED by a change in total pressure?",
        "a": "2SO₂(g) + O₂(g) ⇌ 2SO₃(g)",
        "b": "H₂(g) + I₂(g) ⇌ 2HI(g)",
        "c": "N₂O₄(g) ⇌ 2NO₂(g)",
        "d": "PCl₅(g) ⇌ PCl₃(g) + Cl₂(g)",
        "ans": 1,
        "explanation": "In H₂(g) + I₂(g) ⇌ 2HI(g), there are 2 moles of gas on the reactant side and 2 moles on the product side (Δn_gas = 0). A change in volume/pressure affects both sides equally without shifting equilibrium."
    },
    {
        "id": "chem_mr_278",
        "topic": "Qualitative Analysis & Gas Tests",
        "year": "1998",
        "question": "Which of the following colourless gases will rekindle a glowing wooden splint?",
        "a": "Nitrogen(IV) oxide (NO₂)",
        "b": "Nitrogen(II) oxide (NO)",
        "c": "Dinitrogen monoxide (N₂O, laughing gas)",
        "d": "Chlorine (Cl₂)",
        "ans": 2,
        "explanation": "Dinitrogen monoxide (N₂O) easily decomposes when exposed to heat: 2N₂O → 2N₂ + O₂. The liberated oxygen supports combustion, rekindling a glowing wooden splint (like pure O₂)."
    },
    {
        "id": "chem_mr_279",
        "topic": "Thermal Stability of Metal Salts",
        "year": "1998",
        "question": "Which of the following trioxocarbonate(IV) salts can be melted without undergoing thermal decomposition?",
        "a": "Sodium trioxocarbonate(IV) (Na₂CO₃)",
        "b": "Calcium trioxocarbonate(IV) (CaCO₃)",
        "c": "Magnesium trioxocarbonate(IV) (MgCO₃)",
        "d": "Zinc trioxocarbonate(IV) (ZnCO₃)",
        "ans": 0,
        "explanation": "Group 1 alkali metal carbonates (except Li₂CO₃) have very high thermal stability due to the low charge density of large M⁺ cations and melt without decomposing into oxides at normal Bunsen temperatures."
    },
    {
        "id": "chem_mr_280",
        "topic": "Laboratory Preparation of Oxygen",
        "year": "1998",
        "question": "Oxygen gas can be prepared in the laboratory by the thermal decomposition of:",
        "a": "Potassium trioxochlorate(V) (KClO₃) catalyzed by MnO₂",
        "b": "Ammonium trioxonitrate(V)",
        "c": "Sodium chloride",
        "d": "Calcium hydroxide",
        "ans": 0,
        "explanation": "Heating KClO₃ in the presence of manganese(IV) oxide catalyst produces potassium chloride and oxygen gas: 2KClO₃(s) → 2KCl(s) + 3O₂↑."
    },
    {
        "id": "chem_mr_281",
        "topic": "Qualitative Analysis & Complex Formation",
        "year": "1998",
        "question": "Addition of aqueous ammonia to a solution of Zn²⁺ yields a white precipitate which dissolves in excess ammonia because:",
        "a": "Zinc hydroxide is amphoteric",
        "b": "Zinc forms a soluble tetraamminezinc(II) coordination complex [Zn(NH₃)₄]²⁺",
        "c": "Ammonia solution is a weak base",
        "d": "Zinc is reduced to metallic zinc",
        "ans": 1,
        "explanation": "Zn²⁺ first precipitates as white Zn(OH)₂. With excess aqueous ammonia, it forms the soluble complex tetraamminezinc(II) ion: Zn(OH)₂ + 4NH₃ → [Zn(NH₃)₄]²⁺ + 2OH⁻."
    },
    {
        "id": "chem_mr_282",
        "topic": "Applied Chemistry (Uses of Copper Sulfate)",
        "year": "1998",
        "question": "Copper(II) tetraoxosulphate(VI) (CuSO₄·5H₂O) mixed with lime (Bordeaux mixture) is widely utilized in agriculture as a:",
        "a": "Nitrogenous fertilizer",
        "b": "Fungicide to control fungal plant diseases",
        "c": "Herbicide",
        "d": "Drying agent for grains",
        "ans": 1,
        "explanation": "Bordeaux mixture (a suspension of CuSO₄ and Ca(OH)₂) is a classic agricultural fungicide used to prevent downy mildew on grapevines, potato blight, and black pod disease on cocoa."
    },
    {
        "id": "chem_mr_283",
        "topic": "Thermal Decomposition of Precious Metal Nitrates",
        "year": "1998",
        "question": "Which of the following metal nitrates decomposes on heating to yield the free metal directly, along with NO₂ and O₂?",
        "a": "Copper(II) nitrate",
        "b": "Zinc nitrate",
        "c": "Silver nitrate (AgNO₃) and Mercury(II) nitrate",
        "d": "Lead(II) nitrate",
        "ans": 2,
        "explanation": "The oxides of unreactive metals below copper in the activity series (Ag, Au, Hg) are thermally unstable. Hence their nitrates decompose to the elemental metal: 2AgNO₃(s) → 2Ag(s) + 2NO₂(g) + O₂(g)."
    },
    {
        "id": "chem_mr_284",
        "topic": "Organic Chemistry (Geometric Isomerism)",
        "year": "1998",
        "question": "Which of the following alkene compounds can exist as cis-trans (geometric) stereoisomers?",
        "a": "2-methylbut-2-ene",
        "b": "But-2-ene (CH₃-CH=CH-CH₃)",
        "c": "But-1-ene (CH₂=CH-CH₂-CH₃)",
        "d": "Propene (CH₂=CH-CH₃)",
        "ans": 1,
        "explanation": "Geometric isomerism requires restricted rotation about a C=C bond where each double-bonded carbon carries two different substituent groups. In but-2-ene, each carbon carries -H and -CH₃, yielding cis-but-2-ene and trans-but-2-ene."
    },
    {
        "id": "chem_mr_285",
        "topic": "Organic Chemistry (Free-Radical Halogenation)",
        "year": "1998",
        "question": "The ultimate final product formed when excess chlorine reacts with methane in the presence of strong ultraviolet light is:",
        "a": "Chloromethane (CH₃Cl)",
        "b": "Tetrachloromethane (carbon tetrachloride, CCl₄) and HCl",
        "c": "Trichloromethane (CHCl₃)",
        "d": "Hexachloroethane",
        "ans": 1,
        "explanation": "Under continuous UV irradiation with excess Cl₂, methane undergoes successive substitution through CH₃Cl, CH₂Cl₂, and CHCl₃ to reach fully chlorinated tetrachloromethane: CH₄ + 4Cl₂ → CCl₄ + 4HCl."
    },
    {
        "id": "chem_mr_286",
        "topic": "Stoichiometry (Alkyne Bromination)",
        "year": "1998",
        "question": "How many grams of bromine (Br₂) will be required to completely saturate 10.0 g of propyne (CH₃-C≡CH)? [C=12, H=1, Br=80]",
        "a": "20.0 g", "b": "40.0 g", "c": "60.0 g", "d": "80.0 g",
        "ans": 3,
        "explanation": "CH₃-C≡CH + 2Br₂ → CH₃-CBr₂-CHBr₂. Molar mass of propyne (C₃H₄) = 3(12) + 4 = 40 g/mol. Moles propyne = 10.0 / 40 = 0.25 mol. Moles Br₂ required = 2 × 0.25 = 0.50 mol. Mass of Br₂ = 0.50 × 160 g/mol = 80.0 g."
    },
    {
        "id": "chem_mr_287",
        "topic": "Organic Chemistry (Addition to Alkenes)",
        "year": "1998",
        "question": "When ethene gas is absorbed in concentrated H₂SO₄ and the intermediate ethyl hydrogen sulphate is subsequently diluted with water and warmed, the product is:",
        "a": "Ethanol (C₂H₅OH)",
        "b": "Diethyl ether",
        "c": "Ethanal",
        "d": "Ethanoic acid",
        "ans": 0,
        "explanation": "CH₂=CH₂ + H₂SO₄ → C₂H₅OSO₃H (ethyl hydrogen sulphate). Hydrolysis with warm water regenerates sulfuric acid and yields ethanol: C₂H₅OSO₃H + H₂O → C₂H₅OH + H₂SO₄."
    },
    {
        "id": "chem_mr_288",
        "topic": "Organic Reaction Mechanisms (Dehydrohalogenation)",
        "year": "1998",
        "question": "The conversion: CH₃-CH₂-CH(Br)-CH₃ + alcoholic KOH → CH₃-CH=CH-CH₃ + KBr + H₂O is classified as a:",
        "a": "Dehydration reaction",
        "b": "Dehydrohalogenation (elimination) reaction",
        "c": "Nucleophilic substitution reaction",
        "d": "Hydrolysis reaction",
        "ans": 1,
        "explanation": "Alcoholic KOH acts as a strong base that removes a hydrogen atom and a halogen atom from adjacent carbon atoms in a haloalkane to create a C=C double bond (1,2-elimination / dehydrohalogenation)."
    },
    {
        "id": "chem_mr_289",
        "topic": "Physical Properties of Polyols",
        "year": "1998",
        "question": "A colourless organic liquid has a very high boiling point (290°C), is viscous, non-toxic, sweet-tasting, miscible with water, and hygroscopic. This liquid is:",
        "a": "Ethanol",
        "b": "Ethoxyethane",
        "c": "Glycerol (propane-1,2,3-triol)",
        "d": "Trichloromethane",
        "ans": 2,
        "explanation": "Glycerol (CH₂OH-CHOH-CH₂OH) possesses three polar -OH groups per molecule, forming extensive networks of intermolecular hydrogen bonds that cause high viscosity, hygroscopicity, and a high boiling point."
    },
    {
        "id": "chem_mr_290",
        "topic": "Organic Chemistry (IUPAC Nomenclature)",
        "year": "1998",
        "question": "The IUPAC systematic name for the branched compound CH₃-CH(CH₃)-CH₂-Cl is:",
        "a": "1-chloro-2-methylpropane",
        "b": "2-chloromethylpropane",
        "c": "1-chlorobutane",
        "d": "2-chloro-2-methylpropane",
        "ans": 0,
        "explanation": "Longest carbon chain with chlorine has 3 carbons (propane). Numbering from the end with the chloro group gives 1-chloro and a methyl group at carbon-2: 1-chloro-2-methylpropane (isobutyl chloride)."
    },
    {
        "id": "chem_mr_291",
        "topic": "Organic Chemistry (Saponification Stoichiometry)",
        "year": "1998",
        "question": "Which of the following statements is TRUE regarding the complete saponification of one mole of a triglyceride (fat) by sodium hydroxide?",
        "a": "3 moles of NaOH are required, producing 1 mole of glycerol and 3 moles of soap",
        "b": "1 mole of NaOH produces 3 moles of glycerol",
        "c": "No glycerol is formed",
        "d": "Concentrated H₂SO₄ is required",
        "ans": 0,
        "explanation": "Triglycerides are tri-esters of glycerol. Hydrolyzing the 3 ester linkages requires 3 moles of NaOH, yielding 1 mole of glycerol and 3 moles of sodium carboxylate salts (soap)."
    },
    {
        "id": "chem_mr_292",
        "topic": "Organic Chemistry (Carboxylic Acid Halogenation)",
        "year": "1998",
        "question": "When ethanoic acid (CH₃COOH) reacts with chlorine in the presence of sunlight (Hell-Volhard-Zelinsky conditions), the organic product is:",
        "a": "Chloroethanoic acid (ClCH₂COOH)",
        "b": "Ethanoyl chloride (CH₃COCl)",
        "c": "Chloromethane (CH₃Cl)",
        "d": "Trichloromethane (CHCl₃)",
        "ans": 0,
        "explanation": "Chlorination of ethanoic acid in sunlight substitutes hydrogen on the alpha-carbon to produce chloroethanoic acid (monochloroacetic acid): CH₃COOH + Cl₂ → ClCH₂COOH + HCl."
    },
    {
        "id": "chem_mr_293",
        "topic": "Classification of Mixtures",
        "year": "1998",
        "question": "Which of the following liquid samples is NOT a homogeneous mixture?",
        "a": "Filtered sea water", "b": "Soft drink (soda)", "c": "Turbid flood water containing suspended silt", "d": "Writing ink solution",
        "ans": 2,
        "explanation": "Flood water is a heterogeneous suspension containing coarse mud, soil, and organic debris that settle out upon standing and scatter light non-uniformly."
    },
    {
        "id": "chem_mr_294",
        "topic": "Metallic Bonding & Phase Transitions",
        "year": "1998",
        "question": "There is a very large temperature interval between the melting point and boiling point of metals because:",
        "a": "Melting only loosens lattice vibrations without breaking the metallic bond, whereas boiling requires complete severance of strong delocalized metallic bonding",
        "b": "Metals conduct heat rapidly",
        "c": "Metals are ductile",
        "d": "The metal expands on melting",
        "ans": 0,
        "explanation": "In liquid metals, positive metal ions remain immersed in a mobile sea of delocalized valence electrons. Vaporization (boiling) requires overcoming the entire cohesive energy of the metallic bond to separate atoms into individual gaseous particles."
    },
    {
        "id": "chem_mr_295",
        "topic": "Stoichiometry & Ion Concentration",
        "year": "1998",
        "question": "How many moles of hydrogen ions [H⁺] are present in 1.0 dm³ of a 0.50 M solution of diprotic tetraoxosulphate(VI) acid (H₂SO₄)?",
        "a": "0.25 mol", "b": "0.50 mol", "c": "1.00 mol", "d": "2.00 mol",
        "ans": 2,
        "explanation": "H₂SO₄(aq) → 2H⁺(aq) + SO₄²⁻(aq). Each mole of H₂SO₄ releases 2 moles of H⁺ ions. In 1.0 dm³ of 0.50 M solution, Moles of H⁺ = 2 × 0.50 = 1.00 mol."
    },
    {
        "id": "chem_mr_296",
        "topic": "Balancing Chemical Equations",
        "year": "1998",
        "question": "What are the stoichiometric coefficients w, x, y, and z respectively in the balanced equation: wH₂SO₄ + xAl(OH)₃ → yH₂O + zAl₂(SO₄)₃?",
        "a": "2, 2, 5, 1", "b": "3, 2, 5, 2", "c": "3, 2, 6, 1", "d": "2, 2, 6, 2",
        "ans": 2,
        "explanation": "To balance the sulfate and aluminium ions: 3H₂SO₄ + 2Al(OH)₃ → 6H₂O + 1Al₂(SO₄)₃. Thus w = 3, x = 2, y = 6, z = 1."
    },
    {
        "id": "chem_mr_297",
        "topic": "Gas Laws (Charles's Law)",
        "year": "1998",
        "question": "A given mass of gas occupies 2.0 dm³ at 300 K. At what temperature will its volume be doubled (4.0 dm³) keeping pressure constant?",
        "a": "400 K", "b": "480 K", "c": "550 K", "d": "600 K",
        "ans": 3,
        "explanation": "By Charles's law, V₁ / T₁ = V₂ / T₂ => 2.0 / 300 = 4.0 / T₂ => T₂ = 300 × (4.0 / 2.0) = 600 K."
    },
    {
        "id": "chem_mr_298",
        "topic": "Graham's Law Calculations",
        "year": "1998",
        "question": "If 100 cm³ of oxygen (O₂) diffuses through a porous plug in 50 seconds, how long will the same volume (100 cm³) of hydrogen (H₂) take to diffuse through the same plug under identical conditions? [O=16, H=1]",
        "a": "10.0 s", "b": "12.5 s", "c": "17.7 s", "d": "25.0 s",
        "ans": 1,
        "explanation": "Time ∝ √(Molar Mass) for equal volumes. t_H₂ / t_O₂ = √(M_H₂ / M_O₂) = √(2 / 32) = √(1/16) = 1/4. t_H₂ = 50 × (1/4) = 12.5 seconds."
    },
    {
        "id": "chem_mr_299",
        "topic": "Kinetic Molecular Theory",
        "year": "1998",
        "question": "The absolute temperature (in Kelvin) of a chemical substance is a direct measure of the:",
        "a": "Total mass of the substance",
        "b": "Average kinetic energy of the constituent particles",
        "c": "Total volume of the system",
        "d": "Potential energy between bonded atoms",
        "ans": 1,
        "explanation": "According to kinetic theory, temperature is directly proportional to the average translational kinetic energy of the molecules (KE_avg = ³/₂ kT)."
    },
    {
        "id": "chem_mr_300",
        "topic": "Nuclear Chemistry & Isotopes",
        "year": "1998",
        "question": "The nucleus of the heavy hydrogen isotope tritium (³₁H) contains:",
        "a": "One proton and no neutrons",
        "b": "One proton and one neutron",
        "c": "One proton and two neutrons",
        "d": "Two protons and one neutron",
        "ans": 2,
        "explanation": "Tritium (³₁H) has atomic number Z = 1 (1 proton) and mass number A = 3, meaning it contains A - Z = 3 - 1 = 2 neutrons in its nucleus."
    }
]

print("Part 6 dataset ready")
