# Part 5: Questions 201 - 250 (1994 - 1997 Series)
part5_questions = [
    {
        "id": "chem_mr_201",
        "topic": "Water Purification & Lime Treatment",
        "year": "1994",
        "question": "Calcium hydroxide [slaked lime, Ca(OH)₂] is added during municipal water treatment in order to:",
        "a": "Kill bacteria and viruses directly",
        "b": "Facilitate coagulation of organic flocs and adjust pH for precipitation",
        "c": "Impart a sweet taste to the water",
        "d": "Increase permanent hardness",
        "ans": 1,
        "explanation": "Lime raises pH and supplies Ca²⁺ ions that assist coagulation and precipitate temporary bicarbonate hardness as insoluble CaCO₃, aiding sedimentation."
    },
    {
        "id": "chem_mr_202",
        "topic": "Stoichiometry & Hydrates",
        "year": "1994",
        "question": "A hydrated sulfate of formula MSO₄·xH₂O contains 45.3% by mass of water of crystallization. If the relative atomic mass of M is 24 (Magnesium), calculate the value of x. [Mg=24, S=32, O=16, H=1]",
        "a": "3", "b": "5", "c": "7", "d": "10",
        "ans": 2,
        "explanation": "Molar mass of anhydrous MgSO₄ = 24 + 32 + 64 = 120 g/mol. Formula mass = 120 + 18x. % H₂O = [18x / (120 + 18x)] × 100% = 45.3% => 18x = 0.453(120 + 18x) = 54.36 + 8.154x => 9.846x = 54.36 => x ≈ 7 (Epsom salt, MgSO₄·7H₂O)."
    },
    {
        "id": "chem_mr_203",
        "topic": "Stoichiometry & Limiting Reagents",
        "year": "1994",
        "question": "Using 50 cm³ of 1.0 M KOH and 100 cm³ of 1.0 M H₂SO₄, what are the respective volumes in cm³ of base and acid required to react completely to produce the maximum amount of normal potassium sulphate (K₂SO₄)?",
        "a": "50 cm³ KOH and 50 cm³ H₂SO₄",
        "b": "25 cm³ KOH and 50 cm³ H₂SO₄",
        "c": "50 cm³ KOH and 25 cm³ H₂SO₄",
        "d": "25 cm³ KOH and 25 cm³ H₂SO₄",
        "ans": 2,
        "explanation": "2KOH + H₂SO₄ → K₂SO₄ + 2H₂O. 2 moles of KOH react with 1 mole of H₂SO₄. For 50 cm³ of 1.0 M KOH (0.050 mol), the required volume of 1.0 M H₂SO₄ is 0.050 / 2 = 0.025 mol = 25 cm³."
    },
    {
        "id": "chem_mr_204",
        "topic": "Solutions & Ionic Concentration",
        "year": "1994",
        "question": "A solution of calcium bromide (CaBr₂) contains 20.0 g dm⁻³. What is the molarity of the solution with respect to calcium bromide and bromide ions (Br⁻) respectively? [Ca=40, Br=80]",
        "a": "0.10 M and 0.10 M",
        "b": "0.10 M and 0.20 M",
        "c": "0.20 M and 0.40 M",
        "d": "0.05 M and 0.10 M",
        "ans": 1,
        "explanation": "Molar mass of CaBr₂ = 40 + 2(80) = 200 g/mol. Molarity of CaBr₂ = 20.0 / 200 = 0.10 M. Since CaBr₂ → Ca²⁺ + 2Br⁻, the concentration of Br⁻ ions is 2 × 0.10 M = 0.20 M."
    },
    {
        "id": "chem_mr_205",
        "topic": "Oxides & Amphoterism",
        "year": "1994",
        "question": "Zinc oxide (ZnO) dissolves in both aqueous sodium hydroxide and dilute mineral acids to give soluble products. ZnO is therefore classified as:",
        "a": "A neutral oxide", "b": "A basic oxide", "c": "An amphoteric oxide", "d": "A peroxide",
        "ans": 2,
        "explanation": "Oxides that exhibit dual chemical behavior—reacting as bases with acids and as acids with strong alkalis to form salts—are defined as amphoteric oxides."
    },
    {
        "id": "chem_mr_206",
        "topic": "Acids & Conjugate Pairs",
        "year": "1994",
        "question": "According to the Brønsted-Lowry theory, an acid and its conjugate base:",
        "a": "Differ only by a single proton (H⁺)",
        "b": "Have identical physical and chemical properties",
        "c": "Differ by an electron pair only",
        "d": "Always possess equal electrostatic charges",
        "ans": 0,
        "explanation": "A conjugate acid-base pair consists of two species that transform into one another by the gain or loss of a single hydrogen ion (proton, H⁺), such as NH₄⁺ and NH₃, or H₂O and OH⁻."
    },
    {
        "id": "chem_mr_207",
        "topic": "Faraday's Second Law of Electrolysis",
        "year": "1994",
        "question": "The same quantity of electricity is passed in series through solutions of AgNO₃ and CuSO₄. How much silver will be deposited if 1.00 g of copper is produced? [Cu=63.5, Ag=108]",
        "a": "1.70 g", "b": "3.40 g", "c": "6.80 g", "d": "13.60 g",
        "ans": 1,
        "explanation": "By Faraday's 2nd Law: (Mass_Ag / Equivalent_mass_Ag) = (Mass_Cu / Equivalent_mass_Cu). Mass_Ag / (108 / 1) = 1.00 / (63.5 / 2) => Mass_Ag / 108 = 1.00 / 31.75 => Mass_Ag = 108 / 31.75 ≈ 3.40 g."
    },
    {
        "id": "chem_mr_208",
        "topic": "Electrolysis of Copper Sulfate",
        "year": "1994",
        "question": "What is discharged at the cathode during the electrolysis of aqueous copper(II) tetraoxosulphate(VI) using carbon electrodes?",
        "a": "Cu²⁺ ions only (depositing copper metal)",
        "b": "H⁺ ions only",
        "c": "SO₄²⁻ ions",
        "d": "Oxygen gas",
        "ans": 0,
        "explanation": "In aqueous CuSO₄, Cu²⁺ and H⁺ migrate to the cathode. Because Cu²⁺ has a much higher standard reduction potential (+0.34 V) than H⁺ (0.00 V), Cu²⁺ is discharged preferentially to form reddish copper metal."
    },
    {
        "id": "chem_mr_209",
        "topic": "Complex Ions & Oxidation Numbers",
        "year": "1994",
        "question": "An element Z forms a complex anion whose formula is [Z(CN)₆]ʸ⁻. If Z has an oxidation number of +2 and cyanide is CN⁻, what is the value of the overall ionic charge y?",
        "a": "2", "b": "3", "c": "4", "d": "5",
        "ans": 2,
        "explanation": "Overall charge = Oxidation number of central metal + (number of ligands × ligand charge) = (+2) + 6(-1) = -4. Hence y = 4 (as in hexacyanoferrate(II) [Fe(CN)₆]⁴⁻)."
    },
    {
        "id": "chem_mr_210",
        "topic": "Thermochemistry & Enthalpy of Formation",
        "year": "1994",
        "question": "The standard enthalpy of combustion of ethene (C₂H₄) is -1411 kJ mol⁻¹. If the standard enthalpies of formation of CO₂(g) and H₂O(l) are -394 kJ mol⁻¹ and -286 kJ mol⁻¹ respectively, what is the standard enthalpy of formation of ethene?",
        "a": "+52 kJ mol⁻¹", "b": "-52 kJ mol⁻¹", "c": "+1411 kJ mol⁻¹", "d": "-2091 kJ mol⁻¹",
        "ans": 0,
        "explanation": "C₂H₄(g) + 3O₂(g) → 2CO₂(g) + 2H₂O(l); ΔH°_comb = 2(-394) + 2(-286) - ΔH°_f(C₂H₄) = -1411 => -788 - 572 - ΔH°_f = -1411 => -1360 - ΔH°_f = -1411 => ΔH°_f(C₂H₄) = +51 kJ mol⁻¹."
    },
    {
        "id": "chem_mr_211",
        "topic": "Chemical Equilibrium & Thermodynamic Factors",
        "year": "1994",
        "question": "For the exothermic water-gas shift reaction: CO(g) + H₂O(g) ⇌ CO₂(g) + H₂(g); ΔH = -41.0 kJ mol⁻¹, which factor will favour the formation of hydrogen at equilibrium?",
        "a": "High pressure",
        "b": "High temperature",
        "c": "Lowering the temperature and using excess steam",
        "d": "Increasing the volume of the container",
        "ans": 2,
        "explanation": "Because ΔH < 0 (exothermic), lower temperatures shift equilibrium toward the products. Adding excess steam (reactant H₂O) further drives equilibrium to the right by Le Chatelier's principle."
    },
    {
        "id": "chem_mr_212",
        "topic": "Industrial Chemistry (Contact Process)",
        "year": "1994",
        "question": "The catalyst used in the Contact process for the commercial manufacture of tetraoxosulphate(VI) acid is:",
        "a": "Finely divided iron (Fe)",
        "b": "Manganese(IV) oxide (MnO₂)",
        "c": "Vanadium(V) oxide (V₂O₅)",
        "d": "Copper turnings",
        "ans": 2,
        "explanation": "In the Contact process, vanadium(V) oxide (V₂O₅ pellets) at 450°C catalyzes the reversible oxidation of sulfur(IV) oxide to sulfur(VI) oxide: 2SO₂ + O₂ ⇌ 2SO₃."
    },
    {
        "id": "chem_mr_213",
        "topic": "Fossil Fuels & Industrial By-Products",
        "year": "1994",
        "question": "Which of the following sets of substances represents direct products obtained from the destructive distillation of coal?",
        "a": "Carbon(IV) oxide and ethanoic acid",
        "b": "Coke, coal tar, coal gas, and ammoniacal liquor",
        "c": "Producer gas and water gas",
        "d": "Ethanol and methane",
        "ans": 1,
        "explanation": "Destructive distillation of coal involves heating coal in the absence of air, yielding solid coke, viscous coal tar, volatile coal gas, and aqueous ammoniacal liquor."
    },
    {
        "id": "chem_mr_214",
        "topic": "Applied Chemistry & Explosives",
        "year": "1994",
        "question": "Gunpowder is a mixture of powdered charcoal, sulfur, and potassium trioxonitrate(V) (KNO₃). The role of KNO₃ in this mixture is:",
        "a": "A fuel", "b": "A solid oxidizing agent (oxidant)", "c": "A binding solvent", "d": "A catalyst",
        "ans": 1,
        "explanation": "Potassium nitrate (saltpetre, KNO₃) decomposes upon ignition to supply oxygen rapidly, acting as the oxidant that vigorously burns the carbon and sulfur fuels."
    },
    {
        "id": "chem_mr_215",
        "topic": "Applied Chemistry (Deterioration of Bleaching Powder)",
        "year": "1994",
        "question": "Bleaching powder (CaOCl₂·H₂O) deteriorates and loses its available chlorine on prolonged exposure to atmospheric air because:",
        "a": "It absorbs nitrogen gas",
        "b": "Atmospheric carbon(IV) oxide and moisture react with it to liberate chlorine gas",
        "c": "It undergoes sublimation",
        "d": "It dissolves in its own water of crystallization",
        "ans": 1,
        "explanation": "CaOCl₂ reacts slowly with atmospheric CO₂ and water vapour: CaOCl₂ + CO₂ → CaCO₃ + Cl₂↑, displacing the active chlorine and converting the powder into chalk."
    },
    {
        "id": "chem_mr_216",
        "topic": "Thermal Decomposition of Ammonium Salts",
        "year": "1994",
        "question": "The gaseous products formed upon cautiously heating dry crystals of ammonium trioxonitrate(V) (NH₄NO₃) are:",
        "a": "Dinitrogen monoxide (N₂O, laughing gas) and steam (H₂O)",
        "b": "Nitrogen and oxygen",
        "c": "Ammonia and nitric acid",
        "d": "Nitrogen(IV) oxide and hydrogen",
        "ans": 0,
        "explanation": "Cautious heating of NH₄NO₃ yields dinitrogen monoxide (nitrous oxide) and steam: NH₄NO₃(s) → N₂O(g) + 2H₂O(g)."
    },
    {
        "id": "chem_mr_217",
        "topic": "Electrochemistry & Sacrificial Protection",
        "year": "1994",
        "question": "Iron galvanized with zinc is cathodically protected from atmospheric corrosion even when the zinc coating is scratched because:",
        "a": "Zinc has a more positive standard reduction potential than iron",
        "b": "Zinc has a higher oxidation potential (more electropositive) and corrodes preferentially as a sacrificial anode",
        "c": "Zinc forms a volatile oxide",
        "d": "Zinc is harder than iron",
        "ans": 1,
        "explanation": "Zinc (E°_ox = +0.76 V) is more electropositive than iron (E°_ox = +0.44 V). When exposed to moisture, zinc sacrifices itself by oxidizing preferentially (Zn → Zn²⁺ + 2e⁻), supplying electrons to protect the iron."
    },
    {
        "id": "chem_mr_218",
        "topic": "Civil Engineering & Building Materials",
        "year": "1994",
        "question": "Ordinary lime mortar (sand, water, and slaked lime) cannot be used for underwater construction because:",
        "a": "It dissolves instantly in water",
        "b": "It hardens by absorbing atmospheric CO₂ gas, which is unavailable underwater",
        "c": "It expands explosively under pressure",
        "d": "It requires freezing temperatures to set",
        "ans": 1,
        "explanation": "Non-hydraulic lime mortar hardens by carbonation: Ca(OH)₂ + CO₂ → CaCO₃ + H₂O. Without atmospheric CO₂, it cannot set underwater (unlike hydraulic Portland cement)."
    },
    {
        "id": "chem_mr_219",
        "topic": "Organic Synthesis & Halogenation",
        "year": "1994",
        "question": "When ethene gas is bubbled into a solution of chlorine in tetrachloromethane at room temperature, the addition product formed is:",
        "a": "1,2-dichloroethane",
        "b": "1,1-dichloroethane",
        "c": "Chloroethene (vinyl chloride)",
        "d": "1,1,2-trichloroethane",
        "ans": 0,
        "explanation": "Chlorine adds electrophilically across the C=C double bond in ethene: CH₂=CH₂ + Cl₂ → CH₂Cl-CH₂Cl (1,2-dichloroethane)."
    },
    {
        "id": "chem_mr_220",
        "topic": "Organic Chemistry (Carboxylic Acid Dimerization)",
        "year": "1994",
        "question": "In pure liquid state and in non-polar solvents, ethanoic acid molecules exist predominantly as dimers held together by:",
        "a": "Ionic attractions",
        "b": "Intermolecular hydrogen bonds between carbonyl oxygen and hydroxyl hydrogen",
        "c": "Covalent bonds",
        "d": "Coordinate bonds",
        "ans": 1,
        "explanation": "Carboxylic acids form stable cyclic dimers via two intermolecular hydrogen bonds between the carbonyl oxygen (>C=O) of one molecule and the hydroxyl hydrogen (-O-H) of another."
    },
    {
        "id": "chem_mr_221",
        "topic": "Environmental Chemistry (Mine Safety)",
        "year": "1994",
        "question": "The flammable hydrocarbon gas responsible for disastrous explosive firedamp accidents in underground coal mines is:",
        "a": "Butane", "b": "Ethene", "c": "Methane (CH₄)", "d": "Ethyne",
        "ans": 2,
        "explanation": "Methane (firedamp) is trapped within coal seams. When released into underground mine shafts, it forms explosive mixtures with air when its concentration reaches 5-15%."
    },
    {
        "id": "chem_mr_222",
        "topic": "Organic Chemistry (Aromatics vs Aliphatics)",
        "year": "1994",
        "question": "Three liquid hydrocarbons X, Y, and Z were tested: X and Y burned with luminous, very sooty flames while Z burned with a clean flame. Y quickly decolorized bromine water while X and Z did not. Which liquid is aromatic in nature?",
        "a": "X (e.g. Benzene)", "b": "Y (e.g. Hexene)", "c": "Z (e.g. Hexane)", "d": "Both Y and Z",
        "ans": 0,
        "explanation": "Aromatic hydrocarbons (like benzene, X) have a very high carbon-to-hydrogen ratio, causing them to burn with intensely sooty flames, yet they resist addition reactions with bromine water due to resonance stabilization."
    },
    {
        "id": "chem_mr_223",
        "topic": "Physical vs Chemical Changes",
        "year": "1995",
        "question": "Which of the following represents a purely physical change?",
        "a": "Bubbling chlorine into aqueous potassium iodide",
        "b": "Passing steam over red-hot iron filings",
        "c": "Dissolving common salt (NaCl) in pure water",
        "d": "Rusting of iron in moist air",
        "ans": 2,
        "explanation": "Dissolving NaCl in water is a physical change because no new chemical substance is formed and the original salt can be recovered completely unchanged by simple physical evaporation."
    },
    {
        "id": "chem_mr_224",
        "topic": "Stoichiometry & Percentage Purity",
        "year": "1995",
        "question": "In the reduction of tin(IV) oxide: SnO₂ + 2C → Sn + 2CO, what mass of coke containing 80% carbon is required to reduce 30.2 g of pure SnO₂? [Sn=119, O=16, C=12]",
        "a": "4.80 g", "b": "6.00 g", "c": "2.40 g", "d": "0.48 g",
        "ans": 1,
        "explanation": "Molar mass of SnO₂ = 119 + 32 = 151 g/mol. Moles SnO₂ = 30.2 / 151 = 0.20 mol. Moles C required = 2 × 0.20 = 0.40 mol. Mass of pure carbon = 0.40 × 12 = 4.80 g. Since coke is 80% carbon, Mass of coke = 4.80 / 0.80 = 6.00 g."
    },
    {
        "id": "chem_mr_225",
        "topic": "Gas Laws (General Gas Equation)",
        "year": "1995",
        "question": "If a gas occupies a volume of 146 cm³ at 18°C (291 K) and 0.971 atm, what will be its volume at S.T.P (273 K and 1.00 atm)?",
        "a": "133 cm³", "b": "146 cm³", "c": "160 cm³", "d": "266 cm³",
        "ans": 0,
        "explanation": "V₂ = (P₁ · V₁ · T₂) / (P₂ · T₁) = (0.971 × 146 × 273) / (1.00 × 291) = 38702 / 291 ≈ 133 cm³."
    },
    {
        "id": "chem_mr_226",
        "topic": "Vapour Density & Molar Mass",
        "year": "1995",
        "question": "A sample of gas weighing 1.58 g occupies 500 cm³ at S.T.P. What is the relative molecular mass of the gas? [Molar volume at STP = 22,400 cm³]",
        "a": "28", "b": "32", "c": "44", "d": "71",
        "ans": 3,
        "explanation": "Moles = 500 / 22400 = 0.02232 mol. Molar mass = Mass / Moles = 1.58 / 0.02232 ≈ 70.8 ≈ 71 g mol⁻¹ (chlorine gas, Cl₂)."
    },
    {
        "id": "chem_mr_227",
        "topic": "Graham's Law (Rate of Diffusion Ordering)",
        "year": "1995",
        "question": "Equal volumes of CO (M=28), SO₂ (M=64), NO (M=30), and H₂S (M=34) were released simultaneously in a room. In what order will their smells reach the opposite end of the room (fastest to slowest)?",
        "a": "CO > NO > H₂S > SO₂",
        "b": "SO₂ > H₂S > NO > CO",
        "c": "H₂S > SO₂ > CO > NO",
        "d": "NO > CO > SO₂ > H₂S",
        "ans": 0,
        "explanation": "According to Graham's law, diffusion rate is inversely proportional to the square root of molecular mass (Rate ∝ 1/√M). Lowest molecular mass diffuses fastest: CO (28) > NO (30) > H₂S (34) > SO₂ (64)."
    },
    {
        "id": "chem_mr_228",
        "topic": "Kinetic Theory of Gases (Elastic Collisions)",
        "year": "1995",
        "question": "A basic postulate of the kinetic molecular theory of gases is that collisions between gas molecules are perfectly elastic. This implies that:",
        "a": "The molecules stick together after colliding",
        "b": "There is no net loss of total kinetic energy during collisions",
        "c": "Intermolecular forces of attraction are very large",
        "d": "Gas molecules stop moving upon collision",
        "ans": 1,
        "explanation": "In a perfectly elastic collision, kinetic energy may be transferred between colliding particles, but the total kinetic energy of the entire gaseous system remains completely conserved."
    },
    {
        "id": "chem_mr_229",
        "topic": "Atomic Structure & Periodic Classification",
        "year": "1995",
        "question": "Atom S has 19 protons, 19 electrons, and 20 neutrons. Atom S is described as:",
        "a": "A noble gas with atomic mass 19",
        "b": "A transition element with mass number 38",
        "c": "An alkali metal with mass number 39 that forms a unipositive ion (S⁺) in solution",
        "d": "A halogen that forms a uninegative ion",
        "ans": 2,
        "explanation": "Atom S has Z = 19 (Potassium, K) with electron configuration 2, 8, 8, 1 and mass number A = 19 + 20 = 39. It readily loses its single 4s valence electron to form a unipositive cation (K⁺)."
    },
    {
        "id": "chem_mr_230",
        "topic": "Chemical Bonding & Valency",
        "year": "1995",
        "question": "Which of the following terms defines the combining power of an element, representing the number of chemical bonds its atom can form?",
        "a": "Oxidation number", "b": "Valency", "c": "Electronegativity", "d": "Atomic radius",
        "ans": 1,
        "explanation": "Valency is the combining capacity of an atom or radical, measured by the number of hydrogen atoms (or chlorine atoms) with which one atom of the element can combine or displace."
    },
    {
        "id": "chem_mr_231",
        "topic": "Stoichiometry & Isotopic Abundance",
        "year": "1995",
        "question": "Naturally occurring chlorine consists of two isotopes, ³⁵Cl and ³⁷Cl, with an average atomic mass of 35.5. What is the relative percentage abundance of the heavier ³⁷Cl isotope?",
        "a": "20%", "b": "25%", "c": "50%", "d": "75%",
        "ans": 1,
        "explanation": "Let x be the fractional abundance of ³⁷Cl. 35(1 - x) + 37(x) = 35.5 => 35 + 2x = 35.5 => 2x = 0.5 => x = 0.25 (25% abundance of ³⁷Cl and 75% of ³⁵Cl)."
    },
    {
        "id": "chem_mr_232",
        "topic": "Environmental Analysis & Gas Precipitation",
        "year": "1995",
        "question": "10.0 dm³ of air containing H₂S impurity was bubbled through excess Pb(NO₃)₂ solution until all H₂S reacted, depositing 5.02 g of black PbS precipitate. What is the percentage by volume of H₂S in the air sample at STP? [Pb=207, S=32, Molar volume = 22.4 dm³]",
        "a": "50.2%", "b": "47.0%", "c": "4.70%", "d": "0.47%",
        "ans": 2,
        "explanation": "Molar mass PbS = 207 + 32 = 239 g/mol. Moles PbS = 5.02 / 239 = 0.0210 mol = moles H₂S. Volume of H₂S at STP = 0.0210 × 22.4 dm³ = 0.4704 dm³. % by volume = (0.4704 / 10.0) × 100% = 4.70%."
    },
    {
        "id": "chem_mr_233",
        "topic": "Hydrates & Deliquescence vs Efflorescence",
        "year": "1995",
        "question": "A blue anhydrous solid weighing 5.0 g was exposed to atmospheric air on a bench. After 8 hours, it weighed 5.5 g and turned pink. It can be deduced that the substance:",
        "a": "Is efflorescent",
        "b": "Is an explosive",
        "c": "Absorbed water of crystallization from the air to form a hydrated crystalline salt",
        "d": "Decomposed with evolution of gas",
        "ans": 2,
        "explanation": "Anhydrous cobalt(II) chloride is blue. When it absorbs atmospheric moisture to form hydrated CoCl₂·6H₂O, it increases in mass and changes colour from blue to pink."
    },
    {
        "id": "chem_mr_234",
        "topic": "Industrial Metallurgy & Environmental Effluents",
        "year": "1995",
        "question": "The industrial wastewater effluent from an older chlor-alkali plant using Castner-Kellner mercury cathode cells may contain dangerous toxic traces of:",
        "a": "Sodium carbonate", "b": "Lead nitrate", "c": "Mercury compounds [such as HgCl₂]", "d": "Calcium hydroxide",
        "ans": 2,
        "explanation": "Castner-Kellner mercury cathode cells use a flowing pool of liquid mercury. Trace losses in the wastewater lead to dangerous mercury pollution (which biomagnifies into methylmercury)."
    },
    {
        "id": "chem_mr_235",
        "topic": "Solutions & Solubility Curves",
        "year": "1995",
        "question": "The solubility of copper(II) tetraoxosulphate(VI) (CuSO₄) is 75 g per 100 g water at 100°C and 25 g per 100 g water at 30°C. What mass of CuSO₄ will crystallize out when 50 g of a saturated solution at 100°C is cooled to 30°C?",
        "a": "57.5 g", "b": "42.9 g", "c": "28.6 g", "d": "14.3 g",
        "ans": 3,
        "explanation": "At 100°C, 175 g of saturated solution contains 75 g salt and 100 g water. In 50 g of saturated solution, mass of water = (100/175) × 50 = 28.57 g, and mass of dissolved salt = 21.43 g. At 30°C, 28.57 g water holds (25/100) × 28.57 = 7.14 g salt. Mass crystallized = 21.43 - 7.14 = 14.29 ≈ 14.3 g."
    },
    {
        "id": "chem_mr_236",
        "topic": "Colloids & Dispersions",
        "year": "1995",
        "question": "Smoke is a colloidal dispersion system in which:",
        "a": "Liquid droplets are dispersed in a gas",
        "b": "Solid soot/ash particles are dispersed in a gas",
        "c": "Gas bubbles are dispersed in a liquid",
        "d": "Liquid particles are dispersed in another liquid",
        "ans": 1,
        "explanation": "Smoke is a solid aerosol comprising microscopic solid carbon (soot) and mineral particles suspended in air (gas dispersion medium)."
    },
    {
        "id": "chem_mr_237",
        "topic": "Stoichiometry & Molar Mass of Monobasic Acid",
        "year": "1995",
        "question": "2.00 g of a pure solid monobasic organic acid was dissolved in water and made up to 250 cm³. 25.0 cm³ of this solution required 20.00 cm³ of 0.10 M NaOH for complete neutralization. What is the molar mass of the acid?",
        "a": "200 g mol⁻¹", "b": "160 g mol⁻¹", "c": "100 g mol⁻¹", "d": "50 g mol⁻¹",
        "ans": 2,
        "explanation": "Moles NaOH = 0.020 L × 0.10 M = 0.0020 mol. Since the acid is monobasic (1:1 ratio), moles acid in 25 cm³ = 0.0020 mol. In 250 cm³, total moles = 0.020 mol. Molar mass = 2.00 g / 0.020 mol = 100 g mol⁻¹."
    },
    {
        "id": "chem_mr_238",
        "topic": "Acids, Bases & pH Calculations",
        "year": "1995",
        "question": "What is the hydrogen ion concentration [H⁺] in mol dm⁻³ of a citrus juice solution having a pH of 4.40? [log₁₀(4.0) = 0.60]",
        "a": "4.0 × 10⁻⁵ mol dm⁻³",
        "b": "0.4 × 10⁻⁵ mol dm⁻³",
        "c": "4.0 × 10⁻⁴ mol dm⁻³",
        "d": "1.0 × 10⁻⁴ mol dm⁻³",
        "ans": 0,
        "explanation": "pH = -log₁₀[H⁺] => [H⁺] = 10^(-pH) = 10^(-4.40) = 10^(0.60 - 5.0) = 10^(0.60) × 10⁻⁵ = 4.0 × 10⁻⁵ mol dm⁻³."
    },
    {
        "id": "chem_mr_239",
        "topic": "Solutions & Dilution Calculations",
        "year": "1995",
        "question": "What volume of 11.0 M concentrated hydrochloric acid must be diluted with distilled water to prepare exactly 1.00 dm³ of 0.055 M dilute acid?",
        "a": "0.005 dm³ (5.0 cm³)",
        "b": "0.050 dm³ (50.0 cm³)",
        "c": "0.550 dm³",
        "d": "0.110 dm³",
        "ans": 0,
        "explanation": "Using C₁V₁ = C₂V₂: 11.0 M × V₁ = 0.055 M × 1.00 dm³ => V₁ = 0.055 / 11.0 = 0.005 dm³ = 5.0 cm³."
    },
    {
        "id": "chem_mr_240",
        "topic": "Faraday's Laws & Gas Volumes",
        "year": "1995",
        "question": "If 10.8 g of silver is deposited in a silver coulometer connected in series with a dilute H₂SO₄ coulometer, what volume of oxygen gas is liberated at the anode at S.T.P? [Ag=108, Molar volume at STP = 22.4 dm³]",
        "a": "0.56 dm³", "b": "1.12 dm³", "c": "2.24 dm³", "d": "5.60 dm³",
        "ans": 0,
        "explanation": "Moles Ag deposited = 10.8 / 108 = 0.10 mol e⁻. Liberation of 1 mole of O₂ requires 4 moles of electrons (4OH⁻ → 2H₂O + O₂ + 4e⁻). Moles of O₂ = 0.10 / 4 = 0.025 mol. Volume of O₂ at STP = 0.025 × 22.4 dm³ = 0.56 dm³ (560 cm³)."
    },
    {
        "id": "chem_mr_241",
        "topic": "Faraday's Laws of Electrolysis",
        "year": "1995",
        "question": "How many moles of nickel metal will be deposited from an aqueous Ni²⁺ solution by passing 0.40 Faraday of electricity?",
        "a": "0.20 mol", "b": "0.40 mol", "c": "0.80 mol", "d": "0.10 mol",
        "ans": 0,
        "explanation": "Ni²⁺ + 2e⁻ → Ni. 2 Faradays deposit 1 mole of Ni. Thus, 0.40 Faraday deposits 0.40 / 2 = 0.20 mole of nickel."
    },
    {
        "id": "chem_mr_242",
        "topic": "Redox Reactions & Oxidation States",
        "year": "1995",
        "question": "In the balanced redox equation: Cr₂O₇²⁻ + 6Fe²⁺ + 14H⁺ → 2Cr³⁺ + 6Fe³⁺ + 7H₂O, the oxidation state of chromium changes from:",
        "a": "+7 to +3", "b": "+6 to +3", "c": "+5 to +3", "d": "+6 to +2",
        "ans": 1,
        "explanation": "In dichromate (Cr₂O₇²⁻): 2(Cr) + 7(-2) = -2 => 2Cr = +12 => Cr = +6. In Cr³⁺, Cr is in the +3 state. Thus, chromium is reduced from +6 to +3."
    },
    {
        "id": "chem_mr_243",
        "topic": "Redox Reactions & Oxidizing Agents",
        "year": "1995",
        "question": "In the reaction: IO₃⁻ + 5I⁻ + 6H⁺ → 3I₂ + 3H₂O, the oxidizing agent is:",
        "a": "H⁺", "b": "I⁻", "c": "IO₃⁻", "d": "I₂",
        "ans": 2,
        "explanation": "In the iodate ion (IO₃⁻), iodine has an oxidation state of +5. It is reduced to iodine (I₂, oxidation state 0), causing the oxidation of iodide (I⁻, state -1 to 0). Hence IO₃⁻ is the oxidizing agent."
    },
    {
        "id": "chem_mr_244",
        "topic": "Thermochemistry (Thermite Reaction)",
        "year": "1995",
        "question": "For the thermite reaction: Fe₂O₃(s) + 2Al(s) → Al₂O₃(s) + 2Fe(s), calculate the standard enthalpy change given that ΔH_f(Al₂O₃) = -1670 kJ mol⁻¹ and ΔH_f(Fe₂O₃) = -822 kJ mol⁻¹.",
        "a": "+848 kJ mol⁻¹", "b": "-848 kJ mol⁻¹", "c": "-2492 kJ mol⁻¹", "d": "+2492 kJ mol⁻¹",
        "ans": 1,
        "explanation": "ΔH°_rxn = ΔH°_f(Al₂O₃) - ΔH°_f(Fe₂O₃) = -1670 - (-822) = -1670 + 822 = -848 kJ mol⁻¹ (highly exothermic)."
    },
    {
        "id": "chem_mr_245",
        "topic": "Reaction Kinetics & Rate Factors",
        "year": "1995",
        "question": "Which of the following calcium carbonate samples will react fastest with 50 cm³ of 1.0 M dilute nitric acid?",
        "a": "5.0 g of marble chips at 25°C",
        "b": "5.0 g of powdered marble at 25°C",
        "c": "5.0 g of marble chips at 50°C",
        "d": "5.0 g of powdered marble at 50°C",
        "ans": 3,
        "explanation": "Powdered CaCO₃ provides the maximum surface area for collisions, and higher temperature (50°C) increases average molecular kinetic energy and collision frequency, maximizing the reaction rate."
    },
    {
        "id": "chem_mr_246",
        "topic": "Laboratory Gas Collection",
        "year": "1995",
        "question": "Which of the following gases is much denser than air and collected in the laboratory by downward delivery (upward displacement of air)?",
        "a": "Hydrogen (H₂, M=2)",
        "b": "Ammonia (NH₃, M=17)",
        "c": "Chlorine (Cl₂, M=71)",
        "d": "Methane (CH₄, M=16)",
        "ans": 2,
        "explanation": "Chlorine has a molar mass of 71 g/mol (~2.5 times denser than air, M_air ~ 29) and is collected by downward delivery into a gas jar, displacing lighter air upwards."
    },
    {
        "id": "chem_mr_247",
        "topic": "Non-Metals (Nitric Acid Decomposition)",
        "year": "1995",
        "question": "The reddish-brown fumes given off when concentrated nitric acid is heated or exposed to sunlight consist of:",
        "a": "Nitrogen(II) oxide (NO)",
        "b": "Nitrogen(IV) oxide (NO₂)",
        "c": "Dinitrogen monoxide (N₂O)",
        "d": "Dinitrogen pentoxide (N₂O₅)",
        "ans": 1,
        "explanation": "Pure concentrated HNO₃ slowly decomposes: 4HNO₃ → 4NO₂↑ (brown fumes) + 2H₂O + O₂. The dissolved NO₂ gas gives older samples of nitric acid a yellowish-brown tint."
    },
    {
        "id": "chem_mr_248",
        "topic": "Qualitative Analysis of Gases",
        "year": "1995",
        "question": "Which single chemical reagent will distinguish carbon(IV) oxide (CO₂) from sulphur(IV) oxide (SO₂)?",
        "a": "Lime water [Ca(OH)₂]",
        "b": "Acidified potassium dichromate(VI) solution",
        "c": "Moist blue litmus paper",
        "d": "Burning wooden splint",
        "ans": 1,
        "explanation": "Both CO₂ and SO₂ turn lime water milky. However, reducing SO₂ turns orange acidified K₂Cr₂O₇ green (reducing Cr⁶⁺ to Cr³⁺), whereas CO₂ does not affect acidified dichromate."
    },
    {
        "id": "chem_mr_249",
        "topic": "Industrial Chemistry (Haber Process)",
        "year": "1995",
        "question": "In the Haber process for the manufacture of ammonia: N₂(g) + 3H₂(g) ⇌ 2NH₃(g), the catalyst commonly used is:",
        "a": "Finely divided iron promoted with Al₂O₃/K₂O",
        "b": "Platinum gauze",
        "c": "Vanadium(V) oxide",
        "d": "Copper oxide",
        "ans": 0,
        "explanation": "Finely divided iron (promoted with aluminium oxide and potassium oxide) operates at 450°C and 200 atm to accelerate the formation of ammonia."
    },
    {
        "id": "chem_mr_250",
        "topic": "Applied Metallurgy (Blast Furnace Slag)",
        "year": "1995",
        "question": "The major chemical component of the molten slag that floats on molten iron in a blast furnace is:",
        "a": "Iron(II) silicate",
        "b": "Calcium trioxosilicate(IV) (CaSiO₃)",
        "c": "Calcium carbide",
        "d": "Aluminium oxide",
        "ans": 1,
        "explanation": "Limestone (CaCO₃) decomposes to CaO: CaCO₃ → CaO + CO₂. Basic CaO then reacts with acidic sand impurities (SiO₂) in the iron ore to form molten slag: CaO + SiO₂ → CaSiO₃."
    }
]

print("Part 5 dataset ready")
