# coding=utf-8
"""
Complete JAMB Biology Parts 1 to 5 Data (250 Questions).
Directly transcribed from user's attached JAMB Biology Past Questions Objective PT 1-5.
Full taxonomic nomenclature, physiological processes, genetic crosses, and anatomical structures.
"""

def get_all_biology_questions():
    questions = []

    # -------------------------------------------------------------
    # PART 1 (Questions 1 to 50)
    # -------------------------------------------------------------
    pt1_data = [
        ("Which Question Paper Type of Biology is given to you?", "Type A", "Type B", "Type C", "Type D", 2, "JAMB examination question paper type identifier.", "General Introduction"),
        ("The function of the red head in male Agama lizards is to _____.",
         "conceal and camouflage the animal from predators", "scare other males from the territory", "attract female lizards for mating purposes", "warn predators of the distastefulness of the animal", 2,
         "The bright red breeding coloration of the male Agama lizard serves as an epigamic sexual display to attract receptive females.", "Animal Behaviour & Adaptations"),
        ("In which of the following species is the biomass of an individual the smallest?",
         "Agama sp.", "Bufo sp.", "Spirogyra sp.", "Tilapia sp.", 2,
         "Spirogyra is a microscopic filamentous green alga with individual cell biomass negligible compared to macroscopic vertebrates.", "Ecology & Biomass"),
        ("Seed plants (Spermatophytes) are divided into _____.",
         "tracheophytes and ferns", "angiosperms and gymnosperms", "monocotyledons and dicotyledons", "thallophytes and bryophytes", 1,
         "Spermatophytes are classified into Gymnosperms (naked-seeded plants like conifers) and Angiosperms (enclosed-seeded flowering plants).", "Plant Classification"),
        ("In which of the following groups of vertebrates is parental care mostly exhibited?",
         "Reptilia", "Amphibia", "Aves", "Mammalia", 3,
         "Mammals exhibit the highest degree of parental care, including internal gestation, lactation with mammary glands, and prolonged juvenile protection.", "Vertebrate Zoology"),
        ("Which of the organisms represented (I. Grasshopper/Locust, II. Weevil, III. Mosquito, IV. Caterpillar) are notable agricultural pests?",
         "II and IV", "I and IV", "II and III", "I and III", 1,
         "Locusts (I) and lepidopteran larvae/caterpillars (IV) cause widespread defoliation and destruction of arable farm crops.", "Agricultural Pests"),
        ("An economic importance of the organism represented by IV (caterpillar larva) is that _____.",
         "it transmits water borne disease to humans", "it is destructive to farm crops", "its faeces pollutes drinking water", "it helps in the control of mosquito larvae", 1,
         "Voracious caterpillar larvae feed aggressively on agricultural crop foliage, causing severe economic damage.", "Economic Entomology"),
        ("The adult form of the aquatic mosquito pupa (III) is a vector of _____.",
         "sleeping sickness", "river blindness", "cholera", "elephantiasis (and malaria/yellow fever)", 3,
         "Female Culex and Anopheles mosquitoes transmit filarial nematodes causing lymphatic filariasis (elephantiasis) and Plasmodium malaria.", "Parasitology & Vectors"),
        ("The adaptive importance of nuptial flight from termite colonies is to _____.",
         "disperse the reproductives in order to establish new colonies", "provide abundant food for birds and other animals during the early rains", "ensure cross-breeding between members of one colony and another", "expel the reproductives so as to provide enough food for other members", 0,
         "Winged reproductive alates swarm during the early rains to disperse genetically, pair off, shed wings, and found new subterranean colonies.", "Social Insects"),
        ("In the anaerobic fermentation apparatus containing lime water, 10% sucrose and yeast, the gas evolved in the process is _____.",
         "carbon (IV) oxide", "nitrogen", "oxygen", "carbon (II) oxide", 0,
         "Yeast ferments sucrose to produce ethanol and carbon(IV) oxide: C₁₂H₂₂O₁₁ + H₂O → 4C₂H₅OH + 4CO₂↑ (turning lime water milky).", "Cellular Respiration"),
        ("The experimental set-up above (sucrose solution, yeast, delivery tube into lime water) is used to demonstrate the process of _____.",
         "diffusion", "photosynthesis", "fermentation", "plasmolysis", 2,
         "The apparatus demonstrates anaerobic cellular respiration (alcoholic fermentation) by yeast.", "Fermentation Experiments"),
        ("Which of the following can cause shrinkage (crenation/plasmolysis) of living cells?",
         "Hypotonic solution", "Isotonic solution", "Deionized water", "Hypertonic solution", 3,
         "In a hypertonic medium of higher osmotic pressure, water exosmoses out of the cell, causing cell shrinkage (crenation/plasmolysis).", "Osmosis & Cell Physiology"),
        ("Which of the following is true of leucocytes (white blood cells)?",
         "they are respiratory pigments", "they are most numerous and ramify all cells", "they are large and nucleated", "they are involved in blood clotting", 2,
         "Leucocytes are amoeboid, nucleated, and larger than erythrocytes, functioning in immune defense.", "Circulatory System"),
        ("The conversion and incorporation of absorbed nutrients into the living cellular protoplasm of a consumer is referred to as _____.",
         "digestion", "assimilation", "absorption", "inhibition", 1,
         "Assimilation is the metabolic incorporation of digested nutrient molecules into protoplasmic structures for growth and repair.", "Nutrition"),
        ("The ability of living organisms to detect and respond to changes in their environment is referred to as _____.",
         "locomotion", "irritability", "growth", "taxis", 1,
         "Irritability (or sensitivity) is the fundamental life characteristic of perceiving stimuli and executing appropriate responses.", "Characteristics of Living Things"),
        ("In mammals, the exchange of nutrients and metabolic waste products between blood and tissue cells occurs across the _____.",
         "lungs", "oesophagus", "trachea", "lymph / capillary network", 3,
         "Tissue fluid (lymph) bathing somatic cells mediates metabolic nutrient and gaseous diffusion between capillary blood and tissues.", "Circulatory Physiology"),
        ("An example of an endospermous (albuminous) seed is _____.",
         "maize grain", "cashew nut", "cotton seed", "bean seed", 0,
         "Monocotyledonous seeds like maize retain a prominent starch-storing triploid endosperm at maturity.", "Plant Morphology"),
        ("Which of the following modes of nutrition is correctly matched with the organism that exhibits it? (I. Parasitism → Sundew, II. Autotrophism → Amoeba, III. Saprophytism → Alga, IV. Heterotrophism → Agama)",
         "II", "III", "IV", "I", 2,
         "Agama lizards are holozoic heterotrophs that consume insects and other organisms.", "Modes of Nutrition"),
        ("Given test tubes: I (cane sugar + water), II (cane sugar + dilute acid, boiled), III (cane sugar + sucrase enzyme). In which test tubes will glucose be detected after hydrolysis?",
         "I and II only", "II and III only", "I only", "I, II and III", 1,
         "Sucrose is hydrolyzed into glucose and fructose either chemically by heating with dilute acid (II) or enzymatically by sucrase (III).", "Digestion & Enzymes"),
        ("The digestive enzyme involved in the hydrolysis of sucrose into monosaccharides is _____.",
         "rennin", "erepsin", "sucrase", "maltase", 2,
         "Sucrase (invertase) in intestinal juice specifically hydrolyzes the disaccharide sucrose into glucose and fructose.", "Enzymology"),
        ("The part of the mammalian inner ear responsible for the maintenance of dynamic and static body balance is the _____.",
         "cochlea", "pinna", "semicircular canals / perilymph", "ossicles", 2,
         "The semicircular canals, utricle, and saccule (containing endolymph and perilymph with sensory hair cells) coordinate equilibrium and balance.", "Sense Organs: Ear"),
        ("The path followed by inhaled air as it passes through the respiratory system in mammals is _____.",
         "trachea → bronchi → bronchioles → alveoli", "bronchi → trachea → alveoli → bronchioles", "trachea → bronchioles → bronchi → alveoli", "bronchioles → alveoli → bronchi → trachea", 0,
         "Air enters through the trachea, splits into primary bronchi, branches into smaller bronchioles, and terminates in the alveolar air sacs.", "Respiratory System"),
        ("The movement response of a cockroach rapidly fleeing away from an illuminated light source is described as _____.",
         "positive phototaxis", "negative phototaxis", "negative phototropism", "positive phototropism", 1,
         "Locomotory movement of a mobile animal away from a directional light stimulus is negative phototaxis.", "Irritability & Movement"),
        ("The vascular tissues in higher plants (xylem and phloem) are responsible for _____.",
         "the movement of food and water", "suction pressure", "transpiration pull", "the transport of gases and water", 0,
         "Xylem conducts water and mineral salts upward; phloem translocates manufactured organic food substances throughout the plant.", "Plant Transport"),
        ("Which of the following organs regulates the levels of water, mineral salts, hydrogen ions and urea in mammalian blood?",
         "Liver", "Kidney", "Bladder", "Colon", 1,
         "The kidneys perform osmoregulation and excretion, filtering blood to regulate ionic balance, pH, water volume, and urea elimination.", "Excretory System"),
        ("The sequence of the one-way gaseous exchange water mechanism across the respiratory surface in a teleost fish is _____.",
         "operculum → gills → mouth", "gills → operculum → mouth", "mouth → operculum → gills", "mouth → gills → operculum", 3,
         "Water enters through the mouth, flows over the vascular gill filaments for oxygen uptake, and exits through the opercular cleft.", "Aquatic Respiration"),
        ("The type of asexual reproduction that is common to both Paramecium and unicellular protists is _____.",
         "budding", "sporulation", "fragmentation", "binary fission", 3,
         "Paramecium, Amoeba, and many protists reproduce asexually by mitotic transverse or longitudinal binary fission.", "Reproduction"),
        ("In nature, plants and animals are perpetually engaged in mutualism because _____.",
         "they are rivals", "all animals rely on food produced by plants", "they utilize the respiratory wastes of each other (O₂ and CO₂ exchange)", "they are neighbours", 2,
         "Plants consume animal respiratory waste CO₂ for photosynthesis and release O₂, which animals inhale for aerobic respiration.", "Ecosystem Interactions"),
        ("Soil sample data: Basin alone = 80.5g, Basin + soil = 101.5g (soil = 21.0g), Basin + oven-dried soil = 99.0g, Basin + roasted soil = 95.5g. Humus lost = 99.0 - 95.5 = 3.5g. The percentage of humus in the soil sample is _____.",
         "16.7%", "17.6%", "26.7%", "16.2%", 0,
         "Initial soil mass = 101.5 - 80.5 = 21.0 g. Humus burnt away = 99.0 - 95.5 = 3.5 g. % humus = (3.5 / 21.0) × 100% = 16.67% ≈ 16.7%.", "Soil Experiments"),
        ("An example of a filter-feeding animal is the _____.",
         "shark", "butterfly", "whale (baleen whale)", "mosquito", 2,
         "Baleen whales filter huge volumes of seawater using baleen plates to strain out krill and planktonic organisms.", "Feeding Mechanisms"),
        ("Which of the following is a characteristic feature of the demographic population pyramid of a developing country?",
         "long lifespan", "low birth rate", "low death rate", "broad base with short lifespan / high birth rate", 3,
         "Developing nations have expansive triangular population pyramids with high fertility at the base and declining proportions reaching old age.", "Population Ecology"),
        ("The complex interaction of a biological community of organisms with its abiotic physical environment constitutes _____.",
         "a niche", "a food chain", "an ecosystem", "a microhabitat", 2,
         "An ecosystem is a self-sustaining ecological unit comprising biotic communities interacting with abiotic physical factors.", "Ecology"),
        ("The biological insect vector of the human malaria parasite (Plasmodium) is the _____.",
         "female Aedes mosquito", "female Anopheles mosquito", "male Culex mosquito", "female Culex mosquito", 1,
         "Only female Anopheles mosquitoes possess piercing-sucking mouthparts required to take blood meals and transmit Plasmodium sporozoites.", "Parasitology"),
        ("Which of the following meteorological instruments is used to measure relative atmospheric humidity?",
         "Hydrometer", "Thermometer", "Hygrometer", "Anemometer", 2,
         "A wet-and-dry bulb psychrometer/hygrometer measures the relative humidity of the atmosphere.", "Ecological Instruments"),
        ("The exo-erythrocytic (pre-erythrocytic) schizogony phase of the life cycle of the malaria parasite occurs in the _____.",
         "liver of humans", "reticuloendothelial cells of humans", "Malpighian tubules of mosquito", "brain of humans", 0,
         "Sporozoites injected into the bloodstream invade human hepatocytes (liver parenchymal cells) where they undergo primary asexual multiplication.", "Life Cycle of Plasmodium"),
        ("Major natural ecological habitats are broadly classified into _____.",
         "biotic and abiotic", "aquatic and terrestrial", "arboreal and marine biomes", "microhabitats and macrohabitats", 1,
         "Biospheric habitats are fundamentally partitioned into aquatic (freshwater, estuarine, marine) and terrestrial biomes.", "Habitats"),
        ("Dracunculiasis (guinea worm disease) can be contracted through _____.",
         "eating contaminated food", "drinking contaminated water containing Cyclops", "bathing in contaminated water", "bites of blackfly", 1,
         "Dracunculus medinensis larvae are ingested by drinking pond water containing infected Cyclops water fleas.", "Water-Borne Diseases"),
        ("Which of the following groups of environmental ecological factors are density-dependent?",
         "Food, salinity, accumulation of metabolites and light", "Temperature, salinity, predation and disease", "Food, predation, disease and accumulation of metabolites", "Temperature, food, disease and light", 2,
         "Density-dependent factors (competition for food, contagious disease epidemics, predation, and waste toxicity) intensify as population density rises.", "Population Dynamics"),
        ("Millet, sorghum, maize and onions are common staple crops grown in Nigeria in the _____.",
         "tropical rainforest", "Sudan savanna", "montane forests", "Sahel savanna", 1,
         "The Sudan savanna belt is the premier grain-producing agricultural ecological zone in northern Nigeria.", "Ecological Zones of Nigeria"),
        ("In which of the following ecological biomes is the southwestern part of Nigeria located?",
         "Temperate forest", "Tropical rainforest", "Tropical woodland", "Desert", 1,
         "Southwestern Nigeria lies predominantly within the humid tropical rainforest and derived savanna vegetation belt.", "Biomes"),
        ("An inheritable phenotypic character determined by an allele situated on the differential segment of the X chromosome is _____.",
         "recessive", "sex-linked", "homozygous", "dominant", 1,
         "Sex-linked genes (e.g. red-green colour blindness, haemophilia) reside on the X chromosome and exhibit criss-cross inheritance.", "Genetics"),
        ("In a biological population, severe lack of physical living space leads directly to an increase in _____.",
         "water scarcity", "birth rate", "disease rate / mortality", "drought", 2,
         "Overcrowding enhances pathogen transmission, stress-induced vulnerability, and communicable disease infection rates.", "Population Density"),
        ("If the cross of a pure red-flowered plant with a white-flowered plant produces all pink-flowered offspring in the F₁ generation, this demonstrates _____.",
         "codominance", "incomplete dominance", "mutation", "linkage", 1,
         "Incomplete dominance occurs when the heterozygous phenotype is an intermediate blend between the two homozygous parental traits.", "Mendelian Genetics"),
        ("Which of the following evolutionary theories was NOT considered by Charles Darwin in formulating natural selection?",
         "Variation", "Survival of the fittest", "Use and disuse of organs", "Competition (struggle for existence)", 2,
         "The theory of 'Use and Disuse' was formulated by Jean-Baptiste Lamarck, not Charles Darwin.", "Evolutionary Theories"),
        ("The breeding or crossing of individuals of the same species that exhibit different genetic traits is _____.",
         "cross-breeding (hybridization)", "polygenic inheritance", "non-disjunction", "inbreeding", 0,
         "Cross-breeding (outbreeding) combines divergent parental genotypes to produce genetically diverse hybrid offspring.", "Genetics & Breeding"),
        ("How many multiple alleles govern the inheritance of the ABO blood group system in humans?",
         "3", "4", "5", "2", 0,
         "Human ABO blood group is controlled by three multiple alleles: I^A, I^B, and I^O on chromosome 9.", "Genetics"),
        ("During blood transfusion, agglutination occurs when recipient serum contains antibodies against _____.",
         "contrasting foreign antigens on donor erythrocytes", "two different antigens", "two different antibodies", "similar antigens and antibodies", 0,
         "Agglutination occurs when recipient agglutinins react specifically with foreign donor agglutinogen red blood cell antigens.", "Blood Groups"),
        ("The primary fallacy in Lamarck's evolutionary theory was the erroneous assumption that _____.",
         "traits are acquired through disuse of body parts", "environmentally acquired somatic traits are heritable", "acquired traits are seldom formed", "traits are acquired through the use of body parts", 1,
         "Somatic phenotypic changes acquired during an individual's lifetime do not alter gametic DNA and cannot be inherited.", "Evolution"),
        ("The bright, prominent eye-spots on the wings of certain moths that startle predators represent an example of _____.",
         "warning colouration (aposematism)", "disruptive colouration", "crypsis", "defensive mimicry", 0,
         "Large eyespots startle predators into mistaking the insect for a larger vertebrate predator, functioning as aposematic/warning display.", "Animal Adaptations"),
        ("The aerodynamic wings of a bat (mammal) and those of a bird (avian) with similar flight function but different anatomical origins represent _____.",
         "convergent evolution", "continuous variation", "coevolution", "divergent evolution", 0,
         "Convergent evolution produces analogous structures that perform similar functions in unrelated evolutionary lineages.", "Evolution")
    ]
    for idx, item in enumerate(pt1_data, 1):
        q, a, b, c, d, ans, exp, topic = item
        questions.append({
            "id": f"jamb_bio_pt1_{idx:02d}", "subject": "Biology", "topic": topic, "year": "PT. 1",
            "text": q, "a": a, "b": b, "c": c, "d": d, "ans": ans, "exp": exp,
            "label": f"JAMB Biology PT.1 • Q{idx}"
        })

    # -------------------------------------------------------------
    # PART 2 (Questions 1 to 50)
    # -------------------------------------------------------------
    pt2_data = [
        ("Which Question Paper Type of Biology as indicated above is given to you?", "Type Green", "Type Purple", "Type Red", "Type Yellow", 2, "JAMB examination question paper type identifier.", "General Introduction"),
        ("In an animal cell diagram, the organelle responsible for heredity (containing chromatin DNA) is labelled _____.",
         "I", "II (Nucleus)", "III", "IV", 1,
         "The cell nucleus houses chromosomes composed of DNA and histone proteins carrying genetic instructions.", "Cell Biology"),
        ("In the animal cell diagram, the oval double-membraned organelle labelled IV with folded cristae is the _____.",
         "mitochondrion", "cell wall", "endoplasmic reticulum", "nucleus", 0,
         "Mitochondria are the powerhouses of aerobic respiration, generating ATP via the citric acid cycle and oxidative phosphorylation.", "Cell Organelles"),
        ("Which of the following is most advanced in the evolutionary phylogenetic trend of invertebrates?",
         "Liver fluke (Platyhelminthes)", "Earthworm (Annelida)", "Snail (Mollusca)", "Cockroach (Arthropoda)", 3,
         "Arthropods are coelomate, segmented, have specialized jointed appendages, striated muscle, and complex nervous systems.", "Evolution of Animals"),
        ("Which of the following taxonomic ranks represents the lowest and most specific category of biological classification?",
         "Class", "Species", "Family", "Genus", 1,
         "Species is the basic fundamental unit of biological classification consisting of organisms capable of interbreeding.", "Taxonomy"),
        ("Plants that exhibit secondary growth (cambial woody thickening) are usually found among the _____.",
         "thallophytes", "pteridophytes", "monocotyledons", "dicotyledons and gymnosperms", 3,
         "Dicotyledonous angiosperms and gymnosperms possess active vascular cambium producing secondary xylem and phloem.", "Plant Anatomy"),
        ("The fungi form a distinct kingdom of eukaryotic organisms mainly because they _____.",
         "have spores", "lack chlorophyll and have chitinous cell walls", "have many fruiting bodies", "exhibit both sexual and asexual reproduction", 1,
         "Fungi are non-photosynthetic heterotrophic saprotrophs/parasites possessing chitinous cell walls and lacking chlorophyll.", "Kingdom Fungi"),
        ("An arthropod that is highly destructive to crops in the early larval stage of its life cycle is the _____.",
         "butterfly (caterpillar)", "mosquito", "bee", "millipede", 0,
         "Lepidopteran butterfly larvae (caterpillars) have chewing mouthparts that voraciously devour economic crop foliage.", "Economic Entomology"),
        ("An animal body that can be cut into two equal mirror-image halves along its central longitudinal axis in any vertical plane is said to be _____.",
         "radially symmetrical", "bilaterally symmetrical", "asymmetrical", "spherical", 0,
         "Radial symmetry (e.g. in Hydra and sea anemones) permits division into identical halves along multiple radial planes.", "Animal Symmetry"),
        ("Which of the following aquatic vertebrates possesses functional mammary glands and nurses its young?",
         "Dogfish", "Whale", "Shark", "Catfish", 1,
         "Whales are marine cetacean mammals that give birth to live calves and suckle them with milk from mammary glands.", "Mammalian Zoology"),
        ("The prominent anatomical feature that evolutionary links birds to reptiles is the possession of _____.",
         "feathers", "beak", "internal skeleton", "epidermal scales on their legs", 3,
         "Birds possess beta-keratin epidermal scales on their lower legs and feet, reflecting their dinosaurian reptilian ancestry.", "Vertebrate Evolution"),
        ("Countershading is an adaptive coloration feature that enables pelagic fish and aquatic animals to _____.",
         "fight enemies", "remain undetected by predators and prey", "warn enemies", "attract mates", 1,
         "Dark dorsal pigmentation blends with dark depths when viewed from above, while light ventral coloration blends with sunlight from below.", "Protective Coloration"),
        ("Which of the following plant organ structures completely lacks an external waterproof cuticle layer?",
         "leaf", "stem", "root", "shoot", 2,
         "Roots lack a waxy impermeable cutin cuticle so that root hairs can freely absorb soil water and mineral ions.", "Plant Physiology"),
        ("In the mammalian male reproductive system, the common duct that serves as a conduit for both urine and semen is the _____.",
         "urethra", "ureter", "urinary bladder", "seminal vesicle", 0,
         "The male urethra extends from the bladder through the penis, conveying both urine and seminal ejaculate.", "Urogenital System"),
        ("In plants, which of the following essential mineral elements is classified as a micronutrient required in minute quantities?",
         "Copper", "Potassium", "Phosphorus", "Nitrogen", 0,
         "Copper is a trace element (micronutrient) functioning as an enzyme cofactor, unlike macronutrients like N, P, and K.", "Plant Nutrition"),
        ("Which of the following botanical organisms is both partially parasitic and photosynthetic (autotrophic)?",
         "Sundew", "Loranthus (Mistletoe)", "Rhizopus", "Tapeworm", 1,
         "Loranthus (mistletoe) is a hemi-parasite; its green leaves photosynthesize while its haustoria tap host branch xylem.", "Modes of Nutrition"),
        ("A primary function of hydrochloric acid (HCl) produced by gastric parietal glands during human digestion is to _____.",
         "neutralise the effect of bile", "coagulate milk protein and emulsify fats", "stop the action of salivary ptyalin and provide acidic pH for pepsin", "break up food into smaller particles", 2,
         "Gastric HCl lowers stomach pH to ~1.5-2.0, denaturing salivary ptyalin, killing ingested microbes, and activating pepsinogen.", "Digestive Physiology"),
        ("Which of the following carbohydrates is a complex polysaccharide?",
         "Glucose", "Sucrose", "Maltose", "Cellulose", 3,
         "Cellulose is an unbranched high-molecular-weight structural polysaccharide polymer composed of repeating β-D-glucose units.", "Biomolecules"),
        ("In the seedling diagram showing transport, upward movement of water and dissolved mineral ions from roots (represented by arrow I) occurs through _____.",
         "xylem", "phloem", "cortex", "cambium", 0,
         "Xylem tracheary elements transport water and inorganic salts unidirectionally upwards from soil to photosynthetic leaves.", "Plant Transport"),
        ("In the plant transport diagram, arrow II originating from photosynthetic leaves represents the _____.",
         "release of oxygen", "intake of carbon (IV) oxide", "movement of photosynthates (sucrose) in phloem", "movement of nutrients", 2,
         "Phloem sieve tubes translocate manufactured organic photosynthates (sucrose and amino acids) from source leaves to sink tissues.", "Translocation"),
        ("In the mammalian nephron kidney, the site of ultrafiltration under hydrostatic pressure is the _____.",
         "uriniferous tubule", "Bowman's capsule (and glomerulus)", "loop of Henle", "renal collecting tubule", 1,
         "High capillary blood pressure in the glomerulus forces fluid and small solutes across the basement membrane into Bowman's capsule.", "Excretion"),
        ("Which of the following lateral meristematic tissues is directly involved in secondary thickening in woody stems?",
         "Collenchyma and xylem cells", "Vascular cambium only", "Vascular cambium and cork cambium (phellogen)", "Cork cambium and sclerenchyma", 2,
         "Vascular cambium forms secondary xylem/phloem, and cork cambium produces protective periderm cork tissue.", "Secondary Growth"),
        ("An example of a simple fruit that develops from a monocarpellary ovary (single carpel) is the _____.",
         "okra", "tomato", "bean pod (legume)", "orange", 2,
         "Legume pods of beans and peas develop from a single monocarpellary superior ovary with marginal placentation.", "Fruit Morphology"),
        ("In the diagram of the female reproductive system, the developing mammalian embryo implants and develops within the part labelled _____.",
         "IV (Vagina)", "III (Uterus)", "II (Ovary)", "I (Fallopian tube)", 1,
         "The blastocyst implants into the vascular endometrium of the uterus (womb) where gestation occurs.", "Reproductive Anatomy"),
        ("In the female reproductive system diagram, the gonad labelled II (ovary) functions to _____.",
         "produce egg cells (ova) and estrogen/progesterone", "protect sperms during fertilization", "secrete hormones during coitus", "protect the developing embryo", 0,
         "The ovaries perform oogenesis (producing mature ova) and synthesize the steroid hormones oestrogen and progesterone.", "Endocrinology & Reproduction"),
        ("Plant stem elongation and internode lengthening can be artificially stimulated by application of the phytohormone _____.",
         "gibberellin", "kinin", "abscisic acid", "ethylene", 0,
         "Gibberellins break seed dormancy, promote bolting, and dramatically stimulate cell division and internode elongation in dwarf plants.", "Plant Hormones"),
        ("The autonomic nervous system consists of motor neurones that regulate and control _____.",
         "voluntary skeletal muscles", "heartbeat and involuntary visceral activities", "tongue movements", "conscious hand gestures", 1,
         "The autonomic nervous system (sympathetic and parasympathetic) regulates involuntary visceral functions including cardiac rate, peristalsis, and gland secretion.", "Nervous System"),
        ("Cold-tolerant plants of temperate montane origin can thrive in tropical Nigeria in the highlands of the _____.",
         "rain forest", "Guinea savanna", "Sudan savanna", "montane forest (Jos and Mambilla plateaus)", 3,
         "High altitudes on the Jos and Mambilla plateaus create cool temperate-like microclimates supporting montane vegetation.", "Biogeography"),
        ("The global hydrological water cycle is driven and maintained primarily by _____.",
         "evaporation of water in the environment", "solar-driven evaporation and condensation of water", "condensation of water in the environment", "transpiration and respiration in plants", 1,
         "Solar radiation evaporates water from oceans and soils; water vapour rises, condenses into clouds, and falls as precipitation.", "Biogeochemical Cycles"),
        ("Organisms living in a brackish estuarine mangrove habitat must possess physiological adaptations to _____.",
         "withstand wide fluctuations in temperature", "survive only in water with low salinity", "withstand wide diurnal fluctuations in salinity", "feed only on phytoplankton and dead organic matter", 2,
         "Estuaries experience alternating tidal influxes of hypertonic marine seawater and hypotonic freshwater runoff, demanding euryhaline osmoregulation.", "Estuarine Ecology"),
        ("The presence of prop stilt roots, pneumatophores (breathing roots), and salt-excreting glands are adaptive features of plants in _____.",
         "tropical rainforest", "mangrove swamps", "grassland", "montane forest", 1,
         "Mangrove vegetation (e.g. Rhizophora, Avicennia) adapts to waterlogged, anaerobic, saline coastal mud through stilt roots and pneumatophores.", "Mangrove Ecology"),
        ("Which of the following animals can survive indefinitely in arid habitats without drinking water, relying exclusively on metabolic water?",
         "forest arboreal dweller", "Desert dwellers (e.g. kangaroo rat, desert rodents)", "forest-ground dweller", "rainforest dwellers", 1,
         "Desert rodents extract all needed water from dry seeds through the oxidative catabolism of carbohydrates and fats (metabolic water).", "Physiological Adaptations"),
        ("In ecological primary succession on bare exposed granite rock, the pioneering pioneer colonizers are usually _____.",
         "mosses", "ferns", "lichens (crustose lichens)", "fungi", 2,
         "Crustose lichens tolerate desiccation and secrete organic acids that etch minerals, initiating primitive pedogenesis (soil formation).", "Ecological Succession"),
        ("The carrying capacity (K) of a natural ecological habitat is reached when population growth begins to _____.",
         "increase slowly", "increase exponentially", "slow down and stabilize (zero net growth)", "remain steady at the carrying capacity plateau", 3,
         "At carrying capacity, environmental resistance balances the biotic potential, and population density oscillates stably around K.", "Population Ecology"),
        ("Abiotic physical density-independent factors that regulate and limit human populations include _____.",
         "disease and famine", "space and rainfall", "flooding and earthquakes", "temperature and contagious disease", 2,
         "Geophysical and climatic catastrophes (earthquakes, catastrophic flooding, volcanic eruptions) are abiotic density-independent limiters.", "Population Ecology"),
        ("An indigenous sustainable agricultural practice for restoring and maintaining soil nutrient fertility is _____.",
         "clearing farms by burning", "planting one crop type continuously", "adding inorganic fertilizers yearly", "crop rotation and bush fallowing", 3,
         "Rotational cropping with legumes and fallowing allows natural microbial nitrogen fixation and organic humus replenishment.", "Soil Conservation"),
        ("Human communicable diseases caused by water-borne bacterial pathogens include _____.",
         "gonorrhoea and poliomyelitis", "typhoid and syphilis", "tuberculosis and cholera", "typhoid and cholera", 3,
         "Typhoid fever (Salmonella typhi) and cholera (Vibrio cholerae) are ingested through sewage-contaminated drinking water.", "Pathology & Public Health"),
        ("The bell-shaped normal distribution curve displaying cassava plant heights illustrates _____.",
         "the highest frequency for height of 2 metres", "a discontinuously varying character", "a continuously varying polygenic character", "total yield in a cassava farm", 2,
         "Continuous phenotypic variation (e.g. height, mass) produces a Gaussian bell-shaped distribution governed by multiple quantitative genes.", "Variation & Genetics"),
        ("From the cassava height distribution graph, the modal height possessing the highest frequency of plants is approximately _____.",
         "1.4m", "1.6m", "1.8m", "2.0m", 1,
         "The peak apex of the normal distribution curve corresponds to the modal height class of 1.6 metres.", "Quantitative Variation"),
        ("Which of the following statements is true regarding human ABO blood transfusion?",
         "A person of blood group AB can donate blood only to another person of blood group AB", "persons of blood groups A and B can donate or receive blood from each other", "A person of blood group AB can receive blood only from persons of blood group A or B", "A person of blood group O can donate only to a person of blood group O", 0,
         "Blood group AB erythrocytes express both A and B antigens; they can donate safely only to homologous AB recipients.", "Blood Groups"),
        ("Pure-breeding yellow maize is crossed with white maize yielding all yellow seeds in F₁. Selfing F₁ produces yellow and white seeds in a 3:1 ratio. The yellow allele is _____.",
         "non-heritable", "sex-linked", "a recessive trait", "a dominant trait", 3,
         "The allele masking the alternative phenotype in heterozygous F₁ progeny and yielding a classical 3:1 phenotypic monohybrid ratio is dominant.", "Mendelian Genetics"),
        ("When a red-green colour-blind man (X^c Y) marries a phenotypically normal carrier woman (X^C X^c), what is the probability of their offspring being colour-blind?",
         "25%", "50%", "75%", "100%", 1,
         "Cross: X^c Y × X^C X^c yields daughters: X^C X^c (carrier, 25%), X^c X^c (colour-blind, 25%); sons: X^C Y (normal, 25%), X^c Y (colour-blind, 25%). Overall colour-blind offspring = 50%.", "Sex-Linked Genetics"),
        ("The complementary nitrogenous base-pairing rule for double-stranded DNA is _____.",
         "adenine → thymine and guanine → cytosine", "adenine → guanine and thymine → cytosine", "adenine → cytosine and guanine → thymine", "adenine → adenine and cytosine → cytosine", 0,
         "Watson-Crick base pairing specifies purine Adenine pairs with pyrimidine Thymine (A=T via 2 H-bonds) and Guanine pairs with Cytosine (G≡C via 3 H-bonds).", "Molecular Genetics"),
        ("When Paramecium aurelia and Paramecium caudatum are cultured together, P. caudatum dies out. This interaction is referred to as _____.",
         "interspecific competition", "intraspecific competition", "mutualism", "cooperation", 0,
         "Interspecific competition occurs between different species competing for identical limiting environmental resources.", "Competition"),
        ("Which of the following statements is true regarding Gause's competitive exclusion experiment between Paramecium species?",
         "P. aurelia is better adapted for obtaining food than P. caudatum", "P. caudatum is better adapted for obtaining food than P. aurelia", "both organisms cannot coexist", "both organisms cannot reproduce", 0,
         "Gause's Principle demonstrates that P. aurelia has a higher intrinsic growth rate and outcompetes P. caudatum for food.", "Ecological Competition"),
        ("The short, thick, conical bill in granivorous birds (e.g. finches, sparrows) is an adaptation for _____.",
         "crushing seeds", "sucking nectar", "tearing flesh", "straining mud", 0,
         "Stout conical beaks provide mechanical leverage for cracking hard cereal seeds and grain husks.", "Animal Adaptations"),
        ("The basking behaviour exhibited by ectothermic Agama lizards in the early morning sun is to _____.",
         "change the colour of their body", "raise their internal body temperature to become metabolically active", "fight to defend their territories", "attract the female for courtship", 1,
         "Being poikilothermic, lizards absorb solar radiant heat to elevate muscle and enzyme temperature for active foraging.", "Thermoregulation"),
        ("The evolutionary significance of vast numbers of winged alates swarming in termite nuptial flights is to _____.",
         "provide birds with plenty of food", "ensure species perpetuation despite heavy predatory pressure", "search for a favourable place to breed", "ensure that every individual gets a mate", 1,
         "Predator swamping (mass synchronous swarming) ensures that despite heavy predation, sufficient mated pairs survive to establish new colonies.", "Evolutionary Adaptations"),
        ("The concept of 'use and disuse of organs' and 'inheritance of acquired characteristics' was proposed to explain evolution by _____.",
         "Darwin's theory", "Lamarck's theory", "Mendel's theory", "Wallace's theory", 1,
         "Jean-Baptiste Lamarck published the hypothesis that structural modifications acquired through use or disuse during an organism's lifetime are passed to offspring.", "Evolutionary Theory"),
        ("From his field studies of diverse beak shapes among Galapagos finches, Charles Darwin deduced evidence of evolution from _____.",
         "comparative anatomy and adaptive radiation", "comparative physiology", "fossil remains", "comparative embryology", 0,
         "Adaptive radiation in Galapagos finch bill morphology from a common ancestral founder demonstrated divergent natural selection.", "Evolution")
    ]
    for idx, item in enumerate(pt2_data, 1):
        q, a, b, c, d, ans, exp, topic = item
        questions.append({
            "id": f"jamb_bio_pt2_{idx:02d}", "subject": "Biology", "topic": topic, "year": "PT. 2",
            "text": q, "a": a, "b": b, "c": c, "d": d, "ans": ans, "exp": exp,
            "label": f"JAMB Biology PT.2 • Q{idx}"
        })

    # -------------------------------------------------------------
    # PART 3 (Questions 1 to 50)
    # -------------------------------------------------------------
    pt3_data = [
        ("Which Question Paper Type of Biology is given to you?", "Type D", "Type I", "Type B", "Type U", 2, "JAMB examination question paper type identifier.", "General Introduction"),
        ("The biological metabolic process in which complex organic substances are broken down into simpler molecules with release of energy is _____.",
         "anabolism", "catabolism", "metabolism", "tropism", 1,
         "Catabolism encompasses oxidative cellular reactions (such as glycolysis and Krebs cycle) degrading complex nutrients to liberate ATP.", "Metabolism"),
        ("The photoreceptive organelle sensitive to light intensity in Euglena viridis is the _____.",
         "gullet", "flagellum", "chloroplast", "eyespot (stigma)", 3,
         "The carotenoid-pigmented stigma (eyespot) shields the paraflagellar photoreceptor, guiding positive phototaxis toward light.", "Protozoan Anatomy"),
        ("The organelles present in plant cells that are actively respiring and photosynthesizing simultaneously are _____.",
         "lysosomes and ribosomes", "Golgi apparatus and endoplasmic reticulum", "nucleus and centrioles", "mitochondria and chloroplasts", 3,
         "Mitochondria perform aerobic oxidative cellular respiration, while chloroplasts carry out photosynthetic carbon fixation.", "Cell Organelles"),
        ("The primary intermediate host of the pork tapeworm Taenia solium is the _____.",
         "cow", "goat", "dog", "pig", 3,
         "Taenia solium cysticerci (bladder worms) encyst in the striated muscle flesh of domestic swine (pigs).", "Parasitology"),
        ("In the diagram of an earthworm (Lumbricus), the glandular thickened saddle-like region labelled II is the _____.",
         "spermathecal pore", "cocoon", "clitellum", "chaetae", 2,
         "The clitellum is a glandular epidermal swelling that secretes a mucous cocoon during annelid sexual copulation.", "Annelid Morphology"),
        ("The earthworm lives in subterranean soils rich in _____.",
         "mud", "humus and decaying organic leaf litter", "coarse clay", "dry sand", 1,
         "Earthworms feed on decomposing organic detritus and decaying vegetation, thriving in moist, humus-rich agricultural soils.", "Ecology"),
        ("Which of the following anatomical features describes an essential diagnostic characteristic of the phylum Arthropoda?",
         "The organism finds it easy to grow freely", "the organism has a pair of jointed appendages", "the body is not divided into a number of segments", "the body is covered by a rigid chitinous exoskeleton", 3,
         "Arthropods are distinguished by an external sclerotized cuticle containing chitin and protein, requiring periodic ecdysis (moulting).", "Arthropod Zoology"),
        ("Which of the following characteristics accurately distinguishes a butterfly (Rhopalocera) from a moth (Heterocera)?",
         "the wings of butterfly rest vertically over the back at rest while those of moth rest horizontally or roof-like", "Both are active during the day", "they have similar antennae", "the abdomen of moth is fatter than that of butterfly", 0,
         "Butterflies hold their wings vertically erect over the thorax when resting and possess clubbed antennae, unlike nocturnal moths.", "Entomology"),
        ("Which of the following types of bird feathers provides the broad aerodynamic surface necessary for flight?",
         "Quill (remiges and rectrices)", "Filoplume", "Covert", "Down", 0,
         "Large stiff quill feathers of the wings (remiges) and tail (rectrices) generate aerodynamic lift and directional steering during flight.", "Ornithology"),
        ("Terrestrial plants adapted morphologically and physiologically to survive in arid deserts are referred to as _____.",
         "mesophytes", "hydrophytes", "epiphytes", "xerophytes", 3,
         "Xerophytes feature reduced leaves (spines), sunken stomata, thick cuticles, and succulent water-storing parenchyma.", "Plant Adaptations"),
        ("Which of the following is considered the simplest, most primitive cellular living organism?",
         "Paramecium", "Virus", "Amoeba", "Chlamydomonas", 2,
         "Amoeba proteus is an unspecialized, naked, unicellular eukaryotic protist lacking a fixed cell wall or permanent organelles.", "Cellular Organization"),
        ("A tubular feeding proboscis adapted for siphoning floral nectar is characteristic of adult _____.",
         "insects (butterflies and moths)", "tapeworms", "amphibians", "molluscs", 0,
         "Lepidopteran insects possess elongated maxillae interlocking to form a coiled siphoning proboscis.", "Insect Mouthparts"),
        ("A structural morphological adaptation of desert xerophytic plants for conserving water is the presence of _____.",
         "broad leaves with numerous stomata", "spongy mesophyll", "leaves reduced to sharp protective spines", "prominent open stomata in leaves", 2,
         "Modifying leaves into spines drastically minimizes surface area for cuticular and stomatal transpiration.", "Plant Adaptations"),
        ("The long, curved, sharp raptorial claws (talons) of predatory birds are adapted for _____.",
         "crushing hard seeds", "scooping mud", "tearing flesh", "grasping and killing live prey", 3,
         "Raptors (eagles, hawks, owls) utilize sharp, curved, powerful talons to strike, seize, and pinion live prey.", "Bird Adaptations"),
        ("During autotrophic nutrition, which of the following photosynthetic organisms utilizes solar light energy directly?",
         "Anabaena (cyanobacteria)", "sulphur bacteria", "Nitrosomonas sp.", "Nitrobacter sp.", 0,
         "Anabaena is a photosynthetic blue-green alga (cyanobacterium) possessing chlorophyll a that captures sunlight, unlike chemosynthetic nitrifiers.", "Photosynthesis"),
        ("The physiological movement and distribution of manufactured organic food substances within a plant occurs via _____.",
         "osmosis", "translocation in phloem", "transpiration", "diffusion", 1,
         "Translocation is the systemic transport of soluble organic assimilates (sucrose) through phloem sieve tubes.", "Plant Transport"),
        ("The digestive enzyme present in human saliva that initiates starch breakdown is _____.",
         "rennin", "lipase", "pepsin", "ptyalin (salivary alpha-amylase)", 3,
         "Ptyalin (salivary amylase) hydrolyzes cooked starches into maltose and dextrins at neutral to slightly alkaline pH.", "Digestion"),
        ("Green plants that possess specialized anatomical traps for capturing and enzymatically digesting insects are _____.",
         "carnivorous (insectivorous) plants", "symbiotic", "obligate parasitic", "saprophytic", 0,
         "Insectivorous plants (e.g. sundew, pitcher plant) capture insects to supplement nitrogen and phosphorus in acidic, nutrient-deficient bogs.", "Special Modes of Nutrition"),
        ("The biochemical process of transferring chemical bond energy from organic fuel molecules into high-energy ATP bonds is _____.",
         "autotropism", "photosynthesis", "photolysis", "cellular respiration", 3,
         "Aerobic cellular respiration couples glucose catabolism with mitochondrial oxidative phosphorylation to generate ATP.", "Respiration"),
        ("Fungi are classified ecologically as heterotrophs because they _____.",
         "are filamentous", "completely lack chlorophyll", "have mycelium", "lack true roots", 1,
         "Lacking photosynthetic pigments, fungi cannot synthesize organic nutrients and must absorb carbon from external organic matter.", "Kingdom Fungi"),
        ("An example of a pathogenic parasitic protozoan in humans is _____.",
         "Paramecium", "Plasmodium", "Euglena", "Chlamydomonas", 1,
         "Plasmodium falciparum is an obligate intra-erythrocytic protozoan parasite causing human malaria.", "Parasitic Protozoa"),
        ("Which white blood cells are primarily responsible for the production of humoral antibodies in vertebrate immunity?",
         "Phagocytes", "Lymphocytes (B-lymphocytes)", "Erythrocytes", "Monocytes", 1,
         "B-lymphocytes differentiate into antibody-secreting plasma cells mediating humoral adaptive immunity.", "Immune System"),
        ("The closed blood circulatory system of vertebrates consists anatomically of the _____.",
         "heart, arteries, capillaries and veins", "heart, aorta, capillaries and veins", "heart, aorta, arteries and veins", "heart, vena cava, arteries, and veins", 0,
         "Vertebrate closed circulation pumps blood continuously through the muscular heart, branching arteries, microvascular capillaries, and collecting veins.", "Circulatory System"),
        ("The specialized vascular plant tissue responsible for conducting water and dissolved mineral ions upward from roots is the _____.",
         "cambium", "xylem", "cortex", "phloem", 1,
         "Lignified xylem vessels and tracheids form non-living hollow capillary conduits transporting sap under transpirational pull.", "Plant Anatomy"),
        ("Which of the following blood cellular components plays an essential role in the blood clotting cascade?",
         "Red blood cells", "White blood cells", "Plasma", "Platelets (thrombocytes)", 3,
         "Blood platelets adhere to damaged vascular endothelium and release thromboplastin to trigger prothrombin conversion to thrombin.", "Haematology"),
        ("Which of the following constitutes approximately 55% of the total volume of whole blood in man?",
         "leucocytes", "platelets", "blood plasma", "erythrocytes", 2,
         "Centrifuged whole blood separates into ~55% liquid straw-coloured plasma and ~45% cellular formed elements (erythrocytes, leucocytes, platelets).", "Blood Composition"),
        ("The specialized tubular gland in the mammalian dermis directly involved in thermoregulation and excretion of water and salts is the _____.",
         "sweat gland (sudoriferous gland)", "Malpighian layer", "sebaceous gland", "horny layer", 0,
         "Sweat glands secrete watery perspiration containing sodium chloride, urea, and lactic acid, cooling the body via evaporation.", "Integumentary System"),
        ("The primary nitrogenous excretory waste product voided by terrestrial insects is insolubly precipitated as _____.",
         "Alkaloids", "Uric acid crystals", "Sweat", "Mucilage", 1,
         "Uricotelic insects excrete semi-solid insoluble uric acid pastes via Malpighian tubules, conserving critical body water.", "Excretion in Insects"),
        ("The primary rigid internal skeletal framework that supports and protects vital organs in vertebrates is the _____.",
         "endoskeleton", "ligament", "muscle", "joint", 0,
         "The bony endoskeleton provides structural leverage for locomotion, body posture, and protects brain, spinal cord, and thoracic viscera.", "Skeletal System"),
        ("The polysaccharide chitin in the arthropod exoskeleton is structurally hardened and strengthened by _____.",
         "lipids", "tanned scleroprotein (sclerotin) and calcium salts", "calcium compounds only", "organic salts", 1,
         "Arthropod cuticular sclerotization cross-links chitin microfibrils with phenolic-tanned proteins (sclerotin) and mineral carbonates.", "Arthropod Exoskeleton"),
        ("The transfer of pollen grains from the mature anther to the receptive stigma of a flower is termed _____.",
         "propagation", "placentation", "pollination", "fertilization", 2,
         "Pollination is the mechanical transfer of microspores (pollen) from stamen anthers to carpel stigmas by wind, insects, or water.", "Plant Reproduction"),
        ("The male androecium reproductive organ of a flower is the _____.",
         "carpel", "stamen", "petal", "sepal", 1,
         "Each stamen comprises a pollen-bearing anther supported by a slender filament.", "Flower Structure"),
        ("The master endocrine gland situated immediately below the hypothalamus in the sella turcica of the sphenoid bone is the _____.",
         "parathyroid", "adrenal", "pituitary gland (hypophysis)", "thyroid", 2,
         "The pituitary gland secretes tropic hormones (TSH, ACTH, FSH, LH, GH) regulating downstream endocrine glands under hypothalamic control.", "Endocrinology"),
        ("The primary plant growth hormone responsible for apical dominance, phototropism, and cell elongation is _____.",
         "cytokinin", "abscisic acid", "auxin (indole-3-acetic acid)", "gibberellin", 2,
         "Auxin synthesized in apical meristems stimulates cell elongation and suppresses lateral bud outgrowth (apical dominance).", "Phytohormones"),
        ("The retinal sensory photoreceptor cells in the vertebrate eye specialized for vision in dim light are the _____.",
         "cone cells", "crystalline lens", "rod cells", "iris", 2,
         "Rods contain the visual pigment rhodopsin, exhibiting high optical sensitivity to low photon levels (scotopic vision).", "Vision"),
        ("The pathological deficiency or absence of anti-diuretic hormone (vasopressin) in humans results in _____.",
         "decreasing dehydration", "drastic dehydration (diabetes insipidus)", "eliminating dehydration", "increasing dehydration", 1,
         "Lack of ADH prevents water reabsorption in renal collecting ducts, causing profuse dilute polyuria and severe dehydration (diabetes insipidus).", "Endocrine Disorders"),
        ("Oestrogen is a primary female sex steroid hormone synthesized and secreted by the _____.",
         "ovarian Graafian follicles", "testes", "anterior pituitary", "adrenal cortex", 0,
         "Maturing ovarian follicles and the corpus luteum synthesize oestrogens governing secondary sexual characteristics and uterine proliferation.", "Reproductive Hormones"),
        ("The optical eye defect caused by the progressive opacification and loss of transparency of the crystalline lens is _____.",
         "presbyopia", "glaucoma", "cataract", "astigmatism", 2,
         "Cataracts involve degenerative clouding of the protein matrix in the lens, causing progressive blurring and blindness.", "Sense Organs: Eye"),
        ("Which of the following environmental pollutants is readily biodegradable by microbial decomposers?",
         "crude oil", "heavy metals", "cellophane", "domestic sewage", 3,
         "Organic domestic sewage is broken down into harmless minerals and carbon dioxide by natural aquatic bacteria.", "Pollution"),
        ("A tropical vector-borne parasitic disease caused by the protozoan Trypanosoma brucei and transmitted by tsetse flies is _____.",
         "sleeping sickness (African trypanosomiasis)", "river blindness", "yellow fever", "malaria", 0,
         "Trypanosoma brucei gambiense/rhodesiense infects blood and cerebrospinal fluid, producing fatal African sleeping sickness.", "Parasitology"),
        ("The solid mineral crust and rock layer of the earth's biosphere is termed the _____.",
         "atmosphere", "hydrosphere", "biosphere", "lithosphere", 3,
         "The lithosphere comprises the outermost solid brittle crust and uppermost mantle supporting terrestrial ecosystems.", "Earth's Spheres"),
        ("Which of the following human venereal diseases is caused by the spirochaete bacterium Treponema pallidum?",
         "Gonorrhoea", "Leprosy", "Tuberculosis", "Syphilis", 3,
         "Syphilis is a chronic systemic sexually transmitted infection caused by Treponema pallidum.", "Microbiology & Diseases"),
        ("To which blood group do universal blood recipients belong in the human ABO system?",
         "Group B", "Group A", "Group O", "Group AB", 3,
         "Group AB individuals have both A and B antigens on their erythrocytes and lack anti-A and anti-B antibodies in plasma, safely receiving all ABO blood.", "Blood Groups"),
        ("The clumping together of foreign red blood cells upon reaction with specific serum agglutinins is _____.",
         "agglutination", "fusion", "transfusion", "compatibility", 0,
         "Agglutination occurs when bivalent antibody molecules cross-link surface antigens on donor erythrocytes into visible clumps.", "Immunology"),
        ("The state of metabolic dormancy and reduced physiological activity exhibited by desert animals during intense hot dry seasons is _____.",
         "rejuvenation", "xeromorphism", "hibernation", "aestivation", 3,
         "Aestivation is summer dormancy in hot, arid conditions to minimize metabolic heat production and desiccating water loss.", "Animal Adaptations"),
        ("One structural adaptation of the prickly pear cactus (Opuntia) to minimize transpirational water loss is the reduction of _____.",
         "internodes", "stem to leaves", "leaves to sharp protective spines", "flower size", 2,
         "Leaves are modified into spines, while the green succulent flattened stem (cladode) performs photosynthesis and stores water.", "Xerophytes"),
        ("Which of the following anatomical structures is adapted for seizing and tearing flesh in a carnivorous bird of prey?",
         "Hooked beak and sharp curved talons", "Smooth beak and strong claws", "Big beaks and strong feet", "Pointed beak and strong claws", 0,
         "Raptors possess sharply decurved predatory beaks for shredding muscle tissue and sharp talons for pinning quarry.", "Bird Morphology"),
        ("The specialized dermal pigment-containing cells that expand and contract to produce colour changes in the chameleon are _____.",
         "melanin", "carotenoids", "chromatin", "chromatophores", 3,
         "Chromatophores (melanophores, iridophores, xanthophores) disperse or concentrate pigment granules to change skin reflectance.", "Animal Physiology"),
        ("The behavioural evolutionary social adaptation in social insects (termites, honeybees, ants) is best described as _____.",
         "symbiosis", "saprophytism", "cooperation through division of labour", "commensalism", 2,
         "Colonial social insects exhibit eusocial cooperation with distinct reproductive, foraging, and defensive castes.", "Social Insects")
    ]
    for idx, item in enumerate(pt3_data, 1):
        q, a, b, c, d, ans, exp, topic = item
        questions.append({
            "id": f"jamb_bio_pt3_{idx:02d}", "subject": "Biology", "topic": topic, "year": "PT. 3",
            "text": q, "a": a, "b": b, "c": c, "d": d, "ans": ans, "exp": exp,
            "label": f"JAMB Biology PT.3 • Q{idx}"
        })

    # -------------------------------------------------------------
    # PART 4 (Questions 1 to 50)
    # -------------------------------------------------------------
    pt4_data = [
        ("Which Question paper Type of Biology is given to you?", "Type F", "Type E", "Type L", "Type S", 2, "JAMB examination question paper type identifier.", "General Introduction"),
        ("In the Euglena diagram, the anterior red-pigmented organelle labelled II is the _____.",
         "nucleus", "eyespot (stigma)", "basal granule", "contractile vacuole", 1,
         "The eyespot (stigma) detects light direction to orient swimming toward optimal illumination for photosynthesis.", "Protozoan Anatomy"),
        ("In the Euglena diagram, the green photosynthetic organelle containing chlorophyll labelled I is the _____.",
         "chloroplast", "eyespot", "nucleus", "flagellum", 0,
         "Euglena contains chloroplasts containing chlorophyll a and b for autotrophic photosynthetic carbon fixation.", "Protozoan Anatomy"),
        ("The lowest, most basic structural and functional level of organization in living organisms is the _____.",
         "organ", "cell", "system", "tissue", 1,
         "The cell is the smallest autonomous morphological unit capable of carrying out all fundamental life activities.", "Levels of Organization"),
        ("Which of the following organisms exhibits the most complex cellular level of biological organization?",
         "Heart (organ)", "Hair (tissue)", "Euglena (single cell)", "Hydra (tissue grade)", 0,
         "The mammalian heart is a complex multicellular organ composed of cardiac muscle, nervous, epithelial, and connective tissues.", "Levels of Organization"),
        ("In the Taenia solium tapeworm diagram, the organs for attachment to the host's intestinal mucosa (labelled I and II) are the _____.",
         "hooks (rostellum) and suckers", "proglottids", "neck", "strobila", 0,
         "The tapeworm scolex bears a rostellum with chitinous hooks (I) and four muscular suckers (II) that anchor to the host intestine.", "Parasitology"),
        ("In the tapeworm diagram, the segment representing a young immature proglottid near the neck is labelled _____.",
         "III", "IV", "I", "II", 0,
         "Immature young proglottids bud off continuously from the neck region (III) and mature as they are pushed posteriad.", "Parasitic Helminths"),
        ("Which of the following organisms is a multicellular colonial/filamentous alga?",
         "Chlamydomonas", "Spirogyra", "Amoeba", "Euglena", 1,
         "Spirogyra is a multicellular filamentous green alga with unbranched uniseriate cell chains, unlike unicellular Amoeba and Chlamydomonas.", "Plant Kingdom"),
        ("In bryophytes (mosses and liverworts), the sex organs (antheridia and archegonia) are produced on the _____.",
         "protonema", "sporophyte", "gametophyte generation", "rhizoid", 2,
         "The dominant green leafy plant in bryophytes is the haploid gametophyte, which produces gametes in specialized gametangia.", "Bryophytes"),
        ("Seed plants (Spermatophytes) are the most dominant, successful vegetation on dry land because of _____.",
         "their motile gametes", "their ability to photosynthesize", "independent water-free fertilization and efficient seed dispersal", "availability of water", 2,
         "Pollen tubes eliminate reliance on external water for fertilization, and resistant seeds protect and disperse the dormant embryo.", "Plant Evolution"),
        ("Which of the following is an arboreal animal specially adapted for living among tree canopies?",
         "Elephant", "Fish", "Antelope", "Bird (canopy bird/monkey)", 3,
         "Birds and primates possess grasping feet, wings, prehensile digits, and balance adaptations for canopy locomotion.", "Ecology"),
        ("In the transverse section of a dicotyledonous root, the central star-shaped vascular tissue labelled I is the _____.",
         "xylem", "phloem", "root hairs", "cortex", 0,
         "In dicot roots, primary xylem forms a solid central star-shaped core radiating arms into the surrounding phloem bundles.", "Plant Anatomy"),
        ("The diagram showing a central star of xylem surrounded by phloem in the stele is the transverse section of a _____.",
         "monocotyledonous stem", "dicotyledonous stem", "monocotyledonous root", "dicotyledonous root", 3,
         "A central radial vascular bundle with 3-5 xylem arms and alternating phloem without a central pith is diagnostic of a dicot root.", "Root Anatomy"),
        ("The dental formula i 2/1, c 0/0, pm 3/2, m 3/3 represents that of a _____.",
         "omnivore", "detritus feeder", "carnivore", "herbivore (rodent/rabbit)", 3,
         "Absence of canines (canine 0/0) producing an anterior diastema gap alongside chisel incisors is characteristic of herbivorous gnawing mammals.", "Dentition"),
        ("A specialized circulatory system is essential in large multicellular mammals but not in single-celled organisms like Amoeba because _____.",
         "Amoeba lives in freshwater", "diffusion is sufficient over microscopic intracellular distances in Amoeba", "Amoeba lacks blood containing haemoglobin", "Amoeba exhibits anaerobic respiration", 1,
         "Amoeba's high surface area to volume ratio allows simple molecular diffusion across the cell membrane to meet metabolic demands.", "Transport Systems"),
        ("In vascular plants, sieve tubes and companion cells are the functional conducting elements of the _____.",
         "cambium", "cortex", "xylem", "phloem", 3,
         "Phloem consists of enucleated sieve tube elements intimately supported by nucleated companion cells that drive active translocation.", "Phloem Physiology"),
        ("The microscopic stomatal pores of plant leaves are analogous in respiratory gas exchange function to the _____.",
         "pharynx of humans", "scales of fish", "spiracles of insects", "trachea of toads", 2,
         "Insect spiracles are lateral valve-controlled body wall pores admitting air into the tracheal system, functionally identical to leaf stomata.", "Comparative Respiration"),
        ("The physiological use of thin, moist, vascularized skin for respiratory gas exchange in amphibians is known as _____.",
         "cellular respiration", "cutaneous respiration", "buccal respiration", "pulmonary respiration", 1,
         "Cutaneous respiration allows oxygen and carbon dioxide diffusion directly across the vascularized glandular epidermis of toads and frogs.", "Respiration in Amphibians"),
        ("Excess water in terrestrial plants is lost as water vapour predominantly through the physiological process of _____.",
         "diffusion", "osmosis", "evaporation", "transpiration", 3,
         "Transpiration is the evaporative loss of water vapour from plant shoot surfaces, predominantly through open foliar stomata.", "Transpiration"),
        ("An example of a specialized subterranean organ of perennation and vegetative propagation in plants is a _____.",
         "rhizome (e.g. ginger)", "seed", "petal of a flower", "calyx of flower", 0,
         "A rhizome is a horizontal underground modified stem storing nutrient reserves to survive winter or dry seasons.", "Perennation"),
        ("A distinct alternation of heteromorphic multicellular generations (gametophyte and sporophyte) is clearly exhibited in _____.",
         "mosses (Bryophytes)", "fungi", "grasses", "conifers", 0,
         "Mosses exhibit a prominent haploid leafy gametophyte alternating with a dependent diploid stalked capsule sporophyte.", "Plant Life Cycles"),
        ("Which of the following statements correctly describes the growth pattern in plants? (I. Growth is mainly apical, II. Specific with definite shape, III. Growth continues throughout life)",
         "I, II and III only", "II and III only", "I and II only", "I and III only", 3,
         "Plant growth is localized to apical/lateral meristems (I) and indeterminate, continuing throughout life (III), unlike fixed determinate animal growth (II).", "Plant Growth"),
        ("Coordination and homeostatic regulation of physiological activities in mammals are achieved synergistically by the _____.",
         "nerves and muscles", "nervous system and endocrine hormones", "nerves only", "hormones only", 1,
         "Rapid targeted responses are mediated by the nervous system, while sustained metabolic control is governed by endocrine hormones.", "Coordination"),
        ("The cerebellum of the mammalian brain coordinates and regulates _____.",
         "autonomic reflex action", "muscular activity, posture and balance", "emotional expressions", "the Endocrine system", 1,
         "The cerebellum processes proprioceptive feedback to ensure smooth voluntary muscle coordination, balance, and spatial equilibrium.", "Central Nervous System"),
        ("The part of the mammalian brainstem responsible for regulating involuntary peristalsis and breathing is the _____.",
         "Olfactory Lobe", "Medulla Oblongata", "Hypothalamus", "Thalamus", 1,
         "The medulla oblongata controls vital autonomic centres including cardiac rate, respiratory rhythm, vasomotor tone, and gastrointestinal peristalsis.", "Brain Anatomy"),
        ("Which of the following meteorological instruments is used to measure atmospheric pressure?",
         "Hydrometer", "Hygrometer", "Thermometer", "Barometer", 3,
         "A mercury or aneroid barometer measures atmospheric pressure in millimetres of mercury (mmHg) or hectopascals.", "Ecological Instruments"),
        ("The physical and chemical influence of soil properties on living organisms in a terrestrial habitat is referred to as _____.",
         "edaphic factors", "physiographic factors", "biotic factors", "topographic factors", 0,
         "Edaphic ecological factors relate to soil texture, pH, humus content, moisture, aeration, and mineral availability.", "Ecology"),
        ("The complete genetic constitution and allelic combination of an organism is described as its _____.",
         "allele", "chromosome", "phenotype", "genotype", 3,
         "Genotype is the specific genetic composition of an individual, distinct from its observable physical phenotype.", "Genetics"),
        ("The major primary limiting physical factor governing biological productivity in aquatic photic habitats is _____.",
         "food", "temperature", "water", "penetration of sunlight", 3,
         "Light attenuation with depth restricts primary photosynthetic productivity in lakes and oceans to the euphotic zone.", "Aquatic Ecology"),
        ("Which of the following trophic groups of organisms feeds directly on autotrophic green plants?",
         "Primary Consumers (herbivores)", "Secondary Consumers", "Producers", "Decomposers", 0,
         "Herbivores (primary consumers) occupy the second trophic level, grazing directly on photosynthetic producers.", "Food Chains & Trophic Levels"),
        ("A characteristic structural and botanical feature of the tropical rainforest biome is that it _____.",
         "contains trees with narrow needle leaves", "contains an exceptionally large diversity of plant species and dense layered canopy", "contains fewer number of plant species", "has total annual rainfall of less than 50cm", 1,
         "Tropical rainforests exhibit unmatched biodiversity, multi-layered stratifications (emergents, canopy, understorey), buttress roots, and epiphytes.", "Rainforest Biome"),
        ("The scientific study of how and why biological population sizes change over time and space is termed _____.",
         "Population estimation", "Population dynamics", "Population ecology", "Population cycle", 1,
         "Population dynamics investigates birth rates, death rates, migration, and age structures governing population fluctuation.", "Ecology"),
        ("A prolonged and severe dry season lasting 8-9 months is a characteristic climatic feature of the _____.",
         "Sahel Savanna", "Mangrove Swamps", "Sudan Savanna", "Guinea Savanna", 0,
         "The Sahel savanna border zone near the Sahara desert experiences low erratic rainfall (<400mm) and a harsh 8-10 month drought season.", "Vegetation Zones of Nigeria"),
        ("Which of the following is a free-living and symbiotic nitrogen-fixing blue-green alga (cyanobacterium) in soils and wetlands?",
         "Rhizobium", "Nitrosomonas", "Clostridium", "Anabaena", 3,
         "Anabaena azollae contains nitrogenase in specialized heterocysts that fix atmospheric nitrogen gas into ammonium.", "Nitrogen Fixation"),
        ("The soil type with the finest texture and highest water-retaining capacity is _____.",
         "Clayey Soil", "Stoney soil", "Sandy soil", "Loamy Soil", 0,
         "Clay soil particles are microscopic (<0.002 mm), creating minute micropores with immense capillary water-holding capacity.", "Soil Types"),
        ("The causative microbiological agent of Poliomyelitis (infantile paralysis) is a _____.",
         "Virus (Poliovirus)", "Fungus", "Protozoan", "Bacterium", 0,
         "Poliomyelitis is caused by the picornavirus enterovirus (poliovirus) destroying motor neurons in the spinal cord.", "Infectious Diseases"),
        ("An effective method for mitigating urban community noise pollution is _____.",
         "by siting heavy industries and airports away from residential areas", "that fuel should be completely combusted by engines", "by planting trees on both sides of the road", "by wearing ear devices", 0,
         "Zoning heavy machinery, industrial factories, and airports away from population settlements eliminates noise hazards at the planning stage.", "Pollution Control"),
        ("A dangerous toxic constituent of exhaust fumes from petrol and diesel electricity generator sets is _____.",
         "Carbon (II) Oxide (carbon monoxide)", "Water Vapour", "Ozone", "Carbon (IV) Oxide", 0,
         "Incomplete combustion produces colourless, odourless carbon(II) oxide (CO) which binds irreversibly to haemoglobin, causing asphyxiation.", "Air Pollution"),
        ("Which of the following public health statements is true of smallpox (Variola)?",
         "It is transmitted by bacteria", "It can effectively be controlled with antibiotics", "It has been successfully eradicated globally by universal vaccination", "It is a water-borne infection", 2,
         "Smallpox is a viral orthopoxvirus successfully eradicated from the human population through the WHO global vaccination campaign.", "Virology & Public Health"),
        ("An atmospheric gaseous pollutant that contributes significantly to the formation of acid rain is _____.",
         "Nitrogen (IV) Oxide (NO₂)", "Ozone", "Fluorine", "Argon", 0,
         "Nitrogen(IV) oxide dissolves in rain droplets to produce nitrous and nitric acids (HNO₂ and HNO₃), precipitating as acid rain.", "Acid Rain"),
        ("In ciliates like Paramecium, when adults reach physiological senescence after repeated binary fission, vigour is restored by _____.",
         "conjugation", "sporulation", "budding", "regeneration", 0,
         "Conjugation is a sexual process of nuclear reorganization and micronuclear exchange that rejuvenates senescent ciliate clones.", "Protozoan Genetics"),
        ("Whorls, arches, loops and composite patterns are inherited variations in human _____.",
         "Skin colour", "Fingerprint dermatoglyphics", "Hair texture", "Blood groups", 1,
         "Epidermal ridge dermatoglyphics on human fingertips display unique lifelong polygenic discontinuous variation.", "Human Variation"),
        ("A couple has 10 children who are all females. Which of the following best explains this genetic outcome?",
         "Sex determination was by the man's X-bearing sperm fertilizing the ovum in each pregnancy", "The man's sperm count is low", "The woman is not capable of producing male children", "Sex determination was by the man's Y chromosome", 0,
         "Human males produce equal numbers of X and Y sperm. Each fertilization resulted in an X sperm fertilizing the maternal X egg (XX female).", "Sex Determination"),
        ("A natural biological glycoprotein with potent broad-spectrum antiviral and immunostimulatory properties is _____.",
         "Interferon", "enzyme", "antibiotic", "disinfectant", 0,
         "Interferons are signalling cytokines synthesized by virus-infected cells that induce surrounding cells to express antiviral proteins.", "Immunology"),
        ("A primary genetic advantage of outbreeding (crossing unrelated individuals) in agriculture and nature is _____.",
         "pest tolerance", "hybrid vigour and increased disease resistance", "fast growth", "tall height", 1,
         "Outbreeding elevates heterozygosity, masking deleterious recessive alleles and generating heterosis (hybrid vigour and disease hardiness).", "Genetics & Breeding"),
        ("A recipient with blood group AB can safely receive whole or packed red blood cells from donors of blood groups _____.",
         "A, B, AB, and O (universal recipient)", "A, AB and O only", "AB only", "A and B only", 0,
         "Lacking both anti-A and anti-B agglutinins in their serum, group AB individuals can receive compatible erythrocytes from all ABO types.", "Blood Groups"),
        ("The streamlined fusiform hydrodynamic body shape of fishes is an adaptation for _____.",
         "Securing mates", "reducing water resistance for easy forward locomotion", "obtaining food", "defence and attack", 1,
         "A spindle-like streamlined body shape minimizes turbulent frictional drag during rapid swimming in dense water.", "Aquatic Adaptations"),
        ("An example of an ectothermic (poikilothermic) cold-blooded terrestrial vertebrate is the _____.",
         "Lizard (Reptilia)", "Cockroach", "Rabbit (Mammalia)", "Bird (Aves)", 0,
         "Reptiles like lizards cannot generate metabolic heat to maintain a constant body temperature and rely on environmental basking.", "Thermoregulation"),
        ("The concept that all living organisms are engaged in a perpetual 'struggle for existence' due to geometric reproduction and limited resources was proposed by _____.",
         "Thomas Morgan", "Charles Darwin", "Jean-Baptiste Lamarck", "Alfred Russel Wallace", 1,
         "Charles Darwin identified the struggle for existence as the primary ecological driving force behind natural selection.", "Evolution"),
        ("The diversification of homologous anatomical structures into different forms to exploit diverse ecological niches (e.g. mammalian pentadactyl limbs) illustrates _____.",
         "adaptive radiation", "dentition in mammals", "wings in birds and bats", "appendages in insects", 0,
         "Adaptive radiation is the rapid divergent evolutionary divergence of an ancestral archetype into specialized descendent adaptations.", "Adaptive Radiation")
    ]
    for idx, item in enumerate(pt4_data, 1):
        q, a, b, c, d, ans, exp, topic = item
        questions.append({
            "id": f"jamb_bio_pt4_{idx:02d}", "subject": "Biology", "topic": topic, "year": "PT. 4",
            "text": q, "a": a, "b": b, "c": c, "d": d, "ans": ans, "exp": exp,
            "label": f"JAMB Biology PT.4 • Q{idx}"
        })

    # -------------------------------------------------------------
    # PART 5 (Questions 1 to 50)
    # -------------------------------------------------------------
    pt5_data = [
        ("Which of the following organisms possesses the most primitive, simplest respiratory mechanism?",
         "insect", "fish", "snail", "mouse", 2,
         "Gastropod snails utilize simple pallial lung cavities or primitive ctenidia, less complex than arthropod tracheal networks or vertebrate lungs.", "Comparative Respiration"),
        ("One morphological adaptation shown by submerged hydrophytes in freshwater habitats is the _____.",
         "waxy cuticle on shoot surface", "poor development of roots and xylem vascular tissues", "well-developed roots and supporting system", "leaves reduced to spines", 1,
         "Surrounded by water, hydrophytes do not require extensive water-absorbing root systems or lignified vascular xylem.", "Plant Adaptations"),
        ("Which of the following organisms relies on cutaneous diffusion across its body wall as its primary method of gaseous exchange?",
         "grasshopper", "rat", "lizard", "earthworm", 3,
         "The earthworm possesses no specialized respiratory organs and absorbs oxygen directly across its moist, vascularized skin.", "Respiration"),
        ("The evolutionary hypothesis that muscular enlargement acquired through athletic exercise is inherited by offspring was formulated by _____.",
         "Mendel", "Darwin", "Lamarck", "Pasteur", 2,
         "Jean-Baptiste Lamarck proposed the inheritance of acquired traits developed through lifetime usage of bodily organs.", "History of Evolution"),
        ("The single circular chromosome of prokaryotic organisms in the kingdom Monera is situated directly within the _____.",
         "nucleoplasm", "nucleus", "nucleolus", "cytoplasm (nucleoid region)", 3,
         "Prokaryotes lack a nuclear membrane; their double-stranded circular DNA chromosome floats freely in the cytoplasm.", "Cell Biology"),
        ("In Nigeria, the halophytic mangrove swamp vegetation belt is geographically restricted to the _____.",
         "Sahel savanna", "Guinea savanna", "coastal zone of the Tropical rainforest", "Sudan savanna", 2,
         "Mangrove tidal swamps extend along the saline estuaries and barrier lagoons of the southern Atlantic coastline.", "Ecological Zones"),
        ("The mammalian pancreas secretes exocrine enzymes for the enzymatic digestion of _____.",
         "fats, proteins and carbohydrates", "fats, vitamins and cellulose", "fats, carbohydrates and vitamins", "proteins, cellulose and minerals", 0,
         "Pancreatic juice contains lipase (for lipids), trypsinogen/chymotrypsin (for proteins), and pancreatic amylase (for starch).", "Digestion"),
        ("The causative pathogen of avian influenza (bird flu) is a _____.",
         "protozoan", "virus (Influenza A virus)", "bacterium", "fungus", 1,
         "Avian influenza is an acute viral disease caused by Influenza A virus subtypes (e.g. H5N1, H5N8).", "Veterinary Pathology"),
        ("An external liquid water film medium is obligatorily necessary for flagellated sperm fertilization in _____.",
         "conifers", "angiosperms", "ferns (Pteridophytes)", "fungi", 2,
         "Fern antherozoids possess flagella and must swim through a film of free water to reach the archegonial egg.", "Pteridophyte Reproduction"),
        ("A classic example of a sex-linked hereditary trait in human genetics is _____.",
         "red-green colour blindness / haemophilia", "ability to roll the tongue", "possession of facial hair in adult humans", "ability to grow long hair in females", 0,
         "Red-green colour blindness and haemophilia are controlled by recessive genes carried on the X chromosome.", "Sex-Linked Inheritance"),
        ("In which of the following Nigerian states can true montane cloud forest and grassland vegetation be found?",
         "Bauchi", "Plateau", "Taraba (Mambilla Plateau)", "Enugu", 2,
         "The high-altitude Mambilla Plateau in Taraba State rises above 1,500m, supporting afro-montane vegetation.", "Biogeography of Nigeria"),
        ("Which of the following biological statements is true regarding somatic cell nuclear transfer cloning?",
         "it is welcomed as an ethically and normally sound science", "it involves the asexual multiplication of the genetic makeup of the original donor organism", "the clone is similar to but not exactly like the original organism", "only one cell of the original organism is needed to initiate the process", 1,
         "Cloning produces genetically identical offspring by transferring a somatic donor nucleus into an enucleated oocyte.", "Biotechnology"),
        ("The biological process of shedding the rigid outer chitinous exoskeleton to accommodate larval growth in arthropods is known as _____.",
         "ecdysis (moulting)", "instar formation", "metamorphosis", "osmosis", 0,
         "Ecdysis is the periodic shedding of the cuticular exoskeleton regulated by ecdysone hormone.", "Arthropod Development"),
        ("Which of the following dietary deficiencies is a major predisposing cause of constipation in humans?",
         "lack of dietary fibre (roughage)", "vitamin B deficiency", "vitamin E deficiency", "lack of mineral salts", 0,
         "Indigestible cellulose fibre (roughage) provides intestinal bulk, stimulating propulsive peristaltic contractions.", "Nutrition"),
        ("In mammals, the endocrine gland situated immediately superior to the cranial pole of each kidney is the _____.",
         "adrenal gland (suprarenal gland)", "prostate gland", "pancreas", "thyroid gland", 0,
         "The paired adrenal glands cap the superior surface of the kidneys, secreting adrenaline, aldosterone, and cortisol.", "Endocrine System"),
        ("The definitive forensic identification of a criminal suspect in biological assault cases is carried out by _____.",
         "RNA analysis", "blood group test", "behavioural traits test", "DNA profiling (fingerprinting)", 3,
         "DNA profiling analyzes polymorphic Short Tandem Repeats (STRs) to provide individualized genetic identification.", "Forensic Biology"),
        ("An example of a freshwater dipnoan fish that aestivates inside a subterranean dried mud cocoon during dry seasons is the _____.",
         "croaker", "African lungfish (Protopterus)", "shark", "catfish", 1,
         "Protopterus burrows into mud, secretes a protective mucous cocoon, and breathes atmospheric air using lungs until rains return.", "Animal Adaptations"),
        ("The physiological mechanism regulating the opening and closing of foliar stomata depends directly on _____.",
         "respiration", "osmotic turgor changes in guard cells", "diffusion", "transpiration", 1,
         "Active potassium ion uptake into guard cells lowers water potential, causing endosmosis, turgidity, and pore opening.", "Stomatal Physiology"),
        ("Which of the following biological characteristics is common to the mosquito, housefly, and blackfly?",
         "they are parasites of man", "their immature stages are aquatic", "they undergo complete metamorphosis (holometabolous)", "their adults have two pairs of wings", 2,
         "Dipterans (true flies and mosquitoes) undergo complete metamorphosis through egg, larva, pupa, and adult stages.", "Entomology"),
        ("The sensory facial vibrissae (whiskers) of nocturnal burrowing giant African pouched rats function as organs of _____.",
         "olfaction", "vision", "tactile mechanoreception (touch)", "auditory balance", 2,
         "Vibrissae are specialized tactile hairs connected to sensory mechanoreceptors, guiding navigation in dark burrows.", "Sense Organs"),
        ("Soil sample: Crucible alone = 5g, Crucible + fresh soil = 10g (soil = 5g). Heated at 100°C, cooled weight = 8g. Soil loss = 10 - 8 = 2g. The fraction / percentage of water in the soil is _____.",
         "0.8", "0.4 (40%)", "0.2", "0.6", 1,
         "Mass of fresh soil = 10 - 5 = 5 g. Mass of water evaporated = 10 - 8 = 2 g. Percentage = 2 / 5 = 0.40 (40%).", "Soil Experiments"),
        ("The astringent chemical waste product of plants extracted from bark and used in tanning hides to leather is _____.",
         "alkaloid", "resin", "tannin", "gum", 2,
         "Tannins are complex polyphenolic plant secondary metabolites that precipitate animal skin gelatin, yielding durable leather.", "Plant Secondary Metabolites"),
        ("The correct anatomical sequence of the passage of fluid and urea during urine formation in the nephron is _____.",
         "glomerulus → Bowman's capsule → convoluted tubule → Henle's loop → collecting tubule", "convoluted tubule → glomerulus → Henle's loop → Bowman's capsule → collecting tubule", "glomerulus → Bowman's capsule → collecting tubule → Henle's loop", "convoluted tubule → Bowman's capsule → Henle's loop → collecting tubule", 0,
         "Glomerular filtrate passes into Bowman's capsule, moves through the proximal convoluted tubule, loop of Henle, distal convoluted tubule, and collecting duct.", "Nephron Physiology"),
        ("In male Agama lizards, the rhythmic lowering and flashing of the brightly coloured gular dewlap fold is used to _____.",
         "defend territory and display dominance / attract mates", "frighten predators", "regulate body moisture", "catch flying insects", 0,
         "Gular dewlap extension displays territorial dominance to rival males and functions as courtship signalling.", "Animal Behaviour"),
        ("The essential photosynthetic pigments present in eukaryotic plant thylakoids include _____.",
         "chloroplast and cytochromes", "melanin and haemoglobin", "chlorophylls and accessory carotenoids", "carotenoids and haemoglobin", 2,
         "Thylakoid membranes contain green chlorophyll a and b alongside accessory carotenoids (carotenes and xanthophylls).", "Photosynthesis"),
        ("The highest, most inclusive level of ecological organization in the living biosphere is the _____.",
         "ecosystem", "niche", "biosphere", "population", 2,
         "The biosphere is the global aggregate of all biomes, ecosystems, and living organisms interacting with Earth's lithosphere, hydrosphere, and atmosphere.", "Ecological Hierarchy"),
        ("A biotic living factor that critically limits the geographical distribution and abundance of organisms in a terrestrial habitat is _____.",
         "soil pH", "interspecific competition and predation", "ambient temperature", "solar light intensity", 1,
         "Biological factors like competition, predation, parasitism, and disease vectors represent biotic constraints on species populations.", "Ecology"),
        ("The optical refractive eye defect that arises because the corneal surface is not curved symmetrically in all meridians is _____.",
         "astigmatism", "short-sightedness (myopia)", "long-sightedness (hypermetropia)", "presbyopia", 0,
         "Astigmatism occurs when irregular corneal curvature prevents light rays from focusing onto a single sharp point on the retina.", "Sense Organs: Eye"),
        ("Which of the following ecological relationships represents a clear example of parasitism?",
         "a squirrel living in an abandoned nest of a bird", "mistletoe growing on and drawing nutrients from an orange tree", "fungi decomposing a dead fallen tree branch", "cattle egrets feeding on ticks from the body of cattle", 1,
         "Mistletoe is a plant parasite that penetrates the vascular cylinder of citrus trees using haustoria to extract sap.", "Ecological Interactions"),
        ("The correct increasing order of particle size in the following soil classification types is _____.",
         "clay → silt → sand → gravel", "clay → sand → silt → gravel", "silt → clay → sand → gravel", "sand → silt → clay → gravel", 0,
         "Soil particles increase in diameter from clay (<0.002 mm), to silt (0.002-0.05 mm), to sand (0.05-2.0 mm), to gravel (>2.0 mm).", "Soil Science"),
        ("Which of the following environmental crises can trigger severe competition for resources within an animal population?",
         "emigration", "severe drought", "mortality", "dispersion", 1,
         "Drought drastically depletes water and forage vegetation, intensifying competitive struggle among surviving herbivores.", "Ecology"),
        ("Stunted shoot growth, purple foliage discolouration, and poor root development in crops are diagnostic symptoms of a deficiency in _____.",
         "phosphorus", "calcium", "sulphur", "iron", 0,
         "Phosphorus is essential for nucleic acids and ATP; deficiency stunts root establishment and impairs energy metabolism.", "Plant Mineral Nutrition"),
        ("In eukaryotic cells, the organelle solely responsible for aerobic cellular respiration and ATP synthesis is the _____.",
         "nucleus", "nucleolus", "endoplasmic reticulum", "mitochondrion", 3,
         "Mitochondria carry out pyruvate decarboxylation, the Krebs citric acid cycle, and electron transport phosphorylation.", "Cell Organelles"),
        ("In the diagram of a eukaryotic plant cell, the organelle responsible for storing genetic hereditary information is labelled _____.",
         "IV", "I", "II (Nucleus)", "III", 2,
         "The cell nucleus stores the nuclear genome and directs protein synthesis and hereditary inheritance.", "Cell Biology"),
        ("In the Rhizopus diagram, the process illustrated where two opposite sexual hyphae (+ and -) fuse gametangia is _____.",
         "gametogenesis", "sexual reproduction in Rhizopus (conjugation)", "sexual reproduction in Spirogyra", "sporulation", 1,
         "Heterothallic conjugation between compatible mycelia forms a resistant, thick-walled diploid zygospore.", "Fungal Reproduction"),
        ("In the Rhizopus sexual reproduction diagram, the thick-walled resistant resting spore labelled I is the _____.",
         "zygospore", "conidiophore", "sporangium", "hypha", 0,
         "The zygospore survives drought and adverse environmental extremes before germinating to produce a sporangium.", "Mycology"),
        ("In Paramecium, the specialized organelle responsible for sexual genetic exchange during conjugation is the _____.",
         "macronucleus", "micronucleus", "oral groove", "contractile vacuole", 1,
         "The diploid micronucleus undergoes meiosis and reciprocal gametic exchange during sexual conjugation.", "Protozoan Reproduction"),
        ("In the Paramecium diagram, the star-shaped pulsating vacuole labelled IV is responsible for _____.",
         "respiration", "ingestion", "locomotion", "osmoregulation (water expulsion)", 3,
         "Contractile vacuoles collect excess water that endosmoses into the hypotonic cell and pump it out to prevent cytolysis.", "Osmoregulation"),
        ("In the diagram of the mammalian heart, the massive systemic blood vessel labelled I arching from the left ventricle is the _____.",
         "pulmonary artery", "bicuspid valve", "systemic aorta", "vena cava", 2,
         "The aorta distributes oxygenated blood under high pressure from the left ventricle throughout the systemic circulation.", "Cardiovascular System"),
        ("Oxygenated arterial blood is pumped out to the entire systemic body from the chamber of the heart labelled _____.",
         "Right atrium", "Right ventricle", "Left atrium", "Left ventricle", 3,
         "The thick-walled left ventricle generates the systolic pressure required to propel oxygenated blood into the aorta.", "Heart Anatomy"),
        ("The botanical experiment where germinating seedlings are rotated on a clinostat is designed to demonstrate _____.",
         "hydrotropism", "phototropism", "geotropism (gravitropism)", "thigmotropism", 2,
         "A rotating clinostat neutralizes gravitational pull equally on all sides, preventing geotropic curving of radicle and plumule.", "Plant Tropisms"),
        ("In a horizontally positioned seedling undergoing gravitropism, the lower side of the shoot tip marked I accumulates a high concentration of _____.",
         "ethylene", "abscisic acid", "auxin", "ascorbic acid", 2,
         "Auxin migrates downward under gravity; high auxin concentration on the lower shoot flank accelerates elongation, bending the shoot upward.", "Auxin Transport"),
        ("The characteristic mating clasp and breeding posture in anurans (frogs and toads) illustrated in the diagram is known as _____.",
         "reproductive swimming", "amplexus", "mating", "courtship", 1,
         "During amplexus, the male toad clasps the female's dorsum, stimulating simultaneous shedding of eggs and sperm into water.", "Amphibian Reproduction"),
        ("The diagram showing eggs extruded and fertilized externally in water confirms that toads and frogs are _____.",
         "viviparous", "hermaphroditic", "ovoviviparous", "oviparous", 3,
         "Oviparous animals lay eggs that develop and hatch externally in the environment.", "Reproductive Strategies"),
        ("In human endocrine physiology, insulin is synthesized and secreted by the beta cells of the endocrine organ labelled _____.",
         "liver", "stomach", "pancreas (Islets of Langerhans)", "kidney", 2,
         "Islets of Langerhans in the pancreas secrete insulin to facilitate glucose uptake and lower blood sugar levels.", "Endocrinology"),
        ("Tail docking in dogs: If dog II lost its tail surgically in an accident and mates with normal dog III, what proportion of their offspring will be born tailless?",
         "all offspring will be born without tails", "3/4 will be born without tails", "none of the offspring will be born without a tail (all will have tails)", "1/4 will be born without tails", 2,
         "Somatic amputations and acquired physical injuries do not alter germline DNA and are never inherited by offspring.", "Inheritance Principles"),
        ("If dogs are offspring of a monohybrid cross where gene G (grey head) is dominant over g, the individual homozygous recessive genotype is _____.",
         "GG", "Gg", "gG", "gg", 3,
         "Homozygous recessive individuals carry two identical copies of the non-dominant allele (gg).", "Genetics"),
        ("In the rodent diagram, the countershading dorsal-ventral colour differentiation represents an adaptation for _____.",
         "flash coloration", "countershading colouration", "warning colouration", "disruptive colouration", 1,
         "Countershading (dark dorsal, light ventral) minimizes shadows and obscures body contours against natural backgrounds.", "Protective Coloration"),
        ("In the rodent diagram, the long facial sensory whiskers labelled I (vibrissae) are structurally specialized for _____.",
         "tactile mechanoreception (touch)", "radiosensitivity", "photosensitivity", "chemoreceptive olfaction", 0,
         "Vibrissae are tactile organs with sensitive nerve endings at their base that detect physical obstacles in darkness.", "Sensory Organs")
    ]
    for idx, item in enumerate(pt5_data, 1):
        q, a, b, c, d, ans, exp, topic = item
        questions.append({
            "id": f"jamb_bio_pt5_{idx:02d}", "subject": "Biology", "topic": topic, "year": "PT. 5",
            "text": q, "a": a, "b": b, "c": c, "d": d, "ans": ans, "exp": exp,
            "label": f"JAMB Biology PT.5 • Q{idx}"
        })

    return questions
