# coding=utf-8
import os, sys

out_path = "app/src/main/java/com/example/data/repository/JambGovernment2010to2018CompleteOfficialBank.kt"

def esc(text):
    if not text:
        return ""
    return str(text).replace('\\', '\\\\').replace('"', '\\"').replace('$', '\\$').replace('\n', '\\n')

# 2010 Government Questions (50 Qs)
g2010 = [
    ("jamb_gov_2010_01", "Which Government Question Paper Type is given to you?", "Type A", "Type B", "Type C", "Type D", 1, "Paper Type B specified on official examination sheet.", "General Examination Structure", "2010"),
    ("jamb_gov_2010_02", "Nation-state is synonymous with", "self-actualization", "sovereignty", "liberation", "nationalism", 1, "A nation-state is a sovereign political entity characterized by recognized self-governance and sovereignty.", "Basic Concepts of Government", "2010"),
    ("jamb_gov_2010_03", "A fundamental component of political culture is", "social values", "family values", "community structure", "economic values", 0, "Political culture is grounded in the prevailing social and civic values, beliefs, and attitudes of a society.", "Political Culture", "2010"),
    ("jamb_gov_2010_04", "A form of oligarchy in which gifted people are at the helm of affairs is", "aristocracy", "theocracy", "plutocracy", "gerontocracy", 0, "Aristocracy is traditionally defined as governance by the best, most virtuous, or gifted citizens.", "Forms of Government", "2010"),
    ("jamb_gov_2010_05", "A state that is ruled by an elected citizen is", "a monarchy", "a plutocracy", "a republic", "an empire", 2, "A republic is a state where supreme power rests in the body of citizens entitled to vote and is exercised by elected representatives.", "Forms of Government", "2010"),
    ("jamb_gov_2010_06", "A true democracy in the modern sense exists where the", "elected representatives rule", "majority of the people rule", "majority of the people vote", "elite rules", 0, "Representative democracy functions where elected representatives enact laws and govern on behalf of the citizenry.", "Democracy", "2010"),
    ("jamb_gov_2010_07", "In a parliamentary system, when the legislature passes a vote of no confidence on the executive, it means that the", "executive is expected to go on suspension", "legislature ceases to trust the executive", "executive is required to resign", "legislature commences legal proceeding against the executive", 2, "A vote of no confidence forces the prime minister and cabinet to tender their resignation.", "Parliamentary System", "2010"),
    ("jamb_gov_2010_08", "The legislative body of the United States of America is the", "Parliament", "National Assembly", "Congress", "Council", 2, "The bicameral federal legislature of the United States is the US Congress (Senate and House of Representatives).", "Organs of Government", "2010"),
    ("jamb_gov_2010_09", "Unicameralism is a feature of the legislature in", "Israel", "the United States", "the United Kingdom", "Ghana", 0, "Israel's parliament (the Knesset) is a single-chamber (unicameral) legislative body.", "Legislature", "2010"),
    ("jamb_gov_2010_10", "The upper house in most federal systems is created to", "ensure equality of federating units", "prevent excesses of the executive", "oversee and check the lower house", "enable experienced elders make inputs to governance", 0, "In federations like Nigeria and the USA, the upper house (Senate) provides equal representation to all states regardless of population.", "Federalism", "2010"),
    ("jamb_gov_2010_11", "In which of the following systems is the power of the component units more than that of the central government?", "Monarchical", "Federal", "Unitary", "Confederal", 3, "In a confederation, sovereign power is retained primarily by the autonomous component units while the central authority is weak.", "Systems of Government", "2010"),
    ("jamb_gov_2010_12", "One of the general tenets of fascist doctrine is that the leader is", "supreme relative to the constitution", "weak relative to the constitution", "subordinate to the laws of the state", "subordinate to the norms of the society", 0, "Fascism rejects constitutional limitations and asserts that the totalitarian leader embodies supreme, unchecked will.", "Political Ideologies", "2010"),
    ("jamb_gov_2010_13", "In a cabinet system of government, executive power is exercised by the", "head of government", "monarch", "president", "dominant party", 0, "In a cabinet (parliamentary) system, real executive authority is directed by the Prime Minister as head of government.", "Cabinet System", "2010"),
    ("jamb_gov_2010_14", "The principle of separation of powers is best practiced in the", "presidential system", "parliamentary system", "monarchical system", "feudal system", 0, "The presidential system enforces a strict constitutional separation of personnel and powers among executive, legislative, and judicial organs.", "Separation of Powers", "2010"),
    ("jamb_gov_2010_15", "A typical form of delegated legislation is", "an act", "a bill", "a decree", "a bye-law", 3, "Bye-laws enacted by local government councils or statutory authorities are classic delegated legislation.", "Delegated Legislation", "2010"),
    ("jamb_gov_2010_16", "The rights of a citizen can be withdrawn by the state if the person", "opposes the government violently", "leaves the country permanently", "is convicted of a serious crime", "is pronounced dead", 2, "Conviction for major felonies results in forfeiture of certain fundamental civil and political liberties.", "Citizenship and Rights", "2010"),
    ("jamb_gov_2010_17", "An electoral process in which candidates are selected for elective offices by party members is", "primary election", "electoral college", "bye election", "general election", 0, "Primary elections are internal party balloting processes whereby party members select their official general election flagbearers.", "Elections and Electoral Systems", "2010"),
    ("jamb_gov_2010_18", "In theory one major advantage of the one-party system is that it", "eliminates intra-party conflict", "serves as an instrument of national integration", "promotes greater mass participation in government", "guarantees social justice", 1, "Advocates argue that a single national party can unite diverse multi-ethnic populations without divisive electoral factions.", "Party Systems", "2010"),
    ("jamb_gov_2010_19", "A tactic employed by pressure groups to achieve their objectives is", "memorandum", "electioneering campaign", "propaganda", "lobbying", 3, "Lobbying involves directly persuading legislators and policymakers to enact favorable legislation.", "Pressure Groups", "2010"),
    ("jamb_gov_2010_20", "Public opinion can be measured through", "negotiation", "referendum", "strike action", "rumour", 1, "A referendum is a formal public ballot measuring citizen consensus on specific constitutional or policy propositions.", "Public Opinion", "2010"),
    ("jamb_gov_2010_21", "Which of the following is the main function of the civil service?", "Implementing government policies", "Allocating resources to the federating units", "Supporting the party in power", "Mobilizing grass root support for government", 0, "The civil service executes, administers, and operationalizes approved state laws and government policies.", "Civil Service", "2010"),
    ("jamb_gov_2010_22", "Who was the political head of the Old Oyo Empire?", "Bashorun", "Oyomesi", "Aremo", "Alaafin", 3, "The Alaafin of Oyo was the supreme political monarch of the pre-colonial Oyo Empire.", "Pre-Colonial Administration", "2010"),
    ("jamb_gov_2010_23", "The Igbo political system was based on", "age grades", "Umunna", "family ties", "Umuada", 0, "Age grades played vital roles in law enforcement, defense, public works, and administrative decisions in pre-colonial Igbo society.", "Pre-Colonial Administration", "2010"),
    ("jamb_gov_2010_24", "The Aro age-grade system in Igbo land was", "a religious organization", "a political organization", "a commercial organization", "an imperial organization", 0, "The Aro system derived its prestige from the renowned Ibini Ukpabi oracle and spiritual arbitration network.", "Pre-Colonial Administration", "2010"),
    ("jamb_gov_2010_25", "France introduced the policy of assimilation in her colonies primarily to", "teach them the art of leadership", "give them a sound education", "change their way of life", "discourage them from ritual killings", 2, "Assimilation aimed to culturally transform Africans into French citizens adopt French language, laws, and customs.", "Colonial Administration", "2010"),
    ("jamb_gov_2010_26", "The foremost British trading company on the West African coast was", "Royal Niger Company", "United African Company", "Lever Brothers", "John Holt and Sons", 0, "Sir George Goldie's Royal Niger Company received a royal charter in 1886 to administer and commercially dominate the Niger basin.", "Colonial Administration", "2010"),
    ("jamb_gov_2010_27", "Which of these rulers resisted colonial rule and was deported to Calabar?", "King Kosoko", "King Dosunmu", "Oba Ovonramwen", "King Jaja", 2, "Oba Ovonramwen of Benin resisted British commercial conquest during the 1897 expedition and was exiled to Calabar.", "Colonial Resistance", "2010"),
    ("jamb_gov_2010_28", "Nigerian nationalism was described as two-phased by", "John Payne Jackson", "Edward Wilmot Blyden", "James S. Coleman", "David Ricardo", 1, "Edward Wilmot Blyden articulated early cultural and political nationalist philosophy across West Africa.", "Nationalism", "2010"),
    ("jamb_gov_2010_29", "One major weakness of the Independence Constitution is that it", "failed to provide the country with full sovereignty", "gave total independence to Nigeria", "gave full powers to the Supreme Court in Nigeria", "empowered Britain to continue to rule", 0, "The 1960 Constitution retained Queen Elizabeth II as titular Head of State and the British Privy Council as the final appellate court.", "Constitutional History", "2010"),
    ("jamb_gov_2010_30", "The first law-making body in Nigeria after amalgamation was", "Nigerian Council", "National Assembly", "Legislative Council", "Regional Assembly", 0, "Lord Lugard established the advisory Nigerian Council in 1914 following amalgamation.", "Constitutional History", "2010"),
    ("jamb_gov_2010_31", "The designation of ministers as chief executives and accounting officers was recommended by a commission headed by", "Jerome Udoji", "S.J. Cookey", "Simeon Adebo", "Dotun Philips", 3, "The 1988 Civil Service Reorganization Commission led by Prof. Dotun Philips designated ministers as accounting officers.", "Public Administration", "2010"),
    ("jamb_gov_2010_32", "A major shortcoming of the Ombudsman is", "lack of adequate resources", "Lack of clear-cut mandate", "its inability to restrain bureaucratic excesses", "lack of executive power to enforce decisions", 3, "The Public Complaints Commission can investigate and recommend remedies but lacks coercive executive powers to enforce judgments.", "Public Complaints Commission", "2010"),
    ("jamb_gov_2010_33", "One of the strong points of the multiparty Nigeria's Fourth Republic is", "the provision for a bicameral legislature", "wider political participation", "government interference", "wider anti-democracy campaign", 1, "Plurality of political parties fosters broad civic engagement and inclusive political contestation.", "Nigerian Fourth Republic", "2010"),
    ("jamb_gov_2010_34", "In which of the following is the ceremonial and executive powers fused?", "Presidential system of government", "parliamentary system of government", "Federal system of government", "Unitary system of government", 0, "In the presidential system, the President serves concurrently as titular Head of State and executive Head of Government.", "Presidential System", "2010"),
    ("jamb_gov_2010_35", "A major contentious issue confronting Nigerian federalism is", "poverty", "education", "health care delivery", "revenue allocation", 3, "The formula for sharing the Federation Account among federal, state, and local tiers remains intensely debated.", "Nigerian Federalism", "2010"),
    ("jamb_gov_2010_36", "The main purpose of establishing public enterprises in Nigeria is to", "increase government revenue", "provide essential services", "enrich the elite", "compete with the private sector", 1, "State enterprises were incorporated to supply essential utilities and social infrastructure at subsidized rates.", "Public Enterprises", "2010"),
    ("jamb_gov_2010_37", "Parastatals are established to", "enhance entrepreneurial skills", "maximize government profits", "expand business transactions", "render social services", 3, "Parastatals execute specialized socioeconomic mandates and public service functions.", "Public Administration", "2010"),
    ("jamb_gov_2010_38", "The General-Purpose Committee of the local government is the", "cabinet or the local government", "local government public relations unit", "body responsible for supervising self-help projects", "body for awarding contracts", 2, "The General-Purpose Committee coordinates inter-departmental works and supervises community development projects.", "Local Government", "2010"),
    ("jamb_gov_2010_39", "The highest organ of the state during the Babangida Regime was the", "Provisional Ruling Council", "Supreme Military Council", "Armed Forces Ruling Council", "Federal Executive Council", 2, "The Armed Forces Ruling Council (AFRC) exercised supreme decree-making and executive authority under General Babangida.", "Military Rule in Nigeria", "2010"),
    ("jamb_gov_2010_40", "Decree 34 of 1966 was unacceptable to many Nigerians because it was", "seen as an instrument of impoverishment", "perceived to abolish the federal system", "promulgated without consultation with the people", "considered as alien", 1, "Major-General J.T.U. Aguiyi-Ironsi's Unification Decree 34 abolished federal regions in favor of a unitary system, triggering violent backlash.", "Military Decrees", "2010"),
    ("jamb_gov_2010_41", "Nigeria broke diplomatic relations with France in 1961 because of", "France's atomic test in the Sahara Desert", "General de-Gaulle's negative attitude towards her", "her poor relations with the Francophone countries", "France's diplomatic relations with Israel", 0, "Prime Minister Tafawa Balewa expelled the French ambassador after France detonated atmospheric nuclear tests in the Algerian Sahara.", "Nigerian Foreign Policy", "2010"),
    ("jamb_gov_2010_42", "An attribute that Nigeria shares with most non-aligned countries is", "the state of her economy", "her heterogeneous population", "her large population", "her large size", 0, "Non-Aligned Movement members are predominantly developing nations contending with post-colonial economic challenges.", "International Affairs", "2010"),
    ("jamb_gov_2010_43", "Nigeria spearheaded the formation of ECOWAS during the regime of", "Olusegun Obasanjo", "Yakubu Gowon", "Murtala Muhammed", "Ibrahim Babangida", 1, "General Yakubu Gowon and President Gnassingbé Eyadéma of Togo spearheaded the 1975 Treaty of Lagos founding ECOWAS.", "ECOWAS", "2010"),
    ("jamb_gov_2010_44", "Nigeria was classified as a frontline state for", "participating in peacekeeping in the Congo", "supporting the liberation efforts in Southern Africa", "spearheading the formation of African Union", "helping to end the crisis in Liberia", 1, "Despite not sharing a border with South Africa, Nigeria's diplomatic, financial, and logistical support against apartheid earned her honorary Frontline State status.", "Foreign Policy", "2010"),
    ("jamb_gov_2010_45", "The prominent role Nigeria played in the UN in the 70's earned her", "non-permanent membership position Liberia", "membership of the Security Council", "permanent representation at the UN", "chairmanship of the General Assembly", 3, "Nigeria's Joseph Nanven Garba presided over the 44th Session of the United Nations General Assembly.", "United Nations", "2010"),
    ("jamb_gov_2010_46", "The head of Nigeria's foreign mission in a Commonwealth nation is known as", "high commissioner", "charge d'affaires", "ambassador", "attaché", 0, "Diplomatic envoys exchanged between Commonwealth member countries bear the title of High Commissioner.", "Diplomacy", "2010"),
    ("jamb_gov_2010_47", "One major function of the Authority of Heads of State and Government of ECOWAS is", "organizing international conferences", "appointing the Executive Secretary", "appointing staff of the Secretariat", "preparing the budget of the Community", 1, "The supreme decision-making summit of ECOWAS appoints the Executive Secretary (now Commission President).", "ECOWAS", "2010"),
    ("jamb_gov_2010_48", "The tenure of non-permanent members of the Security Council is", "5 years", "2 years", "4 years", "6 years", 1, "The UN General Assembly elects 10 non-permanent Security Council members for staggered two-year terms.", "United Nations", "2010"),
    ("jamb_gov_2010_49", "The Secretary-General of the United Nations is appointed by the", "Security council acting alone", "General Assembly on the recommendation of the Security Council", "Permanent members of the Security Council on the recommendation of the General Assembly", "General Assembly in plenary session", 2, "Under Article 97 of the UN Charter, the Secretary-General is appointed by the General Assembly upon the recommendation of the Security Council.", "United Nations", "2010"),
    ("jamb_gov_2010_50", "The approval of treaties and agreements of the Economic Community of West African States is the responsibility of the", "secretariat", "ECOWAS Tribunal", "Council of Ministers", "Assembly of Heads of State and Government", 3, "The Assembly of Heads of State and Government ratifies and approves all binding regional protocols and treaties.", "ECOWAS", "2010")
]

print(f"Loaded 2010: {len(g2010)} questions.")
