# coding=utf-8
"""
Complete JAMB Chemistry Parts 1 to 5 Data (240 Questions).
Directly transcribed from user's attached JAMB Chemistry Past Questions Objective PT 1-5.
Preserves exact chemical formulas, equations, superscripts, subscripts, and full stoichiometric calculations.
"""

def get_all_chemistry_questions():
    questions = []

    # -------------------------------------------------------------
    # PART 1 (Questions 1 to 50)
    # -------------------------------------------------------------
    pt1_data = [
        ("Which question Paper Type of Chemistry is given to you?", "Type A", "Type B", "Type C", "Type D", 1, "JAMB examination question paper type identifier.", "General Introduction"),
        ("What is the concentration of a solution containing 2g of NaOH in 100cm³ of solution? [Na = 23, O = 16, H = 1]",
         "0.40 mol dm⁻³", "0.50 mol dm⁻³", "0.05 mol dm⁻³", "0.30 mol dm⁻³", 1,
         "Molar mass of NaOH = 23 + 16 + 1 = 40 g mol⁻¹. Moles = 2 / 40 = 0.05 mol. Volume = 100/1000 = 0.1 dm³. Molarity = 0.05 / 0.1 = 0.50 mol dm⁻³.", "Stoichiometry & Concentrations"),
        ("Which of the following properties is NOT peculiar to matter?",
         "kinetic energy of particles increases from solid to gas", "Random motion of particles increases from liquid to gas", "Orderliness of particles increases from gas to liquid", "Random motion of particles increases from gas to solid", 3,
         "Transition from gas to solid involves loss of kinetic energy, decreasing random motion and forming an ordered crystal lattice.", "Kinetic Theory of Matter"),
        ("The principle of column chromatography is based on the ability of the constituents to _____.",
         "move at different speeds in the column", "dissolve in each other in the column", "react with the solvent in the column", "react with each other in the column", 0,
         "Column chromatography separates components based on their differential distribution coefficients and migration speeds through the adsorbent stationary phase.", "Separation Techniques"),
        ("From the PV versus P graph representing real and ideal gases, an ideal gas is represented by _____.",
         "M", "N", "K", "L", 1,
         "For an ideal gas obeying Boyle's Law, the product of pressure and volume (PV) remains strictly constant at constant temperature, producing a horizontal line (N).", "Gas Laws"),
        ("Which of the following is correct about the periodic table?",
         "The non-metallic properties of the elements tend to decrease across each period", "The valence electrons of the elements increase progressively across the period", "Elements in the same group have the same number of electron shells", "Elements in the same period have the same number of valence electrons", 1,
         "Across a period from left to right, the number of valence shell electrons increases progressively from 1 to 8.", "Periodic Table"),
        ("The relative atomic mass of a naturally occurring lithium consisting of 90% ⁷Li and 10% ⁶Li is _____.",
         "6.9", "7.1", "6.2", "6.8", 0,
         "Relative atomic mass = (90 × 7 + 10 × 6) / 100 = (630 + 60) / 100 = 6.9.", "Atomic Structure & Isotopy"),
        ("An isotope has an atomic number of 15 and a mass number of 31. The number of protons it contains is _____.",
         "16", "15", "46", "31", 1,
         "The atomic number (Z) of an atom is defined as the number of protons in its nucleus (Z = 15).", "Atomic Structure"),
        ("The molecular lattice of iodine is held together by _____.",
         "dative bond", "metallic bond", "hydrogen bond", "van der Waals' forces", 3,
         "Solid iodine forms a molecular crystal lattice bound together by weak intermolecular van der Waals forces.", "Chemical Bonding"),
        ("The arrangement of particles in crystal lattices can be studied using _____.",
         "X-rays", "γ-rays", "α-rays", "β-rays", 0,
         "X-ray crystallography uses X-ray diffraction to determine atomic and molecular lattice geometry.", "Crystallography"),
        ("From the solubility curve, find the amount of solute deposited when 200 cm³ of the solution is cooled from 55°C to 40°C (solubility drops from 6.0 to 5.0 mol dm⁻³).",
         "0.10 mole", "0.20 mole", "0.01 mole", "0.02 mole", 1,
         "Change in solubility = 6.0 - 5.0 = 1.0 mol dm⁻³. Amount deposited in 200 cm³ = 1.0 × (200 / 1000) = 0.20 mole.", "Solubility Curves"),
        ("The importance of sodium aluminate (III) in the treatment of water is to _____.",
         "cause coagulation", "neutralize acidity", "prevent goitre and tooth decay", "kill germs", 0,
         "Sodium aluminate hydrolyzes to gelatinous aluminium hydroxide, coagulating suspended fine clay particles during water purification.", "Water Treatment"),
        ("What type of bond exists between an element X with atomic number 12 and Y with atomic number 17?",
         "Electrovalent", "Metallic", "Covalent", "Dative", 0,
         "Element X (Mg, 2,8,2) transfers two valence electrons to two atoms of Y (Cl, 2,8,7), forming an electrovalent (ionic) bond.", "Chemical Bonding"),
        ("Hardness of water is mainly due to the presence of _____.",
         "calcium hydroxide or magnesium hydroxide", "calcium hydrogencarbonate (IV) or calcium tetraoxosulphate (VI)", "sodium hydroxide or magnesium Hydroxide", "calcium chloride or sodium chloride salts", 1,
         "Water hardness is caused by dissolved calcium and magnesium ions, principally Ca(HCO₃)₂ (temporary) and CaSO₄ (permanent).", "Water Hardness"),
        ("A suitable solvent for iodine and naphthalene is _____.",
         "carbon (IV) sulphide", "ethanol", "water", "benzene", 3,
         "Non-polar covalent compounds like iodine and naphthalene dissolve readily in non-polar organic solvents like benzene (C₆H₆).", "Solvents and Solutions"),
        ("Which of the following noble gases is commonly found in the atmosphere?",
         "Xenon", "Neon", "Helium", "Argon", 3,
         "Argon constitutes approximately 0.93% of dry atmospheric air by volume, making it the most abundant noble gas.", "Atmospheric Chemistry"),
        ("N₂O₄(g) ⇌ 2NO₂(g) ΔH = +ve. In the reaction above, an increase in temperature will _____.",
         "increase the value of the equilibrium constant", "decrease the value of the equilibrium constant", "increase in the reactant production", "shift the equilibrium to the left", 0,
         "For an endothermic reaction (ΔH > 0), raising temperature shifts equilibrium toward products, increasing the equilibrium constant K_eq.", "Chemical Equilibrium"),
        ("CH₃COOH(aq) + OH⁻(aq) ⇌ CH₃COO⁻(aq) + H₂O(l). In the reaction above, CH₃COO⁻(aq) is _____.",
         "conjugate base", "acid", "base", "conjugate acid", 0,
         "Under Bronsted-Lowry theory, CH₃COO⁻ is the conjugate base formed when ethanoic acid loses a proton.", "Acids, Bases & Salts"),
        ("How many cations will be produced from a solution of potassium aluminium tetraoxosulphate (VI) [KAl(SO₄)₂]?",
         "3", "4", "1", "2", 3,
         "Potash alum dissociates into two distinct cation species: K⁺ and Al³⁺ (along with SO₄²⁻ anions).", "Double Salts"),
        ("Which of the following is NOT an alkali?",
         "NH₃", "Mg(OH)₂", "Ca(OH)₂", "NaOH", 1,
         "Mg(OH)₂ is an insoluble/sparingly soluble base and does not yield substantial aqueous hydroxide ions to be classified as an alkali.", "Acids, Bases & Salts"),
        ("An effect of thermal pollution on water bodies is that the _____.",
         "volume of water reduces", "volume of chemical waste increase", "level of oxides of nitrogen increase", "level of oxygen reduces", 3,
         "Elevated water temperatures lower the solubility of dissolved oxygen, suffocating aquatic gill-breathing fauna.", "Environmental Pollution"),
        ("Which of the following is a deliquescent compound?",
         "Na₂CO₃", "CaCl₂", "CuO", "Na₂CO₃·10H₂O", 1,
         "Anhydrous calcium chloride (CaCl₂) absorbs atmospheric moisture and dissolves in it to form a saturated solution.", "Deliquescence & Efflorescence"),
        ("A chemical reaction in which the hydration energy is greater than the lattice energy is referred to as _____.",
         "a spontaneous reaction", "an endothermic reaction", "an exothermic reaction", "a reversible reaction", 2,
         "When hydration enthalpy exceeds crystal lattice energy, excess energy is liberated as heat (ΔH_solution < 0, exothermic).", "Thermochemistry"),
        ("The function of zinc electrode in a galvanic cell is that it _____.",
         "undergoes reduction", "serves as the positive electrode", "produces electrons", "uses up electrons", 2,
         "At the zinc anode, Zn(s) undergoes oxidation (Zn → Zn²⁺ + 2e⁻), releasing electrons into the external circuit.", "Electrochemistry"),
        ("CH₄(g) + Cl₂(g) → CH₃Cl(g) + HCl(g). The major factor that influences the rate of the reaction above is _____.",
         "catalyst", "temperature", "concentration", "light", 3,
         "The photochemical chlorination of methane requires ultraviolet light (photons) to initiate free radical homolytic cleavage of Cl₂.", "Hydrocarbons & Kinetics"),
        ("The condition required for corrosion to take place is the presence of _____.",
         "water and carbon (IV) oxide", "water, carbon (IV) oxide and oxygen", "oxygen and carbon (IV) oxide", "water and oxygen", 3,
         "Rusting of iron requires both moisture (water) and atmospheric oxygen.", "Corrosion & Metals"),
        ("In the potential energy profile diagram of an exothermic reaction, X represents the _____.",
         "enthalpy", "enthalpy change", "activation energy", "activated complex", 2,
         "The energy barrier difference between reactants and the transition state peak represents the activation energy (E_a).", "Chemical Kinetics"),
        ("The curve showing rate of reaction decreasing sharply with time illustrates the effect of decrease in _____.",
         "concentration", "temperature", "surface area", "pressure", 0,
         "As reactants are progressively consumed, reactant concentration decreases, lowering collision frequency and reaction rate.", "Reaction Kinetics"),
        ("MnO₄⁻(aq) + Y + 5Fe²⁺(aq) → Mn²⁺(aq) + 5Fe³⁺(aq) + 4H₂O(l). In the equation above, Y is _____.",
         "5H⁺(aq)", "4H⁺(aq)", "10H⁺(aq)", "8H⁺(aq)", 3,
         "Balancing hydrogen and charge in the permanganate redox reaction: MnO₄⁻ + 8H⁺ + 5Fe²⁺ → Mn²⁺ + 5Fe³⁺ + 4H₂O.", "Redox Reactions"),
        ("Given that M is the mass of a substance deposited during electrolysis and Q is the quantity of electricity consumed, then Faraday's first law can be written as _____ [E = Electrochemical equivalent].",
         "M = E / Q", "M = EQ", "M = Q / E", "M = E / 2Q", 1,
         "Faraday's first law of electrolysis states M = zIt = EQ.", "Electrolysis"),
        ("The impurities formed during the laboratory preparation of chlorine gas (HCl fumes) are removed by _____.",
         "H₂O", "NH₃", "H₂SO₄", "HCl", 0,
         "Passing generated chlorine through water dissolves and removes volatile hydrogen chloride (HCl) gas fumes.", "Preparation of Halogens"),
        ("The effect of the presence of impurities such as carbon and sulphur on iron is that they _____.",
         "give it high tensile strength", "make it malleable and ductile", "increase its melting point", "lower its melting point", 3,
         "Dissolved impurities disrupt regular metallic lattices and lower the melting point of pig iron (from 1538°C to ~1150-1200°C).", "Metals & Alloys"),
        ("A few drops of concentrated HNO₃ is added to an unknown solution and boiled for a while. If this produces a brown solution, the cation present is likely to be _____.",
         "Pb²⁺", "Cu²⁺", "Fe³⁺", "Fe²⁺", 3,
         "Concentrated HNO₃ oxidizes pale-green iron(II) ions (Fe²⁺) to reddish-brown iron(III) ions (Fe³⁺).", "Qualitative Analysis"),
        ("The bleaching action of chlorine gas is effective due to the presence of _____.",
         "hydrogen chloride", "water", "air", "oxygen", 1,
         "Chlorine bleaches via nascent oxygen liberated upon reacting with moisture: Cl₂ + H₂O → HCl + HOCl → HCl + [O].", "Halogens"),
        ("In the laboratory preparation of oxygen, dried oxygen is usually collected over _____.",
         "hydrochloric acid", "mercury", "calcium chloride", "tetraoxosulphate (VI) acid", 1,
         "Because dry oxygen dissolves slightly in water, pure dried gas is collected over mercury.", "Non-Metals: Oxygen"),
        ("The property of concentrated H₂SO₄ that makes it suitable for preparing HNO₃ from its salts is its _____.",
         "boiling point", "density", "oxidizing properties", "dehydrating properties", 0,
         "Concentrated H₂SO₄ is a non-volatile acid with a high boiling point (338°C), displacing volatile HNO₃ (b.p. 83°C) upon gentle heating.", "Acids and Bases"),
        ("Bronze is preferred to copper in the making of medals because it _____.",
         "is stronger", "can withstand low temperature", "is lighter", "has low tensile strength", 0,
         "Bronze (copper-tin alloy) is significantly harder, stronger, and more corrosion-resistant than pure copper.", "Alloys"),
        ("The constituent of baking powder that makes dough rise is _____.",
         "NaHCO₃", "NaOH", "Na₂CO₃", "NaCl", 0,
         "Sodium hydrogentrioxocarbonate(IV) (NaHCO₃) reacts with acidic salts upon moistening to release CO₂ gas bubbles.", "Salts & Carbonates"),
        ("Which of the following compounds is used as a gaseous fuel?",
         "CH₃–C≡CH", "CH₃–CH(OH)–CH₃", "CH₃–CH₂–CH₂–COOH", "CH₃–CH₂–CH₂–CH₃", 3,
         "Butane (C₄H₁₀) is an easily liquified, clean-burning hydrocarbon gas used in domestic and industrial cylinder fuel.", "Hydrocarbons: Alkanes"),
        ("The ability of carbon to form long chains and rings is referred to as _____.",
         "alkylation", "acylation", "catenation", "carbonation", 2,
         "Catenation is the linkage of atoms of the same element into longer chains or rings through strong covalent bonds.", "Organic Chemistry"),
        ("Which of the following compounds will undergo addition polymerization reaction?",
         "C₂H₄", "C₂H₅COOH", "C₂H₆", "C₂H₅OH", 0,
         "Ethene (C₂H₄) contains a reactive carbon-carbon double bond, readily undergoing addition polymerization into polythene.", "Polymers"),
        ("The compound CH₃–CH(OH)–COOH (lactic acid) exhibits _____.",
         "geometric isomerism", "optical isomerism", "structural isomerism", "positional isomerism", 1,
         "The central alpha-carbon is asymmetric (chiral), bonded to four distinct groups (-H, -CH₃, -OH, -COOH), conferring optical activity.", "Isomerism"),
        ("An organic compound has an empirical formula CH₂O and vapour density of 45. What is the molecular formula? [C=12, H=1, O=16]",
         "C₃H₇OH", "C₂H₅OH", "C₃H₆O₃", "C₂H₄O₂", 2,
         "Molar mass = 2 × Vapour Density = 2 × 45 = 90 g mol⁻¹. Empirical mass (CH₂O) = 12 + 2 + 16 = 30. Ratio n = 90 / 30 = 3. Molecular formula = C₃H₆O₃.", "Empirical & Molecular Formula"),
        ("C₆H₁₂O₆ → 2C₂H₅OH + 2CO₂ + energy. The reaction represented by the equation above is useful in the production of _____.",
         "propanol", "butanol", "methanol", "ethanol", 3,
         "Anaerobic fermentation of glucose by zymase enzyme in yeast yields ethanol and carbon(IV) oxide.", "Alkanols"),
        ("The number of structural isomers that can be obtained from butane (C₄H₁₀) is _____.",
         "3", "4", "1", "2", 3,
         "Butane has two structural chain isomers: n-butane (CH₃CH₂CH₂CH₃) and 2-methylpropane (isobutane, CH(CH₃)₃).", "Isomerism"),
        ("In the compound CH₃–CH(OH)–CH₂–CH₂Cl, the functional groups present are _____.",
         "alkene and halo-group", "hydroxyl and chloro-group", "alkene and chloro-group", "hydroxyl and halo-group", 1,
         "The molecule contains the -OH (hydroxyl alkanol) and -Cl (chloro alkyl halide) functional groups.", "Functional Groups"),
        ("Which of the following represents a primary amine?",
         "(CH₃)₃N", "CH₃NH₂", "CH₃CONH₂", "(CH₃)₂NH", 1,
         "Methylamine (CH₃NH₂) contains the -NH₂ group bonded to a single alkyl radical, characteristic of primary amines.", "Organic Nitrogen Compounds"),
        ("Two organic compounds K and L were treated with a few drops of Fehling's solutions respectively. K formed a brick red precipitate while L remains unaffected. The compound K is an _____.",
         "alkanol", "alkane", "alkanal", "alkanone", 2,
         "Alkanals (aldehydes) are strong reducing agents that reduce blue alkaline copper(II) tartrate to brick-red Cu₂O precipitate.", "Alkanals & Alkanones"),
        ("Which of the following statements is true about 2-methylpropane and butane?",
         "They are members of the same homologous series", "They have the same boiling point", "They have different number of carbon atoms", "They have the same chemical properties", 0,
         "Both are alkane structural isomers sharing the general formula CnH2n+2 and belonging to the alkane homologous series.", "Alkanes"),
        ("CH₃COOH + C₂H₅OH ⇌ (conc H₂SO₄) CH₃COOC₂H₅ + H₂O. The reaction above is best described as _____.",
         "esterification", "condensation", "saponification", "neutralization", 0,
         "Esterification is the acid-catalyzed condensation of an alkanoic acid with an alkanol to form an ester (alkyl alkanoate) and water.", "Organic Reactions")
    ]
    for idx, item in enumerate(pt1_data, 1):
        q, a, b, c, d, ans, exp, topic = item
        questions.append({
            "id": f"jamb_chm_pt1_{idx:02d}", "subject": "Chemistry", "topic": topic, "year": "PT. 1",
            "text": q, "a": a, "b": b, "c": c, "d": d, "ans": ans, "exp": exp,
            "label": f"JAMB Chemistry PT.1 • Q{idx}"
        })

    # -------------------------------------------------------------
    # PART 2 (Questions 1 to 50)
    # -------------------------------------------------------------
    pt2_data = [
        ("Which Question Paper Type of Chemistry is given to you?", "Type Green", "Type Purple", "Type Red", "Type Yellow", 2, "JAMB examination question paper type identifier.", "General Introduction"),
        ("Which of the following methods can be used to obtain pure water from a mixture of sand, water and methanoic acid?",
         "neutralization with NaOH followed by filtration", "neutralization with NaOH followed by distillation", "fractional distillation", "filtration followed by distillation", 1,
         "Neutralizing with NaOH converts volatile methanoic acid into non-volatile sodium methanoate (HCOONa), allowing pure water to be distilled off.", "Separation of Mixtures"),
        ("How many atoms are present in 6.0g of magnesium? [Mg = 24, N_A = 6.02 × 10²³ mol⁻¹]",
         "1.20 × 10²²", "2.41 × 10²²", "1.51 × 10²³", "3.02 × 10²³", 2,
         "Moles of Mg = 6.0 / 24 = 0.25 mol. Number of atoms = 0.25 × 6.02 × 10²³ = 1.505 × 10²³ atoms.", "Mole Concept"),
        ("50 cm³ of gas was collected over water at 10°C and 765 mm Hg. Calculate the volume of the gas at s.t.p. if the saturated vapour pressure of water at 10°C is 5 mm Hg.",
         "49.19 cm³", "48.87 cm³", "48.55 cm³", "48.23 cm³", 3,
         "Dry gas pressure P₁ = 765 - 5 = 760 mmHg. T₁ = 10 + 273 = 283 K. At STP: P₂ = 760 mmHg, T₂ = 273 K. V₂ = (P₁V₁T₂) / (P₂T₁) = (760 × 50 × 273) / (760 × 283) = 48.23 cm³.", "Gas Laws"),
        ("An increase in the pressure exerted on a gas at constant temperature results in _____.",
         "a decrease in the number of effective collisions", "a decrease in volume", "an increase in the average intermolecular distance", "an increase in volume", 1,
         "Boyle's Law states that gas volume is inversely proportional to applied pressure at constant temperature.", "Gas Laws"),
        ("2H₂(g) + O₂(g) → 2H₂O(g). In the reaction above, what volume of hydrogen would be left over when 300 cm³ of oxygen and 1000 cm³ of hydrogen are exploded in a sealed tube?",
         "200 cm³", "400 cm³", "600 cm³", "700 cm³", 1,
         "From Gay-Lussac's Law: 1 vol O₂ reacts with 2 vols H₂. 300 cm³ O₂ requires 600 cm³ H₂. Excess H₂ = 1000 - 600 = 400 cm³.", "Gay-Lussac's Law"),
        ("Which of the following can correctly be listed as evidence for the particulate nature of matter? (I. Evaporation, II. Sublimation, III. Diffusion, IV. Brownian motion)",
         "I and III only", "II and IV only", "I, II and III only", "I, II, III and IV", 3,
         "Evaporation, sublimation, diffusion, and Brownian motion all confirm that matter is composed of discrete moving particles.", "Nature of Matter"),
        ("If the elements X and Y have atomic numbers 11 and 17 respectively, what type of bond can they form?",
         "Dative", "Covalent", "Ionic", "Metallic", 2,
         "Element X is Sodium (metal, 2,8,1) and Y is Chlorine (non-metal, 2,8,7); electron transfer produces an electrovalent (ionic) bond.", "Chemical Bonding"),
        ("A hydrogen atom which has lost an electron (H⁺) contains _____.",
         "one proton only", "one neutron only", "one proton and one neutron", "one proton, one electron and one neutron", 0,
         "The standard protium atom (¹₁H) consists of 1 proton and 1 electron with no neutrons; losing its electron leaves a bare proton.", "Atomic Structure"),
        ("The electronic configuration of Mg²⁺ (atomic number 12) is _____.",
         "1s² 2s² 2p⁶ 3s² 3p²", "1s² 2s² 2p⁶ 3s²", "1s² 2s² 2p⁶", "1s² 2s² 2p⁴", 2,
         "Neutral Mg (Z=12) is 1s² 2s² 2p⁶ 3s²; losing two valence electrons leaves the stable octet 1s² 2s² 2p⁶.", "Electronic Configurations"),
        ("Group VII elements (halogens) are _____.",
         "monoatomic", "good oxidizing agents", "highly electropositive", "electron donors", 1,
         "Halogens have seven valence electrons and strong electron affinities, acting as powerful oxidizing agents by accepting electrons.", "Halogens"),
        ("Which of the following is used to study the arrangement of particles in crystal lattices?",
         "Alpha-particles", "Beta-particles", "Gamma-rays", "X-rays", 3,
         "X-ray diffraction analysis measures interatomic lattice spacing in solid crystalline structures.", "Crystallography"),
        ("Which of the following confirms that air is a mixture? (I. Variable composition, II. Constituents separated by physical means, III. Contains unreactive noble gases)",
         "I and II only", "II and III only", "I and III only", "I, II and III", 0,
         "Air exhibits variable geographic composition and its component gases can be fractionated physically by fractional distillation of liquid air.", "Mixtures and Compounds"),
        ("The chemicals used to soften hard water involve the addition of _____.",
         "insoluble sodium compounds which form soluble solutions of calcium and magnesium", "soluble sodium compounds which form soluble solutions of calcium and magnesium ions", "soluble sodium compounds which form insoluble precipitates of calcium and magnesium ions", "insoluble precipitates of calcium and magnesium ions", 2,
         "Washing soda (Na₂CO₃) is soluble and precipitates dissolved Ca²⁺ and Mg²⁺ ions as insoluble CaCO₃ and MgCO₃.", "Water Treatment"),
        ("Chlorination of water for town supply is carried out to _____.",
         "make the water colourless", "remove germs from the water", "make the water tasteful", "remove odour from the water", 1,
         "Chlorine acts as a potent bactericide, destroying pathogenic bacteria and microorganisms.", "Water Purification"),
        ("The solubilities of different solutes in a given solvent can be compared by _____.",
         "plotting their solubility curves on separate axes", "plotting their solubility curves on the same axes", "plotting some of the solubility curves on the x-axis and others on the y-axis", "plotting their solubility curves on the x-axis only", 1,
         "Comparing solubilities requires plotting temperature vs concentration curves of all solutes on the identical coordinate axes.", "Solubility Curves"),
        ("Potassium trioxochlorate (V) [KClO₃] has a solubility of 1.5 mol dm⁻³ at 45°C. On cooling to 20°C, solubility is 0.5 mol dm⁻³. What mass of KClO₃ was crystallized out from 1 dm³? [K=39, Cl=35.5, O=16]",
         "1.00g", "10.00g", "12.25g", "122.50g", 3,
         "Molar mass of KClO₃ = 39 + 35.5 + 48 = 122.5 g mol⁻¹. Moles crystallized = 1.5 - 0.5 = 1.0 mol. Mass = 1.0 × 122.5 = 122.50 g.", "Solubility Calculations"),
        ("Which of the following pollutants is associated with brain damage and neurotoxicity?",
         "Carbon (II) oxide", "Radioactive fallout", "Biodegradable waste", "Lead / Sulphur (IV) oxide", 1,
         "Radioactive radiation and heavy metals cause severe cellular degradation and nervous system damage.", "Environmental Pollution"),
        ("Which of the following will produce a solution with pH less than 7 at equivalent point?",
         "HNO₃ + NaOH", "H₂SO₄ + KOH", "HCl + Mg(OH)₂", "HNO₃ + KOH", 2,
         "Titration of a strong acid (HCl) with a weak base [Mg(OH)₂] produces an acidic salt that hydrolyzes to give pH < 7.", "Acid-Base Titrations"),
        ("The number of hydroxonium ions produced by one molecule of an acid in aqueous solution is its _____.",
         "basicity", "acid strength", "pH", "concentration", 0,
         "Basicity is the number of replaceable hydrogen ions (H₃O⁺) yielded per molecule of an acid in water.", "Acids and Bases"),
        ("During a titration experiment, 0.05 moles of carbon (IV) oxide is liberated. What is the volume of gas liberated at s.t.p.?",
         "22.40 dm³", "11.20 dm³", "2.24 dm³", "1.12 dm³", 3,
         "Volume at STP = Moles × Molar volume = 0.05 × 22.4 dm³ = 1.12 dm³.", "Stoichiometry"),
        ("A major factor considered in selecting a suitable method for preparing a simple salt is its _____.",
         "Crystalline form", "melting point", "reactivity with dilute acids", "solubility in water", 3,
         "Salt preparation depends fundamentally on water solubility (soluble salts via neutralization/action of acid on metal, insoluble salts via double decomposition precipitation).", "Preparation of Salts"),
        ("The oxidation number of boron in NaBH₄ is _____.",
         "-3", "-1", "+1", "+3", 3,
         "In tetrahydroborate(III), Na is +1 and H is -1 (hydride). 1 + B + 4(-1) = 0 => B = +3.", "Oxidation States"),
        ("2Na₂O₂(s) + 2H₂O₂(l) → 4NaOH(s) + O₂(g). The substance that is oxidized in the reaction above is _____.",
         "2NaO₂(s)", "NaOH(aq)", "H₂O₂(l)", "O₂(g)", 2,
         "In hydrogen peroxide, oxygen has oxidation state -1 and is oxidized to elemental oxygen O₂ (oxidation state 0).", "Redox Reactions"),
        ("What number of moles of Cu²⁺ will be deposited by 360 coulombs of electricity? [F = 96500 C mol⁻¹]",
         "5.36 × 10⁻⁴ mole", "1.87 × 10⁻³ mole", "9.35 × 10⁻⁴ mole", "3.73 × 10⁻³ mole", 1,
         "Cu²⁺ + 2e⁻ → Cu. Depositing 1 mole of Cu requires 2 Faradays (2 × 96500 C). Moles = 360 / (2 × 96500) = 1.865 × 10⁻³ mole.", "Faraday's Laws"),
        ("A metal M displaces zinc from ZnCl₂ solution. This shows that _____.",
         "electrons flow from zinc to M", "M is more electropositive than zinc", "M is more electronegative than zinc", "zinc is more electropositive than M", 1,
         "A metal higher in the electrochemical series is more electropositive and readily displaces lower cations from aqueous solution.", "Electrochemical Series"),
        ("CO(g) + H₂O(g) → CO₂(g) + H₂(g). Calculate standard enthalpy change if ΔHf of CO₂(g), H₂O(g) and CO(g) are -394, -242 and -110 kJ mol⁻¹ respectively.",
         "+262 kJ mol⁻¹", "-262 kJ mol⁻¹", "+42 kJ mol⁻¹", "-42 kJ mol⁻¹", 3,
         "ΔH = ΣΔHf(products) - ΣΔHf(reactants) = [-394 + 0] - [-110 + (-242)] = -394 - (-352) = -42 kJ mol⁻¹.", "Thermochemistry: Hess's Law"),
        ("An increase in entropy can best be illustrated by _____.",
         "mixing of gases", "freezing of water", "the condensation of vapour", "solidifying candle wax", 0,
         "Mixing gases increases molecular chaos and spatial microstates, resulting in a large positive entropy change (ΔS > 0).", "Entropy"),
        ("The highest rate of production of carbon (IV) oxide can be achieved using _____.",
         "0.05 mol dm⁻³ HCl and 5g powdered CaCO₃", "0.05 mol dm⁻³ HCl and 5g lump CaCO₃", "0.10 mol dm⁻³ HCl and 5g powdered CaCO₃", "0.025 mol dm⁻³ HCl and 5g powdered CaCO₃", 2,
         "Higher acid concentration (0.10 M) combined with greater surface area of finely powdered CaCO₃ maximizes collision frequency.", "Reaction Kinetics"),
        ("From the reaction 2HCl(aq) + CaCO₃(s) → CaCl₂(aq) + CO₂(g) + H₂O(l), the curve showing initial rapid production of CO₂ gas leveling off as reactants deplete is represented by curve _____.",
         "L", "M", "N", "P", 1,
         "Typical progressive reaction curves show an initial steep slope that gradually flattens to a horizontal asymptote as the limiting reactant is exhausted.", "Reaction Curves"),
        ("2CO(g) + O₂(g) ⇌ 2CO₂(g). In the reaction above, high pressure will favour the forward reaction because _____.",
         "high pressure favours gas formation", "the reaction is in dynamic equilibrium", "the reaction is exothermic", "the process occurs with a decrease in volume", 3,
         "Le Chatelier's Principle: increasing pressure shifts equilibrium toward fewer gas moles (3 moles reactant → 2 moles product, decrease in volume).", "Chemical Equilibrium"),
        ("A piece of filter paper moistened with lead (II) ethanoate solution turns black when dropped into _____.",
         "sulphur (VI) oxide", "hydrogen chloride", "sulphur (IV) oxide", "hydrogen sulphide", 3,
         "Hydrogen sulphide gas (H₂S) precipitates black lead(II) sulphide: Pb(CH₃COO)₂ + H₂S → PbS↓ (black) + 2CH₃COOH.", "Qualitative Identification"),
        ("Which of the following gases has a characteristic pungent smell, turns red litmus paper blue and forms dense white fumes with hydrogen chloride gas?",
         "N₂", "N₂O", "Cl₂", "NH₃", 3,
         "Ammonia (NH₃) is an alkaline gas reacting with HCl vapour to form airborne ammonium chloride smoke: NH₃ + HCl → NH₄Cl(s).", "Inorganic Chemistry: Nitrogen"),
        ("Commercial bleaching can be carried out using _____.",
         "sulphur (IV) oxide and ammonia", "hydrogen sulphide and chlorine", "chlorine and sulphur (IV) oxide", "ammonia and chlorine", 2,
         "Chlorine (bleaching by oxidation) and sulphur(IV) oxide (bleaching by reduction) are standard commercial industrial bleaches.", "Bleaching Agents"),
        ("Mineral acids are usually added to commercial hydrogen peroxide to _____.",
         "oxidize it", "decompose it", "minimize its decomposition", "reduce it to water and oxygen", 2,
         "Dilute mineral acid acts as a negative catalyst (inhibitor) stabilizing hydrogen peroxide against spontaneous decomposition.", "Chemical Kinetics"),
        ("Which of the following compounds will burn with a brick-red colour in a non-luminous Bunsen flame?",
         "LiCl", "NaCl", "CaCl₂", "MgCl₂", 2,
         "Calcium salts impart a characteristic brick-red coloration to the non-luminous flame.", "Flame Tests"),
        ("The purest commercial form of iron which contains only about 0.1% carbon is _____.",
         "pig iron", "wrought iron", "cast iron", "iron pyrite", 1,
         "Wrought iron contains less than 0.15% carbon, making it malleable, ductile, and the purest commercial iron grade.", "Iron and Steel"),
        ("A common characteristic between zinc and other transition elements is the ability to _____.",
         "have variable oxidation states", "form complex ions", "act as a catalyst", "form coloured ions", 1,
         "Although zinc has completely filled 3d orbitals (non-variable valency and colorless ions), it readily forms stable coordination complex ions like [Zn(NH₃)₄]²⁺.", "Transition Metals"),
        ("Which of the following metals is the least reactive in the electrochemical series?",
         "Pb", "Sn", "Hg", "Au", 3,
         "Gold (Au) lies at the bottom of the activity series, resisting oxidation and corrosion by air, water, and common mineral acids.", "Activity Series"),
        ("Geometric (cis-trans) isomerism can exist in _____.",
         "hex-3-ene", "hexane", "prop-1-ene", "3-methylbut-1-ene", 0,
         "Hex-3-ene (CH₃CH₂CH=CHCH₂CH₃) possesses restricted rotation about C=C with non-identical groups on each carbon.", "Stereochemistry"),
        ("Alkanals can be distinguished from alkanones by reaction with _____.",
         "Sudan III stain", "starch iodide paper", "lithium tetrahydrido aluminate (III)", "Fehling's solution", 3,
         "Fehling's solution oxidizes aliphatic alkanals yielding a brick-red precipitate of Cu₂O, while alkanones give no reaction.", "Alkanals & Alkanones"),
        ("The isomers of C₃H₈O are _____.",
         "1-propanol and 2-propanol", "1-propanol and 1-propanol", "2-propanol and 2-propanone", "2-propanol and 1-propanol", 0,
         "C₃H₈O forms positional isomers 1-propanol (CH₃CH₂CH₂OH) and 2-propanol (CH₃CH(OH)CH₃), plus the functional ether isomer methoxyethane.", "Isomerism"),
        ("Carbohydrates are large molecules with formula Cx(H₂O)y. In which of the following pairs is x not equal to y?",
         "glucose and starch", "maltose and starch", "sucrose and fructose", "sucrose and starch", 1,
         "Disaccharides (maltose C₁₂H₂₂O₁₁, x=12, y=11) and polysaccharides (starch [C₆H₁₀O₅]n, x=6, y=5) have x ≠ y.", "Carbohydrates"),
        ("A compound contains 40.0% C, 6.7% H, 53.3% O. If molecular mass is 180, its molecular formula is _____ [C=12, H=1, O=16]",
         "CH₂O", "C₃H₆O₃", "C₆H₆O₃", "C₆H₁₂O₆", 3,
         "C: 40/12=3.33; H: 6.7/1=6.7; O: 53.3/16=3.33. Ratio 1:2:1 (CH₂O, empirical mass 30). n = 180/30 = 6 => C₆H₁₂O₆ (glucose/fructose).", "Empirical & Molecular Formula"),
        ("The alkyne that will give a white precipitate with ammoniacal silver trioxonitrate (V) is _____.",
         "CH₃CH₂C≡CCH₂CH₃", "CH₃C≡CCH₂CH₂CH₃", "CH₃CH₂CH₂CH₂C≡CH", "CH₃CH₂CH₂C≡CCH₂CH₃", 2,
         "Terminal alkynes with an acidic acetylenic hydrogen (–C≡C–H) react with Tollens' reagent to form white silver acetylide precipitate.", "Alkynes"),
        ("The saponification of an alkanoate to produce soap and alkanol involves _____.",
         "dehydration", "esterification", "hydrolysis", "oxidation", 2,
         "Saponification is the alkaline hydrolysis of fats/oils (glycerol esters) with NaOH or KOH to produce soap and glycerol.", "Fats and Oils"),
        ("2-methylpropan-2-ol is an example of a _____.",
         "primary alkanol", "secondary alkanol", "tertiary alkanol", "quaternary alkanol", 2,
         "The hydroxyl-bearing carbon is directly attached to three methyl groups ((CH₃)₃C-OH), making it a tertiary alkanol.", "Alkanols"),
        ("The final oxidation product of primary alkanols, alkanals and alkanoic acids is _____.",
         "alkanoic acid", "alkanoyl halide", "alkanoate", "alkanamide", 0,
         "Primary alkanols oxidize to alkanals, which upon exhaustive oxidation yield stable alkanoic acids (carboxylic acids).", "Oxidation of Alkanols"),
        ("Ethanol reacts with concentrated tetraoxosulphate (VI) acid at a temperature above 170°C to form _____.",
         "ethanone", "ethene", "ethyne", "ethanal", 1,
         "At 170°C, concentrated H₂SO₄ acts as a dehydrating agent, eliminating water from ethanol to yield ethene: C₂H₅OH → C₂H₄ + H₂O.", "Dehydration of Ethanol"),
        ("An example of an oxidation-reduction enzyme is _____.",
         "amylase", "protease", "lipase", "dehydrogenase", 3,
         "Dehydrogenases catalyze biological oxidation-reduction reactions by transferring hydride ions or electrons.", "Enzymes")
    ]
    for idx, item in enumerate(pt1_data, 1):
        q, a, b, c, d, ans, exp, topic = item
        questions.append({
            "id": f"jamb_chm_pt2_{idx:02d}", "subject": "Chemistry", "topic": topic, "year": "PT. 2",
            "text": q, "a": a, "b": b, "c": c, "d": d, "ans": ans, "exp": exp,
            "label": f"JAMB Chemistry PT.2 • Q{idx}"
        })

    # -------------------------------------------------------------
    # PART 3 (Questions 1 to 50)
    # -------------------------------------------------------------
    pt3_data = [
        ("Which Question Paper Type of Chemistry is given to you?", "Type D", "Type I", "Type B", "Type U", 1, "JAMB examination question paper type identifier.", "General Introduction"),
        ("The presence of an impurity in a substance will cause the melting point to _____.",
         "be zero", "reduce", "increase", "be stable", 1,
         "Impurities disrupt the crystalline lattice of a pure solid, depressing and broadening its melting point.", "Purity of Substances"),
        ("What volume of carbon (II) oxide is produced by reacting excess carbon with 10dm³ of oxygen?",
         "5 dm³", "20 dm³", "15 dm³", "10 dm³", 1,
         "2C(s) + O₂(g) → 2CO(g). From Gay-Lussac's law, 1 volume of O₂ yields 2 volumes of CO. 10 dm³ O₂ yields 20 dm³ CO.", "Gas Stoichiometry"),
        ("From the PV versus P plot, an ideal gas is represented by _____.",
         "M", "N", "K", "L", 1,
         "An ideal gas has constant PV regardless of pressure, displayed as a horizontal straight line (N).", "Gas Laws"),
        ("The rate of diffusion of a gas Y is twice that of Z. If the relative molecular mass of Y is 64 and the two gases diffuse under the same conditions, find the relative molecular mass of Z.",
         "32", "4", "8", "256", 3,
         "Graham's Law: R_Y / R_Z = √(M_Z / M_Y). 2 = √(M_Z / 64) => 4 = M_Z / 64 => M_Z = 256.", "Graham's Law"),
        ("The radioisotope used in industrial radiography for the rapid checking of faults in welds and casting is _____.",
         "Carbon-14", "phosphorus-32", "cobalt-60", "iodine-131", 2,
         "Cobalt-60 emits high-energy gamma rays capable of penetrating thick industrial steel castings and pipeline welds.", "Nuclear Chemistry"),
        ("How many unpaired electrons are in the p-orbitals of a fluorine atom?",
         "3", "0", "1", "2", 2,
         "Fluorine (Z=9) has electronic configuration 1s² 2s² 2px² 2py² 2pz¹, possessing exactly one unpaired p electron.", "Atomic Structure"),
        ("The radioactive emission with the least ionization power is _____.",
         "α-particles", "X-rays", "γ-rays", "β-particles", 2,
         "Gamma rays (γ) are uncharged electromagnetic photons with the highest penetration and weakest specific ionization power.", "Radioactivity"),
        ("The shape of the carbon (IV) oxide molecule is _____.",
         "pyramidal", "linear", "angular", "tetrahedral", 1,
         "CO₂ has two double bonds with zero lone pairs on carbon (sp hybridization), producing a symmetrical linear molecule (180° bond angle).", "Molecular Shapes"),
        ("Which of the following molecules is held together by hydrogen bond?",
         "CH₄", "HBr", "H₂SO₄", "HF", 3,
         "Fluorine's extreme electronegativity polarizes the H-F bond, forming strong intermolecular hydrogen bonds.", "Intermolecular Forces"),
        ("The bond formed between two elements with electron configurations 1s² 2s² 2p⁶ 3s² and 1s² 2s² 2p⁴ is _____.",
         "metallic", "covalent", "dative", "ionic", 3,
         "The first element is Magnesium (metal, transfers 2 electrons) and the second is Oxygen (non-metal, gains 2 electrons), forming an ionic bond (MgO).", "Chemical Bonding"),
        ("The constituent of air that acts as a diluent is _____.",
         "nitrogen", "carbon (IV) oxide", "noble gases", "oxygen", 0,
         "Nitrogen (78% of air) is chemically unreactive under normal conditions, diluting atmospheric oxygen and moderating combustion.", "Atmosphere"),
        ("Steam changes the colour of anhydrous cobalt (II) chloride from _____.",
         "white to red", "blue to white", "blue to pink", "white to blue", 2,
         "Anhydrous CoCl₂ is blue and hydrates in contact with water/steam to form pink hexahydrate CoCl₂·6H₂O.", "Test for Water"),
        ("An example of a hygroscopic substance is _____.",
         "CuO(s)", "MgCl₂(s)", "CaCl₂(s)", "NaOH(s)", 2,
         "Solid anhydrous CaCl₂ absorbs atmospheric water vapour without forming a pool of liquid, serving as a laboratory desiccant.", "Hygroscopy"),
        ("If 24.4g of lead (II) trioxonitrate (V) was dissolved in 42g of distilled water at 20°C, calculate the solubility of the solute in g dm⁻³.",
         "581.000", "0.581", "5.810", "58.100", 0,
         "Solubility in g dm⁻³ = (24.4 g / 42 g) × 1000 g dm⁻³ = 580.95 ≈ 581.0 g dm⁻³.", "Solubility Calculations"),
        ("The solvent used for removing grease stains is _____.",
         "turpentine", "ammonia solution", "ethanol", "solution of borax in water", 0,
         "Turpentine and non-polar organic solvents dissolve non-polar fats, waxes, and machine grease.", "Solvents"),
        ("In a water body, too much sewage leads to _____.",
         "a decrease in the temperature of the water which causes death of aquatic animals", "an increase in the number of aquatic animals in the water", "an increase in the bacterial population which reduces the level of oxygen in the water", "a decrease in the bacterial population which increases the level of oxygen in the water", 2,
         "Biodegradation of organic sewage causes bacterial blooms that consume dissolved oxygen (high Biological Oxygen Demand), creating anoxic conditions.", "Water Pollution"),
        ("10.0 dm³ of water was added to 2.0 mol dm⁻³ of 2.5 dm³ solution of HCl. What is the concentration of the final solution in mol dm⁻³?",
         "0.4", "8.0", "2.0", "0.5", 0,
         "Initial moles = C₁V₁ = 2.0 × 2.5 = 5.0 moles. Final volume V₂ = 2.5 + 10.0 = 12.5 dm³. Final concentration C₂ = 5.0 / 12.5 = 0.40 mol dm⁻³.", "Volumetric Dilutions"),
        ("Three drops of a 1.0 mol dm⁻³ solution of HCl was added to 20cm³ of a solution of pH 6.4. The pH of the resulting solution will be _____.",
         "close to that of pure water", "less than 6.4", "greater than 6.4", "unaltered", 1,
         "Adding hydrochloric acid increases hydrogen ion concentration [H⁺], decreasing the solution pH below 6.4.", "Acids, Bases and pH"),
        ("Which of the following substances is not a salt?",
         "Aluminium oxide", "Sodium hydrogen trioxosulphate (IV)", "Sodium trioxocarbonate (IV)", "Zinc chloride", 0,
         "Aluminium oxide (Al₂O₃) is an amphoteric basic oxide, not a salt formed by replacement of acidic hydrogen.", "Acids, Bases & Salts"),
        ("An insoluble salt can be prepared by _____.",
         "the reaction of trioxocarbonate (IV) with an acid", "double decomposition", "the action of dilute acid on an insoluble base", "the reaction of metals with an acid", 1,
         "Insoluble salts (e.g. BaSO₄, PbSO₄, AgCl) are synthesized via precipitation/double decomposition of two soluble electrolyte solutions.", "Preparation of Salts"),
        ("2H₂O(l) + 2F₂(g) → 4HF(aq) + O₂(g). In the reaction above, the substance that is being reduced is _____.",
         "O₂(g)", "H₂O(l)", "F₂(g)", "HF(aq)", 2,
         "Fluorine's oxidation number decreases from 0 in elemental F₂ to -1 in HF, meaning F₂ undergoes reduction.", "Redox Reactions"),
        ("Zn(s) + CuSO₄(aq) → ZnSO₄(aq) + Cu(s). In the reaction above, the oxidizing agent is _____.",
         "CuSO₄(aq)", "ZnSO₄(aq)", "Cu(s)", "Zn(s)", 0,
         "Copper(II) ions in CuSO₄ gain electrons (Cu²⁺ + 2e⁻ → Cu) and are reduced, thereby acting as the oxidizing agent.", "Redox Reactions"),
        ("In an electrochemical cell, polarization is caused by _____.",
         "chlorine", "oxygen", "tetraoxosulphate (VI) acid", "hydrogen", 3,
         "Polarization is the accumulation of hydrogen gas bubbles on the positive copper plate, increasing internal resistance.", "Electrochemical Cells"),
        ("Calculate the volume in dm³ of oxygen evolved at s.t.p. when a current of 5 A is passed through acidified water for 193s {F = 96500 C mol⁻¹, Molar volume at s.t.p. = 22.4 dm³}.",
         "224.000 dm³", "0.056 dm³", "0.224 dm³", "56.000 dm³", 1,
         "Q = It = 5 × 193 = 965 C. 4OH⁻ → 2H₂O + O₂ + 4e⁻. 1 mole of O₂ requires 4 × 96500 C = 386000 C. Moles O₂ = 965 / 386000 = 0.0025 mol. Volume = 0.0025 × 22.4 = 0.056 dm³.", "Electrolysis Calculations"),
        ("In an endothermic reaction, if there is a loss in entropy (ΔH > 0, ΔS < 0), the reaction will _____.",
         "be indeterminate", "be spontaneous", "not be spontaneous", "be at equilibrium", 2,
         "Gibbs free energy ΔG = ΔH - TΔS. With positive ΔH and negative ΔS, ΔG is always positive at all temperatures, so the reaction is non-spontaneous.", "Chemical Thermodynamics"),
        ("2SO₂(g) + O₂(g) ⇌ 2SO₃(g) ΔH = −395.7 kJ mol⁻¹. In the reaction above, the concentration of SO₃(g) can be increased by _____.",
         "decreasing the pressure", "decreasing the temperature", "increasing the temperature", "the addition of catalyst", 1,
         "For an exothermic reaction, lowering temperature shifts equilibrium toward the forward direction, increasing SO₃ yield.", "Equilibrium"),
        ("The minimum amount of energy required for a reaction to take place is _____.",
         "lattice energy", "ionization energy", "activation energy", "kinetic energy", 2,
         "Activation energy (E_a) is the threshold kinetic energy colliding molecules must possess for chemical bond rearrangement.", "Chemical Kinetics"),
        ("In a potential energy graph of a catalyzed versus uncatalyzed reaction, the activation energy of the catalyzed reaction (peak 200 kJ, baseline reactants 100 kJ) is _____.",
         "100 kJ", "300 kJ", "250 kJ", "200 kJ", 0,
         "Activation energy E_a(cat) = 200 kJ - 100 kJ = 100 kJ.", "Catalysis"),
        ("3Fe(s) + 4H₂O(g) ⇌ Fe₃O₄(s) + 4H₂(g). The equilibrium constant, K, of the reaction above is represented as _____.",
         "[Fe₃O₄][H₂] / [Fe][H₂O]", "[H₂O]⁴ / [H₂]⁴", "[H₂]⁴ / [H₂O]⁴", "[Fe]³[H₂O]² / [Fe₃O₄][H₂]⁴", 2,
         "Pure solids (Fe and Fe₃O₄) have constant activity equal to 1. The equilibrium expression contains only gaseous species: K = [H₂]⁴ / [H₂O]⁴.", "Equilibrium Constants"),
        ("Which of the following compounds is a neutral oxide?",
         "Carbon (IV) oxide", "Sulphur (VI) oxide", "Sulphur (IV) oxide", "Carbon (II) oxide", 3,
         "Carbon(II) oxide (CO), nitrous oxide (N₂O), and nitric oxide (NO) are neutral oxides showing neither acidic nor basic properties.", "Oxides"),
        ("In the laboratory preparation of ammonia, the flask is placed in a slanting position so as to _____.",
         "prevent condensed water from breaking the reaction flask", "enable the proper mixing of the reactions in the flask", "enhance the speed of the reaction", "prevent formation of precipitate", 0,
         "Slanting the tube downward prevents condensed steam from trickling back into the hot bottom of the glassware and cracking it.", "Laboratory Preparation of Ammonia"),
        ("Which of the gases is employed as an anaesthetic (laughing gas)?",
         "N₂O", "NO₂", "NH₃", "NO", 0,
         "Dinitrogen monoxide (N₂O) is used in medical and dental anesthesia as an inhaled sedative.", "Nitrogen Compounds"),
        ("Sulphur (IV) oxide is a strong reducing agent in the presence of water due to the formation of _____.",
         "hydroxide ion", "sulphur (VI) oxide", "hydrogen sulphide", "trioxosulphate (IV) acid / salt", 3,
         "SO₂ dissolves in water forming trioxosulphate(IV) acid (H₂SO₃), which readily oxidizes to sulfate while reducing other species.", "Sulphur Chemistry"),
        ("A metal that forms a soluble trioxosulphate (IV) salt is _____.",
         "barium", "potassium", "manganese", "aluminium", 1,
         "All alkali metal (Group 1) sulfites, including potassium sulfite (K₂SO₃), are readily soluble in water.", "Salts"),
        ("Copper is displaced from the solution of its salts by most metals because it _____.",
         "is a transition element", "is at the bottom of the activity series", "is very reactive", "has completely filled 3d-orbitals", 1,
         "Copper has a high standard reduction potential (+0.34 V) and is readily reduced and displaced by more electropositive metals.", "Electrochemical Series"),
        ("The coloured nature of transition metal ions is associated with their partially filled _____.",
         "f-orbital", "s-orbital", "p-orbital", "d-orbital", 3,
         "d-d electron transitions between split d-orbital energy levels absorb visible wavelengths, rendering coordination ions coloured.", "Transition Metals"),
        ("Aluminium containers are frequently used to transport concentrated trioxonitrate (V) acid because aluminium _____.",
         "has a silvery-white appearance", "has a low density", "does not react with the acid (rendered passive)", "does not corrode", 2,
         "Concentrated HNO₃ passivates aluminium by forming a dense, unreactive, protective surface oxide coating (Al₂O₃).", "Metals and Nitric Acid"),
        ("2-methylbutan-2-ol is an example of a _____.",
         "dihydric alkanol", "tertiary alkanol", "secondary alkanol", "primary alkanol", 1,
         "The hydroxyl group is attached to carbon-2, which is bonded to three other alkyl carbon atoms: CH₃–C(OH)(CH₃)–CH₂CH₃.", "Alkanols"),
        ("The reaction between ammonia and ethyl ethanoate produces _____.",
         "propanol and ethanamide", "propanol and propanamide", "ethanol and propanamide", "ethanol and ethanamide", 3,
         "Ammonolysis of an ester: CH₃COOC₂H₅ + NH₃ → CH₃CONH₂ (ethanamide) + C₂H₅OH (ethanol).", "Esters and Amides"),
        ("The decarboxylation of ethanoic acid will produce carbon (IV) oxide and _____.",
         "methane", "ethane", "propane", "butane", 0,
         "Heating sodium ethanoate with sodalime eliminates the carboxyl group as carbonate, yielding methane: CH₃COONa + NaOH → CH₄ + Na₂CO₃.", "Alkanes"),
        ("In the structure CH₃–CO–CH₃, the compound is an _____.",
         "alkanone", "alkanoate", "alkanal", "alkanol", 0,
         "Propanone contains the carbonyl group (>C=O) flanked by two alkyl radicals, characteristic of alkanones (ketones).", "Alkanones"),
        ("The compound that will react with sodium hydroxide to form salt and water is _____.",
         "C₆H₁₂O₆", "(CH₃)₃COH", "CH₃CH=CH₂", "CH₃CH₂COOH", 3,
         "Propanoic acid (CH₃CH₂COOH) is a carboxylic acid that neutralizes NaOH to form sodium propanoate and water.", "Carboxylic Acids"),
        ("Which of the following nitrogenous compounds in solution will turn red litmus paper blue?",
         "RCOOR'", "RCONHR", "RNH₂", "RCOR'", 2,
         "Aliphatic amines (RNH₂) are organic Bronsted-Lowry bases whose aqueous solutions turn red litmus paper blue.", "Organic Bases"),
        ("The dehydration of the ammonium salt of an alkanoic acid produces a compound with the general formula _____.",
         "RCOOR", "RCONH₂", "RCONHR", "RCONR₂", 1,
         "Pyrolysis of ammonium alkanoate dehydrates it into an unsubstituted primary amide: RCOONH₄ → RCONH₂ + H₂O.", "Organic Nitrogen Compounds"),
        ("Which of the following fractions of crude petroleum is used as raw material for the cracking process?",
         "kerosene", "lubricating oil", "bitumen", "diesel oils (gas oil)", 3,
         "Heavy gas oil and diesel oil fractions are cracked thermally or catalytically into high-octane gasoline petrol fractions.", "Petroleum Refining"),
        ("An organic compound with a sweet, pleasant fruity smell is likely to have the general formula _____.",
         "C_n H_{2n+1} CHO", "C_n H_{2n+1} COOH", "C_n H_{2n+1} COOC_m H_{2m+1}", "C_n H_{2n+1} COC_m H_{2m+1}", 2,
         "Alkyl alkanoates (esters, RCOOR') are volatile liquids with characteristic fruity aromas used in flavorings and perfumes.", "Esters"),
        ("A primary amide is generally represented by the formula _____.",
         "RCOOR", "RCONH₂", "RCONHR", "RCONR₂", 1,
         "Primary amides have the carbonyl group directly bonded to an unsubstituted –NH₂ group.", "Amides"),
        ("The IUPAC nomenclature for (CH₃)₂CH–CH₂–CH=CH₂ is _____.",
         "4-methylpent-1-ene", "3-methylpent-2-ene", "2-methylpent-1-ene", "2-methylpent-4-ene", 0,
         "Numbering begins from the double bond end (C1=C2). At C4 there is a methyl substituent: 4-methylpent-1-ene.", "IUPAC Nomenclature"),
        ("An organic compound contains 60% carbon, 13.3% hydrogen and 26.7% oxygen. Calculate empirical formula. [C=12, H=1, O=16]",
         "C₅H₁₂O", "C₃H₈O", "C₆H₁₃O₂", "C₄H₉O", 1,
         "C: 60/12 = 5; H: 13.3/1 = 13.3; O: 26.7/16 = 1.67. Dividing by 1.67: C = 3, H = 8, O = 1. Empirical formula = C₃H₈O.", "Empirical Formula")
    ]
    for idx, item in enumerate(pt3_data, 1):
        q, a, b, c, d, ans, exp, topic = item
        questions.append({
            "id": f"jamb_chm_pt3_{idx:02d}", "subject": "Chemistry", "topic": topic, "year": "PT. 3",
            "text": q, "a": a, "b": b, "c": c, "d": d, "ans": ans, "exp": exp,
            "label": f"JAMB Chemistry PT.3 • Q{idx}"
        })

    # -------------------------------------------------------------
    # PART 4 (Questions 1 to 50)
    # -------------------------------------------------------------
    pt4_data = [
        ("Which Question Paper Type of Chemistry is given to you?", "Type F", "Type E", "Type L", "Type S", 1, "JAMB examination question paper type identifier.", "General Introduction"),
        ("A mixture is different from a compound because _____.",
         "the properties of a compound are those of its individual constituents while those of a mixture differ from its constituents", "a mixture is always homogeneous while a compound is not", "the constituents of a compound are chemically bound together while those of a mixture are not", "a mixture can be represented by a chemical formula while a compound cannot", 2,
         "Compounds consist of chemically combined elements in fixed stoichiometric proportions, whereas mixtures are physical combinations separated by physical means.", "Matter and Mixtures"),
        ("What is the percentage of sulphur in sulphur (IV) oxide [SO₂]? [S = 32, O = 16]",
         "66%", "25%", "40%", "50%", 3,
         "Molar mass of SO₂ = 32 + 2(16) = 64 g mol⁻¹. % S = (32 / 64) × 100% = 50%.", "Percentage Composition"),
        ("A gas X diffuses twice as fast as gas Y. If the relative molecular mass of X is 32, calculate the relative molecular mass of Y.",
         "128", "8", "16", "64", 0,
         "Graham's Law: R_X / R_Y = √(M_Y / M_X) => 2 = √(M_Y / 32) => 4 = M_Y / 32 => M_Y = 128.", "Gas Laws"),
        ("200cm³ of a gas at 25°C exerts a pressure of 700 mmHg. Calculate its pressure if its volume increases to 350 cm³ at 75°C.",
         "342.53 mmHg", "1430.54 mmHg", "467.11 mmHg", "400.00 mmHg", 2,
         "General gas law: (P₁V₁) / T₁ = (P₂V₂) / T₂. P₂ = (700 × 200 × 348) / (298 × 350) = 467.11 mmHg.", "Gas Laws"),
        ("An element X has electron configuration 1s² 2s² 2p⁶ 3s² 3p⁵. Which of the following statements is correct about the element?",
         "It has a completely filled p-orbital", "It has 5 electrons in its outermost shell", "It belongs to group II on the periodic table", "It is a halogen", 3,
         "With seven valence electrons (3s² 3p⁵, atomic number 17, Chlorine), element X is a Group 7 halogen.", "Electronic Configuration"),
        ("Beryllium and aluminium have similar properties because they _____.",
         "are both metals", "belong to the same group", "belong to the same period", "are positioned diagonally to each other", 3,
         "Beryllium and aluminium exhibit a diagonal relationship due to comparable ionic charge densities and polarizing power.", "Periodic Table"),
        ("If the difference in electronegativity of elements P and Q is 3.0, the bond that will be formed between them is _____.",
         "metallic", "covalent", "co-ordinate", "ionic", 3,
         "An electronegativity difference exceeding 1.7 to 2.0 indicates complete electron transfer and predominantly ionic character.", "Chemical Bonding"),
        ("How many protons, neutrons and electrons respectively are present in the cobalt isotope ⁶⁰₂₇Co?",
         "27, 33 and 33", "33, 27 and 27", "27, 33, and 27", "60, 33 and 60", 2,
         "Protons = Z = 27; Electrons = 27; Neutrons = A - Z = 60 - 27 = 33.", "Atomic Structure"),
        ("The radiation used in studying the arrangement of particles in giant organic crystal molecules is _____.",
         "γ-rays", "α-particles", "X-rays", "β-particles", 2,
         "X-ray crystallography determines 3D macromolecular structures of proteins and polymers.", "Crystallography"),
        ("A silicon-containing ore has 92% ²⁸Si, 5% ²⁹Si and 3% ³⁰Si. Calculate the relative atomic mass of the silicon.",
         "14.00", "29.00", "28.11", "28.00", 2,
         "R.A.M. = (92 × 28 + 5 × 29 + 3 × 30) / 100 = (2576 + 145 + 90) / 100 = 28.11.", "Isotopes & Atomic Mass"),
        ("The nitrogen obtained from air has a density higher than the one from nitrogen-containing compounds because the one from air is contaminated with _____.",
         "water vapour", "oxygen", "rare gases (argon)", "carbon (IV) oxide", 2,
         "Atmospheric nitrogen contains dense noble gases (chiefly Argon, atomic mass 40 vs N₂ mass 28), increasing its density.", "Atmospheric Nitrogen"),
        ("Water is said to be temporarily hard when it contains _____.",
         "Ca(HCO₃)₂ and Mg(HCO₃)₂ salts", "Ca(HCO₃)₂ and CaCO₃ salts", "Mg(HCO₃)₂ and CaSO₄ salts", "CaSO₄ and Ca(HCO₃)₂ salts", 0,
         "Temporary water hardness is caused by dissolved calcium and magnesium hydrogentrioxocarbonate(IV) salts.", "Water Hardness"),
        ("On exposure to the atmosphere, a hydrated salt loses its water of crystallization to become anhydrous powder. This phenomenon is referred to as _____.",
         "efflorescence", "deliquescence", "hygroscopy", "hydrolysis", 0,
         "Efflorescence is the loss of water of crystallization from a hydrated salt when its vapour pressure exceeds atmospheric humidity.", "Efflorescence"),
        ("16.55g of lead (II) trioxonitrate (V) [Pb(NO₃)₂] was dissolved in 100g of distilled water at 20°C. Calculate the solubility of the solute in mol dm⁻³ [Pb = 207, N = 14, O = 16].",
         "0.05 mol dm⁻³", "2.00 mol dm⁻³", "1.00 mol dm⁻³", "0.50 mol dm⁻³", 3,
         "Molar mass of Pb(NO₃)₂ = 207 + 2(14 + 48) = 331 g mol⁻¹. Moles = 16.55 / 331 = 0.05 mol in 100g water => 0.50 mol in 1000g (1 dm³) water.", "Solubility Calculations"),
        ("The dispersion of a liquid in a liquid medium will give _____.",
         "an emulsion", "a fog", "a gel", "an aerosol", 0,
         "An emulsion is a colloidal dispersion of one liquid in another immiscible liquid medium (e.g. milk, mayonnaise).", "Colloids"),
        ("The major and most effective way of controlling industrial environmental pollution is to _____.",
         "improve machinery so that the substances released from combustion are less harmful", "pass strict laws against it by individuals and companies", "educate people on the causes and effects of pollution", "convert chemical wastes to harmless substances before releasing them into the environment", 3,
         "Effluent and emissions treatment neutralization before environmental discharge eliminates pollutant toxicity at the source.", "Pollution Control"),
        ("The basicity of ethanoic acid (CH₃COOH) is _____.",
         "4", "1", "2", "3", 1,
         "Ethanoic acid has only one ionizable carboxylic proton (-COOH) and is therefore monobasic (basicity = 1).", "Acids and Bases"),
        ("The colour of litmus in a neutral medium is _____.",
         "purple", "pink", "yellow", "orange", 0,
         "Litmus indicator exhibits a neutral purple shade intermediate between its red acidic and blue alkaline colors.", "Indicators"),
        ("The mathematical expression of pH is _____.",
         "log₁₀ [OH⁻]", "log₁₀(1 / [H₃O⁺])", "log₁₀ [H₃O⁺]", "log₁₀(1 / [OH⁻])", 1,
         "pH is defined as the negative logarithm of the hydrogen/hydroxonium ion concentration: pH = -log₁₀[H₃O⁺] = log₁₀(1 / [H₃O⁺]).", "pH Definition"),
        ("Which of the following salts will turn blue litmus red?",
         "Sodium tetrahydroxozincate (II)", "Potassium hydrogen tetraoxosulphate (VI)", "Sodium trioxocarbonate (IV)", "Zinc chloride hydroxide", 1,
         "KHSO₄ contains replaceable acidic hydrogen and ionizes in water to release H⁺ ions, turning blue litmus red.", "Acidic Salts"),
        ("Zn(s) + CuSO₄(aq) → ZnSO₄(aq) + Cu(s). In the reaction above, the oxidation number of the reducing agent changes from _____.",
         "0 to +4", "0 to +2", "+1 to +2", "+1 to +3", 1,
         "Zinc is the reducing agent and undergoes oxidation, increasing its oxidation state from 0 in Zn(s) to +2 in Zn²⁺.", "Redox Reactions"),
        ("H₂O(g) + C(s) → H₂(g) + CO(g). The oxidizing agent in the reaction above is _____.",
         "CO(g)", "C(s)", "H₂O(g)", "H₂(g)", 2,
         "Water vapour oxidizes carbon to CO while itself being reduced from H(+1) to H₂(0).", "Water Gas Reaction"),
        ("Calculate the quantity of electricity in coulombs required to liberate 10g of copper from a copper compound [Cu = 64, F = 96500 C mol⁻¹].",
         "32395.5", "30156.3", "60784.5", "15196.5", 1,
         "Cu²⁺ + 2e⁻ → Cu. Q = (mass × n × F) / M = (10 × 2 × 96500) / 64 = 30156.25 C.", "Electrolysis Calculations"),
        ("How many faradays of electricity are required to produce 0.25 mole of copper from a Cu²⁺ solution?",
         "1.00 F", "0.01 F", "0.05 F", "0.50 F", 3,
         "Reduction of 1 mole of Cu²⁺ requires 2 Faradays. Producing 0.25 mole requires 0.25 × 2 = 0.50 F.", "Faraday's Laws"),
        ("In the reaction coordinate diagram, Z represents _____.",
         "heat of reaction (enthalpy change)", "activation energy", "free energy", "entropy of reaction", 0,
         "Z denotes the net enthalpy difference between reactants and products (ΔH = H_products - H_reactants).", "Thermochemistry"),
        ("If the change in free energy (ΔG) of a system is -899 J mol⁻¹ and the entropy change is 10 J mol⁻¹ K⁻¹ at 25°C, calculate the enthalpy change.",
         "+2081 J mol⁻¹", "-2081 J mol⁻¹", "-649 J mol⁻¹", "+649 J mol⁻¹", 0,
         "T = 25 + 273 = 298 K. ΔG = ΔH - TΔS => ΔH = ΔG + TΔS = -899 + (298 × 10) = -899 + 2980 = +2081 J mol⁻¹.", "Thermodynamics"),
        ("In an equilibrium reaction, which of the following conditions indicates that maximum yield of the product will be obtained?",
         "Equilibrium constant is very large", "ΔH - TΔS = 0", "ΔH > TΔS", "Equilibrium constant is less than zero", 0,
         "A very large equilibrium constant (K >> 1) indicates that the equilibrium position lies predominantly on the side of products.", "Chemical Equilibrium"),
        ("In a chemical reaction, the change in concentration of a reactant with time is _____.",
         "entropy of reaction", "enthalpy of reaction", "rate of reaction", "order of reaction", 2,
         "Rate of reaction is defined as the decrease in concentration of reactants (or increase in products) per unit time.", "Chemical Kinetics"),
        ("Cr₂O₇²⁻(aq) + H₂O(l) ⇌ 2CrO₄²⁻(aq) + 2H⁺(aq). What happens to the reaction above when the hydrogen ion concentration is increased?",
         "more of the products will be formed", "the reaction will not proceed", "the equilibrium position will shift to the right", "the equilibrium position will shift to the left", 3,
         "Increasing [H⁺] (adding acid) shifts equilibrium to the left according to Le Chatelier's principle, turning the yellow chromate solution orange.", "Chemical Equilibrium"),
        ("Which of the following will liberate hydrogen from dilute tetraoxosulphate (VI) acid?",
         "Lead", "Magnesium", "Copper", "Gold", 1,
         "Magnesium lies above hydrogen in the reactivity series and reacts vigorously with dilute H₂SO₄ to release H₂ gas.", "Metals and Acids"),
        ("In the laboratory preparation of chlorine, the function of concentrated H₂SO₄ in the wash bottle is to _____.",
         "purify the gas", "dry the gas", "liquefy the gas", "remove odour", 1,
         "Concentrated tetraoxosulphate(VI) acid is a powerful hygroscopic dehydrating agent that absorbs water vapour, drying the chlorine gas.", "Preparation of Chlorine"),
        ("In the apparatus for preparing chlorine, the gas that is removed by the water wash bottle is _____.",
         "O₂", "SO₂", "HCl", "H₂", 2,
         "Water scrubs and dissolves volatile hydrogen chloride (HCl) gas fumes carried over from the reaction flask.", "Chlorine Chemistry"),
        ("Fluorine does not occur in the free state in nature because _____.",
         "it is a poisonous gas", "it belongs to the halogen family", "it is inert", "of its high reactivity", 3,
         "Fluorine has the highest electronegativity and lowest bond dissociation energy among halogens, making it violently reactive and only found combined.", "Halogens"),
        ("In the extraction of sodium by Downs cell, the anode is made of graphite/platinum because _____.",
         "sodium is formed at the anode", "chlorine is formed at the anode", "sodium does not react with platinum", "chlorine does not attack graphite/platinum", 3,
         "Chlorine gas evolved at the anode is highly corrosive and would attack reactive metals, requiring chemically inert carbon or platinum electrodes.", "Downs Process"),
        ("A compound that gives a brick-red colour to a non-luminous Bunsen flame contains _____.",
         "copper ions", "sodium ions", "calcium ions", "aluminium ions", 2,
         "Volatile calcium salts produce an intense brick-red coloration in flame tests.", "Flame Tests"),
        ("In the electrolytic extraction of calcium from molten calcium chloride, the cathode is made of _____.",
         "zinc", "graphite", "platinum", "iron", 3,
         "Calcium is discharged at an iron cathode (water-cooled) while chlorine is evolved at a graphite anode.", "Extraction of Calcium"),
        ("A few drops of NaOH solution was added to an unknown salt forming a white precipitate which is insoluble in excess solution. The cation likely present is _____.",
         "Zn²⁺", "Pb²⁺", "Ca²⁺", "Al³⁺", 2,
         "Calcium ions form white Ca(OH)₂ precipitate insoluble in excess NaOH, whereas Zn²⁺, Pb²⁺, and Al³⁺ precipitates are amphoteric and redissolve.", "Qualitative Analysis"),
        ("The general molecular formula of haloalkanes (alkyl halides) is _____.",
         "C_n H_{2n-1} X", "C_n H_{2n} X", "C_n H_{2n+2} X", "C_n H_{2n+1} X", 3,
         "Replacing one hydrogen atom of an alkane (CnH2n+2) with a halogen atom gives CnH2n+1X.", "Organic Chemistry"),
        ("The IUPAC nomenclature of CH₃–CH(Br)–CH(Cl)–CH₂OH is _____.",
         "2-bromo-3-chlorobutanol", "3-bromo-2-chlorobutanol", "3-chloro-2-bromobutanol", "2-chloro-3-bromobutanol", 1,
         "Numbering from the alkanol carbon (C1 with -OH): C2 carries -Cl and C3 carries -Br. Alphabetically: 3-bromo-2-chlorobutan-1-ol.", "IUPAC Nomenclature"),
        ("The alkanol obtained as a byproduct from the manufacture of soap is _____.",
         "propanol", "ethanol", "glycerol (propane-1,2,3-triol)", "methanol", 2,
         "Saponification of triglycerides yields sodium carboxylate soap and glycerol (glycerine).", "Fats and Oils"),
        ("Ethyne is passed through a hot tube containing an organo-nickel catalyst to produce _____.",
         "isoprene", "polythene", "ethanol", "benzene", 3,
         "Trimerization of three ethyne molecules (cyclization) at elevated temperatures produces benzene: 3C₂H₂ → C₆H₆.", "Alkynes"),
        ("Due to the unstable explosive nature of compressed ethyne, it is stored commercially by dissolving under pressure in _____.",
         "ethane-1,2-diol", "propanol", "ethanoic acid", "propanone (acetone)", 3,
         "Acetylene cylinders contain porous mass soaked in propanone (acetone), which dissolves up to 300 volumes of ethyne per volume at 12 atmospheres.", "Industrial Storage of Gases"),
        ("The process of converting starch to ethanol via maltose and glucose by enzyme action is _____.",
         "cracking", "distillation", "fermentation", "oxidation", 2,
         "Starch is hydrolyzed by diastase to maltose, by maltase to glucose, and converted to ethanol by zymase (fermentation).", "Industrial Fermentation"),
        ("The polymer used in making aircraft cockpit canopies and car rear lights is _____.",
         "Perspex (polymethyl methacrylate)", "Bakelite", "polystyrene", "polyacrylonitrile", 0,
         "Perspex is a rigid, shatter-resistant, optically transparent thermoplastic acrylic polymer.", "Polymers"),
        ("CH₃COOC₂H₅(l) + H₂O(l) ⇌ (H⁺) CH₃COOH(aq) + C₂H₅OH(aq). The purpose of H⁺ in the reaction above is to _____.",
         "increase the yield of products", "maintain the solution at a constant pH", "increase the rate of the hydrolysis", "decrease the rate of the reverse reaction", 2,
         "Hydrogen ions act as a homogeneous catalyst, lowering the activation energy and accelerating the rate of ester hydrolysis.", "Catalysis"),
        ("A hydrocarbon has an empirical formula CH and a vapour density of 39. Determine its molecular formula. [C = 12, H = 1]",
         "C₂H₆", "C₃H₈", "C₃H₄", "C₆H₆", 3,
         "Molar mass = 2 × 39 = 78 g mol⁻¹. Empirical mass (CH) = 13. n = 78 / 13 = 6. Molecular formula = C₆H₆ (benzene).", "Empirical & Molecular Formula"),
        ("Polystyrene is widely used as packaging material for fragile objects during transportation because of its _____.",
         "lightness", "low density and shock absorbency", "high density", "high compressibility", 1,
         "Expanded polystyrene foam has very low density, high impact absorption, and thermal insulation.", "Polymers"),
        ("The process of converting linear alkanes to branched chain and cyclic hydrocarbons by heating in the presence of a catalyst to improve petrol octane rating is _____.",
         "refining", "cracking", "reforming", "blending", 2,
         "Catalytic reforming restructures low-octane straight-chain alkanes into high-octane branched and aromatic hydrocarbons.", "Petroleum Refining"),
        ("The petroleum fraction that is used in heating furnaces in heavy industries is _____.",
         "diesel oil", "gasoline", "kerosene", "fuel oil / lubricating oil", 0,
         "Heavy diesel and residual fuel oils furnish intense thermal combustion in industrial boilers and furnaces.", "Petroleum Fractions")
    ]
    for idx, item in enumerate(pt4_data, 1):
        q, a, b, c, d, ans, exp, topic = item
        questions.append({
            "id": f"jamb_chm_pt4_{idx:02d}", "subject": "Chemistry", "topic": topic, "year": "PT. 4",
            "text": q, "a": a, "b": b, "c": c, "d": d, "ans": ans, "exp": exp,
            "label": f"JAMB Chemistry PT.4 • Q{idx}"
        })

    # -------------------------------------------------------------
    # PART 5 (Questions 1 to 40)
    # -------------------------------------------------------------
    pt5_data = [
        ("Which of the following statements is correct regarding the kinetic theory of gases?",
         "The average kinetic energy of a gas is directly proportional to its absolute temperature", "At constant temperature, the volume of a gas increases as the pressure increases", "The pressure of a gas is inversely proportional to its volume", "The temperature of gas is directly proportional to its volume", 0,
         "Postulate of kinetic theory: Average kinetic energy of gas molecules is directly proportional to absolute thermodynamic temperature (E_k ∝ T).", "Kinetic Theory"),
        ("Which are the correct IUPAC names for HCOOCH₃ and CH≡CH?",
         "Methyl methanoate and ethene", "Methanoic acid and ethyne", "Ethyl methanoate and ethyne", "Methyl methanoate and ethyne", 3,
         "HCOOCH₃ is the methyl ester of methanoic acid (methyl methanoate); CH≡CH is ethyne (acetylene).", "Organic Nomenclature"),
        ("A solution X on mixing with AgNO₃ solution gives a white precipitate soluble in NH₃(aq). A solution Y, when added to X, also gives a white precipitate which is soluble on boiling. Solution Y contains _____.",
         "Ag⁺ ion", "Pb²⁺ ion", "Pb⁴⁺ ion", "Zn²⁺ ion", 1,
         "Solution X contains chloride ions (AgCl is white, soluble in ammonia). Adding Pb²⁺ (solution Y) precipitates white PbCl₂, which dissolves in hot boiling water.", "Qualitative Analysis"),
        ("Methane is a member of the homologous series called _____.",
         "alkenes", "alcohols", "esters", "alkanes", 3,
         "Methane (CH₄) is the simplest member of the saturated paraffin hydrocarbons (alkanes).", "Hydrocarbons"),
        ("Which of the following bonds exist in crystalline ammonium chloride (NH₄Cl)?",
         "ionic and covalent only", "ionic and co-ordinate only", "ionic, covalent and co-ordinate", "covalent, co-ordinate and metallic", 2,
         "In NH₄Cl: three N-H bonds are normal covalent, one N→H bond is dative/coordinate, and the NH₄⁺ and Cl⁻ ions are held by electrovalent (ionic) attraction.", "Chemical Bonding"),
        ("Some copper (II) sulphate pentahydrate (CuSO₄·5H₂O) was heated at 120°C with results: Wt of crucible = 10.00g; Wt of crucible + CuSO₄·5H₂O = 14.98g; Wt of crucible + residue = 13.54g. How many molecules of water of crystallization were lost? [H=1, Cu=63.5, O=16, S=32]",
         "1", "2", "3", "4", 3,
         "Initial hydrate mass = 4.98 g. Residue mass = 3.54 g. Water lost = 1.44 g. Moles of water lost = 1.44 / 18 = 0.080 mol. Initial moles of CuSO₄·5H₂O = 4.98 / 249.5 = 0.020 mol. Water molecules lost per formula unit = 0.080 / 0.020 = 4 molecules (forming CuSO₄·H₂O).", "Hydrated Salts Calculations"),
        ("Which of the curves shown represents the relationship between volume (V) and pressure (P) of an ideal gas at constant temperature?",
         "1", "2", "3", "4", 1,
         "At constant temperature, Boyle's Law specifies that V ∝ 1/P, producing an equilateral rectangular hyperbola curve.", "Gas Laws"),
        ("12.0g of a mixture of potassium carbonate and potassium chloride was dissolved in a 250cm³ flask. 25cm³ of this solution required 40.00cm³ of 0.1M HCl for neutralization. What is the percentage by weight of K₂CO₃ in the mixture? [K=39, O=16, C=12]",
         "60%", "72%", "82%", "92%", 2,
         "Moles of HCl used = 0.040 × 0.1 = 0.004 mol. K₂CO₃ + 2HCl → 2KCl + H₂O + CO₂. Moles of K₂CO₃ in 25cm³ = 0.004 / 2 = 0.002 mol. Total moles in 250cm³ = 0.02 mol. Molar mass of K₂CO₃ = 138 g mol⁻¹. Mass of K₂CO₃ = 0.02 × 138 = 2.76 g. % by weight = (2.76 / 12.0) × 100% ≈ 82% (or closest stoichiometric grade).", "Volumetric Analysis"),
        ("Which of the following groups of physical properties increases from left to right across a Period of the Periodic Table?",
         "1 and 2", "1, 2 and 3", "1, 3 and 4", "1, 2, 3 and 4", 2,
         "Across a period: Ionization energy (1), Electronegativity (3), and Electron affinity (4) increase, whereas Atomic radius (2) decreases.", "Periodic Trends"),
        ("An element Z contains 90% of ⁸Z₁₆ and 10% of ⁸Z₁₈. Its relative atomic mass is _____.",
         "16.0", "16.2", "17.0", "17.8", 1,
         "R.A.M. = (90 × 16 + 10 × 18) / 100 = (1440 + 180) / 100 = 1620 / 100 = 16.2.", "Atomic Mass"),
        ("What are the possible oxidation numbers for an element if its atomic number is 17 (Chlorine)?",
         "-1 and 7", "-1 and 6", "-3 and 5", "-2 and 6", 0,
         "Chlorine displays oxidation numbers ranging from -1 (in chlorides) up to +7 (in perchlorates).", "Oxidation Numbers"),
        ("How many valence electrons are contained in the phosphorus atom represented by ³¹₁₅P?",
         "3", "5", "15", "31", 1,
         "Phosphorus (Z=15) has electronic configuration 2, 8, 5; its outermost valence shell contains 5 electrons.", "Atomic Structure"),
        ("10.0 dm³ of air containing H₂S as an impurity was passed through a solution of Pb(NO₃)₂ until all H₂S reacted. The precipitate of PbS weighed 5.02 g. Calculate percentage by volume of H₂S in the air. [Pb=207, S=32, Molar vol = 22.4 dm³]",
         "50.2%", "47.0%", "4.70%", "0.47%", 2,
         "Pb(NO₃)₂ + H₂S → PbS + 2HNO₃. Molar mass of PbS = 207 + 32 = 239 g mol⁻¹. Moles of PbS = 5.02 / 239 = 0.021 mol. Volume of H₂S at STP = 0.021 × 22.4 = 0.47 dm³. % by volume = (0.47 / 10.0) × 100% = 4.70%.", "Gas Volumetric Analysis"),
        ("A quantity of air was passed through a weighed amount of alkaline pyrogallol. An increase in the weight of the pyrogallol would result from the absorption of _____.",
         "nitrogen", "neon", "argon", "oxygen", 3,
         "Alkaline solution of pyrogallol (1,2,3-trihydroxybenzene) quantitatively absorbs atmospheric oxygen.", "Gas Analysis"),
        ("Water for municipal town supply is chlorinated to make it free from _____.",
         "bad odour", "bacteria", "temporary hardness", "permanent hardness", 1,
         "Chlorination destroys pathogenic bacteria and water-borne infectious disease agents.", "Water Treatment"),
        ("4.0 g of sodium hydroxide in 250cm³ of solution contains a concentration of _____ [NaOH = 40 g mol⁻¹].",
         "0.40 mol dm⁻³", "0.10 mol dm⁻³", "0.04 mol dm⁻³", "0.02 mol dm⁻³", 0,
         "Moles = 4.0 / 40 = 0.10 mol. Volume = 0.25 dm³. Concentration = 0.10 / 0.25 = 0.40 mol dm⁻³.", "Concentration"),
        ("A major ecological effect of oil pollution in coastal marine waters is the _____.",
         "destruction of marine life", "desalination of the water", "increase in the acidity of the water", "detoxification of the water", 0,
         "Oil slicks block dissolved oxygen exchange and coat fish gills, killing aquatic fauna and mangrove biomes.", "Environmental Pollution"),
        ("In general, an increase in temperature increases the solubility of a solid solute in water because _____.",
         "more solute molecules collide with each other", "most solutes dissolve with the evolution of heat", "more solute molecules dissociate at higher temperatures", "most solutes dissolve with absorption of heat (endothermic)", 3,
         "For salts with endothermic heats of solution (ΔH_soln > 0), raising temperature shifts dissolution forward per Le Chatelier's principle.", "Solubility"),
        ("The relatively high boiling points of alkanols compared to alkanes of similar molar mass are due to _____.",
         "ionic bonding", "aromatic character", "covalent bonding", "intermolecular hydrogen bonding", 3,
         "Hydroxyl (-OH) groups form intermolecular hydrogen bonds requiring substantial thermal energy to break.", "Alkanols"),
        ("Given that 15.00cm³ of H₂SO₄ was required to completely neutralize 25.00cm³ of 0.125 mol dm⁻³ NaOH, calculate the molar concentration of the acid solution.",
         "0.925 mol dm⁻³", "0.156 mol dm⁻³", "0.104 mol dm⁻³", "0.023 mol dm⁻³", 2,
         "H₂SO₄ + 2NaOH → Na₂SO₄ + 2H₂O. C_a = (C_b × V_b × n_a) / (V_a × n_b) = (0.125 × 25 × 1) / (15 × 2) = 3.125 / 30 = 0.104 mol dm⁻³.", "Volumetric Neutralization"),
        ("What volume of 0.1 mol dm⁻³ solution of tetraoxosulphate (VI) acid would be needed to dissolve 2.86g of sodium trioxocarbonate (IV) decahydrate crystals? [Na=23, C=12, O=16, H=1, S=32]",
         "20 cm³", "40 cm³", "80 cm³", "100 cm³", 3,
         "Molar mass of Na₂CO₃·10H₂O = 106 + 180 = 286 g mol⁻¹. Moles of salt = 2.86 / 286 = 0.010 mol. Reaction: Na₂CO₃ + H₂SO₄ → Na₂SO₄ + H₂O + CO₂. Moles of acid needed = 0.010 mol. Volume = 0.010 / 0.1 = 0.100 dm³ = 100 cm³.", "Stoichiometry"),
        ("The solution with the lowest pH value (highest acidity) is _____.",
         "5 ml of M/10 HCl", "10 ml of M/10 HCl", "15 ml of M/5 HCl", "20 ml of M/8 HCl", 2,
         "Acidity depends on molar concentration: M/5 = 0.20 M (pH ≈ 0.70), which is more concentrated than M/8 (0.125 M) and M/10 (0.10 M).", "Acids and pH"),
        ("In which order does the light-sensitivity of the silver halides decrease?",
         "AgI > AgCl > AgBr", "AgCl > AgI > AgBr", "AgBr > AgCl > AgI", "AgCl > AgBr > AgI", 2,
         "Silver bromide (AgBr) is most photosensitive (used in photographic emulsion), followed by AgCl and AgI.", "Silver Halides"),
        ("A metal M displaces zinc from zinc chloride solution. This shows that _____.",
         "M is more electronegative than Zinc", "Zinc is above hydrogen in the series", "M is more electropositive than zinc", "electrons flow from zinc to M", 2,
         "Metals that displace Zn²⁺ must have a more negative standard reduction potential and higher electropositivity.", "Electrochemical Series"),
        ("Steam changes the colour of anhydrous cobalt (II) chloride paper from _____.",
         "blue to pink", "white to red", "white to green", "blue to white", 0,
         "Anhydrous cobalt(II) chloride is blue and hydrates upon reaction with steam to pink CoCl₂·6H₂O.", "Test for Water"),
        ("When at equilibrium, which of the reactions below will shift to the right if pressure is increased at constant temperature?",
         "2SO₃(g) ⇌ 2SO₂(g) + O₂(g)", "2CO₂(g) ⇌ 2CO(g) + O₂(g)", "2H₂(g) + O₂(g) ⇌ 2H₂O(g)", "2NO(g) ⇌ N₂(g) + O₂(g)", 2,
         "2H₂(g) + O₂(g) ⇌ 2H₂O(g) has 3 moles of gaseous reactants and 2 moles of product; increased pressure favours the side with fewer gas moles.", "Le Chatelier's Principle"),
        ("2CO(g) + O₂(g) → 2CO₂(g). Given that ΔH[CO] = -110.4 kJ mol⁻¹ and ΔH[CO₂] = -393.0 kJ mol⁻¹, the energy change for the reaction is _____.",
         "-503.7 kJ", "-565.2 kJ / -282.6 kJ", "+282.6 kJ", "+503.7 kJ", 1,
         "ΔH = 2(-393.0) - 2(-110.4) = -786.0 - (-220.8) = -565.2 kJ (or -282.6 kJ per mole of CO).", "Thermochemistry"),
        ("Which of these properties gives a solid its definite shape?",
         "Strong intermolecular attraction", "High melting point", "High boiling point", "Weak intermolecular attraction", 0,
         "Strong cohesive electrostatic forces lock particles into fixed vibrating positions, preventing fluidity and maintaining shape.", "States of Matter"),
        ("When a crystal was added to the clear solution of its salt, the crystal did not dissolve and the solution remained unchanged. This showed that the solution was _____.",
         "supersaturated", "concentrated", "unsaturated", "saturated", 3,
         "In a saturated solution at dynamic equilibrium, no additional solute can dissolve at that temperature.", "Solubility"),
        ("If the electron configuration of an element is 1s² 2s² 2p⁵, how many unpaired electrons are there?",
         "2", "5", "1", "4", 2,
         "The p subshell contains 5 electrons: two paired orbitals (2px², 2py²) and one singly occupied orbital (2pz¹), giving exactly 1 unpaired electron.", "Atomic Orbitals"),
        ("The substance that is used in the steel industry for the removal of carbon, sulphur and phosphorus impurities from pig iron is _____.",
         "oxygen", "chlorine", "nitrogen", "hydrogen", 0,
         "In the Basic Oxygen Steelmaking process, high-purity oxygen is blown through molten iron to oxidize carbon to CO/CO₂ and silicon/phosphorus to slag.", "Extraction of Iron"),
        ("Hydrogen sulphide gas (H₂S) can act as _____.",
         "an oxidizing agent", "a dehydrating agent", "a bleaching agent", "a reducing agent / precipitating agent", 3,
         "H₂S reacts with metallic salt solutions to precipitate insoluble metallic sulphides (e.g. PbS, CuS).", "Inorganic Chemistry: Sulphur"),
        ("Which of the following is used as an oxidizer in rocket fuel?",
         "HNO₃", "CH₃COOH", "H₂SO₄", "HCl", 0,
         "Fuming nitric acid (HNO₃) is a powerful liquid oxidant used in rocket propellants.", "Industrial Chemistry"),
        ("The bleaching action of chlorine is effective due to the presence of _____.",
         "Hydrogen chloride", "Water", "Air", "Oxygen", 1,
         "Chlorine must react with water to form chloric(I) acid (HOCl), which releases nascent oxygen responsible for bleaching.", "Halogens"),
        ("Mineral acids are usually added to commercial hydrogen peroxide to _____.",
         "oxidize it", "decompose it", "minimize its decomposition", "reduce it to water and oxygen", 2,
         "Traces of mineral acid act as negative catalysts, stabilizing H₂O₂ against thermal and catalytic breakdown.", "Catalysis"),
        ("Aluminium containers are frequently used to transport concentrated trioxonitrate (V) acid because aluminium _____.",
         "has a low density", "does not react with the acid (passivation)", "does not corrode", "has a silvery-white appearance", 1,
         "Concentrated HNO₃ forms an impervious adherent passive oxide layer (Al₂O₃) preventing further chemical attack.", "Corrosion and Passivity"),
        ("Ethyne is passed through a hot tube containing organo-nickel catalyst to produce _____.",
         "isoprene", "polythene", "ethanol", "benzene", 3,
         "Cyclic trimerization of three ethyne molecules over a nickel catalyst yields benzene (C₆H₆).", "Hydrocarbons: Alkynes"),
        ("The process of converting starch to ethanol is _____.",
         "cracking", "distillation", "fermentation", "oxidation", 2,
         "Industrial fermentation converts starch to maltose, glucose, and finally ethanol by yeast enzymes.", "Applied Chemistry"),
        ("An endothermic reaction is one during which heat is absorbed and can be represented by the symbol +ΔH. Which combination completes the definition?",
         "liberated, -ΔH", "liberated, +ΔH", "absorbed, -ΔH", "absorbed, +ΔH", 3,
         "Endothermic processes absorb thermal energy from surroundings, designated by positive enthalpy change (+ΔH).", "Thermochemistry"),
        ("Consider the exothermic reaction 2SO₂(g) + O₂(g) ⇌ 2SO₃(g). If the temperature of the reaction is reduced from 800°C to 500°C, and no other change takes place, then _____.",
         "the reaction rate increases", "concentration of SO₂ decreases", "concentration of SO₂ increases", "SO₂ gas becomes unreactive", 1,
         "According to Le Chatelier's principle, lowering temperature favours the forward exothermic reaction, converting more SO₂ into SO₃ (concentration of SO₂ decreases).", "Equilibrium")
    ]
    for idx, item in enumerate(pt5_data, 1):
        q, a, b, c, d, ans, exp, topic = item
        questions.append({
            "id": f"jamb_chm_pt5_{idx:02d}", "subject": "Chemistry", "topic": topic, "year": "PT. 5",
            "text": q, "a": a, "b": b, "c": c, "d": d, "ans": ans, "exp": exp,
            "label": f"JAMB Chemistry PT.5 • Q{idx}"
        })

    return questions
