# coding=utf-8
"""
Complete JAMB Commerce Parts 1 to 5 Data (240 Questions).
Directly transcribed from user's attached JAMB Commerce Past Questions Objective PT 1-5.
"""

def get_all_commerce_questions():
    questions = []

    # -------------------------------------------------------------
    # PART 1 (Questions 1 to 50)
    # -------------------------------------------------------------
    pt1_data = [
        ("Which question paper Type of commerce is given to you?", "Type A", "Type B", "Type C", "Type D", 2, "JAMB examination paper type identification question.", "General Introduction"),
        ("The most important function of commerce is in _____.", "enhancing business relationships", "helping people to improve their profits", "facilitating exchange among individuals and firms", "assisting trade through banking and insurance", 2, "Commerce bridges the gap between producers and consumers by facilitating the distribution and exchange of goods and services.", "Nature of Commerce"),
        ("The three main classification of occupation are _____.", "construction, trade and services", "manufacturing, industry and services", "farming, banking and trading", "industry, commerce and services", 3, "Occupations are broadly divided into industry (extractive, manufacturing, constructive), commerce (trade and aids to trade), and direct/indirect services.", "Occupation"),
        ("An oil exploration company is engaged in _____.", "tertiary production", "constructive occupation", "extractive occupation", "secondary production", 2, "Extractive occupations extract natural resources and raw materials directly from the earth, sea, or air.", "Production"),
        ("Service rendered to the public is provided by _____.", "government", "civil servants", "professionals", "domestic servants", 1, "Civil servants provide indirect public administrative services to the general citizenry.", "Services"),
        ("The creation of goods and services to satisfy human wants is referred to as _____.", "manufacturing", "commercialization", "production", "entrepreneurship", 2, "In economics and commerce, production is the creation of utility to satisfy human needs.", "Production"),
        ("Which of the following is a limitation of division of labour?", "Decline in craftsmanship", "Monotony of work", "Reduction in output", "Reduction in labour force", 1, "A major drawback of division of labour is monotony and boredom resulting from performing repetitive tasks.", "Division of Labour"),
        ("Resources obtained from the extractive sector that are transformed into finished products are examples of _____.", "primary production", "tertiary production", "direct production", "secondary production", 3, "Secondary production involves converting raw materials into semi-finished or finished manufactured products.", "Stages of Production"),
        ("From the organizational tree of Commerce (Commerce -> Trade & Aids to Trade), what does I stand for?", "Aids to trade", "Publicity", "Home trade", "Advertising", 0, "Commerce is divided into Trade and Aids to Trade (banking, insurance, warehousing, transport, advertising, communication).", "Branches of Commerce"),
        ("An individual that links the producer with the retailer is _____.", "an agent", "a wholesaler", "an entrepreneur", "a principal", 1, "The wholesaler buys in bulk from the manufacturer/producer and breaks bulk to supply retailers.", "Channels of Distribution"),
        ("One of the functions of a retailer is the _____.", "financing of production activities", "provision of credit facilities to relations", "provision of jobs for customers", "breaking of bulk", 3, "Retailers buy convenient quantities from wholesalers and sell in small units to final consumers (breaking bulk).", "Retail Trade"),
        ("The main aim of selling directly to the consumers by manufacturers is to _____.", "reduce transportation cost", "make contact with individual consumers", "discourage the activities of middlemen", "maximize profit margin", 3, "Direct marketing eliminates middleman markups, enabling manufacturers to maximize overall margins while offering competitive prices.", "Direct Selling"),
        ("Balance of payment problems arise if a country's _____.", "exports are more than imports", "imports are more than exports", "currency devaluation", "invisible exports are more than visible exports", 1, "A balance of payments deficit occurs when total payments for imports exceed receipts from exports.", "International Trade"),
        ("The three components of a country's balance of payments are _____.", "current account, capital account and monetary movement account", "capital account, trade account and business record", "sales account, profit and loss account and capital account", "monetary movement account, trade account and sales ledger", 0, "A country's balance of payments consists of the Current Account, Capital Account, and Official Financing/Monetary Movement Account.", "Balance of Payments"),
        ("A document that indicates obligation that is transferable by delivery and endorsement is a _____.", "bill of lading", "bill of exchange", "documentary evidence", "negotiable instrument", 3, "A negotiable instrument is a document guaranteeing the payment of a specific amount of money, transferable by delivery or endorsement.", "Negotiable Instruments"),
        ("The document which can be exchange for a bill of lading is _____.", "freight note", "mate receipt", "export invoice", "ship report", 1, "The mate's receipt is issued by the ship's officer acknowledging cargo loading and is subsequently exchanged for the signed bill of lading.", "Shipping Documents"),
        ("The price quoted which includes the cost of insurance, freight and all delivery charges to the importer's warehouse is _____.", "Free Alongside Ship", "Franco", "Free on Board", "Free on Rail", 1, "Franco (or Free Domicile) price covers all costs including carriage, insurance, customs, and delivery right to the buyer's premises.", "Trade Terms"),
        ("The purchase of goods under the CWO system of payment implies that _____.", "money must be enclosed when ordering", "payment must be made on delivery", "payment must be made within few days", "cash must be paid on the spot", 0, "Cash With Order (CWO) mandates that full remittance accompany the purchase order before shipment.", "Terms of Payment"),
        ("The most effective but limited medium of advertising in Nigeria is _____.", "billboard", "television", "newspaper", "radio", 1, "Television provides high visual and auditory impact but has historically been limited by electrical power availability in rural communities.", "Advertising"),
        ("A cheque that has been drawn but not presented for payment can still be honoured _____.", "within 6 months", "after 9 months", "within 9 months", "after 6 months", 0, "In standard banking practice, a cheque remains valid and legally payable within six months of its date before becoming stale.", "Banking"),
        ("The major source of income to commercial banks is _____.", "loans", "deposits", "interest", "overdrafts", 2, "Commercial banks earn the bulk of their revenue from interest charged on loans, advances, and credit facilities.", "Commercial Banking"),
        ("An ancillary to trade that easily links suppliers with consumers is _____.", "tourism", "banking", "communication", "transportation", 2, "Communication transmits trade enquiries, market data, and orders between suppliers and buyers.", "Aids to Trade"),
        ("Mr. Lawal insured his warehouse against burglary but it was later gutted by fire. This implies that _____.", "the loss should be borne by the insurer", "Mr. Lawal is liable only for half of the estimated loss", "the insurer should make a consolation payment for the loss", "the loss should be borne by Mr. Lawal", 3, "Under the doctrine of proximate cause, an insurer only compensates for losses resulting directly from the specific insured peril.", "Insurance Principles"),
        ("The agreement of insurers to spread risks among themselves is a major feature of _____.", "reinsurance", "life insurance", "underwriter", "marine insurance", 0, "Reinsurance allows an insurance company to transfer portions of its risk portfolio to other insurers to prevent catastrophic insolvency.", "Insurance"),
        ("Inbound tourism occurs when _____.", "non-residents of a country travel to other countries", "resident of a country travel to another country", "non-resident of a country travel within it", "resident of a country travel within it", 2, "Inbound tourism refers to visits to a host country by visitors who are not residents of that country.", "Tourism"),
        ("One of the major disadvantages of pipeline transportation is its _____.", "high cost of construction", "limitation in scope", "vulnerability to climate changes", "high maintenance cost", 1, "Pipelines are inflexible and limited in scope because they can transport only liquid or gaseous fluids along fixed routes.", "Transportation"),
        ("The business organization that can effectively combine management with control is _____.", "private limited liability company", "sole proprietorship", "public limited liability company", "co-operation society", 1, "The sole proprietor exercises absolute personal authority, unity of command, and direct supervision without corporate bureaucracy.", "Business Organizations"),
        ("When two or more companies agree to execute a project too large for one to handle, this is referred to as _____.", "an amalgamation", "a cartel", "a merger", "a consortium", 3, "A consortium is a temporary association of independent corporate enterprises pooled together to execute a major project.", "Business Combinations"),
        ("In the event of voluntary liquidation, the appointment of a liquidator is the responsibility of the _____.", "directors", "creditors", "promoters", "court", 1, "In a creditors' voluntary liquidation, the creditors appoint a liquidator to wind up the firm's affairs.", "Company Liquidation"),
        ("A source of business financing which involves pledging of a specific asset is _____.", "bond", "mortgage", "debentures", "loan", 1, "A mortgage is a debt instrument secured by the collateral of specified real estate or fixed property.", "Business Finance"),
        ("An example of a trade association is _____.", "ALGON", "NLC", "NURTW", "NULGE", 2, "The National Union of Road Transport Workers (NURTW) is a recognized commercial trade association protecting transport operators.", "Trade Associations"),
        ("A broker is an agent who links a potential investor with _____.", "a shareholder who wants to register a company", "other members of the exchange who want to trade", "government official on the exchange", "a quoted company", 1, "Stockbrokers act as intermediary agents buying and selling securities on behalf of clients among exchange market participants.", "Stock Exchange"),
        ("Second-tier Securities Market differs from the First-tier Securities Market in that the former is _____.", "highly restricted", "regulated by the SEC", "regulated by the NIPC", "less restricted", 3, "The Second-tier Securities Market (SSM) provides less stringent listing rules to encourage small and medium scale enterprises.", "Capital Market"),
        ("A communication process providing information for decision-making in an organization is the _____.", "Management information System", "Transmission Control Protocol", "Information Retrieval System", "File Transfer Protocol", 0, "A Management Information System (MIS) collects and analyzes data to support executive organizational decisions.", "Management & Communication"),
        ("The managerial ability of a supervisor in an organization may be underutilized if the _____.", "morale of the supervised is high", "span of control is wide", "span of control is narrow", "morale of the supervisor is low", 2, "A very narrow span of control assigns too few subordinates to a supervisor, leading to underutilization of supervisory capacity.", "Span of Control"),
        ("The arrangement and interrelationship of the various components and positions of a business is referred to as _____.", "organizational structure", "clarity of objective", "unity of direction", "line structure", 0, "Organizational structure defines formal lines of authority, responsibility, and departmental relationships.", "Organizational Structure"),
        ("The variety of goods and services which a company offers for sale is its _____.", "place mix", "promotion mix", "price mix", "product mix", 3, "Product mix refers to the complete portfolio of product lines and items offered for sale by a commercial entity.", "Marketing Mix"),
        ("Activities undertaken to create awareness for goods by conducting contests is _____.", "marketing concept", "consumerism", "sales promotion", "marketing mix", 2, "Sales promotions utilize contests, free samples, vouchers, and discounts to stimulate consumer buying interest.", "Sales Promotion"),
        ("The slogan, 'a wonderful world', used by a communication network is a form of _____.", "product differentiation", "persuasive advertising", "publicity", "packaging", 1, "Persuasive advertising uses emotional appeals and catchy slogans to attract customer patronage.", "Advertising"),
        ("To make a simple contract valid, the intention must be _____.", "legal and written", "legal and binding", "legal and attractive", "legal and harmonious", 1, "For a valid simple contract, there must be intention to create legal and binding relations between the parties.", "Law of Contract"),
        ("The major parties to an agency relationship are the _____.", "principal and the creditor", "Bailee and the bailor", "principal and the agent", "shareholder and the creditor", 2, "An agency relationship exists between a principal who delegates authority and an agent authorized to act on their behalf.", "Law of Agency"),
        ("One of the obligations of an employer to an employee is to _____.", "indemnify him against liabilities incurred on duty", "award scholarship to his children", "terminate his appointment without prior notice", "indemnify him against injuries caused through negligence", 0, "An employer has a common-law duty to indemnify an employee for legal liabilities and expenses incurred in discharging their lawful duties.", "Employment Law"),
        ("The body charged with the responsibility of regulating foods and drugs in Nigeria is the _____.", "SON", "NDLEA", "NAFDAC", "CAC", 2, "NAFDAC (National Agency for Food and Drug Administration and Control) regulates drugs, food, and medical consumables in Nigeria.", "Consumer Protection"),
        ("The physical components of a computer system refers to the _____.", "system unit", "hardware", "software", "compact disk", 1, "Hardware refers to the tangible electronic and mechanical equipment comprising a computer system.", "Computer Systems"),
        ("An example of a computer operating system is _____.", "the PageMaker", "the Word Perfect", "Microsoft Word 2000", "Windows 2000", 3, "Windows 2000 is an operating system that manages computer hardware and system resources.", "Operating Systems"),
        ("Intranet differs from extranet in that the former _____.", "requires a modem before it could be used", "can generally be accessed by the public", "is restricted to employees of an organization", "requires internet protocols", 2, "An intranet is a private internal network restricted solely to authorized organizational staff.", "Business Networks"),
        ("A software application which enables a user to display and interact with texts, images and videos is the _____.", "web server", "Internet Protocol", "CorelDraw", "web browser", 3, "A web browser retrieves, renders, and displays multimedia web pages from the internet.", "Internet Applications"),
        ("A predominant make-up language for web pages is the _____.", "IP", "HTTP", "HTML", "TCP", 2, "HTML (HyperText Markup Language) is the standard markup language used to structure content on the World Wide Web.", "Web Technologies"),
        ("The symbol @ in an internet mail address is used to _____.", "separate the user name from the machine name", "link the user with other Internet users", "locate the addresses of Internet users", "link the user with the machine", 0, "In email syntax, the '@' delimiter separates the individual account username from the host domain name.", "Electronic Mail"),
        ("A business organization is said to be socially responsible when it _____.", "gets involved in issues relating to the society", "rewards its staff for long-term service", "offers discounts to customers", "invites the public to its annual general meetings", 0, "Corporate Social Responsibility entails proactive business participation in solving community and environmental concerns.", "Social Responsibility")
    ]
    for idx, item in enumerate(pt1_data, 1):
        q, a, b, c, d, ans, exp, topic = item
        questions.append({
            "id": f"jamb_com_pt1_{idx:02d}", "subject": "Commerce", "topic": topic, "year": "PT. 1",
            "text": q, "a": a, "b": b, "c": c, "d": d, "ans": ans, "exp": exp,
            "label": f"JAMB Commerce PT.1 • Q{idx}"
        })

    # -------------------------------------------------------------
    # PART 2 (Questions 1 to 50)
    # -------------------------------------------------------------
    pt2_data = [
        ("Which question paper type of commerce as indicated above is given to you?", "Type Green", "Type Purple", "Type Red", "Type Yellow", 1, "JAMB examination instructions require candidate verification of their paper type.", "General Introduction"),
        ("One of the major benefits of commerce to government is to _____.", "improve the standard of living", "generate revenue for growth and development", "encourage cooperation among public organisations", "encourage the development of sociocultural values", 1, "Commerce yields substantial public revenue through excise duties, VAT, corporate income tax, and customs tariffs.", "Importance of Commerce"),
        ("An example of an activity in the construction industry is _____.", "blacksmithing", "bricklaying", "car assembling", "shoemaking", 1, "Bricklaying is a primary construction trade involved in building civil structures and edifices.", "Industry"),
        ("One of the inputs in production that can be motivated by remuneration is _____.", "capital", "entrepreneur", "labour", "land", 2, "Labour is human mental and physical exertion motivated by wages, salaries, and monetary bonuses.", "Factors of Production"),
        ("The allocation of tasks to different skills in a production process is referred to as _____.", "production technique", "production function", "division of labour", "delegation of responsibility", 2, "Division of labour assigns workers to specific segments of an overall production chain based on specialization.", "Division of Labour"),
        ("The sales of goods through a medium that accepts money and delivers the items to the customer is _____.", "an automated teller machine", "a vending machine", "a counting machine", "a branding machine", 1, "A vending machine is an automated retail dispensary that accepts cash/cards and dispenses selected merchandise.", "Retail Trade"),
        ("The main purpose of branding is to _____.", "create identity for a product", "make a product look attractive", "create product awareness", "increase sales volume", 0, "Branding establishes distinct identity, trademark recognition, and differentiation from rival products.", "Marketing & Branding"),
        ("The basis for international trade is embedded in the principle of _____.", "absolute advantage", "globalization", "deregulation", "comparative advantage", 3, "David Ricardo's law of comparative advantage explains that nations trade to benefit from differences in relative opportunity costs.", "International Trade"),
        ("The major problem encountered in international trade is that of _____.", "distance", "differences in culture", "politics", "differences in currency", 3, "Dealing across diverse foreign currencies and foreign exchange volatility constitutes a primary hurdle in cross-border commerce.", "Foreign Trade"),
        ("The document a seller uses in dispatching goods to a customer by a carrier is _____.", "a bill of lading", "an invoice", "an advice note", "a delivery note", 3, "A delivery note accompanies dispatched goods to be signed by the consignee as evidence of physical receipt.", "Trade Documents"),
        ("A document which serves as an order with details of goods required by an intending purchaser is _____.", "a freight note", "an indent", "a bill of lading", "a way bill", 1, "An indent is an official order placed with an overseas agent specifying quantities, prices, and shipment terms.", "Foreign Trade Documents"),
        ("If a customer pays within nine days of receiving goods and takes advantage of 3% off the invoice price, this is stated as _____.", "3/9; net 30", "9/27; net 30", "30; net 9/3", "9/30; net 3", 0, "Trade credit terms '3/9; net 30' mean a 3% cash discount is granted if settled within 9 days, else the full bill is due in 30 days.", "Trade Discounts"),
        ("Which of the following is a characteristic of a bearer cheque?", "it is made with transverse lines", "it is made payable to whoever presents it", "it is made without transverse lines", "it is only payable into the payees account", 1, "A bearer cheque is payable on demand to anyone presenting it at the banking counter without proof of identity.", "Banking Instruments"),
        ("A bill of exchange paid before its due date at an amount less than its face value is said to have been _____.", "accepted", "rejected", "discounted", "dishonoured", 2, "Discounting a bill of exchange involves selling it to a bank before maturity for cash minus a discount charge.", "Commercial Paper"),
        ("The most effective type of advertising for branded products is _____.", "mass advertising", "persuasive advertising", "informative advertising", "competitive advertising", 3, "Competitive advertising aims to persuade consumers that a branded item is superior to identical rival offerings.", "Advertising"),
        ("A current account holder pays fees for services in form of _____.", "bank charges", "interest rates", "commission on turnover", "minimum lending rate", 2, "Commercial banks historically charged Commission on Turnover (COT) or account maintenance fees for handling current accounts.", "Banking Operations"),
        ("Printed messages sent by cable are recorded as _____.", "telegram", "SMS", "telex", "MMS", 2, "Telex allowed text messages to be exchanged internationally across a switched network of teleprinters.", "Communication"),
        ("Communication is relevant to business activities because it _____.", "creates wealth for people", "reduces the cost and risk of travelling", "connects people", "enhances delivery of goods and services", 1, "Efficient business telecommunication permits instant negotiation and transaction without expensive physical travel.", "Commercial Communication"),
        ("The right of an insurance company to stand in place of an insured against a third party, who is liable for the occurrence of a loss, is the principle of _____.", "proximate cause", "insurable interest", "insurance priority", "subrogation", 3, "Subrogation grants the insurer all legal rights against liable third parties once the claim is indemnified.", "Insurance Principles"),
        ("Assurance is different from insurance in that the former is based on _____.", "probability", "possibility", "risk", "uncertainty", 0, "Assurance covers events that are bound to happen sooner or later (such as death), whereas insurance covers contingent risks.", "Insurance vs Assurance"),
        ("A person who undertakes life insurance is said to be an _____.", "insurer", "assurer", "assured", "insured", 2, "In life assurance, the person taking out the cover on their own life is designated the assured.", "Life Assurance"),
        ("Tourism serves the purpose of _____.", "cross-cultural understanding and peaceful interaction", "opening values for leaving the country", "economic development and naturalization", "exploiting the country's natural endowment", 0, "Tourism fosters cross-cultural exchange, global goodwill, and mutual international understanding.", "Tourism"),
        ("The type of letters that are delivered through the normal mail or by airmail express service is referred to as _____.", "inland letters", "registered letters", "airmail letters express letters", "express letters", 3, "Express letters receive priority handling and rapid courier dispatch over ordinary post.", "Postal Services"),
        ("A business organization that exploits the capabilities of a member to remedy the weaknesses of another is _____.", "joint venture", "partnership", "nominal partnership", "cooperative", 1, "A partnership combines complementary skills, capital, and expertise of partners to offset individual weaknesses.", "Partnerships"),
        ("The most important business objective is to _____.", "improve investments", "provide quality products", "target consumers for satisfaction", "carve a niche for the business", 2, "Under the modern marketing concept, the supreme objective is creating satisfied customers at a profit.", "Business Objectives"),
        ("In case of a liquidation of a public limited liability company, those that are first paid are _____.", "ordinary shareholders", "preference shareholders", "cumulative preference shareholders", "debenture holders", 3, "Debenture holders are secured creditors and hold priority of repayment before any equity or preference shareholders.", "Company Liquidation"),
        ("A feature common to public and private limited liability companies is that _____.", "both can sue and be sued", "the minimum number of their shareholders is five", "the transfer of their shares is not restricted", "their annual accounts are published for public use", 0, "Both corporate forms are incorporated legal entities with distinct legal personality capable of suing and being sued.", "Company Law"),
        ("A business organization can obtain long term financing through _____.", "bank overdraft", "the sale of shares", "credit purchases", "bureau de change", 1, "Issuing equity shares provides permanent capital that never requires repayment during business solvency.", "Long-term Finance"),
        ("The portion of the authorized share capital given out to the public for subscription is _____.", "called-up capital", "issued capital", "paid-up capital", "reserved capital", 1, "Issued capital is the nominal value of shares actually offered to and taken up by shareholders.", "Corporate Capital"),
        ("A company has an authorized capital of 40 million shares at N1 each, out of which 32 million are issued and fully paid-up. What happens to the remaining 8 million shares?", "it has been issued but not paid-up", "it has been applied for but not issued", "it is not paid-up", "it has not yet been issued", 3, "The remaining 8 million shares represent unissued capital kept in reserve for future public subscription.", "Company Finance"),
        ("If the rate of turnover of a company in 1999 was 4 times while the average stock was ₦49,600, determine the turnover.", "₦199,400", "₦198,400", "₦100,200", "₦99,200", 1, "Turnover (Cost of Sales) = Rate of turnover × Average stock = 4 × ₦49,600 = ₦198,400.", "Commercial Calculations"),
        ("Given: opening stock ₦1,800, purchases ₦2,800, sales ₦8,000, closing stock ₦350, carriage on sales ₦500. Calculate the value of the unused stock.", "₦800", "₦500", "₦350", "₦320", 2, "Unused stock at the close of an accounting trading period is simply the closing stock (₦350).", "Trading Account"),
        ("The main objective of a trade association is to _____.", "protect its members against litigation", "boost the trade of its members", "secure credit for its members", "protect its members against victimization", 1, "Trade associations exist to promote, safeguard, and advance the collective business interests and profitability of members.", "Trade Associations"),
        ("The promotion and protection of trade, industry and agriculture through trade fairs is a function of _____.", "NACRDB", "NACCIMA", "the consumer protection council", "the chamber of commerce", 3, "Chambers of Commerce organize international and domestic trade exhibitions to promote commerce and enterprise.", "Chambers of Commerce"),
        ("Dealing in quoted securities on the Nigerian Stock Exchange is restricted to authorized _____.", "companies", "brokers", "investors", "principals", 1, "Only licensed dealing member firms and registered stockbrokers execute trades on the floor of the Stock Exchange.", "Stock Exchange"),
        ("Securities that entitle the investor to coupon rates are _____.", "bonds", "equities", "warrants", "treasury bills", 0, "Bonds are debt securities carrying a fixed annual nominal rate of interest called the coupon rate.", "Securities"),
        ("Under what management function will the motivation of employees fall?", "staffing", "controlling", "organizing", "directing", 3, "Directing (or leading) involves guiding, supervising, communicating with, and motivating workforce personnel.", "Management Functions"),
        ("The promotion of team spirit in an organization is referred to as _____.", "unity of direction", "esprit de corps", "unity of purpose", "discipline", 1, "Henri Fayol's principle of 'esprit de corps' advocates fostering workplace harmony and team solidarity.", "Principles of Management"),
        ("One of the characteristics of a good organizational chart is that it should _____.", "be rigid", "show government policy", "facilitate communication", "be acceptable", 2, "An organizational chart clarifies reporting relationships, division of duties, and official communication pathways.", "Organizational Structure"),
        ("An organization which focuses on consumer satisfaction is practicing _____.", "consumerism", "market segmentation", "selling concept", "marketing concept", 3, "The marketing concept asserts that corporate success depends on determining customer needs and delivering customer satisfaction.", "Marketing Concepts"),
        ("Goods and services are made available to consumers through _____.", "the channel of distribution", "sales promotion", "the advertising agency", "the middle men", 0, "The channel of distribution provides the logistical conduit transferring title and goods from producer to user.", "Distribution Channels"),
        ("A person who in consideration for an extra commission takes responsibility for goods sold on credit and in case of default is a _____.", "commission agent", "del credere agent", "broker", "factor", 1, "A del credere agent guarantees payment for goods sold on credit to third parties in exchange for an extra fee.", "Law of Agency"),
        ("Yahaya bought a piece of furniture on a credit sale agreement from Ahmed and resold it to Ali before all instalments were made. The court upheld that Ahmed could not recover possession of the items from Ali. The reason for the judgement was because _____.", "ownership was transferred on completion of instalment", "ownership was transferred on delivery", "Yahaya could not pass title to a third party", "Ali was still indebted to Yahaya", 1, "Under a credit sale agreement (unlike hire purchase), ownership and property in the goods pass immediately upon initial delivery.", "Commercial Law: Sales of Goods"),
        ("The body which ensures that consumers are protected against harmful products in Nigeria is _____.", "NAFDAC", "NDLEA", "SON", "CPC", 2, "The Standards Organisation of Nigeria (SON) sets industrial standards and inspects consumer products against safety hazards.", "Consumer Protection"),
        ("The process of decoding data in a computer is known as _____.", "dilution", "default drive", "decryption", "data security", 2, "Decryption transforms encoded or encrypted data back into its original readable plain text format.", "Information Technology"),
        ("Which of the following is a type of system software?", "utility programmes", "registers", "hard drives", "packages", 0, "Utility programs (like antivirus, disk defragmenters) are system software maintaining computer performance.", "System Software"),
        ("Computers that process all data as binary zeros and ones are _____.", "analog computers", "digital computers", "hybrid computers", "desktop computers", 1, "Digital computers process discrete numerical data using binary digits (0 and 1).", "Computer Hardware"),
        ("Modern means of payment is greatly facilitated by _____.", "e-commerce", "paper money", "e-banking", "credit transfer", 2, "Electronic banking (e-banking) enables instant fund transfers, ATM transactions, and digital payment clearance.", "Banking"),
        ("The provision of quality and safe products which guarantee the health of consumers is an example of _____.", "quality control", "price control", "civic responsibility", "social responsibility", 3, "Consumer protection and product safety represent core corporate social responsibilities.", "Business Ethics"),
        ("A business organization must always consider the overall effect of its actions on the _____.", "competitor", "product", "profit", "society", 3, "Modern enterprises must gauge the external socio-environmental impacts of their policies on the broader society.", "Business Environment")
    ]
    for idx, item in enumerate(pt2_data, 1):
        q, a, b, c, d, ans, exp, topic = item
        questions.append({
            "id": f"jamb_com_pt2_{idx:02d}", "subject": "Commerce", "topic": topic, "year": "PT. 2",
            "text": q, "a": a, "b": b, "c": c, "d": d, "ans": ans, "exp": exp,
            "label": f"JAMB Commerce PT.2 • Q{idx}"
        })

    # -------------------------------------------------------------
    # PART 3 (Questions 1 to 50)
    # -------------------------------------------------------------
    pt3_data = [
        ("Which question paper Type of commerce is given to you?", "Type D", "Type I", "Type B", "Type U", 0, "JAMB examination instructions require verification of question paper type.", "General Introduction"),
        ("The type of labour that makes use of physical effort in production processes is the _____.", "unskilled labour", "skilled labour", "blue-collar job", "white-collar job", 0, "Unskilled labour relies predominantly on manual physical exertion with little specialized technical training.", "Labour & Employment"),
        ("The assembling of products into usable forms is known as _____.", "creation", "manufacturing", "construction", "formation", 1, "Manufacturing is the industrial processing and assembling of component parts into finished usable goods.", "Industry"),
        ("The final link in the chain of distribution is _____.", "middlemen", "wholesaling", "consumer", "retailing", 2, "The final consumer is the ultimate user who consumes goods to satisfy personal wants.", "Channels of Distribution"),
        ("A country is said to be experiencing an unfavourable balance of trade if her _____.", "exports exceed imports", "visible exports exceed visible imports", "imports and exports are equal", "visible imports exceed visible exports", 3, "A deficit or unfavourable balance of trade occurs when the value of visible imports exceeds visible exports.", "Balance of Trade"),
        ("Trading position of Nigeria is the same as her _____.", "desire to trade with many countries", "willingness to grant credit to foreigners", "balance of trade", "terms of trade", 3, "The terms of trade describe a country's purchasing power and exchange position in international trade.", "International Trade"),
        ("The role of customs and excise authority includes the _____.", "provision of a good transport system to facilitate imports and exports", "provision of security at the port", "control of the flow of goods in and out of the country", "provision of dockyards for ship repairs", 2, "The Customs Service regulates cross-border commodity flow, enforces trade tariffs, and intercepts prohibited contraband.", "Customs & Excise"),
        ("The document lodged with the customs authorities before a ship can leave the port is a _____.", "shipping note", "ship report", "ship manifest", "dock warrant", 2, "A ship manifest details the full cargo, crew, and destination presented to customs before sailing clearance.", "Shipping Documents"),
        ("The document which must be endorsed by the ambassador of a country of destination before shipment of goods is a _____.", "consular invoice", "certificate of origin", "bill of lading", "close indent", 0, "A consular invoice is certified by the importing country's consul stationed in the exporting territory to verify values.", "Shipping Documents"),
        ("A country's terms of trade are said to improve when the ratio of her export _____.", "decreases", "remains constant", "increases", "equals import", 2, "Terms of trade improve when export price indices rise relative to import price indices (export/import ratio increases).", "International Trade"),
        ("Which of the following advertising medium appeals to only the literate in the society?", "radio advertising", "print media advertising", "television advertising", "cinema advertising", 1, "Print media (newspapers, magazines, trade journals) requires literacy to read and comprehend the message.", "Advertising Media"),
        ("The two main forms of communication are _____.", "oral and written", "verbal and non-verbal", "e-mail and fax", "traditional and modern media", 1, "Communication is classified into verbal communication (spoken or written words) and non-verbal communication (gestures, signs).", "Business Communication"),
        ("The most reliable and efficient means of conveying urgent documents is through _____.", "postal order", "ordinary letters", "registered letters", "courier services", 3, "Dedicated courier services provide tracked, prompt, door-to-door physical parcel and document dispatch.", "Communication"),
        ("An undertaking given by a person to another assuring his integrity is _____.", "proximate cause", "fidelity guarantee", "subrogation", "insurable interest", 1, "Fidelity guarantee insurance protects employers against financial loss from employee dishonesty, fraud, or embezzlement.", "Insurance"),
        ("If Mr. N takes a fire insurance policy with average clause on property valued at ₦100,000 for ₦25,000, and suffers an actual loss of ₦30,000, his compensation will be _____.", "₦5,000", "₦7,500", "₦70,000", "₦75,000", 1, "Under the Average Clause: Compensation = (Sum Insured / Actual Value) × Actual Loss = (₦25,000 / ₦100,000) × ₦30,000 = ₦7,500.", "Insurance Calculations"),
        ("What insurance principle has Mr. P violated if he decides to overstate the actual value of his property?", "Indemnity", "Insurable interest", "Uberrimae fidei", "Subrogation", 2, "Uberrimae fidei (utmost good faith) requires full, accurate disclosure of all material facts without overstating values.", "Insurance Principles"),
        ("The difference between indemnity insurance and non-indemnity insurance is that the latter provides _____.", "cover for exporters against risks", "cover for importers against risks", "full payment to the insured", "consolation payment to the insured", 2, "Non-indemnity policies (such as life and personal accident assurance) pay a fixed, pre-agreed sum on the occurrence of the event.", "Insurance"),
        ("An importance of warehousing is in the _____.", "production of goods", "transportation of goods", "importation of goods", "repackaging of goods", 3, "Warehouses provide facilities for processing, grading, sorting, and repackaging goods before final marketing.", "Warehousing"),
        ("In order to increase the capital owned, a sole trader may _____.", "seek for bank loan", "issue debentures", "acquire extra shop fittings on credit", "draw less of his profit for personal use", 3, "Retained earnings from reduced personal drawings directly increase the proprietor's owner equity and net worth.", "Sole Proprietorship"),
        ("A business partner who provides capital but abstains from participation in administration of a firm is a _____.", "general partner", "nominal partner", "secret partner", "dormant partner", 3, "A dormant (sleeping) partner supplies capital and shares in profits/losses but takes no active part in business management.", "Partnership"),
        ("Which of the following will not be stated in a Memorandum of Association?", "Name clause", "rights of shareholders", "object clause", "registered office", 1, "Shareholder rights, voting rules, and internal managerial regulations are detailed in the Articles of Association.", "Company Documents"),
        ("The amount of authorized capital that shareholders have subscribed to is _____.", "issued share capital", "authorized share capital", "owner's equity", "working capital", 0, "Issued (subscribed) capital represents the portion of authorized share capital agreed to be taken up by investors.", "Corporate Capital"),
        ("The rate of turnover of a firm in a given year is 5 times while the average stock is ₦12,500. What is the turnover of the firm?", "₦24,000", "₦46,500", "₦62,500", "₦65,000", 2, "Turnover = Rate of turnover × Average stock = 5 × ₦12,500 = ₦62,500.", "Commercial Calculations"),
        ("A lawyer that defrauds his client may be de-robed by the Nigerian Bar Association in order to _____.", "protect other lawyers", "protect the integrity of the association", "compensate the affected client", "prevent the client from suing the association", 1, "Professional disciplinary sanctions preserve ethical standards, public confidence, and institutional integrity.", "Professional Associations"),
        ("In the Nigerian GSM industry, a parliament is organized by the Nigerian Communications Commission in order to _____.", "increase profit of service providers", "protect the interest of government", "encourage more people into the business", "protect the interest of consumers", 3, "Consumer advocacy forums and telecoms consumer parliaments resolve grievances and safeguard consumer rights.", "Consumer Protection"),
        ("Trade fairs in Nigeria are organised by _____.", "the Federal Government", "Manufacturers' Association of Nigeria", "Ministry of Commerce and Industry", "Chambers of Commerce", 3, "Chambers of Commerce, Industry, Mines and Agriculture organize trade exhibitions and commercial fairs.", "Chambers of Commerce"),
        ("Money is generally accepted for transactions due to _____.", "the legal backing", "the rule of law", "its acceptability in the global market", "the Central Bank Governor's signature", 0, "Money is universally accepted because the state declares it legal tender with statutory backing.", "Money and Banking"),
        ("Which of the following is a quality of money?", "Availability", "Scarcity", "Indivisibility", "Convertibility", 1, "Scarcity (relative scarcity) ensures money retains purchasing power and does not lose value through excess abundance.", "Qualities of Money"),
        ("Money can simply be referred to as a _____.", "measure of value", "standard of value", "means of settlement", "durable asset for doing business", 2, "The fundamental economic role of money is serving as a recognized legal means of settling debts and transactions.", "Functions of Money"),
        ("Gilt-edged securities are issued mainly by _____.", "individuals", "non-governmental organisations", "Government", "multi-national companies", 2, "Gilt-edged securities are sovereign debt instruments issued by the Federal Government carrying virtually no risk of default.", "Securities"),
        ("The initial function of a manager is _____.", "setting up an organisation", "coordinating", "planning", "provision of welfare package", 2, "Planning is the foundational management function determining objectives and mapping actions before execution begins.", "Principles of Management"),
        ("The most suitable organizational structure for small or medium sized enterprises is _____.", "line structure", "staff structure", "committee structure", "functional structure", 0, "A line organizational structure provides direct, simple, unambiguous scalar authority well-suited to small firms.", "Organizational Structure"),
        ("In a staff-authority relationship, the opinion of a specialist in one department to another is _____.", "a directive", "an advice", "a command", "a delegation", 1, "Staff authority has an advisory capacity; specialists counsel line managers without commanding execution.", "Management Authority"),
        ("Management of a business involves the development of ideas for the _____.", "distribution of goods and services that human wants", "transportation of goods and services that human wants", "transfer of title of ownership of goods and services to individuals", "production of goods and services that satisfy human needs", 3, "Business management harnesses resources to innovate, produce, and market utilities that fulfill human needs.", "Business Management"),
        ("Which of the following is used as a pricing policy?", "Packaging", "Market selection", "Labelling", "Market skimming", 3, "Market skimming charges high introductory prices to recover innovation costs from price-insensitive early adopters.", "Pricing Policies"),
        ("The essential utility derived from the use of a product is known as _____.", "augmented benefit", "branded benefit", "core benefit", "formal benefit", 2, "The core benefit is the fundamental service or solution the customer is actually purchasing.", "Marketing Management"),
        ("The breaking down of a market into separate and identifiable elements is known as _____.", "differentiation", "segmentation", "skimming", "penetration", 1, "Market segmentation divides a broad consumer market into sub-groups sharing similar needs or characteristics.", "Market Segmentation"),
        ("A contract that is acknowledged before the law court is referred to as _____.", "informal contract", "formal contract", "contract of records", "specialty contract", 2, "A contract of record is an obligation confirmed by a court of law (e.g. judgment debts, recognizances).", "Law of Contract"),
        ("An agent employed to sell goods delivered to him by the principal is referred to as a _____.", "special agent", "del credere agent", "factor", "universal agent", 2, "A factor is an agent entrusted with possession and control of goods with authority to sell them in their own name.", "Law of Agency"),
        ("A motor dealer who agreed to sell a car to Mr. X but delivered it to Mr. Y on the delivery date agreed with Mr. X has discharged the contract by _____.", "performance", "frustration", "an agreement", "breach", 3, "Failing to deliver agreed subject matter to the buyer constitutes an actionable repudiation and fundamental breach.", "Discharge of Contract"),
        ("A contract can be terminated through _____.", "physical combat", "family intervention", "frustration", "consultation", 2, "A contract terminates by frustration when unforeseen external circumstances render performance legally or physically impossible.", "Law of Contract"),
        ("The right to retain possession of goods until the contract price is paid is referred to as _____.", "a promise", "ultra vires", "a breach", "a lien", 3, "A possessory lien entitles a seller to hold goods as security until full purchase payment is satisfied.", "Sale of Goods"),
        ("The sole legal right held by the author to publish his book is _____.", "trademark", "copyright", "patent right", "bookmark", 1, "Copyright grants exclusive statutory protection to authors of original literary, musical, and artistic works.", "Intellectual Property"),
        ("The process of transferring data from one computer to another is referred to as _____.", "downloading", "faxing", "browsing", "decoding", 0, "Downloading copies digital files from a remote server or host computer to a local computer terminal.", "Computer Networks"),
        ("The physical component of a computer system is _____.", "software", "hardware", "hard disk", "floppy disk", 1, "Hardware encompasses all physical circuitry, peripheral devices, and mechanical units of a computer.", "Computer Systems"),
        ("A computer accessory through which information can be retrieved is the _____.", "hard disk", "input device", "control unit", "floppy disk", 0, "A hard disk is a permanent secondary storage medium from which recorded data and software files are retrieved.", "Computer Storage"),
        ("The type of computer software used mainly for management information is _____.", "Corel draw", "AutoCAD", "database", "word perfect", 2, "Database management systems (DBMS) organize, process, and query large datasets for executive information.", "Business Applications"),
        ("To meet security requirements before gaining access to data, a computer operator supplies _____.", "an e-mail address", "a yahoo address", "a password", "a modem", 2, "Passwords verify user identity and enforce access authentication across computer networks.", "Computer Security"),
        ("A major factor that affects business operations is _____.", "technology", "supply", "product", "rivalry", 0, "Technological innovations rapidly transform production techniques, delivery channels, and business models.", "Business Environment"),
        ("The environmental hazard that is most difficult to control is _____.", "land pollution", "water pollution", "air pollution", "political unrest", 2, "Air pollution disperses rapidly and across international atmospheric boundaries, making it exceptionally difficult to contain.", "Environmental Hazards")
    ]
    for idx, item in enumerate(pt3_data, 1):
        q, a, b, c, d, ans, exp, topic = item
        questions.append({
            "id": f"jamb_com_pt3_{idx:02d}", "subject": "Commerce", "topic": topic, "year": "PT. 3",
            "text": q, "a": a, "b": b, "c": c, "d": d, "ans": ans, "exp": exp,
            "label": f"JAMB Commerce PT.3 • Q{idx}"
        })

    # -------------------------------------------------------------
    # PART 4 (Questions 1 to 50)
    # -------------------------------------------------------------
    pt4_data = [
        ("Which paper type of commerce is given to you?", "Type F", "Type E", "Type L", "Type S", 2, "JAMB examination instructions require verification of question paper type.", "General Introduction"),
        ("Cooperation and friendliness are enhanced among nations through interdependence necessitated by _____.", "tourism", "commerce", "agriculture", "socio-cultural activities", 1, "International commerce links nations together in mutual economic interdependence and diplomatic goodwill.", "Importance of Commerce"),
        ("One of the products of an extractive industry is _____.", "an airplane", "an iron ore", "a shoe", "a textile material", 1, "Iron ore is mined directly from natural mineral deposits, representing primary extractive output.", "Industry"),
        ("The payment for direct service is usually made by the _____.", "local authority", "community", "government", "individual", 3, "Direct personal services (domestic staff, barbers, private tutors) are paid directly by individual consumers.", "Occupations"),
        ("An important feature of land is that it _____.", "has an elastic supply", "is an active factor of production", "is heterogeneous in nature", "is subject to returns to scale", 2, "Land is heterogeneous, non-reproducible, and varies widely in fertility, location, and mineral content.", "Factors of Production"),
        ("One of the major determinants of the volume of production is _____.", "the market size", "the availability of banks", "sex distribution", "government policy", 0, "The extent of effective market demand and population size determines the profitable volume of production.", "Production"),
        ("Mrs. Jones who lives in the riverine community of Rivers State makes her living through crabbing and fishing. This type of occupation she is in is _____.", "commercial", "manufacturing", "service", "extractive", 3, "Fishing and crabbing extract living biological resources directly from water bodies, constituting extractive occupation.", "Occupations"),
        ("To eliminate middlemen, there should be a retail outlet such as _____.", "producer co-operative", "consumer co-operative", "multiple shop", "departmental store", 1, "Consumer cooperative societies purchase directly from producers in bulk and sell to member consumers at cost price, bypassing middlemen.", "Cooperative Societies"),
        ("The document issued by a port authority for goods deposited is a _____.", "bill of lading", "bill of sight", "consular invoice", "warehouse warrant", 3, "A warehouse warrant certifies title to specified goods deposited in a bonded or port warehouse.", "Warehousing Documents"),
        ("The document submitted to the customs authority when full description of imported goods is not provided is _____.", "a bill of sight", "an invoice", "an indent", "a bill of entry", 0, "A bill of sight allows importers to examine landed cargo in the presence of customs officials when shipping invoices are incomplete.", "Customs Documents"),
        ("The role of customs and excise authority includes the _____.", "control of the flow of goods in and out of the country", "control of security agents within and out of the borders", "provision of dockyards for ship repairs and maintenance", "provision of transport system to facilitate imports and exports", 0, "Customs authorities monitor import/export flows, levy tariffs, prevent smuggling, and enforce trade bans.", "Customs & Excise"),
        ("A document recording the transactions of an organization with its customer for a specified period which normally shows the indebtedness of one to the other is a _____.", "statement of account", "consular invoice", "proforma invoice", "statement of affairs", 0, "A statement of account summarizes all debit and credit entries between a merchant and customer over a billing period.", "Trade Documents"),
        ("In response to an inquiry from a customer, a wholesaler is expected to send back _____.", "a consignment note", "an order", "a quotation", "an advice note", 2, "A quotation states prices, delivery periods, discount terms, and conditions in response to a customer's trade enquiry.", "Terms of Trade"),
        ("A carton of noodles valued at ₦2,000 was invoiced at ₦200 only. The accounting procedure to correct this error is to issue _____.", "an invoice for ₦200", "a debit note for ₦2,000", "a credit note for ₦1,800", "a debit note for ₦1,800", 3, "A debit note is issued to charge the buyer for the undercharged difference (₦2,000 - ₦200 = ₦1,800).", "Commercial Documents"),
        ("Tourists with no fixed address in a town may receive their letters from post office through a _____.", "poste restante", "parcel post", "private mail bag", "recorded delivery", 0, "Poste restante holds transient mail at a designated post office until collected in person by travelers.", "Postal Services"),
        ("Endowment policy in insurance business is an aspect of _____.", "accident insurance policy", "fidelity guarantee insurance policy", "motor vehicle insurance policy", "life assurance policy", 3, "An endowment policy is a life assurance contract that pays a fixed capital sum either on a specified maturity date or at prior death.", "Life Assurance"),
        ("Insurance against burglary is an example of _____.", "indemnity insurance", "fidelity guarantee insurance", "non-insurable risk", "non-indemnity insurance", 0, "Property and burglary covers are indemnity contracts restoring the policyholder to their pre-loss financial position.", "Insurance"),
        ("The principle which requires the insurance company to disclose to the proposer all material facts of the risk to be covered is _____.", "subrogation", "proximate cause", "uberrimae fidei", "contribution", 2, "Uberrimae fidei mandates complete good faith and transparent disclosure of all material risk details by both parties.", "Insurance Principles"),
        ("The insurance principle that allows an insurance company to take over the rights of the insured once he has been compensated is _____.", "indemnity", "proximate cause", "utmost good faith", "subrogation", 3, "Subrogation prevents double recovery by allowing the insurer to pursue third-party wrongdoers after settling the claim.", "Insurance Principles"),
        ("A trader who experienced loss through fire can be restored by _____.", "an insurance company", "a trade association", "the bank", "an advertising agency", 0, "A fire insurance policy indemnifies the property owner against actual damage caused by accidental conflagration.", "Insurance"),
        ("The distribution of petroleum products in Nigeria is predominantly handled through _____.", "rail", "road", "sea", "air", 1, "In Nigeria, road transport via tanker haulage carries the overwhelming share of distributed refined petroleum.", "Transportation"),
        ("The deliberate effort geared towards discarding some cargoes in order to lighten the vessel is _____.", "caveat emptor", "uberrimae fidei", "demurrage", "jettison", 3, "Jettison is the intentional throwing overboard of cargo to lighten a ship in danger of distress or sinking.", "Marine Insurance"),
        ("The major aim of establishing a public corporation is to _____.", "establish a monopoly", "provide essential services", "provide employment opportunities", "encourage specialization", 1, "Public corporations provide critical social utilities (water, power, sanitation) on a non-profit-maximizing basis.", "Public Corporations"),
        ("The coming together of a manufacturing business with a firm that markets its products is _____.", "backward integration", "a consortium", "forward integration", "a syndicate", 2, "Forward vertical integration unites a manufacturer with downstream distributors or retail outlets.", "Business Combinations"),
        ("An association of voluntary organizations that work together for a common aim while retaining their independence is a _____.", "syndicate", "merger", "cartel", "consortium", 3, "A consortium associates independent enterprises for a joint commercial undertaking without loss of corporate identity.", "Business Combinations"),
        ("The document that explains the types of shares available for sale to the public is _____.", "a prospectus", "an invoice", "an open indent", "a closed indent", 0, "A prospectus is a legal notice issued by a public company inviting subscriptions for shares or debentures.", "Company Documents"),
        ("Which of the following attracts only interest but leaves the capital unpaid?", "a long-term loan", "a development bond", "a redeemable bond", "an irredeemable bond", 3, "Irredeemable (perpetual) bonds pay regular coupon interest indefinitely without returning the principal sum.", "Securities"),
        ("A loan to a customer with a cheque account at a bank in which the account is allowed to go into debit is _____.", "overdraft", "advance", "interest", "commission", 0, "An overdraft permits a current account holder to draw funds exceeding their credit balance up to an agreed limit.", "Commercial Banking"),
        ("Part payments made on allotted shares by subscribers is usually the _____.", "subscribed capital", "authorized capital", "issued capital", "called-up capital", 3, "Called-up capital represents the sum requested by the company to be paid up on allotted shares.", "Corporate Finance"),
        ("The net profit is the excess of gross profit and sources of income over all the expenses. This implies that net profit is _____.", "the difference between gross profit and trade expenses", "the difference between gross profit and net sales", "sales less cost of sales including sales returns", "opening stock add purchases less closing stock", 0, "Net profit is calculated by deducting operating and general business expenses from gross profit.", "Trading and Profit & Loss"),
        ("A form of money with face value which is greater than the value of the metal content is _____.", "legal tender", "bank notes", "token money", "commodity money", 2, "Token money has an intrinsic metallic commodity value far below its legally declared face value.", "Money"),
        ("An agent who transacts business with the broker in the stock exchange is a _____.", "stag", "bull", "del credere", "jobber", 3, "Stock jobbers are market makers who deal in securities on the exchange floor exclusively with stockbrokers.", "Stock Exchange"),
        ("A document sent by a broker to his client to confirm a purchase of sale made on his behalf is _____.", "delivery note", "consignment note", "transfer form", "contract note", 3, "A contract note specifies prices, fees, and settlement terms of stock transactions executed for the client.", "Stock Exchange Documents"),
        ("Cum div differs from ex div in that, the latter _____.", "entitles the purchaser to receive a company's current dividend", "entitles the vendor to receive a company's current dividend", "confirms a purchase or sale made on behalf of a share holder", "is a document used to transfer ownership of shares", 1, "When shares trade 'ex div' (excluding dividend), the seller (vendor) retains the declared dividend distribution.", "Stock Terms"),
        ("The payment made by a speculator to the buyer when he is unable to deliver stocks on the agreed date is _____.", "arbitrage", "Franco", "contango", "backwardation", 3, "Backwardation is a penalty fee paid by a seller unable to deliver shares on the settlement date to postpone delivery.", "Stock Exchange"),
        ("Which of the following regulates and controls the activities in the Nigerian Stock Exchange?", "BPE", "SEC", "NDIC", "CBN", 1, "The Securities and Exchange Commission (SEC) is the apex regulatory agency overseeing the Nigerian capital market.", "Capital Market Regulation"),
        ("The principle of management that emphasizes on the number of subordinates under the direct supervision of a manager is _____.", "span of control", "unity of command", "scalar chain", "unity of direction", 0, "Span of control defines the optimal number of subordinates reporting directly to a single executive supervisor.", "Principles of Management"),
        ("Marketing differs from selling in that, the latter only creates _____.", "possession utility", "marginal utility", "form utility", "place utility", 0, "Selling focuses narrowly on transferring ownership (possession utility), whereas marketing encompasses product creation, pricing, and placement.", "Marketing vs Selling"),
        ("A business that focuses attention on the quality of the goods produced by precisely knowing what the consumers desire is said to be operating the _____.", "product mix", "promotion mix", "marketing concept", "product orientation", 2, "The marketing concept aligns production with verified consumer desires, tastes, and expectations.", "Marketing Concepts"),
        ("The physical and psychological satisfaction a customer derives from the purchase of goods and services is _____.", "price mix", "product mix", "marketing mix", "promotion mix", 1, "The total product concept encompasses both functional performance and psychological consumer satisfactions.", "Product Mix"),
        ("Which of the following aspects of marketing stimulates buying by providing free gifts?", "personal selling", "sales promotion", "advertising", "publicity", 1, "Sales promotion incorporates promotional incentives like premiums, contest prizes, and free samples.", "Sales Promotion"),
        ("Which of the following is used as pricing policy?", "labelling", "packaging", "market selection", "market skimming", 3, "Market skimming is a strategic pricing mechanism recovering developmental expenditure from premium buyers.", "Pricing Strategies"),
        ("Mr. Taiwo entered into a contract to let a car to Mr. Bunmi for his wedding for two days. However, the car had an accident before the first day. Mr. Bunmi attempted to claim damages but failed. This implies the contract was terminated by _____.", "bankruptcy", "frustration", "breach", "lapse of time", 1, "Destruction of the essential subject matter without fault of either party discharges the agreement by frustration.", "Law of Contract"),
        ("Hire purchase is advantageous to the seller in that _____.", "it elevates his living standard", "his turnover will increase", "people pay in instalment", "it enhances high level of patronage", 1, "Permitting deferred payments broadens customer purchasing power, substantially expanding the seller's turnover.", "Hire Purchase"),
        ("The difference between a factor and a broker is that the former _____.", "is licensed to sell goods on auction", "has a lien on the goods he possesses", "is not in possession of the goods", "cannot sell in his own name", 1, "A factor takes physical possession of merchandise and therefore enjoys an enforceable possessory lien for fees.", "Law of Agency"),
        ("A contract which is devoid of legal effect is _____.", "void contract", "unenforceable contract", "voidable contract", "valid contract", 0, "A void contract is destitute of legal effect ab initio and confers no enforceable rights upon either party.", "Law of Contract"),
        ("The three functional units of a modern computer are _____.", "input, processor and output units", "processor, FORTRAN and output units", "black box, output and input units", "basic, COBOL and output units", 0, "Computer system architecture consists of Input Units, the Central Processing Unit, and Output Units.", "Computer Systems"),
        ("Which of the following computers can be used in weather forecast?", "Hybrid computer", "Digital computer", "Mainframe computer", "Analog computer", 0, "Hybrid computers combine analog sensors (measuring continuous temperatures/pressures) with digital computing speed.", "Types of Computers"),
        ("A Digital Versatile Disk is an example of a _____.", "transmission control protocol", "microprocessor", "file transfer protocol", "computer storage device", 3, "A Digital Versatile Disk (DVD) is an optical secondary data storage device.", "Computer Hardware"),
        ("The social responsibility factor of an organization is geared towards _____.", "contributing to the sustenance and development of its host community", "operating without disrupting the very essence of the environment", "tackling the socio-economic problems of the state", "meeting the needs and demands of the shareholders", 0, "Corporate social responsibility focuses heavily on advancing the socio-economic welfare of host communities.", "Corporate Social Responsibility")
    ]
    for idx, item in enumerate(pt4_data, 1):
        q, a, b, c, d, ans, exp, topic = item
        questions.append({
            "id": f"jamb_com_pt4_{idx:02d}", "subject": "Commerce", "topic": topic, "year": "PT. 4",
            "text": q, "a": a, "b": b, "c": c, "d": d, "ans": ans, "exp": exp,
            "label": f"JAMB Commerce PT.4 • Q{idx}"
        })

    # -------------------------------------------------------------
    # PART 5 (Questions 1 to 40)
    # -------------------------------------------------------------
    pt5_data = [
        ("A proforma invoice is not required when _____.", "dealing regularly with a customer", "quoting for the supply of goods", "goods are sent on approval", "final prices are uncertain", 0, "Regular customers with established credit lines receive normal sales invoices rather than proforma estimates.", "Trade Documents"),
        ("A distinguishing characteristic of a limited liability company is that _____.", "is a collection of many sole proprietors", "can sue and be sued", "is a multiple partnership", "has limited resources", 1, "Incorporation confers separate legal personality (Salomon v Salomon), allowing the company to sue and be sued in its corporate name.", "Company Law"),
        ("Construction activities include the building of houses and roads as well as _____.", "shoe-making", "black smithing", "brick laying", "car assembling", 2, "Bricklaying is an integral craft in construction operations.", "Industry"),
        ("Which of the following information is contained in the Articles of Association of a limited liability company?", "Objectives of the company", "Rights and obligations of directors", "Amount of share capital", "Limitation of liability of share holders", 1, "The Articles of Association govern internal management, directors' powers, and shareholder voting procedures.", "Company Documents"),
        ("Which of the following contributed least to the evolution of commercial activities in Nigeria?", "Development of banks", "Development of transportation", "Development of currencies", "Development of trader's union", 3, "Traders' unions regulate local retail disputes but played a minor role compared to modern banking, currencies, and transport systems.", "History of Commerce in Nigeria"),
        ("One of the factors which critically determines the choice of occupation is _____.", "skill", "training", "interest", "aptitude", 0, "Specialized vocational skill is the decisive qualification governing occupational eligibility.", "Occupations"),
        ("Tourists with no fixed address in a town may receive letters from the post office through _____.", "poste restante", "recorded delivery", "post master", "parcel post", 0, "Poste restante allows travelers to receive general delivery mail held at the central post office.", "Postal Services"),
        ("On liquidation of a public limited liability company, the residual owners are the _____.", "debenture holders", "creditors", "preference shareholders", "ordinary shareholders", 3, "Ordinary shareholders bear residual risk and receive whatever surplus assets remain after all debts and preference claims are settled.", "Company Finance"),
        ("The major factors that facilitate merchandising are _____.", "banking, insurance and transportation", "management, insurance, and advertising", "communication, advertising, and banking", "trading, warehousing and production", 0, "Banking (finance), insurance (protection), and transportation (movement) are the core aids supporting merchandising.", "Aids to Trade"),
        ("The pivot on which the wheel of commerce rotates is _____.", "tariff", "taxation", "price", "trade", 3, "Trade—the buying and selling of goods—is the core axis around which all commercial auxiliary services revolve.", "Nature of Commerce"),
        ("The major procedures in the purchase and sale of goods are enquiry _____.", "order, sale and invoice", "quotation, order and invoice", "placement, order and invoice", "bargain, order and invoice.", 1, "Standard trade transactions progress through Enquiry -> Quotation -> Order -> Invoice -> Delivery -> Receipt.", "Trade Procedures"),
        ("An advantage of hire purchase to the customer is the _____.", "low interest rate chargeable", "increase in turnover and profits", "economics of scale in production", "possession of goods before payment", 3, "Hire purchase allows buyers immediate physical possession and utility of valuable assets while paying in installments.", "Hire Purchase"),
        ("The agency in Nigeria which ensures that products confirm to government quality specifications is the _____.", "Nigerian Consumers Association", "Standards Organization of Nigeria", "Nigerian Chamber of Commerce", "Manufacturer's Association of Nigeria", 1, "The Standards Organisation of Nigeria (SON) enforces mandatory industrial quality standards and product certifications.", "Consumer Protection"),
        ("The most widely used computer language that focuses on solving science oriented problems is _____.", "COBOL", "ADA", "BASIC", "FORTRAN", 3, "FORTRAN (Formula Translation) was developed specifically for complex numeric, mathematical, and scientific computing.", "Computer Languages"),
        ("An essential factor for evaluating the different sources of funds for a business is the _____.", "ownership structure of the business concern", "burden of cost and repayment", "size and the type of the business", "decree establishing the business", 1, "Management must evaluate the interest burden, security pledges, and cash flow strain imposed by repayment schedules.", "Business Finance"),
        ("In the primary market, new shares are issued through _____.", "personal selling, publicity and advertising", "advertising, a prospectus and a bill of exchange", "a prospectus, an offer for sale and placing", "a prospectus, offer for sale and a bill of exchange", 2, "Primary issues are floated through public offers with a prospectus, offers for sale, private placements, or rights issues.", "Capital Market"),
        ("One of the advantages of commercialization is that it _____.", "increases the salaries of workers", "encourages entrepreneurship", "gives workers on-the-job training", "motivates government to establish more business", 1, "Commercialization makes state enterprises operate on private commercial principles, stimulating efficiency and enterprise.", "Public Policy"),
        ("Given: Sales ₦15,000, Opening stock ₦5,600, Purchases ₦9,700, Closing stock ₦4,400, Gross profit ₦4,500, Net profit ₦2,000. Calculate the rate of turnover.", "2.18 times", "3.50 times", "3.00 times", "2.00 times", 0, "Cost of Goods Sold = 5,600 + 9,700 - 4,400 = ₦10,900. Average Stock = (5,600 + 4,400) / 2 = ₦5,000. Rate of turnover = 10,900 / 5,000 = 2.18 times.", "Accounting Calculations"),
        ("Which of the following confirms the accuracy of the duty charged on imported goods?", "Consular invoice", "An indent", "Shipping note", "Bill of lading", 0, "A consular invoice is certified by consular officials to prevent under-invoicing and ensure accurate customs duty calculation.", "Customs Documents"),
        ("The type of communication from a superior to a subordinate in an organization is referred to as _____.", "downward communication", "horizontal communication", "lateral communication", "upward communication", 0, "Downward communication flows down the chain of command from management to operational staff.", "Organizational Communication"),
        ("The safety and quality of products are the social responsibility of _____.", "the Manufacturer's Association of Nigeria", "the Corporate Affairs Commission", "business organization", "the Standard Organization of Nigeria", 2, "Ensuring safe, defect-free goods that do not harm consumers is an essential social duty of the business enterprise.", "Corporate Social Responsibility"),
        ("The members of ECOWAS include _____.", "Togo, Nigeria and Ghana", "Burkina Faso, Nigeria, Niger and Mauritania", "Guinea, Mali, Cameroon and Nigeria", "Nigeria, Chad, Gabon and Cape Verde", 0, "Togo, Nigeria, and Ghana are all active founding member states of ECOWAS in West Africa.", "International Organizations"),
        ("One of the functions of Nigeria Ports Authority is the _____.", "provision of facilities to ensure that goods get to their destinations", "courier services to ensure specific delivery", "shelter for operators of cargoes", "facilities to enhance the speedy loading and offloading of cargoes", 3, "The NPA manages port berths, quays, and container cranes to expedite vessel loading and cargo discharge.", "Port Administration"),
        ("A document which advertises the shares of a company is known as _____.", "deed", "prospectus", "dividend warrant", "memorandum of satisfaction", 1, "A prospectus provides statutory financial disclosures inviting the public to subscribe for newly issued securities.", "Capital Market"),
        ("An association to which all Chambers of Commerce in Nigeria are affiliated is the _____.", "National Association of Chambers of Commerce", "Nigeria Labour Congress", "Nigeria Stock Exchange", "Nigeria Association of Chambers of Commerce, Industry, Mines and Agriculture", 3, "NACCIMA is the umbrella national federation coordinating state and city chambers of commerce across Nigeria.", "Commercial Associations"),
        ("An aspect of commerce that facilitates the distribution of product is _____.", "advertising", "branding", "transportation", "trading", 2, "Transportation bridges physical spatial distances, delivering commodities to consumption points.", "Aids to Trade"),
        ("Unresolved disputes between the employer and employees are usually referred to the _____.", "industrial arbitration tribunal", "disciplinary committee", "code of conduct bureau", "personal unit", 0, "Industrial disputes not settled by conciliation are referred to the Industrial Arbitration Panel (IAP).", "Industrial Relations"),
        ("A chain store usually combines the features of _____.", "hyper markets and stalls", "multiple shops and hyper markets", "multiple shops and departmental shops", "mail order business and multiple shop", 2, "Chain stores utilize multiple retail branches while offering diverse departmental lines under central control.", "Retail Trade"),
        ("Which of the following is a matter of personal preference on the part of a superior officer?", "Delegation of authority", "Unity of direction", "Span of control", "Unity of command", 0, "Delegation of authority is discretionary, determined by the managerial style and confidence of the executive.", "Principles of Management"),
        ("Manufacturing and constructive activities are classified under _____.", "direct-service", "primary production", "tertiary production", "secondary production", 3, "Secondary production encompasses all industrial manufacturing, fabrication, and structural construction.", "Production"),
        ("From the organizational tree of Commerce (Commerce -> Trade & Aids to Trade), what does I stand for?", "Publicity", "Home trade", "Aids to trade", "Advertising.", 2, "Commerce consists of Trade and Aids to Trade (transport, banking, insurance, warehousing, advertising).", "Branches of Commerce"),
        ("The three main classification of occupation are _____.", "industry, commerce and services", "manufacturing, industry and trading", "farming, banking and trading", "construction, trade and services", 0, "The canonical division of economic occupations is Industry, Commerce, and Direct/Indirect Services.", "Occupations"),
        ("The person who undertakes life assurance is said to be an _____.", "assurer", "insurer", "insured", "assured", 3, "The policyholder whose life is covered in life assurance contracts is designated the assured.", "Life Assurance"),
        ("A business organization must always consider the overall effect of its actions on the _____.", "profit", "society", "product", "competitor", 1, "Sustainable commercial enterprise requires harmonizing corporate profit with positive societal welfare.", "Business & Society"),
        ("An undertaking given by a person to another assuring his integrity is _____.", "subrogation", "insurable interest", "proximate clause", "fidelity guarantee", 3, "Fidelity guarantee contracts protect against financial losses arising from employee fraud or dishonesty.", "Insurance"),
        ("Which of the following is a quality of money?", "scarcity", "availability", "convertibility", "indivisibility", 0, "Relative scarcity maintains the purchasing power and stability of monetary currency.", "Money"),
        ("The distribution of petroleum products in Nigeria is predominantly through _____.", "the bank", "air", "sea", "road", 3, "Heavy articulated road tankers distribute petroleum products across the federation.", "Transportation"),
        ("The business that focuses attention on the quality of the goods produced by precisely knowing what the consumers desire is said to be operating the _____.", "marketing concept", "promotion mix", "product orientation", "product mix", 0, "The marketing concept focuses on producing what consumers desire based on verified market demand.", "Marketing"),
        ("A floating policy is an example of _____.", "marine insurance", "motor insurance", "fire insurance", "actuaries insurance", 0, "A floating policy in marine insurance covers fluctuating cargo values across multiple voyages up to an aggregate insured limit.", "Marine Insurance"),
        ("The art of soap making is an example of a _____.", "construction occupation", "tertiary occupation", "primary occupation", "secondary occupation", 3, "Soap making transforms chemical raw materials into consumer commodities, representing secondary manufacturing.", "Occupations")
    ]
    for idx, item in enumerate(pt5_data, 1):
        q, a, b, c, d, ans, exp, topic = item
        questions.append({
            "id": f"jamb_com_pt5_{idx:02d}", "subject": "Commerce", "topic": topic, "year": "PT. 5",
            "text": q, "a": a, "b": b, "c": c, "d": d, "ans": ans, "exp": exp,
            "label": f"JAMB Commerce PT.5 • Q{idx}"
        })

    return questions
