import sys, os
sys.path.append(os.path.dirname(__file__))
from bank_writer import write_kotlin_bank
from generate_lit_2013 import lit_all

# --- 2014 LITERATURE (50 Qs) ---
l2014 = [
    ("jamb_lit_2014_01", "Literature in English", "Exam Administration", "2014", "Which Question Paper Type of Literature-in-English is given to you?", "Type F", "Type S", "Type L", "Type S", 3, "Paper Type S assigned."),
    ("jamb_lit_2014_02", "Literature in English", "Women of Owu - Femi Osofisan", "2014", "In the play, the gods (Anlugbua and Lawumi) are portrayed as", "helpless", "capricious architects of human destiny and vengeance", "amorous", "saviours of mankind", 1, "The gods orchestrate the doom and sack of Owu in retribution for hubris."),
    ("jamb_lit_2014_03", "Literature in English", "Women of Owu - Femi Osofisan", "2014", "Orisaye describes the allied general Balogun Kusa as", "a great warrior", "an enemy, butcher and ruthless conqueror", "a friend in need", "a good leader", 1, "Denounces Kusa's brutal massacres and merciless treatment of captives."),
    ("jamb_lit_2014_04", "Literature in English", "Women of Owu - Femi Osofisan", "2014", "Erelu Afin is", "the oldest and chief wife of the deceased Oba Akinjobi", "a courtier to the Alaafin of Oyo", "the most brilliant woman in Owu", "the first wife of the Oba", 0, "Erelu Afin is the royal matriarch who leads the mourning women of Owu."),
    ("jamb_lit_2014_05", "Literature in English", "Women of Owu - Femi Osofisan", "2014", "Balogun Kusa is killed by", "a god", "an herbalist", "a lunatic / demented girl (Orisaye)", "a soldier", 2, "Orisaye stabs Balogun Kusa to death during her prophetic frenzy."),
    ("jamb_lit_2014_06", "Literature in English", "The Tempest - William Shakespeare", "2014", "In the play, Ariel is identified as", "leader of the spirits and servant to Prospero", "Prospero's daughter", "Alonso's wife", "assistant to Sycorax", 0, "The delicate, airy spirit who performs magical tasks to regain his freedom."),
    ("jamb_lit_2014_07", "Literature in English", "The Tempest - William Shakespeare", "2014", "Before the shipwreck, Prospero and Miranda had lived on the enchanted island for", "two decades", "twelve years", "forty days", "eighteen months", 1, "'Twelve year since, Miranda, twelve year since, Thy father was the Duke of Milan.'"),
    ("jamb_lit_2014_08", "Literature in English", "The Tempest - William Shakespeare", "2014", "Caliban's intention to assault Miranda was born out of the desire to", "destroy the island", "compete with Ferdinand", "populate the island with Calibans", "marry her", 2, "'Thou didst prevent me; I had peopled else / This isle with Calibans.'"),
    ("jamb_lit_2014_09", "Literature in English", "The Tempest - William Shakespeare", "2014", "The character associated with uncivilized, earthly savagery in the play is", "Ariel", "Stephano", "Caliban", "Ferdinand", 2, "Caliban embodies primal nature, base appetite, and native resistance."),
    ("jamb_lit_2014_10", "Literature in English", "The Tempest - William Shakespeare", "2014", "Prospero is initially portrayed as a ruler who was", "full of mistrust", "more devoted to secret book studies than state governance", "dependent on spirits", "eager to conquer", 1, "Neglected his political duties in Milan to pursue the liberal arts and magic."),
    ("jamb_lit_2014_11", "Literature in English", "A Woman in Her Prime - Asare Konadu", "2014", "The novel explores the traditional Ghanaian theme of", "exploitation", "sex discrimination", "women liberation", "the desperate quest for a child (maternal yearning)", 3, "Pokuwaa's emotional, physical, and spiritual struggle to overcome childlessness."),
    ("jamb_lit_2014_12", "Literature in English", "A Woman in Her Prime - Asare Konadu", "2014", "According to village tradition in Brenhoma, the worst calamity for a woman is", "inability to bear children (barrenness)", "poverty", "divorce", "widowhood", 0, "Barrenness is viewed as the ultimate social stigma and personal failure."),
    ("jamb_lit_2014_13", "Literature in English", "A Woman in Her Prime - Asare Konadu", "2014", "In the novel, Asogo is a traditional moonlight game in which", "fathers tell stories", "youths engage in musical teasing and songs of social admonition", "girls sing praise songs", "mothers lull babies", 1, "Village youth playfully tease and critique social behaviors through song."),
    ("jamb_lit_2014_14", "Literature in English", "Purple Hibiscus - Chimamanda Ngozi Adichie", "2014", "In the novel, one of the rigid religious changes introduced by Father Benedict at St. Agnes is that", "there must be monthly fasting", "the Credo must be in Igbo", "the Credo and liturgical responses must be rendered only in Latin/English", "everyone must take communion", 2, "Father Benedict strictly enforces European liturgy, banning indigenous Igbo praise."),
    ("jamb_lit_2014_15", "Literature in English", "Purple Hibiscus - Chimamanda Ngozi Adichie", "2014", "Eugene Achike (Papa) is portrayed as", "a gentle husband", "an uncompromising traditionalist", "a fanatical, abusive Catholic fundamentalist", "a retired soldier", 2, "A wealthy philanthropist whose tyrannical religious fanaticism terrorizes his family."),
    ("jamb_lit_2014_16", "Literature in English", "Purple Hibiscus - Chimamanda Ngozi Adichie", "2014", "In the Achike family, the narrator and central character experiencing growth is", "Kambili", "Mama (Beatrice)", "Sisi", "Jaja", 0, "The novel is narrated from Kambili's perspective as she finds her voice at Nsukka."),
    ("jamb_lit_2014_17", "Literature in English", "The Old Man and the Sea - Ernest Hemingway", "2014", "In the novel, the magnificent giant fish hooked by Santiago is a", "shark", "mako", "giant marlin", "geisha", 2, "Santiago battles an 18-foot marlin in the Gulf Stream for three days."),
    ("jamb_lit_2014_18", "Literature in English", "The Old Man and the Sea - Ernest Hemingway", "2014", "The novel demonstrates the central Hemingway code of", "attempting to catch fish", "understanding life", "influence of sea", "the unconquerable dignity of man against defeat", 3, "'Man is not made for defeat. A man can be destroyed but not defeated.'"),
    ("jamb_lit_2014_19", "Literature in English", "The Old Man and the Sea - Ernest Hemingway", "2014", "In the novel, Santiago's philosophical attitude toward the sea (la mar) is", "cautious and skeptical", "hostile", "careless", "deeply respectful, affectionate and reverent", 3, "He regards the sea as a woman ('la mar') who gives or withholds great favors."),
    ("jamb_lit_2014_20", "Literature in English", "The Old Man and the Sea - Ernest Hemingway", "2014", "Santiago repeatedly dreams of", "sharks attacking", "his late wife", "the great Joe DiMaggio", "lions playing on the African beaches of his youth", 3, "The recurring vision of playful lions on golden African beaches symbolizes youthful vitality and peace."),
    ("jamb_lit_2014_21", "Literature in English", "Poetry - Hard Lines", "2014", "The dominant sensory imagery in Gbemisola Adeoti's Hard Lines is", "auditory", "gustatory", "visual and tactile", "olfactory", 2, "Sharp visual and physical descriptions of metallic wires, hard surfaces, and socio-economic tension."),
    ("jamb_lit_2014_22", "Literature in English", "Poetry - Ambassadors of Poverty", "2014", "The tone of P.O.C. Umeh's Ambassadors of Poverty can be described as", "metaphorical", "caustically satirical and indignant", "admonitory", "panegyrical", 1, "Biting satire condemning African corrupt politicians who parade poverty for personal enrichment."),
    ("jamb_lit_2014_23", "Literature in English", "Poetry - Homeless, Not Hopeless", "2014", "In Owonibi's Homeless, Not Hopeless, the persona explains that street beggars", "worry about heaven", "rarely sleep", "attend conferences", "are focused on basic daily survival and resilient dignity", 3, "Highlights their resilience and persistent optimism despite destitution."),
    ("jamb_lit_2014_24", "Literature in English", "Poetry - Myopia", "2014", "Syl Cheney-Coker's Myopia is structurally a", "dirge and political lament", "ballad", "sonnet", "pastoral lyric", 0, "An agonizing poetic lament over Sierra Leone's political and moral decay."),
    ("jamb_lit_2014_25", "Literature in English", "Poetry - Expelled", "2014", "Jared Angira is a celebrated African poet from", "Sierra Leone", "Kenya", "South Africa", "Ghana", 1, "Angira is a prominent Kenyan social and political poet."),
    ("jamb_lit_2014_26", "Literature in English", "Poetry - Serenade", "2014", "The dominant literary technique used in Serenade is", "metaphor and lyrical romantic imagery", "simile", "oxymoron", "apostrophe", 0, "Rich lyrical metaphors expressing devotion to the beloved."),
    ("jamb_lit_2014_27", "Literature in English", "Poetry - The Sun Rising", "2014", "The sun in Donne's The Sun Rising is dramatized through the use of", "invocation", "ellipsis", "enjambment", "direct apostrophe and personification", 3, "Direct address to the sun ('Busy old fool, unruly sun')."),
    ("jamb_lit_2014_28", "Literature in English", "Poetry - The Soul's Errand", "2014", "In Sir Walter Raleigh's The Soul's Errand, the soul is portrayed as a", "friend of masses", "fearless truth-teller and messenger of moral defiance", "restorer of lost glory", "messenger of peace", 1, "Dispatched to 'give the world the lie' without fear of earthly tyrants."),
    ("jamb_lit_2014_29", "Literature in English", "Poetry - The Negro Speaks of Rivers", "2014", "The allusion in Langston Hughes's The Negro Speaks of Rivers is mainly", "biblical", "deeply historical, civilizational and ancestral", "classical", "literary", 1, "Traces Black ancestral history from the Euphrates, Congo, and Nile to the Mississippi."),
    ("jamb_lit_2014_30", "Literature in English", "Poetry - Upon An Honest Man's Fortune", "2014", "John Fletcher's Upon An Honest Man's Fortune encourages people to", "condemn soothsaying", "trust in fortune", "accept self-reliance and cultivate inner virtue against fate", "accept life as it is", 2, "Stoic celebration of inner fortitude and personal integrity over fickle fortune."),
    ("jamb_lit_2014_31", "Literature in English", "Literary Principles", "2014", "A quality in drama that evokes pity, tenderness, or sorrow from the audience is", "pathos", "parody", "pyrrhic", "props", 0, "Pathos appeals directly to the audience's deep emotions of sympathy and sorrow."),
    ("jamb_lit_2014_32", "Literature in English", "Literary Principles", "2014", "The psychological purgation and cleansing of pity and fear in tragedy is termed", "epilogue", "exposition", "catharsis", "catastrophe", 2, "Aristotle defined catharsis as the emotional release experienced at the climax of tragedy."),
    ("jamb_lit_2014_33", "Literature in English", "Literary Principles", "2014", "A dramatic convention where a character speaks their innermost thoughts alone on stage is a", "apostrophe", "dialogue", "soliloquy", "aside", 2, "Soliloquy provides direct insight into a solitary character's psyche."),
    ("jamb_lit_2014_34", "Literature in English", "Literary Principles", "2014", "The plot in a literary work is fundamentally about the", "resolution", "poetic justice", "character list", "causal organization and arrangement of narrative events", 3, "Plot structures the cause-and-effect relationship between story occurrences."),
    ("jamb_lit_2014_35", "Literature in English", "Literary Principles", "2014", "Tone and mood of a poem jointly contribute to its overall emotional", "setting", "space", "locale", "atmosphere", 3, "The emotional feeling or mood established throughout a literary text."),
    ("jamb_lit_2014_36", "Literature in English", "Literary Principles", "2014", "A humorous or lighthearted scene introduced into a serious tragedy to ease emotional tension is", "tragicomedy", "tragic hero", "comedy", "comic relief", 3, "Comic relief (e.g. the Porter in Macbeth, the Gravediggers in Hamlet) relieves dramatic tension."),
    ("jamb_lit_2014_37", "Literature in English", "Literary Principles", "2014", "In literature, a flat character is one who", "dies abruptly", "achieves greatness", "is one-dimensional, uncomplicated, and undergoes little change", "develops dynamically", 2, "E.M. Forster defined flat characters as built around a single idea or trait."),
    ("jamb_lit_2014_38", "Literature in English", "Literary Principles", "2014", "The Latin term 'dramatis personae' in a play script refers to the", "cast list / characters of the drama", "protagonist and antagonist", "stage directions", "order of entrance", 0, "The complete list of dramatic characters in a play."),
    ("jamb_lit_2014_39", "Literature in English", "Literary Principles", "2014", "A concluding speech or poem addressed directly to the audience at the end of a play is an", "a dirge", "a monologue", "a prologue", "an epilogue", 3, "An epilogue rounds off a drama and offers final reflections to the audience."),
    ("jamb_lit_2014_40", "Literature in English", "Literary Principles", "2014", "The quality of realism and appearance of truth in narrative fiction is known as", "Objectivity", "Subjectivity", "Verisimilitude", "Dialogue", 2, "Verisimilitude gives fictional narratives the semblance of genuine real-life plausibility."),
    ("jamb_lit_2014_41", "Literature in English", "Literary Appreciation", "2014", "'He put himself in uniform, made one for his five-year-old son, and marched... singing Kayiwawa beturi' portrays the persona as", "energetic", "a policeman", "a soldier", "mentally unhinged / abnormal", 3, "Delusional military drill behavior indicating psychiatric illness."),
    ("jamb_lit_2014_42", "Literature in English", "Literary Appreciation", "2014", "'He is a faithful liar' is an example of", "epigram", "oxymoron", "euphemism", "antithesis", 1, "Oxymoron pairs two contradictory words ('faithful' and 'liar') together."),
    ("jamb_lit_2014_43", "Literature in English", "Literary Appreciation", "2014", "'Fights by the book of arithmetic' is an example of", "hyperbole", "euphemism", "litotes", "innuendo / metaphor", 3, "Tybalt in Romeo and Juliet is mocked for fencing mechanically by strict mathematical rules."),
    ("jamb_lit_2014_44", "Literature in English", "Literary Appreciation", "2014", "'And when you trudge on your horny pads Gullied like the soles of modern shoes...' Horny pads refers to", "a policeman", "a madman", "the hardened calloused bare soles of a pauper", "a soldier", 2, "Vivid sensory imagery describing the scarred, calloused bare feet of impoverished laborers."),
    ("jamb_lit_2014_45", "Literature in English", "Literary Appreciation", "2014", "'Lift not the painted veil which those who live call life...' by P.B. Shelley is a 14-line", "quatrain", "sonnet", "couplet", "sestet", 1, "Shelley's famous 14-line metaphysical sonnet on life and illusion."),
    ("jamb_lit_2014_46", "Literature in English", "To a Bed-Bug - Mbure", "2014", "'I wonder how long, you awful parasites, shall share with me this little bed...' is a poem of", "mock-heroic light verse / satire", "lampoon", "ode", "epic", 0, "Humorous mock-serious address to household pests."),
    ("jamb_lit_2014_47", "Literature in English", "To a Bed-Bug - Mbure", "2014", "The poet persona expresses comical dismay about", "bats", "bed-bugs and nocturnal parasites", "grasshoppers", "mosquitoes", 1, "Vexed by persistent bloodsucking bedbugs disrupting sweet sleep."),
    ("jamb_lit_2014_48", "Literature in English", "To a Bed-Bug - Mbure", "2014", "The most dominant figure of speech in the excerpt addressing bed-bugs directly is", "metaphor", "apostrophe and personification", "hyperbole", "simile", 1, "Direct apostrophe addressing bed-bugs as bed-mates."),
    ("jamb_lit_2014_49", "Literature in English", "Literary Appreciation", "2014", "'You Your head is like a drum that is beaten for spirits. Your ears are like fans used for blowing fire.' is", "caricature and lampoon", "ridicule only", "subtle satire", "praise poetry", 0, "Aggressive, humorous invective utilizing exaggerated derogatory similes (lampoon/caricature)."),
    ("jamb_lit_2014_50", "Literature in English", "The Voice - Gabriel Okara", "2014", "'This thing you are doing is too heavy for you... I have killed many more years in this world than you' shows speaker is", "wise", "a porter", "more experienced through age", "foolish", 2, "The elder relies on senior age and societal experience to caution Okolo.")
]
lit_all.extend(l2014)

print(f"Total Literature questions through 2014: {len(lit_all)}")
