import sys, os
sys.path.append(os.path.dirname(__file__))
from bank_writer import write_kotlin_bank

lit_all = []

# --- 2010 LITERATURE (50 Qs) ---
l2010 = [
    ("jamb_lit_2010_01", "Literature in English", "Exam Administration", "2010", "Which literature in English Question Paper Type is given to you?", "Type A", "Type B", "Type C", "Type D", 0, "Paper Type A assigned."),
    ("jamb_lit_2010_02", "Literature in English", "Sons and Daughters - J.C. De Graft", "2010", "'I simply don't understand what's the matter with everybody today. Everybody let me down', the speaker refers to", "Fosuwa and Maidservant", "Hannah and George", "Aaron and Maanan", "Lawyer B and Mrs. B", 0, "James Ofosu expresses frustration over lack of obedience from household members."),
    ("jamb_lit_2010_03", "Literature in English", "Sons and Daughters - J.C. De Graft", "2010", "Maanan expresses dislike for Lawyer B because of", "his condemnation of her choice of career", "his recent advances towards her", "the betrayal of her father's trust", "the betrayal of his wife's trust", 1, "Lawyer B made improper sexual advances toward Maanan while pretending to advise her father."),
    ("jamb_lit_2010_04", "Literature in English", "Sons and Daughters - J.C. De Graft", "2010", "The traditional order in the play is represented by", "Mrs. B", "Hannah", "Maanan", "Aunt Fosuwa", 3, "Aunt Fosuwa represents unyielding traditional customs and societal expectations."),
    ("jamb_lit_2010_05", "Literature in English", "Sons and Daughters - J.C. De Graft", "2010", "Where does the play take place?", "On the street", "In George's place", "In Aunt's house", "In Ofosu's place", 3, "The entire dramatic action is set in James Ofosu's sitting room."),
    ("jamb_lit_2010_06", "Literature in English", "Romeo and Juliet - William Shakespeare", "2010", "'O deadly sin! O rude unthankfulness! Thy fault our law calls death, but the kind Prince... turned that black word...' Deadly sin refers to", "suicide of Juliet", "suicide of Romeo", "murder of Paris", "murder of Tybalt", 3, "Friar Lawrence rebukes Romeo after he slays Tybalt and is granted exile instead of execution."),
    ("jamb_lit_2010_07", "Literature in English", "Romeo and Juliet - William Shakespeare", "2010", "The play is mostly written in", "blank verse", "free verse", "metres", "foot", 0, "Shakespeare primarily utilizes unrhymed iambic pentameter (blank verse)."),
    ("jamb_lit_2010_08", "Literature in English", "Romeo and Juliet - William Shakespeare", "2010", "'O serpent heart, hid with a flowering face!' The statement refers to", "Juliet", "Romeo", "Tybalt", "Benvolio", 1, "Juliet laments in oxymorons upon hearing that her beloved Romeo killed her cousin Tybalt."),
    ("jamb_lit_2010_09", "Literature in English", "Romeo and Juliet - William Shakespeare", "2010", "The spatial setting of the play is", "Athens", "Verona", "Padua", "Venice", 1, "The central setting is fair Verona, Northern Italy."),
    ("jamb_lit_2010_10", "Literature in English", "Romeo and Juliet - William Shakespeare", "2010", "Romeo is banished to Mantua because he", "kills Tybalt in a street duel", "marries Juliet without parental consent", "attends Capulet's party uninvited", "attempts to kill Paris his rival", 0, "Prince Escalus banishes Romeo for killing Tybalt in revenge for Mercutio's death."),
    ("jamb_lit_2010_11", "Literature in English", "The Joys of Motherhood - Buchi Emecheta", "2010", "In the novel, the society puts high value on", "egalitarianism", "male ascendancy", "procreation", "gender equity", 2, "Traditional Ibuza and colonial Lagos society place supreme importance on bearing children, especially sons."),
    ("jamb_lit_2010_12", "Literature in English", "The Joys of Motherhood - Buchi Emecheta", "2010", "The medicine man links the lump discovered on the head of Nnu Ego at birth to the", "possession of physical admirable qualities", "wound inflicted on the slave woman buried with Agbadi's wife", "ancestral beauty mark", "divine omen", 1, "The slave woman vowed to return as Agbadi's daughter after being brutally struck on the head during burial."),
    ("jamb_lit_2010_13", "Literature in English", "The Joys of Motherhood - Buchi Emecheta", "2010", "The constant companions of Nnaife's family are", "togetherness and happiness", "poverty and hunger", "sickness and joblessness", "disagreement and humiliation", 1, "Nnu Ego continually battles grinding poverty and starvation to feed her growing household."),
    ("jamb_lit_2010_14", "Literature in English", "The Old Man and the Medal - Ferdinand Oyono", "2010", "The disagreement between Mvondo and Nti centres on the latter's claim to have", "assisted Meka in getting the medal", "eaten the entire entrails of a sheep", "eaten more than his share of the food", "been in a white man's office", 2, "The villagers quarrel over food distribution during the celebratory feast."),
    ("jamb_lit_2010_15", "Literature in English", "The Old Man and the Medal - Ferdinand Oyono", "2010", "Meka can best be described as", "an egocentric old man", "a simple-hearted old man", "an impulsive old man", "an old religious bigot", 1, "Meka is naive and trusting, genuinely believing in the benevolence of the French colonial authorities."),
    ("jamb_lit_2010_16", "Literature in English", "The Old Man and the Medal - Ferdinand Oyono", "2010", "In the novel, the colonialists treat the Africans with", "kid gloves", "disdain", "indifference", "honour", 1, "The colonial administrators view and treat the indigenous population with contempt and condescension."),
    ("jamb_lit_2010_17", "Literature in English", "Nineteen Eighty-Four - George Orwell", "2010", "The Ministry of Peace is concerned with making", "instruments", "weapons", "wars", "reconciliation", 2, "In Newspeak doublethink, the Ministry of Peace (Minipax) conducts perpetual warfare."),
    ("jamb_lit_2010_18", "Literature in English", "Nineteen Eighty-Four - George Orwell", "2010", "The subject matter of the novel is", "totalitarian dictatorship", "exploitation and cruelty", "retributive justice", "class segregation", 0, "Orwell warns against omnipotent totalitarian control and psychological manipulation."),
    ("jamb_lit_2010_19", "Literature in English", "Nineteen Eighty-Four - George Orwell", "2010", "How did Winston start his rebellion against the state?", "By engaging in anti-party activities", "By keeping a private diary", "When he started a secret affair", "When he spied on the party", 1, "Winston commits thoughtcrime by purchasing a blank book and writing 'DOWN WITH BIG BROTHER'."),
    ("jamb_lit_2010_20", "Literature in English", "Nineteen Eighty-Four - George Orwell", "2010", "The Party seeks power for", "the nation", "its own sake", "its members", "peoples' sake", 1, "O'Brien declares that the Party seeks power entirely for its own sake, not as a means to an end."),
    ("jamb_lit_2010_21", "Literature in English", "Poetry - Naked Soles", "2010", "As the dancers move through paths strewn with glass chips, images in Adeoti's Naked Soles change from", "joy to excitement", "inaction to action", "pain to grief", "sorrow to joy", 3, "The poetry reflects resilience and transformative optimism amidst hardship."),
    ("jamb_lit_2010_22", "Literature in English", "Poetry - An African Thunderstorm", "2010", "Rubadiri's An African Thunderstorm says that during thunderstorm in the village", "women cook their food", "children play in the rain", "children are delighted while women move in and out", "both women and children are delighted", 2, "Children scream in delight while hurried mothers dart about frantically to secure belongings."),
    ("jamb_lit_2010_23", "Literature in English", "Poetry - In the Navel of the Soul", "2010", "'Yet in their finger upon Our navel The midwives of the spirit say They feel a foetal throb.' The dominant literary device is", "epigram", "allegory", "enjambment", "rhythm", 2, "Lines run onto succeeding lines without terminal punctuation (enjambment)."),
    ("jamb_lit_2010_24", "Literature in English", "Poetry - A Heritage of Liberation", "2010", "In Kunene's A Heritage of Liberation, the poet persona requests that weapons of warfare be handed to their", "friends", "relations", "grandchildren", "families", 2, "The generational legacy of struggle is entrusted to the grandchildren."),
    ("jamb_lit_2010_25", "Literature in English", "Poetry - End of the War", "2010", "The predominant device in Launko's End of the War is", "onomatopoeia", "antithesis", "oxymoron", "paradox", 3, "The complex ironies and contradictions of post-war reality are framed through paradox."),
    ("jamb_lit_2010_26", "Literature in English", "Poetry - Give Me The Minstrel's Seat", "2010", "The theme of Give Me The Minstrel's Seat centres on", "divorce", "fortune", "marriage", "companionship", 3, "Focuses on human unity, domestic harmony, and enduring companionship."),
    ("jamb_lit_2010_27", "Literature in English", "Poetry - To His Coy Mistress", "2010", "In Marvell's To His Coy Mistress, the persona is willing to praise the lady's eyes for", "thirty thousand years", "six decades", "two centuries", "a century", 3, "'An hundred years should go to praise / Thine eyes, and on thy forehead gaze'."),
    ("jamb_lit_2010_28", "Literature in English", "Poetry - Bat", "2010", "In Lawrence's Bat, the poet persona mistakes the bats for", "owls", "swallows", "pipistrello", "sparrows", 1, "At dusk over Florence, the speaker initially assumes the darting silhouettes are swallows."),
    ("jamb_lit_2010_29", "Literature in English", "Poetry - Journey of the Magi", "2010", "In Eliot's Journey of the Magi, the magi are aided on their journey by", "donkeys", "horses", "camels", "chariots", 2, "'And the camels galled, sore-footed, refractory / Lying down in the melting snow.'"),
    ("jamb_lit_2010_30", "Literature in English", "Poetry - Sonnet VII", "2010", "According to Wendy Cope's Sonnet VII, poetry is basically", "boring", "therapeutic", "philosophical", "inspiring", 1, "Cope highlights the expressive and emotional healing function of writing verse."),
    ("jamb_lit_2010_31", "Literature in English", "Literary Principles", "2010", "A play which mainly aims at provoking excessive laughter is called", "tragi-comedy", "comedy", "a farce", "satire", 2, "A farce relies on exaggerated physical comedy, absurdity, and improbable situations to incite laughter."),
    ("jamb_lit_2010_32", "Literature in English", "Literary Principles", "2010", "Both comedy and tragedy have", "happy ending", "climax", "tragic hero", "stanza", 1, "All standard dramatic plot arcs incorporate an inciting moment, rising action, and a climax."),
    ("jamb_lit_2010_33", "Literature in English", "Literary Principles", "2010", "A formal dignified speech or writing praising a person or thing for past or present deeds is", "premiere", "eulogy", "anthology", "lampoon", 1, "A eulogy (or panegyric) formally extols someone's virtues and accomplishments."),
    ("jamb_lit_2010_34", "Literature in English", "Literary Principles", "2010", "The narrative style in which the hero tells his own story directly is the", "objective", "subjective", "first-person", "third-person", 2, "First-person point of view uses 'I' / 'we' to narrate personal experiences directly."),
    ("jamb_lit_2010_35", "Literature in English", "Literary Principles", "2010", "The physical, historical or cultural background of a literary work is referred to as", "episode", "plot", "time", "setting", 3, "Setting encompasses time, location, social milieu, and historical era."),
    ("jamb_lit_2010_36", "Literature in English", "Literary Principles", "2010", "A plot structure that defies chronology can be described as", "open-ended", "circular", "episodic", "non-linear", 2, "An episodic or non-linear plot departs from chronological sequence using flashbacks and vignettes."),
    ("jamb_lit_2010_37", "Literature in English", "Literary Principles", "2010", "Pun as a literary device deals with", "placing two opposite phrases", "placing words side by side", "playing on words", "arrangement of words", 2, "A pun is a humorous play on words with multiple meanings or similar sounds."),
    ("jamb_lit_2010_38", "Literature in English", "Literary Principles", "2010", "In a narrative poem, the poet attempts to", "summarize a story", "describe a place", "preach a sermon", "tell a story", 3, "A narrative poem's primary function is storytelling through verse."),
    ("jamb_lit_2010_39", "Literature in English", "Literary Principles", "2010", "The account of experiences of an individual during the course of a journey is known as", "a travelogue", "an autobiography", "a catalogue", "a memoir", 0, "A travelogue chronicles travels, observations, and journey encounters."),
    ("jamb_lit_2010_40", "Literature in English", "Literary Principles", "2010", "Satirical writing employs", "epigram", "synecdoche", "irony", "onomatopoeia", 2, "Irony, sarcasm, and ridicule are the foundational tools of satire."),
    ("jamb_lit_2010_41", "Literature in English", "Literary Appreciation", "2010", "'Basha: You dumb skull of a bone head... you will face court martial for this.' The person being addressed is a", "soldier", "student", "domestic servant", "lawyer", 0, "Facing a court martial confirms the subordinate is a soldier under military discipline."),
    ("jamb_lit_2010_42", "Literature in English", "Literary Appreciation", "2010", "From the tone of Basha's speech in King Baabu, the speaker is obviously", "enraged", "lackadaisical", "elated", "happy", 0, "The insulting language and threats demonstrate severe rage."),
    ("jamb_lit_2010_43", "Literature in English", "Things Fall Apart - Chinua Achebe", "2010", "'That year the harvest was sad, like a funeral, and many farmers wept as they dug up the miserable yams...' The mood conveyed is", "sadness", "frustration", "sympathy", "dilemma", 0, "The somber simile 'like a funeral' and weeping farmers evoke deep sadness."),
    ("jamb_lit_2010_44", "Literature in English", "Literary Appreciation", "2010", "'That age is best which is the first, when youth and blood are warmer, But being spent, the worse, and worst Time still succeed the former.' Rhyme scheme is", "bbaa", "aabb", "abab", "abba", 2, "first/worst (a), warmer/former (b) => alternate rhyme scheme abab."),
    ("jamb_lit_2010_45", "Literature in English", "Literary Appreciation", "2010", "'She moved, suddenly, and the houses crumbled, the mountains heaved horribly, and the work of a million years was lost.' Subject matter is", "storm", "sea waves", "house movement", "earthquake", 3, "Heaving mountains and crumbled structures describe a seismic earthquake."),
    ("jamb_lit_2010_46", "Literature in English", "Literary Appreciation", "2010", "'And your laughter like a flame piercing the shadows Has revealed Africa to me beyond the snow of yesterday.' Shadow means", "famine", "bleak future", "period of sufferings", "abstract ideas", 2, "Shadows symbolize colonial gloom, alienation, and prolonged suffering."),
    ("jamb_lit_2010_47", "Literature in English", "Literary Appreciation", "2010", "'Don't panic. Be calm, If you are somehow upset... try to regain your exposure.' The speaker is", "hopeless", "uncertain", "afraid", "confident", 3, "Advising others to remain calm displays composure and self-confidence."),
    ("jamb_lit_2010_48", "Literature in English", "Poetry - Futility", "2010", "Wilfred Owen's 'Move him into the sun... Was it for this the clay grew tall?' can be described as", "a lyric", "an epic", "a sonnet", "an elegy", 3, "An elegy mourning a fallen soldier and lamenting the futility of war."),
    ("jamb_lit_2010_49", "Literature in English", "Poetry - Futility", "2010", "The theme of Owen's poem 'Futility' is", "futility of life", "distortion of life", "creation of life", "vanity of life", 0, "Highlights the tragic meaninglessness of death on the battlefield."),
    ("jamb_lit_2010_50", "Literature in English", "Literary Appreciation", "2010", "'A cursing rogue with a merry farce, A bundle of rags upon a crutch, Stumbled upon that windy place Called Cruachan...' Rhyme scheme is", "aabb", "abab", "bbaa", "abba", 1, "farce/place (a), crutch/much (b) => abab.")
]
lit_all.extend(l2010)

print(f"Literature questions through 2010: {len(lit_all)}")
