import sys, os
sys.path.append(os.path.dirname(__file__))
from bank_writer import write_kotlin_bank
from generate_lit_2012 import lit_all

# --- 2013 LITERATURE (50 Qs) ---
l2013 = [
    ("jamb_lit_2013_01", "Literature in English", "Exam Administration", "2013", "Which Question Paper Type of Literature-in-English is given to you?", "Type B", "Type I", "Type B", "Type U", 3, "Type U selected."),
    ("jamb_lit_2013_02", "Literature in English", "Sons and Daughters - J.C. De Graft", "2013", "James: 'Let me swear, woman. And I will swear by my father's coffin that if...' depicts James as a", "traditionalist", "Christian", "pagan", "Muslim", 0, "Swearing by an ancestor's coffin reflects unyielding traditional oaths."),
    ("jamb_lit_2013_03", "Literature in English", "Sons and Daughters - J.C. De Graft", "2013", "In the excerpt above, James is addressing", "Fosuwa", "Awere", "Maanan", "Hannah", 3, "James quarrels with his patient wife Hannah regarding household management."),
    ("jamb_lit_2013_04", "Literature in English", "Sons and Daughters - J.C. De Graft", "2013", "Aaron: '...All I need really is a place in an Art school, engineering can go hang itself.' Dominant device is", "metonymy", "synecdoche", "personification", "metaphor", 2, "Engineering is personified as an entity that can 'go hang itself'."),
    ("jamb_lit_2013_05", "Literature in English", "Sons and Daughters - J.C. De Graft", "2013", "From the play, the character of Aaron represents the", "painters", "art work", "new educated generation", "old generation", 2, "Aaron symbolizes modern African youth defying rigid paternal career demands."),
    ("jamb_lit_2013_06", "Literature in English", "Romeo and Juliet - William Shakespeare", "2013", "'Uncle, this is a Montague, our foe; A villain that is hither come in spite, To scorn at our solemnity this night.' The villain is", "attempting to steal", "attending a feast uninvited", "engaging in a shouting match", "holding a sword to murder", 1, "Tybalt recognizes Romeo crashing the Capulet masquerade ball uninvited."),
    ("jamb_lit_2013_07", "Literature in English", "Romeo and Juliet - William Shakespeare", "2013", "'What, drawn and talk of peace? I hate the word As I hate hell, all Montagues, and thee Have at thee, coward!' reveals speaker as a", "violence seeker", "peace maker", "real Montague", "trouble shooter", 0, "Tybalt reveals his aggressive, pugnacious temperament."),
    ("jamb_lit_2013_08", "Literature in English", "Romeo and Juliet - William Shakespeare", "2013", "Romeo's mood at the beginning of the play can be described as", "melancholic and lovesick", "dreamy and hopeful", "frustrated and angry", "elated", 0, "Pines obsessively in unrequited love for Rosaline."),
    ("jamb_lit_2013_09", "Literature in English", "Romeo and Juliet - William Shakespeare", "2013", "'O deadly sin! O rude unthankfulness! Thy fault our law calls death, but the kind Prince... turned that black word death to banishment.' Speaker is", "Lord Montague", "Friar Lawrence", "Apothecary", "Lord Capulet", 1, "Friar Lawrence reprimands Romeo for lamenting his exile instead of celebrating spared life."),
    ("jamb_lit_2013_10", "Literature in English", "Romeo and Juliet - William Shakespeare", "2013", "'...Put up thy sword Or manage it to part these men with me.' Speech was made when", "Tybalt challenges Romeo", "Prince Escalus arrives", "Romeo fights Paris", "Benvolio tries to separate the brawling servants", 3, "Benvolio attempts to halt the street brawl between Capulet and Montague servants."),
    ("jamb_lit_2013_11", "Literature in English", "The Old Man and the Medal - Ferdinand Oyono", "2013", "For his land sacrifices to the church, Meka receives", "appointment to elders' council", "privilege to choose a seat", "a place near an aged leper", "new farm land", 2, "Satirical reward placing the aging benefactor next to an outcast leper."),
    ("jamb_lit_2013_12", "Literature in English", "The Old Man and the Medal - Ferdinand Oyono", "2013", "'Since I came to this country, I have never seen cocoa as well dried as yours.' The speaker is", "Nkolo", "the Commandant", "the Catechist", "Nua", 1, "The French colonial officer flatters Meka during farm inspection."),
    ("jamb_lit_2013_13", "Literature in English", "The Old Man and the Medal - Ferdinand Oyono", "2013", "To the white colonialists, the medal given to Meka symbolizes", "harmonious paternalistic control", "true love", "peace", "superficial tokenism / friendship", 3, "A worthless decorative medal substituting for genuine rights and equality."),
    ("jamb_lit_2013_14", "Literature in English", "The Joys of Motherhood - Buchi Emecheta", "2013", "In Ibuza society, Nnu Ego is blamed for the misfortunes of her", "parents", "husband", "siblings", "children", 3, "A mother carries sole traditional blame for any illness, failure, or delinquency of her offspring."),
    ("jamb_lit_2013_15", "Literature in English", "The Joys of Motherhood - Buchi Emecheta", "2013", "According to the novel, Nnaife becomes deeply frustrated when", "Oshiaju secures a scholarship abroad", "he is arrested for assault", "his wife bears female twins", "he is conscripted into the army", 2, "Traditional expectations make female twin births a cultural and economic disappointment in his eyes."),
    ("jamb_lit_2013_16", "Literature in English", "The Joys of Motherhood - Buchi Emecheta", "2013", "Adaku remains in Nnaife's compound until she", "keeps bad friends", "is unable to give birth to a male child and leaves for trading independence", "is rebuked by Ibuza society", "becomes poor", 1, "Deprived of status due to having only daughters, Adaku leaves to achieve economic autonomy."),
    ("jamb_lit_2013_17", "Literature in English", "Nineteen Eighty-Four - George Orwell", "2013", "The Ministry of Love is primarily concerned with", "peace", "torture, brainwashing and interrogation", "joy", "hatred", 1, "Miniluv enforces ideological compliance through torture and psychological reprogramming."),
    ("jamb_lit_2013_18", "Literature in English", "Nineteen Eighty-Four - George Orwell", "2013", "The absolute instruments of power and surveillance belong to", "the citizens", "the Inner Party", "Thought Police", "the proletariat", 1, "The Party wields monopoly over surveillance telescreens and judicial power."),
    ("jamb_lit_2013_19", "Literature in English", "Nineteen Eighty-Four - George Orwell", "2013", "The entire central narrative of the novel is built around", "Winston Smith", "O'Brien", "Julia", "Emmanuel Goldstein", 0, "Winston's internal struggle and ill-fated rebellion against totalitarian control."),
    ("jamb_lit_2013_20", "Literature in English", "Nineteen Eighty-Four - George Orwell", "2013", "Winston Smith works in the Records Department of the Ministry of", "Love", "Truth (Minitrue)", "Peace", "Plenty", 1, "Winston fabricates historical records to conform with shifting Party propaganda."),
    ("jamb_lit_2013_21", "Literature in English", "Poetry - Naked Soles", "2013", "The dominant poetic technique in Adeoti's Naked Soles is", "zeugma", "oxymoron", "hyperbole", "onomatopoeia / vivid metaphor", 3, "Sensory soundscapes and rhythmic descriptions of collective walking."),
    ("jamb_lit_2013_22", "Literature in English", "Poetry - An African Thunderstorm", "2013", "Rubadiri's An African Thunderstorm can be described as", "didactic", "dramatic and evocative", "traditional", "satirical", 1, "Vivid kinetic depiction of rolling storm clouds and domestic panic."),
    ("jamb_lit_2013_23", "Literature in English", "Poetry - A Heritage of Liberation", "2013", "'Since it was you who in all these thin seasons...' is an example of", "apostrophe", "allusion", "anecdote", "aside", 0, "Direct poetic address to departed liberation heroes."),
    ("jamb_lit_2013_24", "Literature in English", "Poetry - Give Me The Minstrel's Seat", "2013", "'Let me ask for what reason or rhyme women refuse to marry?' exemplifies", "pathetic fallacy", "chiasmus", "irony", "rhetorical question", 3, "A rhetorical query probing contemporary marriage dynamics."),
    ("jamb_lit_2013_25", "Literature in English", "Poetry - To His Coy Mistress", "2013", "'Time's winged chariot hurrying near' depicts", "how fast time flies", "usefulness of time", "measurement of time", "history", 0, "Personifies time as a rushing chariot hastening mortality."),
    ("jamb_lit_2013_26", "Literature in English", "Poetry - Bat", "2013", "D.H. Lawrence's Bat opens with a serene description of the", "Italian evening scene and twilight over Florence", "creatures", "caves", "darkness", 0, "Begins at dusk on the terrace overlooking the River Arno in Florence."),
    ("jamb_lit_2013_27", "Literature in English", "Poetry - Journey of the Magi", "2013", "The central spiritual theme of Eliot's Journey of the Magi is", "quest for spiritual salvation through suffering", "escape from persecution", "nature beauty", "travel guide", 0, "The arduous spiritual transformation required to embrace the Christian faith."),
    ("jamb_lit_2013_28", "Literature in English", "Poetry - In the Navel of the Soul", "2013", "Acquah's In the Navel of the Soul describes the", "lack of midwives", "excesses of modern charismatic churches and politicians", "complications of childbirth", "colonial taxes", 1, "Satirizes hypocritical televangelists and corrupt political opportunists."),
    ("jamb_lit_2013_29", "Literature in English", "Poetry - End of the War", "2013", "'Listen... to beat drums is mere children's play, the adult's is to start echoes...' enhances", "rhyme", "rhythm", "language", "use of philosophical imagery", 3, "Metaphorical drums and echoes contrast superficial acts with enduring consequences."),
    ("jamb_lit_2013_30", "Literature in English", "Poetry - Sonnet VII", "2013", "The language of Wendy Cope's Sonnet VII is deliberately", "complicated", "simple and conversational", "archaic", "latinate", 1, "Employs accessible, contemporary, unpretentious diction."),
    ("jamb_lit_2013_31", "Literature in English", "Literary Principles", "2013", "A device used by an author to recall past events in a narrative is", "interlude", "anti-climax", "flashback (analepsis)", "foreshadowing", 2, "A flashback interrupts chronology to reveal earlier background information."),
    ("jamb_lit_2013_32", "Literature in English", "Literary Principles", "2013", "A paragraph in prose is structurally equivalent to a", "trope", "verse", "stanza", "meter", 2, "A stanza organizes groups of lines in poetry just as paragraphs organize prose."),
    ("jamb_lit_2013_33", "Literature in English", "Literary Principles", "2013", "A fable is a brief narrative illustrating wisdom and moral", "urgency", "origin", "custom", "truth", 3, "Conveys timeless moral truths and ethical guidance."),
    ("jamb_lit_2013_34", "Literature in English", "Literary Principles", "2013", "A poetic device that repeats words or phrases for emphasis is", "rhyme", "assonance", "repetition", "alliteration", 2, "Repetition reinforces dominant motifs, emotions, and themes."),
    ("jamb_lit_2013_35", "Literature in English", "Literary Principles", "2013", "A literary work that ridicules the vices and shortcomings of individuals or society is a", "masque", "satire", "irony", "fable", 1, "Satire uses wit, irony, and ridicule to expose folly and provoke reform."),
    ("jamb_lit_2013_36", "Literature in English", "Literary Principles", "2013", "The figure of speech where a speaker says the opposite of what is meant is", "satire", "irony", "paradox", "metaphor", 1, "Verbal irony expresses meaning through the opposite literal statement."),
    ("jamb_lit_2013_37", "Literature in English", "Literary Principles", "2013", "Dramatic action and storytelling conveyed entirely through physical gesture without speech is", "soliloquy", "aside", "epilogue", "mime (pantomime)", 3, "Mime relies on silent bodily expression and movement."),
    ("jamb_lit_2013_38", "Literature in English", "Literary Principles", "2013", "A literary work explicitly designed to teach moral and ethical lessons is", "impressive", "didactic", "instructive", "corrective", 1, "Didactic literature prioritizes moral, philosophical, or educational instruction."),
    ("jamb_lit_2013_39", "Literature in English", "Literary Principles", "2013", "A fatal character flaw that leads directly to a tragic hero's downfall is known as", "comic relief", "terse", "climax", "tragic flaw (hamartia)", 3, "Hamartia is the fatal flaw (e.g. hubris, jealousy, indecision) precipitating downfall."),
    ("jamb_lit_2013_40", "Literature in English", "Literary Principles", "2013", "A dramatic speech delivered by an actor alone on stage revealing inner thoughts is a", "monologue", "epilogue", "aside", "soliloquy", 3, "A soliloquy allows characters to speak their private thoughts aloud while alone."),
    ("jamb_lit_2013_41", "Literature in English", "Night - Wole Soyinka", "2013", "'Women as a clam, on the sea's crescent I saw your jealous eye quench the sea's fluorescence...' suggests women are", "magicians", "mysterious, watchful and possessing hidden depths", "dogmatic", "seers", 1, "Metaphor of the closed clam capturing nocturnal mystery and watchful presence."),
    ("jamb_lit_2013_42", "Literature in English", "The Sun Rising - John Donne", "2013", "'Busy old fool, unruly sun Why dost thou thus Through windows... call on us?' suggests", "praise of nature", "invitation to sun", "welcoming the sun", "indictment and playful scolding of the intrusive sun", 3, "The metaphysical speaker boldly scolds the sun for disturbing two lovers."),
    ("jamb_lit_2013_43", "Literature in English", "The Sun Rising - John Donne", "2013", "Addressing the sun as a 'busy old fool' employs the figure of speech known as", "simile", "personification and apostrophe", "epigram", "pun", 1, "Personifies the sun as a prying elderly busybody and addresses it directly."),
    ("jamb_lit_2013_44", "Literature in English", "The Solitary Reaper - William Wordsworth", "2013", "'Will no one tell me what she sings? Perhaps the plaintive numbers flow For old, unhappy, far-off things...' reveals persona", "does not understand the Scots Gaelic language of the song", "is in love", "hates the song", "knows the tune", 0, "Wordsworth listens to the Scottish Highland girl singing in Scots Gaelic."),
    ("jamb_lit_2013_45", "Literature in English", "The Solitary Reaper - William Wordsworth", "2013", "'Familiar matter of today? Some natural sorrow, loss, or pain...' ends in a", "transferred epithet", "rhetorical question", "irony", "conceit", 1, "The speaker ponders the song's universal themes through rhetorical questions."),
    ("jamb_lit_2013_46", "Literature in English", "Literary Appreciation", "2013", "'Oh incomprehensible God! Shall my pilot be My inborn stars...' used in the opening line is", "passion", "apostrophe", "burlesque", "rhetoric", 1, "Direct exclamation and invocation addressed to God (apostrophe)."),
    ("jamb_lit_2013_47", "Literature in English", "The Sun Rising - John Donne", "2013", "Donne views the morning sun intruding upon lovers as an", "a necessary light", "a light provider", "illumination", "an unwelcome intruder / nuisance", 3, "Scolds the sun for trying to enforce temporal working hours on love."),
    ("jamb_lit_2013_48", "Literature in English", "Literary Appreciation", "2013", "'The body perishes, the heart stays young. The platter wears away with serving food... No lover peaceful while the rival weeps' theme is", "permanence of true love", "decay of wood", "turbulent, possessive nature of love", "diminishing love", 2, "Explores passionate possessiveness and emotional turbulence in love."),
    ("jamb_lit_2013_49", "Literature in English", "Literary Appreciation", "2013", "'No lover peaceful while the rival weeps' signifies that", "true love is peaceful", "lovers weep together", "rivalry brings continuous anxiety and lack of peace", "there is no love", 2, "Romantic competition breeds perpetual unrest until resolved."),
    ("jamb_lit_2013_50", "Literature in English", "Dizzy Angel - Grace Osifo", "2013", "'Will college make you a better Olokun priest? Look at me... Did I go to college?' device used is", "simile", "parallelism and rhetorical question", "onomatopoeia", "metaphor", 1, "Succession of rhetorical questions asserting traditional ritual authority over formal schooling.")
]
lit_all.extend(l2013)

print(f"Total Literature questions through 2013: {len(lit_all)}")
