import sys, os
sys.path.append(os.path.dirname(__file__))
from bank_writer import write_kotlin_bank
from generate_literature_official import lit_all

# --- 2011 LITERATURE (50 Qs) ---
l2011 = [
    ("jamb_lit_2011_01", "Literature in English", "Exam Administration", "2011", "Which Question Paper Type of Literature-in-English is given to you?", "Type A", "Type B", "Type C", "Type D", 3, "Paper Type D assigned."),
    ("jamb_lit_2011_02", "Literature in English", "Sons and Daughters - J.C. De Graft", "2011", "From its resolution of conflicts, the play can be described as", "tragedy", "comedy", "farce", "melodrama", 1, "The play ends harmoniously with reconciliation between the father and his children."),
    ("jamb_lit_2011_03", "Literature in English", "Sons and Daughters - J.C. De Graft", "2011", "The prevailing theme of the play is", "love", "affluence", "social decadence", "parental tyranny and generation gap", 3, "Focuses on generational conflict between traditional parental ambition and youthful career choices."),
    ("jamb_lit_2011_04", "Literature in English", "Sons and Daughters - J.C. De Graft", "2011", "The final harassment of Maanan takes place in", "Ofosu's office", "Lawyer B's house", "Lawyer B's chamber", "Ofosu's house", 3, "Lawyer B attempts his final improper overtures inside the Ofosu family home."),
    ("jamb_lit_2011_05", "Literature in English", "Sons and Daughters - J.C. De Graft", "2011", "'Everything in this room outrages my sense of beauty, undermines my will to create...' The speaker is", "happy", "frustrated", "excited", "tired", 1, "Aaron expresses artistic frustration at his father's lack of appreciation for painting."),
    ("jamb_lit_2011_06", "Literature in English", "Romeo and Juliet - William Shakespeare", "2011", "'Farewell - God knows when we shall meet again. I have a faint cold fear thrills through my veins... Come, vial.' The intention of the speaker is to", "commit suicide", "take a temporary sleeping potion", "escape reality", "challenge Paris", 1, "Juliet drinks the distilled liquor prepared by Friar Lawrence to feign death for 42 hours."),
    ("jamb_lit_2011_07", "Literature in English", "Romeo and Juliet - William Shakespeare", "2011", "The play reaches the point of denouement", "at the family feast", "when Romeo kills Paris", "at the reconciliation of the feuding families", "when Romeo is informed of Juliet's death", 2, "The Capulets and Montagues finally end their ancient blood feud upon witnessing their children's sacrifice."),
    ("jamb_lit_2011_08", "Literature in English", "Romeo and Juliet - William Shakespeare", "2011", "The news of Juliet's death is broken to Romeo in Mantua by", "Balthasar", "Friar Lawrence", "Boy", "Friar John", 0, "Balthasar rides to Mantua and mistakenly reports Juliet's burial in the Capulet vault."),
    ("jamb_lit_2011_09", "Literature in English", "Romeo and Juliet - William Shakespeare", "2011", "In the play, Mercutio can be described as", "fraudulent", "quarrelsome and witty", "gentle", "kind-hearted", 1, "Mercutio is hot-tempered, quick to duel Tybalt, yet brilliantly satirical and lively."),
    ("jamb_lit_2011_10", "Literature in English", "Romeo and Juliet - William Shakespeare", "2011", "The plot of the play is", "simple", "complicated", "convoluted", "chronological", 3, "The tragedy follows a strict five-day chronological timeline from Sunday to Thursday night."),
    ("jamb_lit_2011_11", "Literature in English", "The Old Man and the Medal - Ferdinand Oyono", "2011", "The heavy downpour on the night of Meka's investiture symbolizes", "revelation", "mockery", "conviction", "blessing", 1, "The torrential rain washes away Meka's illusions and highlights colonial abandonment."),
    ("jamb_lit_2011_12", "Literature in English", "The Old Man and the Medal - Ferdinand Oyono", "2011", "Vandermayer's attitude and action towards Meka illustrates the church's", "despondency", "suspicion", "infuriation", "hypocrisy", 3, "Exposes double standards between christian preachings and discriminatory colonial treatment."),
    ("jamb_lit_2011_13", "Literature in English", "The Old Man and the Medal - Ferdinand Oyono", "2011", "'As he opened and shut his mouth his lower jaw went down and came up, puffing up...' Describes", "the High Commissioner", "M. Pipiniakis", "the White Chief", "M. Fouconi", 3, "Satirical caricature describing the grotesque physical appearance of the French official."),
    ("jamb_lit_2011_14", "Literature in English", "The Joys of Motherhood - Buchi Emecheta", "2011", "For attempted murder, Nnaife was jailed for", "four months", "three months", "five months", "two months", 3, "Nnaife serves a two-month prison sentence following the cutlass confrontation with his in-laws."),
    ("jamb_lit_2011_15", "Literature in English", "The Joys of Motherhood - Buchi Emecheta", "2011", "In the novel, Nwokocha Agbadi is famous for his oratorical powers and", "height", "treachery", "illiteracy", "wealth and bravery", 3, "Agbadi is a wealthy, revered chief and great hunter in Ibuza."),
    ("jamb_lit_2011_16", "Literature in English", "The Joys of Motherhood - Buchi Emecheta", "2011", "The handing over of a baby boy in a dream to Nnu Ego by her personal god signifies", "reincarnation", "future blessing", "idol worship", "doom", 1, "Foreshadows her upcoming fertility and long-awaited male children in Lagos."),
    ("jamb_lit_2011_17", "Literature in English", "Nineteen Eighty-Four - George Orwell", "2011", "The novel draws a picture of", "a useless past", "a totalitarian future", "an unstable moment", "a peaceful atmosphere", 1, "Dystopian warning against future omnipotent surveillance and total state tyranny."),
    ("jamb_lit_2011_18", "Literature in English", "Nineteen Eighty-Four - George Orwell", "2011", "The power and oppression of an irresistible evil debased Winston's dreams of", "freedom and democracy", "internal security", "wealth and capitalism", "sovereignty", 0, "The Thought Police crush all aspirations of personal autonomy, free thought, and democracy."),
    ("jamb_lit_2011_19", "Literature in English", "Nineteen Eighty-Four - George Orwell", "2011", "Room 101 symbolizes a place of", "rest", "fun", "humiliation and worst fear", "tour", 2, "Room 101 houses 'the worst thing in the world' customized to break each prisoner's soul."),
    ("jamb_lit_2011_20", "Literature in English", "Nineteen Eighty-Four - George Orwell", "2011", "The overall atmosphere of the novel can be described as", "optimistic", "antagonistic", "persuasive", "pessimistic and bleak", 3, "Concludes on an uncompromisingly grim note as Winston succumbs to loving Big Brother."),
    ("jamb_lit_2011_21", "Literature in English", "Poetry - Naked Soles", "2011", "In Naked Soles, Adeoti writes that the carnival of naked soles dances through", "scorching sun", "a dirty room", "blooming thorns", "a cloudy atmosphere", 2, "Dancers navigate 'blooming thorns', symbolizing surviving socio-political hardship."),
    ("jamb_lit_2011_22", "Literature in English", "Poetry - An African Thunderstorm", "2011", "In Rubadiri's An African Thunderstorm, the storm begins with", "rain from the west", "clouds from the east", "rain from the east", "clouds from the west", 3, "'From the west / Clouds come hurrying with the wind / Turning sharply / Here and there'."),
    ("jamb_lit_2011_23", "Literature in English", "Poetry - In the Navel of the Soul", "2011", "The theme of Acquah's In the Navel of the Soul is", "the conflict of traditions", "ensuring traditions were strictly observed", "the futility of man and tradition", "the strength in cultural roots", 3, "Emphasizes reconnecting with ancestral identity and spiritual heritage."),
    ("jamb_lit_2011_24", "Literature in English", "Poetry - A Heritage of Liberation", "2011", "In Kunene's A Heritage of Liberation, the persona is concerned with the", "people's struggle for liberation", "criticism of modern tradition", "intolerance of new generation", "celebration of tradition", 0, "Honors freedom fighters who endured sacrifice to liberate their nation."),
    ("jamb_lit_2011_25", "Literature in English", "Poetry - End of the War", "2011", "Launko's End of the War portrays the", "silence of defeat", "usefulness of praise singers", "irony of peace after destruction", "arrangement of war", 2, "Explores how devastation lingers long after formal armistices are signed."),
    ("jamb_lit_2011_26", "Literature in English", "Poetry - Give Me The Minstrel's Seat", "2011", "'Woman cannot exist except by man, What is there in that to vex some of them so?' is an example of", "litotes", "rhetorical question", "transferred epithet", "synecdoche", 1, "The speaker asks a provocative rhetorical question regarding traditional marital norms."),
    ("jamb_lit_2011_27", "Literature in English", "Poetry - To His Coy Mistress", "2011", "Marvell uses the imagery of death ('The grave's a fine and private place') to", "appreciate God's power", "underscore life's transience (carpe diem)", "condemn the lady", "scare the lady", 1, "Employs carpe diem philosophy urging urgent consummation of love before youth vanishes."),
    ("jamb_lit_2011_28", "Literature in English", "Poetry - Bat", "2011", "To sustain the interest of readers, Lawrence in Bat uses", "elision", "hyperbole", "suspense", "oxymoron", 2, "Delays identifying the creature to build atmospheric tension and eerie mystery."),
    ("jamb_lit_2011_29", "Literature in English", "Poetry - Journey of the Magi", "2011", "'With a running stream and a water-mill beating the darkness. And three trees on the low sky.' The dominant device is", "oxymoron", "personification", "hyperbole", "alliteration / symbolism", 3, "Water-mill beating the darkness personifies nature and alliterates sounds."),
    ("jamb_lit_2011_30", "Literature in English", "Poetry - Sonnet VII", "2011", "The tone of Wendy Cope's Sonnet VII is generally", "persuasive", "humorous and witty", "optimistic", "mournful", 1, "Cope adopts a playful, self-deprecating, and humorous perspective on poetry."),
    ("jamb_lit_2011_31", "Literature in English", "Literary Principles", "2011", "The large space above the proscenium arch from which stage scenery is controlled is called", "aside", "setting", "anachronism", "flies", 3, "The fly loft (flies) is the rigging space above the stage for flying scenery and lights."),
    ("jamb_lit_2011_32", "Literature in English", "Literary Principles", "2011", "Zhang Yu's 'Good warriors make others come to them... attacking emptiness with fullness' theme is", "folly of soldiers", "military strategy and foresight", "spurring people to action", "war destruction", 1, "Advocates strategic preparation and psychological initiative in conflict."),
    ("jamb_lit_2011_33", "Literature in English", "Literary Principles", "2011", "The repetition of single words or phrases at the beginning of successive lines is", "assonance", "anaphora / parallelism", "onomatopoeia", "alliteration", 1, "Anaphora is the deliberate repetition of initial words across poetic lines."),
    ("jamb_lit_2011_34", "Literature in English", "Literary Principles", "2011", "A traditional ballad is originally meant to be", "acted", "sung", "discussed", "read silently", 1, "Folk ballads were oral, rhythmic verses sung to musical accompaniment."),
    ("jamb_lit_2011_35", "Literature in English", "Literary Principles", "2011", "In dramatic production, a dramaturge is one who", "writes, adapts or researches dramatic texts", "features in a play", "directs a play", "acts in a film", 0, "A dramaturge provides literary, historical, and structural counsel for productions."),
    ("jamb_lit_2011_36", "Literature in English", "Literary Principles", "2011", "A travelogue is a work of art written", "by a famous playwright", "before death", "by an unpopular novelist", "on a journey", 3, "Records factual narrative accounts of an author's journeys and encounters."),
    ("jamb_lit_2011_37", "Literature in English", "Literary Principles", "2011", "Plays are fundamentally created and written to be", "read quietly", "kept in libraries", "studied for tests", "presented on stage", 3, "Drama is primarily intended for live theatrical performance."),
    ("jamb_lit_2011_38", "Literature in English", "Literary Principles", "2011", "A character who re-enacts familiar, stereotypical experiences that audiences easily identify with is a", "round character", "flat character", "stock character", "static character", 2, "A stock character is a conventional, universally recognizable literary archetype."),
    ("jamb_lit_2011_39", "Literature in English", "Literary Principles", "2011", "The plot of a story generally refers to the", "intrigue made against hero", "ending", "causal arrangement of events", "opening exposition", 2, "Plot is the deliberate, causal sequence of narrative events."),
    ("jamb_lit_2011_40", "Literature in English", "Literary Principles", "2011", "A line of verse consisting of five metrical feet (ten syllables) is", "trochaic decametre", "dactylic metre", "iambic pentameter", "anapaestic metre", 2, "Five iambic feet per line forms standard iambic pentameter."),
    ("jamb_lit_2011_41", "Literature in English", "Literary Appreciation", "2011", "'Theseus: Now, fair Hippolyta... This old moon wanes, she lingers my desires, Like to a step-dame...' Literary devices used are", "personification and simile", "irony and suspense", "alliteration and synecdoche", "rhyme and refrain", 0, "Moon personified as 'she', with comparison using 'like to a step-dame'."),
    ("jamb_lit_2011_42", "Literature in English", "Literary Appreciation", "2011", "'You are the silent code of pleasure... hive of treasure, no dragon can plunder' achieves effect through", "repetition and meiosis", "metaphor and rhyme", "caesura and hyperbole", "alliteration and irony", 1, "Direct metaphors ('hive of treasure') paired with end rhyme (wonder/plunder)."),
    ("jamb_lit_2011_43", "Literature in English", "A Forest of Flowers - Ken Saro-Wiwa", "2011", "In Saro-Wiwa's A Forest of Flowers, the passenger's experience inside the crowded lift is", "timely", "comfortable", "unpleasant and suffocating", "amusing", 2, "Endures intense body odor and claustrophobia before tumbling out in relief."),
    ("jamb_lit_2011_44", "Literature in English", "The Gods Are Not To Blame - Ola Rotimi", "2011", "'Are not people ailing and dying?' In the excerpt, the land of Kutuje is not at peace because of", "chieftaincy tussle", "famine and war", "political unrest", "pestilence, sickness and death", 3, "A devastating plague ravages the kingdom due to an unpunished ancestral curse."),
    ("jamb_lit_2011_45", "Literature in English", "The Vulture - David Diop", "2011", "'When civilization kicked us in the face, when holy water slapped brows...' Dominant literary device is", "pun", "metaphor", "personification", "simile", 2, "Civilization and holy water are personified as violent, abusive forces."),
    ("jamb_lit_2011_46", "Literature in English", "Literary Appreciation", "2011", "'I am not afraid of anything; I have been in prison more hours than I have been out of it...' Speaker's tone is", "regretful", "boastful and brazen", "subdued", "repentant", 1, "Takes arrogant pride in reckless criminal exploits without displaying remorse."),
    ("jamb_lit_2011_47", "Literature in English", "Twelfth Night - William Shakespeare", "2011", "'I have said too much unto a heart of stone...' 'A heart of stone' is an example of", "metonymy", "litotes", "assonance", "metaphor", 3, "Metaphorically equates an unfeeling, unresponsive lover's heart to cold stone."),
    ("jamb_lit_2011_48", "Literature in English", "Two Thousand Seasons - Ayi Kwei Armah", "2011", "In Armah's Two Thousand Seasons, the narrator's attitude to the self-isolated king is one of", "envy", "sympathy", "suspicion", "contempt", 3, "Condemns the corrupt monarch's moral degradation and cowardice."),
    ("jamb_lit_2011_49", "Literature in English", "Salutation to the Gods - Gbemisola Adeoti", "2011", "'Homage to Peregede the triumphant mother of morning... Let today's dawn bring...' is an example of", "invocation", "limerick", "ode", "elegy", 0, "A solemn ritual invocation calling upon divine morning spirits."),
    ("jamb_lit_2011_50", "Literature in English", "Tithonus - Alfred Lord Tennyson", "2011", "'The woods decay, the woods decay and fall... Man comes and fills the field and lies beneath' subject matter is", "death and mortality", "rainfall", "famine", "storm", 0, "Contrasts universal mortal decay and natural death with the tragedy of endless physical aging.")
]
lit_all.extend(l2011)

print(f"Total Literature questions through 2011: {len(lit_all)}")
