import sys, os
sys.path.append(os.path.dirname(__file__))
from bank_writer import write_kotlin_bank
from generate_lit_2011 import lit_all

# --- 2012 (50 Qs) ---
l2012 = [
    ("jamb_lit_2012_01", "Literature in English", "Exam Administration", "2012", "Which Question Paper Type of Literature-in-English is given to you?", "Type Green", "Type Purple", "Type Red", "Type Yellow", 2, "Type Red assigned."),
    ("jamb_lit_2012_02", "Literature in English", "Sons and Daughters - J.C. De Graft", "2012", "Who is the paternal aunt to Aaron and Maanan?", "Mrs Bonu", "Hannah", "Fosuwa", "Adwao", 2, "Aunt Fosuwa is James Ofosu's sister and aunt to the children."),
    ("jamb_lit_2012_03", "Literature in English", "Sons and Daughters - J.C. De Graft", "2012", "From the play, George is a", "laboratory assistant", "pharmacist", "nurse", "medical doctor", 3, "George is a qualified medical doctor and James's eldest son."),
    ("jamb_lit_2012_04", "Literature in English", "Sons and Daughters - J.C. De Graft", "2012", "'If you touch me, I shall smash your face with this bottle.' The statement is made by", "Maanan to Lawyer B", "Maanan to Mrs Bonu", "James to Awere", "Awere to Aaron", 0, "Maanan fiercely defends her dignity against Lawyer B's advances."),
    ("jamb_lit_2012_05", "Literature in English", "Sons and Daughters - J.C. De Graft", "2012", "The issue at stake during the confrontation is that", "Maanan is compromising", "Lawyer B is attempting to assault Maanan", "James opposes Awere", "Mrs Bonu is taunting Maanan", 1, "Lawyer B attempts to force an unwanted kiss upon Maanan."),
    ("jamb_lit_2012_06", "Literature in English", "Romeo and Juliet - William Shakespeare", "2012", "'From forth the fatal loins of these two foes A pair of star-crossed lovers take their life...' suggests tragedy is", "avertable", "predestined by fate", "brought on enmity", "misfortune only", 1, "The prologue establishes that the tragedy is governed by celestial fate (star-crossed)."),
    ("jamb_lit_2012_07", "Literature in English", "Romeo and Juliet - William Shakespeare", "2012", "'O she doth teach the torches to burn bright! It seems she hangs upon the cheek of night Like a rich jewel...' Juliet's beauty is presented", "in contrast to dark night", "as source of envy", "in terms of riches", "as outstanding brilliance", 3, "Romeo is captivated by her radiant luminescence against surrounding darkness."),
    ("jamb_lit_2012_08", "Literature in English", "Romeo and Juliet - William Shakespeare", "2012", "'The all-seeing sun, Ne'er saw her match since first the world begun' was spoken by", "Count Paris in praise of Juliet", "Romeo in praise of Juliet", "Romeo in praise of Rosaline", "Lady Capulet in praise of Rosaline", 2, "Romeo proclaims this in Act 1 while still infatuated with Rosaline."),
    ("jamb_lit_2012_09", "Literature in English", "Romeo and Juliet - William Shakespeare", "2012", "The major role of Mercutio in the play is to", "serve as a dramatic foil to Romeo", "aid Romeo's passion", "annoy Tybalt", "accompany Romeo to church", 0, "Mercutio's cynical, witty realism balances Romeo's romantic idealism."),
    ("jamb_lit_2012_10", "Literature in English", "Romeo and Juliet - William Shakespeare", "2012", "The play shares features of classical tragedy through the use of", "violence on stage", "the prologue/chorus", "comic relief", "flashback", 1, "A chorus delivers the formal exposition and philosophical frame in the opening sonnet."),
    ("jamb_lit_2012_11", "Literature in English", "The Old Man and the Medal - Ferdinand Oyono", "2012", "'Meka, kneeling down in his usual fashion with his behind up in the air. Kelara knelt beside him...' Actions signify", "parade", "dance", "christian prayer", "celebration", 2, "Depicts their devotional prayer routine before the French ceremony."),
    ("jamb_lit_2012_12", "Literature in English", "The Old Man and the Medal - Ferdinand Oyono", "2012", "'He had knocked his toes against so many things that he had no toenails anymore...' refers to the feet of", "Kelara", "Meka", "Egamba", "Mvondo", 1, "Realistic portrait of peasant patriarch Meka suffering inside tight European leather shoes."),
    ("jamb_lit_2012_13", "Literature in English", "The Old Man and the Medal - Ferdinand Oyono", "2012", "'They said their prayers in a monotonous sing-song... like camels waiting to be loaded.' Dominant figure of speech is", "rhetorical question", "simile", "metaphor", "mixed metaphor", 1, "Explicit comparison using 'like camels waiting to be loaded'."),
    ("jamb_lit_2012_14", "Literature in English", "The Joys of Motherhood - Buchi Emecheta", "2012", "As a symbol of material success and fulfilment, Ibuza community places high importance on", "childbirth and male offspring", "wealth", "large farmland", "chieftaincy", 0, "A woman's honor in Ibuza is strictly tied to bearing sons to inherit the lineage."),
    ("jamb_lit_2012_15", "Literature in English", "The Joys of Motherhood - Buchi Emecheta", "2012", "Ona on her dying bed appeals to Agbadi to", "give her a befitting burial", "take good care of children", "take another wife", "allow Nnu Ego to marry a man of her choice", 3, "Plea that their daughter be granted freedom to choose her own spouse."),
    ("jamb_lit_2012_16", "Literature in English", "The Joys of Motherhood - Buchi Emecheta", "2012", "The money Nnaife receives upon returning from military service in Burma is used for", "expanding business", "taking care of family", "sending children to school", "paying bride price for additional wives", 3, "Nnaife spends his military gratuity marrying more wives in Ibuza."),
    ("jamb_lit_2012_17", "Literature in English", "Nineteen Eighty-Four - George Orwell", "2012", "The novel is primarily classified as a", "dystopian satire", "hyperbole", "romance", "historical chronicle", 0, "Political satire attacking totalitarian propaganda, historical revisionism, and authoritarianism."),
    ("jamb_lit_2012_18", "Literature in English", "Nineteen Eighty-Four - George Orwell", "2012", "Winston writes in his diary that hope for overthrowing the Party lies with the", "Ministry of Truth", "Proles (working class)", "Outer Party", "children", 1, "'If there is hope, wrote Winston, it lies in the proles.'"),
    ("jamb_lit_2012_19", "Literature in English", "Nineteen Eighty-Four - George Orwell", "2012", "In the novel, the Two Minutes Hate is a programme designed for", "parents", "indoctrinating party members and channeling aggression", "the community", "foreigners", 1, "Rallies collective hatred against Goldstein and Oceania's enemies."),
    ("jamb_lit_2012_20", "Literature in English", "Nineteen Eighty-Four - George Orwell", "2012", "To break his philosophy and enforce orthodoxy, Winston is tortured in the Ministry of Love by", "O'Brien", "Thought Police", "Big Brother", "Goldstein", 0, "Inner Party member O'Brien oversees Winston's psychological re-education."),
    ("jamb_lit_2012_21", "Literature in English", "Poetry - Naked Soles", "2012", "The movement in Adeoti's Naked Soles is characterized by", "hope and agreement", "freedom and self-determination", "pricks and tears", "disappointment and disarray", 2, "Depicts painful perseverance across sharp metaphorical obstacles."),
    ("jamb_lit_2012_22", "Literature in English", "Poetry - An African Thunderstorm", "2012", "One of the dominant themes of Rubadiri's An African Thunderstorm is the", "relationship between man and woman", "destructive and unpredictable power of nature", "effect of rain on women and children", "climate change", 1, "Vividly captures the chaotic elemental fury of a tropical storm."),
    ("jamb_lit_2012_23", "Literature in English", "Poetry - A Heritage of Liberation", "2012", "In Kunene's A Heritage of Liberation, weapons are preserved for unborn generations by the", "gods", "elders", "freedom fighters / people", "government", 2, "Symbolic defense of liberty passed down through ancestral lineages."),
    ("jamb_lit_2012_24", "Literature in English", "Poetry - Give Me The Minstrel's Seat", "2012", "Give Me The Minstrel's Seat ends on a clarion call for", "freedom", "peace and moral rectitude", "wealth", "war", 1, "Urges societal return to upright ethics and harmonious coexistence."),
    ("jamb_lit_2012_25", "Literature in English", "Poetry - To His Coy Mistress", "2012", "'...the youthful hue / Sits on thy skin like a morning dew' is an example of", "simile", "anaphora", "paradox", "onomatopoeia", 0, "Explicit simile comparing blooming youthful glow to morning dew."),
    ("jamb_lit_2012_26", "Literature in English", "Poetry - Bat", "2012", "In Lawrence's Bat, the poet contrasts bats with", "sparrows", "swans", "swallows", "crows", 2, "Contrasts the graceful daytime swallows with sinister, nocturnal bats."),
    ("jamb_lit_2012_27", "Literature in English", "Poetry - Journey of the Magi", "2012", "T.S. Eliot's The Journey of the Magi examines the hardship of", "physical journey", "spiritual rebirth and conversion", "empty wine-skins", "political rebellion", 1, "The spiritual birth of Christ brings painful death to the old pagan world order."),
    ("jamb_lit_2012_28", "Literature in English", "Poetry - In the Navel of the Soul", "2012", "'We would be believing we dreamt it' features the device of", "apostrophe", "assonance / alliteration", "antithesis", "hyperbole", 1, "Repetition of initial consonant 'b' sounds (alliteration)."),
    ("jamb_lit_2012_29", "Literature in English", "Poetry - End of the War", "2012", "The primary casualties highlighted in Launko's End of the War are", "women and children", "soldiers", "politicians", "praise singers", 0, "Innocent women and children bear the brunt of ongoing post-conflict trauma."),
    ("jamb_lit_2012_30", "Literature in English", "Poetry - Sonnet VII", "2012", "The theme of Wendy Cope's Sonnet VII explores the", "craft and pretensions of poetry", "adventure", "contempt for books", "loneliness", 0, "Satirizes academic pomposity surrounding classical sonnet composition."),
    ("jamb_lit_2012_31", "Literature in English", "Literary Principles", "2012", "A literary work in which characters and events represent abstract ideas is an", "characterization", "allegory", "metaphor", "parallelism", 1, "An allegory conveys symbolic moral, spiritual, or political truths beneath literal narrative."),
    ("jamb_lit_2012_32", "Literature in English", "Literary Principles", "2012", "Characterization in a novel refers to the", "writer's biography", "technique of portraying and developing characters", "plot timeline", "moral summary", 1, "The artistic creation and development of fictional personalities."),
    ("jamb_lit_2012_33", "Literature in English", "Literary Principles", "2012", "In literature, verbal irony occurs when", "a speaker says the exact opposite of what they mean", "characters act against fate", "a dilemma occurs", "an actor shouts on stage", 0, "Sarcastic or intentional understatement stating the reverse of literal intent."),
    ("jamb_lit_2012_34", "Literature in English", "Literary Principles", "2012", "Words spoken by an actor on stage intended for audience hearing only is an", "aside", "soliloquy", "acoustic", "tone", 0, "An aside is addressed directly to the audience while other characters remain unaware."),
    ("jamb_lit_2012_35", "Literature in English", "Literary Principles", "2012", "Drama is the representation of actions through", "movement and stage dialogue", "prose descriptions", "written memoirs", "choral chants only", 0, "Performance art utilizing embodied movement, dialogue, and theatrical gesture."),
    ("jamb_lit_2012_36", "Literature in English", "Literary Principles", "2012", "A poet's regular pattern of stressed and unstressed syllables is known as", "allegory", "assonance", "metre", "onomatopoeia", 2, "Metre dictates rhythmic cadence in formal verse."),
    ("jamb_lit_2012_37", "Literature in English", "Literary Principles", "2012", "A literary genre that directly imitates human speech and action on stage is", "drama", "comedy", "prose", "poetry", 0, "Drama is inherently mimetic and performance-based."),
    ("jamb_lit_2012_38", "Literature in English", "Literary Principles", "2012", "A fable is a short fictional tale in which", "allegations are made", "animals or inanimate objects act as characters with moral lessons", "historical kings rule", "rhyming stanzas occur", 1, "Anthropomorphic animal stories delivering universal moral truths (e.g. Aesop)."),
    ("jamb_lit_2012_39", "Literature in English", "Literary Principles", "2012", "Juxtaposing two contrasting ideas in close proximity in poetry is", "euphemism", "synecdoche", "antithesis / oxymoron", "catharsis", 2, "Antithesis places opposing concepts in balanced grammatical contrast."),
    ("jamb_lit_2012_40", "Literature in English", "Literary Principles", "2012", "The main objective of caricature is to", "describe beauty", "expose reality", "emphasize facts", "ridicule through comic exaggeration", 3, "Gross distortion of physical or personality traits for satirical comedy."),
    ("jamb_lit_2012_41", "Literature in English", "Literary Appreciation", "2012", "'O! Ceremony, show me but thy worth What is thy soul of adoration' is an example of", "antithesis", "invocation", "personification", "apostrophe", 3, "Directly addressing the abstract concept of 'Ceremony' constitutes apostrophe."),
    ("jamb_lit_2012_42", "Literature in English", "Vanity - Birago Diop", "2012", "'What eyes will watch our large mouths, Shaped by the laughter of big children...' Tone is", "sarcasm and mournful reproach", "sacrilege", "chiasmus", "eulogy", 0, "Reproaches modern Africans for neglecting the wisdom of their ancestors."),
    ("jamb_lit_2012_43", "Literature in English", "Literary Appreciation", "2012", "'The old man slept in his favourite chair The wind ran its fingers through his hair...' Rhyme scheme is", "bbaa", "aabb", "abab", "baba", 1, "chair/hair (a), sap/lap (b) => aabb."),
    ("jamb_lit_2012_44", "Literature in English", "Ulysses - Alfred Lord Tennyson", "2012", "'Unequal laws unto a savage race, That hoard, and sleep, and feed...' reveals speaker", "desires heroic travel over domestic governance", "detects discrimination", "hates his wife", "loves city life", 0, "Ulysses expresses restless dissatisfaction with idle court life in Ithaca."),
    ("jamb_lit_2012_45", "Literature in English", "The Beautyful Ones Are Not Yet Born - Ayi Kwei Armah", "2012", "'How can I look at Oyo and say I hate long shiny cars? How can I despise international schools?' feeling conveyed is", "alienation and moral torment", "anger", "hope", "despair", 0, "The protagonist suffers agonizing self-doubt under societal pressure to engage in graft."),
    ("jamb_lit_2012_46", "Literature in English", "Night - Wole Soyinka", "2012", "'Hide me now, when night children haunt the earth' Night children evokes", "birds", "spirits and mystical darkness", "armed robbers", "animals", 1, "Reflects Yoruba metaphysical consciousness of supernatural night forces."),
    ("jamb_lit_2012_47", "Literature in English", "Night - Wole Soyinka", "2012", "'Serrated shadows, through dark leaves... Sensation pained me, faceless, silent as night thieves' mood is", "apprehension and eerie dread", "defiance", "joy", "indifference", 0, "Atmosphere of suspense, vulnerability, and creeping apprehension."),
    ("jamb_lit_2012_48", "Literature in English", "Casualties - J.P. Clark", "2012", "'The drums overwhelmed the guns...' uses the literary device of", "litotes", "symbolism", "onomatopoeia", "alliteration", 1, "Drums and guns symbolize the cultural heartbeat and violence of civil war."),
    ("jamb_lit_2012_49", "Literature in English", "Casualties - J.P. Clark", "2012", "'They do not see the funeral piles At home eating up the forests...' imagery is achieved through", "metaphor and personification", "synecdoche", "metonymy", "hyperbole", 0, "Funeral piles described as voracious monsters consuming the forest."),
    ("jamb_lit_2012_50", "Literature in English", "Ulysses - Alfred Lord Tennyson", "2012", "'I cannot rest from travel: I will drink life to the lees... greatly have suffered' informs reader poet", "is determined to experience life to the fullest", "is ready to die", "will cure his mood", "will not travel", 0, "Unquenchable thirst for exploration, adventure, and boundless experience.")
]
lit_all.extend(l2012)

print(f"Total Literature questions through 2012: {len(lit_all)}")
