# coding=utf-8
import os, sys

out_path = "app/src/main/java/com/example/data/repository/JambGovernment2010to2018CompleteOfficialBank.kt"

def esc(text):
    if not text:
        return ""
    return str(text).replace('\\', '\\\\').replace('"', '\\"').replace('$', '\\$').replace('\n', '\\n')

def append_questions(questions):
    lines = []
    for q in questions:
        qid, qtext, a, b, c, d, ans, exp, topic, yr = q
        code = f"""
        list.add(
            QuestionEntity(
                id = "{esc(qid)}",
                subject = "Government",
                topic = "{esc(topic)}",
                year = "{esc(yr)}",
                questionText = "{esc(qtext)}",
                optionA = "{esc(a)}",
                optionB = "{esc(b)}",
                optionC = "{esc(c)}",
                optionD = "{esc(d)}",
                correctAnswerIndex = {ans},
                explanation = "{esc(exp)}",
                imageUrl = null,
                originType = "JAMB_ORIGINAL",
                originLabel = "JAMB Government {esc(yr)}",
                isVerifiedJamb = true
            )
        )"""
        lines.append(code)
    with open(out_path, "a", encoding="utf-8") as f:
        f.write("".join(lines))
    print(f"Appended {len(questions)} questions to {out_path}")

# Import 2010 from build_government_complete_2010_2018
sys.path.insert(0, "app/scripts")
from build_government_complete_2010_2018 import g2010

# 2011 Government (50 Qs)
g2011 = [
    ("jamb_gov_2011_01", "Which Government Question Paper Type is given to you?", "Type A", "Type B", "Type C", "Type D", 0, "Paper Type A specified on official examination sheet.", "General Examination Structure", "2011"),
    ("jamb_gov_2011_02", "The development of attitudes and beliefs about a political system is", "political emancipation", "political socialization", "political participation", "political orientation", 3, "Political orientation represents the internalized attitudes, knowledge, and value judgments toward the political realm.", "Political Culture", "2011"),
    ("jamb_gov_2011_03", "Political behavior is governed by", "political socialization", "political ideology", "political economy", "political culture", 1, "Political ideology provides the conceptual framework, values, and guiding norms that govern political conduct.", "Political Ideology", "2011"),
    ("jamb_gov_2011_04", "In a nation, sovereignty is vested in the", "community", "state", "elite", "electorate", 3, "Political sovereignty in a democratic nation-state resides ultimately in the electorate through the ballot box.", "Sovereignty", "2011"),
    ("jamb_gov_2011_05", "Which of the following is a feature of democracy?", "interdependence of states", "state responsibilities to society", "power vested in minority parties", "popular consultation", 1, "State responsiveness and institutional responsibility to societal welfare is a cornerstone of democratic governance.", "Democracy", "2011"),
    ("jamb_gov_2011_06", "Private ownership of the means of production is central to", "fascism", "feudalism", "capitalism", "communism", 0, "Private property and market competition constitute the defining core of free-enterprise capitalism.", "Economic Systems", "2011"),
    ("jamb_gov_2011_07", "A system based on hierarchies of land ownership is", "feudalism", "totalitarianism", "communism", "fascism", 2, "Feudalism organizes political power and social relations around land tenure, fiefs, lords, and serfs.", "Feudalism", "2011"),
    ("jamb_gov_2011_08", "Which of the following performs quasi-legislative functions?", "The Judiciary", "The Traditional Institutions", "The Civil Service", "The Executive", 0, "Judicial precedent and case law interpretation serve quasi-legislative functions in clarifying statutory law.", "Organs of Government", "2011"),
    ("jamb_gov_2011_09", "A major weakness of confederation is", "over-concentration of authority", "tendency towards secession", "lack of local independence", "lack of common currency", 3, "Confederations are inherently fragile because member states retain autonomous sovereignty, encouraging secession.", "Systems of Government", "2011"),
    ("jamb_gov_2011_10", "Members of a parliament are required to report the proceedings of the house to their", "constituencies", "local government chairmen", "traditional rulers", "political parties", 2, "Elected parliamentarians are constitutionally accountable to the voters in their electoral constituencies.", "Legislature", "2011"),
    ("jamb_gov_2011_11", "Which of the following Country is a unitary state?", "Nigeria", "India", "United States of America", "Ghana", 1, "Ghana operates a unitary constitutional framework where central government retains undivided legislative authority.", "Unitary System", "2011"),
    ("jamb_gov_2011_12", "Ending a session of parliament by royal proclamation means the", "expiration of parliament", "prorogation of parliament", "adjournment of parliament", "dissolution of parliament", 2, "Prorogation formally terminates a parliamentary session without calling a general election.", "Legislative Procedure", "2011"),
    ("jamb_gov_2011_13", "A main feature of the parliamentary system is that", "the executive consists of all party members", "judges are drawn from the ruling party", "electoral commissioners leave at the end of their tenure", "the executive is appointed by the legislature", 1, "In Westminster parliamentary systems, the executive cabinet is drawn directly from and is answerable to parliament.", "Parliamentary System", "2011"),
    ("jamb_gov_2011_14", "In a socialist economy, private accumulation of wealth is", "prohibited", "regulated", "limited", "encouraged", 2, "Socialism strictly restricts or limits private capital accumulation to prevent class exploitation.", "Socialism", "2011"),
    ("jamb_gov_2011_15", "The earliest classification of constitutions was the work of", "Aristotle", "J.J. Rousseau", "K.C. Wheare", "Plato", 0, "Aristotle analyzed and categorized 158 Greek city-state constitutions into monarchies, aristocracies, and polities.", "Constitutional Classification", "2011"),
    ("jamb_gov_2011_16", "Constitutionalism refers to", "the process of drafting a constitution", "amendment of an existing constitution", "the process of operating a constitution", "strict adherence to a constitution", 1, "Constitutionalism embodies adherence to the rule of law and strict limitation of governmental powers by constitutional rules.", "Constitutionalism", "2011"),
    ("jamb_gov_2011_17", "An advantage of delegated legislation is that", "much time is saved in the process", "technical issues are handled by experts", "ministers and lawmakers work together", "it hastens the implementation of policy", 2, "Administrative agencies and technical experts can rapidly formulate specialized operational rules without burdening parliament.", "Delegated Legislation", "2011"),
    ("jamb_gov_2011_18", "One essential duty of a citizen to his state is to", "support the government in power", "recite the pledge", "pay his tax", "encourage other citizens", 0, "Prompt payment of taxes and rates is a mandatory civic obligation enabling public services.", "Duties of Citizens", "2011"),
    ("jamb_gov_2011_19", "Franchise in an electoral process means the", "right to vote", "ownership of means of production", "the sovereignty of a nation", "rights and duties of a citizen", 2, "Franchise (suffrage) denotes the constitutional right to vote and participate in elections.", "Electoral Process", "2011"),
    ("jamb_gov_2011_20", "The type of party system in practice is defined by the", "relationship between the parties and electorate", "structure of the political parties", "manner in which the parties operate", "number of political parties in a country", 1, "Party systems are conventionally classified as one-party, two-party, or multi-party based on party count and competitiveness.", "Party Systems", "2011"),
    ("jamb_gov_2011_21", "Pressure groups harmonize different individual concerns through", "interest formulation", "interest manipulation", "interest mobilisation", "interest aggregation", 0, "Interest aggregation combines multiple individual preferences into consolidated policy demands.", "Pressure Groups", "2011"),
    ("jamb_gov_2011_22", "Opinion polls are organized to find out the", "benefits derived by people from government", "people's thought about a particular government policy", "people's expectations from the government", "feelings of people about particular issues and policies", 1, "Polling surveys systematically measure the public's sentiments, attitudes, and approval of state policies.", "Public Opinion", "2011"),
    ("jamb_gov_2011_23", "In pre-colonial Igboland, autocratic rule was made difficult by the", "fear of dethronement", "absence of a centralized system of authority", "pressure from age grades", "activities of cult societies", 3, "Egalitarian republicanism and decentralized family/village assemblies prevented despotic dictatorship in traditional Igboland.", "Pre-Colonial Administration", "2011"),
    ("jamb_gov_2011_24", "The Yoruba traditional system of government was", "republican", "democratic", "monarchical", "egalitarian", 0, "Pre-colonial Yoruba states were constitutional monarchies featuring the Oba and advisory checks by the council of chiefs.", "Pre-Colonial Administration", "2011"),
    ("jamb_gov_2011_25", "Under the pre-colonial Sokoto Caliphate system, the next in command to the sultan was the", "Alkali", "Galadima", "Madaki", "Waziri", 1, "The Waziri (grand vizier) acted as prime minister, chief administrative officer, and second-in-command to the Sultan.", "Pre-Colonial Administration", "2011"),
    ("jamb_gov_2011_26", "Which of the following societies was classified as acephalous?", "Benin", "Ibibio", "Igbo", "Ijaw", 0, "Acephalous (stateless) societies like the traditional Igbo lacked a centralized monarchical head of state.", "Pre-Colonial Administration", "2011"),
    ("jamb_gov_2011_27", "Indirect rule encouraged", "communal integration", "exploitation and oppression", "inter-communal cooperation", "the rise of nationalism", 3, "Colonial discrimination, taxation, and autocratic native authorities sparked unified anti-colonial nationalist agitation.", "Colonial Administration", "2011"),
    ("jamb_gov_2011_28", "The main achievement of the nationalists in Nigeria was", "registration of political parties", "economic liberation of the nation", "political liberation of the nation", "building the nation", 0, "Nationalist struggles successfully brought about decolonization, political sovereignty, and national independence in 1960.", "Nationalism", "2011"),
    ("jamb_gov_2011_29", "The major external factor that promoted nationalism in Nigeria was", "Pan-Africanism", "the Yom-Kippur War", "the Second World War", "Anti-apartheid Movement", 2, "WWII demystified European superiority, as returning Nigerian servicemen demanded democratic freedoms and equality.", "Nationalism", "2011"),
    ("jamb_gov_2011_30", "The presidential system of government was introduced in Nigeria with the Constitution of", "1989", "1999", "1960", "1979", 1, "The 1979 Constitution introduced an American-style Executive Presidential system, replacing the Westminster model.", "Constitutional History", "2011"),
    ("jamb_gov_2011_31", "The Action Group crisis of 1963 led to the formation of", "UPP", "NEPU", "NPC", "NCNC", 2, "Chief S.L. Akintola's faction broke away from Awolowo's Action Group to establish the United People's Party (UPP).", "Political Crises in Nigeria", "2011"),
    ("jamb_gov_2011_32", "Under the 1963 Republican Constitution, the power of judicial review was vested in the", "President", "Chief Justice", "Supreme Court", "Parliament", 0, "The 1963 Constitution made the Supreme Court of Nigeria the final apex appellate court endowed with judicial review.", "Constitutional History", "2011"),
    ("jamb_gov_2011_33", "The rules and regulations of the civil service are called", "General Order", "Bureaucratic Order", "Service Order", "Administrative Order", 2, "The Public Service Rules (formerly known as General Orders or G.O.) regulate civil service administration.", "Civil Service", "2011"),
    ("jamb_gov_2011_34", "The Code of Conduct Bureau was essentially established to", "reduce corruption in public life", "protect the rights of public servants", "enhance probity and accountability in public service", "ensure the independence of the public service", 0, "The Code of Conduct Bureau enforces transparency, asset declaration, and ethical accountability among public officials.", "Public Accountability", "2011"),
    ("jamb_gov_2011_35", "Which of the following political parties was the first to be formed when the ban on politics was lifted in 1978?", "NPP", "PRP", "NPN", "UPN", 0, "Chief Obafemi Awolowo announced the formation of the Unity Party of Nigeria (UPN) immediately following the lifting of the political ban.", "Party History", "2011"),
    ("jamb_gov_2011_36", "The principle of federal character was adopted in order to promote equitable allocation of", "positions and appointments among people of various regions", "appointments between the North and the South", "opportunities between the males and females", "revenue between groups in the country", 2, "Federal character ensures equitable representation of diverse ethnic and regional communities in public institutions.", "Nigerian Federalism", "2011"),
    ("jamb_gov_2011_37", "The component units of the Nigerian Federation comprise", "national assembly, military, police and civil service", "constituency, ward, emirate and chiefdom", "federal, state, local government and federal capital territory", "federal capital territory, national assembly, supreme court and civil service", 0, "Nigerian federation is composed of 36 states, 774 local governments, and the Federal Capital Territory under federal coordination.", "Nigerian Federalism", "2011"),
    ("jamb_gov_2011_38", "In Nigeria, privatization and commercialization policies were introduced to", "hand over the control of commercial ventures to citizens", "increase the asset base of government", "divest government major control of commercial ventures", "allow government control of the private sector", 0, "Privatization transfers state-owned enterprise ownership to private investors to curb waste and boost efficiency.", "Economic Reforms", "2011"),
    ("jamb_gov_2011_39", "An example of a public corporation in Nigeria is", "National Universities Commission", "Nigerian Television Authority", "National Population Commission", "First Bank of Nigeria", 3, "The Nigerian Television Authority (NTA) is a statutory broadcasting corporation delivering public media services.", "Public Corporations", "2011"),
    ("jamb_gov_2011_40", "Following the reform of the Native Authority system in Northern Nigeria, traditional rulers became", "Council", "Chief-and-Council", "Prefects", "Chief-in-Council", 1, "The reforms transitioned northern traditional rulers into advisory Chief-and-Council configurations.", "Local Government History", "2011"),
    ("jamb_gov_2011_41", "Under whose regime were Akwa-Ibom and Katsina States created?", "Gen Murtala Muhammed", "Gen Ibrahim Babangida", "Gen Sani Abacha", "Gen Yakubu Gowon", 3, "General Ibrahim Babangida created Katsina and Akwa Ibom States on September 23, 1987.", "State Creation", "2011"),
    ("jamb_gov_2011_42", "Under the 1999 Constitutions of the Federal Republic of Nigeria, the appointment and posting of members of election tribunal on the elections conducted by INEC is the responsibility of the", "Chairman, Independent National Electoral Commission", "President of Nigeria", "Chief Justice of Nigeria", "President, Court of Appeal", 3, "The President of the Court of Appeal possesses constitutional authority to constitute and post election petition tribunal judges.", "Judiciary", "2011"),
    ("jamb_gov_2011_43", "Rhodesia was the former name of", "Zimbabwe", "Swaziland", "Zambia", "Namibia", 2, "Southern Rhodesia attained sovereign independence in 1980 and was renamed Zimbabwe.", "African Politics", "2011"),
    ("jamb_gov_2011_44", "The adoption of non-alignment as a principle of Nigeria's foreign policy was aimed at", "promoting Nigeria's leadership aspiration in Africa", "attaining equal status with the world powers", "fulfilling a basic requirement for acceptance in the UN Security Council", "insulating Nigeria against having to take side in the Cold War", 1, "Non-alignment shielded Nigeria from Cold War ideological entanglement between the Western and Eastern power blocs.", "Foreign Policy", "2011"),
    ("jamb_gov_2011_45", "In 1979, the non-aligned member states were", "21", "27", "37", "19", 0, "The Havana NAM Summit of 1979 expanded active developing-world membership.", "Non-Aligned Movement", "2011"),
    ("jamb_gov_2011_46", "Which of the following was the secretary general of OPEC?", "Jibril Aminu", "Aret Adams", "Dalhatu Bayero", "Rilwan Lukwan", 1, "Alhaji Dr. Rilwanu Lukman served with great distinction as Secretary-General and Conference President of OPEC.", "OPEC", "2011"),
    ("jamb_gov_2011_47", "Which of the following countries pioneered the idea of ECOWAS alongside Nigeria?", "Liberia", "Togo", "Cote d'Ivoire", "Mali", 3, "General Yakubu Gowon of Nigeria and President Gnassingbé Eyadéma of Togo spearheaded the diplomatic creation of ECOWAS.", "ECOWAS", "2011"),
    ("jamb_gov_2011_48", "Which of the following international organizations were in existence before the Second World War?", "The UNO", "The OAU", "The League of Nations", "The ECOWAS", 0, "The League of Nations was founded in 1919 after WWI and preceded the United Nations.", "International Organizations", "2011"),
    ("jamb_gov_2011_49", "The organ of the United Nations responsible for the approval of its annual budget is the", "Secretariat", "Security Council", "General Assembly", "Economic and Social Council", 0, "Article 17 of the UN Charter confers exclusive budget review and approval power on the General Assembly.", "United Nations", "2011"),
    ("jamb_gov_2011_50", "Each member state is represented on the Board of Governors of OPEC for a period of", "2 years", "3 years", "4 years", "1 year", 2, "OPEC member states nominate representatives to the OPEC Board of Governors for two-year terms.", "OPEC", "2011")
]

# 2012 Government (50 Qs)
g2012 = [
    ("jamb_gov_2012_01", "Which Questions Paper Type of Government as indicated above is given to you?", "Type Green", "Type Purple", "Type Red", "Type Yellow", 2, "Paper Type Red allocated for examination evaluation.", "General Examination Structure", "2012"),
    ("jamb_gov_2012_02", "The distinctive attribute of a state is the monopoly of", "control", "power", "violence", "justice", 1, "Max Weber defined the state as an entity possessing a monopoly on the legitimate use of physical force and power.", "The State", "2012"),
    ("jamb_gov_2012_03", "State as a political entity refers to", "An organized group within a definite territory", "An association of men in a given society", "A branch of a nation", "A geographical location", 0, "A state is an organized political community occupying a definite sovereign territory with an established government.", "The State", "2012"),
    ("jamb_gov_2012_04", "Political values are acquired in any given society through", "political re-orientation", "political campaign", "political socialization", "political indoctrination", 2, "Political socialization is the lifelong developmental process through which citizens internalize political norms and values.", "Political Socialization", "2012"),
    ("jamb_gov_2012_05", "In a democratic government, political sovereignty is vested in the", "legislature", "elite", "executive", "electorate", 3, "Ultimate political sovereignty belongs to the citizenry (electorate) through the democratic electoral mandate.", "Sovereignty", "2012"),
    ("jamb_gov_2012_06", "One judicial function performed by the executive is", "Granting of amnesty", "Implementing judicial orders", "Ensuring obedience to the law", "Appointing judges", 2, "The prerogative of mercy (pardons and amnesty) is an executive function of quasi-judicial character.", "Executive Organ", "2012"),
    ("jamb_gov_2012_07", "A governmental system in which constitutional supremacy resides in the center is", "federal", "confederal", "unitary", "parliamentary", 0, "In a unitary system, all constitutional and sovereign legislative authority is concentrated in the central government.", "Unitary System", "2012"),
    ("jamb_gov_2012_08", "A political system which empowers the leader with the ultimate responsibility to execute laws is", "parliamentarianism", "presidentialism", "dictatorship", "autocracy", 3, "Presidentialism concentrates unified executive authority in a single elected president.", "Presidential System", "2012"),
    ("jamb_gov_2012_09", "A bill is a draft which is awaiting the consideration of the", "executive", "party caucus", "legislature", "judiciary", 2, "A bill is a proposed legislative enactment submitted to parliament for deliberation, readings, and passage.", "Legislative Process", "2012"),
    ("jamb_gov_2012_10", "The private ownership of the means of production is a feature of", "capitalism", "socialism", "communalism", "communism", 0, "Capitalism relies fundamentally upon private property, free enterprise, and market-driven production.", "Capitalism", "2012"),
    ("jamb_gov_2012_11", "In a feudal system, the two major classes are the serfs and the", "masses", "vassals", "lords", "elite", 2, "Feudal agrarian hierarchy divided society primarily into landholding lords and subjugated tenant serfs.", "Feudalism", "2012"),
    ("jamb_gov_2012_12", "An example of a country with a flexible constitution is", "South Africa", "Britain", "Benin Republic", "the United States of America", 1, "The unwritten British constitution can be amended through ordinary parliamentary statutes without complex referendum hurdles.", "Constitutional Types", "2012"),
    ("jamb_gov_2012_13", "The rule of law is negation of", "equality before the law", "supremacy of the law", "Limited power", "absolute power", 3, "The Rule of Law directly negates arbitrary autocracy, despotism, and unchecked governmental absolute power.", "Rule of Law", "2012"),
    ("jamb_gov_2012_14", "To ensure the rights and freedom of citizens, the powers of the arms of government must be", "fused", "incorporated", "separated", "rotated", 2, "Montesquieu demonstrated that dividing legislative, executive, and judicial powers prevents despotic tyranny.", "Separation of Powers", "2012"),
    ("jamb_gov_2012_15", "Delegated legislation is made by bodies others than the", "president", "governor", "parliament", "judiciary", 0, "Delegated legislation is promulgated by executive or administrative agencies acting under powers delegated by parliament.", "Delegated Legislation", "2012"),
    ("jamb_gov_2012_16", "The bringing of a session of a parliament to an end through royal proclamation is known as", "political impasse", "dissolution of parliament", "vote of no confidence", "prorogation of parliament", 1, "Dissolution officially brings a parliament to an end and triggers a general election.", "Legislature", "2012"),
    ("jamb_gov_2012_17", "The right of citizens to participate in the affairs of government of their country is called", "economic right", "civil right", "political right", "social right", 2, "Political rights encompass voting, contesting public office, and participating in public administration.", "Citizenship and Rights", "2012"),
    ("jamb_gov_2012_18", "The commission charged with the conduct of federal elections in Nigeria is", "NEC", "FEDECO", "INEC", "NECON", 2, "The Independent National Electoral Commission (INEC) manages national and state elections in Nigeria.", "Electoral Commissions", "2012"),
    ("jamb_gov_2012_19", "An electoral system in which parties are assigned seats in the parliament commensurate to the number of votes polled is", "Absolute majority", "Simple majority", "proportional representation", "indirect election", 2, "Proportional representation allocates parliamentary seats in direct proportion to the percentage of popular votes received.", "Electoral Systems", "2012"),
    ("jamb_gov_2012_20", "An intra-party activity for the selection of candidates for elective positions known as", "primary election", "general election", "mid-term election", "bye-election", 0, "Primaries allow enrolled party electors or delegates to pick official party flagbearers.", "Party Politics", "2012"),
    ("jamb_gov_2012_21", "The primary aim of pressure groups is to", "Attract people's attention", "protects the interest of members", "captured political power", "fight corrupt officials", 1, "Pressure groups organize to promote and protect the common occupational or social interests of their members.", "Pressure Groups", "2012"),
    ("jamb_gov_2012_22", "Which of the following is used in gauging public opinion?", "constitution", "educational institution", "mass media", "electoral college", 2, "Radio, newspapers, television, and social media act as barometers measuring and reflecting citizen public opinion.", "Public Opinion", "2012"),
    ("jamb_gov_2012_23", "A permanent structure that facilitates continuity and guarantees orderly conduct in governance is", "Bureaucracy", "public corporation", "ombudsman", "political party", 0, "The civil service bureaucracy maintains administrative stability and state continuity across changing political regimes.", "Civil Service", "2012"),
    ("jamb_gov_2012_24", "In the Hausa pre-colonial political system, a district was headed by", "A hakimi", "a dagaci", "an alkali", "a waziri", 0, "Hakimi was the title of the district head overseeing subordinate village heads (Dagaci) in the emirate system.", "Pre-Colonial Administration", "2012"),
    ("jamb_gov_2012_25", "Which of the following ensured the practice of democracy in the pre-colonial Yoruba political system?", "Checks and balances", "Fusion of power", "individual responsibility", "the rule of law", 0, "The Oyo Mesi and Ogboni cult balanced the monarchical powers of the Alaafin to prevent tyrannical rule.", "Pre-Colonial Administration", "2012"),
    ("jamb_gov_2012_26", "Colonization of Africa was mainly motivated by", "security considerations", "economic reasons", "religious reasons", "cultural factors", 1, "The industrial revolution drove European colonial powers to seek raw materials and captive consumer markets across Africa.", "Colonialism", "2012"),
    ("jamb_gov_2012_27", "The French colonial system was underlined by the policy of", "assimilation", "paternalism", "socialism", "indirect rule", 0, "The French colonial doctrine of assimilation sought to integrate colonized peoples into French cultural and political life.", "Colonial Administration", "2012"),
    ("jamb_gov_2012_28", "Radical nationalism in Nigeria is generally attributed to the influence of", "Aminu Kano", "Herbert Macaulay", "Nnamdi Azikiwe", "Mbonu Ojike", 2, "Dr. Nnamdi Azikiwe pioneered radical militant nationalism through his West African Pilot and the Zikist Movement.", "Nationalism", "2012"),
    ("jamb_gov_2012_29", "Two foreigners that directly aroused nationalist feelings among Nigerians are", "Edward Blyden and Payne Jackson", "Casely Hayford and James Horton", "W.E du Bois and H.O Davies", "Marcus Garvey and Casely Hayford", 2, "W.E.B. Du Bois and international Pan-African leaders inspired early West African nationalist activists.", "Nationalism", "2012"),
    ("jamb_gov_2012_30", "Members of the Senate in Nigeria's First Republic were", "Elected directly by the people", "Elected by electoral college", "Nominated by regional and federal governments", "Nominated by the president of the house", 2, "In the 1960 and 1963 constitutions, senators were selected and nominated by the regional executive governments.", "First Republic", "2012"),
    ("jamb_gov_2012_31", "In Nigeria, the agency mainly responsible for the maintenance of internal peace and security is the", "Army", "Navy", "Civil Defence Corps", "Police", 3, "The Nigeria Police Force is the primary constitutional security agency charged with maintaining internal law and order.", "Law Enforcement", "2012"),
    ("jamb_gov_2012_32", "The National Assembly in Nigeria is primarily responsible for", "Executing laws", "interpreting laws", "Ratifying appointments", "Making laws", 3, "Section 4 of the 1999 Constitution vests the supreme federal law-making power in the National Assembly.", "Legislature", "2012"),
    ("jamb_gov_2012_33", "The major factor militating against the efficient operation of electoral commissions in Nigeria is", "Inadequate public support", "Population size", "Inadequate skilled manpower", "Excessive political interference", 3, "Partisan executive interference and inadequate fiscal autonomy have historically compromised electoral commission impartiality.", "Electoral Process", "2012"),
    ("jamb_gov_2012_34", "A major objective of the Public Complaints Commission is", "Training and promotion of public servants", "Settlement of disputes among individuals", "Addressing the grievances of individuals and groups", "Fighting corruption and indiscipline", 2, "The Ombudsman investigates administrative injustice, maladministration, and bureaucratic abuse of citizen rights.", "Ombudsman", "2012"),
    ("jamb_gov_2012_35", "The three registered political parties at the inception of Nigeria's Fourth Republic were", "PDP, DPP and PPA", "PDP, AD and APP", "PDP, AD and PPA", "PDP, APP and AC", 1, "The Peoples Democratic Party (PDP), Alliance for Democracy (AD), and All Peoples Party (APP) contested the 1999 transition.", "Party Politics", "2012"),
    ("jamb_gov_2012_36", "The Sharia legal system was first introduced in the Fourth Republic in", "Kano State", "Katsina State", "Zamfara State", "Sokoto State", 2, "Governor Ahmad Sani Yerima of Zamfara State signed comprehensive Sharia penal legislation into law in October 1999.", "Legal History", "2012"),
    ("jamb_gov_2012_37", "Quota system and federal character principles were entrenched in the 1979 constitution to ensure", "loyalty", "Economic empowerment", "Equity", "Even development", 2, "The federal character principle was institutionalized to ensure equity, inclusion, and national cohesion in public appointments.", "Nigerian Federalism", "2012"),
    ("jamb_gov_2012_38", "Workers in the public corporations are known as", "civil servants", "private employees", "public servants", "professional employees", 2, "Employees of statutory corporations, parastatals, and military forces are legally categorized as public servants.", "Public Administration", "2012"),
    ("jamb_gov_2012_39", "The central objective of privatization in Nigeria is to", "Reduce the retrenchment of workers", "Encourage prompt payment of salaries", "Improve standard of living", "Improve the efficiency of enterprises", 3, "Privatization seeks to eliminate state subsidies, attract capital, and boost productivity in commercially viable enterprises.", "Economic Policy", "2012"),
    ("jamb_gov_2012_40", "Military intervention in Nigeria arose from", "perceived incapability of civilians to govern", "international pressure for change", "the desire for a military government", "civilian's desire to relinquish power", 0, "Electoral violence, corruption, census controversies, and governance breakdowns provoked the January 1966 coup.", "Military Rule", "2012"),
    ("jamb_gov_2012_41", "The first institution introduced by the military to exercise legislative power was the", "supreme military council", "armed forces ruling council", "federal executive council", "provisional ruling council", 0, "The Supreme Military Council (SMC) was established in 1966 as the highest legislative decree-making organ.", "Military Rule", "2012"),
    ("jamb_gov_2012_42", "The main focus of Nigeria's foreign policy since independence centers on", "South-south cooperation", "Sub-regionalism", "Globalism", "Afrocentrism", 3, "Africa as the center-piece of foreign policy dictates prioritizing African liberation, peace, and economic integration.", "Foreign Policy", "2012"),
    ("jamb_gov_2012_43", "The country that championed decolonization in Africa was", "Nigeria", "South Africa", "Ghana", "Kenya", 2, "Kwame Nkrumah's Ghana championed African emancipation under the banner 'Ghana is not free until all Africa is free'.", "Decolonization", "2012"),
    ("jamb_gov_2012_44", "A major drawback to the NEPAD initiative is its", "Articulation by few African leaders", "Affiliation by few African union", "Inability to empower the youth", "Reliance on Western donors for funds", 3, "Excessive financial dependence on G8 and Western donor capital compromised NEPAD's autonomous African developmental agenda.", "African Union & NEPAD", "2012"),
    ("jamb_gov_2012_45", "The structures of the African Union include", "the court of justice, pan African congress and people's Assembly", "pan African parliament, the court of justice and the peace and security council", "specialized Technical commission, the court of justice and humanitarian board", "people's Assembly, Humanitarian Board and the peace and security council", 1, "The AU institutional framework incorporates the Pan-African Parliament, Court of Justice, and Peace and Security Council.", "African Union", "2012"),
    ("jamb_gov_2012_46", "ECOMOG at the initial stage of its intervention in Liberia was perceived as", "Neutral", "Incompetent", "Partisan", "Invaders", 0, "ECOMOG deployed as a neutral regional peacekeeping force to halt factional bloodshed and protect innocent civilians.", "ECOWAS & ECOMOG", "2012"),
    ("jamb_gov_2012_47", "One of the programmes binding members of the Commonwealth is the", "Food and aid programme", "Cultural programme", "Agenda for peace", "Scholarship scheme", 0, "The Commonwealth Scholarship and Fellowship Plan provides educational and technical exchange across member nations.", "Commonwealth", "2012"),
    ("jamb_gov_2012_48", "The African leader mostly credited for spearheading the formation of the African Union is", "Muammar Ghaddafi", "Abdelaziz Bouteflika", "Abdoulaye Wade", "Thabo Mbeki", 2, "Colonel Muammar Gaddafi championed the 1999 Sirte Declaration transforming the OAU into the African Union.", "African Union", "2012"),
    ("jamb_gov_2012_49", "As part of the reforms in the UN, two slots were proposed in the Security Council for", "Asia", "Africa", "America", "Europe", 1, "The Ezulwini Consensus articulated Africa's demand for two permanent and five non-permanent UN Security Council seats.", "United Nations", "2012"),
    ("jamb_gov_2012_50", "The founding members of OPEC are", "Algeria, Iran, Iraq, Saudi Arabia and Kuwait", "Nigeria, Libya, Iraq and Saudi Arabia", "Venezuela, Nigeria, Libya, Iran and Iraq", "Saudi Arabia, Iran, Iraq, Kuwait and Venezuela", 3, "The Baghdad Conference of 1960 was founded by Iran, Iraq, Kuwait, Saudi Arabia, and Venezuela.", "OPEC", "2012")
]

append_questions(g2010)
append_questions(g2011)
append_questions(g2012)
print("Part 1 complete.")
