# coding=utf-8
import os, sys
from gov_data_part1 import append_questions, out_path

# 2016 Government (50 Qs)
g2016 = [
    ("jamb_gov_2016_01", "Citizenship is acquired by an alien through", "registration", "birth", "naturalization", "conferment", 2, "An alien legally resident in a country acquires nationality by naturalization.", "Citizenship", "2016"),
    ("jamb_gov_2016_02", "The upper house in most federal systems is created to", "prevent excesses of the executive", "enable experienced elders make inputs to governance", "oversee and check the lower house", "ensure equality of federating units", 3, "Upper chambers (like the Senate) protect equality among federating states irrespective of their population sizes.", "Federalism", "2016"),
    ("jamb_gov_2016_03", "Public Complaints Commission is responsible for", "investigating the use of false document", "entertaining complaints against public servant", "arresting public servant", "sentencing erring public servants", 1, "The Ombudsman investigates administrative abuses, delays, and unfair treatment by public officials.", "Ombudsman", "2016"),
    ("jamb_gov_2016_04", "The earliest nationalist activities in Nigeria were spearheaded by", "trade unions", "educated elites", "political parties", "traditional rulers", 3, "Traditional kings, chiefs, and emirs staged the earliest armed resistance against colonial intrusion.", "Nationalism", "2016"),
    ("jamb_gov_2016_05", "The organ of UN that promotes voluntary co-operation among member states in diverse areas is the", "General Assembly", "International Court of Justice", "Security Council", "Economic and Social Council", 0, "The General Assembly fosters global dialogue and voluntary cooperation across cultural and economic realms.", "United Nations", "2016"),
    ("jamb_gov_2016_06", "The officer responsible for announcing the result of an election is referred to as the", "electoral officer", "presiding officer", "returning officer", "ballot officer", 2, "The Returning Officer collates votes and issues the official certificate of return to the winner.", "Electoral Process", "2016"),
    ("jamb_gov_2016_07", "Under the emirate system, the commander of the army is the", "Sarkin Fada", "Hakimi", "Alkali", "Madawaki", 3, "The Madawaki was the commander-in-chief of the emirate military forces.", "Pre-Colonial Administration", "2016"),
    ("jamb_gov_2016_08", "Which of the following is a feature of checks and balances?", "Code of conduct", "Judicial review", "Judicial immunity", "Judicial precedent", 1, "Judicial review acts as a constitutional check against legislative and executive unconstitutionality.", "Separation of Powers", "2016"),
    ("jamb_gov_2016_09", "Cross-carpeting was first outlawed in which of the following constitutions?", "1963 constitution", "1979 constitution", "1960 constitution", "1999 constitution", 0, "The 1963 Republican Constitution first introduced provisions to penalize regional carpet-crossing.", "Constitutional History", "2016"),
    ("jamb_gov_2016_10", "The performance of ritual rites in the Yoruba empire is the responsibility of the", "Aare-ona Kakanfo", "Oyomesi", "Ogboni", "Oba", 2, "The Ogboni fraternity performed vital ritual sacrifices, judicial arbitrations, and royal burials in Yoruba kingdoms.", "Pre-Colonial Administration", "2016"),
    ("jamb_gov_2016_11", "The development of a classless society is the goal of", "marxism", "feudalism", "liberalism", "conservatism", 0, "Marxism-Leninism pursues the establishment of a classless communist society.", "Political Ideologies", "2016"),
    ("jamb_gov_2016_12", "The indirect rule system of administration was more successful in Northern Nigeria because", "the Europeans ensured that the farmlands of the natives were not confiscated", "of the existence of an organised structure in the area", "the natives showed little or no resistance", "the people were mainly interested in being governed indirectly", 1, "The pre-existing hierarchical Fulani emirate administration provided an efficient structure for colonial indirect rule.", "Colonial Administration", "2016"),
    ("jamb_gov_2016_13", "As an executive, the commissioner is charged with the responsibility of", "writing laws", "implementing laws", "giving loans", "law making", 1, "State commissioners implement executive policies and direct ministerial departments.", "Executive Organ", "2016"),
    ("jamb_gov_2016_14", "A good example of a country that operates a cabinet system of government is", "France", "Cameroun", "Nigeria", "Britain", 3, "Great Britain is the mother of the Westminster cabinet parliamentary system.", "Parliamentary System", "2016"),
    ("jamb_gov_2016_15", "In its bids to reduce regional structural imbalance in the federation, Gowon administration", "formed political parties", "increased allocation", "created states", "appointed ministers", 2, "General Gowon created 12 states in May 1967 to dismantle regional monoliths and pacify minorities.", "Nigerian Federalism", "2016"),
    ("jamb_gov_2016_16", "The administrative head of a public corporation is the", "General Manager", "Permanent Secretary", "Chairman", "Chief Executive", 0, "The General Manager (or Managing Director) directs the routine operational affairs of a public corporation.", "Public Corporations", "2016"),
    ("jamb_gov_2016_17", "Which of these is an attribute of the state?", "Dress mode", "Language", "Religion", "Population", 3, "A permanent population is one of the four essential components of a sovereign state.", "The State", "2016"),
    ("jamb_gov_2016_18", "The utmost goal of nationalism in Africa was", "representation", "independence", "development", "Patriotism", 1, "African nationalism sought total emancipation from foreign imperial domination and sovereign self-rule.", "Nationalism", "2016"),
    ("jamb_gov_2016_19", "The centre piece of Nigeria's foreign policy covers only", "Africa", "Europe", "Asia", "Latin America", 0, "Afrocentrism declares Africa as the foundational centerpiece of Nigeria's external diplomacy.", "Foreign Policy", "2016"),
    ("jamb_gov_2016_20", "A representative of a commonwealth country in another member state is known as", "Consul-General", "High Commissioner", "Attache", "Ambassador", 1, "Commonwealth diplomatic ambassadors are officially titled High Commissioners.", "Diplomacy", "2016"),
    ("jamb_gov_2016_21", "The review of Nigerian foreign policy under the Murtala-Obasanjo regime was done by", "Udoji committee", "Aboyade committee", "Okigbo committee", "Adedeji committee", 0, "The 1975 Committee on Foreign Policy headed by Prof. Adebayo Adedeji reviewed Nigeria's diplomatic objectives.", "Foreign Policy", "2016"),
    ("jamb_gov_2016_22", "Nigeria placed Africa at the centre of her foreign policy because of her", "role in Congo crisis", "size and wealth", "desire to dominate the continent", "potential role in Africa", 3, "Nigeria recognized her demographic and economic capacity to champion continental liberation.", "Foreign Policy", "2016"),
    ("jamb_gov_2016_23", "Rule adjudication is a primary function of the", "judiciary", "legislature", "government", "executive", 0, "The judiciary interprets laws and settles disputes between citizens and the state.", "Judiciary", "2016"),
    ("jamb_gov_2016_24", "Franchise in an electoral process means the", "sovereignty of a nation", "rights and duties of citizens", "ownership of means of production", "right to vote", 3, "Franchise is the constitutional right of qualified citizens to cast ballots in public elections.", "Electoral Process", "2016"),
    ("jamb_gov_2016_25", "Which of these is not a dimension of public opinion?", "Substance", "Intensity", "Orientation", "Polling", 0, "Substance, intensity, and orientation are qualitative aspects, while polling is an instrument.", "Public Opinion", "2016"),
    ("jamb_gov_2016_26", "The process through which citizens acquire political values is", "education", "acculturation", "socialization", "participation", 2, "Political socialization is the lifelong learning process conveying civic beliefs and values.", "Political Socialization", "2016"),
    ("jamb_gov_2016_27", "The main objective of pressure groups is to", "serve as opposition to the government", "protect the interest of the country against foreigners", "promote the interest of political parties", "influence legislation for the benefit of their members", 3, "Pressure groups lobby state organs to influence policy in favor of their constituent members.", "Pressure Groups", "2016"),
    ("jamb_gov_2016_28", "The three-tier system of Nigerian Federalism was formalised by the", "2004 Pension reform", "1963 Republic Constitution", "1951 Hicks-Phillipson Commission's Report", "1976 local government reform", 3, "The 1976 nationwide Local Government Reform established local councils as a constitutionally recognized third tier of government.", "Local Government", "2016"),
    ("jamb_gov_2016_29", "A flexible constitution is one which is", "known to all the citizens", "popular with the legislators", "easily amended", "written by the parliament", 2, "A flexible constitution can be altered with the same ease as passing ordinary statutory legislation.", "Constitutions", "2016"),
    ("jamb_gov_2016_30", "The main representative body of the United Nations is the", "Security Council", "Secretariat", "Trusteeship", "General Assembly", 3, "The UN General Assembly represents all member states equally with one vote per sovereign nation.", "United Nations", "2016"),
    ("jamb_gov_2016_31", "One feature of public corporations that was weakened by privatization was", "social harmony", "national integration", "social control", "government control", 3, "Privatization strips government of direct administrative control over corporate operations.", "Privatization", "2016"),
    ("jamb_gov_2016_32", "One of the main duties of the Local Government Service Commission is to", "create enabling working environment for council workers", "conduct election into Local Council", "supervise and manage the personnel of local governments", "handle request for the creation of more local governments", 2, "The commission handles recruitment, promotions, and discipline of local government personnel.", "Local Government", "2016"),
    ("jamb_gov_2016_33", "According to Aristotle, a form of government in which the few rule for the benefit of all is", "aristocracy", "polyarchy", "diarchy", "autocracy", 0, "Aristocracy is governance by the virtuous few dedicated to the collective good of the commonwealth.", "Forms of Government", "2016"),
    ("jamb_gov_2016_34", "One of the major problems of Nigerian federalism is", "pre-colonial administrative structure among the units of federation", "imbalance in the structure and sizes of units of federation", "lack of revenue to cater for the demands of the federation", "inadequate manpower to fill vacancies", 1, "Disparities in land mass, population, and resource endowments have generated ongoing federal friction.", "Nigerian Federalism", "2016"),
    ("jamb_gov_2016_35", "Which of the following countries pioneered the establishment of ECOWAS alongside Nigeria?", "Ghana", "Cameroun", "Algeria", "Togo", 3, "Togo co-partnered with Nigeria under Eyadema and Gowon to establish ECOWAS.", "ECOWAS", "2016"),
    ("jamb_gov_2016_36", "The NCNC and NPC facilitated the creation of the", "Eastern Region", "Northern Region", "Western Region", "Mid-West Region", 3, "The 1963 referendum carved the Mid-Western Region out of the Western Region under federal legislative sponsorship.", "State Creation", "2016"),
    ("jamb_gov_2016_37", "A problem of public corporation in Nigeria is", "Wastage of resources", "Choice of leadership", "Public control", "Emphasis on subsidies", 0, "Financial leakages, bureaucracy, and operating deficits have challenged public corporations.", "Public Corporations", "2016"),
    ("jamb_gov_2016_38", "Nigeria's non-alignment policy in the sixties lacked real substance because of her", "poor economic potential", "close ties with Britain", "Afro centric policy", "partnership with Asian countries", 2, "Nigeria's defense agreements and ideological sympathy toward Western democracies contradicted non-aligned neutrality.", "Foreign Policy", "2016"),
    ("jamb_gov_2016_39", "The type of authority that is based on personal qualities is", "charismatic", "Legal", "traditional", "coercive", 0, "Charismatic authority derives from dynamic, exceptional personal character and leadership magnetism.", "Authority", "2016"),
    ("jamb_gov_2016_40", "The judiciary controls the executive in federal systems through", "judicial overview", "motions", "delegated legislation", "judicial review", 3, "Courts nullify ultra vires and unlawful executive actions through the power of judicial review.", "Judiciary", "2016"),
    ("jamb_gov_2016_41", "Which of the following was adjudged as the most free and fair election in Nigeria?", "1999 elections", "1993 elections", "2007 elections", "1982 elections", 1, "The June 12, 1993 presidential election was widely celebrated by international observers as Nigeria's freest election.", "Elections in Nigeria", "2016"),
    ("jamb_gov_2016_42", "Laws made by military governors are called", "acts", "bye-laws", "edicts", "decrees", 2, "Military governors enacted state Edicts, whereas the military head of state promulgated federal Decrees.", "Military Rule", "2016"),
    ("jamb_gov_2016_43", "A problem of public corporations in Nigeria is", "wastage of resources", "public control", "emphasis on subsidies", "choice of leadership", 0, "Mismanagement and resource wastage have chronically hampered performance.", "Public Corporations", "2016"),
    ("jamb_gov_2016_44", "The pro-west orientation of Nigeria's foreign policy was mainly because of her", "historical development", "geographical locations", "social structure", "economic under-development", 3, "Colonial heritage and trade dependency on British and Western markets entrenched a pro-Western posture.", "Foreign Policy", "2016"),
    ("jamb_gov_2016_45", "A sovereign state is one", "whose government decisions are made independent of foreign interference", "whose constitution can be changed by a military government", "in which authority is vested in the military", "where its citizens can speak without fear or favour", 0, "External sovereignty requires absolute freedom from foreign domination or coercive external dictate.", "Sovereignty", "2016"),
    ("jamb_gov_2016_46", "In Nigeria's First Republic, the prime minister was both the", "Head of state and party leader", "Head of government and a lawmaker", "Commander-in-chief of the armed forces and party leader", "Head of state and commander-in-chief of the armed forces", 1, "The Prime Minister held an elective seat in parliament while leading the executive branch.", "First Republic", "2016"),
    ("jamb_gov_2016_47", "The AU differs from the OAU in having", "no permanent headquarters", "effective mechanisms for enforcing its decisions", "a minimum of divergent viewpoints", "no assembly of Heads of state", 1, "The AU incorporates intervention mandates under Article 4(h) of its Constitutive Act to enforce regional decisions.", "African Union", "2016"),
    ("jamb_gov_2016_48", "Under Nigeria's Second Republic, the Senate was under the leadership of", "Joseph Wayas", "John Wash Pam", "J.S. Tarka", "Godwin Ume-Ezeoke", 0, "Senator Joseph Wayas was Senate President throughout the civilian Second Republic (1979-1983).", "Second Republic", "2016"),
    ("jamb_gov_2016_49", "The ultimate aim of political parties is to", "implement people-oriented programmes", "acquire and exercise power", "formulate and implement policies", "increase the political awareness of the electorate", 1, "Contesting elections to capture and exercise state authority is the central objective of political parties.", "Political Parties", "2016"),
    ("jamb_gov_2016_50", "Rule by the old people is known as", "gerontocracy", "theocracy", "monarchy", "feudalism", 0, "Gerontocracy vests political supremacy in a council of senior elders.", "Forms of Government", "2016")
]

# 2017 Government (40 Qs)
g2017 = [
    ("jamb_gov_2017_01", "Which of the following is a foremost right of a citizen?", "Religious right", "Academic right", "Right to life", "Private life", 2, "The right to life is the foundational right upon which all other civil and human liberties depend.", "Fundamental Rights", "2017"),
    ("jamb_gov_2017_02", "Which of the following is a merit of aristocracy?", "Leaders must have military experience", "The best citizen is in control of government", "Organised few control the government", "Majority control the government", 1, "Aristocratic philosophy claims governance by the most cultivated, educated, and ethically qualified leaders.", "Forms of Government", "2017"),
    ("jamb_gov_2017_03", "Which of the following is a strategy of foreign policy implementation?", "Cultural integration", "Democratic elections", "Political representation", "Propaganda", 3, "Diplomatic representation, propaganda, economic aid, treaties, and military power are core tools of foreign policy.", "Foreign Policy", "2017"),
    ("jamb_gov_2017_04", "The Structural Adjustment Programme was introduced under the", "Babangida Regime", "Obasanjo Regime", "Buhari Regime", "Abacha Regime", 0, "General Ibrahim Babangida introduced SAP in 1986 under IMF/World Bank economic reform guidelines.", "Economic Policy", "2017"),
    ("jamb_gov_2017_05", "To facilitate the effective achievement of its objectives, ECOWAS is operationally structured with", "councils", "panels", "committees", "commissions", 0, "ECOWAS is organized around specialized ministerial councils and operational directorates.", "ECOWAS", "2017"),
    ("jamb_gov_2017_06", "Shortage of trained personnel is a major problem of the", "Federal Government", "State Governments", "Regional Governments", "Local Governments", 3, "Grassroots local councils chronically struggle with recruitment of technical, medical, and administrative experts.", "Local Government", "2017"),
    ("jamb_gov_2017_07", "The right of a state to govern its territory and people without external control is known as", "authority", "power", "sovereignty", "legitimacy", 2, "Sovereignty is the supreme, inalienable constitutional authority of a state over its domestic and foreign affairs.", "Sovereignty", "2017"),
    ("jamb_gov_2017_08", "The popularity of a political party in given democracy rests on its", "constitution", "manifesto", "ideology", "number of branches", 1, "An appealing, actionable party manifesto attracts voter enthusiasm and electoral support.", "Political Parties", "2017"),
    ("jamb_gov_2017_09", "A system of local council that allows for rotational leadership is known as", "single executive", "dual executive", "multi executive", "collegiate executive", 3, "Collegiate executives distribute presiding leadership roles among council members collectively.", "Local Government", "2017"),
    ("jamb_gov_2017_10", "A type of constitution that is difficult to amend is described as", "written and flexible", "rigid and written", "unwritten and rigid", "flexible and rigid", 1, "Rigid written constitutions mandate complex super-majorities to effect constitutional amendments.", "Constitutions", "2017"),
    ("jamb_gov_2017_11", "The political achievement of UN is the promotion of", "economic development", "educational development", "international peace and security", "democratic institution", 2, "Under Article 1 of the UN Charter, preserving collective international peace and security is the primary mandate.", "United Nations", "2017"),
    ("jamb_gov_2017_12", "Elective principle in Nigeria was first introduced by", "Richards Constitution", "Macpherson Constitution", "Littleton Constitution", "Clifford Constitution", 3, "Sir Hugh Clifford's 1922 Constitution introduced elective democracy for four legislative council seats.", "Constitutional History", "2017"),
    ("jamb_gov_2017_13", "The three major political parties of the First Republic can be said to have had", "national outlook", "regional and ethnic undertone", "governmental funding", "religious and sectional appeals", 1, "The NPC (North), Action Group (West), and NCNC (East) drew support primarily from regional and ethnic bases.", "Party Politics", "2017"),
    ("jamb_gov_2017_14", "Development of the Civil Service relies on", "impartiality", "anonymity", "pro notability", "neutrality", 2, "Professional meritocracy, non-partisan neutrality, and anonymity ensure institutional performance.", "Civil Service", "2017"),
    ("jamb_gov_2017_15", "The chief executive system is associated with", "federalism", "presidentialism", "parliamentary", "unitarism", 1, "Presidentialism concentrates supreme executive authority in a single Chief Executive President.", "Presidential System", "2017"),
    ("jamb_gov_2017_16", "Public Corporations are mainly funded through", "foreign aid", "shareholders fund", "internally generated funds", "government subvention", 3, "Government subventions, state grants, and statutory budgetary allocations finance public corporations.", "Public Corporations", "2017"),
    ("jamb_gov_2017_17", "Which of the following is the oldest Public Corporation in Nigeria?", "Power Distribution Company of Nigeria", "Nigeria Mining Corporation", "Nigerian Railway Corporation", "Nigerian Postal Services", 2, "The Nigerian Railway Corporation traces its origins back to the 1898 Lagos government railway line.", "Public Corporations", "2017"),
    ("jamb_gov_2017_18", "In 1987, Nigeria attained a federation of", "19 states", "12 states", "21 states", "30 states", 2, "General Babangida created Katsina and Akwa Ibom in 1987, raising the state count from 19 to 21 states.", "State Creation", "2017"),
    ("jamb_gov_2017_19", "The Ombudsman aims at", "offering qualitative educational services", "rendering alternative dispute resolution services", "providing qualitative job opportunities", "entertaining complaints on abuse of public office", 3, "The Ombudsman redresses citizen grievances regarding unfair bureaucratic decisions and administrative malice.", "Ombudsman", "2017"),
    ("jamb_gov_2017_20", "The apex body under the military regime of Yakubu Gowon was", "Supreme military Council", "Federal Executive Council", "The Armed Forces Ruling Council", "The national Council of State", 0, "The Supreme Military Council served as the supreme governing council under General Gowon.", "Military Regimes", "2017"),
    ("jamb_gov_2017_21", "One of the problems of the Commonwealth of Nations is lack of", "finance", "administrative structures", "cultural heterogeneity", "capacity to enforce decisions", 3, "The Commonwealth lacks standing military forces or coercive mechanisms to enforce summit resolutions.", "Commonwealth", "2017"),
    ("jamb_gov_2017_22", "A major objective of Public Complaints Commission is", "creating fair opportunities for all government employees", "training and promoting public servants", "addressing grievances of individuals and groups", "creating an efficient work environment", 2, "The PCC investigates unfair administrative practices on behalf of aggrieved citizens.", "Ombudsman", "2017"),
    ("jamb_gov_2017_23", "Activities of pressure groups that influence governmental decisions are hampered by", "its size", "its leadership", "its affiliation", "the economy", 3, "Economic dependence, lack of financial funds, and poverty restrict pressure group lobbying efficacy.", "Pressure Groups", "2017"),
    ("jamb_gov_2017_24", "Which of the following is a major feature of democracy?", "Capacity to influence people", "Existence of political office holders", "Decision making", "Consent of the people", 3, "Democratic legitimacy rests upon the freely given consent of the governed expressed through universal franchise.", "Democracy", "2017"),
    ("jamb_gov_2017_25", "The struggle for self-government from foreign rule is known as", "imperialism", "nationalism", "patriotism", "neo-colonialism", 1, "Nationalism mobilizes colonial subjects to achieve political self-determination and territorial sovereignty.", "Nationalism", "2017"),
    ("jamb_gov_2017_26", "Territorial defence in the Yoruba precolonial system was the responsibility of the", "Bashorun", "Oyomesi", "Aremo", "Are-Ona-Kakanfo", 3, "The Aare-Ona-Kakanfo was the supreme field marshal and commander of the imperial armed forces of Oyo.", "Pre-Colonial Administration", "2017"),
    ("jamb_gov_2017_27", "An effective means of measuring public opinion is", "referendum", "radio interview", "letters to government", "telephone calls", 0, "A national referendum directly registers the voting public's stance on critical statutory or constitutional questions.", "Public Opinion", "2017"),
    ("jamb_gov_2017_28", "Universal Adult Suffrage permits all", "citizens to vote", "qualified male to vote", "qualified citizens to vote", "female to vote", 2, "Universal adult suffrage enfranchises all citizens who satisfy age, sanity, and statutory registration rules.", "Suffrage", "2017"),
    ("jamb_gov_2017_29", "In the pre-colonial Emirate system, the emir of Gwandu controlled the", "Central section", "Southern section", "Eastern section", "Western section", 3, "Following the 1804 Jihad, Abdullahi dan Fodio ruled the Western division of the Sokoto Caliphate from Gwandu.", "Pre-Colonial Administration", "2017"),
    ("jamb_gov_2017_30", "Both federal and state governments derive power from the", "residual list", "concurrent list", "exclusive list", "regional list", 1, "Under Section 4 of the Constitution, both National and State assemblies exercise shared jurisdiction over the Concurrent Legislative List.", "Federalism", "2017"),
    ("jamb_gov_2017_31", "A social group consisting of two or more people who interact and identify with one another is", "nation", "society", "government", "state", 1, "Sociology defines a society as an organized aggregate of interacting individuals sharing cultural norms.", "Basic Concepts", "2017"),
    ("jamb_gov_2017_32", "Which of the following Nigerian president initiated and facilitated the creation of NEPAD?", "Goodluck Jonathan", "Olusegun Obasanjo", "Umaru Musa Yar'dua", "Mohammadu Buhari", 1, "President Olusegun Obasanjo, along with Thabo Mbeki and Bouteflika, authored and launched NEPAD in 2001.", "Foreign Policy", "2017"),
    ("jamb_gov_2017_33", "Nigeria became a republic with the", "1979 Constitution", "1989 Constitution", "1960 Constitution", "1963 Constitution", 3, "The 1963 Republican Constitution officially severed all monarchical links to the Queen of Great Britain.", "Constitutional History", "2017"),
    ("jamb_gov_2017_34", "Which of the following is a function of the civil service commission?", "Enforcement of law and order", "Payment of civil servants' salaries", "Discipline of erring civil servants", "Protection of lives and properties", 2, "The commission investigates misconduct, implements regulations, and sanctions erring civil service personnel.", "Civil Service", "2017"),
    ("jamb_gov_2017_35", "The concentration of power on the units is a merit of", "quasi-federal-system", "confederal system", "federal system", "unitary system", 1, "Confederal structures grant sweeping sovereign autonomy and legislative freedom to constituent units.", "Confederation", "2017"),
    ("jamb_gov_2017_36", "In fascism, the leader is", "supreme", "democratic", "rich", "religious", 0, "Fascist ideology dictates unconditional obedience to the supreme, infallible will of the autocratic dictator.", "Political Ideologies", "2017"),
    ("jamb_gov_2017_37", "Delegated legislation is the", "limitation of responsibilities to agencies", "transfer of responsibilities to agencies", "deterring of responsibilities of agencies", "facilitation responsibilities of agencies", 1, "Primary legislatures delegate statutory rulemaking power to executive ministries and administrative tribunals.", "Delegated Legislation", "2017"),
    ("jamb_gov_2017_38", "Which of the following countries significantly contributed to the formation of ECOMOG?", "Ghana", "Gambia", "Liberia", "Nigeria", 3, "Nigeria provided the lion's share of funding, manpower, logistics, and field command for ECOMOG peacekeeping.", "ECOWAS & ECOMOG", "2017"),
    ("jamb_gov_2017_39", "An important element of the doctrine of separation of powers is", "Delegation of power", "Checks and Balances", "Rule of Law", "Concentration of powers", 1, "Checks and balances ensure each arm of government possesses constitutional means to prevent excess by the others.", "Separation of Powers", "2017"),
    ("jamb_gov_2017_40", "Nigeria's action towards the external environment is embedded in her", "state policy", "party policy", "government policy", "foreign policy", 3, "Foreign policy defines a nation's official diplomatic, economic, and strategic interactions with other sovereign states.", "Foreign Policy", "2017")
]

# 2018 Government (40 Qs)
g2018 = [
    ("jamb_gov_2018_01", "Between 1960 and 1980, Nigeria experienced all the following systems of government except", "unitary", "federal", "confederal", "parliamentary", 2, "Nigeria operated parliamentary (1960-1966), unitary (Decree 34 1966), and federal presidential systems (1979), but never a confederal system.", "Systems of Government", "2018"),
    ("jamb_gov_2018_02", "Which of the following was the first political party in Nigeria?", "The Action Group (AG)", "Northern People's Congress (NPC)", "National Council of Nigeria and the Camerouns (NCNC)", "Nigerian National Democratic Party (NNDP)", 3, "Herbert Macaulay established the NNDP in 1923 following the introduction of the elective principle.", "Party History", "2018"),
    ("jamb_gov_2018_03", "The primary function of government in a state is to", "build schools and hospitals", "provide transport services", "engage in campaigns and rallies", "maintain law and order", 3, "Thomas Hobbes pointed out that the first and fundamental obligation of state governance is preserving civil peace, order, and security.", "The State", "2018"),
    ("jamb_gov_2018_04", "A country is most likely to have a good government only if it has", "a good constitution but bad operators", "good operators but bad constitution", "a good constitution and good operators", "illegitimate government", 2, "Good governance requires both an enlightened constitutional framework and ethical, competent public officials.", "Constitutionalism", "2018"),
    ("jamb_gov_2018_05", "Which of the following is a basic principle of democracy? Rule by", "the majority and the right of the minority", "the minority at the expense of the majority", "the wealthy few", "two political parties", 0, "Democracy operates by majority decision-making while vigorously guaranteeing inalienable civil rights for minorities.", "Democracy", "2018"),
    ("jamb_gov_2018_06", "Which of the following is a legal source of political authority?", "Power from the gun", "Economic power", "Minority power", "Power from the electorate", 3, "Constitutional authority in modern states derives from sovereign electoral choice and statutory law.", "Authority", "2018"),
    ("jamb_gov_2018_07", "Which organ of government is vested with the responsibility of initiating bills and recommending them to the legislature for consideration?", "Federal House of Representatives", "Executive", "Senate", "Judiciary", 1, "The executive drafts executive bills and annual national budget estimates for parliamentary consideration.", "Organs of Government", "2018"),
    ("jamb_gov_2018_08", "In democracies, the political participation could be restricted on the basis of", "religion", "age", "sex", "class", 1, "Electoral laws establish statutory minimum voting ages (e.g. 18 years) to ensure civic maturity.", "Elections", "2018"),
    ("jamb_gov_2018_09", "Disenfranchisement refers to the", "qualification of voters in an election", "Disqualification of fraudulent president aspirants", "denial of the right to vote in an election", "right to vote and be voted for", 2, "Disenfranchisement is the legal or de facto deprivation of an individual's constitutional right to vote.", "Electoral Process", "2018"),
    ("jamb_gov_2018_10", "The limitation of the right to life can be found", "among the people", "in the case of a convicted person", "in the executive", "in the government", 1, "Under Section 33 of the Nigerian Constitution, the execution of a sentence of court following conviction for a capital offense limits the right to life.", "Fundamental Rights", "2018"),
    ("jamb_gov_2018_11", "Which of the following is not an agent of political socialisation?", "Tourism", "Mass media", "Peer group", "University", 0, "Family, schools, universities, mass media, and peer groups are recognized primary agents of socialization; tourism is not.", "Political Socialization", "2018"),
    ("jamb_gov_2018_12", "Political sovereignty belongs to", "the people", "government", "military", "the parliament", 1, "Dicey's political sovereignty is ultimately held by the citizenry who determine public policy through elections.", "Sovereignty", "2018"),
    ("jamb_gov_2018_13", "An alien who has lived in Nigeria for twenty years may acquire citizenship by", "nationalisation", "naturalization", "registration", "marriage", 1, "Section 27 of the 1999 Constitution permits foreign nationals meeting residency requirements to acquire citizenship via naturalization.", "Citizenship", "2018"),
    ("jamb_gov_2018_14", "In a republic parliamentary system of government, the ceremonial Head of State is the", "Chief Justice", "Prime Minister", "President", "Queen", 2, "In republican parliamentary regimes (like Nigeria 1963 or India), an elected or appointed President serves as ceremonial titular Head of State.", "Parliamentary System", "2018"),
    ("jamb_gov_2018_15", "A representative government can be established through", "a general election", "a military coup", "apartheid", "espionage", 0, "Representative democracy requires periodic, competitive, free, and fair general elections.", "Democracy", "2018"),
    ("jamb_gov_2018_16", "Delegated legislation is suitable for", "relieving the parliament of its workload", "enthroning the rule of law", "ensuring the fusion of powers", "checking the executive arm of government", 0, "Delegating detailed operational rule-making to specialized agencies frees parliament to focus on major legislative policy.", "Delegated Legislation", "2018"),
    ("jamb_gov_2018_17", "The indirect rule system succeeded in the Hausa-Fulani society because the", "society had only one religion", "people received Quranic education", "people were descendants of Uthman dan Fodio", "existing administration favoured the system", 3, "The pre-existing centralized authoritarian emirate system, taxes, and Sharia courts mapped seamlessly onto colonial indirect rule.", "Colonial Administration", "2018"),
    ("jamb_gov_2018_18", "The policy of Association was adopted by the", "British to replace their policy of Indirect Rule", "French to replace their policy of Assimilation", "British on their arrival in West Africa", "French on their departure from West Africa", 1, "France abandoned radical assimilation in favor of 'Association', respecting indigenous customs while maintaining colonial subordination.", "Colonial Administration", "2018"),
    ("jamb_gov_2018_19", "Nationalism in Africa eventually led to", "a rapid political awareness among the colonialists", "the alignment of the new states", "de-colonisation", "international economic groupings", 2, "African nationalist agitation culminated in the political withdrawal of European powers and sovereign decolonization.", "Nationalism", "2018"),
    ("jamb_gov_2018_20", "One major achievement of the Richards Constitution of Nigeria was that it", "united the North and South under a single legislature", "provided for official African members of the Executive Council", "allowed the participation of traditional rulers in government", "introduced the elective principle", 0, "The 1946 Richards Constitution brought northern and southern delegates together under a single central Legislative Council for the first time.", "Constitutional History", "2018"),
    ("jamb_gov_2018_21", "The 1954 Constitution of Nigeria made the country a true federation because it provided for", "the abolition of representation of white officials", "the election of all members of parliament", "a division of functions between the centre and the regions", "the post of a Prime Minister at the centre", 2, "The Lyttleton Constitution demarcated powers into Exclusive, Concurrent, and Residual lists, cementing genuine regional autonomy.", "Federalism", "2018"),
    ("jamb_gov_2018_22", "The decision to separate Lagos from the Western Region and make it a neutral Territory was taken at the", "1950 general conference", "1953 constitutional conference", "1954 constitutional conference", "1963 All party constitutional conference", 2, "The London Constitutional Conference of 1953/1954 severed Lagos from the Western Region to serve as a neutral federal capital.", "Constitutional Conferences", "2018"),
    ("jamb_gov_2018_23", "The first Head of State and Head of Government in Nigeria was", "Lord Frederick Lugard", "Alhaji Abubakar Tafawa Balewa", "General J.T.U. Aguiyi Ironsi", "Alhaji Shehu Shagari", 3, "Alhaji Shehu Shagari was the pioneer executive President combining titular head of state and head of government powers under the 1979 Constitution.", "Presidents of Nigeria", "2018"),
    ("jamb_gov_2018_24", "Which of the following did not generate political crisis in Nigeria?", "Adoption of Abuja as the New Federal Capital", "Motion for self-government in 1956 by Enahoro", "1965 election in the Western Region", "1964 General Elections", 0, "The planned transition to Abuja was an administrative consensus recommendation that did not cause constitutional crisis.", "Political Crises", "2018"),
    ("jamb_gov_2018_25", "A system of government where political powers are inherited is called", "monarchy", "diarchy", "democracy", "aristocracy", 0, "Hereditary monarchies transmit sovereign royal authority through dynastic family lineage.", "Forms of Government", "2018"),
    ("jamb_gov_2018_26", "Democracy can be promoted through", "gerrymandering", "slander", "accountability", "lobbying", 2, "Institutional transparency, free media, and governmental accountability strengthen democratic rule.", "Democracy", "2018"),
    ("jamb_gov_2018_27", "The ability to command obedience is called", "authority", "influence", "legitimacy", "mobilisation", 0, "Authority is the legitimate institutional power that commands recognized and lawful obedience.", "Basic Concepts", "2018"),
    ("jamb_gov_2018_28", "Legitimacy is determined mainly by", "charisma", "influence", "acceptance", "desire", 2, "Legitimacy reflects the moral acceptance and recognition by citizens of a government's right to govern.", "Legitimacy", "2018"),
    ("jamb_gov_2018_29", "A.V. Dicey popularised the principle of", "rule of law", "democracy", "political culture", "separation of powers", 0, "British constitutional scholar Albert Venn Dicey popularized the three doctrines of the Rule of Law in 1885.", "Rule of Law", "2018"),
    ("jamb_gov_2018_30", "Which of the following is the lowest in the hierarchy of feudal system?", "Knights", "Serfs", "Nobles", "Lords", 1, "Serfs were bonded peasant laborers situated at the bottom of the feudal socioeconomic pyramid.", "Feudalism", "2018"),
    ("jamb_gov_2018_31", "In which of the following political systems is rule of law most enhanced?", "Cabinet system", "Feudal system", "Fascist system", "Communist system", 0, "Constitutional parliamentary and cabinet systems provide institutional courts, habeas corpus, and legal equality.", "Rule of Law", "2018"),
    ("jamb_gov_2018_32", "The concept of collective responsibility is synonymous with", "presidential system of government", "military system of government", "unitary system of government", "parliamentary system of government", 3, "Cabinet ministers in a parliamentary system must collectively defend all executive government decisions or resign.", "Cabinet Government", "2018"),
    ("jamb_gov_2018_33", "A constitution is the", "written document of traditional practices", "functional aspect of government activities", "supreme documents of the government", "fundamental laws of the land", 3, "A constitution is the organic body of fundamental legal principles and laws according to which a state is governed.", "Constitutions", "2018"),
    ("jamb_gov_2018_34", "Which of the following cannot be found in a constitution?", "Fundamental Human Rights", "Manifestoes of political parties", "Organs of government", "Duties and obligations of citizens", 1, "Party manifestoes are partisan campaign platforms published by political parties, not constitutional statutes.", "Constitutions", "2018"),
    ("jamb_gov_2018_35", "A rigid constitution is a feature of", "unitary system", "monarchical system", "federal system", "confederal system", 2, "Federal states require rigid constitutions to prevent the federal center from arbitrarily altering regional jurisdictions.", "Federalism", "2018"),
    ("jamb_gov_2018_36", "In 1973, following an OAU resolution, Nigeria broke diplomatic relations with", "South Africa", "France", "Israel", "Cuba", 2, "Following the 1973 Yom Kippur War and Israeli occupation of African Egyptian territory, Nigeria severed ties with Israel.", "Foreign Policy", "2018"),
    ("jamb_gov_2018_37", "Nigeria's foreign policy of non-alignment was a reaction to", "British imperialism", "East-West ideological competition", "militarism of ex-colonial powers", "World poverty", 1, "Non-alignment sought to maintain diplomatic sovereignty amidst intense Cold War superpower rivalry.", "Non-Alignment", "2018"),
    ("jamb_gov_2018_38", "Which of the following countries had a strained relationship with Nigeria over the Angolan crisis of 1975?", "The Soviet Union", "Tanzania", "The United States of America", "South Africa", 2, "Nigeria boldly recognized the MPLA government in Luanda and rebuffed US President Gerald Ford's diplomatic pressure.", "Foreign Policy", "2018"),
    ("jamb_gov_2018_39", "The major liberation organisation which fought for Namibia's independence was", "SWAPO", "ANC", "FRELIMO", "M.P.L.A", 0, "The South West Africa People's Organisation (SWAPO) led the armed struggle for Namibia's independence from apartheid South Africa.", "African Liberation", "2018"),
    ("jamb_gov_2018_40", "Which of these international organisations is the predecessor of the United Nations?", "The European Economic Community", "The organisation of American States", "The League of Nations", "The North Atlantic Treaty Organisation", 2, "The League of Nations, established in 1919 after WWI, preceded the creation of the United Nations in 1945.", "United Nations", "2018")
]

append_questions(g2016)
append_questions(g2017)
append_questions(g2018)

# Write footer
with open(out_path, "a", encoding="utf-8") as f:
    f.write("""
        return list
    }
}
""")

print("Successfully written JambGovernment2010to2018CompleteOfficialBank.kt with all 430 questions!")
