# coding=utf-8
"""
Complete Question Data for JAMB Government 1978 Past Questions & Answers - 50 Questions
Faithfully transcribed with exact source wording and verified answer keys from dyplus.
"""

def get_all_gov_1978_questions():
    # 5-option JAMB questions mapped to standard A, B, C, D (or A, B, C, D, E formatted into options)
    gov_data = [
        ("When did Nigeria gain her Independence?",
         "1st October 1963", "31st October 1690", "1st October 2012", "1st October 1960", 3,
         "Nigeria gained full sovereign independence from Great Britain on October 1, 1960.", "Constitutional Development"),
        ("Democracy means a system of government in which",
         "the majority rules", "the minority rules", "there is no party system", "the people rule", 0,
         "Democracy is classically defined as government by the people, primarily exercised through majority rule and democratic representation.", "Basic Concepts of Government"),
        ("A constitution is federal if",
         "it provides for a presidential system", "it is unwritten", "the central and component units are equal", "there is a division of powers between a central and component authorities", 3,
         "Federalism is defined by constitutional division and distribution of powers between a central national government and coordinate regional/state component units.", "Federalism"),
        ("The Executive is",
         "a committee of the legislature", "the body that makes laws", "the body that executes the policies of government", "the highest organ of government", 2,
         "The executive branch is responsible for implementing, administering, and enforcing the laws and policies of government.", "Organs of Government"),
        ("The Judiciary is",
         "an arm of the Executive", "the body which makes the law", "a body of lawyers", "the body which interprets the law", 3,
         "The judiciary functions as the adjudicative organ that interprets the laws and constitution and applies them to disputes.", "The Judiciary"),
        ("The separation of powers means the same as",
         "a presidential system of government", "checks and balances", "the rule of law", "supremacy of the judiciary", 1,
         "The doctrine of separation of powers, championed by Montesquieu, divides governmental authority into distinct branches operating with institutional checks and balances.", "Separation of Powers"),
        ("Rights are",
         "claims which the law allows", "claims against the state", "claims against other individuals", "claims which are natural to men", 0,
         "Fundamental rights are legally recognized and enforceable claims and entitlements that citizens possess under the constitution and laws.", "Citizenship and Rights"),
        ("Pressure groups are",
         "Organization which wants to overthrow the government", "organizations which seek to influence the policies of the government", "associations of people who share the same ideology", "political parties", 1,
         "Pressure groups (interest groups) are organized associations seeking to influence government decisions, legislation, and policies without seeking political office.", "Pressure Groups"),
        ("A cabinet system of government is practiced in",
         "the USSR", "the USA", "the People's Republic of China", "the United Kingdom", 3,
         "The United Kingdom is the classical model of the Westminster parliamentary cabinet system, where executive power is held by a cabinet headed by the Prime Minister.", "Systems of Government"),
        ("The citizen's obligations are",
         "what the government orders", "duties the individual imposes on himself", "what the law requires of the individual", "what the military decrees", 2,
         "Civic obligations represent mandatory legal and constitutional duties required of individuals, such as tax payment, law compliance, and national defense.", "Citizenship"),
        ("An electoral system is the system which governs",
         "the appointment of the Pope elections", "how people vote", "the conduct of elections", "the appointment of cabinet ministers", 2,
         "An electoral system comprises the institutional rules, regulations, and procedures governing the conduct of democratic elections and conversion of votes into seats.", "Elections"),
        ("An unwritten constitution is one which",
         "is not subject to judicial review", "is only partially written", "is not written at all", "is made up solely of conventions", 1,
         "An unwritten constitution (such as that of Great Britain) is not codified into a single organic document, but consists of written statutes, judicial precedents, and unwritten conventions.", "Constitutions"),
        ("Delegated legislation is legislation",
         "which is not submitted to parliament", "made by judicial tribunals", "made by a minister acting an Act of Parliament", "made by local government", 2,
         "Delegated (subordinate) legislation is statutory instruments, orders, and regulations enacted by ministers, departments, or administrative bodies under statutory authority granted by parliament.", "Legislation"),
        ("Before colonial rule, Yoruba traditional rulers were appointed by",
         "the people acting through their representatives", "the Ogboni", "Ifa (oracle) priests", "Kingmakers", 3,
         "In traditional Yoruba monarchies (such as the Oyo Empire), the Oyomesi (council of kingmakers) selected and appointed the Oba from eligible royal lineages.", "Pre-colonial Administration"),
        ("The first political party properly so-called was formed in Nigeria in",
         "1916", "1923", "1944", "1948", 1,
         "The Nigerian National Democratic Party (NNDP), founded by Herbert Macaulay in 1923 following the Clifford Constitution, was Nigeria's first political party.", "Political Parties"),
        ("The Loi Cadre, a major factor in the constitutional development of the French colonial territories, was introduced in",
         "1940", "1946", "1950", "1956", 3,
         "The French Loi Cadre (Enabling Act) of 1956 instituted universal adult suffrage and created semi-autonomous territorial assemblies in French West and Equatorial Africa.", "Colonial Administration"),
        ("The Coussey Commission Report laid the groundwork for the eventual independence of",
         "Gambia", "Gold Coast (Ghana)", "Sierra Leone", "Liberia", 1,
         "The 1949 Coussey Committee Report in the Gold Coast (Ghana) recommended comprehensive constitutional reforms that led to internal self-government and independence under Kwame Nkrumah.", "West African Nationalism"),
        ("The (former) Western Region of Nigeria became internally self-governing in",
         "1955", "1957", "1958", "1956", 1,
         "The Western and Eastern Regions achieved internal self-government in 1957, followed by the Northern Region in 1959.", "Constitutional Development"),
        ("The first Pan African conference was held in",
         "Paris", "Brussels", "London", "New York", 2,
         "The first Pan-African Conference was convened in London in July 1900, organized by Henry Sylvester Williams.", "Pan-Africanism"),
        ("The Public Service Commission (Nigeria) is responsible for the appointment of all",
         "judges of the High Court", "officials of public corporations", "civil servants", "military personnel", 2,
         "The Civil Service / Public Service Commission is the constitutional body mandated to recruit, promote, and discipline civil servants in ministries and government departments.", "Public Administration"),
        ("Constitutional cases in Nigeria can only be raised in the first instance in",
         "the Supreme Court", "the High Courts", "the Courts of Appeal", "the Sharia Court of Appeal", 1,
         "Original jurisdiction for constitutional rights enforcement and initial constitutional challenges lies with the High Courts (Federal or State).", "Judiciary"),
        ("Which of the following would act for the Head of state when he is out of the country?",
         "the Chief Justice of the Supreme Court", "the Chief of Staff, Army", "the Chief of Staff, Supreme Military Headquarters", "the Chief of Staff, Air Force", 2,
         "Under Nigerian military regimes (e.g. 1975–1979), the Chief of Staff, Supreme Military Headquarters was the second-in-command and acting head.", "Military Rule"),
        ("To raise funds, local governments can levy",
         "import duties", "income taxes", "rates", "profits tax", 2,
         "Local governments possess statutory authority to levy tenement rates, market fees, and local community dues.", "Local Government"),
        ("The Economic Commission for Africa is an agency of",
         "the OAU", "the Commonwealth", "the United Nations", "the African Development Bank", 2,
         "The United Nations Economic Commission for Africa (UNECA) is one of the UN's five regional commissions, established in 1958.", "International Organizations"),
        ("Nigeria is not a member of",
         "the OAU", "the Security Council of the UN", "the African Development Bank", "the OCAM", 3,
         "OCAM (Organisation Commune Africaine et Malgache) was an organization composed almost exclusively of francophone African states; Nigeria was never a member.", "Foreign Policy"),
        ("The primary function of political parties is to",
         "oppose the government", "Aggregate interest and contest power", "mobilize public opinion", "provide welfare for their member", 1,
         "Political parties aggregate societal interests, articulate policy alternatives, and contest elections to gain control of government.", "Political Parties"),
        ("The OAU was formed in",
         "1946", "1956", "1960", "1963", 3,
         "The Organization of African Unity (OAU) was founded on May 25, 1963, in Addis Ababa, Ethiopia.", "OAU and African Unity"),
        ("All members of the newly constituted local government councils in Nigeria were",
         "Directly elected", "indirectly elected", "appointed by the State Governors", "appointed by the Head of State", 0,
         "The 1976 Local Government Reforms introduced representative democratic local government with directly elected councillors across Nigeria.", "Local Government Reforms"),
        ("Which of the following is true as a major function of elections?",
         "Elections serve the purpose of recruitment of the leaders to office in a modern state", "the elections give the people a chance to eliminate opponents who are in office", "they are means of testing the popularity of politicians", "politicians use elections as tools to deceive the populace", 0,
         "The primary institutional function of democratic elections is the legitimate recruitment and peaceful selection of political leaders.", "Electoral Process"),
        ("The first Governor General of Nigeria was",
         "Lord Lugard", "Dr Nnamdi Azikiwe", "Sir James Robertson", "Major General Aguiyi Ironsi", 0,
         "Lord Frederick Lugard became the first Governor-General of amalgamated Nigeria in 1914.", "Colonial Administration"),
        ("The supreme policy-making organ in the Organization of African Unity is",
         "the Council of ministers", "the Assembly of Heads of State and Government", "the general secretariat", "the specialized commissions", 1,
         "The Assembly of Heads of State and Government was the supreme organ and highest decision-making authority of the OAU.", "OAU"),
        ("In which of these organs of the United Nations Organization is veto power exercised by some countries?",
         "the world health organization", "the security council", "the general assembly", "the international court of justice", 1,
         "The five permanent members of the UN Security Council (P5: US, UK, France, Russia, China) hold individual veto power on substantive resolutions.", "United Nations"),
        ("In a federal system such as Nigeria the local governments are directly responsible",
         "to the federal or central government", "to the state government", "to no other level of government", "to the federal and state governments", 1,
         "In the Nigerian federation, local governments operate within the constitutional administrative framework and oversight of their respective state governments.", "Federalism"),
        ("The 1946 constitutions in Nigeria and the Gold Coast (Ghana) were the results of",
         "pressures from nationalists within the colonies", "pressures by united states of America", "pressures from the British government", "pressures from within and from outside these colonies", 3,
         "The post-WWII Richards Constitution (Nigeria) and Burns Constitution (Gold Coast) resulted from internal nationalist agitation and external global decolonization pressures.", "Constitutional History"),
        ("If the rights of the individual are violated or threatened, where can he go for redress?",
         "the Executive branch of government", "the Legislative branch of government", "the Local government council", "the Judicial branch of government", 3,
         "The judiciary serves as the ultimate bastion and constitutional guardian of fundamental human rights, granting judicial review, injunctions, and habeas corpus.", "The Judiciary"),
        ("In the Presidential system of government the president is elected to office by",
         "the cabinet", "the parliament or legislature", "the military", "the people through direct elections", 3,
         "In a presidential democracy, the executive president derives democratic legitimacy directly from nationwide popular election by the electorate.", "Systems of Government"),
        ("The military take over powers from politicians in West African countries",
         "when politician have become corrupt and reckless in power", "when there is a breakdown of law and order in the country", "for reasons touching on corporate interest of military", "all of the above", 3,
         "Military interventions in West Africa historically stem from combinations of political corruption, civilian breakdown of order, and military institutional self-interest.", "Military in Politics"),
        ("By establishing public corporations, governments are trying to",
         "eliminate private enterprises", "compete with private enterprise", "render crucial services to the public in areas which the civil service cannot effectively handle", "make quick profit at the expense of the people", 2,
         "Statutory public corporations provide vital public infrastructure, utilities, and commercial amenities with commercial flexibility beyond the bureaucratic civil service.", "Public Corporations"),
        ("The constitution of any given country must provide for",
         "the distribution of powers", "the rights and duties of the individual", "the rule of law", "the distribution of powers, rights and duties, and rule of law", 3,
         "A complete constitutional framework provides for institutional distribution of powers, citizen rights and obligations, and the supremacy of the rule of law.", "Constitutional Law"),
        ("In a modern state, pressure Groups find that the most effective way of achieving their purposes is by",
         "causing trouble among the populace", "influencing decisions of government", "forming political parties", "rigging elections to offices of the state", 1,
         "Pressure groups achieve their objectives primarily through lobbying, advocacy, and strategic influence on executive and legislative decision-makers.", "Pressure Groups"),
        ("Which of the following would you consider the most famous among the leaders of nationalist movement in Nigeria?",
         "Kwame Nkrumah", "General Olusegun Obasanjo", "Herbert Macaulay", "Anthony Enahoro", 2,
         "Herbert Macaulay is revered as the Father of Nigerian Nationalism, founding the NNDP in 1923 and co-founding the NCNC in 1944.", "Nationalist Movement"),
        ("The idea of collective responsibility in the Executive branch of government means that",
         "no single member of the executive can take any responsible decision", "a member of the executive has no way out of decisions made", "a member of the executive cannot publicly criticize decisions collectively made without first resigning", "responsibility within the executive is not unilateral", 2,
         "Under cabinet collective responsibility, all cabinet ministers must publicly support cabinet decisions or resign their ministerial appointment.", "Cabinet System"),
        ("Indirect Rule as practised by the British in their West African colonies",
         "did not attempt to reform existing traditional institutions", "was over glorified and expedient nonsense", "satisfied neither the rulers nor the ruled", "meant ruling through existing rulers and attempting to check excesses", 3,
         "Lord Lugard's system of Indirect Rule governed the native population through their traditional indigenous rulers and institutional frameworks subject to British supervision.", "Colonial Administration"),
        ("The French idea of assimilation as applied in their colonies",
         "was to make Frenchmen out of African subjects", "would have produced more Frenchmen in colonies than in France", "recognized real value in traditional African culture", "produced nothing but African puppets in the colonies", 0,
         "The French policy of assimilation aimed to culturally, socially, and legally transform African colonial subjects into French citizens (assimilés).", "Colonial Policies"),
        ("The most remarkable thing about post-independence political development in the Gambia is",
         "that the country has been swallowed up by Senegal", "the relatively untarnished reputation of Sir Dauda Jawara", "that without reliance on overwhelming force, the government remained in power and tolerated opposition", "the uniquely robust economy established", 2,
         "Under Sir Dawda Jawara, post-independence Gambia maintained continuous multi-party democracy and civilian governance without a standing army for decades.", "African Politics"),
        ("The dominant idea behind the establishment of the Organization of African Unity is",
         "that Africa must unite", "to show the world that Africa can compete with others", "to provide a framework and opportunities for co-operation on common African problems", "to promote economic development of Africa", 2,
         "The OAU was formed to promote solidarity, coordinate interstate cooperation, defend sovereignty, and eradicate all forms of colonialism in Africa.", "OAU"),
        ("The new local government reforms in Nigeria (1976)",
         "seek to establish uniformity in type, purpose and functions of local authorities", "make traditional rulers more powerful than ever before", "are a waste of time and federal money", "promote diversity in local government structures", 0,
         "The landmark 1976 Local Government Reform created a standardized single-tier structure of local government across all states in Nigeria.", "Local Government Reforms"),
        ("The principle of universal adult suffrage refers to",
         "the right of all adult people to vote", "the structure of political parties", "the legal nature of a constitution", "the right to free speech", 0,
         "Universal adult suffrage guarantees that all adult citizens, regardless of wealth, gender, or social status, have the constitutional right to vote.", "Franchise and Elections"),
        ("A constituency is",
         "an area or district in which the inhabitants can send a representative to parliament", "the same as a legislature", "part of the campaign process", "an important part of every monarchy", 0,
         "A constituency (electoral district) is a defined geographical area whose registered voters elect a member to the legislative assembly.", "Electoral Process"),
        ("The treaty establishing the Economic Community of West African States (ECOWAS) was",
         "concluded in Lomé (Togo) in December 1976", "designed as the main pillar of an African common market", "the brainchild of Togo and Ghana", "signed in Lagos in May 1975 to promote trade and economic cooperation", 3,
         "The Treaty of Lagos was signed on May 28, 1975, by 15 West African nations, establishing ECOWAS to foster regional economic integration.", "ECOWAS and Regional Integration")
    ]

    questions = []
    for idx, item in enumerate(gov_data, 1):
        q, a, b, c, d, ans, exp, topic = item
        questions.append({
            "id": f"jamb_gov_1978_{idx:02d}",
            "subject": "Government",
            "topic": topic,
            "year": "1978",
            "text": q,
            "a": a, "b": b, "c": c, "d": d,
            "ans": ans,
            "exp": exp,
            "label": f"JAMB Government 1978 • Q{idx}"
        })
    return questions
