import sys, os
sys.path.append(os.path.dirname(__file__))
from generate_lit_gov_banks import write_bank
from generate_literature_official import l2010
from generate_lit_2011 import l2011
from generate_lit_2012 import l2012
from generate_lit_2013 import l2013

lit_master = []
lit_master.extend(l2010)
lit_master.extend(l2011)
lit_master.extend(l2012)
lit_master.extend(l2013)

from generate_lit_2014 import l2014
lit_master.extend(l2014)

# We also need 2015, 2016, 2017, 2018 for Literature
from generate_lit_2014 import l2014 # reference base

# Let's import 2015 questions
# 2015 Literature
l2015 = [
    ("jamb_lit_2015_01", "Literature in English", "The Sun Rising - John Donne", "2015", "'Busy old fool, unruly sun why through windows and through curtains call on us?' Most vivid device is", "simile", "diction", "personification and apostrophe", "pun", 2, "Personifies the morning sun as an unruly old busybody."),
    ("jamb_lit_2015_02", "Literature in English", "The Negro Speaks of Rivers - Langston Hughes", "2015", "The historical allusion in Hughes's The Negro Speaks of Rivers spans", "biblical", "classical", "literary", "deep historical civilizational milestones", 3, "Chronicles ancient African civilisations from the Nile and Congo to America."),
    ("jamb_lit_2015_03", "Literature in English", "Hard Lines - Gbemisola Adeoti", "2015", "In Adeoti's Hard Lines, sodium cyanide symbolizes that which is", "deadly poisonous and destructive", "adhesive", "sweet", "fragrant", 0, "Represents fatal political and environmental toxicity."),
    ("jamb_lit_2015_04", "Literature in English", "Homeless, Not Hopeless - Owonibi", "2015", "In Homeless, Not Hopeless, the persona explains that street beggars", "worry about heaven", "attend conferences", "are absorbed in daily survival needs", "rarely sleep", 2, "Focuses on the immediate reality of securing daily sustenance."),
    ("jamb_lit_2015_05", "Literature in English", "Serenade - Selected Poetry", "2015", "The poet persona in Serenade adopts the posture of an ardent", "suitor and romantic lover", "mother", "spinster", "passer-by", 0, "A passionate suitor singing outside his beloved's window."),
    ("jamb_lit_2015_06", "Literature in English", "Myopia - Syl Cheney-Coker", "2015", "In Cheney-Coker's Myopia, peasants refer to the", "underprivileged, suffering working masses", "politicians", "farmers only", "rural dwellers", 0, "The exploited, voiceless multitude suffering under corrupt governance."),
    ("jamb_lit_2015_07", "Literature in English", "Expelled - Jared Angira", "2015", "In Angira's Expelled, the poet persona laments the", "loss of property and sudden displacement from one's homeland", "stranger's visit", "presence of strangers", "family problems", 0, "Mourns the forced eviction and traumatic dispossession of innocent families."),
    ("jamb_lit_2015_08", "Literature in English", "Upon An Honest Man's Fortune - John Fletcher", "2015", "Fletcher's Upon An Honest Man's Fortune achieves its lyrical effect through", "synecdoche", "antithesis and balanced philosophical couplets", "enjambment", "ballad meter", 1, "Employs balanced philosophical antitheses celebrating moral fortitude."),
    ("jamb_lit_2015_09", "Literature in English", "The Soul's Errand - Sir Walter Raleigh", "2015", "Rhythm and urgency are achieved in Raleigh's The Soul's Errand through the use of", "metaphor", "alliteration", "strophic repetition and the refrain 'Give the world the lie'", "antithesis", 2, "The repeated imperative refrain drives the poem's fearless tempo."),
    ("jamb_lit_2015_10", "Literature in English", "Ambassadors of Poverty - P.O.C. Umeh", "2015", "The title of Umeh's Ambassadors of Poverty is primarily", "repetition", "a simile", "an alliteration", "a biting situational and verbal irony", 3, "Irony describing corrupt leaders whose actions spread destitution rather than solutions."),
    ("jamb_lit_2015_11", "Literature in English", "Literary Principles", "2015", "The rapid repetition of identical consonant sounds at the beginning of neighboring words is", "alliteration", "pun", "onomatopoeia", "assonance", 0, "Alliteration creates euphony and musical emphasis."),
    ("jamb_lit_2015_12", "Literature in English", "Literary Principles", "2015", "A play or narrative in which episodes succeed one another without strict causal connection is", "episodic", "simple", "linear", "convoluted", 0, "Episodic structure strings together loosely connected incidents."),
    ("jamb_lit_2015_13", "Literature in English", "Literary Principles", "2015", "A narrative technique recalling a previous occurrence to illuminate current events is a", "climax", "flashback", "interlude", "catharsis", 1, "Flashback supplies critical backstory and emotional context."),
    ("jamb_lit_2015_14", "Literature in English", "Literary Principles", "2015", "Literary criticism is the scholarly activity which seeks to", "find faults", "analyze, interpret and evaluate literary works", "compare novels", "discover beauty only", 1, "Systematic analysis, interpretation, and critical valuation of literature."),
    ("jamb_lit_2015_15", "Literature in English", "Literary Principles", "2015", "A dramatic line spoken by an actor to the audience without other characters on stage hearing is an", "soliloquy", "chorus", "aside", "solo", 2, "An aside creates dramatic irony directly shared with the theater audience."),
    ("jamb_lit_2015_16", "Literature in English", "Literary Principles", "2015", "A synchronized group of performers who sing, dance, and comment on the dramatic action is the", "chorus", "clown", "playwright", "cast", 0, "The classical Greek chorus provides philosophical commentary and exposition."),
    ("jamb_lit_2015_17", "Literature in English", "Literary Principles", "2015", "A literary character whose specific name provides the title of the work is an", "antagonist", "round character", "eponymous character", "flat character", 2, "Eponymous characters include Hamlet, Macbeth, and Oliver Twist."),
    ("jamb_lit_2015_18", "Literature in English", "Literary Principles", "2015", "In poetry, the term 'poetic license' refers to the", "freedom to sell poems", "liberty poets take to bend rules of grammar and meter for artistic effect", "approval to publish", "honorary degree", 1, "Artistic freedom to deviate from conventional grammar and factual rigidity."),
    ("jamb_lit_2015_19", "Literature in English", "Literary Principles", "2015", "The principal, central character who drives the narrative action forward is the", "protagonist", "actor", "antagonist", "heroine only", 0, "The protagonist is the central figure facing the core conflict."),
    ("jamb_lit_2015_20", "Literature in English", "Literary Principles", "2015", "A form of poetry that nostalgically idealizes simple rural, rustic, and shepherd life is", "ballad", "romance", "epic", "pastoral", 3, "Pastoral poetry celebrates idyllic rustic tranquility away from urban corruption."),
    ("jamb_lit_2015_21", "Literature in English", "Song of Lawino - Okot p'Bitek", "2015", "'We all make decisions. Sometimes it is wrong, sometimes it is right.' The speaker's tone is", "afraid", "excited", "pessimistic", "reassuring and pragmatic", 3, "Adopts a calm, pragmatic acceptance of human fallibility."),
    ("jamb_lit_2015_22", "Literature in English", "Song of Lawino - Okot p'Bitek", "2015", "'Her neck is rope-like thin, long and skinny and her face sickly pale.' The stylistic mode is", "narrative", "argumentative", "dramatic", "vivid descriptive satire", 3, "Lawino uses biting visual descriptions to ridicule Clementine's Western cosmetic bleaching."),
    ("jamb_lit_2015_23", "Literature in English", "Once Upon A Time - Gabriel Okara", "2015", "'Once upon a time son... they only laugh with their teeth, while their ice-block-cold eyes search behind my shadow' expresses", "friendliness", "hypocrisy and emotional insincerity of modern adulthood", "jealousy", "sympathy", 1, "Contrasts genuine childhood warmth with cold, calculated adult duplicity."),
    ("jamb_lit_2015_24", "Literature in English", "Love Song - Traditional Poetry", "2015", "'When she opens her heart the savior's image!' The allusion suggests", "the poet is a Christian", "spiritual exaltation and divine reverence for the beloved", "cardiac surgery", "anti-climax", 1, "Equates the beloved's purity with sacred divine iconography."),
    ("jamb_lit_2015_25", "Literature in English", "She Stoops to Conquer - Oliver Goldsmith", "2015", "'Here we live in an old rumbling mansion, that looks for all the world like an inn, but we never see company.' Figure of speech in 'like an inn' is", "irony", "euphemism", "simile", "metaphor", 2, "Explicit simile comparing the cavernous home to an empty public coaching inn."),
    ("jamb_lit_2015_26", "Literature in English", "Literary Appreciation", "2015", "'She gave out colanuts... to appease the angry earth and Amadioha spoke through lightning and thunder.' Figure of speech in the third line is", "personification", "simile", "hyperbole", "metaphor", 0, "Thunder and lightning are personified as the direct voice of the deity Amadioha."),
    ("jamb_lit_2015_27", "Literature in English", "She Stoops to Conquer - Oliver Goldsmith", "2015", "Mrs. Hardcastle's attitude regarding living in their old country mansion is", "hopeful", "frustrated and complaining", "regretful", "happy", 1, "She perpetually complains about provincial rural boredom and yearning for London high fashion."),
    ("jamb_lit_2015_28", "Literature in English", "Song of Lawino - Okot p'Bitek", "2015", "'Her neck is rope-like thin... and her face sickly pale' represents the tone of", "ridicule and satirical scorn", "admonition", "anger", "sympathy", 0, "Lawino mocks the artificiality of European fashion adopted by African women."),
    ("jamb_lit_2015_29", "Literature in English", "Ah, Sun-flower - William Blake", "2015", "'Ah, Sunflower, weary of time! Who countest the steps of the sun...' Figure of speech in the second line is", "simile", "personification", "irony", "hyperbole", 1, "The sunflower is personified as a weary pilgrim tracking the sun's journey."),
    ("jamb_lit_2015_30", "Literature in English", "Macbeth - William Shakespeare", "2015", "'There's no art to find the mind's construction in the face: he was a gentleman on whom I built an absolute trust.' The gentleman referred to", "annoys the speaker", "fights the speaker", "detests the speaker", "betrays King Duncan through treason (Thane of Cawdor)", 3, "King Duncan laments how easily he was deceived by the traitorous Thane of Cawdor."),
    ("jamb_lit_2015_31", "Literature in English", "The Old Man and the Sea - Ernest Hemingway", "2015", "The coastal village and flourishing fishing harbor in the novel is situated near", "St. Louis", "Canary Island", "Cleveland", "Havana, Cuba", 3, "The narrative takes place in a small fishing village outside Havana, Cuba."),
    ("jamb_lit_2015_32", "Literature in English", "The Old Man and the Sea - Ernest Hemingway", "2015", "In his fundamental philosophy of struggle against odds, Santiago is best described as", "a Marxist", "an idealist", "an indefatigable, resilient optimist", "a realist", 2, "Maintains unshakable optimism, dignity, and determination despite 84 days without a catch."),
    ("jamb_lit_2015_33", "Literature in English", "The Old Man and the Sea - Ernest Hemingway", "2015", "As he battles the giant marlin and invading sharks alone, Santiago talks to himself because", "he is afraid of the sea", "it keeps him company and maintains focus in profound loneliness", "it scares sharks", "the boy left him", 1, "Speaking aloud helps Santiago combat exhaustion, hallucination, and isolation on the open sea."),
    ("jamb_lit_2015_34", "Literature in English", "The Old Man and the Sea - Ernest Hemingway", "2015", "To the aging Santiago, the boy Manolin represents", "a symbol of oppression", "the cause of ill-luck", "a loyal disciple, companion and source of emotional sustenance", "a lazy youth", 2, "Manolin embodies deep unconditional love, loyalty, and discipleship."),
    ("jamb_lit_2015_35", "Literature in English", "Purple Hibiscus - Chimamanda Ngozi Adichie", "2015", "The central thematic conflict of the novel focuses on", "domestic violence and religious tyranny within the family", "commercial fraud", "child abuse alone", "marital infidelity", 0, "Examines the traumatic domestic terror inflicted by Eugene's fanatical control."),
    ("jamb_lit_2015_36", "Literature in English", "Purple Hibiscus - Chimamanda Ngozi Adichie", "2015", "In the Achike family, the character whose moral defiance catalyzes family liberation is", "Kambili", "Mama", "Sisi", "Jaja", 3, "Jaja's defiance on Palm Sunday by refusing communion breaks Eugene's tyrannical hold."),
    ("jamb_lit_2015_37", "Literature in English", "Purple Hibiscus - Chimamanda Ngozi Adichie", "2015", "The socio-political backdrop of the novel exposes", "military dictatorship, press censorship and academic decay in Nigeria", "single girl travails", "patriarchal family rules", "urban migration", 0, "Interweaves familial tyranny with Nigeria's brutal military dictatorship and public strikes."),
    ("jamb_lit_2015_38", "Literature in English", "A Woman in Her Prime - Asare Konadu", "2015", "'A priest rushed forward and poured libation... Moments passed before bearers could move again.' The incident is", "sacrifice for pregnancy", "the traditional burial procession of Yaw Boakye", "search for Boakye", "finding black hen", 1, "The ritual funeral ceremony for the deceased elder Yaw Boakye."),
    ("jamb_lit_2015_39", "Literature in English", "A Woman in Her Prime - Asare Konadu", "2015", "According to traditional divination in Brenhoma, Pokuwaa's childlessness is attributed to", "physical injury", "destined barrenness", "neglected ancestral sacrifices and spiritual pacification", "witchcraft", 2, "The diviner insists continuous sacrifices are needed to appease the goddess Tano."),
    ("jamb_lit_2015_40", "Literature in English", "A Woman in Her Prime - Asare Konadu", "2015", "The dramatic pouring of libation during the stalled funeral procession takes place", "on the road to the stream", "at the market square", "close to the sacred cemetery / crossroads", "at the village square", 2, "Occurs on the path leading toward the ancestral burial grounds."),
    ("jamb_lit_2015_41", "Literature in English", "The Tempest - William Shakespeare", "2015", "The overarching philosophical theme of Shakespeare's The Tempest is", "man and nature", "heaven and earth", "reconciliation, forgiveness and the renunciation of vengeance", "slow and steady", 2, "'The rarer action is / In virtue than in vengeance.' Prospero chooses forgiveness over revenge."),
    ("jamb_lit_2015_42", "Literature in English", "The Tempest - William Shakespeare", "2015", "In the backstory, Prospero lost his Dukedom of Milan because he devoted his hours to", "alchemy and black magic", "deep scholarly knowledge, occult books and liberal arts", "romance", "court games", 1, "He surrendered worldly political rule to immerse himself in secret academic studies."),
    ("jamb_lit_2015_43", "Literature in English", "The Tempest - William Shakespeare", "2015", "Prospero's moral sense of justice is often viewed critically because", "while condemning Antonio's usurpation, he subjugates Ariel and Caliban on the island", "he wants power back", "he is one-sided", "he is strict with Miranda", 0, "Exposes colonial contradictions in claiming victimhood while enslaving the island's natives."),
    ("jamb_lit_2015_44", "Literature in English", "The Tempest - William Shakespeare", "2015", "A recurring political motif throughout the play is", "the human lust for political power and usurpation", "love for money", "island development", "love at first sight", 0, "Mirrored across Antonio's coup, Sebastian's conspiracy, and Stephano's comic coup."),
    ("jamb_lit_2015_45", "Literature in English", "The Tempest - William Shakespeare", "2015", "Gonzalo in the play is portrayed as", "Antonio's brother", "a Milan Senator", "an honest, compassionate old Neapolitan Councillor", "a conspirator", 2, "The benevolent counselor who secretly provided Prospero with water, garments, and his cherished books."),
    ("jamb_lit_2015_46", "Literature in English", "Women of Owu - Femi Osofisan", "2015", "In Women of Owu, the ancestral gods are dramatically portrayed as", "benevolent protectors", "unjust, destructive and indifferent to human agony", "helpless spectators", "amorous beings", 1, "The gods orchestrate brutal retributive destruction without mercy for innocent victims."),
    ("jamb_lit_2015_47", "Literature in English", "Women of Owu - Femi Osofisan", "2015", "Through the tragic ruin of the city of Owu, Osofisan demonstrates that war is", "utterly senseless, destructive and leaves only grief and ashes", "beneficial to gods", "constructive", "patriotic duty", 0, "Anti-war tragedy highlighting how violent conflict destroys both victors and vanquished."),
    ("jamb_lit_2015_48", "Literature in English", "Women of Owu - Femi Osofisan", "2015", "The deranged prophetess Orisaye insists that she receives prophetic visions from the Yoruba deity", "Sango", "Ogun", "Orunmila", "Obatala (Orisa-Nla)", 3, "Orisaye is consecrated to the pure, white deity Obatala."),
    ("jamb_lit_2015_49", "Literature in English", "Women of Owu - Femi Osofisan", "2015", "In the play, the fierce Allied Commander leading the Ijebu and Ife armies is", "Balogun Okunade (Maye)", "Erelu", "Akinjobi", "Anlugbua", 0, "Maye Okunade leads the allied forces in their vengeful siege of Owu."),
    ("jamb_lit_2015_50", "Literature in English", "Women of Owu - Femi Osofisan", "2015", "In the play, the legendary ancestral founding ruler of Owu-Ipole is", "King of Ijebu", "Ooni of Ife", "Alaafin of Oyo", "Oba Asunkungbade (Anlugbua)", 3, "Anlugbua (Oba Asunkungbade) is the deified warrior-king and founder of Owu.")
]
lit_master.extend(l2015)

print(f"Total Literature questions through 2015: {len(lit_master)}")
