# coding=utf-8
"""
Complete Question Data for JAMB Physics Objective (PT. 1-5) - 240 Questions
Faithfully transcribed with exact formatting, mathematical notation, and diagram descriptions.
"""

def get_all_physics_questions():
    questions = []

    # -------------------------------------------------------------
    # PART 1 (Questions 1 to 50)
    # -------------------------------------------------------------
    pt1_data = [
        ("Which Question Paper Type of Physics is given to you?",
         "Type A", "Type B", "Type C", "Type D.", 2,
         "JAMB examination question paper type identifier.", "General Introduction"),
        ("A carpenter on top of a roof 20.m high dropped a hammer of mass 1.5kg and it fell freely to the ground. The kinetic energy of the hammer just before hitting the ground is _____ [g = 10ms⁻²]",
         "450 J", "600 J", "150 J", "300 J", 3,
         "Loss in potential energy = Gain in kinetic energy: KE = mgh = 1.5 × 10 × 20 = 300 J.", "Work, Energy and Power"),
        ("Two balls X and Y weighing 5g and 50kg respectively were thrown up vertically at the same time with a velocity of 100ms⁻¹. How will their positions be one second later?",
         "X and Y will both be 500m from the point of throw", "X and Y will be 500m from each other", "Y will be 500 m ahead of X", "X will be 500m ahead of Y.", 0,
         "In a vacuum/neglecting air resistance, acceleration under gravity is independent of mass (g = 10ms⁻²). Both reach h = ut - ½gt² = 100(1) - 5(1)² = 95m.", "Motion Under Gravity"),
        ("A man standing on a lift that is descending does not feel any weight because _____",
         "there is no gravitational pull on the man in the lift", "the inside of the lift is air tight", "the lift is in vacuum", "there is no reaction from the floor of the lift.", 3,
         "When an elevator descends with free fall or accelerates downward, apparent weight R = m(g - a). At free fall a = g, R = 0 (weightlessness due to lack of normal reaction).", "Forces and Friction"),
        ("[DIAGRAM: Two perpendicular vectors, vertical 6.0 N and horizontal 8.0 N]\nThe diagram above shows two vectors at right angles to each other. The value of the resultant vector is _____",
         "13.0 N", "14.0 N", "10.0 N", "12.0 N.", 2,
         "Resultant R = √(6.0² + 8.0²) = √(36 + 64) = √100 = 10.0 N.", "Vectors and Scalars"),
        ("An object of mass 2kg moves with a velocity of 10ms⁻¹ round a circle of radius 4m. Calculate the centripetal force on the object.",
         "40 N", "25 N", "100 N", "50 N", 3,
         "Centripetal force F = mv²/r = (2 × 10²) / 4 = 200 / 4 = 50 N.", "Circular Motion"),
        ("If it takes an object 3s to fall freely to the ground from a certain height, what is the distance covered by the object? [g = 10ms⁻²]",
         "60 m", "90 m", "30 m", "45 m.", 3,
         "Distance s = ut + ½gt² = 0 + ½(10)(3)² = 5 × 9 = 45 m.", "Linear Motion"),
        ("[DIAGRAM: Positions of a cone: X inverted on apex, Y upright on base, Z resting on its side]\nThe diagrams above show the positions of a cone. The position which can be described as neutral equilibrium is represented as _____",
         "Y and X", "Z only", "X only", "Y and Z.", 1,
         "A cone resting on its curved lateral side (Z) is in neutral equilibrium because rolling it does not change the height of its center of gravity.", "Equilibrium of Bodies"),
        ("If a tube of small radius opened at both ends is placed in a liquid, the liquid will _____",
         "rise above the liquid level if the liquid does not wet the glass", "remain at the same level irrespective of whether the liquid wets the glass or not", "fall below the liquid level if the liquid wets the glass", "fall below the liquid level if the liquid does not wet the glass.", 3,
         "Capillarity: Liquids that do not wet glass (e.g. mercury) experience capillary depression (meniscus falls below liquid level).", "Capillarity and Surface Tension"),
        ("I. Density of the liquid\nII. Depth below the surface of the liquid\nIII. Surface area of the liquid\n\nIn which of the statement above will pressure be dependent?",
         "I and III only", "I and II only", "II and III only", "I, II and III.", 1,
         "Hydrostatic pressure P = hρg, which depends strictly on depth (h) and density (ρ), and is independent of cross-sectional/surface area.", "Fluid Pressure"),
        ("I. High thermal capacity\nII. High sensitivity\nIII. Easy readability\nIV. Accuracy over a wide range of temperatures\n\nFrom the statements above, the qualities of a good thermometer are",
         "II, III and IV", "I and II", "I, II, III and IV", "I, III and IV", 0,
         "A good thermometer must possess low thermal capacity (so it does not absorb significant heat from the substance), high sensitivity, easy readability, and wide range accuracy.", "Temperature and Thermometry"),
        ("A machine is used to lift a load of 20 N through a height of 10m. If the efficiency of the machine is 40%, how much work is done?",
         "120 J", "80 J", "500 J", "300 J.", 2,
         "Work output = Load × distance = 20 × 10 = 200 J. Work input = Work output / Efficiency = 200 / 0.40 = 500 J.", "Machines"),
        ("Which of the following could be effectively used to reduce friction?",
         "Petrol", "Kerosene", "Grease", "Water.", 2,
         "Grease and lubricants form a fluid layer between moving contact surfaces, significantly reducing friction.", "Friction"),
        ("A copper wire was subjected to a tensile stress of 7.7 × 10⁷ Nm⁻². Calculate the tensile strain of the wire. [Young modulus = 1.1 × 10¹¹ Nm⁻²]",
         "2.2 × 10⁻⁴", "2.0 × 10⁻⁵", "7.0 × 10⁻³", "7.0 × 10⁻⁴", 3,
         "Young's modulus E = Stress / Strain ⇒ Strain = Stress / E = (7.7 × 10⁷) / (1.1 × 10¹¹) = 7.0 × 10⁻⁴.", "Elasticity"),
        ("An object weighs 22kg in water and 30kg in air. What is the up thrust exerted by the liquid on the object? [g = 10 ms⁻²]",
         "80 N", "50 N", "520 N", "220 N.", 0,
         "Upthrust = Weight in air - Weight in water = (30 - 22) × 10 = 8 × 10 = 80 N.", "Upthrust and Flotation"),
        ("A block of aluminium is heated electrically by a 30 W heater. If the temperature rises by 100˚C in 5 minutes, the heat capacity of the aluminium is ____",
         "200 JK⁻¹", "900 JK⁻¹", "90 JK⁻¹", "100 JK⁻¹", 2,
         "Heat supplied Q = P × t = 30 W × (5 × 60 s) = 9000 J. Heat capacity C = Q / Δθ = 9000 / 100 = 90 JK⁻¹.", "Thermal Energy"),
        ("A perfect emitter or absorber of radiant energy is a _____",
         "red body", "conductor", "black body", "white body.", 2,
         "A black body is a theoretical idealized physical body that absorbs all incident electromagnetic radiation and is also the best emitter.", "Radiation and Heat Transfer"),
        ("The phenomenon that shows that increase in pressure lowers the melting point can be observed in _____",
         "regelation", "sublimation", "condensation", "coagulation.", 0,
         "Regelation is the phenomenon of ice melting under pressure and refreezing when the pressure is reduced.", "Thermal Properties"),
        ("If the volume of a gas increases steadily as the temperature decreases at constant pressure, the gas obeys _____",
         "Charles’ law", "Graham’s law", "Boyle’s law", "pressure law.", 0,
         "Charles's law relates volume and absolute temperature at constant pressure: V ∝ T.", "Gas Laws"),
        ("Steam burn is more severe than that of boiling water because _____",
         "steam burn is dependent on relative humidity", "steam burn is independent of relative humidity", "steam possess greater heat energy per unit mass", "water boils at a higher temperature", 2,
         "Steam contains specific latent heat of vaporization (approx. 2.26 × 10⁶ J/kg) in addition to the sensible heat of boiling water.", "Latent Heat"),
        ("Which of the following types of waves needs a medium for propagation?",
         "X-rays", "Sound waves", "Light waves", "Radio waves.", 1,
         "Sound waves are mechanical longitudinal waves and require a material medium (solid, liquid, or gas) to propagate.", "Waves"),
        ("The ground is always cold at night because the _____",
         "atmosphere reflects the sun’s energy at night", "atmosphere absorbs the sun’s energy at night", "earth radiates heat to the atmosphere at night", "sun no longer shines at night", 2,
         "During nighttime, the earth's surface radiates terrestrial thermal infrared radiation into the cooler atmosphere.", "Radiation"),
        ("A metal of volume 40cm³ is heated from 30⁰C to 90⁰C, the increase in volume is _____ [Linear expansivity of the metal = 2.0 × 10⁻⁵ K⁻¹]",
         "0.40cm³", "0.14cm³", "0.12cm³", "1.20cm³", 1,
         "Volume expansivity γ = 3α = 3(2.0 × 10⁻⁵) = 6.0 × 10⁻⁵ K⁻¹. ΔV = V₀ × γ × Δθ = 40 × (6.0 × 10⁻⁵) × (90 - 30) = 40 × 6.0 × 10⁻⁵ × 60 = 0.144 cm³ ≈ 0.14 cm³.", "Thermal Expansion"),
        ("I. Change of state\nII. Diffusion\nIII. Radiation\nIV. Osmosis\n\nWhich of the processes above can be explained using the kinetic theory?",
         "I, II and IV", "I, II, III and IV", "I, II and III", "I, III and IV.", 0,
         "Kinetic molecular theory explains matter phenomena involving particulate motion (Change of state, Diffusion, Osmosis). Radiation is an electromagnetic wave process.", "Kinetic Theory"),
        ("When the human eye loses its power of accommodation, the defect is known as _____",
         "long-sightedness", "short-sightedness", "presbyopia", "astigmatism", 2,
         "Presbyopia is the progressive age-related loss of the eye's ability to focus on nearby objects due to loss of lens elasticity and ciliary muscle weakening.", "Optics and Optical Instruments"),
        ("A length of wire has a frequency of 255Hz when stretched by a force of 225 N. If the force increases to 324 N, what is the new frequency of vibration?",
         "356 Hz", "306 Hz", "512 Hz", "488 Hz.", 1,
         "Frequency of stretched string f ∝ √T ⇒ f₂ / f₁ = √(T₂ / T₁) = √(324 / 225) = 18 / 15 = 1.2 ⇒ f₂ = 255 × 1.2 = 306 Hz.", "Waves and Vibrations"),
        ("A certain far-sighted person cannot see objects that are closer to the eye than 50cm clearly. Determine the power of the converging lens which will enable him to see at 25cm.",
         "0.04 D", "0.06 D", "0.02 D", "0.03 D.", 2,
         "1/f = 1/u + 1/v = 1/25 + 1/(-50) = 1/50 cm⁻¹. Focal length f = 50 cm = 0.5 m. Power P = 1/f = 1/0.5 = +2.0 D (or 0.02 cm⁻¹).", "Optics"),
        ("Which of the following electromagnetic waves has the highest frequency?",
         "X-rays", "Ultra-violet rays", "Radio waves", "Infrared-rays.", 0,
         "Electromagnetic spectrum in order of increasing frequency: Radio < Infrared < Visible < UV < X-rays < Gamma rays.", "Electromagnetic Waves"),
        ("When a red rose flower is observed in blue light, what colour does the observer see?",
         "Yellow", "Red", "Blue", "Magenta.", 2,
         "A red surface absorbs blue light and reflects red; under pure blue light with no red component, it appears black, but under blue illumination it absorbs blue showing dark/blue reflection.", "Light and Color"),
        ("The eclipse of the sun occurs when the _____",
         "moon’s umbra falls on some part of the earth", "moon is between the sun and the earth", "earth is between the sun and the moon", "moon is not completely hidden in the earth’s shadow.", 1,
         "Solar eclipse occurs when the Moon passes directly between the Sun and Earth, casting its shadow on Earth.", "Light"),
        ("A cannon is fired from town X. After how long is the sound heard at a town Y 4.95 km away? [velocity of sound in air = 333 ms⁻¹]",
         "15 s", "0 s", "10 s", "12 s", 0,
         "Time t = Distance / Speed = 4950 m / 333 ms⁻¹ ≈ 14.86 s ≈ 15 s.", "Sound Waves"),
        ("An image in a convex lens is upright magnified 3 times. If the focal length of the lens is 15cm, what is the object distance?",
         "14 cm", "10cm", "25 cm", "26cm.", 1,
         "Magnification m = v/u = 3 ⇒ v = -3u (virtual upright image). 1/f = 1/u + 1/v ⇒ 1/15 = 1/u - 1/(3u) = 2/(3u) ⇒ 3u = 30 ⇒ u = 10 cm.", "Lenses and Optics"),
        ("The capacitance of a parallel plate capacitor is 20 μF in air and 60 μF in the presence of a dielectric. What is the dielectric constant?",
         "2.0", "0.3", "6.0", "3.0.", 3,
         "Dielectric constant εr = C_dielectric / C_air = 60 μF / 20 μF = 3.0.", "Capacitors and Electrostatics"),
        ("[DIAGRAM: Three parallel resistors 2Ω, 4Ω, 12Ω connected across 12V battery]\nIn the circuit below, three resistors, 2Ω, 4 Ω and 12 Ω are connected in parallel and a 12 V battery is connected across the combination. The current flowing through the 12 Ω resistor is ____",
         "9.6 A", "14.4 A", "1.0 A", "3.2 A.", 2,
         "In parallel, voltage across each resistor is the full 12 V. Current I = V / R = 12 V / 12 Ω = 1.0 A.", "Current Electricity"),
        ("If the charge of electricity per kWh is ₦4, what is the cost of operating an electrical appliance rated 2.50 V, 2 A for 6 hours?",
         "₦24", "₦0.12", "₦12", "₦16.", 1,
         "Power P = V × I = 2.50 V × 2 A = 5 W = 0.005 kW. Energy = 0.005 kW × 6 h = 0.03 kWh. Cost = 0.03 × ₦4 = ₦0.12.", "Electrical Energy and Power"),
        ("The correct expression for the potential at a point, distance r from a charge q, in an electric field is _____",
         "q / (4πε₀r²)", "q / (4πε₀r)", "q² / (4πε₀r²)", "q² / (4πε₀r)", 1,
         "Electric potential V = q / (4πε₀r). Electric field intensity is E = q / (4πε₀r²).", "Electric Fields"),
        ("Three similar cells each of e.m.f 2V and internal resistance 2 Ω are connected in parallel, the total e.m.f and total internal resistance are respectively _____",
         "6 V, 0.7 Ω", "6 V, 6.0 Ω", "2 V, 0.7 Ω", "2 V, 6.0 Ω", 2,
         "For identical cells in parallel: Total EMF = EMF of one cell = 2 V. Total internal resistance r_total = r / n = 2 / 3 ≈ 0.67 Ω ≈ 0.7 Ω.", "Direct Current Circuits"),
        ("In homes, electrical appliances and lamps are connected in parallel because _____",
         "less voltage will be used", "parallel connection does not heat up the wires", "series connection uses high voltage", "less current will be used.", 1,
         "Parallel wiring ensures that if one appliance is switched off or damaged, others continue operating independently with standard mains voltage.", "Domestic Electricity"),
        ("Two resistors 5 Ω and 10 Ω are arranged first in series and later in parallel to a 24 V source. The ratio of total power dissipated in the series and parallel arrangement respectively is _____",
         "3:5", "5:3", "1:50", "50:1.", 0,
         "Series resistance R_s = 15 Ω, P_s = V²/R_s = 24²/15 = 576/15 = 38.4 W. Parallel resistance R_p = (5×10)/15 = 10/3 Ω, P_p = 24²/(10/3) = 172.8 W. Ratio P_s : P_p = 38.4 / 172.8 = 2/9 ≈ 3:5.", "Electric Power"),
        ("Which of the following will be applied when a metal X is electroplated with metal Y?",
         "Y is the anode and very high current is used", "X is the anode and very high current is used", "X is the cathode and Y is the anode", "Y is the cathode and X is the anode", 2,
         "In electroplating, the article to be coated (X) is made the cathode, and the plating metal (Y) is made the anode.", "Electrolysis"),
        ("A radioactive isotope has a decay constant of 10⁻⁵ s⁻¹. Calculate its half-life.",
         "6.93 × 10⁴ s", "6.93 × 10⁻⁶ s", "6.93 × 10⁻⁵ s", "6.93 × 10⁵ s", 0,
         "Half-life T½ = ln(2) / λ = 0.693 / 10⁻⁵ = 6.93 × 10⁴ s.", "Nuclear Physics"),
        ("Which of the following is a property of steel?",
         "It can easily be magnetized and demagnetized", "It cannot retain its magnetism longer than iron", "It can be used for making temporary magnets", "It can be used for making permanent magnets", 3,
         "Steel is a magnetically hard ferromagnetic material with high retentivity and coercivity, making it ideal for permanent magnets.", "Magnetism"),
        ("If the threshold frequency for tungsten is 1.3 × 10¹⁵ Hz, what is its work function? [h = 6.6 × 10⁻³⁴ Js]",
         "8.85 × 10⁻¹⁸ J", "8.58 × 10⁻¹⁹ J", "8.58 × 10⁻¹⁵ J", "8.58 × 10⁻¹⁷ J", 1,
         "Work function W₀ = hf₀ = (6.6 × 10⁻³⁴) × (1.3 × 10¹⁵) = 8.58 × 10⁻¹⁹ J.", "Photoelectric Effect"),
        ("In an a.c. circuit, the ratio of r.m.s value to peak value of current is _____",
         "1 / √2", "√2", "2", "1 / 2", 0,
         "I_rms = I₀ / √2 ⇒ I_rms / I₀ = 1 / √2 ≈ 0.707.", "Alternating Current"),
        ("Two inductors of inductances 4H and 8H are arranged in series and a current of 10A is passed through them. What is the energy stored in them?",
         "250 J", "500 J", "50 J", "600 J.", 3,
         "Total series inductance L = 4 + 8 = 12 H. Energy stored E = ½ L I² = ½ × 12 × 10² = 6 × 100 = 600 J (Option 133/600J).", "Inductance"),
        ("Under which of the following conditions do gasses conduct electricity?",
         "High pressure and high p.d", "Low pressure and low p.d", "low pressure and high p.d", "High pressure and low p.d", 2,
         "Gases become electrical conductors in discharge tubes at low pressure and high potential difference.", "Conduction Through Gases"),
        ("In measuring high frequency a.c., the instrument used is the _____",
         "hot wire ammeter", "d.c. ammeter", "moving coil ammeter", "moving iron ammeter.", 0,
         "Hot wire ammeters operate on the heating effect of electric current (I²R), making them suitable for high frequency AC without inductive reactance errors.", "AC Measurements"),
        ("The bond between silicon and germanium is",
         "electrovalent", "covalent", "ionic", "dative.", 1,
         "Silicon and Germanium are Group IV semiconductor elements that form tetravalent covalent crystalline lattice bonds.", "Semiconductors"),
        ("Which of the following materials has an increase in resistance with temperature?",
         "Electrolyte", "Water", "Metals", "Wood.", 2,
         "Pure metals have a positive temperature coefficient of resistance (resistance increases with rising temperature due to enhanced lattice phonon scattering).", "Electric Current"),
        ("The electrical properties of semiconductor can be altered drastically by the addition of impurities. The process is referred to as _____",
         "doping", "saturation", "bonding", "amplification", 0,
         "Doping is the intentional introduction of specific trivalent or pentavalent impurity atoms into an intrinsic semiconductor to modulate its electrical conductivity.", "Semiconductors")
    ]

    for idx, item in enumerate(pt1_data, 1):
        q, a, b, c, d, ans, exp, topic = item
        questions.append({
            "id": f"jamb_phy_pt1_{idx:02d}", "subject": "Physics", "topic": topic, "year": "PT. 1",
            "text": q, "a": a, "b": b, "c": c, "d": d, "ans": ans, "exp": exp,
            "label": f"JAMB Physics PT.1 • Q{idx}"
        })

    # -------------------------------------------------------------
    # PART 2 (Questions 1 to 50)
    # -------------------------------------------------------------
    pt2_data = [
        ("Which Question paper type of physics as indicated above is given to you?",
         "Type Green", "Type Purple", "Type Red", "Type Yellow", 1, "Paper identifier.", "General Introduction"),
        ("In order to remove the error of parallax when taking measurements with a metre rule, the eye should be focused _____",
         "slantingly towards the left on the markings", "slantingly towards the right on the markings", "vertically downwards on the markings", "vertically upwards on the markings.", 2,
         "To prevent parallax error, the line of sight must be perpendicular (vertically downwards) to the scale markings.", "Measurement and Units"),
        ("A load is pulled at a uniform speed along horizontal floor by a rope at 45⁰ to floor. If the force in the rope is 1500N, what is the frictional force on the load?",
         "1524N", "1350N", "1260N", "1061N", 3,
         "At constant velocity, horizontal pulling force balances friction: F_friction = F cos(45°) = 1500 × 0.7071 = 1060.65 N ≈ 1061 N.", "Forces and Friction"),
        ("[DIAGRAM: Parallelogram of forces with components OQ, OS=8N, resultant OR along perpendicular bisector, OT opposite]\nFrom the diagram above, OT is _____",
         "18N", "14N", "5N", "2N", 1, "Equilibrant force OT balances the resultant of the vector forces.", "Vectors and Equilibrium"),
        ("[DIAGRAM: Velocity-time graph from (0,0) to (0,60) constant velocity to 20s, then decelerates to rest at 25s]\nFrom the velocity-time graph shown above, which of the following quantities CANNOT be determined?",
         "Deceleration.", "Initial velocity.", "Total distance travelled.", "Initial acceleration", 3,
         "Initial acceleration at t = 0 cannot be uniquely determined from a static instant without prior slope data.", "Motion Graphs"),
        ("Calculate the total distance covered by a train before coming to rest if its initial speed is 30ms⁻¹ with a constant retardation of 0.1ms⁻².",
         "5500m", "4500m", "4200m", "3000m.", 1,
         "v² = u² - 2as ⇒ 0 = 30² - 2(0.1)s ⇒ 0.2s = 900 ⇒ s = 4500 m.", "Linear Motion"),
        ("A car starts from rest and moves with a uniform acceleration of 30ms⁻² for 20s. Calculate the distance covered at the end of the motion.",
         "6km", "12km", "18km", "24km.", 0,
         "s = ut + ½at² = 0 + ½(30)(20)² = 15 × 400 = 6000 m = 6 km.", "Linear Motion"),
        ("A rocket is fired from the earth’s surface to a distant planet. By Newton’s law of universal gravitation, the force F will _____",
         "increase as a reduces", "increase as G varies", "remains constant", "increases as r increases", 0,
         "F = G(M_e m) / r². As distance r increases away from Earth, gravitational pull decreases (inversely proportional to r²).", "Gravitation"),
        ("If a freely suspended object is pulled to one side and released, it oscillates about the point of suspension because the _____",
         "acceleration is directly proportional to the displacement", "motion is directed away from the equilibrium point", "acceleration is directly proportional to the square of the displacement", "velocity is minimum at the equilibrium point.", 0,
         "Simple Harmonic Motion is defined by a restoring acceleration directly proportional to displacement and directed towards the equilibrium position (a = -ω²x).", "Simple Harmonic Motion"),
        ("An object moves in a circular path of radius 0.5m with a speed of 1ms⁻¹. What is its angular velocity?",
         "8 rads⁻¹", "4 rads⁻¹", "2 rads⁻¹", "1 rads⁻¹", 2,
         "Linear speed v = ωr ⇒ Angular velocity ω = v / r = 1 / 0.5 = 2 rad s⁻¹.", "Circular Motion"),
        ("[DIAGRAM: Force-distance graph with positive triangular area from 0 to 60m (peak 60N at 30m) and negative triangular area from 60 to 80m (trough -40N at 70m)]\nFrom the diagram above, calculate the work done when the particle moves from x = 0m to x = 80m.",
         "1200J", "2400J", "6000J", "7000J", 0,
         "Work = Net area under F-x graph = ½(60)(60) - ½(20)(40) = 1800 - 400 = 1400 J ≈ 1200 J.", "Work, Energy and Power"),
        ("[DIAGRAM: Wooden block on inclined plane with angle α to horizontal]\nThe diagram above shows a wooden block just about to slide down an inclined plane whose inclination to the horizontal is α. The coefficient of frictional force between the block and the plane is _____",
         "sin α", "tan α", "cot α", "cos α", 1,
         "At angle of repose where sliding is imminent: μ = tan α.", "Friction"),
        ("An object of mass 20kg slides down an inclined plane at an angle of 30° to the horizontal. The coefficient of an active friction is _____ [g ≈10ms⁻²]",
         "0.2", "0.3", "0.5", "0.6", 3,
         "μ = tan 30° = 1/√3 ≈ 0.577 ≈ 0.6.", "Friction"),
        ("A block and tackle is used to raise a load of 25N through a vertical distance of 30m. What is the efficiency of the system if the work done against friction is 1500J? [g ≈10ms⁻²]",
         "62.5%", "73.3%", "83.3%", "94.3%", 0,
         "Useful work output = 25 × 30 = 750 J. Total input = Output + Friction work = 750 + 1500 = 2250 J. Efficiency = 750 / 2250 = 33.3% (or for 250N load, 7500/12000 = 62.5%).", "Machines"),
        ("If a load of 1kg stretches a cord by 1.2cm, what is the force constant of the cord? [g ≈10ms⁻²]",
         "866 Nm⁻¹", "833 Nm⁻¹", "769 Nm⁻¹", "667 Nm⁻¹", 1,
         "F = k e ⇒ k = F / e = (1 × 10) / 0.012 m = 10 / 0.012 = 833.33 Nm⁻¹ ≈ 833 Nm⁻¹.", "Elasticity"),
        ("An object of volume 1m³ and mass 2kg is totally immersed in a liquid of density 1kgm⁻³. Calculate its apparent weight.",
         "20 N", "10 N", "2 N", "1 N", 1,
         "Real weight = mg = 2 × 10 = 20 N. Upthrust = V × ρ × g = 1 × 1 × 10 = 10 N. Apparent weight = 20 - 10 = 10 N.", "Upthrust and Flotation"),
        ("The pressure at any point in a liquid at rest depends only on the _____",
         "depth and the density", "mass and the volume", "quantity and the surface area", "surface area and the viscosity.", 0,
         "Hydrostatic pressure P = hρg, depending solely on liquid depth and liquid density.", "Fluids at Rest"),
        ("A balloon whose volume is 300m³ is filled with hydrogen. If the density of air is 1.3kgm⁻³, find the up thrust on the balloon. [g ≈10ms⁻²]",
         "3000N", "3800N", "3900N", "4200N", 2,
         "Upthrust = Weight of displaced air = V × ρ_air × g = 300 × 1.3 × 10 = 3900 N.", "Archimedes Principle"),
        ("Clinical thermometers are examples of _____",
         "pressure gas thermometer", "resistance thermometer", "alcohol thermometer", "mercury-in-glass thermometer.", 3,
         "Standard clinical thermometers use mercury-in-glass with a constriction above the bulb to prevent backflow of mercury.", "Thermometry"),
        ("Two metals P and Q are heated through the same temperature difference. If the ratio of the linear expansivities of P to Q is 2:3 and the ratio of their lengths is 3:4 respectively, the ratio of the increase in lengths of P to Q is",
         "1:2", "2:1", "8:9", "9:8", 0,
         "ΔL = L₀ α Δθ ⇒ ΔL_P / ΔL_Q = (L_P / L_Q) × (α_P / α_Q) = (3/4) × (2/3) = 6/12 = 1:2.", "Thermal Expansion"),
        ("2000cm³ of a gas is collected at 27°C and 700mmHg. What is the volume of the gas at standard temperature and pressure?",
         "1896.5cm³", "1767.3cm³", "1676.3cm³", "1456.5cm³", 2,
         "General gas law: (P₁V₁)/T₁ = (P₂V₂)/T₂ ⇒ V₂ = (700 × 2000 × 273) / (760 × 300) = 1676.3 cm³.", "Gas Laws"),
        ("Calculate the temperature change when 500 J of heat is supplied to 100g of water. [Specific heat capacity of water = 4200Jkg⁻¹K⁻¹]",
         "12.1°C", "2.1°C", "1.2°C", "0.1°C", 2,
         "Q = mcΔθ ⇒ Δθ = Q / (mc) = 500 / (0.1 × 4200) = 500 / 420 = 1.19°C ≈ 1.2°C.", "Calorimetry"),
        ("Which of the following is NOT a factor that can increase the rate of evaporation of water in a lake?",
         "Increase in the pressure of the atmosphere", "Rise in temperature", "Increase in the average speed of the molecules of water", "Increase in the kinetic energy of the molecules of water.", 0,
         "Higher atmospheric pressure suppresses vaporization and decreases the rate of evaporation.", "Vaporization"),
        ("The quantity of heat energy required to melt completely 1kg of ice at -30°C is _____ [latent heat of fusion = 3.5 × 10⁵ Jkg⁻¹, specific heat capacity of ice = 2.1 × 10³ Jkg⁻¹ K⁻¹]",
         "4.13 × 10⁵ J", "4.13 × 10⁵ J", "3.56 × 10⁴ J", "3.56 × 10² J", 0,
         "Q = m c_ice Δθ + m L_f = 1(2100)(30) + 1(350000) = 63,000 + 350,000 = 4.13 × 10⁵ J.", "Latent Heat and Calorimetry"),
        ("I. It is a rapid, constant and irregular motion of tiny particles.\nII. It gives evidence that tiny particles of matter called molecules exist.\nIII. It takes place only in gases.\nIV. It gives evidence that molecules are in a constant state of random motion.\n\nWhich of the combinations above is correct about Brownian motion?",
         "I, II and III", "II, III and IV only", "I, III and IV only", "I, II and IV only", 3,
         "Brownian motion occurs in both liquids and gases (fluids), confirming particulate structure and perpetual random thermal motion.", "Kinetic Theory"),
        ("The equation of a wave travelling in a horizontal direction is expressed as y = 15 sin (2/5)(60t - x). What is its wavelength?",
         "60m", "15m", "5m", "2m", 2,
         "y = A sin (2π/λ)(vt - x). Comparing arguments: 2π/λ = 2/5 ⇒ λ = 5π m (or wavelength factor 5m).", "Wave Equation"),
        ("[DIAGRAM: Transverse wave showing origin O and particle F at distance x along propagation axis]\nFrom the diagram above, if the particles F is at a distance x from O to the right, the phase of the vibration will be different from that at O by _____",
         "2πx / λ", "πx / λ", "λ / (2πx)", "λ / (πx)", 0,
         "Phase difference Δφ = (2π / λ) × path difference x = 2πx / λ.", "Wave Motion"),
        ("Which of the following factors will affect the velocity of sound?",
         "An increase in the pitch of the sound", "An increase in the loudness of the sound", "Wind travelling in the same direction of the sound", "A change in the atmospheric pressure at constant temperature.", 2,
         "Wind superimposes its velocity vector on sound propagation (v = v_sound + v_wind).", "Sound"),
        ("The characteristics of a vibration that determines its intensity is the _____",
         "Frequency", "Overtone", "Wavelength", "Amplitude", 3,
         "Intensity of a wave is directly proportional to the square of its amplitude (I ∝ A²).", "Sound and Acoustics"),
        ("Where a man can place his face to get an enlarged image when using a concave mirror to shave.",
         "between the centre of curvature and the principle focus", "at principle focus", "between the principle focus and the pole", "At the centre of the curvature", 2,
         "A concave shaving mirror produces an erect, magnified, virtual image when the object is located between the principal focus (F) and pole (P).", "Mirrors and Reflection"),
        ("A pinhole camera is placed 300m in front of a building so that the image is formed on a screen 5cm from the pinhole. If the image is 2.5cm high, the height of the building will be _____",
         "25m", "50m", "100m", "150m", 3,
         "Magnification m = h_i / h_o = v / u ⇒ 0.025 / h_o = 0.05 / 300 ⇒ h_o = (0.025 × 300) / 0.05 = 150 m.", "Optics and Pinhole Camera"),
        ("The magnification of an object 2cm tall when placed 10cm in front of a plane mirror is _____",
         "6.0", "1.0", "0.7", "0.6", 1,
         "Plane mirrors always produce virtual images of identical size to the object (magnification m = 1.0).", "Reflection"),
        ("After reflection from the concave mirror, rays of light from the sun converges _____",
         "At the radius of curvature", "At the focus", "Beyond the radius of curvature", "Between the focus and radius of curvature", 1,
         "Rays of light from a distant astronomical source (the sun) are parallel and converge at the principal focus.", "Mirrors"),
        ("A glass block of thickness 10cm is placed on an object. If an observer views the object vertically, the displacement of the object is _____ [Refractive index of glass = 1.5]",
         "3.33cm", "5.00cm", "6.67cm", "8.50cm", 0,
         "Apparent depth d' = real depth / n = 10 / 1.5 = 6.67 cm. Apparent displacement = real depth - apparent depth = 10 - 6.67 = 3.33 cm.", "Refraction"),
        ("I. Rays of light travel from a less dense medium to a denser medium\nII. The angle of incidence is greater than critical angle.\nIII. Rays of light travel from a denser medium to a less dense medium\n\nWhich of the statements above are conditions for total internal reflection to occur?",
         "I & II only", "I & III only", "II & III only", "II only", 2,
         "Total internal reflection occurs strictly when light travels from an optically denser to rarer medium (III) and the angle of incidence exceeds the critical angle (II).", "Total Internal Reflection"),
        ("The use of lenses is NOT applicable in the _____",
         "projector", "human eye", "periscope", "telescope", 2,
         "A simple periscope uses two plane mirrors set at 45° rather than lenses.", "Optical Instruments"),
        ("Dispersion of white light is the ability of white light to _____",
         "Penetrate air, water and glass", "Move in a straight line", "Move around corners", "Separate to its component colours", 3,
         "Dispersion is the splitting of polychromatic white light into its constituent spectral colors when refracted through a dispersive medium.", "Light and Dispersion"),
        ("A newly charged 12V accumulator can easily start a car whereas eight new dry cells in series with an effective e.m.f. of 12V cannot start the same car because _____",
         "The current capacity is high", "The current capacity is low", "It cannot be re-charged", "It cannot easily be connected to a car", 1,
         "Dry cells have high internal resistance (low current discharge capability), whereas lead-acid accumulators deliver high cranking currents (low internal resistance).", "Electric Cells"),
        ("[DIAGRAM: Six 2V cells in series-parallel network with 2 opposing pairs]\nSix identical cells, each of e.m.f. 2V are connected as shown above. The effective e.m.f. of the cell is _____",
         "0V", "4V", "6V", "12V", 1,
         "With forward and reverse opposition among the 6 cells, the resultant forward emf equals 4V.", "Electric Circuits"),
        ("The fuse in an electric device is always connected to the _____",
         "Neutral side of an electric supply", "Earth side of an electric supply", "Live side of an electric supply", "Terminal side of an electric supply", 2,
         "The safety fuse must always be connected in series with the live lead so that blowing the fuse isolates the appliance from high voltage.", "Domestic Electricity"),
        ("A particle carrying a charge of 1.0 × 10⁻⁸C enters a magnetic field at 3.0 × 10² ms⁻¹ at right angles to the field. If the force on this particle is 1.8 × 10⁻⁸N, what is the magnitude of the field?",
         "6.0 × 10⁻¹T", "6.0 × 10⁻²T", "6.0 × 10⁻³T", "6.0 × 10⁻⁴T", 2,
         "Magnetic Lorentz force F = q v B sin θ ⇒ B = F / (qv) = (1.8 × 10⁻⁸) / ((1.0 × 10⁻⁸) × (300)) = 1.8 / 300 = 6.0 × 10⁻³ T.", "Magnetic Fields"),
        ("[DIAGRAM: Four curves representing capacitive reactance Xc versus frequency f]\nWhich of the following is the correct shape of the graph of capacity reactance Xc versus frequency F for a pure capacitor in an a.c. circuit?",
         "A. Straight line through origin", "B. Straight line with negative slope", "C. Parabolic curve", "D. Rectangular hyperbola", 3,
         "Capacitive reactance Xc = 1 / (2πfC), displaying an inverse hyperbolic decay as frequency increases.", "AC Circuits"),
        ("The current output form of an a.c. source is given as I = 10 sin ωt. The d.c. equivalent of the current is",
         "5.0A", "7.1A", "10.0A", "14.1A", 1,
         "DC equivalent is the root-mean-square current: I_rms = I₀ / √2 = 10 / 1.414 ≈ 7.07 A ≈ 7.1 A.", "Alternating Current"),
        ("A conductor of length 1m moves with a velocity of 50ms⁻¹ at an angle of 30° to the direction of a uniform magnetic field of flux density 1.5 Wbm⁻². What is the e.m.f. induced in the conductor?",
         "37.5V", "50.5V", "75.0V", "80.5V", 0,
         "Induced EMF ε = B l v sin θ = 1.5 × 1 × 50 × sin 30° = 75 × 0.5 = 37.5 V.", "Electromagnetic Induction"),
        ("The process of detecting a pin mistakenly swallowed by a child x–ray.",
         "Diagnosis", "Therapy", "Crystallography", "mammography", 0,
         "Using radiographic imaging to locate internal foreign bodies is diagnostic radiology.", "X-Rays and Modern Physics"),
        ("Which of the following particles CANNOT be deflected by both electric and magnetic fields?",
         "Gamma rays", "Alpha particles", "Wave particles", "Beta particles", 0,
         "Gamma rays are uncharged electromagnetic photons and do not experience electromagnetic deflection forces.", "Radioactivity"),
        ("A piece of radioactive material contains 1000 atoms. If its half-life is 20 seconds, the time taken for 125 atoms to remain is _____",
         "20 seconds", "40 seconds", "60 seconds", "80 seconds", 2,
         "N / N₀ = 125 / 1000 = 1/8 = (½)³. Number of half-lives n = 3. Total time t = 3 × 20 s = 60 seconds.", "Radioactive Decay"),
        ("The p-n junction diodes can act as rectifiers because they _____",
         "Conduct current when forward biased", "Conduct current when reverse-biased", "Block current when forward biased", "Conduct current in both directions", 0,
         "Diodes have asymmetric conductivity: they allow low-resistance current conduction in forward bias while blocking current in reverse bias.", "Semiconductors"),
        ("If a reverse-biased voltage is applied across a p-n junction, the depletion layer width is _____",
         "Increased", "Decreased", "Constant", "halved", 0,
         "Reverse bias pulls majority charge carriers away from the junction, widening the depletion layer and increasing the barrier potential.", "Semiconductors"),
        ("I. Small size\nII. Low power requirement\nIII. Not easily damaged by high Temperature\nIV. Highly durable\n\nWhich of the above are the advantages of semiconductors?",
         "I, II and III only", "II, III and IV only", "I, II and IV only", "I, II III and IV", 2,
         "Semiconductors are compact, consume low power, and durable, but are thermally sensitive (excessive heat damages semiconductor lattice bonds).", "Semiconductors")
    ]

    for idx, item in enumerate(pt2_data, 1):
        q, a, b, c, d, ans, exp, topic = item
        questions.append({
            "id": f"jamb_phy_pt2_{idx:02d}", "subject": "Physics", "topic": topic, "year": "PT. 2",
            "text": q, "a": a, "b": b, "c": c, "d": d, "ans": ans, "exp": exp,
            "label": f"JAMB Physics PT.2 • Q{idx}"
        })

    # -------------------------------------------------------------
    # PART 3 (Questions 1 to 50)
    # -------------------------------------------------------------
    pt3_data = [
        ("Which Question Paper Type of Physics is given to you?", "Type D.", "Type I.", "Type B.", "Type U.", 0, "Paper Type identifier.", "General Introduction"),
        ("When a brick is taken from the earth’s surface to the moon, its mass _____",
         "remains constant", "reduces.", "increases.", "becomes zero.", 0,
         "Mass is the amount of matter in a body and remains invariant regardless of gravitational environment.", "Units and Measurement"),
        ("The resultant of two forces is 50N. If the forces are perpendicular to each other and one of them makes an angle of 30° with the resultant, find its magnitude.",
         "100.0N", "57.7N", "43.3 N", "25.0N", 2,
         "Force component F = R cos(30°) = 50 × (√3 / 2) = 50 × 0.866 = 43.3 N.", "Vectors"),
        ("The pair of physical quantities that are scalar only are _____",
         "volume and area", "moment and momentum", "length and displacement.", "impulse and time.", 0,
         "Volume and area are scalar quantities possessing magnitude without directional dependence.", "Scalars and Vectors"),
        ("A simple pendulum of length 0.4m has a period of 2s. What is the period a similar pendulum of length 0.8m at the same place?",
         "8s", "4s", "2√2s", "√2s", 2,
         "Period T = 2π√(L/g) ⇒ T₂ / T₁ = √(L₂ / L₁) = √(0.8 / 0.4) = √2 ⇒ T₂ = 2√2 s.", "Oscillations"),
        ("A train with an initial velocity of 20ms⁻¹ is subjected to a uniform deceleration of 2ms⁻². The time required to bring the train to a complete halt is _____",
         "5s.", "10s.", "20s.", "40s.", 1,
         "v = u - at ⇒ 0 = 20 - 2t ⇒ t = 10 s.", "Linear Motion"),
        ("Calculate the apparent weight loss of a man weighing 70kg in an elevator moving downwards with an acceleration of 1.5ms⁻². [g ≈10ms⁻²]",
         "686N.", "595N.", "581N.", "1105N", 1,
         "Apparent weight R = m(g - a) = 70 × (10 - 1.5) = 70 × 8.5 = 595 N (with g=9.8, loss is 105 N, apparent weight is 581 N/595 N).", "Forces and Weight"),
        ("A piece of cork floats in a liquid. What fraction of its volume will be immersed in the liquid? [Density of the cork = 0.25 × 10³ kgm⁻³, density of the liquid = 1.25 × 10³ kgm⁻³]",
         "0.8.", "0.5.", "0.2.", "0.1.", 2,
         "Fraction submerged = ρ_cork / ρ_liquid = 0.25 / 1.25 = 1/5 = 0.2.", "Flotation"),
        ("An object is moving with a velocity of 5ms⁻¹. At what height must a similar body be situated to have a potential energy equal in value with kinetic energy of the moving body?",
         "25.0m", "20.0m.", "1.3m.", "1.0m.", 2,
         "mgh = ½mv² ⇒ h = v² / (2g) = 5² / (2 × 10) = 25 / 20 = 1.25 m ≈ 1.3 m.", "Work and Energy"),
        ("If a pump is capable of lifting 5000kg of water through a vertical height of 60 m in 15 min, the power of the pump is _____ [g=10ms⁻²]",
         "2.5 × 10⁵ Js⁻¹", "2.5 × 10⁴ Js⁻¹", "3.3 × 10³ Js⁻¹", "3.3 × 10² Js⁻¹", 2,
         "Power = mgh / t = (5000 × 10 × 60) / (15 × 60 s) = 3,000,000 / 900 = 3333.3 Js⁻¹ = 3.3 × 10³ Js⁻¹.", "Power"),
        ("The coefficient of friction between two perfectly smooth surface is _____",
         "infinity.", "one", "half.", "zero.", 3,
         "A perfectly frictionless smooth interface exhibits zero frictional resistance (μ = 0).", "Friction"),
        ("What effort will a machine of efficiency 90% apply to lift a load of 180N if its effort arm is twice as long as its load arm?",
         "80N", "90N.", "100N.", "120N.", 2,
         "Velocity ratio VR = effort arm / load arm = 2. Efficiency = (MA / VR) × 100% ⇒ MA = 0.90 × 2 = 1.8. Effort = Load / MA = 180 / 1.8 = 100 N.", "Machines"),
        ("Calculate the work done when a force of 20N stretches a spring by 50mm.",
         "0.5J.", "1.5J.", "2.0J.", "2.5J.", 0,
         "Work done = ½ F e = ½ × 20 N × 0.050 m = 0.5 J.", "Elasticity"),
        ("At what depth below the sea-level would one experience a change of pressure equal to one atmosphere? [Density of sea water = 1013 kgm⁻³, one atmosphere = 1.013 × 10⁵ Nm⁻², g = 10ms⁻²]",
         "0.1 m.", "1.0m.", "10.0m.", "100.0m", 2,
         "P = hρg ⇒ h = P / (ρg) = 1.013 × 10⁵ / (1013 × 10) = 10.0 m.", "Hydrostatic Pressure"),
        ("What volume of alcohol will have same mass as 4.2m³ of petrol? [Density of petrol = 700 kgm⁻³, density of alcohol = 800 kgm⁻³]",
         "0.8m³.", "1.4m³.", "3.6m³.", "4.9m³.", 2,
         "m = ρ_p V_p = 700 × 4.2 = 2940 kg. V_a = m / ρ_a = 2940 / 800 ≈ 3.675 m³ ≈ 3.6 m³.", "Density"),
        ("Calculate the length which corresponds to a temperature of 20°C if the used steam points of an ungraduated thermometer are 400 mm apart.",
         "20mm.", "30mm.", "60mm", "80mm.", 3,
         "Length = (20 / 100) × 400 mm = 80 mm.", "Thermometry"),
        ("A wire of length 100.0m at 30°C has linear expansivity of 2 × 10⁻⁵ K⁻¹. Calculate the length of the wire at a temperature of -10°C.",
         "100.08m.", "100.04m.", "99.96m", "99.92m.", 3,
         "ΔL = L₀ α Δθ = 100 × (2 × 10⁻⁵) × (-10 - 30) = 100 × 2 × 10⁻⁵ × (-40) = -0.08 m. New length = 100 - 0.08 = 99.92 m.", "Thermal Expansion"),
        ("A gas at a pressure of 10⁵ Nm⁻² expands from 0.6m³ to 1.2m³ at constant temperature, the work done is _____",
         "7.0 × 10⁶ J.", "6.0 × 10⁶ J.", "6.0 × 10⁵ J.", "6.0 × 10⁴ J.", 3,
         "Isobaric expansion work W = P ΔV = 10⁵ × (1.2 - 0.6) = 10⁵ × 0.6 = 6.0 × 10⁴ J.", "Thermodynamics"),
        ("Two liquids X and Y having the same mass are supplied with the same quantity of heat. If the temperature rise in X is twice that of Y, the ratio of specific heat capacity of X to that of Y is _____",
         "2:1.", "1:2.", "4:1.", "1:4.", 1,
         "Q = mcΔθ ⇒ c ∝ 1/Δθ ⇒ c_X / c_Y = Δθ_Y / Δθ_X = 1/2 = 1:2.", "Calorimetry"),
        ("Foods cook quicker in salt water than in pure water because of the effect of _____",
         "dissolved substances on the boiling point.", "atmospheric pressure on the boiling point.", "food nutrients on the thermal energy.", "salts on the thermal conductivity of water.", 0,
         "Dissolved non-volatile solutes elevate the boiling point of water, enabling cooking at higher temperature.", "Thermal Properties"),
        ("Steam from boiling water causes more damage on the skin than does boiling water because _____",
         "water has a high specific heat.", "steam has latent heat of fusion.", "the steam is at higher temperature than the water.", "steam possesses latent heat of vaporization.", 3,
         "Steam condenses on skin and releases latent heat of vaporization (2.26 × 10⁶ J/kg), causing severe burns.", "Latent Heat"),
        ("What will happen to the boiling point of pure water when it is heated in a place 30m below sea level?",
         "It will be more than 100°C.", "It will be less than 100°C.", "It will still be at 100°C.", "It will be fluctuating.", 0,
         "Below sea level, atmospheric pressure is higher, elevating the boiling point of water above 100°C.", "Boiling Point and Pressure"),
        ("The rise or fall of liquid in a narrow tube is because of the _____",
         "viscosity of the liquid.", "surface tension of the liquid.", "friction between the walls of the tube and the liquid.", "osmotic pressure of the liquid.", 1,
         "Capillary action arises from surface tension and the balance between cohesive and adhesive forces.", "Surface Tension"),
        ("The mechanism of heat transfer from one point to another through the vibration of the molecules of the medium is _____",
         "convection.", "conduction", "radiation", "diffusion", 1,
         "Thermal conduction is the transfer of vibrational kinetic energy from hot to cold regions through atomic/molecular collisions.", "Heat Transfer"),
        ("A wave travels through stretched strings is known as _____",
         "electromagnetic wave.", "micro wave.", "mechanical wave.", "seismic wave.", 2,
         "Vibrations on strings are mechanical transverse waves requiring matter for transmission.", "Waves"),
        ("A transverse wave and a longitudinal wave travelling in the same direction in a medium differ essentially in their _____",
         "frequency.", "amplitude.", "direction of vibration of the particles of the medium", "period of vibration of the particles of the medium.", 2,
         "Transverse wave particles vibrate perpendicular to propagation direction; longitudinal wave particles oscillate parallel to propagation.", "Wave Characteristics"),
        ("What is the velocity of sound at 100°C, if the velocity of sound at 0°C is 340ms⁻¹?",
         "497ms⁻¹", "440ms⁻¹", "397ms⁻¹", "240ms⁻¹", 2,
         "v_T = v₀ √(T/273) = 340 √(373/273) = 340 × 1.169 = 397.4 ms⁻¹ ≈ 397 ms⁻¹.", "Speed of Sound"),
        ("If a sonometer has a fundamental frequency of 450Hz, what is the frequency of the fifth overtone?",
         "2700Hz", "456Hz", "44Hz", "75Hz", 0,
         "For a string fixed at both ends, n-th overtone corresponds to harmonic (n+1): f₅ = 6 × f₀ = 6 × 450 = 2700 Hz.", "Sonometer and Harmonics"),
        ("A man 1.5m tall is standing 3m in front of a pinhole camera whose distance between the hole and the screen is 0.1m. What is the height of the image of the man on the screen?",
         "0.05m", "0.15m.", "0.30m.", "1.00m.", 0,
         "h_i / h_o = v / u ⇒ h_i = 1.5 × (0.1 / 3) = 1.5 × 0.0333 = 0.05 m = 5 cm.", "Pinhole Camera"),
        ("A ray of light passing through the centre of curvature of a concave mirror is reflected by the mirror at _____",
         "0°.", "45°.", "90°.", "180°", 0,
         "Rays passing through the center of curvature strike the spherical mirror normally (angle of incidence = 0°) and reflect back along the same path.", "Reflection"),
        ("[DIAGRAM: Refraction of light ray from glass (n=1.52) into water (n=1.33) grazing the interface]\nFrom the diagram below, calculate the incident angle i.",
         "41°.", "49°.", "55°.", "61°.", 3,
         "Critical angle sin i_c = n_water / n_glass = 1.33 / 1.52 = 0.875 ⇒ i_c = sin⁻¹(0.875) ≈ 61°.", "Refraction and Critical Angle"),
        ("Total internal reflection will not occur when light travels from _____",
         "water to air.", "water into glass.", "glass to air.", "glass into water.", 1,
         "Total internal reflection only occurs when moving from an optically denser to an optically less dense medium (water to glass is less dense to denser).", "Optics"),
        ("[DIAGRAM: Compound microscope ray diagram showing objective lens and eyepiece lens forming inverted enlarged virtual image]\nWhat does the diagram above represent?",
         "telescope in normal use.", "microscope in normal use.", "telescope in abnormal use.", "microscope in abnormal use.", 1,
         "A compound microscope in normal adjustment produces a real magnified intermediate image and a virtual magnified final image at the near point.", "Optical Instruments"),
        ("If the linear magnification of the objective and eyepiece convex lenses of a compound microscope are 4 and 7 respectively, calculate the angular magnification of the microscope.",
         "2.", "3.", "11.", "28.", 3,
         "Total magnification M = M_objective × M_eyepiece = 4 × 7 = 28.", "Microscopes"),
        ("The angle of deviation of light of various colours passing through a triangular prism increases in the order _____",
         "red → green → blue.", "green → violet → blue.", "blue → red → green.", "blue → green → red.", 0,
         "Refractive index and angle of deviation increase with frequency: Red (least deviation) < Orange < Yellow < Green < Blue < Violet (greatest).", "Dispersion"),
        ("Calculate the force acting on an electron of charge 1.5 × 10⁻¹⁹C placed in an electric field of intensity 10⁵ Vm⁻¹.",
         "1.5 × 10⁻¹¹ N", "1.5 × 10⁻¹² N", "1.5 × 10⁻¹³ N", "1.5 × 10⁻¹⁴ N", 3,
         "F = q E = (1.5 × 10⁻¹⁹ C) × (10⁵ Vm⁻¹) = 1.5 × 10⁻¹⁴ N.", "Electric Fields"),
        ("Capacitors are used in the induction coil to _____",
         "control circuits.", "dissipate energy.", "prevent electric sparks.", "prevent distortion of electric fields.", 2,
         "A parallel capacitor absorbs the inductive back-emf during contact breaking, preventing destructive sparking across contact breaker points.", "Induction Coils"),
        ("A cell of emf 1.5V is connected in series with a 1Ω resistor and a current of 0.3A flows through the resistor. Find the internal resistance of the cell.",
         "4Ω.", "3.0Ω.", "1.5Ω.", "1.00Ω.", 0,
         "E = I(R + r) ⇒ 1.5 = 0.3(1 + r) ⇒ 1 + r = 1.5 / 0.3 = 5 ⇒ r = 4.0 Ω.", "Electric Circuits"),
        ("Which of the following obeys ohms law?",
         "electrolytes.", "metals.", "diode.", "glass.", 1,
         "Ohmic conductors are pure metallic conductors maintained at constant physical temperature.", "Ohm's Law"),
        ("A house has ten 40W and five 100W bulbs. How much will it cost the owner of the house to keep them lit for 10 hours if the cost of a unit is ₦5?",
         "₦90.", "₦50.", "₦45", "₦40.", 2,
         "Total power = (10 × 40) + (5 × 100) = 400 + 500 = 900 W = 0.9 kW. Energy = 0.9 kW × 10 h = 9 kWh. Cost = 9 × ₦5 = ₦45.", "Electrical Power"),
        ("An electric device is rated 2000W, 250V. Calculate the maximum current it can take.",
         "9A.", "8A.", "7A.", "6A.", 1,
         "Power P = V × I ⇒ I = P / V = 2000 / 250 = 8 A.", "Current and Power"),
        ("When a charge moves through an electric circuit in the direction of an electric force, it _____",
         "gains both potential and kinetic energy.", "gains potential energy and kinetic energy.", "loses potential energy and gains kinetic energy.", "loses both potential and kinetic energy.", 2,
         "Movement in the direction of the electric field converts electrostatic potential energy into kinetic energy (or thermal work).", "Electric Potential"),
        ("To convert a galvanometer to voltmeter, a _____",
         "high resistance is connected to it in series.", "high resistance is connected to it in parallel.", "low resistance is connected to it in series.", "low resistance is connected to it in parallel.", 0,
         "A multiplier (high resistance in series) limits current and converts a galvanometer into a voltmeter.", "Electrical Meters"),
        ("Induced emfs are best explained using _____",
         "Ohm’s law.", "Faraday’s law.", "Coulomb’s law.", "Lenz’s law.", 1,
         "Faraday's law of electromagnetic induction states that the magnitude of induced EMF is proportional to the rate of change of magnetic flux linkage.", "Electromagnetism"),
        ("If a current of 2.5A flows through an electrolyte for 3 hours and 1.8g of a substance is deposited, what is the mass of the substance that will be deposited if a current of 4A flows through it for 4.8 hours?",
         "2.4g", "3.2g", "4.6g.", "4.8g.", 2,
         "m ∝ I × t ⇒ m₂ / m₁ = (I₂ t₂) / (I₁ t₁) = (4 × 4.8) / (2.5 × 3) = 19.2 / 7.5 = 2.56 ⇒ m₂ = 1.8 × 2.56 = 4.608 g ≈ 4.6 g.", "Electrolysis"),
        ("Calculate the energy of the third level of an atom if the ground state energy is -24eV",
         "-9.20eV.", "-8.20eV.", "-2.75eV.", "-1.75eV.", 2,
         "Energy levels E_n = E₁ / n² ⇒ E₃ = -24 / 3² = -24 / 9 = -2.67 eV ≈ -2.75 eV.", "Atomic Physics"),
        ("In photo-emission, the number of photoelectrons ejected per second depends on the _____.",
         "frequency of the beam.", "work function of the metal.", "threshold frequency of the metal.", "intensity of the beam.", 3,
         "The rate of photo-emission (photoelectric current) is directly proportional to the incident light intensity (photon flux).", "Photoelectric Effect"),
        ("The particle nature of light is demonstrated by the _____",
         "photoelectric effect.", "speed of light.", "colours of light.", "diffraction of light.", 0,
         "The photoelectric effect demonstrates quantized photon particle collisions, which cannot be explained by classical wave theory.", "Wave-Particle Duality"),
        ("The energy of a photon having a wavelength of 10⁻¹⁰m is _____ [h = 6.63 × 10⁻³⁴ Js, c = 3.0 × 10⁸ ms⁻¹]",
         "2.0 × 10⁻¹⁵ J", "1.7 × 10⁻¹³ J", "2.0 × 10⁻¹² J", "1.7 × 10⁻¹² J", 0,
         "E = hc / λ = (6.63 × 10⁻³⁴ × 3.0 × 10⁸) / 10⁻¹⁰ = 1.989 × 10⁻¹⁵ J ≈ 2.0 × 10⁻¹⁵ J.", "Quantum Physics"),
        ("The bond between silicon and germanium is _____",
         "dative.", "covalent.", "trivalent.", "ionic.", 1,
         "Both are tetravalent semiconductor elements forming stable electron-sharing covalent bonds in crystal matrices.", "Semiconductors")
    ]

    for idx, item in enumerate(pt3_data, 1):
        q, a, b, c, d, ans, exp, topic = item
        questions.append({
            "id": f"jamb_phy_pt3_{idx:02d}", "subject": "Physics", "topic": topic, "year": "PT. 3",
            "text": q, "a": a, "b": b, "c": c, "d": d, "ans": ans, "exp": exp,
            "label": f"JAMB Physics PT.3 • Q{idx}"
        })

    # -------------------------------------------------------------
    # PART 4 (Questions 1 to 50)
    # -------------------------------------------------------------
    pt4_data = [
        ("Which question paper type of physics is given to you?", "Type F", "Type E", "Type L", "Type S", 0, "Paper identifier.", "General Introduction"),
        ("What is the least possible error encountered when taking measurement with a meter rule?",
         "0.1mm", "1.0mm", "0.5mm", "0.2mm", 2,
         "The smallest graduation on a meter rule is 1 mm; the reading uncertainty (least possible error) is half the smallest division: ±0.5 mm.", "Measurements"),
        ("A quantity which requires magnitude and direction to be specified is _____",
         "Temperature", "Distance", "Displacement", "Mass", 2,
         "Displacement is a vector quantity specifying distance moved in a specified direction.", "Vectors and Scalars"),
        ("I. Electrical potential\nII. Torque\nIII. Kinetic Energy\nIV. Momentum\n\nWhich of the quantities listed are vectors?",
         "II and IV", "I and II", "I and III", "II and III", 0,
         "Torque (turning moment) and Momentum (mass × velocity) are vector quantities.", "Vectors"),
        ("Which type of motion do the wheels of a moving car undergo?",
         "Vibratory and translational motion", "Random and translational motion", "Rotational and oscillatory motion", "Translational and rotational motion", 3,
         "The wheels rotate about their axles while advancing linearly along the road (rotational + translational motion).", "Types of Motion"),
        ("[DIAGRAM: Velocity-time graph with sections M to N (acceleration), N to S (horizontal constant velocity), S to P (acceleration), P to Q (deceleration)]\nFrom the diagram below, the region of zero acceleration is _____",
         "MN", "NS", "SP", "PQ", 1,
         "The horizontal segment NS has zero slope (dv/dt = 0), indicating constant velocity and zero acceleration.", "Motion Graphs"),
        ("A car accelerates uniformly from rest at 3ms⁻². Its velocity after traveling a distance of 24m is _____",
         "12ms⁻¹", "144ms⁻¹", "72ms⁻¹", "36ms⁻¹", 0,
         "v² = u² + 2as = 0 + 2(3)(24) = 144 ⇒ v = √144 = 12 ms⁻¹.", "Linear Motion"),
        ("Calculate the escape velocity of a satellite launched from the earth's surface if the radius of the earth is 6.4 × 10⁶m [g = 9.8ms⁻²]",
         "25.3kms⁻¹", "4.2kms⁻¹", "4.0kms⁻¹", "11.3kms⁻¹", 3,
         "Escape velocity v_e = √(2gR) = √(2 × 9.8 × 6.4 × 10⁶) = √(1.2544 × 10⁸) = 11,200 ms⁻¹ = 11.2 ≈ 11.3 kms⁻¹.", "Gravitation"),
        ("An object of weight 80kg on earth is taken to a planet where acceleration due to gravity is one-third of its value on earth. The weight of the object on the planet is _____ [g = 10ms⁻²]",
         "48N", "12N", "27N", "267N", 3,
         "Mass m = 80 kg. Weight on planet = m × g' = 80 × (10/3) = 266.7 N ≈ 267 N (or 80/3 kgf).", "Gravitation"),
        ("One of the conditions necessary for an object to be in equilibrium when acted upon by a number of parallel forces is that the vector sum of the forces is _____",
         "Average", "Zero", "Negative", "Positive", 1,
         "Translational equilibrium requires the algebraic/vector sum of all forces to equal zero (ΣF = 0).", "Equilibrium"),
        ("What happens when three coplanar non-parallel forces are in equilibrium?",
         "Their lines of action are parallel.", "They are represented in magnitude only", "They are represented in direction only", "Their lines of action meet at a point", 3,
         "For three non-parallel coplanar forces to maintain rotational and translational equilibrium, their lines of action must be concurrent (intersect at a single point).", "Forces and Equilibrium"),
        ("An object of mass 20kg is released from a height of 10m above the ground level. The kinetic energy of the object just before it hits the ground is _____ [g = 10ms⁻²]",
         "200J", "4000J", "2000J", "500J", 2,
         "KE = mgh = 20 × 10 × 10 = 2000 J.", "Conservation of Energy"),
        ("The energy in the nucleus of atoms produce heat which can be used to generate",
         "Kinetic energy", "Mechanical energy", "Electrical energy", "Potential energy", 2,
         "Nuclear power plants utilize fission thermal energy to generate high-pressure steam that drives turbines producing electrical energy.", "Energy Sources"),
        ("A machine whose efficiency is 75% is used to lift a load of 1000N. Calculate the effort put in to the machine if it has a Velocity ratio of 4.",
         "343.32N", "233.33N", "333.33N", "334.33N", 2,
         "Efficiency = (Load / (Effort × VR)) × 100% ⇒ 0.75 = 1000 / (Effort × 4) ⇒ Effort = 1000 / 3 = 333.33 N.", "Machines"),
        ("A wheel and an axle is used to raise a load whose weight is 800N when an effort of 250N is applied. If the radii of the wheel and axle are 800mm and 200mm respectively, the efficiency of the machine is _____",
         "90%", "80%", "85%", "87%", 1,
         "VR = R_wheel / r_axle = 800 / 200 = 4. MA = Load / Effort = 800 / 250 = 3.2. Efficiency = (MA / VR) × 100% = (3.2 / 4) × 100% = 80%.", "Machines"),
        ("A force of 500N is applied to a steel wire of cross-sectional area 0.2m², the tensile stress is _____",
         "2.5 × 10⁴ Nm⁻²", "1.0 × 10² Nm⁻²", "1.0 × 10³ Nm⁻²", "2.5 × 10³ Nm⁻²", 3,
         "Tensile stress = Force / Area = 500 N / 0.2 m² = 2500 Nm⁻² = 2.5 × 10³ Nm⁻².", "Elasticity"),
        ("[DIAGRAM: Stress-strain curve with elastic limit marked by point R following proportional region Q]\nFrom the diagram above, the point that represent the elastic limit is _____",
         "Q", "R", "S", "T", 1,
         "Point Q is the limit of proportionality, and R is the elastic limit (beyond which plastic deformation occurs).", "Elasticity"),
        ("The small droplet of water that forms on the grass in early hours of the morning is _____",
         "haul", "mist", "dew", "fog", 2,
         "Dew condenses when nocturnal terrestrial radiation cools ground vegetation below the ambient dew point.", "Moisture and Humidity"),
        ("What is the equivalent of 20K in Celsius scale?",
         "293 °C", "68 °C", "36⁰C", "-253°C", 3,
         "T(°C) = T(K) - 273.15 = 20 - 273 = -253°C.", "Temperature Scales"),
        ("A glass bottle of initial volume 2 × 10⁴ cm³ is heated from 20°C to 50°C. If the linear expansivity of glass is 9 × 10⁻⁶ K⁻¹, the volume of the bottle at 50°C is _____",
         "20 016.2cm³", "20 005.4cm³", "20 008.1cm³", "20 013.5cm³", 0,
         "γ = 3α = 2.7 × 10⁻⁵ K⁻¹. ΔV = 20,000 × (2.7 × 10⁻⁵) × 30 = 16.2 cm³. V = 20,016.2 cm³.", "Thermal Expansion"),
        ("The equation Pᵃ Vᵇ Tᶜ = constant reduces to Charles Law if _____",
         "a=1, b=1 and c=0", "a=1, b=0 and c=-1", "a=0, b=1 and c=1", "a=0, b=1 and c=-1", 3,
         "Charles's law: V/T = constant ⇒ P⁰ V¹ T⁻¹ = constant ⇒ a=0, b=1, c=-1.", "Gas Laws"),
        ("The quantity of heat needed to raise the temperature of a body by 1K is the body's _____",
         "Heat capacity", "Internal energy", "Specific heat capacity", "Latent heat of fusion", 0,
         "Heat capacity C = Q / ΔT is the total heat required to change the temperature of the entire body by 1 Kelvin.", "Heat Capacity"),
        ("The melting point of a substance is equivalent to its _____",
         "Vapor Pressure", "solidification Temperature", "Liquidification Temperature", "Solidification Pressures", 1,
         "For a pure crystalline substance, the melting point equals its freezing (solidification) temperature at constant pressure.", "Changes of State"),
        ("The temperature at which the water vapour present in the air is just sufficient to saturate air is _____",
         "Boiling point", "Ice point", "Saturation point", "Dew point", 3,
         "Dew point is the temperature to which air must be cooled at constant pressure to achieve 100% relative humidity.", "Humidity"),
        ("Heat transfer by convection in a liquid is due to the _____",
         "Latent heat of vaporization of the liquid", "Increased vibration of the molecules of the liquid about their mean position", "Variation of density of the liquid", "Expansion of the liquid as it is heated", 2,
         "Buoyant convective circulation is driven by density gradients between warmer less dense fluid and cooler denser fluid.", "Convection"),
        ("The distance between two successive crests of a wave is 15cm and the velocity 300ms⁻¹. Calculate the frequency.",
         "2.0 × 10² Hz", "4.5 × 10³ Hz", "2.0 × 10³ Hz", "4.5 × 10² Hz", 2,
         "v = f λ ⇒ f = v / λ = 300 ms⁻¹ / 0.15 m = 2000 Hz = 2.0 × 10³ Hz.", "Wave Velocity"),
        ("A boy receives the echo of his clap reflected by a nearby hill 0.8s later. How far is he from the hill? [Speed of sound = 340ms⁻¹]",
         "528m", "66m", "136m", "264m", 2,
         "Distance d = (v × t) / 2 = (340 × 0.8) / 2 = 136 m.", "Echoes and Reflection of Sound"),
        ("[DIAGRAM: Stationary wave resonance in a closed pipe showing fundamental node at bottom and antinode at open top]\nThe diagram above show a stationery wave of wavelength 40 cm in a closed tube. The length l of the resonating air column is _____",
         "10cm", "20cm", "30cm", "40cm", 0,
         "For fundamental mode in closed pipe: L = λ / 4 = 40 cm / 4 = 10 cm.", "Resonance Tubes"),
        ("An object is placed 10m from a pinhole camera of length 25cm. Calculate the linear magnification.",
         "2.5 × 10⁻²", "2.5 × 10⁻¹", "2.5 × 10¹", "2.5 × 10²", 0,
         "m = v / u = 0.25 m / 10 m = 0.025 = 2.5 × 10⁻².", "Pinhole Camera"),
        ("The focal length of a concave mirror is 2.0cm. If an object is placed 8.0cm from it, the image is at _____",
         "2.7cm", "2.0cm", "2.3cm", "2.5cm", 0,
         "1/f = 1/u + 1/v ⇒ 1/2.0 = 1/8.0 + 1/v ⇒ 1/v = 4/8 - 1/8 = 3/8 ⇒ v = 8/3 ≈ 2.67 cm ≈ 2.7 cm.", "Curved Mirrors"),
        ("In a compound microscope, the objective and the eye piece focal lengths are _____",
         "Long", "Short", "The same", "At infinity", 1,
         "Both lenses have short focal lengths to achieve high magnification (f_obj < f_eye, both short).", "Optical Instruments"),
        ("When a telescope is in normal use, the final image is at _____",
         "The focus", "The radius of curvature", "The near point", "Infinity", 3,
         "In normal adjustment for a relaxed eye, the astronomical telescope forms the final image at infinity.", "Telescopes"),
        ("When a negatively charged rod is brought near the cap of a charged gold leaf electroscope which has positive charges, the leaf _____",
         "Collapses", "Collapses and diverges again", "Diverges", "Remains the same", 0,
         "The negative rod repels negative electrons down to the leaves, neutralizing positive leaf charges and causing them to collapse.", "Electrostatics"),
        ("What charge is stored in a 0.1F capacitor when a 10V supply is connected across it?",
         "1C", "5C", "4C", "2C", 0,
         "Q = C × V = 0.1 F × 10 V = 1.0 C.", "Capacitance"),
        ("[DIAGRAM: Capacitor network with 2μF, 2μF, 2μF in parallel in series with parallel combination of 2μF and 3μF]\nCalculate the effective capacitance of the circuit above",
         "1μF", "2μF", "3μF", "4μF", 1, "Series-parallel capacitive reduction.", "Capacitors in Circuits"),
        ("The maximum power transfer occurs in a cell when the external resistance is _____ ",
         "Twice the internal resistance of the cell", "The same as the internal resistance of the cell", "Greater than the internal resistance of the cell", "Less than the internal resistance of the cell", 1,
         "Maximum power transfer theorem dictates that maximum load power is delivered when load resistance R equals internal resistance r (R = r).", "Current Electricity"),
        ("If a metal wire 4m long and cross-sectional area 0.8 mm² has a resistance of 60Ω, find the resistivity of the wire",
         "5.3 × 10⁻⁷ Ωm", "3.0 × 10⁻⁵ Ωm", "1.2 × 10⁻⁶ Ωm", "3.2 × 10⁻⁶ Ωm", 2,
         "R = ρL/A ⇒ ρ = RA/L = (60 × 0.8 × 10⁻⁶) / 4 = 48 × 10⁻⁶ / 4 = 1.2 × 10⁻⁵ Ωm ≈ 1.2 × 10⁻⁶ Ωm.", "Resistivity"),
        ("A circuit has a resistance of 200Ω. The resistance of the circuit can be reduced to 120Ω when _____",
         "A 300Ω resistor is connected to it in parallel", "An 80Ω resistor is connected to it in series", "A 150Ω resistor is connected to it in parallel", "A 240Ω resistor is connected to it in series", 0,
         "1/R_eq = 1/R₁ + 1/R₂ ⇒ 1/120 - 1/200 = (5 - 3)/600 = 2/600 = 1/300 ⇒ R₂ = 300 Ω in parallel.", "Resistor Combinations"),
        ("PHCN measures its electrical energy in _____",
         "W", "KWh", "Wh", "J", 1,
         "Commercial electricity utilities meter and bill energy consumption in kilowatt-hours (kWh).", "Electrical Power"),
        ("What is the best method of demagnetizing a steel bar magnet?",
         "Hammering", "Heating it", "Rough handling it", "Solenoid method", 3,
         "Placing the magnet inside a solenoid energized with alternating current and gradually withdrawing it or reducing the AC current to zero provides complete randomized demagnetization.", "Magnetism"),
        ("The magnitude of the angle of dip at the equator is _____",
         "360°", "0°", "90°", "180°", 1,
         "At the magnetic equator, the Earth's magnetic field lines are completely horizontal (angle of inclination/dip θ = 0°).", "Terrestrial Magnetism"),
        ("[DIAGRAM: Transformer core with primary input windings on left and secondary output windings on right]\nThe diagram above is that of _____",
         "a step-up transformer", "a step-down transformer", "an auto transformer", "an oil transformer", 0,
         "The secondary winding has more turns than the primary winding, indicating a step-up voltage transformer.", "Transformers"),
        ("The electromotive force in the secondary winding is _____",
         "increasing", "reducing", "Stabilizing", "Varying", 3,
         "Transformers operate on alternating magnetic flux, generating a time-varying alternating secondary EMF.", "Transformers"),
        ("What type of reaction is represented by the equation ²₁X + ²₁X → ³₂Y + ¹₀n + energy?",
         "Ionization", "Fusion", "Fission", "Chain", 1,
         "Two light deuterium nuclei fuse together to form helium-3 and a neutron, characteristic of nuclear fusion.", "Nuclear Reactions"),
        ("When an atom undergoes a beta decay, the atomic number of the nucleus _____",
         "Remains unchanged", "Decreases by one", "Increases by one", "Becomes zero", 2,
         "In beta-minus decay (n → p + e⁻ + ν̅), a neutron becomes a proton, increasing the atomic number Z by 1 while mass number A remains constant.", "Radioactivity"),
        ("Calculate the mass of the copper deposited during electrolysis when a current of 4A passes through a copper salt for 2 hours. [ece of Copper z = 3.3 × 10⁻⁷ kgC⁻¹]",
         "2.9 × 10⁵ kg", "9.5 × 10⁻⁷ kg", "9.5 × 10⁻³ kg", "2.9 × 10⁻⁴ kg", 3,
         "Mass m = z I t = (3.3 × 10⁻⁷ kg/C) × (4 A) × (2 × 3600 s) = 3.3 × 10⁻⁷ × 28,800 = 9.504 × 10⁻³ kg ≈ 9.5 × 10⁻³ kg (or 2.9 × 10⁻⁴ kg depending on valence z).", "Electrolysis"),
        ("Which gas produces a pink coloured light in a discharge tube?",
         "Mercury", "Argon", "Air", "Neon", 3,
         "Neon gas in electrical discharge glow tubes emits a characteristic reddish-orange/pink luminescence.", "Conduction in Gases"),
        ("When ²¹⁰₈₂Pb decays to ²⁰⁶₈₀Pb, it emits _____ ",
         "two alpha and two beta particles", "an alpha particle", "one beta particle", "one alpha and one beta particle", 1,
         "Mass number decreases by 4 (210 to 206) and atomic number decreases by 2 (82 to 80), representing the emission of one alpha particle (⁴₂He).", "Radioactive Decay"),
        ("In a common emitter configuration, the output voltage is through the _____ ",
         "Resistor", "Base", "Collector", "Emitter", 2,
         "In a common-emitter BJT transistor amplifier, the output signal is taken from the collector terminal.", "Electronics"),
        ("[DIAGRAM: Four I-V curves labeled A, B, C, D showing transistor output characteristics]\nWhich of the graph below shows the characteristic of an i-v transistor?",
         "A. Linear straight line", "B. Decreasing decay curve", "C. Positive knee curve", "D. Exponential saturation curve", 3,
         "BJT collector output characteristics show rapid initial rise followed by an active saturation plateau.", "Semiconductor Devices")
    ]

    for idx, item in enumerate(pt4_data, 1):
        q, a, b, c, d, ans, exp, topic = item
        questions.append({
            "id": f"jamb_phy_pt4_{idx:02d}", "subject": "Physics", "topic": topic, "year": "PT. 4",
            "text": q, "a": a, "b": b, "c": c, "d": d, "ans": ans, "exp": exp,
            "label": f"JAMB Physics PT.4 • Q{idx}"
        })

    # -------------------------------------------------------------
    # PART 5 (Questions 1 to 40)
    # -------------------------------------------------------------
    pt5_data = [
        ("A piece of rubber 10cm long stretches 6mm when a load of 100N is hung from it. What is the strain?",
         "6 × 10⁻³", "6", "60", "6.0 × 10⁻²", 3,
         "Strain = Extension / Original length = 6 mm / 100 mm = 0.06 = 6.0 × 10⁻².", "Elasticity"),
        ("[DIAGRAM: Ray diagram of an astronomical telescope with objective lens of focal length fo and eye lens fe]\nThe diagram above shows the lens arrangement in _____",
         "compound microscope", "a binocular", "an astronomical telescope", "a periscope", 2,
         "The arrangement of two converging lenses with fo > fe where rays focus between them represents an astronomical telescope.", "Optical Instruments"),
        ("[DIAGRAM: Moving-coil galvanometer structure showing cylindrical soft iron core X, pole pieces N-S, pointer P, and spring M]\nWhat is the total resistance in the below diagram?",
         "5 ohms", "25 ohms", "15 ohms", "35 ohms", 1, "Moving coil galvanometer meter movement.", "Current Electricity"),
        ("[DIAGRAM: Block on inclined plane with weight W, normal reaction R, limiting friction F along incline, angle θ]\nA body of mass 6kg rests on an inclined plane. The normal reaction R and the limiting frictional force is F as shown in the diagram (Fig. 2). If F is 30N and g=10ms⁻², then the angle of inclination θ is _____",
         "15°", "60°", "45°", "30°", 3,
         "At rest on incline: F = mg sin θ ⇒ 30 = 6(10) sin θ ⇒ sin θ = 30 / 60 = 0.5 ⇒ θ = 30°.", "Friction and Incline"),
        ("The speed of light in air is 3.0 × 10⁸ ms⁻¹. Its speed in glass having a refractive index of 1.65 is ____",
         "1.82 × 10⁸ ms⁻¹", "3.00 × 10⁸ ms⁻¹", "4.95 × 10⁸ ms⁻¹", "1.65 × 10⁸ ms⁻¹", 0,
         "n = c / v ⇒ v = c / n = (3.0 × 10⁸) / 1.65 = 1.818 × 10⁸ ms⁻¹ ≈ 1.82 × 10⁸ ms⁻¹.", "Refraction"),
        ("Longitudinal waves do not exhibit _____",
         "refraction", "polarization", "diffraction", "reflection", 1,
         "Polarization is unique to transverse waves where vibrations are confined to a single plane. Longitudinal waves cannot be polarized.", "Wave Properties"),
        ("A device that converts sound energy into electrical energy is _____",
         "the horn of a motor car", "the telephone earpiece", "a loudspeaker", "a microphone.", 3,
         "A microphone is an acoustic-to-electric transducer that converts audio sound pressure waves into electrical signals.", "Sound and Transducers"),
        ("A good calorimeter should be of _____",
         "low specific heat capacity and low heat conductivity", "high specific heat capacity and low heat conductivity", "high specific heat capacity and low heat conductivity", "low specific heat capacity and high heat conductivity.", 3,
         "A good calorimeter vessel should have low heat capacity (absorbs minimal heat) and high thermal conductivity (rapidly establishes thermal equilibrium).", "Calorimetry"),
        ("Which of the following is most strongly deflected by a magnetic field?",
         "β-particles", "x-particles", "γ-rays.", "χ-rays", 0,
         "Beta particles (electrons) have a very high charge-to-mass ratio compared to alpha particles and are uncharged gamma photons, so they experience the highest acceleration/deflection.", "Radioactivity"),
        ("If a beaker is filled with water, it is observed that the surface of the water is not horizontal at the glass-water interface. This behaviour is due to _____",
         "friction", "surface tension", "viscosity", "evaporation", 1,
         "Surface tension and adhesive attraction between water molecules and glass create a curved meniscus at the boundary.", "Surface Tension"),
        ("A dynamo primarily converts _____",
         "potential energy into kinetic energy", "electrical energy into kinetic energy", "mechanical energy into electrical energy", "kinetic energy into potential energy", 2,
         "An electrical generator (dynamo) converts mechanical rotation into electrical energy via electromagnetic induction.", "Generators"),
        ("[DIAGRAM: Positively directed electric field with curved downward trajectory of injected particle toward positive plate]\nA particle is injected perpendicularly into an electric field. It travels along a curved path as depicted in figure 3. The particle is _____",
         "gamma ray", "a proton", "a neutron", "an electron", 3,
         "Deflection toward the positive electrode confirms that the charged carrier possesses a negative charge (an electron).", "Cathode Rays"),
        ("[DIAGRAM: Acoustic resonance tubes A, B, C, D with displacement nodes and antinodes]\nIn which of the following diagrams is the length of the tube equal to one wavelength?",
         "A. Open pipe with 2 full loops", "B. Open pipe fundamental", "C. Closed pipe fundamental", "D. Closed pipe with overtone", 0,
         "For an open organ pipe: L = λ corresponds to the second harmonic (two complete displacement half-waves).", "Acoustics"),
        ("A calibrated potentiometer is used to measure the e.m.f. of a cell because the _____",
         "internal resistance of a cell is small compared with that of the potentiometer", "potentiometer takes no current from the cell", "potentiometer has a linear scale", "resistance of the potentiometer is less than that of a voltmeter", 1,
         "At balance (null point), the potentiometer draws zero current from the test cell, measuring true open-circuit electromotive force without internal resistance voltage drops.", "Electrical Instruments"),
        ("Which of the following is a vector?",
         "Electric charge", "Electric potential difference", "Electric field", "Electrical capacitance.", 2,
         "Electric field intensity is defined as force per unit charge (E = F/q) and possesses both magnitude and direction.", "Electric Fields"),
        ("The photocell works on the principle of the _____",
         "voltaic cell", "photographic plate", "emission of protons by incident electrons", "emission of electrons by incident radiation", 3,
         "Photocells function via the photoelectric effect, emitting electrons when illuminated by photons above threshold frequency.", "Photoelectric Effect"),
        ("When an atom loses or gains a charge, it becomes _____",
         "an ion", "an electron", "a neutron", "a proton", 0,
         "An atom that gains or loses valence electrons becomes an electrically charged ion (cation or anion).", "Atomic Structure"),
        ("Which of the following characteristics of a wave is used in the measurement of the depth of the sea?",
         "Diffraction", "Reflection", "Refraction", "Interference", 1,
         "SONAR (Sound Navigation and Ranging) utilizes the reflection of ultrasonic acoustic wave pulses off the seabed.", "Sound Waves"),
        ("Which of the following are produced after a nuclear fusion process?\nI. One heavy nucleus\nII. Neutrons\nIII. Protons\nIV. Energy",
         "I and II", "II and III", "I and IV", "II and IV.", 2,
         "Nuclear fusion unites lighter nuclei into a heavier daughter nucleus with immense liberation of kinetic/radiant binding energy.", "Nuclear Physics"),
        ("Two similar kettles containing equal masses of boiling water are placed on a table. If the surface of one is highly polished and the surface of the other is covered with soot, which of the following observations is correct?",
         "The two kettles will cool down at the same rate", "The polished kettle cools down more quickly by conduction", "The kettle covered with soot cools down more quickly because it is a good radiator of heat", "The kettle covered with soot cools down more quickly by the process of heat convection.", 2,
         "Dull, dark, soot-coated surfaces have high emissivity and radiate thermal infrared radiation far more rapidly than reflective polished surfaces.", "Radiation"),
        ("Total eclipse of the sun occurs when the _____",
         "moon is between the sun and the earth", "sun is between the moon and the earth", "the earth is between the moon and the sun", "ozone layer is threatened.", 0,
         "A total solar eclipse occurs when the Moon completely blocks the solar disc from Earth's view.", "Optics"),
        ("Which of the following pairs of colours gives the widest separation in the spectrum of white light?",
         "Green and Yellow", "Red and violet", "Red and indigo", "Yellow and violet.", 1,
         "Red (longest wavelength, least deviation) and Violet (shortest visible wavelength, greatest deviation) occupy opposite extremes of the visible spectrum.", "Light and Color"),
        ("Which of the following with respect to a body performing simple harmonic motion are in phase?",
         "Displacement and velocity of the body", "Displacement and force on the body", "Velocity and acceleration of the body", "Force acting on the body and the acceleration", 3,
         "By Newton's second law (F = ma), restoring force and acceleration act instantaneously in the same direction with zero phase lag.", "Simple Harmonic Motion"),
        ("A uniform metre rule weighing 0.5N is to be pivoted on a knife-edge at the 30cm-mark. Where will a force of 2N be placed from the pivot to balance the metre rule?",
         "95cm", "5cm", "20cm", "25cm", 1,
         "Weight of rule (0.5 N) acts at center of gravity (50 cm mark), distance from pivot at 30 cm is (50 - 30) = 20 cm. Clockwise moment = 0.5 × 20 = 10 Ncm. Anticlockwise moment = 2 N × x = 10 ⇒ x = 5 cm from pivot.", "Moments and Equilibrium"),
        ("A solid weighs 10.0N in air, 6.0N when fully immersed in water and 7.0N when fully immersed in a certain liquid X. Calculate the relative density of the liquid.",
         "3/4", "4/3", "5/3", "7/10", 0,
         "Relative density = (Weight in air - Weight in liquid) / (Weight in air - Weight in water) = (10 - 7) / (10 - 6) = 3 / 4.", "Archimedes Principle"),
        ("[DIAGRAM: Six's maximum and minimum thermometer showing bulb P, capillary U-tube Q, and upper expansion bulb R]\nThe diagram above shows a maximum and minimum thermometer divided into three portions P, Q and R. Which of the following is true about the respective content of P, Q and R?",
         "Air, alcohol and mercury", "alcohol, mercury and alcohol", "mercury, alcohol and mercury", "Air, mercury and alcohol", 1,
         "Six's thermometer contains alcohol in left bulb P, a thread of mercury in bottom U-bend Q, and saturated alcohol vapor in right bulb R.", "Thermometers"),
        ("The process of energy production in the sun is _____",
         "nuclear fission", "nuclear fusion", "electron collision", "radioactivity decay", 1,
         "Solar thermonuclear energy is generated by proton-proton chain nuclear fusion of hydrogen into helium.", "Modern Physics"),
        ("The particle responsible for nuclear fission in a nuclear reactor is _____",
         "electron", "Photon", "proton.", "Neutron", 3,
         "Thermal neutrons induce nuclear chain fission reactions in fissile fuel isotopes like Uranium-235.", "Nuclear Reactions"),
        ("If the uncertainty in the measurement of the position of a particle is 5 × 10⁻¹⁰m, the uncertainty in the momentum of the particle is _____ [h = 6.6 × 10⁻³⁴ Js]",
         "1.32 × 10⁻²⁴ Ns", "3.30 × 10⁻⁴⁴ Ns", "1.32 × 10⁻⁴⁴ Ns", "3.30 × 10⁻²⁴ Ns", 0,
         "Heisenberg uncertainty principle: Δx Δp ≥ h / (4π) ⇒ Δp = (6.6 × 10⁻³⁴) / (4 × 3.1416 × 5 × 10⁻¹⁰) = 6.6 × 10⁻³⁴ / (6.283 × 10⁻⁹) = 1.05 × 10⁻²⁵ Ns (or h/λ format ≈ 1.32 × 10⁻²⁴ Ns).", "Quantum Mechanics"),
        ("The change in volume when 450kg of ice is completely melted is _____ [density of ice = 900kgm⁻³, density of water = 1000 kgm⁻³]",
         "0.50m³", "0.45m³", "4.50m³", "0.05m³", 3,
         "V_ice = 450 / 900 = 0.50 m³. V_water = 450 / 1000 = 0.45 m³. Change in volume ΔV = 0.50 - 0.45 = 0.05 m³.", "Density and Expansion"),
        ("When impurities are added to semiconductor, its conductivity _____",
         "decreases", "increases then decreases", "increases", "remains constant", 2,
         "Doping introduces extra free electrons or holes into the crystal matrix, greatly increasing its electrical conductivity.", "Semiconductors"),
        ("The process through which free electrons leave the hot surface of hot metal is known as _____",
         "photo emission", "thermionic emission", "photon emission", "electron emission", 1,
         "Thermionic emission is the thermally induced flow of charge carriers from a heated cathode surface.", "Thermionics"),
        ("The production of pure spectrum could easily be achieved using a _____",
         "Triangular prism only", "Triangular prism with two concave lens", "Glass prism with a pin", "Triangular prism with two convex lens.", 3,
         "A pure spectrometer uses a collimating convex lens to parallelize rays, a prism to disperse them, and a telescope convex lens to focus monochromatic wavelengths onto a screen.", "Spectra and Light"),
        ("A short chain is something attached to the back of a petrol tanker to _____",
         "Conduct excess charges to the earth", "Ensure the balancing of the tanker", "Caution the driver when over speeding", "Generate more friction", 0,
         "Electrostatic friction charges build up on fuel tankers; the trailing metal chain discharges static electricity safely to ground.", "Electrostatics"),
        ("A perfect emitter or absorber of radiant energy is a _____",
         "White body", "Red body", "Conductor", "Black body", 3,
         "An ideal blackbody has an absorptivity and emissivity of unity (e = 1).", "Radiation"),
        ("[DIAGRAM: Six identical 2V cells connected in series-parallel with opposing polarities]\nSix identical cells, each of e.m.f 2V are connected as shown above. The effective e.m.f of the cell is _____",
         "4V", "0V", "6V", "12V", 0,
         "Resultant net EMF after accounting for polar opposition is 4V.", "Electric Circuits"),
        ("If a pump is capable of lifting 5000Kg of water through a vertical height of 60 m in 50 mins, the power of the pump is _____ [g = 10ms⁻²]",
         "2.5 × 10⁵ Js⁻¹", "3.3 × 10³ Js⁻¹", "2.5 × 10⁴ Js⁻¹", "1.0 × 10³ Js⁻¹", 3,
         "Power = mgh / t = (5000 × 10 × 60) / (50 × 60 s) = 3,000,000 / 3000 = 1000 W = 1.0 × 10³ Js⁻¹ (or 3.3 × 10² Js⁻¹).", "Work and Power"),
        ("The distance between two successive crest of a wave is 15 cm and the velocity is 300ms⁻¹. Calculate the frequency.",
         "4.5 × 10⁵ Hz", "4.5 × 10² Hz", "2.0 × 10³ Hz", "2.0 × 10² Hz", 2,
         "f = v / λ = 300 / 0.15 = 2000 Hz = 2.0 × 10³ Hz.", "Waves"),
        ("An electric lamp marked 240V, 60 Watts is left to operate for an hour. How much energy is generated by the filament?",
         "3.86 × 10⁵ J", "2.16 × 10⁵ J", "1.80 × 10⁴ J", "3.56 × 10⁵ J", 1,
         "Energy E = Power × time = 60 W × 3600 s = 216,000 J = 2.16 × 10⁵ J.", "Electrical Energy"),
        ("In comparing the camera and human eye, the film of the camera functions as the _____",
         "Iris", "Pupil", "Retina", "Cornea", 2,
         "The light-sensitive photographic film (or digital sensor) in a camera corresponds to the retina of the human eye.", "Optics of the Eye")
    ]

    for idx, item in enumerate(pt5_data, 1):
        q, a, b, c, d, ans, exp, topic = item
        questions.append({
            "id": f"jamb_phy_pt5_{idx:02d}", "subject": "Physics", "topic": topic, "year": "PT. 5",
            "text": q, "a": a, "b": b, "c": c, "d": d, "ans": ans, "exp": exp,
            "label": f"JAMB Physics PT.5 • Q{idx}"
        })

    return questions
